### ISSUE TITLE
pre-select all nodes change state opened to true

### ISSUE THREAD

**Issue by teo89** [vakata/jstree#1001]
I have a tree with plugin checkbox and  i have the follow problem:  When i pre-select all the nodes of the tree then the state opened of the tree is always opened i set opened : false but nothing change. How can i select on the load all the nodes of the tree and opened stays false?(javascript code you can see in  : http://jsfiddle.net/9cog88f8/)

**Comment by vakata** [comment]
The demo you provided does not work. Anyway - the core.expand_selected_onload option is what you need: http://jsfiddle.net/DGAF4/339/

**Comment by teo89** [comment]
thanks i will check it
