### ISSUE TITLE
How to add a marker line?

### ISSUE THREAD

**Issue by Lusito** [vakata/jstree#1002]
I've seen older versions of jstree adding a line below or above the marker to better highlight where an item would be inserted. How can I get this working with the current version of jstree ?
![Marker Line](https://camo.githubusercontent.com/ee4b7b37bfc30a9ddcb1646e76762afef6ac2626/687474703a2f2f692e696d6775722e636f6d2f71787a437262662e706e67)

as far as I can see, there is no class to differentiate between an insert into and above/below, which is needed in order to hide the line when dropping into a node.

**Comment by vakata** [comment]
You can use the `core.check_callback` and set it to a function. 
```js
check_callback : function (operation, node, par, pos, more) {
  if((operation === "move_node" || operation === "copy_node") && more && more.dnd) {
     // use more.pos to update your own marker
  }
}
```

Best regards,
Ivan

**Comment by Lusito** [comment]
thanks, works :)
