### ISSUE TITLE
Wholerow does not work with dnd

### ISSUE THREAD

**Issue by Lusito** [vakata/jstree#1003]
Try dragging a row or dropping on a row outside of the text element. It doesn't work.

**Comment by vakata** [comment]
Use the latest code from repository and the `dnd.large_drop_target` option. Here is a demo:
http://jsfiddle.net/DGAF4/340/

Best regards,
Ivan

**Comment by Lusito** [comment]
Thanks, this works for dropping, but not for dragging.

**Comment by vakata** [comment]
Thanks for the pointer, I will add a setting for that too.
