### ISSUE TITLE
xml_data does not work with IE, any version

### ISSUE THREAD

**Issue by born2net** [vakata/jstree#1004]
xml_data does not work with IE, any version
works find in FF, Chrome, but no good in IE :(

**Comment by born2net** [comment]
u can look here for issue: 
http://www.digitalsignage.com/_html/video_tutorialsv2.html

the does comes back but does not get processed in IE

**Comment by vakata** [comment]
Sorry, but jstree v.1 is no longer supported. v.3 is a lot more stable and has been out for over an year.
