### ISSUE TITLE
IS the efficiency of populating a tree with JSON tree structure better than Scrambled JSON?

### ISSUE THREAD

**Issue by saikrishna2deep** [vakata/jstree#1006]
Hi,

Currently, I'm using this method of populating my tree

`$('#using_json_2').jstree({ 'core' : {
    'data' : [
       { "id" : "ajson1", "parent" : "#", "text" : "Simple root node" },
       { "id" : "ajson2", "parent" : "#", "text" : "Root node 2" },
       { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1" },
       { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2" },
    ]
} });`

I have huge lists. Around 3.2k inputs. I was wondering if it is more efficient when a child structure is given for the jsTree? Like

$('#using_json').jstree({ 'core' : {
    'data' : [
       'Simple root node',
       {
         'text' : 'Root node 2',
         'state' : {
           'opened' : true,
           'selected' : true
         },
         'children' : [
           { 'text' : 'Child 1' },
           'Child 2'
         ]
      }
    ]
} });

**Comment by vakata** [comment]
Yes, the latter is faster.
You can also try disabling `core.worker` in your config - that will result in faster rendering, but will block the UI - see if it is OK for you.

Best regards,
Ivan

**Comment by saikrishna2deep** [comment]
Does it make a huge difference in load time, say for a list with 2k entries?

**Comment by vakata** [comment]
Test for yourself with your data. My tests are with 30.000 nodes and usually the tree is rendered under 5 seconds, disabling core.worker drops the time in half, but freezes the UI.
