### ISSUE TITLE
create_node creates node and successive calls insert at the same position (pos 'last' is not updated/working?)

### ISSUE THREAD

**Issue by muenalan** [vakata/jstree#1008]
Funny,

http://jsfiddle.net/v50geunb/

Even changing/omitting the "pos" argument does nothing.

Thx,
M!

**Comment by vakata** [comment]
You are calling create_node before the tree is ready. Here is a fixed demo:
http://jsfiddle.net/v50geunb/1/

**Comment by muenalan** [comment]
Thx !

I wonder why this was not mentioned in the demos ?
