### ISSUE TITLE
Getting position/index of a node

### ISSUE THREAD

**Issue by steeeeeve** [vakata/jstree#1009]
I'm using jstree in order to reorder a list of elements serverside.  On the move node event I can get the position of the newly placed node.  However is there any way to get the current position of a node outside of this?

**Comment by vakata** [comment]
Yes, but that is not maintained as a static property, as it will be too expensive.
```js
var inst = $('#tree').jstree(true),
    node = inst.get_node('ID_HERE'),
    parent = inst.get_node(node.parent);
alert($.inArray(node.id, parent.children));
```

**Comment by niejian** [comment]
thank you so much ,it helps me a lot 来自我的华为手机-------- 原始邮件 --------主题：Re: [jstree] Getting position/index of a node (#1009)发件人：Ivan Bozhanov 收件人：vakata/jstree 抄送：Yes, but that is not maintained as a static property, as it will be too expensive.

var inst = $('#tree').jstree(true),
    node = inst.get_node('ID_HERE'),
    parent = inst.get_node(node.parent);
alert($.inArray(node.id, parent.children));
