### ISSUE TITLE
$.jstree.reference(DOMElement) returns wrong instance

### ISSUE THREAD

**Issue by duzun** [vakata/jstree#1013]
Here is my usecase:

I have a UI with two panels, with jstree in each of them.
All jstree nodes have IDs from data source.
Both jstree instances display the same set of nodes, which means each node id (and thus DOM id) is repeated twice in the document.
While performing Drag&Drop on second panel, jstree moves my node to the first panel.
I could track the issue up to `$.jstree.reference(DOMElement)`. It first takes id of needle (which is `DOMElement` in my case), then fetches the element by id with `$('#'+id)`. This way jstree finds first DOM element with given id, which is not the original element passed to `$.jstree.reference(DOMElement)`.

**Comment by duzun** [comment]
I rewrote [$.jstree.reference(needle)](https://github.com/duzun/jstree/commit/68e2ff6c2a3243c925fc86007831513df4465b83?diff=split#diff-953c4378bac043afa01fe263095d6724R169), trying to cover as many cases as possible.
I also added a warning in the case it finds more then one jstree instance for needle (it took me few hours to find this issue, so it would be helpfull to have a warning in the console).

@vakata If you like my version I'm glad to make a PR.

**Comment by vakata** [comment]
Thanks for dedicating time to track this down - it was a huge help. I will go over your fix and let you know if I will merge it. For now the fix I added will do the trick. I am not sure how type checking will affect performance.
Best regards,
Ivan

**Comment by duzun** [comment]
I made use of `$.type` just to ensure the algorith is clean and easy to read and refactor.
I also try to not change the original behaviour of the method, so that it works the same way in all other contexts except the one from this issue.

Thanks for a great library :-)
