### ISSUE TITLE
.move_node(foreign_node) should work on it's own node (by ID or clone)

### ISSUE THREAD

**Issue by duzun** [vakata/jstree#1014]
While moving a node from one jstree instance to another, sometimes same node object gets inserted into the destination jstree, resulting in shared properties between two different jstree instances for same node.
Because of this issue I get some errors and missbehaviours in the original jstree instance related to the likned node.

I made a small change in `.move_node()`, that seems to fix this issue, but I'm not sure about other side-effects:

[L3702](https://github.com/vakata/jstree/blob/master/src/jstree.js#L3702) 
```javascript
obj = obj && obj.id ? obj : this.get_node(obj); // I replaced this line
// with:
obj = this.get_node(obj); // this one
```

**Comment by vakata** [comment]
I cannot reproduce the issue, but the above can not be used as is. The idea is that when a node is foreign it comes with its own ID, if `get_node` is called one of two issues will happen:
1) If there is a node with the same ID in the destination tree that node will be moved instead of the foriegn one
2) If there is no node with the same ID in the destination tree the move will fail.

Both of the above are not acceptable. 
From what I understand maybe the problem comes from the way you are invoking the `move_node` method? Invoking `move_node` with a foreign node, especially provided that the same ID exists in the destination tree can lead to problems, because of those lines:
```js
old_ins = obj.instance ? obj.instance : (this._model.data[obj.id] ? this : $.jstree.reference(obj.id));
is_multi = !old_ins || !old_ins._id || (this._id !== old_ins._id);
```
In the above case (when you are moving a foreign node, whose ID is already in the destination tree), please provide an `instance` property on the node object, there is no other way for jstree to reliably determine which node to use (this is what the DND plugin does).
```js
instance.move_node({
  id : 1,
  instance : the_source_instance,
  ...
})
```

If I misunderstood - please let me know and I will reopen the issue.

Best regards,
Ivan

**Comment by duzun** [comment]
In my setup I have two trees side by side from same data source, which means I have nodes with  the same id in both trees.
I got into this issue by dragging from one tree to another.
Here is my scenario:
-   Both trees load data dynamically as nodes are open
-   Node B is child of node A
-   Node A is open on right-side tree, but close on left-side tree (whch means left-side tree doesn't know anything about node B yet)
-  I move node X from left tree to right tree, and place it under B.
-  At this point node X moves to B on right-side tree, but X on left stays in place and I see and error in console at [L3592](https://github.com/vakata/jstree/blob/master/src/jstree.js#L3592) -  'Cannot read property 'children_d' of undefined'

This is due to the fact that node object X from left tree has been modified in .move_node() called on right-side instance, and now it's `.parents` property contains a new chain of parents from right-side tree that are missing on left (B is not laoded on left yet, cause A is closed). Even if I don't get the error in the console, (say A is open on left), there is something wrong happening if `.delete_node()` on left does stuff with `.parents` from right.

**Comment by duzun** [comment]
I have to add that is doesn't ahppen all the time. In my tests B had one more child C, and I notice a relation between DND and the issue:
-  A is closed on both sides (contains at least one child node B)
-  I drag X from left to right, and drop X into A before A loads & opens.

**Comment by vakata** [comment]
Thanks, I was able to reproduce, I am on it.

**Comment by duzun** [comment]
I found another quick fix.
Clone `foreign_node` in `.move_node(foreign_node)`:
```javascript
obj = obj && obj.id ? $.extend(true, {}, obj) : this.get_node(obj);
```

With this I can't reproduce the issue.

**Comment by vakata** [comment]
Sorry, cloning is not an option, as with the previous idea - it will cause a lot of issues (aside from the performance penalty, which will be the minor problem).

Everything should be fine with the latest commit. It is a rewrite of the foreign move / copy operation and is generally cleaner.

Best regards,
Ivan

**Comment by duzun** [comment]
I just tested your last commit and the issue seems to be fixed.

Thanks

**Comment by duzun** [comment]
After last commit I get another error.
When I move some node to the top-most one, I get "Uncaught TypeError: Cannot read property 'parents' of undefined" in [L6947](https://github.com/vakata/jstree/blob/master/dist/jstree.js#L6947)

**Comment by vakata** [comment]
http://vakata.eu/jstree/ - please provide steps to reproduce.

**Comment by duzun** [comment]
I'm not able to reproduce it here.
Even in my working setup it doesn't always trigger the error, but it happens very often.
If it happens, I can't move to that node any more until a refresh.
I'll try to find steps to reproduce this.

**Comment by vakata** [comment]
Please describe the steps and share your types config - it must be relevant. By describe I mean - grab a node from tree A, and drop it above the first root of tree B, then try dragging the newly dropped node, etc. Something like that so that I can try reproducing.

**Comment by vakata** [comment]
OK, I got it. It really is the reference as you suggested - the types plugin is checking for the foreign node in the local node collection. But since it is quite late here I prefer to fix this after resting, so I will fix this first thing tomorrow - hope it is not too late.

**Comment by duzun** [comment]
I still can't find the steps to reproduce.
Here is my config:
```javascript
$tree.jstree({
  'core' : {
    'themes' : { 'stripes' : true }
  , 'data' : function (node, done) { ... }
    , 'check_callback' : function(){ ... }
    , 'multiple': true
  }
  , 'plugins' : ['dnd', 'contextmenu', 'search', 'types', 'wholerow']
  // Plugins settings
  , 'search': { ... }
  , 'dnd': {
    'always_copy': false
    , 'copy': true
    , 'drag_selection': true
    , 'is_draggable': function (nodes) { ... }
  }
  , 'types' : {
      '#' : {
        'valid_children' : ['root', 'trash']
      },
      'root' : {
        'valid_children' : ['dir', 'tab']
      },
      'trash' : {
        'valid_children' : ['dir', 'tab']
      },
      'dir' : {
        'valid_children' : ['dir', 'tab']
      },
      'tab' : {
        'max_children' : 0,
        'max_depth' : 0,
        'icon' : 'glyphicon glyphicon-file',
        'valid_children' : []
      }
  }
  , 'contextmenu': {
      'items': function(){ ... }
  }
})
```

I'm basically draging `dir` onto `dir` and get the error, even in one tree (on right tree so far).
The error logs multiple times, as I drag the `dir` over other `dir` nodes, which makes me think it has to do with `types`, as you mentioned.
Unfortunately I'm new to this library and don't know the inner working of it.

Thank you @vakata again for your support and quick responses.

Have a good night!

**Comment by duzun** [comment]
It looks like the issue is gone.

I decided to not use `types` plugin and replaced it with a custom `check_callback()` function, which does exactly what I need. Without the `types` plugin the issue were gone. Now I enable back `types`, use same old configuration, and can't reproduce the issue any more.

**Comment by vakata** [comment]
Great, thanks. Sorry of the delay and thank you for your patience.
Best regards,
Ivan
