### ISSUE TITLE
Bug in Checkbox pugin whit (checkbox.whole_node : false)

### ISSUE THREAD

**Issue by eDitore** [vakata/jstree#1015]
When Checkbox plugin is set like in this example: http://jsfiddle.net/DGAF4/352, paramter checkbox.whole_node : false  works incorrectly. After selecting all the checkboxes and clicking on anywhere on random node, the rest of checkboxes become unchecked (they should remains unchanged).

**Comment by vakata** [comment]
You misunderstood the setting - `whole_node` as `false` means that the rest of the node behaves as normal selection and the checkboxes are used for multiselection. So clicking on a node will select it and deselect all other nodes. This is the correct behavior. 

Take a look at the other checkbox config options - I am sure you will find how to create the desired behavior, if not - feel free to ask. 
Maybe you need to set `keep_selected_style` to `false` and keep `whole_node` as `true`? Or perhaps set `tie_selection` to `false` but use that with caution.

Best regards,
Ivan

**Comment by ULazdins** [comment]
What is the point of such behaviour? It looks somehow unintuitive to me.

Anyway, in my situation I'm looking for a way to have two types of interaction with the tree:
a) when checkbox is clicked, add the node to selection
b) when the click is performed anywhere else on the node, I wand to do something else (show additional info about node), but - without including it in the selection.

Can checkbox plugin be configured to work in a such way?

Thanks,
U.

**Comment by vakata** [comment]
Well, it was requested, made sense at the time (the same behavior is present in some operating systems when dealing with lists).
Anyway, for what you need, I'd set whole_node to false and create a plugin with a few lines overriding the select_node function, or you could bind to click events on .jstree-anchor nodes before creating the tree and stopImmediatePropagation if it was not the checkbox that was clicked, which would achieve exactly what you need.

Best regards,
Ivan

**Comment by ULazdins** [comment]
I haven't had experience with such a pattern, so it was confusing at first.

Thank you for the suggestion!

BR,
U.

**Comment by jsteerv** [comment]
Hi thanks for the suggestion, i need to do the same, but i cant find the way.
I am trying to put this:

        $('.jstree-anchor').bind("click", function () {
                alert(1);
        });

Before creating the tree, but wherever i put it, the binding is ignored... i am not an expert, but i really want to make this work, can you give me some directions?

Thanks in advance!

**Comment by vakata** [comment]
Use event delegation, do not bind on each node as jstree will redraw them:
```
$('#tree').on('click', '.jstree-anchor', function () { ... });
```

Best regards,
Ivan

**Comment by Nicky-Agarwal** [comment]
Hi Ivan

I did try the above method for seperating the click of checkbox "event" and clicking anywhere on the Node "event" but its still failing.

myTree.on('click','.jstree-anchor',function (event, data) {
              var href = data.node.a_attr.href;
              document.location.href = href; 
              //var target="_blank";
              $scope.$digest();
            });

This is how my code looks.Can you please help me with this?

**Comment by Nicky-Agarwal** [comment]
And also can you tell me a way through which one can make sure that if on clicking anywhere on the node,I want to open a new page ,so that happens in the new tab

**Comment by jrief** [comment]
@Nicky-Agarwal I'm encountering the same problem using version 3.3.1. Have you been able to solve it?

**Comment by BorisKrones** [comment]
Same issue. Is there really no "one line solution" to avoid checkbox de-/selection on row (children) click?

**Comment by jrief** [comment]
After searching for it, I found this fiddle: http://jsfiddle.net/dhskgky0/3/
