### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by tux-** [vakata/jstree#1016]
When holding down shift / ctrl / alt and using the keyboard as a tree navigation tool, it would be nice if jstree does not catch the events, so they can be bound to other stuff. eg:

```$(document).on('keydown', function (e) {
if ((e.ctrlKey == true) && (e.keyCode == 37)) {
selectLeftPhane();
}
});```

**Comment by vakata** [comment]
I do not see anything being prevented: http://jsfiddle.net/DGAF4/353/

Best regards,
Ivan

**Comment by tux-** [comment]
The problem is that the tree also picks up on the ctrl + arrow key, where that should be able to perform another operation without also affecting the tree. Like alt + forward / backward is normally bound to history back and forward and if you there have events to check if there are unsaved changed before performing that action, the tree will open a node when clicking alt + forward.

Sorry if I explain badly.

regards Tux Solbakk :)

**Comment by vakata** [comment]
I see what you mean - sorry for closing prematurely - I will skip all the handling if modifier keys are pressed and are not applicable. This is a part of the ARIA tree spec I did not find, but it makes perfect sense - thanks.

**Comment by tux-** [comment]
Tested and works great! Thanks a lot!

regards Tux Solbakk
