### ISSUE TITLE
How to use a custom sprite for nodes?

### ISSUE THREAD

**Issue by saikrishna2deep** [vakata/jstree#1020]
Hi,

As of now, I've only an option to use the sprite that you offer or else, a custom file icon by doing `item.icon = "images/myimg.png"`. But the problem is, when there are multiple nodes, there are multiple file requests.

Lets say,I've the following file extensions '.srt','.avi','.mp4' etc. each needs to have a different icon from my fileext-sprite.png. I know how to add icons with custom image URLs but I fail to see how I can use the same setting for using a sprite with a specific background position.

Thanks,
Sai

**Comment by vakata** [comment]
Please read the docs in this very repo: 
https://github.com/vakata/jstree#the-required-json-format
Or on jstree.com:
http://www.jstree.com/docs/json/

> To change the icon of the node use the `icon` property. Specifying a string containing a `/` will display that image as the node icon. Using any other string will apply that class to the <i> element that is used to represent the icon. You can use boolean `false` to make jsTree render the node with no icon.

So basically you put this for `icon`:
```js
"icon" : "my-icons my-icons-rtfm"
```
And somewhere in the CSS you put the definition:
```css
.my-icons { background-image:... }
.my-icons-rtfm { background-position:... }
```
