### ISSUE TITLE
.refresh() effects .on('changed' ?

### ISSUE THREAD

**Issue by saikrishna2deep** [vakata/jstree#1021]
`$('#tree')
     .on('changed.jstree', function (e, data) {
// my function
}
     .jstree({
            'core': {
                'check_callback': true,
                    'data': function (node, cb) {
                    cb.call(this, treeJSON);
                }
});
input.onchange = function (e) {

// treeJSON gets updated dynamically here

var tree = $('#tree').jstree(true);
tree.refresh();    

            }`

My Problem.

So, my treeJSON always has a state `{'selected':true}`. But this makes the `.on('changed')` portion to loop multiple times when the tree refresh occurs (I'm assuming that everytime the refresh on tree with new JSON data happens, it recognizes it as an onchange event).

When I remove the selected state. It seems to be just fine when I refresh. The fucntion in `on.changed` runs just once.

What I'm trying to get:

So, In my treeJSON, I already mention which node to be selected.When I refresh it, I just want it to update the tree with this instead of it triggering it an `on.change` event. I'm reserving the `on.changed` just for noting down the selected nodes and nothing else.I wish to keep it that way.

Thank you,
Sai

**Comment by vakata** [comment]
Sorry, this is the way jsTree works - the state is always restored after a refresh (unless you explicitly specify not to restore it as stated in the docs, but I doubt that is what you need) and the selected nodes are a part of that state. To me it seems your logic is off, but I won't go into that.

Anyway - you have an easy solution - do not process the `changed.jstree` event from the moment you call refresh to the moment `refresh.jstree` is triggered.
```js
$('#tree').on('changed.jstree.myevent', function (e, data) { ... your code ... });
var tree = $('#tree').jstree(true);
$('#tree').off('.myevent');
tree
  .on('refresh.jstree', function () {
    $('#tree').on('changed.jstree.myevent', function (e, data) { ... your code ... });
  })
  .refresh(); 
```

Of course you could use a simple boolean variable in your function and not this `on` / `off` technique. 

jsTree provides you with all the necessary information and events - it is up to you to decide how to use them.

Best regards,
Ivan

**Comment by saikrishna2deep** [comment]
And where exactly am I loading the jsTree itself with my treeJSON data?

**Comment by vakata** [comment]
I just modified your own code - everything else stays the same. Working with second example I gave, and:
* add `var process = true;` at the top of your code
* wrap your `changed.jstree` handler with `if(process) { ... handler code here ... }`
* add `process = false` right before invoking refresh
* add `$('#tree').on('refresh.jstree', function () { process = true; });`

Obviously you are loading your tree by setting `core.data` to a function, and the `refresh()` call will invoke that function - this is your own code, after all. If you don't understand the above, I really can't help you further.

Regards,
Ivan

**Comment by saikrishna2deep** [comment]
Sorry for the late reply. I understand what you said. I've given it a shot but still the selected state doesn't seem to stay after a refresh.

Please have a look at the fiddle below.

http://jsfiddle.net/johnjacob/z6cLb7er/2/

**Comment by vakata** [comment]
In this use case there is no way for jstree to restore the state, as there is no folder selected initially. In your case you should create the tree after the folder is selected, then the state will be restored.

Best regards,
Ivan

**Comment by saikrishna2deep** [comment]
I've already added the `checked:true` and `selected:states` in `var checkstate`. Only 1 folder is selected whose parent is `'#'`

it's given by this condition: `if (item.parent == "#") item.state = checkstate;`
