### ISSUE TITLE
[Doubt] Search in the tree with ajax

### ISSUE THREAD

**Issue by Wivison** [vakata/jstree#1022]
Hi Ivan, i'm having some difficulty in implementing a search using ajax and assemble the tree. My scenario: I have a tree over 500 records, they are loaded via the lazy loading (on demand), but must allow a search by name. So I created a method that returns the records containing the name searched along with their parents (recursively until the root). Set up the method in the ajax property search plugin. But is not working. Only shows records that were previously disclosed. It's like the search, ignored the tree coming from the server. Optionally also important that parents appear.

Follows the code:

```javascript
//jsTree config
$("#divJsTree")
            .jstree({
                "core": {
                    "expand_selected_onload": false,
                    "multiple": false,
                    "strings": { 'Loading ...': 'Carregando ...' },
                    "data": {
                        "url": "/GetTree",
                        "dataType": "json",
                        "contentType": "application/json;",
                        "data": function (node) {
                            return { "id": node.id };
                        }
                    }
                },
                "plugins": ["search"],
                "search": {
                    "show_only_matches": true,
                    "ajax": function (str, callback) {
                        $.ajax({
                            "url": "/Search",
                            "dataType": "json",
                            "contentType": "application/json;",
                            "data": { 'str': str }
                        })
                            .done(function (data) {
                                data = data.d;
                                callback(data);
                            });
                    }
                }
            });

        var to = false;
        $('#input').keyup(function () {
            if (to) { clearTimeout(to); }
            to = setTimeout(function () {
                jsTreeReference("divJsTree").search($('#input').val());
            }, 250);
        });
```

I thank you attention!

**Comment by vakata** [comment]
The only reason the search.ajax option would not work is if the response format is wrong. When you invoke `callback(data);` what does `data` contain? 

It should be an array of parent node IDs, like so:
```js
[ "root1", "some-other-id" ]
```

Here is an example: if you are searching for "asdf" and you have this ID : name structure:
```
root1 : "Root Node"
  child1 : "Some other node"
    child2 : "asdf"
```
Your response (the `data` you pass to the callback) should be:
```js
["root1","child1"]
```
jsTree will load those two nodes (if not already loaded), and perform the client-side search, which will match the "child2" node (since it will be loaded).

Please let me know if you need any more help.

Best regards,
Ivan

**Comment by Wivison** [comment]
Hi again,

Ivan, the return was wrong, but already corrected. But was not cool, because as I said my tree has many records distributed at various levels and to search, and the word has many occurrences in the tree, are made many requests to the server to load the nodes and multiplies it by the number of users!

It is possible, as I will on the server to get the id of the parent nodes, instead of bringing the id, can bring a new tree with the records containing the word along with their parents and replace the current without losing settings, eg lazzy loading?

I thank you attention!

**Comment by vakata** [comment]
Please take a look at the latest code in this repo, it features a "massload" plugin. It can load multiple nodes at various levels using a single request. The docs are in the code:
https://github.com/vakata/jstree/blob/master/src/jstree.massload.js#L24

Search and state benefit from including this plugin (or any other plugin that calls `_load_nodes`)

Let me know if you have further questions.

Best regards,
Ivan

**Comment by vbudithi** [comment]
Hi Ivan,

I have a doubt regarding this. I have been searching for this from many days, but nowhere i found the solution. While i was searching for this, I found this post and I felt that this would be a good idea to ask you. If you have an idea of "How to load a CSV file format using NodeJs and ajax on to the JS tree"

Can i get the code for both of them ?

Thanks in advance

**Comment by vbudithi** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by charlesgetup** [comment]
> The only reason the search.ajax option would not work is if the response format is wrong. When you invoke `callback(data);` what does `data` contain?
> 
> It should be an array of parent node IDs, like so:
> 
> ```js
> [ "root1", "some-other-id" ]
> ```
> 
> Here is an example: if you are searching for "asdf" and you have this ID : name structure:
> 
> ```
> root1 : "Root Node"
>   child1 : "Some other node"
>     child2 : "asdf"
> ```
> 
> Your response (the `data` you pass to the callback) should be:
> 
> ```js
> ["root1","child1"]
> ```
> 
> jsTree will load those two nodes (if not already loaded), and perform the client-side search, which will match the "child2" node (since it will be loaded).
> 
> Please let me know if you need any more help.
> 
> Best regards, Ivan

The above response data (array) is wrong. I have experienced this issue. If response data is **["root1","child1"]**, then the jstree could not load and open the dir and show the search result. The correct response data is **["root1","root1/child1"]**. Do not return the folder name, return the folder path. 

Hope this could help someone who has still used this library (version is 3.3.15).
