### ISSUE TITLE
node with maxlength on create or rename

### ISSUE THREAD

**Issue by alissonbarison** [vakata/jstree#1023]
is there any way to limit the amount of characters the user can enter when inserting or renomar one node

**Comment by vakata** [comment]
No, sorry that is not possible with a setting. You can build your own code of course:
```js
$("#tree").on("keydown", ".jstree-rename-input", function (e) { ... });
```

Best regards,
Ivan

**Comment by alissonbarison** [comment]
thank you, it was what I needed
