### ISSUE TITLE
Can't set title attribute on .jstree-themeicon via jstree API

### ISSUE THREAD

**Issue by slominskir** [vakata/jstree#1024]
I'd like to set the title attribute on the .jstree-themeicon elements depending on the type of node (this is so users get a browser generated tooltip on hover).   The work-around is to wait until the tree is loaded and then use jquery to splice the titles in.  This is not ideal.  Here are some things that I tried:

1. Tried using HTML instead of JSON to generate nodes.   The "i" element and it's title are erased and replaced with a new "i" element.
2. You can set attributes for the "li" and for the "a", but that isn't the same as the "i".

**Comment by vakata** [comment]
Sorry, this is not possible with the built-in functionality. For the time being the cleanest way to achieve this is to add a small plugin (examples are in the src/misc.js file). 
I will think of adding sucha plugin to the core.

**Comment by aj-dev** [comment]
@vakata as far as I understand, there's no way to add custom HTML to the generated tree `<li></li>` elements? It would be nice to have a possibility of appending `<span></span>` to the LI that would hold some extra info about the node, eg. description, warning, etc. So something like a custom template. Would it be feasible to expose such functionality in a plugin interface?

**Comment by vakata** [comment]
No, sorry, this would mean way too much config options, etc. There is only one way to add additional DOM elements to all rendered nodes - via a plugin (aside from having the node text as HTML, but that may not always be enough).
There are a couple of examples here: https://github.com/vakata/jstree/blob/master/src/misc.js
Tell me if you need help with creating a plugin.

Best regards,
Ivan
