### ISSUE TITLE
state.selected set too early

### ISSUE THREAD

**Issue by istr** [vakata/jstree#1025]
The state ```selected``` is set too early. There is no chance to see if a node already was selected before.
Even if you replace the "conditional select" plugin (cf. ```misc.js```) with this code
```js
    // conditional select
    (function ($) {
      'use strict';
      $.jstree.defaults.conditionalselect = function () { return true; };
      $.jstree.plugins.conditionalselect = function (options, parent) {
        // own function
        this.select_node = function (obj, suppress_event, prevent_open, e) {
          if(this.settings.conditionalselect.call(this, this.get_node(obj))) {
            parent.select_node.call(this, obj, suppress_event, prevent_open, e);
          }
        };
      };
    })(jQuery);
```
The ```conditionalselect``` function will always "see" ```state.selected === true``` even if the node about to be selected was not selected before. The jstree logic should set the flag and add the node to the selection array *after* ```select_node``` is triggered and *before* ```activate_node``` is triggered, such that you could hook on both (pre- and post-selection).
A typical use case is to start renaming if a selected item is clicked again when already selected.

**Comment by vakata** [comment]
I believe this isn't true: http://jsfiddle.net/DGAF4/363/
Open the DEV console and observe - on first click you will get false / true, and on a subsequent click you will get true / true - exactly as expected.

Maybe you are dealing with a reference that you are inspecting after the fact?

If there is something else you need - please let me know, I can help you modify the conditionalselect plugin, but I am closing this, as it simply is not true (as you can see in the above demo).

Best regards,
Ivan

**Comment by istr** [comment]
Ok, thanks for the fiddle. After purging jstree and reinstalling it worked, cf. http://jsfiddle.net/yj7bd5cp/18/
However, this fiddle shows a strange FF specific bug with drag and drop (FF 36.0 Linux). If you set ```overflow:hidden``` on ```html``` then the draggable helper item will be offset when the jstree overflows and is scrolled to the bottom. Everything works like expected in Chrome. Any idea why?
![shot-jstree-dnd-ff-36 0-scrolldown](https://cloud.githubusercontent.com/assets/4235579/6483730/b245b2e2-c274-11e4-915b-39d7b36fad3b.png)
![shot-jstree-dnd-ff-36 0-scrollup](https://cloud.githubusercontent.com/assets/4235579/6483734/bd911ac4-c274-11e4-8339-6330eba505a9.png)

**Comment by vakata** [comment]
No, sorry, absolutely no idea. I will try to reproduce this and let you know if I can fix it.
