### ISSUE TITLE
check_node.jstree callback not working

### ISSUE THREAD

**Issue by npearson72** [vakata/jstree#1028]
Hi,

Can you please review this jsfiddle... am I doing something wrong or is this a genuine bug?

https://jsfiddle.net/2oprjpgj/3/

**Comment by cccvvv2012** [comment]
It said http://www.jstree.com/api/#/?q=.jstree%20Event&f=check_node.jstree
only if tie_selection in checkbox settings is false
see working demo
https://jsfiddle.net/2oprjpgj/9/

**Comment by npearson72** [comment]
Ah, thank you!
