### ISSUE TITLE
cascade: 'up' does not select root node

### ISSUE THREAD

**Issue by npearson72** [vakata/jstree#1029]
Please see screenshot for my data structure. When I click on a deeply nested child, all of his parents are selected except for the root.

Is there a trick to this?
![screen shot 2015-03-07 at 7 18 04 pm](https://cloud.githubusercontent.com/assets/1323414/6544320/01c6a1b4-c4ff-11e4-8b8d-705aa78d43ef.png)

**Comment by vakata** [comment]
Sorry, you will have to provide a demo for this. Maybe you misunderstood this option, take this fiddle for example: https://jsfiddle.net/2oprjpgj/10/
When checking "asdf", only its parent "child 1" will be checked, not the root node, because Child 2 is not selected. "up" means if all siblings are selected - select the parent, and then check its own level, and so on.
There is no setting that will select parents that only have a few of their children checked. If you want that - add a "changed.jstree" or "select_node.jstree" handler and do it manually - it will take 2-3 lines of code.

Best regards,
Ivan

**Comment by npearson72** [comment]
I see now. Thank you. BTW, on a different topic (I didn't want to pollute your issues with more questions) are there any plans to allow checkboxes to be native dom elements rather than sprite images?

**Comment by vakata** [comment]
Yes, there is a plugin, that is not bundled, but is in `src/misc.js` called `realcheckboxes`. 

You can read up on it in the groups page, but long story short - if it is visuals you are after, it will do the job, if you want to submit a form - it won't work, as only visible nodes are in the DOM, any nodes under a closed parent are not in the DOM, so form submissions will not be reliable.

Best regards,
Ivan

**Comment by npearson72** [comment]
Ah, thanks Ivan. l gave it a try, and while the native ones appear, for some reason they don't display the checkmark. Otherwise they function... the dom element is displayed... but clicking does not change the checkbox state to appear checked.

I just pasted the code from misc.js into dist/jstree.js right?

**Comment by vakata** [comment]
The code needs to be in the page, copying inside another file will work, adding a separate script tag will work too. I will check later today and let you know.

**Comment by npearson72** [comment]
Thanks. Please let me know.

**Comment by vakata** [comment]
I just tested - adding misc.js to the page and listing both `checkbox` and `realcheckboxes` plugins in the `plugins` config option resulted in a visible and working checkbox. 
Maybe you did not add the `checkbox` plugin as well as `realcheckboxes`?

**Comment by npearson72** [comment]
I'll try again tonight and will let you know. Thanks for all the help.

**Comment by npearson72** [comment]
I think I discovered the issue. It does not work with: `tie_selection: false`

**Comment by npearson72** [comment]
Hi Ivan, sorry to bother you again. But did you even happen to check on this? I mean, were you able to reproduce the the reachceckboxes problem with tie_selection set to false?

If you like, I can open an actual issue for it?

**Comment by vakata** [comment]
There is no issue with it: `realcheckboxes` is a demo plugin, it was never designed to work with `tie_selection` set to `false`. 

It is also not part of jstree per se, it is just a demo. 
You can build on top of it and add support for `tie_selection : false`, if you decide to do that - I would be very grateful if you created a pull request.

If I get the time some day soon I will add support myself, but no need to add an issue - it is a demo piece of code, as such it is not supported - just demonstrates how to build plugins. It is not part of jstree. Anyone is welcome to use it of course if it suits their needs.

If you do not want to add support yourself I will let you know when I get around to adding it, but I doubt it will be in the next few days.

Best regards,
Ivan

**Comment by npearson72** [comment]
I'd love to, but I'm not good enough with js. I'm a rails guy :-)

**Comment by vakata** [comment]
OK, I will let you know when I get round to it myself.

Best regards,
Ivan

**Comment by vakata** [comment]
@npearson72 you can find the fixed `realcheckboxes` plugin in the repo. It should now work properly with `tie_selection : false`.

**Comment by npearson72** [comment]
Sweet, it works! Thank you Ivan! I love this library!

**Comment by damianprzygodzki** [comment]
Why isnt it documented? I can't see the sense of having only visual checkbox plugin.

**Comment by vakata** [comment]
A lot of people do find sense in using this plugin, I am sorry you do not feel the same. 

@damianprzygodzki, my guess is you are trying to submit a form? I usually create a hidden element and populate it with the value of ```instance.get_top_checked()``` as most of the time - this is what I actually need (submitting children of selected parents rarely makes sense). I hope this helps at least a bit.

**Comment by damianprzygodzki** [comment]
@vakata Yeah, but populating the changes to hidden inputs is so complicated, because the selection property is filled with only js-tree-generated identifiers - that doesnt have sense with actual data in nodes. So you have to mess with your DOM always you want to populate changes.

Once you render real checkboxes we can left it and let it work its own way. On the otherside i can't find reason for using fake checkboxes.

**Comment by vakata** [comment]
@damianprzygodzki the selection property is filled with the IDs of your nodes, jstree only generates those IDs if you did not supply them. So once you have populated your tree properly all the code you need is this:
```js
$('#your-tree').on('changed.jstree', function (e, data) {
    // you could of course generate a lot of inputs and avoid using a separator
    $('#your-input').val(data.instance.get_top_checked().join(','));
});
```

The reason for not using real checkboxes is that a lot of users use huge trees (tens of thousands of nodes) and having those all in the DOM at the same time usually means a huge performance problem. 

As for the solution - once again - either populate the tree with values that actually make sense (use your own IDs and do not rely on jstree to generate node IDs for you) or combine the realcheckboxes demo plugin with the demo plugin that keeps all nodes in the DOM, which is exactly what you are after. If it were me - I would go for the solution with a hidden input, but you still have the option to submit the tree like a normal form.
