### ISSUE TITLE
Contextmenu with custom items

### ISSUE THREAD

**Issue by sytolk** [vakata/jstree#1030]
Hi,
I have context menu and pass custom items:
http://www.jstree.com/api/#/?q=$.jstree.defaults.contextmenu&f=$.jstree.defaults.contextmenu.items
I'm trying to synchronize built in jsTree edit with server side and only on delete node I have success :) I can't have new name after Create/Rename node.

```javascript
 items: {
'create' : {
'label': 'Създай нова група',
'action':  function (obj) { console.log(obj); this.create(obj); ajaxExec('%{editNode}', {'groupsId': obj[0].id,'editaction':1}); }
},
'rename' : {
'label': 'Преименувай групата',
'action':  function (obj) {  console.log(this.rename(obj));  }
},
'ccp' : false,
'remove' : {
'label': 'Изтрии групата',
'action':  function (obj) { this.remove(obj); ajaxExec('%{editNode}', {'groupsId': obj[0].id,'editaction':0}); }
}
}}
```
I know that its possible to handle it with listeners for events
$(jstree).on('delete_node.jstree'..
.on('create_node.jstree'
but I have use plugin that generate JavaScript and it not have this listeners:
https://github.com/struts-community-plugins/struts2-jquery/issues/26
If its possible to get new node name after Rename/Create after override items?
I think that it will be better if I can do that like this:
var new_node_name = this.create(obj);
var new_node_name = this.rename(obj);

**Comment by vakata** [comment]
Sorry, I could not understand what you mean. 
You can easily add or remove contextmenu items - just use the defaults and modify them, so set `contexmenu.items` to a function in your config and in that function modify the defaults:
```js
items : function (node) {
  var dflt = $.jstree.contextmenu.items.call(this);
  // remove from dflt or add to it
  return dflt;
```

As for getting the name after a rename - that is what the events are for. There is no other sure way to get the changed name - the `rename_node.jstree` event is what you need.

If I misunderstood - clarify and I will reopen the ticket.

Best regards,
Ivan

**Comment by sytolk** [comment]
I have try to get changed name in the items action property instead of events. 
```javascript
items: {
'rename' : {
'action':  function (obj) { this.rename(obj); ajaxExec(..
```
But no way :)

**Comment by vakata** [comment]
You could do a timeout and try to get the name but that will not be reliable and it won't be future safe - the events are the way to go.

**Comment by sytolk** [comment]
It is possible without timeout if this action is executed after user submit the form with new name. Maybe this can be new action:
items: {
'rename' : {
'action':  function (obj) { this.rename(obj); },
'actionSuccess': function(changedObj) { ajaxExec(..},

**Comment by vakata** [comment]
No, sorry - the only sure way is to simply use the events - its a few lines of JS after all. If you are using a tool to generate javascript, maybe it is time to stop using it and write some code on your own, since it obviously limits what you can use. 

I will not add additional bloat and callbacks that duplicate existing functionality. Once again - the way to react to changes in the tree is to listen for the events.

Best regards,
Ivan

**Comment by sytolk** [comment]
Да сляза на земята и да не се боря с фреймуорка повече викаш :) :+1:
