### ISSUE TITLE
Dynamic array collection data  - Uncaught Error: Syntax error, unrecognized expression

### ISSUE THREAD

**Issue by nazre** [vakata/jstree#1031]
Dynamic json data is not working.Tested with below code it is throwing error 
Uncaught Error: Syntax error, unrecognized expression: [{"id":"1","parent":"#","text":"test"}]
<div id="jstree_demo_div"></div>
$(document).ready(function () {

      var tree = {
		    nodes: []
		};
        tree.nodes.push({
	          id :  1 ,
              parent: '#' ,
	          text : 'test'
	    });
   $('#jstree_demo_div').jstree({
                    'core': {
                        'data': JSON.stringify(tree.nodes)
                    }
                });  

})

**Comment by vakata** [comment]
Please read the docs - jstree expects an array, or an AJAX config, or a function, not a string. You are passing in a string.

Best regards,
Ivan

**Comment by nazre** [comment]
vakata . Thank you very much for clarification
