### ISSUE TITLE
How to change helper text while dragging

### ISSUE THREAD

**Issue by abnerdr** [vakata/jstree#1033]
In the attached image, the helper text has the same text as node title ("One more"), how can I change the helper text displayed while dragging?, for example, display the parent title of dragged node ("Child 2").
[jstree](https://cloud.githubusercontent.com/assets/5678871/6627109/6dde0e80-c8c1-11e4-8f32-be9eaccf2054.png)

**Comment by vakata** [comment]
Sorry, you can't and for the time being I do not plan on adding such an option. 

If you want to you can manually hook to the DOM object of the helper and change the html / text. Listen for the drag start event and change the text inside the handler: 
http://www.jstree.com/api/#/?q=vakata&f=dnd_start.vakata

Best regards,
Ivan
