### ISSUE TITLE
[Question] Setting up deep selections for lazily loaded trees

### ISSUE THREAD

**Issue by AudriusButkevicius** [vakata/jstree#1038]
So I have a directory tree, which has some selections somewhere deep down inside the tree.

I use `get_top_selected` to get these selections and store them in some array.
The checkboxes are tristate, meaning when I select some deep leaf of branch of the tree, I get to the 3rd state all the way up to the root.

What I would like to do, is that next time I open the tree, and given I have the old `get_top_selected`, I'd like to be able to set the parent nodes to the 3rd state to indicate that there is something selected deeper down.

Now the problem is that my tree is loaded via ajax one level at a time, hence the parent only gets the 3rd state applied when I actually load all the nodes down to the one which was actually selected.

I guess the answer is to forcefully open all the nodes down to the ones in `get_top_selected` causing the tree to get populated correctly? Or is there some better way, such as marking the parents as the 3rd state without having to load the children?

**Comment by vakata** [comment]
Try using the `state` plugin. It will restore the previously opened and selected nodes. If you are worried about too much requests - include and configure the `massload` plugin too. That way your whole tree will be restored in two requests.

If you want to mark nodes as `undetermined` and keep the lazy loading intact - you have to use the `undetermined` property on each node as you lazy load it. That way the checkbox plugin will know that although the node is not yet loaded it should be marked as having a selected child / grandchild.

Best regards,
Ivan
