### ISSUE TITLE
get_checked order by tree sequence

### ISSUE THREAD

**Issue by lhpderckx** [vakata/jstree#1039]
Hi Vakata,

I'm using the get_top_checked jstree function. It returns everything I expect, although I would be greatefull if I could somehow get the items in sequential order, matching the visual sort order in the tree.

Now, the first item chronologically selected will be the first item returned and so on. Surely, I will now get the logical order sequence again server side after post and sort on that, or add more data to the jstree items so I can sort using that, but a built-in feature for this would make sense, or so I believe.

**Comment by vakata** [comment]
Sorry, that is just not possible with the way jstree stores data at the moment - it will require a huge overhead, which would make the call very very slow on large trees. I will give it some thought when I get round to v.4 in the distant future, but currently - there is no way to achieve that - sorry.

**Comment by lhpderckx** [comment]
Okay, no problem. I've worked around it by adding a sequence path in front of each node's ID value (an ID exampe is now: "2.5.1|40-345-1228", which means: node 1228 with parents: 40 (level 1) and 345 (level 2), with sequence: 2 (level 1), 5 (level 2) and 1 (level 3). I'm splitting the ID, store each level's sequence and sort my hierarchical list of node representations after the entire selection has been converted to my hierarchical list. It's just a few lines of code #iloverecursionlogic :)
