### ISSUE TITLE
State plugin on one of two trees

### ISSUE THREAD

**Issue by yoyoprs** [vakata/jstree#1040]
If multiple trees are loaded and one of them will have the state parameter.
Errors between the trees occur when traverses the same folders.

TypeError: a.state is undefined	
...d:function(a){return a=this.get_node(a),a&&a.state.loaded},is_loading:function(a...

or

TypeError: this._model.data[b].state is undefined
...model.data.hasOwnProperty(b)&&"#"!==b&&(this._model.data[b].state.opened&&a.core...

**Comment by vakata** [comment]
I can not reproduce: http://jsfiddle.net/DGAF4/375/

Please be more specific:
* which version are you using (probably 3.0.9);
* do all trees have the `state` plugin active or just one;
* If all have the plugin - have you provided different keys (`state.key` config option)

Basically, I need to see the relevant part of the tree configs you are using - the `plugins` option and the `state` opions. I will reopen when more info is provided.

Best regards,
Ivan

**Comment by yoyoprs** [comment]
Version : 3.0.9
State plugin : activated on just one tree
State.Key : Yes, was provided
Plugins used : sort,wholerow,types + state

It's happen when in my state i have 2 directories open in a same root directory, on your fiddle example  only the first path is expanded after a page refresh. In my example, jstree try to reload the 2 directories

See video: http://we.tl/ar6Qxbih29

**Comment by vakata** [comment]
Could you try using the latest code from this repo, and NOT the minified file, as I cannot find the offending line.

**Comment by yoyoprs** [comment]
TypeError: this._model.data[i].state is undefined
if(this._model.data[i].state.opened) {
jstree.js (ligne 3115)

**Comment by yoyoprs** [comment]
No errros when i add:

    $("#tree_popup").on("open_node.jstree", function (e, data) {
        var obj =  data.instance.get_node(data.node, true);
        if(obj) {
            obj.siblings('.jstree-open').each(function () { data.instance.close_node(this, 0); });
        }

**Comment by vakata** [comment]
That is very odd, it must be data related, as there is no way for the `.state` property to disappear. Do you by any chance return `state` as part of your JSON response?
Also - did you try the latest code from the repo?

**Comment by yoyoprs** [comment]
Yes i have the latest code from repo.
No state on my json response.
But i forgot to mention i use Jstree-directive (Angularjs) as a layer (https://github.com/arvindr21/jsTree-directive)
I opened a ticket on, i do not determine where it comes from ... :(

**Comment by vakata** [comment]
Check with the angular directive vendor, as I can't reproduce this. Also - in the latest code there is a comment on the line with the error.

**Comment by yoyoprs** [comment]
Sorry, i used the latest release. With the new version:
i open Two subchild (without state plugin), i refresh  $('#treef').jstree(true).refresh();) the tree i have this
error:

TypeError: obj.id.replace is not a function : line 2289 col 226 
(...).replace($.jstree.idregex,'\\$&') : obj.id.replace($.jstree.idregex,'\\$&')) );...

**Comment by vakata** [comment]
Sorry, this is not something I can reproduce with jstree: http://jsfiddle.net/DGAF4/378/, check with your angular directive provider.
