### ISSUE TITLE
Where is the website source?

### ISSUE THREAD

**Issue by IonicaBizau** [vakata/jstree#1041]
I found a small issue in the documentation site and I would like to fix it. Where could I find the website repository?

---

[Here](http://www.jstree.com/docs/html/) is the issue (*Loading with ajax*):

```js
$('#tree').jstree({
'core' : {
  'data' : {
    'url' : 'ajax_nodes.html',
    'data' : function (node) {
      'url' : 'ajax_nodes.html',
      'data' : function (node) {
        return { 'id' : node.id };
      }
    }
  }
});
```

There is a duplicated `url` field in a wrong place. 

I suppose that this should look like:

```js

$('#tree').jstree({
'core' : {
  'data' : {
    'url' : 'ajax_nodes.html',
    'data' : function (node) {
      return { 'id' : node.id };
    }
  }
});
```

**Comment by vakata** [comment]
Thanks, I just fixed it. Sorry, the site is not in the repo.

**Comment by IonicaBizau** [comment]
You're welcome! I'd recommend to host it on GitHub pages (the `gh-pages` branch). Just push your site files (html, css, js) in the `gh-pages` branch and you should have it live here: https://vakata.github.com/jstree

**Comment by vakata** [comment]
Yes, I know, but I'd rather not do that. This lib is completely free (as you probably know) and having a few ads on jstree.com helps my finances a bit :)

**Comment by IonicaBizau** [comment]
@vakata Nobody stops you to have ads on your website. If everything is client side, I'd vote for GH pages.

**Comment by vakata** [comment]
Thanks again for the tips, still I prefer to have everything on my own host as I know terms and conditions there will not change. Also - it is all part of my build process and I can easily control various aspects of the site.

Best regards,
Ivan

**Comment by IonicaBizau** [comment]
I see. OK and keep up the good work! :+1:
