### ISSUE TITLE
Contextmenu for dynamic list

### ISSUE THREAD

**Issue by IonicaBizau** [vakata/jstree#1043]
Everything I load comes from ajax responses.

I loaded the `contextmenu` plugin and right-clicking works fine, but none of the context menu actions work...

For example, if I click *Rename* nothing happens.

**Comment by IonicaBizau** [comment]
I followed [this example](http://www.jstree.com/demo/).

**Comment by vakata** [comment]
Did you set `core.check_callback` to `true`? From what I see on the site all the demos seem to work fine, so it must be something with your config. Please share your config if it was not the `check_callback` setting.

If it turns out that there is something wrong with the contextmenu plugin I will reopen the issue.

**Comment by IonicaBizau** [comment]
Yes, that was the problem! Thank you! 

PS: I love how you manage the issues. You post the reply and close it speedy. :smile: :+1:

**Comment by vakata** [comment]
Sorry, I know it can be annoying but I really hate having open issues, and with most issues I am 99% certain that the problem is not with jstree itself (as in this case) :smile:

**Comment by IonicaBizau** [comment]
Me too! :smile: I always liked clean repositories like this. That's a good sign that the repository is *still* maintained.

**Comment by IonicaBizau** [comment]
@vakata I'm trying to implement the context menu again. The config object looks like this:

```js
{
    plugins: ["dnd", "types", "wholerow", "contextmenu", "search"],
    types: {...},
    core: {
       data: function (node, cb) {
          ...
       },
       check_callback: true
    },
    contextmenu: {
       createFolder: {
           label: "New folder",
           action: function (node) {
       },
       ...
    }
}
```

The context menu doesn't appear when I right click, but the item is selected. Why?

I have to mention that I'm modifying the `href` attributes so I can use the middle click to 
open the links in new tabs. Maybe that's the problem?

**Comment by vakata** [comment]
I think you missed the `items` key - it should contain the actions, not the `contextmenu` key itself. The node is selected by default when you right click it - it is controlled with a setting: http://www.jstree.com/api/#/?q=contextmenu.select_node&f=$.jstree.defaults.contextmenu.select_node

Try something like this:
```js
contextmenu : {
    items : { .... },
    select_node : false
}
```

Best regards,
Ivan

**Comment by IonicaBizau** [comment]
@vakata Thanks, but that doesn't work either. The only change is that the node is not selected anymore.

**Comment by vakata** [comment]
Here is a demo: http://jsfiddle.net/DGAF4/513/
Tell me if it works.

Best regards,
Ivan

**Comment by IonicaBizau** [comment]
@vakata Sorry for confusion, the issue was because the tree lives in a `fixed` element. So, I had to update the `z-index` of `.jstree-contextmenu` to bring it to front.

Thanks a lot! :cake:
