### ISSUE TITLE
dnd and ajax preload

### ISSUE THREAD

**Issue by TkachenkoAYU** [vakata/jstree#1046]
Steps to bug on demo page (Database demo):
1) create nodes 1 > 11, 2 > 22;
2) collapse nodes, update page;
3) expand node 2;
4) move node 22 to 1 (do not until "open_timeout");
5) open node 1;
6) move node 22 to 2;
7) collapse/expand nodes 1, 2.

![dnd_ajax](https://cloud.githubusercontent.com/assets/11524145/6692123/c32f7bb0-cd05-11e4-9b72-7028b06d9a2b.gif)

**Comment by vakata** [comment]
I believe this bug is already fixed, can you reproduce it with the latest code from this repository?
