### ISSUE TITLE
add jstree-grid to the official list of jstree plugins

### ISSUE THREAD

**Issue by ehartford** [vakata/jstree#1047]
can jstree-grid be brought in? https://github.com/deitch/jstree-grid

**Comment by deitch** [comment]
+1

**Comment by vakata** [comment]
Hi,

I do not think that it is a good idea to bundle jstree-grid into jstree. I would have to support it, which I currently can't. Bringing it in would require me to gain deep understanding of the plugin, how it works, etc. Don't get me wrong - it is an excellent plugin, thanks @deitch, but it is not something I wrote, so I can't support it properly.

I suppose the real question to ask is - what would anyone gain from bundling it with jstree? My guess is that if someone wants to use it, they will download the plugin and use it. If it is about spreading the work - I can simply list it on jstree.com? 
@deitch If that sounds like a good idea - just let me know and I will list it in the plugins page, in a new section listing 3rd party plugins.

Best regards,
Ivan

**Comment by deitch** [comment]
Of course, I would be more than happy to have it adopted into jstree. But I certainly understand; I barely can find time to support it when issues get opened. If there is a route we could take to get it there, that would be great (and probably improve its quality on the way).

In the meantime, listing it on the plugins page sound like a great idea.

**Comment by ehartford** [comment]
I question what disadvantage is there to having this code in one repo
instead of two repos?  It seems to me it would bring community together,
benefit from shared test and release processes, expanded feature set for
jstree, increased adoption of jstree-grid, more unified look and feel.  I
don't see how it would hurt anything, and I see a lot to gain...

**Comment by vakata** [comment]
I agree about the adoption, but for all other listed benefits to work, would mean that I have to take over the plugin, which I am not ready to do, sorry.

To help adoption - I will add the plugin to the site.

Best regards,
Ivan
