### ISSUE TITLE
misc plugins are not getting added to the distributed release

### ISSUE THREAD

**Issue by mtraynham** [vakata/jstree#1048]
https://github.com/vakata/jstree/blob/master/gruntfile.js#L10

Found when trying to figure out why the `conditionalselect` plugin stopped working.

**Comment by vakata** [comment]
Those are demo plugins, they are not supposed to be in the release. The sample plugins are various snippets of code people asked me to help with. They are not part of the build. I will however consider adding the `conditionalselect` plugin as it seems to be widely used.

**Comment by mtraynham** [comment]
@vakata Understood thanks!
