### ISSUE TITLE
Need node title

### ISSUE THREAD

**Issue by xjsender** [vakata/jstree#1050]
Because the node text is too long, I just want to display part of it, however, I also want to add a title attribute for it.

**Comment by vakata** [comment]
Then add it: https://github.com/vakata/jstree#the-required-json-format (last one: `a_attr`).

Sample:
`{ "id" : "1", "text" : "Node 1", "a_attr" : { "title" : "Long title for node 1" }, ... }`

Best regards,
Ivan
