### ISSUE TITLE
Preventing node opening

### ISSUE THREAD

**Issue by Muchiachio** [vakata/jstree#1052]
It seems that ```select_node (obj [, supress_event, prevent_open])```, prevent_open parameter is being ignored and all parent nodes are being opened after selecting. Maybe I'm doing something wrong?
Here's a [repro fiddle (based on 3.0.9)](http://jsfiddle.net/fdf3d8oj/), tested on 3.0.9 - 3.0.10.

**Comment by vakata** [comment]
You are trying to modify the tree before it has fired its `ready` event. Here is a proper demo: 
http://jsfiddle.net/fdf3d8oj/1/

The reason the nodes are opened is that they are marked as selected before the tree is ready, in that case the `expand_selected_onload` option comes into play:
http://www.jstree.com/api/#/?q=core.expand&f=$.jstree.defaults.core.expand_selected_onload
Here is a demo with that option set to `false`:
http://jsfiddle.net/fdf3d8oj/2/

However - the first approach is the better one - if possible - wait for the tree to be ready before interacting with it.

Best regards,
Ivan
