### ISSUE TITLE
cascade selection doesn't fired "select_node.jstree"

### ISSUE THREAD

**Issue by DmLapin** [vakata/jstree#1055]
I luched plugin with the next options:
```
<script>
$(function () { 
    $('#tree').jstree({ 
        "checkbox" : { 
            "cascade" : "up",
            "three_state" : false
        },
        "core" : { 
            "multiple" : 1
        },
        "plugins" : [ "checkbox" ],    
    }); 
    
    $('#tree').on('select_node.jstree', function (e, data) {
        console.log(data.node);        
    });    
});
</script>
```
If we have such tree:
```
Root1
---Child1
---Child2
Root2
```
and select Child1, Child2 then Root1 will be selected automatically. But "select_node.jstree" will be fired only 2 times for child elements and not for parent.

Expected behaviour: automatic selection/deselection should trigger event too.
My use case: select/deselect corresponding form checkbox in event handler.

**Comment by vakata** [comment]
`select_node` is more of an internal event - to listen for changes use the `changed.jstree` event - it will fire once everything is done. You can then use `data.selected` in the event handler to see which nodes are selected.
This will not change - triggering `select_node` for every node when using cascade will drop performance quite a bit and will make the tree unusable with as little as a few thousand nodes.

**Comment by eggyal** [comment]
Whilst one can use `data.selected` in the `changed.jstree` event handler to discover which nodes are selected after the change:

1. `data.selected` might contain a great many nodes, but it could well be that only a small subset of them were selected as a result of the event that is being handled—yet there is no easy way to discover which; and

2. some nodes might have been deselected as a result of the event that is being handled—yet there is similarly no easy way to discover which.

So far as I can see, the only solution (to either problem) is to save a list of selected nodes prior to the event; and calculate the difference between that set and `data.selected` in the event handler.  Ugly.

Could you at very least add `data.changelist` or somesuch, to providing direct access to the nodes that have been (de)selected during the event?

**Comment by vakata** [comment]
Hi,

There is a lot of additional info in the `changed.jstree` event - like what triggered the change (select, deselect, etc) and which node or nodes triggered it, along with information if the change was triggered by user interaction.
I believe this information should be enough almost all of the time. If it is not - you need some advanced way of keeping state, but I will not include this in the core, as it makes no sense to include everything anyone has ever asked for - if I find there is a growing need for this - I will consider including it in the checkbox plugin in some way.

In the mean time, as you said - the difference between previously and currently selected nodes will give you which nodes were deselected, and the opposite - will give you which nodes were selected. I will create a plugin that includes this information in the changed event, so it is easy to use. I will get back to you with the plugin later today.

Best regards,
Ivan

**Comment by vakata** [comment]
Here is the sample plugin: https://github.com/vakata/jstree/blob/master/src/misc.js#L23
If the performance tests are fine I will add it to the core.

Best regards,
Ivan

**Comment by eggyal** [comment]
Thank you @vakata for such a speedy fix!  I have made a donation to show my appreciation.

**Comment by eggyal** [comment]
Thank you @vakata for such a speedy fix! I have made a donation to show my appreciation.

Is it also possible to obtain the nodes that have changed to/from undetermined state (i.e. with the checkbox plugin in three-state mode)?

**Comment by vakata** [comment]
Thank you @eggyal - I really appreciate it.

As for the undetermined nodes - unfortunately that is not possible, in the internals there is no such state, so there is no track of it, such nodes are internally simply not selected, and the undetermined icon is added to the DOM only.

I believe I published a script to get all undetermined IDs somewhere, but it was quite expensive (it involved iterating all parents of selected nodes and checking it they themselves are not selected). Running such code each time `changed.jstree` fires would probably impact performance too much for larger trees. If you are interested in the script - I believe it was published in the discussion group - if you want you can easily attach it to the sample plugin I provided. I doubt the undetermined diff will be ever fast enough for me to include it in the build (as opposed to the changed object, which I am currently testing).

**Comment by RevathiArunachalam** [comment]
$('#tree').jstree({
		    	"plugins" : [ "checkbox"],
		    	"checkbox" : {	
		    		 "whole_node" : false,
		    		"three_state": false,
		    	    "keep_selected_style" : true //selected node style
		    	   
		    	  },
		    	 
		    	"core" : {
		    	    "multiple" : true, //multiple node select
		    	    "animation" : 0,
		    	    "themes" : {
		    	    	'responsive': true,
		    	    	"icons":true,
		    	        "variant" : "large" // large size display
		    	      }, 
		    	     
					  'data' : jsonObjects,
					  
		    	  }
		    	    
		    });

//to select a node
$("#tree").bind(
			        "select_node.jstree", function(evt, data){	
			        	  $('#tree').jstree('check_node', 'li[selected=selected]');
			        	
			        	  var fileId=data.instance.get_node(data.selected).id;
					      var fileName=data.instance.get_node(data.selected).text;
					      if ((fileName.indexOf(".") != -1)) {
								var url = "#";
								window.location = url;
							} 
					   
			        }
			);  
My issue is when i try to check a checkbox url is firing. and  when i try to select a node url is firing and check box is checked. What i need is if check a checkbox url wont be fire and select a node check box won't be checked.  am using v3.2.1  Help me
