### ISSUE TITLE
Don't prevent default click in a[href=http://...] inside a node

### ISSUE THREAD

**Issue by duzun** [vakata/jstree#1060]
This is a feature request.

It would be great to have a special class/attribute/option to allow default click event on links inside jsTree nodes.

Here is a simple example [commit](https://github.com/duzun/jstree/commit/366797d9ecd69177bf2b5f5de2787320ec1501af)

**Comment by vakata** [comment]
Sorry, that would cause a cascade of additional config options (checkbox behavior, etc). I have refused this a lot of times, and I will once again. For me it is pretty easy to attach a changed.jstree handler with about a line of code in it.

Best regards,
Ivan
