### ISSUE TITLE
Endless loop when trying to create a new node

### ISSUE THREAD

**Issue by mikehaertl** [vakata/jstree#1062]
I have an issue that seem to be related to the `types` plugin. My tree works fine, but as soon as I enable `types` and try to  create a new node on a node that has children, jstree runs into an endless loop.

Here's a jsfiddle: http://jsfiddle.net/mike_haertl/yh08vyoz/

Try to right click on "id: 24 test" and then "Create". 

I found that it never leaves the `do {...} while()` here: https://github.com/vakata/jstree/blob/a0767ceb3fffe1c0b2774d28c811116892a071b8/src/jstree.types.js#L165

Am I doing something wrong or is this a bug?

**Comment by vakata** [comment]
Your data is wrong - here is the corrected fiddle: http://jsfiddle.net/yh08vyoz/14/

When jstree wants the children of c24 - return just that - the children, not the whole node and its children. What you were doing caused a second node with the same `c24` ID to be added to the structure, which basically brakes the tree, as there can not be two nodes within the same tree with the same ID.

Best regards,
Ivan

**Comment by mikehaertl** [comment]
Alright, thanks.
