### ISSUE TITLE
Add more documentation about check_callback

### ISSUE THREAD

**Issue by mikehaertl** [vakata/jstree#1063]
I couldn't really find a full documentation for all the `check_callback` parameters. What I found was:

 * http://www.jstree.com/api/#/?f=$.jstree.defaults.core.check_callback
 * https://github.com/vakata/jstree#more-on-configuration (mid of the section)

So the signature is `function (operation, node, parent, position, more)`. But that alone leaves many questions open:

 * What are all possible situations when the callback gets called and what are the respective values for `operation`?
 * For each situation, what do all the other parameters mean? Especially the `more` parameter is very complex. I found for `dnd` it's `pos` property can vary between `i`, `a` and `b`. What does this mean?

So it would be cool if you could add some more details here.

Thanks!

**Comment by mikehaertl** [comment]
Thanks!

**Comment by tihomiro** [comment]
For anyone looking, the more.pos property can be any of the following:

1. 'b' - addBefore
2. 'a' - addAfter
3. 'i' - append

Source: [https://groups.google.com/forum/#!topic/jstree/qYPyhXcewuc](https://groups.google.com/forum/#!topic/jstree/qYPyhXcewuc)
