### ISSUE TITLE
HTML entities get double encoded on rename

### ISSUE THREAD

**Issue by mikehaertl** [vakata/jstree#1064]
If you have a tree node with a text like `<test>` and you click on rename, it becomes `&lt;test&lt;`.

In fact, I miss a feature to disable this automatic encoding of text. The way it should work IMO:

 * `get_text()` and `set_text()` work with raw, unencoded values (`<test>`)
 * only when the node is rendered should the text get encoded

Is there a workaround to make this work with the current 3.1.0 version?

**Comment by mikehaertl** [comment]
I found the `$.jstree.defaults.core.force_text` setting, which improves the situation. But still the text is not correctly encoded anymore when editing a name.

**Comment by mikehaertl** [comment]
Nevermind, I had a typo in `force_text`. With this set to `true` it works as expected.

**Comment by duzun** [comment]
I think this is still an issue if one needs `force_text` == false.

**Comment by vakata** [comment]
This has been discussed a lot - jstree has no way of knowing what you need - plain text or HTML - hence the config option - any kind of guess work will be wrong half the time.

**Comment by duzun** [comment]
I agree @vakata, but this is still an issue!

I choose what I need, HTML or text, but I need jsTree to reliably interpret my choice.

Right now `force_text == true` works perfectly, 
but if `force_text == false`, jsTree reads `a.innerHTML` into editing input and writes to `a.textContent`.
As a result, when I just open a node with the text "&amp;" for editing and close it, I get "&amp;amp;" as `textContent`. If I open it again and close, I get "&amp;amp;amp;", then "&amp;amp;amp;amp;", and so on.

The correct behavior should be as follows:
When `textContent` of the node is "&amp;", I should see "&amp;amp;" in editing input (`innerHTML` of the node) and get "&amp;" as `textContent` after saving.

**Comment by mikehaertl** [comment]
Even if my original problem is solved with `force_text=true` I agree to @duzun. It was actually because of this weird behavior, that I found out that jstree uses encoded values by default.

**Comment by vakata** [comment]
Oh, I see, I will have a look - sorry, I did not get this right away.

**Comment by duzun** [comment]
I just tested the commit, and the issue of double encoding is fixed - great!

Just to note, with `force_text=false`, "<b>text" bocomes "<b>text</b>" after editing, "text > text" becomes "text &gt; text", and other HTML normalization apply.
I guess this is the intension.

**Comment by vakata** [comment]
Yes, that is the intention, I am afraid there is no other way to do this - I am using the jQuery parseHTML function, which in turn uses the browser correction if I am not mistaken, so `<b>text` will become `<b>text</b>`. If you need the other result you'd have to type `&lt;b&gt;text `.

Best regards,
Ivan
