### ISSUE TITLE
parentheses in filename don't work

### ISSUE THREAD

**Issue by MLightsOut** [vakata/jstree#1065]
I am filling a tree view with a directory structure (files and folders).  The node (folder) will not open if a filename inside of that folder contains parentheses.  I receive a JavaScript error  JavaScript runtime error: SyntaxError.

**Comment by vakata** [comment]
Sorry, until you provide more information I am closing this. As you can see in the demo there is no problem with parentheses: http://jsfiddle.net/DGAF4/395/

Please provide your config, some sample data and let me know which version of jstree you are using.
I will reopen this when you provide this information.

Best regards,
Ivan
