### ISSUE TITLE
Confusion with target position on movement

### ISSUE THREAD

**Issue by mikehaertl** [vakata/jstree#1066]
I am still struggling with getting movement right. Say I have a tree like this:

 * tree
  * a
  * b
  * c
  * d

Now say, I move `d` between `a` and `b`. The `position` parameter now is `1` which makes sense, because for a 0-based index I'm moving to position `1`.

Now try to move `a` between `c` and `d`. Now the position parameter is `2` which does not make sense to me. In the unmodified tree (before the movement) `d` is at position `3` and this is where `a` would end up. So I would expect to get `3` as target position.

So it seems, that for forward movements the position is calculated, as if the movement already happened! But this makes it very hard to deal with on the server side of things.

**Comment by vakata** [comment]
In the `move_node.jstree` and `copy_node.jstree` events the position is exactly what you would expect.
Still, if you need help with the server side - take a look at the PHP demo that is provided - it is pretty basic and can be ported to any language you like.

As for calling `move_node` and `copy_node` - imagine removing the node from the collection first and then inserting it back in at a specified index (without counting the node of course), or simply use the `before` and `after` positions.

Best regards,
Ivan
