### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by zeynepsu** [vakata/jstree#1069]
Getting "Uncaught TypeError: undefined is not a function" on these lines (181 and 262):

![screen shot 2015-04-12 at 11 57 27 am](https://cloud.githubusercontent.com/assets/2171970/7107036/379b1be4-e10b-11e4-8bbc-9c02d487fb46.png)
![screen shot 2015-04-12 at 11 57 37 am](https://cloud.githubusercontent.com/assets/2171970/7107035/379adcf6-e10b-11e4-9bd9-b7deaf9a7264.png)

I believe $(function () { $('#jstree_demo_div').jstree(); }); causes these errors, but there is no error reported there and jstree.js is included with 200 ok according to the network tab. This is a chrome extension.

**Comment by vakata** [comment]
It seems you do not have jQuery loaded.

Best regards,
Ivan
