### ISSUE TITLE
Single click on items to open subitems

### ISSUE THREAD

**Issue by mortalis13** [vakata/jstree#1070]
Hi.
Is there a configuration to set single click to open subitems instead of doubleclicking them?
Thanks.

**Comment by vakata** [comment]
No, but its a one liner if you need it: 
```js
$('#tree').on('click', '.jstree-anchor', function (e) { $('#tree').jstree(true).open_node(this); });
```

Best regards,
Ivan

**Comment by ginolon** [comment]
Hi Ivan (@vakata),

I'm using Turbolinks 3.0 from github, last version and when I load the page with it (the menu isn't reloaded in the page), what change is just the part of page I need to update (not via ajax, with tubolinks's system), with your code or also with default double click jstree not open anymore the three...

Why?

If the menu is already open (by default), when I reload the page (again with turbolinks 3.0 partial replacement) when I click on a three it reopen itself.

Why?
