### ISSUE TITLE
Get node from id

### ISSUE THREAD

**Issue by alexandernst** [vakata/jstree#1071]
It would be nice if one could get the actual node element out of an id.

**Comment by vakata** [comment]
http://www.jstree.com/api/#/?q=get_node 
If you need the DOM element, keep in mind only visible and opened nodes are kept in the DOM.

**Comment by alexandernst** [comment]
@vakata IIRC that method accepts a jQuery DOM object, right? I'm asking for a way to get the DOM object out of an ID (the ID you set in `core.data.myitem.id`)

**Comment by vakata** [comment]
No, this function works with IDs, DOM objects, jQuery collections, etc:
`$('#tree').jstree(true).get_node('ID123');`
