### ISSUE TITLE
ready.jstree called after only root nodes loaded

### ISSUE THREAD

**Issue by c4simba** [vakata/jstree#1074]
To my mind it shuld be after all nodes and childs. Now I use a workaround: setTimeout (...,100) to wait when all childs load.

**Comment by vakata** [comment]
Read the documentation - there are a few events you can use. My guess is you are using the state plugin - use the state_ready.jstree event.

**Comment by c4simba** [comment]
I read the documentation. I init jstree in angular when resived data. *tree* is array of data
$(e).jstree({
            "checkbox": {
              "keep_selected_style": false,
              "tie_selection": false
            },
            "search": {
              "show_only_matches": true
            },
            "plugins": ["wholerow", "checkbox", "search"],
            core: {
                "themes": {
                    "icons": false
                },
              "data": tree
            }
          }).on('ready.jstree',
                  function() {
                      // *I use setTimeout because on this event loaded only first level of tree. It's right?*
                      setTimeout($.proxy(function () { scope.ngLoadModeldata(); }, this), 100);
                  }
              );

Can you tell me it work right?

**Comment by vakata** [comment]
Sorry, I do not use angular, but `ready.jstree` fires after all nodes are loaded, there was a bug with it a few versions back, where it fired before all nodes were loaded, but that was fixed. Which version are you using?

**Comment by c4simba** [comment]
I tested it on 3.1.0 and 2.8.x.
Do you speak russian?

**Comment by vakata** [comment]
What is 2.8.x? And no, sorry, I do not speak Russian. 

As for your problem - let me clarify - tree is an array, right? If that is so the ready.jstree will fire immediately, what do you mean by "only root nodes loaded" - if you are passing an array, there is no lazy loading, which means all nodes are "loaded" immediately. 
If you want to do something with the DOM, and you want to wait for nodes to open, that is another matter. If it is so - keep your timeout solution, it should even work with 0 timeout. But the DOM has nothing to do with jstree loading the nodes and firing the ready handler.

Best regards,
Ivan

**Comment by c4simba** [comment]
Sorry, it was 3.0.8 version, not 2.8. thee os an array of countries whitch including towns as children elements. I wanna hide unselected items after load tree, but i shuld do timeout for test countries with some selected towns.

Thank you for converstation. May be in new version  will be added new event)

**Comment by vakata** [comment]
There will be no new event, the ready / loaded / init events are based on jstree parsing data, not on anything DOM related. Anyway, I am glad it is clear now.

**Comment by c4simba** [comment]
I tested with 0 delay: it work throught time.

**Comment by lahirue** [comment]
If I use lazy loading , i cannot programatically check_node , because open_node is take some time to render the  UI. in that case how i wait ?

**Comment by vakata** [comment]
There should be absolutely no problem checking a node - jstree does not depend on the DOM, so you can call check_node or select_node just with the node ID (not a selector) and all will work fine, regardless if the node is visible or not.

Best regards,
Ivan

**Comment by lahirue** [comment]
Thank you for your fast reply. Actually what i'm doing is , dynamically opening nodes and going to check specific leaf nodes. 

treex.jstree({
        "plugins": ["checkbox"],
        'core': {
            'data': {
                "animation": 0,
                "check_callback": true,
                "themes": {"stripes": true},
                'url': function (node) {
                     return "/apis/" + node.id;
                } 

            }
        }
    }).bind("loaded.jstree", function (event, data) {
        $.ajax({
            url: URL that will get my custom data, (selected nodes as paths)
            type: 'GET',
            async: false,
            headers: {
                Accept: "application/json"
            },
            success: function (response) {
                    selectedTaxa = response.data;
                for (var i = 0; i < selectedTaxa.length; i++) {
         
                    var ref = $('#data').jstree(true);
                   
                    try {
                        var nodeList = selectedTaxa[i].split("/");
                        for (var j = 0; j < nodeList.length; j++) {
                             //recursively open nodes . nodeList contain id of nodes
                             ref.open_node(nodeList[j]);
                        }
            // leaf node of the given path
             var nodeId = selectedTaxa[i].substring(selectedTaxa[i].lastIndexOf("/") + 1, selectedTaxa[i].length);
              ref.check_node(nodeId);
                    } catch (ex) {

                    }


                }


            },
            error: function () {
            }
        });

    });

**Comment by lahirue** [comment]
this will not get checked because of node is not rendered in the page. if we use same code after open all nodes , it will work. What is the problem here ?

**Comment by lahirue** [comment]
Problem here is im loading the DOM dynamically and .

**Comment by marioandrei505** [comment]
Hi Lahirue, I have the same problem. Did you solve it?

**Comment by khateeb321** [comment]
Same issue I'm facing as of @lahirue
