### ISSUE TITLE
redraw not working

### ISSUE THREAD

**Issue by Batistleman** [vakata/jstree#1075]
I'm changing the data on a tree like this:

    $('#tree').jstree(true).settings.core.data = new_data;

When I call 

    $('#balanceList').jstree(true).refresh();

The tree properly updates, but when I do 

    $('#balanceList').jstree(true).redraw(true);

nothing happens, any ideas? 
Side note: I only changed some icons in the new data.

**Comment by vakata** [comment]
`redraw` is an internal method - do not use it, but to clarify - jstree parses your data to an internal object, `redraw` visualizes that object in the DOM, but it will not reparse your data.

`refresh` is the way to go - it will first reload / reparse data as needed and store it in the internal object and then call redraw to update the DOM.

Also - you'd be better off setting `core.data` to a function, and in that function feed to jstree whatever data you want. Manually changing the data object will work (as you noticed), but I would not recommend it.
```js
var data = [...];
$('#tree').jstree({
  core : {
    data : function (node, cb) { cb(data); },
    ...
// once the data changes store it in the data variable and call .refresh()
```

Best regards,
Ivan

**Comment by Batistleman** [comment]
ok, thanks for the clarification!
