### ISSUE TITLE
Getting children nodes

### ISSUE THREAD

**Issue by andreaci** [vakata/jstree#1076]
I'm using checkbox plugin and when the user click on a node containing childrens, the check_node event is fired

```js
.on('check_node.jstree', function (e, data) {
  var id = data.node.original.id;
}
```

**data.node** contains the checked node, with all properties, but not **children**.

The two arrays "children" and "children_d" contains **only children'IDs**, not the node themselves.

How can I obtain child nodes with all their properties? Or, in alternative, searching for the nodes by IDs (NOT getting the DOM element,  but the node himself)

The only way I found is something like:

```js
 for(var i in data.node.children) {
  var curChildren = tree_data.instance.get_node(data.node.children[i]).original;
}
```

getting the array directly in event data would be way easier

**Comment by vakata** [comment]
On a side note - do not depend on `original` - what do you need that is not directly present on the node? If you store extra properties - use the `data` property (for more read the home page of this repo).

As for the issue - yes - you need to use `get_node` and use the `children` array. Collecting all children each time before the event is fired will be way too slow, and would mean transferring a huge object with each event.

Best regards,
Ivan
