### ISSUE TITLE
Issue in 3.1.0

### ISSUE THREAD

**Issue by olepogam** [vakata/jstree#1078]
Hello,
First thanks for your great job.
I've found an issue on lines 3719 & 3891 (two conditions : "if(old_ins || old_ins._id) {" ) than may lead to a null exception on old_ins._id if old_ins is null (actually dropping an external div to a jstree). 
Replaced the "or" by a "and" for now, waiting for the boss' fix.
Best regards,
Oli

**Comment by vakata** [comment]
Thank you.
