### ISSUE TITLE
Add a method to check whether a node is a leaf node

### ISSUE THREAD

**Issue by mikehaertl** [vakata/jstree#1080]
I have some problems to find out whether a node is a leaf node. There are methods `is_leaf()` and `is_parent()` but they seem to be not accessible. So for now I had to adapt the code from `is_parent()` which is pretty inconvenient:

```
  function onActivateNode(e, data) {
    if (data.node.state.loaded && data.node.children.length===0) {
      alert('leaf node clicked');
    }
  }
```

**Comment by vakata** [comment]
What do you mean by "not accessible"?
http://jsfiddle.net/DGAF4/426/

Best regards,
Ivan

**Comment by mikehaertl** [comment]
Oh, ok, sorry. I've tried something like `$.jstree.is_leaf(node)` and forgot about the instance.
