### ISSUE TITLE
Make only leaf nodes selectable

### ISSUE THREAD

**Issue by mikehaertl** [vakata/jstree#1081]
I need a tree, where only the leaf nodes should be selectable. If a used clicks on a parent node, it should not change the current selection.

This may already be possible somehow, but I couldn't figure it out from the API docs. If it's not possible, then maybe we could add a `before_select` event, and make the event cancelable there?

**Comment by vakata** [comment]
There is a plugin, that is not in the core - check this repo - (src/misc.js)[https://github.com/vakata/jstree/blob/master/src/misc.js#L30], the plugin is called `conditionalselect` copy the source on your page and include it in your config. Then you can supply a function that will be executed before each select - if that function returns `false` - the select will be prevented.

```js
(function ($, undefined) {
	"use strict";
	$.jstree.defaults.conditionalselect = function () { return true; };
	$.jstree.plugins.conditionalselect = function (options, parent) {
		// own function
		this.activate_node = function (obj, e) {
			if(this.settings.conditionalselect.call(this, this.get_node(obj))) {
				parent.activate_node.call(this, obj, e);
			}
		};
	};
})(jQuery);

$("#tree").jstree({
  plugins : ["conditionalselect", ...],
  conditionalselect : function (node) { return this.is_leaf(node); },
  ...
});
```

**Comment by mikehaertl** [comment]
Ok, thanks!

**Comment by VISAE** [comment]
Thank you!! you're a magician!!
