### ISSUE TITLE
Select only parent node

### ISSUE THREAD

**Issue by teo89** [vakata/jstree#1085]
I want in jstree with checkboxies to select only parent node how can i do that. There is any way?
![2015-04-22 12_26_45-jstree](https://cloud.githubusercontent.com/assets/9746909/7271494/71f01fcc-e8ec-11e4-8d2a-0bedc529c376.png)

**Comment by vakata** [comment]
Read the docs: http://www.jstree.com/api/#/?q=three_state&f=$.jstree.defaults.checkbox.three_state

**Comment by teo89** [comment]
thanks
