### ISSUE TITLE
When deselect children parent deselected too 

### ISSUE THREAD

**Issue by teo89** [vakata/jstree#1086]
when i deselect all children parent note deselected too. So if i want only parent node i can't selected it and if i use three_state: false i can select all children in once. There is any way to do that? When i select parent node all children selected too and when i deselect all children parent note stay selected

**Comment by vakata** [comment]
For the third time - read the docs or use ONLY the discussion group for how-to questions: http://www.jstree.com/api/#/?q=cascade&f=$.jstree.defaults.checkbox.cascade

```js
$("#tree").jstree({
  checkbox : {
    three_state : false, 
    cascade : 'down'
  },
  ...
})
```

**Comment by guxiaoyong** [comment]
![qq 20160913225241](https://cloud.githubusercontent.com/assets/22174062/18478743/face5f34-7a04-11e6-985e-5ee72d860394.png)
![qq 20160913225251](https://cloud.githubusercontent.com/assets/22174062/18478751/0331e0ba-7a05-11e6-9e13-d1a883ac1de5.png)
when the three_state is set to true, the get_selected() doesn't return the parent node id to me. I want to know could I use the cascade functionality at the same time with geting parent id at get_selected() is called.
