### ISSUE TITLE
Uncaught TypeError: this.get_node(...).find is not a function

### ISSUE THREAD

**Issue by alexandernst** [vakata/jstree#1088]
From time to time (haven't found a 100% reproducible way) I get this error in my console.

This is the backtrace:

    (anonymous function)	@	jstree.js?v=1429556021:829
    jQuery.extend.proxy.proxy	@	jquery.js?v=1429556021:512
    jQuery.event.dispatch	@	jquery.js?v=1429556021:4430
    jQuery.event.add.elemData.handle	@	jquery.js?v=1429556021:4116

And this i the relevant code in jstree:

	.on('focus.jstree', $.proxy(function () {
			if(+(new Date()) - was_click > 500 && !this._data.core.focused) {
				was_click = 0;
				this.get_node(this.element.attr('aria-activedescendant'), true).find('> .jstree-anchor').focus();
			}
		}, this))

I think it (mainly) happens when I click on an action created with the [actions](https://github.com/alexandernst/jstree-actions) plguin.

**Comment by alexandernst** [comment]
Actually, scratch the last phrase. It happens when I click on the row of a node, outside of the area of the node's text. (I'm using the widerow plugin).

**Comment by alexandernst** [comment]
Actually... This is a weird bug somehow related with the focus event of the nodes.

Have a look here: https://www.youtube.com/watch?v=eKBaOd3uwEU

Note that if I click on a row without hovering the node's text first, I get the error, but if I do hover the text first, I don't.

**Comment by vakata** [comment]
Oh, I see - this happens because you are initially creating an empty tree, so active descendant is not set. I will fix this in a minute.

**Comment by alexandernst** [comment]
Nice! Good job! I'll be waiting for the patch release ;)
