### ISSUE TITLE
Range Select (Shift + LMB) and disabled nodes issue

### ISSUE THREAD

**Issue by Nostalgiaplatz** [vakata/jstree#1089]
Great work on this plugin, it is amazingly powerful and I have found it infinitely useful

I have encountered an issue where when disabling a node using:
```javascript
$('#container').jstree('disable_node', id);
```

The issue arises when using the range selection by clicking shift + LMBand checkboxes, when you are range selecting two nodes if there are disabled nodes within the range they also get checked too even though they cannot be selected by clicking.

Is there a node level parameter you can set to prevent this range selection (as disable_node doesn't seem to do it) or is this a bug?

Thanks

**Comment by Nostalgiaplatz** [comment]
Just to clarify also that this is range selection within the one level so it is not that the disabled nodes have checked as a result of cascading down

**Comment by vakata** [comment]
That is definitely a bug, cascading can not be prevented, but this indeed must be fixed. I will add a fix later today or tomorrow - thank you.
