### ISSUE TITLE
Empty node Title doesn't trigger rename_node

### ISSUE THREAD

**Issue by dotsad** [vakata/jstree#1090]
I want create a new node but leave text value blank for end user to select a new name.
`var sel = refTree.create_node('#',
 {
                        'id': newGuid(),
                        'text': ''
 }, 'last');`

put that node in Edit mode
`ref.edit(sel);`

when user clicks Enter or mouse clicks else where, node is renamed with "".
`"set_text.jstree"` is being called twice, but there is no helpful info in it to distinguish a rename event. 

Is there a possible work around to catch nodes with "Empty" names?

**Comment by vakata** [comment]
Sorry, but I can not reproduce this:
http://jsfiddle.net/DGAF4/449/

In the latest commit there is also a callback function that you can supply to `edit()` if that helps, but please first let me know how to reproduce the problem.

Best regards,
Ivan
