### ISSUE TITLE
get node data on contextmenu

### ISSUE THREAD

**Issue by ridwanhabbal** [vakata/jstree#1092]
Hi, 

I'm using this piece of js: 

('#jstree').on('contextmenu', '.jstree-anchor', function (e) {
			alert(e);
			// you ca easily get the instance using: $('#jstree').jstree(true), and the node using: instance.get_node(e.target);
});

and it's working. however, the action I'd like to do requires me to know on which node the user has right-clicked. could you please assist?

Thanks
Ridwan

**Comment by vakata** [comment]
I really do not understand the question, since the solution is inside the question. What is the problem exactly?

```js
$('#jstree').on('contextmenu', '.jstree-anchor', function (e) {
  var node = $('#jstree').jstree(true).get_node(e.target);
  console.log(node); // everything about the node is here
});
```

**Comment by ridwanhabbal** [comment]
No issues... Thank you for the reply. Actually I didn't know that I can get the node that way. Still new to jstree
