### ISSUE TITLE
Destroy does not completly destroy (html data)

### ISSUE THREAD

**Issue by oshlab** [vakata/jstree#1093]
I have a tree with html data. (needed for styling), with the state plugin. I am loading the entire div holding the tree with ajax. If i destroy the tree using $.jstree.destroy (); and then reload my div that creates the tree with data on the div, through ajax, it gives the tree a new ID and the state is not restored. 

The first time the page loads, the tree has an id of jstree-1 and the elements are j1_1, j1_2 etc. If I destroy the tree then reload my tree div with ajax, the tree now has an id on jstree-2 and the elements are j2_1, j2_2 and so on. 

Is there a way around this without having to load json data? For my application, leaving it as html is best.

**Comment by vakata** [comment]
Maybe this is what you need: http://www.jstree.com/api/#/?q=destroy&f=destroy%28%29

The `keep_html` flag of the `destroy()` function. If this is not it - please clarify and I will reopen the issue.

Best regards,
Ivan

**Comment by oshlab** [comment]
That is not quite it. Ill try to clarify. I have a div on my page that is empty on load. Lets call it navDiv. When the DOM is loaded, I use ajax to pull a php file to the div with jquery .load() function. That file has an html tree that uses the state plugin. It also has the script to create the js tree in it. There is a point where a user will make a change so the tree needs to update. If i reload the entire page, the state plugin works fine. However, if I destroy the tree, and then use jquery load() to reload the tree file into the navDiv, the new tree is given a different id than the original (jstree-2 now) and the state is not restored because the id is different. I am guessing that destroy is not destroying the jstree auto generated id and therefore created an incremented number id going from jstree-1 to jstree-2. If i repeat this process again I get jstree-3. Is there a way to destroy the tree where the next generated is will be jstree-1 again instead of incrementing it. 

Right now, I have everything working great if I reload the entire page when the tree needs to be updated. I would like to just reload navDiv through Ajax if possible.

**Comment by vakata** [comment]
The state plugin is not affected by the tree ID - it has a `key` property in its config, that is `"jstree"` by default, so it will work, provided your nodes have IDs. If you rely on the autogenerated IDs, it will not work, but since you are using state, you should not rely on those IDs.
And to answer your question - no, there is no way to reset the internal counter, but as I tried to explain - you should not have to. If your nodes have defined IDs, and the state is still not restored - let me know and I will have a look.

Best regards,
Ivan

**Comment by oshlab** [comment]
Thanks for your help. I switched to json data and defined ids. That got it working properly. Love this project and thank you for making it and your support.
