### ISSUE TITLE
Open nodes when no childs

### ISSUE THREAD

**Issue by vladanPro** [vakata/jstree#1099]
Problem is when we get information from other API and want to load categories and send request after click click on expand . And we want to show categories that can expand and after someone click to expend then send API request and respond add to tree. When i put
 tmp_array["children"] = true;
i get plus at categories but it can't expend like its lock and documentation is:
"When using AJAX set children to boolean true and jsTree will render the node as closed and make an additional request for that node when the user opens it."
But there is not response of any kind when i try to open it. Thank you.

**Comment by vakata** [comment]
Sorry, but I can not help you without a demo or some code. You have either misconfigured jstree or you are not returning the data properly. I can assure you lazy loading works fine as can be seen in all the demos and jsfiddles I have provided.

For future how-to questions please use the discussion group. Of course feel free to provide a demo or some code here in this issue.

Best regards,
Ivan

**Comment by vladanPro** [comment]
Of course  i am sorry for mistake, here is code:
first json
[
	{
		"status": "success",
		"request":
			{
				"mid":1515
			}
		,
		"categories":[
			{
				"categoryId":123,
				"categoryName":"Drinks",
				"productCount":160,
				"childCount":5
			},
			{
				"categoryId":124,
				"categoryName":"Dessert",
				"productCount":25,
				"childCount":5
			},
			{
				"categoryId":125,
				"categoryName":"Lunch",
				"productCount":246,
				"childCount":5
			}
		]
	}
]

and code:
$(function () {
    var array_json_tree = null;
    $.getJSON("data/tree.json", function (data) {
        array_json_tree = data[0].categories;
        var tmp_set_tree = [];
        if (array_json_tree !== null)
            tmp_set_tree = replace_json_for_tree(array_json_tree);

        $('.js-tree').jstree({
            'plugins': ["wholerow", "checkbox"],
            'core': {
                'data': tmp_set_tree,
                'themes': {
                    'name': 'proton',
                    'responsive': true
                }
            }});
    });

    function replace_json_for_tree(json) {
        var retVal = [];
//        console.info(json);
        $.each(json, function (index, value) {
            var tmp_array = {};
            tmp_array["id"] = value.categoryId;
            tmp_array["text"] = value.categoryName;
            if (value.childCount)
                tmp_array["children"] = "A";
            //ptmp_array["children"] = true; when set to true don't expend
            retVal.push(tmp_array);

        });
        return retVal;
    }

    $('.js-tree').on("before_open.jstree", function (e, data) {
        console.log(data.node.id);
        var url = "data/Drinks.json";
        var jqxhr = $.getJSON(url, function (data1) {
            var tmp_set_tree = replace_json_for_tree(data1[0].categories);
            console.info(data.node);
            $('.js-tree').jstree("delete_node", data.node.id, "inside", tmp_set_tree, false, true);
            $('.js-tree').jstree("refresh.jstree");
        });
    });

    $(document).on("click", "#test-tree", function () {
        var checked_ids = $('.js-tree').jstree('get_checked');
        alert('You have selected: ' + checked_ids);
    });
});

**Comment by vladanPro** [comment]
I figure what is problem but not solution for it. Lazy loading working great, but only when i have children is know variable, but i don't know what children are until someone click on plus mark. On that point i get loading icon and that it is. no before open is called and then i can not add children's dynamically. By the way great  library and great work, thank you. You don't have donating on web site or something like that? Regards.

**Comment by vakata** [comment]
I do have a donate button on the site - jstree.com :)
Anyway - you are not using lazy loading, so you can't expect anything to happen - you are just loading a static object as data. Read the docs on lazy loading - in your case - you should use `core.data` as a function. Something like this:
```js
    $('.js-tree').jstree({
        'plugins': ["wholerow", "checkbox"],
        'core': {
            'data': function (node, cb) {
               if(node.id === "#") {
                 cb(tmp_set_tree);
               }
               else {
                 alert(node.id);
                 /* make a separate AJAX as needed, `node.id` is the node whose children you need to return, 
                    once loaded - call cb with the result:
                    $.post('/some/endpoint', {'id':node.id}, function (data) { cb(replace_json_for_tree(data)); });
                   */
               }
            },
            'themes': {
                'name': 'proton',
                'responsive': true
            }
        }});
```

This is far from optimal code, but you get the idea of using core.data as a function - read the docs on it if this is not enough - there are examples on the front page of this repo.

Best regards,
Ivan

**Comment by vladanPro** [comment]
Its work perfect, thank you vary much.

**Comment by gs-rthati** [comment]
> I do have a donate button on the site - jstree.com :)
> Anyway - you are not using lazy loading, so you can't expect anything to happen - you are just loading a static object as data. Read the docs on lazy loading - in your case - you should use `core.data` as a function. Something like this:
> 
> ```js
>     $('.js-tree').jstree({
>         'plugins': ["wholerow", "checkbox"],
>         'core': {
>             'data': function (node, cb) {
>                if(node.id === "#") {
>                  cb(tmp_set_tree);
>                }
>                else {
>                  alert(node.id);
>                  /* make a separate AJAX as needed,
>                     `node.id` is the node whose children you need to return, 
>                     once loaded - call cb with the result:
>                     $.post('/some/endpoint', {'id':node.id}, function (data) {
>                       cb(replace_json_for_tree(data));
>                     });
>                   */
>                }
>             },
>             'themes': {
>                 'name': 'proton',
>                 'responsive': true
>             }
>         }});
> ```
> 
> This is far from optimal code, but you get the idea of using core.data as a function - read the docs on it if this is not enough - there are examples on the front page of this repo.
> 
> Best regards,
> Ivan

How do I call just a function that returns some json data on demand. I don't want to make ajax call as i have data and also I don't want to load data before creating the tree. I just want load some static data only when a node is opened? How do I handle this case?

**Comment by gs-rthati** [comment]
> I do have a donate button on the site - jstree.com :)
> Anyway - you are not using lazy loading, so you can't expect anything to happen - you are just loading a static object as data. Read the docs on lazy loading - in your case - you should use `core.data` as a function. Something like this:
> 
> ```js
>     $('.js-tree').jstree({
>         'plugins': ["wholerow", "checkbox"],
>         'core': {
>             'data': function (node, cb) {
>                if(node.id === "#") {
>                  cb(tmp_set_tree);
>                }
>                else {
>                  alert(node.id);
>                  /* make a separate AJAX as needed,
>                     `node.id` is the node whose children you need to return, 
>                     once loaded - call cb with the result:
>                     $.post('/some/endpoint', {'id':node.id}, function (data) {
>                       cb(replace_json_for_tree(data));
>                     });
>                   */
>                }
>             },
>             'themes': {
>                 'name': 'proton',
>                 'responsive': true
>             }
>         }});
> ```
> 
> This is far from optimal code, but you get the idea of using core.data as a function - read the docs on it if this is not enough - there are examples on the front page of this repo.
> 
> Best regards,
> Ivan

But these nodes that have "plus"/childs on demand, i want to sort them to the bottom of the list. how can I do that?

**Comment by gs-rthati** [comment]
Please add this kind of stuff in the documentation. I researched for 4 days just for this. Tried many hacks. Thank God and vakata, I finally found it
