### ISSUE TITLE
Disable Collapse nature in jstree

### ISSUE THREAD

**Issue by debayan31** [vakata/jstree#1101]
Hi,

I have a requirement in which I have to "disable collapse nature of any parent node of a jstree".
How can I able to do this?

**Comment by vakata** [comment]
You can do it in two ways:
1) Bind to the `close_node.jstree` event and call `open_node()` like so:
```js
$('#tree').on('close_node.jstree', function (e, data) { data.instance.open_node(data.node); });
```
2) Create a small plugin which overrides the `close_node` function with an empty function, include it in your page and in your `plugins` config array, like so:
```js
(function ($, undefined) {
	"use strict";
	$.jstree.plugins.noclose = function () {
		this.close_node = $.noop;
	};
})(jQuery);
$('#tree').jstree({
  plugins : ["noclose", ... ],
  ...
});
```

Best regards,
Ivan

**Comment by garipovAlbert** [comment]
(function ($, undefined) {
    "use strict";
    $.jstree.plugins.noclose = function () {
        this.close_node = $.noop;
    };
})(jQuery);
$('#tree').jstree({
  plugins : ["noclose", ... ],
  ...
});


doesn't work
Uncaught TypeError: (intermediate value)(...) is not a function

**Comment by DilipRajkumar** [comment]
Nice Ivan, exactly what I am looking for.. thank you..

**Comment by drbarto** [comment]
@vakata Is this still the correct way to control node collapsing?

I tried your suggestion 1), but this led to a strange effect: all expanded nodes can be collapsed exactly once, and afterwards are no longer expandable.

P.S.: I cannot use suggestion 2) because I have a slightly different requirement: I only want to prevent the root node from collapsing, all other nodes should collapse as usual. So in the `close_node.jstree` callback, I check if the closed node is the root node and only then call `open_node`.

**Comment by drbarto** [comment]
If anyone else has the same problem: it seems to be a timing issue; delaying the call to `open_node` works for me:

    setTimeout(function() {
      data.instance.open_node(data.node);
    }, 0);

**Comment by suhas-possible** [comment]
Hello @vakata,
Greetings for the Day.
I have tried the second approach from your suggestions, but it is not exactly matching my requirement, my requirement is as: When We disable the expand/collapse feature of jstree then user will not be able to expand/collapse tree nodes but when we try to expand/collapse using internal API ( by developer for specific use case) then it should be allowed to  expand/collapse via internal API.
Currently, it is disabling expand/collapse using API as well as user interaction.

Looking forward to the answer. Thanks in advance for Help :)

**Comment by suhas-possible** [comment]
Hello @vakata,
Thanks for the quick response. It's working for me.

**Comment by simon1tan** [comment]
I added this to jstree.
```
if(obj.data.disable_close){ 
    return(false)
}

```
Just set your add node "data":{ "disable_close": true} to your node.

**Comment by gabrieldatagol** [comment]
Hey guys, I'm new in javascript and I have a jstree working fine.. but the nodes are closed as default. I just want to open only the root node. Could you guys help me please? This is my js code:
```
<script>

  var lojas = <?=$lojas;?>;

  $(function() {
    $('#jstree').jstree({
      'core': {
        'data': lojas
      },
      'plugins': ['checkbox']
    });
  });

</script>
```
