### ISSUE TITLE
moving node using drag drop plugin 

### ISSUE THREAD

**Issue by MajedDH** [vakata/jstree#1102]
I listen to `move_node.jstree` event and when i move node using drag drop the event is not fired every time i move a node.

It fires for about 80% of moved nodes and 20% of the moves doesn't fire the event

**Comment by vakata** [comment]
Sorry, but this is not possible, there is nothing I can do without a demo. Also keep in mind multitree drops will result in `copy_node.jstree` being fired. If you provide a demo I will reopen the issue.

Best regards,
Ivan
