### ISSUE TITLE
Dynamically resizing jstree container to fit width of items as they are expanded

### ISSUE THREAD

**Issue by joshuaterrill** [vakata/jstree#1105]
I've got a jstree in a container that I would like to horizontally expand as items of the jstree are expanded. Here is a jsfiddle describing my current situation: http://jsfiddle.net/0xwg3c2c/

How can I accomplish this?

**Comment by vakata** [comment]
This is not jstree related, but still: http://jsfiddle.net/0xwg3c2c/4/

Best regards,
Ivan
