### ISSUE TITLE
move_node has no option to suppress event

### ISSUE THREAD

**Issue by robmeek** [vakata/jstree#1106]
This would be useful to me. 

In my application I am interested in listening to  "move_node.jstree" when the user drags nodes around - so I can update my model. When the model changes, independently of jstree, I use move_node to update the tree - In this case I don't want "move_node.jstree" to be triggered.

I have a workaround involving setting a flag when dragging and dropping but its ugly and an option to suppress the event (in line with other jstree methods) would be more elegant.

I can prepare a PR if that makes sense to you.

**Comment by vakata** [comment]
The only method that can be suppressed is the `changed.jstree` and it is only temporarily suppressed by plugins to avoid triggering it multiple consecutive times. Sorry, but I do not think such an option is usable, and it will likely just cause confusion.

However you can easily add your own plugin that overrides the `move_node` and `copy_node` functions and accepts an additional parameter which controls whether the event is triggered. That way you can include this in the instances you need it active.

As for changes to the model - maybe a `.refresh()` call will be a lot more reasonable than invoking `move_node`, but it all depends on your config.

Best regards,
Ivan

**Comment by robmeek** [comment]
Thanks for the prompt response and excellent repo. I'll consider the plugin option.
