### ISSUE TITLE
Question: How can I use DND for dropping an outside element?

### ISSUE THREAD

**Issue by mariorodriguespt** [vakata/jstree#1107]
In my use case I'm using a tree to show the folders and the files are represented in another container. When I drag a file from it's container to a jstree, I would like to get the same functional when I drag and drop a node inside the tree, special with the folders opening feature on the mouse over.

Is this possible with DND plugins?

**Comment by vakata** [comment]
Check the first and only pinned topic in the discussion group:
https://groups.google.com/forum/#!topic/jstree/BYppISuCFRE

Best regards,
Ivan
