### ISSUE TITLE
Edit New issue Can we limit the number of search result (follow up)? 

### ISSUE THREAD

**Issue by zfy0701** [vakata/jstree#1109]
Hi, sorry for filing the same issue I filed before:

https://github.com/vakata/jstree/issues/1100
but it seems we can't continue discuss it after it being closed.

so yes, I understood that we could limit the input the length, but that doesn't works for us, there are lots of cases that even you enter 5 or characters the results are still too much, while in some cases one character is perfectly fine to just enter 1 characters.

I would be happy to contribute patches if this feature is blessed and would be great if you could give us some guidance how to do this.

**Comment by vakata** [comment]
There is no problem with discussing the issue in one place.
