### ISSUE TITLE
set_state destroys the passed state

### ISSUE THREAD

**Issue by alexandernst** [vakata/jstree#1110]
The `set_state` method wipes the data in the object that is passed to the function. Took me a while to figure that out. 

    var state = { core: { ...state... }};
    console.log(state); // <--- shows the content of "state"
    my_tree.set_state(state);
    console.log(state); // <--- empty object

I'd expect either `set_state` not to touch the state I'm passing or mention that behavior in the docs.

**Comment by vakata** [comment]
Thanks - I will mention it in the docs with the next release.
