### ISSUE TITLE
jsTree with Turbolinks 3.0. Three isn't working when new page loaded.

### ISSUE THREAD

**Issue by ginolon** [vakata/jstree#1118]
I'm using Turbolinks 3.0 from github, last version:

https://github.com/rails/turbolinks

and when I load the page with it (the menu isn't reloaded in the page), what change is just the part of page I need to update (not via ajax, with tubolinks's system), with your code or also with default double click jstree not open anymore the three...

Why?

If the menu is already open (by default), when I reload the page (again with turbolinks 3.0 partial replacement) when I click on a three it reopen itself.

Why?

**Comment by vakata** [comment]
Sorry, I am not familiar with Turbolink, I can assure you jstree will make no conflicts with any tools you may be using - it is self contained.
If something is not working it must be related to the way you are creating the tree or manipulating the DOM with the tree in it, which means I can not help you without a demo, but rest assured - it is not a bug with jsTree.

**Comment by ginolon** [comment]
Now I've just discovered something:

If i start with first load of the page let's say here:

**localhost/books/**

the jsTree start good and everything works excellent

(Turbolinks 3 partial replacement has not yet been called!)

I click on a node (the links is like this above):

```ruby
<%= link_to "Something", choose_category_path(category.name), remote: true %>
```

and the new page is loaded with Turbolinks 3 partial replacement.

Now the page is like this:

**localhost/books?category=Thriller**

and jsTree is frozen at the same level before the click (the node's levels are opened where I opened them because of partial replacement)

but now I can't click on the node because it don't works.

If I click again on another or the same link of before (the link's structure are the same of the first one) **the jsTree came back to works again! MAGICAL! And now it's still Turbolinks 3 Partial replacement! Absurd!**

Why this?

I add in application.js this code:

```javascript
var ready;

ready = function() {
    $('#menu').on('click', '.jstree-anchor', function (e) { $(this).jstree(true).toggle_node(this); });
}

$(document).ready(ready);
$(document).on('page:load', ready);
```

Where am I wrong?

**Comment by vakata** [comment]
TurboLinks is most probably replacing the `#menu` node (or one of its parents) and then you lose all event bindings - once again - I can not help you with this - I hope the maintainers of Turbolinks can help you. If the DOM is intact OR if you recreate the tree after its DOM node is replaced everything will work as expected.

**Comment by ginolon** [comment]
If I use this code it doesn't work because it don't close the tree, it just reopen the node!

```javascript
var ready;
var change;

ready = function() {
    something
}

change = function() {
  $('#menu').on('click', '.jstree-anchor', function (e) { $(this).jstree(true).toggle_node(this); });
  alert("Change!");
}

$(document).ready(ready);
$(document).on('page:load', ready);
$(document).on('page:change', change);
```

If I change the line:

```javascript
 $('#menu').on('click', '.jstree-anchor', function (e) { $(this).jstree(true).open_node(this); });
```

it works. But I have to close the tree with icon e not with single click on node!

**Comment by ginolon** [comment]
A guy (@vizo) on this thread tell me a way to fix the problem:

https://github.com/rails/turbolinks/issues/535#issuecomment-102788732

```javascript
$('#menu').off('click.jstree').on('click.jstree', '.jstree-anchor', function (e) {
  $(this).jstree(true).toggle_node(this);
});
```

I now don't knwo why, but it works!

Why?

**Comment by vizo** [comment]
@ginolon because if page:change is triggered more then once (it happens when you don't do full refresh of page, but on every partial change), $('#menu').on('click', ... was called more than once. 

So if it was called for example twice, when you clicked on #menu it was called two times toggle_node(this).

It is same like you would write it twice:
```javascript
$('#menu').on('click', '.jstree-anchor', function (e) {
  $(this).jstree(true).toggle_node(this);
});
$('#menu').on('click', '.jstree-anchor', function (e) {
  $(this).jstree(true).toggle_node(this);
});
```
toggle_node(this) will be called twice on single mouse click. First time it will open node, and second close it again ...
