### ISSUE TITLE
dnd doesn't work after a destroy

### ISSUE THREAD

**Issue by ncolboc** [vakata/jstree#1120]
Hello,
I noticed that since version 3.0.4, drag and drop doesn't work anymore if I recreate a tree after calling jsTree('destroy'). works as expected in 3.0.3.
same as issue #621 

Best regards,
Nicolas

**Comment by vakata** [comment]
Please provide a demo, from what I see it is working fine in 3.1.1:
http://jsfiddle.net/DGAF4/508/

Best regards,
Ivan
