### ISSUE TITLE
selecting node from code should bring selected node to view

### ISSUE THREAD

**Issue by MajedDH** [vakata/jstree#1121]
When having large trees selecting node from code should make the tree scrolled to the selected node .

Is there some method i forgot in the api? Or it's just missing?

I usually do `tree.deselect_all` and then `tree.select_node` how to make the tree scroll to it automatically?

**Comment by vakata** [comment]
If the select is from user input - the node will be scrolled. There are many cases where programmatic selection should not scroll the node into view. Just add:
`tree.get_node(node, true)[0].scrollIntoView()`

Best regards,
Ivan
