### ISSUE TITLE
Error in checkbox check_all()

### ISSUE THREAD

**Issue by teo89** [vakata/jstree#1124]
I am using checkbox plugin. I make a call of check_all() like that 

$scope.treeReady = (e, data) ->
      $scope.treeInstance.jstree(true).check_all()

Everything looks fine but in browser console i get that error:
TypeError: $scope.treeInstance.jstree(...).check_all is not a function

I called all plugin methods and all of them shows the same error.

**Comment by vakata** [comment]
You are most likely using an older version of jsTree, where `check_all` was not added yet. 

Also keep in mind your angular container may not expose all functions - you'd better file a bug with the creators of the angular container.

Best regards,
Ivan
