### ISSUE TITLE
Getting the node data in contextmenu actions

### ISSUE THREAD

**Issue by IonicaBizau** [vakata/jstree#1126]
When I right-click the context menu is opened. When I click the item (e.g. *rename*), I want to access the node data:

```js
contextmenu: {
    items: {
         rename: {
             label: "Rename"
             action: function (node) {
                 // How can I get here the full path?
             }
         }
    }
}
```

So, inside of the action function I want to access node data. Also, if possible, how can I make the item renamable (the user to have friendly way to rename the item)?

Thanks! :apple:

**Comment by vakata** [comment]
I guess this is what you need :) https://github.com/vakata/jstree/blob/master/src/jstree.contextmenu.js#L83

Keep in mind you can call whatever methods you want once you have the instance in the first row of the function.

Best regards,
Ivan

**Comment by IonicaBizau** [comment]
@vakata I have the reference, but I don't know how to get the node data that is associated with that node.

**Comment by vakata** [comment]
Well, it is there - in the above link:
```js
"action" : function (data) {
    var inst = $.jstree.reference(data.reference),
        obj = inst.get_node(data.reference);
    ...
```

The second row gets the node data.

Best regards,
Ivan

**Comment by IonicaBizau** [comment]
@vakata Thanks a lot! It figured it out:

```js
var inst = $.jstree.reference(data.reference)
  , item = inst.get_node(node.reference)
  ;

console.log(item.original); // output the node data
```

:sparkle:

**Comment by moeinifar** [comment]
var inst = $.jstree.reference(node.reference),
obj = inst.get_node(node.reference);
console.log(inst);
console.log(obj);
