### ISSUE TITLE
Move problem

### ISSUE THREAD

**Issue by mark1917** [vakata/jstree#1127]
Hi, Ivan.
I use jstree on my site in the admin panel to manage the directory structure. All DATA keep in MySQL and use your class class.tree.php.
I noticed a serious error in the program, but I can not figure out how to fix it.
When I create multiple nodes with children:
Menu
-Root1
--1.1
--1.2
--1.3
-Root2
--2.1
--2.2
--2.3

And then I try to select and move nodes from one node to another, I get a strange structure:
1) In a parent node few children have the same position number (field pos in Database) 2) Incorrectly calculates the field right index (field rgt in Database) 3) The entire structure of the tree breaks.
At first I thought it was a mistake somewhere in my code, but then you look at the site in Database demo. It turned out that it is exactly the same mistake.
Please, Ivan, help deal with the problem.
Thanks in advance.

**Comment by vakata** [comment]
Sorry, the PHP part is for demo purposes only and I do not support it, it is not thoroughly tested. However, I have not seen such an issue in the places where I use this code. I will have a look but I can not guarantee I will be able to reproduce and fix. 

This is not part of jstree so I will close the issue, but I will keep you posted.
