### ISSUE TITLE
I think the api documentation is too simple, it is difficult to understand

### ISSUE THREAD

**Issue by whstudy** [vakata/jstree#1129]
I think this is the official website jstree plugin api documentation is too simple, it is difficult to understand

**Comment by vakata** [comment]
Hi,

Please search the issues here for "documentation" and you will find my position on this. I do not accept tickets regarding documentation quality - I accept pull requests.

I am aware the docs are not great, but it is the best I can do. I am not keeping the docs "bad" on purpose. There is also no point in time where the docs will be perfect, so I do not think having issues about it helps, there will be no moment where I can close an issue regarding the docs and say there is no more work to be done (this is why I close all issues related to the quality of the docs).

I try to make up for my inability to write quality documentation by helping actively in the discussion group and on stackoverflow. Once again - please - create pull requests for anything in the docs that you think should be better.

Best regards,
Ivan
