### ISSUE TITLE
Drag and drop out side of tree

### ISSUE THREAD

**Issue by RajivGoaple** [vakata/jstree#1130]
I want to drag file and drop it to outside tree ..how can I achieve it.

**Comment by vakata** [comment]
Here is a guide: https://groups.google.com/d/msg/jstree/BYppISuCFRE/KKh7oHZzNkwJ 

Please use the discussion group for how-to questions.

**Comment by RajivGoaple** [comment]
Ok Thanks!!

**Comment by RajivGoaple** [comment]
using 'dnd_move.vakata'  and 'dnd_stop.vakata' its working now i.e dragging file outside the tree.

but now its not working for inside tree ,
I am not able to drag file into folder now.

any guess?

Thanks!

**Comment by vakata** [comment]
Have you set `check_callback` in your tree config?

**Comment by RajivGoaple** [comment]
no.. .

please can you tell me how to set it.

Thanks!

**Comment by RajivGoaple** [comment]
yes I have written this

 $('#tree')
              .jstree({
                  'core': {
                      'check_callback': true
                  }, 

but not working

**Comment by RajivGoaple** [comment]
Ivan,

I have written 

  $(document).bind('dnd_move.vakata', function (e, data) {})

and 

$('#tree').on('move_node.jstree', function (){})

I expect here .. for dragging outside of tree 'dnd _move' event should call and for dragging within tree 'move_node.jstrr' should get call


but this is not the case here ...here for both the situations 'dnd_move' is calling...and i have diffrent logic for both 

please can you suggest anything .
 

Thanks!!

**Comment by vakata** [comment]
Please read the docs on the `dnd_` events:
http://www.jstree.com/api/#/?q=dnd_

`dnd_move` will always fire when mousemove fires and you are dragging something - you probably need `dnd_stop` which will always fire when something is dropped. 

`move_node` will fire when a node is moved in a tree - which may be caused by a previous `dnd_stop`. If you do not want to handle drops on a tree in `dnd_stop` - the link I gave you already has the code for that:
```
 if(!t.closest('.jstree').length) {
   ...
```

**Comment by RajivGoaple** [comment]
I got your point but becuase of dnd event 

'move_node'  is not getting call when i drop file on folder..

**Comment by vakata** [comment]
Sorry, I must have clarified - when dropping an external node the event that fires is `"copy_node.jstree"`. Here is a demo with the code I mentioned before:
http://jsfiddle.net/DGAF4/517/

Best regards,
Ivan

**Comment by RajivGoaple** [comment]
Ivan ,

First thanks for quick response :)

I have a tree

i was previously handling move event of file in tree itself by event 'move_node'

after that i have added dnd event 'dnd_move.vakata' and 'dnd_stop.vakata'
for handling dragging file outside tree

but now when i drop file in tree itself, it calls 'dnd_stop' event where i am not handling dropping on itself ..i am handling it in 'move_node' event which is not get fire now ..i think because of dnd events



so my logic is in 2 places 1 for drag file in tree itself which i have written in 'move_node' function

and 2nd for dragging outside tree which i have written in 'dnd_stop' event 


so problem is 'move_node' is not getting call ...what should i do ...should i move my logic in 'move_node ' in dnd event or what


Thanks

**Comment by RajivGoaple** [comment]
Ivan,

I have two trees in same page , for one tree i have facility to drop outside so i have bind  dnd_move.vakata and dnd_stop.vakata to document object but because of this the second tree's drag drop not working ......cant we bind dnd_stop to tree element

Thanks

**Comment by vakata** [comment]
Please provide a demo of the `move_node.jstree` event not being fired. I can assure you `move_node.jstree` and `copy_node.jstree` will always fire, regardless of the fact that you have bound handlers to `dnd_move` and `dnd_stop`.

If you have two trees and only want to share nodes between the two trees you do not need to use `dnd_stop` - just listen for `copy_node.jstree`. When moving a node from one tree to another tree `cope_node.jstree` will be triggered onm the receiving tree.

Please be more precise next time - are you moving nodes between trees or do you have drop & drag targets that are not trees, I can not help you if you do not give me the full information. 

Still - just listen for `copy_node.jstree` & `move_node.jstree` - they will always work (as shown in the fiddle I provided).
