### ISSUE TITLE
Reload tree

### ISSUE THREAD

**Issue by IonicaBizau** [vakata/jstree#1131]
I fetch data from server and after something changes I want to reload the tree. How can I do that?

**Comment by vakata** [comment]
Use the `refresh()` method. Here is its signature & docs:
http://www.jstree.com/api/#/?q=refresh%28%29&f=refresh%28%29

Would you please use the discussion group for how-to questions:
https://groups.google.com/forum/#!forum/jstree

Best regards,
Ivan

**Comment by IonicaBizau** [comment]
@vakata Thanks!

> Would you please use the discussion group for how-to questions

Sure, are you active on StackOverflow? If so, I'd be happy to ask there and give you points. :smile:

**Comment by vakata** [comment]
Yes, I try to answer all `jstree` tagged questions every day: 
http://stackoverflow.com/questions/tagged/jstree

**Comment by IonicaBizau** [comment]
Oh, that's cool! Then I ask there the new questions! :+1: :sparkles:
