### ISSUE TITLE
Editing last created node

### ISSUE THREAD

**Issue by hwdavies** [vakata/jstree#1132]
I am currently putting newly created nodes straight into edit mode through the following function:

```js
function edit_last() {
   $('.myTreeList').jstree().edit('.jstree-last:last')
}
```

However, when adding multiple nodes repeatedly on Internet Explorer.. many of the new nodes that get created are left without a name.. any known issues with this/why this may be?

Thanks in advance.

**Comment by vakata** [comment]
This was a known bug (fast renames) with IE, that was fixed a while ago - which version are you using? Keep in mind `.jstree-last` is not at all reliable - use the `create_node.jstree` event and invoke edit from there:
```js
$('.myTreeList').on('create_node.jstree', function (e, data) {
    data.instance.edit(data.node);
});
```

Best regards,
Ivan
