### ISSUE TITLE
On keypress, checking for "INPUT" tag name can fail

### ISSUE THREAD

**Issue by Truplic** [vakata/jstree#1133]
The input element is created as:
$("<"+"input />", ...
so it is not understandable why the if statement is using capital letters. I suggest something like:

 if(e.target.tagName.toLowerCase() === "input") { return true; }

**Comment by vakata** [comment]
Thank you for spotting this. 

I have not ever seen this fail (maybe because I test using HTML documents), but it could fail (especially in XML based documents): 
https://developer.mozilla.org/en-US/docs/Web/API/Element/tagName

Best regards,
Ivan

**Comment by Truplic** [comment]
Yes, it was failing on XHTML document.
Thanks for the quick reaction.
