### ISSUE TITLE
Question: When a parent is checked load all children of the parent

### ISSUE THREAD

**Issue by DanLawrence82** [vakata/jstree#1134]
Hi Vakata,

I sent an issue last week mentioning i had a dataset of 16000+ records and did not want them to load all at the start. Just so you know turning the worker off didn't really help that much but lazy loading made a huge difference. 

Now that i'm using lazy loading I would like to know, what is the best way to load all children when you select the parent node's checkbox? I can check the parent then open it and all the children are selected, but i would like it to open all children nodes and possibly other parents below it.

Thanks for the help!

**Comment by vakata** [comment]
Try the `open_all` method with its first argument:
http://www.jstree.com/api/#/?q=open_all&f=open_all%28[obj,%20animation,%20original_obj]%29

Best regards,
Ivan
