### ISSUE TITLE
edit callback not working

### ISSUE THREAD

**Issue by andytorres** [vakata/jstree#1136]
Hi:
I am creating a new node using this:
```javascript
    $node = tree.create_node('#', {'icon': 'glyphicon glyphicon-folder-open', 'text': 'New item', "li_attr": {'type': 'tab'} });
    tree.edit($node, null, function(){
        console.log("callback");
    });
```
The node is being created and put in edit mode, but it isn't printing nothing to the console. Is it something with the callback function?

**Comment by vakata** [comment]
You are probably using an older version. Edit callback was added in 3.1.1. If you are using 3.1.1 and still not getting anything I will reopen the issue. You can check the version using `$.jstree.version` in the console.

Best regards,
Ivan

**Comment by andytorres** [comment]
That was it. I was using 3.0.9. Upgraded to 3.1.1 and it worked. Thanks a lot, Ivan!
