### ISSUE TITLE
Link to the official NuGet package

### ISSUE THREAD

**Issue by Eagle3386** [vakata/jstree#1137]
Currently, there are two JSTree versions available via NuGet:

jsTree 3.0.0 - https://www.nuget.org/packages/jsTree
and
jstree 3.1.0.5 - https://www.nuget.org/packages/jquery.jstree

Unfortunately, none of them is up to date (3.1.1 is currently the latest stable version) and as a new user, I just can't figure out which version is the official one.

Therefore I'm requesting some sort of an "official note" regarding which package to use and maybe taking over the package and/or getting the package updated to the latest stable version.

**Comment by vakata** [comment]
I wanted to maintain the package myself, but the name "jstree" was already registered. The person who registered it said he would maintain it, but did not transfer the name to me. I will get in touch with him.

Best regards,
Ivan

**Comment by Eagle3386** [comment]
Hi Ivan,

after opening this issue, I've contacted the the NuGet package author, too and asked him to update the package.
Maybe you both can negotiate the package maintenance or kind of automate the release workflow?

Thanks in advance.

Best regards,
 Martin

**Comment by vakata** [comment]
Hi again,

Tom and I have already discussed this a year or so ago and the current setup was the only possible option, I doubt that has changed. From what I see there is no way to add a webhook to publish all github tags as a nuget package version.

As for linking to the package on nuget - I will not do that for two reasons:
1) I do not control the package on nuget
2) I have not adopted such a practice - jstree is published on npm, packagist and a lot of other places, but I do not link to them from jstree.com - I do not see why nuget should be any different. If I ever decide to link to the other repos I will include nuget as well.

Best regards,
Ivan
