### ISSUE TITLE
Offer mapping for jsTree properties

### ISSUE THREAD

**Issue by Eagle3386** [vakata/jstree#1139]
AFAICT, jsTree (unexpectedly, TBH) enforces its users to write lowercase property names, e. g. "id" instead of "ID" (or at least "Id") or "parent" instead of "Parent".

Coming from the C# / .NET side of the Force, this is unusual and to help others hitting this problem, too, I'd like to request a mapping feature.

**Comment by vakata** [comment]
As mentioned a lot of times (if you for some reason can not properly map properties on the server side) you can convert from one structure to another either in jQuery's `dataFilter` AJAX config option, or by setting jsTree's `core.data` to a function and handling the mapping yourself.

If you want to you can create a plugin to help other .net users (although to be honest there have not been a lot of request for this, if any) you can create a simple plugin that overwrites the `_parse_model_from_json`, converts the data (in whatever way you want) and calls the parent function:

```js
// mapping
(function ($, undefined) {
	"use strict";
	// use this if you need any options
	$.jstree.defaults.mapper = {
		option_key : "option_value"
	};
	$.jstree.plugins.mapper = function () {
		this._parse_model_from_json = function (d, p, ps) {
			// d is the node from the server, it will be called recursively for children,
			// so you do not need to process at once
			/* // for example
			for(var i in d) {
				if(d.hasOwnProperty(i)) {
					d[i.toLowerCase()] = d[i];
				}
			}
			*/
			return parent.activate_node.call(this, d, p, ps);
		};
	};
})(jQuery);
```

Now you can include mapper in your plugins config array if needed. The example logic I provided is very simple - implement whatever transformations you need.

Best regards,
Ivan

**Comment by Eagle3386** [comment]
Could you help me once more, regarding settings core.data to do the mapping, please?
I tried
```javascript
(...)
data: {
        url: function (node) {
          return ("/TreeController/GetNodes" + (node.id === "#" ? 0 : node.id));
        },
        dataType: "json",
        data: function(node) {
          return {
            ID: node.id,
          };
        },
(...)
```
but that didn't work. It's surely something pretty simple, but I'm missing the forest for the trees. :(

**Comment by vakata** [comment]
The plugin above would have been a better option, but still:

```js
(...)
data: function (node, cb) {
        $.ajax({
            url: ("/TreeController/GetNodes" + (node.id === "#" ? 0 : node.id));
            dataType: "json",
            data: { ID: node.id }
        })
        .done(function (data) {
            var i, j, tmp;
            for(var i = 0, j = data.length; i < j; i++) {
                for(var tmp in data[i]) {
                    if(data[i].hasOwnProperty(tmp)) {
                        data[i][tmp.toLowerCase()] = d[i][tmp];
                    }
                }
                cb(data);
            }
        });
(...)
```

**Comment by Eagle3386** [comment]
Sorry for the delay.
Fortunately, I was able to change JSON parsing on the server's side (thanks to Newtonsoft.Json and "JsonConvert.SerializeObject()"), so no need for additional mapping.

However, due to your great support, I'd like to give something back and therefore I'd like to implement the mapping plugin. But since it's quite new for me (never been that deep in the JS forest of life ;)), it'll probably take some time.
