### ISSUE TITLE
Please offer additional wholerow styling option

### ISSUE THREAD

**Issue by Eagle3386** [vakata/jstree#1142]
You can format the anchor, its icon and the actual line's text by inserting (a) CSS class(es) into the "icon" property which is transferred with the JSON data to the client.

But while working on a jsTree style which uses the "wholerow"-plugin, I discovered that there's no way to set a row's background-color depending on a given CSS class via the JSON data returned from the server.

It would be very nice to have such a feature. :)

**Comment by vakata** [comment]
Actually you can:
1) Supply a `li_attr` property for each node you want to modify, that property should contain an object, which has a key named `class` - set that to whatever you need: 
`{ "id" : 1, "text" : "1", "li_attr" : { "class" : "my-custom-class" } }`
2) Specify CSS to modify the looks of the node: 
`#tree .my-custom-class > .jstree-wholerow { background:red; }`

This should be enough to get you going - you can modify selected & hovered colors, etc.

Best regards,
Ivan

**Comment by Eagle3386** [comment]
Ivan, you're awesome! Thanks a lot! :+1: :smile:
