### ISSUE TITLE
indicator arrows

### ISSUE THREAD

**Issue by andytorres** [vakata/jstree#1143]
Hi:
I am using jstree in different pages within my website, but in one page, when I drag nodes, I can see the position indicator arrows(before, after and inside), but when I change to the other page, I can drag and drop, but I don't see the indicator arrows. I am importing the same jstree library in both pages... what could I be overriding in the second page? 
Thanks in advance, 
Andy

**Comment by vakata** [comment]
Sorry, I can not help you without a demo. It might be a z-index issue. If it is - try changing the z-index on this selector `#jstree-marker`.

If this does not resolve the issue - please provide a demo (for example a jsfiddle) and I will reopen the issue.

Best regards,
Ivan

**Comment by andytorres** [comment]
Yep, it's a z-index issue. However, for those who are using jstree with Bootstrap, take this into consideration: Bootstrap modal has a z-index of 1040. If you put a jstree inside a modal, the drag&drop markers won't be visible. So, a quick fix:
```css
#jstree-marker{
	z-index: 2000; /*Any value above 1040 will do*/
}
```
Thanks for the tip, hope this helps others,
Andy

**Comment by vakata** [comment]
I am glad it is working for you, however I will not make any changes - I will not participate in z-index wars. I have explained this a lot of times here. 

If you need anything - don't hesitate to ask.

Best regards,
Ivan
