### ISSUE TITLE
Is there any possibility to use both 'checkbox' plugin and additional checkboxes inside an item?

### ISSUE THREAD

**Issue by Patlatus** [vakata/jstree#1145]
Is there any possibility to use both 'checkbox' plugin and additional checkboxes inside an item?

When I try to do so, additional checkboxes are checked or unchecked if checkboxes before an <li> item are checkbed or unchecked.
I am trying to get them work independently, but looks like this is impossible. Am I wrong?

**Comment by vakata** [comment]
There is no such built-in functionality, but you can build a simple plugin that adds this functionality - look at `src/misc.js` for example plugins.

Best regards,
Ivan
