### ISSUE TITLE
Trigger content menu event

### ISSUE THREAD

**Issue by hanspeter1** [vakata/jstree#1148]
Is there a way to trigger a context menu “action-event” (Rename, Delete ..) by clicking some button?

**Comment by vakata** [comment]
Just copy the code of that event and execute it. 

You cannot use the contextmenu actrion directly as it takes some parameters that will be harder to mimic than to simply use the API. 

Read the API docs to see the function reference - you are looking for `create_node`, `edit` and `delete_node`.

Best regards,
Ivan
