### ISSUE TITLE
Hide a specific node

### ISSUE THREAD

**Issue by teo89** [vakata/jstree#1149]
Hello i am trying to do a simple thing. I am trying to hide a child node in a closed tree. I tried that 

var treeNode = document.getElementById(id);

    if (true) {
        $(treeNode).hide();
    }

But i don't get any element because that element will be create only when you open his father node.
There is any way to configure that like we can make a node to be opened or not ( node.state{opened : true } )

**Comment by vakata** [comment]
No, sorry, jstree will not support hiding nodes, the only plugin that hides nodes is the search plugin, but this is not what you are looking for.
Sorry, I do not plan on adding hide/show functionality.

Best regards,
Ivan

**Comment by teo89** [comment]
ok thanks, I suppose you don't know if there is any work around for my issue?

**Comment by horans** [comment]
1. set *li_attr* of a node to *"class":"node-hidden"*
2. set *.node-hidden { display:none; }* in your css
