### ISSUE TITLE
checkbox tie-selection initialization with json data

### ISSUE THREAD

**Issue by tharasp** [vakata/jstree#1152]
I am using `jstree` + `checkbox plug-in` along with `jstreegrid`. I have a `json` which I get from database for rendering the tree. The `selected` property of `state` is set to true/false based on whether I want to check / uncheck each node. 

I use `whole_node = false` since I have a number of `select` boxes in grid for each node and I don't want `checkbox` selections to change when users interact with elements in grid. With `whole_node = false`, as a click on any node will de-select other checkboxes, I used `tie-selection = false`. 

But now I get all checkboxes as unchecked and the `selected` property of `state` does not seem to be used. The doc says a separate internal array will be used by checkbox plug-in if `tie-selection = false`. Is there a different way for setting checkbox selections/deselections when `tie-selection = false`.

**Comment by vakata** [comment]
Yes, the `checked` property, which works exactly as the `selected` property, but only when `tie_selection` is `false`.

Best regards,
Ivan

**Comment by jack-gaojz** [comment]
> Yes, the `checked` property, which works exactly as the `selected` property, but only when `tie_selection` is `false`.
> 
> Best regards,
> Ivan

If we enable the "tie_selection" setting, the "changed.jstree" event will not work. :(
