### ISSUE TITLE
open_node should open node even if not visible

### ISSUE THREAD

**Issue by gauravjhs** [vakata/jstree#1153]
If a node is hidden from from user view and if we pass on the id, then tree should open all it's parents as well.

**Comment by vakata** [comment]
I do not think this is an agreed upon standard. `open_node` opens a particular node (or nodes) it would break existing functionality to automatically reveal all parents.

You can do that yourself either by:
 * passing an array to `open_node(nodes)`

or by 

 * using the dedicated function that does this: `_open_to(node)`

Best regards,
Ivan
