### ISSUE TITLE
Tree overlapped

### ISSUE THREAD

**Issue by sebastienserre** [vakata/jstree#1154]
Hello

I'm trying to use a backup tool using jstree in an old version and when I deploy more than 2 levels, the tree is overlapping itself with other entry ....
as a pics is better than an explanation... 

![backup](https://cloud.githubusercontent.com/assets/3902621/8194572/cb8ac648-147c-11e5-82d5-442231dd62ec.png)

could you please help me?

Many thx

**Comment by vakata** [comment]
Maybe you do not have a doctype? jsTree works properly only in standards mode. Btw, I have not seen this bug in quite a long time - is this jstree v.1 or v.3?
If the doctype is not the reason I will reopen the issue (provided it is about v.3).

Best regards,
Ivan
