### ISSUE TITLE
Can't use types with JSON data

### ISSUE THREAD

**Issue by ddevlin13** [vakata/jstree#1157]
jsTree v3.1.1

Using jSON data to lazy load my tree.  I am running into an issue when trying to use the types plugin. Here is the problem:

 - In order to get the type to be recognized, you must add data-jstree='{ "type": "typename" }' to the LI tag for the item.  

 - In order to get this attribute onto the LI when using JSON data, you must use the li_attr object since you do not have any actual HTML to modify

 - when li_attr object renders, the attribute is written as data-jstree="{ "type": "typename" }" (note the outside double quotes)  This is not valid markup

**Comment by vakata** [comment]
Why would you use the HTML syntax if you are using JSON? Simply add the `type` property to your JSON data:
```
[{ "id" : "some-id", "text" : "Node title", "type" : "typeName", ... }, ... ]
```

Best regards,
Ivan

**Comment by ddevlin13** [comment]
I actually tried that first, but it did not work.  I only found the data-jstree approach after searching for an answer why... going back to that approach, here is what the data for my root nodes (the only ones that need a type) looks like:

```
[
	{"id":"2","text":"Vision Systems - In-Sight","children":true,"type":"top"},
	{"id":"3","text":"Industrial ID - DataMan","children":true,"type":"top"},
	{"id":"5","text":"Vision Sensors - Checker","children":true,"type":"top"},
	{"id":"6","text":"Vision Software - All Products","children":true,"type":"top"},
	{"id":"132","text":"Vision Software - OmniView","children":true,"type":"top"},
	{"id":"124","text":"Accessories - All Products","children":true,"type":"top"},
	{"id":"7","text":"Services - All Products","children":true,"type":"top"}
]
```

Here is my tree configuration:

```
$("#jstree").jstree(
{
	"core":
	{
		"data": function (node, callback)
		{
			var id = node.id == "#" ? 0 : node.id;
			var nodeData = GetNodeData(id);

			callback.call(this, nodeData);
		},

		"themes": { "icons": false }
	},

	"types":
	{
		"top": { "max_depth": 2 }
	},

	"plugins": ["types"]
});
```

The depth on these top level items are not being restricted - I can open down to five levels (that max my tree actually has).  I do not see the type set anywhere in the markup, which is why I figured this wasn't working.

What am I missing?

**Comment by vakata** [comment]
I believe I already answered this in your groups post - please restrict to asking in a single place :) Github is for issues, Groups is for how-to questions (as is StackOverflow with a `jstree` tag).

Here is the answer:
https://groups.google.com/forum/#!topic/jstree/PWfzFJHAEFk

The short version - `max_depth` restricts user interaction (creating, copying, moving) not what you as the developer populate the tree with.

Best regards,
Ivan
