### ISSUE TITLE
jstree.com not available

### ISSUE THREAD

**Issue by jamiya** [vakata/jstree#1158]
Hello i'm using jstree these days so i need documentation. When the website available tnx?

**Comment by vakata** [comment]
Sorry, I can't help you without knowing where you are located. I recently switched DNS entries, so that might be the cause of the issue. However I have no problem accessing the server.

Please share your location so that I can check with my hosting provider.

Best regards,
Ivan

**Comment by Programie** [comment]
Hi, I'm having the same issue.

The website is available but really slow.

I'm located in Germany.
