### ISSUE TITLE
create node with data-jstree?

### ISSUE THREAD

**Issue by rodrigoporcionato** [vakata/jstree#1161]
Hi,

How to create a new node with data-jstree specific?

I try this,but not work:

              createItem: { 
                label: "Create Folder",
                action: function (data) {
                    var inst = $.jstree.reference(data.reference),
                    obj = inst.get_node(data.reference);
                     
                    inst.create_node(obj, {"attr":{ "idCat": 9999999, "opened" : true, "subfolder": true, "abrirdoc":true }}, "last",
                        function (new_node)
                        {
                            new_node.data = { file: false };
                            setTimeout(function () {
                                inst.edit(new_node);

                            //$.ajax({
                            //    type: "POST",
                            //    url: "/documentos/CreateFolder",
                            //    data: "idCat="+ idCat +"&name=Nova Pasta",
                            //    dataType: "json",
                            //    success: function (response) {
                            //        console.log("CreateFolder => " + response);
                            //    }
                            //});

                        }, 0);
                    });                   

                }

**Comment by vakata** [comment]
Please read the docs on the format:
https://github.com/vakata/jstree#the-required-json-format

There is no `attr` property, you are also mixing properties that should be in `state` and `data`. Let me know if you still need help after reading the above link.
