### ISSUE TITLE
Deselect All doesn't clean "jstree-undetermined" class!

### ISSUE THREAD

**Issue by jzalucki** [vakata/jstree#1162]
Please add:
this.element.find('.jstree-undetermined').removeClass('jstree-undetermined');

to deselect_all function.

**Comment by vakata** [comment]
It does not need to clean it. Here is a demo:
http://jsfiddle.net/DGAF4/548/

Please provide an example where the above is not working for you. Keep in mind if you are using `tie_selection : false` you need to use `uncheck_all()`

Best regards,
Ivan
