### ISSUE TITLE
How to populate child nodes only on expanding/selection of parent node??

### ISSUE THREAD

**Issue by vaniaravinda** [vakata/jstree#1163]
Hi,

I tried with below code which is not populating the tree view at all. Helpful for all the valuable suggestions.

```
<div id="selector">
</div>
<script type="text/javascript">
    debugger;
    jQuery(function ($) {
        $("#selector").jstree({
            "json_data": {
                "data": [
                             {
                                 "data": "Employee 1",
                                 "children": [
                                   { "data": "Official" },
                                   { "data": "Personal", "children": ["Salary Slips", "Jokes"] },
                                   { "data": "Medical" },
                                 ]
                             },
                             {
                                 "data": "Employee 2",
                                 "children": [
                                   { "data": "Official" },
                                   { "data": "Personal", "children": ["Salary Slips", "Jokes"] },
                                   { "data": "Medical" },
                                 ]
                             },
                             {
                                 "data": "Employee 3",
                             }
                ]
            },
            "plugins": ["themes", "json_data", "ui"]
        }).bind();
    })
</script>
```

Thanks,
Vani Aravinda

**Comment by vakata** [comment]
There are countless examples on how to do this:
 * read the home page of this very repo
 * check the examples provided - both as code and on jstree.com
 * read the discussion group

If you have how-to questions, please use the discussion group:
https://groups.google.com/forum/#!forum/jstree

Your problem is that you are using a v.1 config with v.3 code - those are years apart and not compatible (hence the change in major version from 1 to 3). Try using `core.data` instead of `json_data` - it is all in the docs.

Best regards,
Ivan

**Comment by sudhir9026** [comment]
I have a drop down that have multiple options when i select any one than
populate a tree..
This code run only once on page refresh after select another drop down its
do not work

$(function () {
        $("#selector").bind('move_node.jstree', function (e, data) {
             data.rslt.o.each(function (i) {
                alert('xyz');
});
});

**Comment by vakata** [comment]
Once again - read the docs - this is v.1 code, if you are using version 1, I can not help you - it has not been supported for years. If you are using version 3, this code is invalid and will not work.

**Comment by sudhir9026** [comment]
I am Using v.pre1.0
