### ISSUE TITLE
How to use jquery sweetAlert instead of javascripts default confirm when confirming to delete a node

### ISSUE THREAD

**Issue by newton777** [vakata/jstree#1164]
How to use jquery sweetAlert instead of javascripts default confirm when confirming to delete a node or not? At the moment its just deleting the node and I cant seem to find a way to stop it from deleting the node?

"                    'check_callback': function (operation, node, parent, position, more) {
                        if (operation === "delete_node")
                        {
                            if (!swal({
                                title: "Are you sure?",
                                text: "This level will be deleted permanantly!",
                                type: "warning",
                                showCancelButton: true,
                                confirmButtonColor: "#DD6B55",
                                confirmButtonText: "Yes, delete it!",
                                cancelButtonText: "No, cancel!",
                                closeOnConfirm: false,
                                closeOnCancel: false
                            },
                            function (isConfirm) {
                                   if (isConfirm) {
                                   deleteLevel();
                                   return true;

                            } else {
                                   swal("Cancelled", "Level is safe :)", "error");
                                   return false;
                            }
                            })) {
                                //e.stopImmediatePropagation();
                                return false;
                            }

                        }
                    }"

**Comment by vakata** [comment]
You cannot - `check_callback` does not work with async responses - you have to prevent the action right away. My guess is you need to attach your dialog when the user clicks delete (in your interface), and only if the user confirms - to actually delete the node. 

If you are using the contextmenu plugin and want to capture its delete action too - override it - let me know if you need any pointers on how to do that.

Best regards,
Ivan

**Comment by newton777** [comment]
Thanks a lot Ivan.

Im not sure how to override the delete method without loosing the default contextmenu plugin items? So for example the only way I know how to do it is to define new contextmenu items but i just want to override the delete item?

Appreciate the help. This API is the best Iv come across.

Thanks 
Newton

**Comment by vakata** [comment]
You can override the defaults like this:
```
contextmenu : {
    items : function (node) {
        var contextmenu = $.jstree.defaults.contextmenu.items(node);
        contexmenu.remove.action = function (data) {
		var inst = $.jstree.reference(data.reference),
			obj = inst.get_node(data.reference);
		// show your confirm dialog here, and in its confirm callback execute the code below:
		// function () { inst.delete_node(obj); }
	}
    },
    ...
```

**Comment by newton777** [comment]
Thanks Ivam,

I get this error when I right click on the node. 
Uncaught TypeError: Cannot read property 'contextmenu' of undefined

Im not sure if any of my other scripts are interferring with jstree.
