### ISSUE TITLE
create_node not working

### ISSUE THREAD

**Issue by Eschon** [vakata/jstree#1165]
I tried to add a new node to my tree and couldn't get it to work. After looking around in your documentation, the issues and some stackoverflow questions I ended up with the following code:

```JavaScript
var tree = $("#tree").jstree(true);

$(".add").click(function() {
  tree.create_node($("#root"), "new", "first");
});
```

It doesn't throw errors but it doesn't add a node to my tree either.

**Comment by vakata** [comment]
Read the docs:
http://www.jstree.com/docs/interaction/

The text in yellow:
> Please keep in mind that by default all modifications to the tree are prevented (create, rename, move, delete). To enable them set `core.check_callback` to true

So when creating the tree set this config option to `true`, or read more about the option:
http://www.jstree.com/api/#/?q=check_call&f=$.jstree.defaults.core.check_callback (there is an example here too)

Best regards,
Ivan

**Comment by Eschon** [comment]
Oh thanks I missed that. Works now.
