### ISSUE TITLE
pressing special characters will cause 'quicksearch' regex to fail (line 756)

### ISSUE THREAD

**Issue by ogzogz23** [vakata/jstree#1166]
I get this when trying to press special keys such as +, /, ?, etc..

SyntaxError: nothing to repeat	

if(new RegExp('^' + chr + '+$').test(word)) {

Traced to line 756.
Although I'm not trying to use any quick search features, it gets picked up anyway and causes issues.

Suggestion to include/use a regexEscape type function on the chr such as:

RegExp.escape = function(text) {
    return text.replace(/[-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");
}

jQuery UI also has a similar function to escape the characters.

**Comment by vakata** [comment]
Thanks for reporting but this was fixed a while ago:
https://github.com/vakata/jstree/blob/master/src/jstree.js#L778

Best regards,
Ivan
