### ISSUE TITLE
Event listener is removed after adding a node

### ISSUE THREAD

**Issue by Eschon** [vakata/jstree#1167]
I've prepared a small [jsFiddle](http://jsfiddle.net/Eschon/n9dtL7g3/) that shows my issue.
When you click the add-node a new node is added, but when you press the add button again nothing happens.

To make it work I have to reattach the event listener every time after adding a node. Is this a bug or intended behaviour?

**Comment by vakata** [comment]
The handler is not removed - the element is removed when the tree is redrawn - this will not change - jstree constantly redraws the tree as needed, which means nodes are recreated - any event attached directly to a node is lost. The solution is simple - use event delegation:
`$("#tree").on("click",".add", function (e) { ... })`

Best regards,
Ivan
