### ISSUE TITLE
Create button doesn't work

### ISSUE THREAD

**Issue by antiflu** [vakata/jstree#1168]
I am using the demo on http://www.jstree.com/demo/ but the Create button does nothing. Both under Firefox and Chrome it does not work, and there are no Console message indicating any errors. I want to create a new node. How can I do it?

**Comment by vakata** [comment]
Just look at the source - the demo is created using the types plugin - you can only create a node inside a folder. Open up "Root 1", select "Child 1" and click "Create".

Best regards,
Ivan
