### ISSUE TITLE
Use a couple of plugins

### ISSUE THREAD

**Issue by Gonzalo2683** [vakata/jstree#1169]
Hello,
I have a question?
Is it possible to load only the core file and a few plugins?
The jstree.js file in the dist folder is very large and need only a couple of plugins.

How I could use only the plugins I need and not load that will not use?

Thanks

**Comment by vakata** [comment]
I am creating an online builder, but unfortunately it is not ready yet, so you have to do it manually - sorry.

Copy the plugins you need in a single file and minify it (if needed). The better option is to use the build procedure of jstree - clone the repo, delete the plugins you do not need and run the build procedure - the resulting files in the `dist` directory will be what you need.

Best regards,
Ivan
