### ISSUE TITLE
THREE_STATE = FALSE and CASCADE = 'down'

### ISSUE THREAD

**Issue by juli-alvarez** [vakata/jstree#1173]
Hi Ivan,
First of all, thank you for the plugin, great work!
I have a situation in which I have the options of checkbox plugin like in the title, because I do not want to have undetermined status and use only the down propagation. My problem is that when the tree loads its nodes if I have one node with children with state checked = true and one of its children has state checked = false, the down propagation makes it be also checked. What I need is that the tree loads its nodes in the same status I save them. Is this possible without disabling the propagation and without using undetermined status? One thing, the status of the parent node that has one of its children unchecked must be checked = true.
Thanks in advance!

**Comment by vakata** [comment]
Hi,

Since you configured the tree with cascade `down` that state will propagated. If you want to have full manual control - disable cascading. There is no middle ground where the tree will load without respecting the cascade option, but will apply it some time later - sorry.

Best regards,
Ivan
