### ISSUE TITLE
jsTree Hangs in Chrome and Firefox

### ISSUE THREAD

**Issue by MrHarry01** [vakata/jstree#1175]
When u stay on the page for little long and when u drill down many nodes after some time it stop expand / collapse. I am using lazy loading with Ajax call. Even i upgraded latest version of jsTree but still that problem is there. And In firefox it happened very quickly it show one alert window also after some time on Firefox.
Kindly look into this issue its very urgent.

**Comment by vakata** [comment]
Sorry, I cannot reproduce this - I use this tree in quite a few projects with large nodesets and I have not noticed such an issue. I will need a demo to help you. I will reopen on more information.

Best regards,
Ivan
