### ISSUE TITLE
Edit() callback function never gets called

### ISSUE THREAD

**Issue by RobinL93** [vakata/jstree#1177]
Hi, 

I'm trying to save to a DB after editing is done. In the callback I'm doing the save thing, but the problem is that the callback wont get called at all... 

I have the check_callback set to true.

What is the problem?

**Comment by vakata** [comment]
It is better to use the rename_node event, but if you insist on using the callback, make sure you use the dev version from this repo, not 3.1.1

**Comment by RobinL93** [comment]
Okay :)
