### ISSUE TITLE
Children load with AJAX

### ISSUE THREAD

**Issue by aavrug** [vakata/jstree#1178]
I am trying to set children to true, just for displaying that which parent have children and then on selection of node creating the children. But the problem is when setting children to true the selection is returning the objects but the parent is not expanding. And if removing the children part it's just working fine. Any solution?

**Comment by vakata** [comment]
I have no idea what you mean. lazy loading (children : true) works when a node is expanded not selected. And it has worked for thousands of users. I can help you debug, but at least post your config, you can also use the discussion group for such how-to questions.
