### ISSUE TITLE
having problems with IE11

### ISSUE THREAD

**Issue by SRGreenwood** [vakata/jstree#1179]
Using IE 11.0.9600
I have a hierarchy of documents in folders in jstree.  Document and folders are in a database.  Content of the jstree is supplied by AJAX.  The page has a filter that will screen documents based on year published, language, string in title.  Changing the filter does a POST to the page which saves the filter in the session (all PHP).  The AJAX code gets the filter from the session (again PHP).

Works as expected in FireFox and Chrome.  IE does not update.  AJAX code is not triggered in IE.
Tried the IE debugger as you have suggested to look for errors that might be stopping the javascript.  It works with the debugger on and no errors are issued.

I'm more of a PHP guy than javascript, so your package has come in very handy, but I might be making a stupid error.

**Comment by vakata** [comment]
jstree works without properly in IE11 - there is no known issue. But it works only in standards mode - maybe you are using compatibility view or IE has turned that automatically for you (happens for intranet sites). Make sure you are in standards mode and try again. If that does not solve it - please provide a demo so that I can help you and I will reopen the issue.

Best regards,
Ivan

**Comment by SRGreenwood** [comment]
compatibility view settings not on for browsing the site.
I'll see what I can do to provide an isolation.

**Comment by SRGreenwood** [comment]
Is there any clue in that it works in the browser debugger but not without?

**Comment by vakata** [comment]
Check for any debug statements in your code. It was an issue with IE8, but
I doubt it will trip up IE11, but it won't hurt to chevk.

**Comment by SRGreenwood** [comment]
So this is part of a much bigger site, but the page is pretty simple (no alerts -- what I use for debugging javascript).

CSS:
\<link type="text/css" rel="stylesheet" href="http://irock41/dms/assets/js/jstree/jstree.css" />
\<link type="text/css" rel="stylesheet" href="http://irock41/dms/resources/modules/document/views/docs.css" />
JavaScript:
\<script type="text/javascript" src="http://irock41/dms/assets/js/jstree/jstree.js"></script>
\<script type="text/javascript" src="http://irock41/dms/resources/modules/document/views/download.js"></script>

on the page is a div: \<div id="doctree"></div>
jstree.css and jstree.js are right from your site
docs.css is pretty simple:
#grouptree { float:left; min-width:319px; overflow:auto; padding:0px 0; }
#grouptree .folder { background:url('./folder.png') right bottom no-repeat; }
#doctree { float:left; min-width:319px; overflow:auto; padding:0px 0; }
#doctree .folder { background:url('./folder.png') right bottom no-repeat; }
#doctree .file { background:url('./file.png') right bottom no-repeat; }

download.js I think is pretty simple by your standards:
$(document).ready(function() {
	$('#doctree')
		.jstree({
			'core' : {
				'data' : {
					'url' : siteUrl + 'resources.php/document/ajax/get_group_docs',
					'data' : function (node) {
						return { 'id' : node.id };
					}
				},
				'check_callback' : function(o, n, p, i, m) {
					return false;
				},
				'themes' : {
					'responsive' : false,
					'variant' : 'small'
				}
			},
			'types' : {
				'file' : { 'icon' : 'file' },
				'folder' : { 'icon' : 'folder' },
				'default' : { 'icon' : 'folder' }
			},
			'plugins' : ['state','types']
		})
		.on('changed.jstree', function (e, data) {
			if(data && data.selected && data.selected.length) {
				if(data.node.type == "file") {
					data.instance.deselect_node(data.node);
					window.location = data.node.a_attr.href;
				}
			}
		});
});

I get the ajax call on the initial page load and as directories expand.  For Chrome and Firefox I also get them when the filter changes (which causes a post), but not for IE.

If in IE11 I do a refresh in the browser, I get a request for the outermost directory but not the nested directories where the changes occur.  In Firefox and Chrome I get a request for all directories that are expanded.

**Comment by vakata** [comment]
I will build a demo and have a look as soon as I can.

**Comment by SRGreenwood** [comment]
Ivan,
Many thanks for looking into this.
I attached the files I am using.  ViewDocuments.htm is actually 
generated by a framework (CodeIgniter).  It is IE11 view of the source 
file. You don't have all the files it uses, but most can likely be 
pruned away.  The parts I think are relevant:

  * scripts and css in first 20 lines
  * contents of the fieldset (lines 107-168)
      o this is the filter that is designed to change the documents
        displayed in jstree
      o I'm relying on the post to do a refresh with new content
  * line 192 is the <div> that holds the instance of jstree

I'm quite a neophyte at javascript so it may be something really 
stupid.  Let me know if you need any more info.

SRG

**Comment by SRGreenwood** [comment]
Much appreciated --I emailed you files so you don't need to cut and paste

**Comment by JackDarth** [comment]
I am also having the same issue right now.  Did you guys find any solution on IE 11 jstree ajax calls?

**Comment by JackDarth** [comment]
Resolved, define the tree cache to false.  

<'cache' : false,>
