### ISSUE TITLE
Select on child nodes of a selected jstree node. 

### ISSUE THREAD

**Issue by honey07** [vakata/jstree#1180]
Hi,

I am using jstree with checkboxes. I want to only select children of any selected node, no parent node of the selected node should get checked. If I uncheck a node then only its children should get unchecked not its parents.

Thanks

**Comment by vakata** [comment]
Turn off the `three_state` checkbox option, and take a look at the `cascade` option of the same plugin (the API is documented on jstree.com - just search for the above two options).

Best regards,
Ivan

**Comment by honey07** [comment]
Thanks a lot Ivan. This perfectly works . I used the following configuration 
                "three_state": false,
                "whole_node" :true,
                "keep_selected_style": true,          
                "cascade":"down",

and it perfectly works.

**Comment by honey07** [comment]
Hi,

How can I make the jstree (with checkboxes) as readonly tree for view purpose only with no collapse, check/uncheck operation? I tried to use following
types: {
    "disabled": {
        "select_node": false,
        "open_node":   false,
        "close_node":  false      
    }
}

but its not working.

**Comment by vakata** [comment]
Well, there is no config option that will do that for you, but you can remove all event handlers which will render the tree readonly.
```js
$('#tree').off('.jstree');
```
I have not tested this - see if it works for you.

Best regards,
Ivan

**Comment by honey07** [comment]
Hi Ivan,

Thanks for this help. It worked to some extent. But I used the following to run my case:

$(this).jstree("open_all");		   
			   
			    for(var i = 0; i < elements.length; i++) {
			    	$(this).jstree("check_node", ['#'+elements[i]]); 				    	
			    }			   
			    var array = str.split(',');			    
			    for(var j=0;j<array.length;j++){			    	
			    	 $(this).jstree("disable_node", ['#'+ array[j]]);
			    }

**Comment by honey07** [comment]
Hi Ivan,

How can we get all the child/ sub child nodes of a selected parent node?

Thanks,

**Comment by vakata** [comment]
Use the `get_node` method, the returned object will have a `children` property, which is the IDs of all immediate children.

Best regards,
Ivan

**Comment by honey07** [comment]
Hi Ivan,

I want my js tree to be closed on loading. 

But as soon as I explicitly check the node as below
 $(this).jstree("check_node", ['#'+i]);	
, it makes the whole tree expended.

 I tried using 
$("#this").jstree("close_all"); but its not working. 
 How can I keep it as closed. 

Thanks in advance.

**Comment by honey07** [comment]
Hi Ivan,

I am facing a performance issue right now. Recently I added around 14000 noded in jsTree (with checkboxes). 
I am keeping "three_state": false because I do not want each child node to be checked when parent gets checked. So, on the basis of my current requirement , I verify manually in the tree which child nodes I need to check and which not , when a parent nodes gets selected. This I am doing as follows:
<b>

.on('select_node.jstree', function (e, data) {	
	 for(var m=0;m<str.length;m++){
		var val = "#" + str[m];					
		if(!$('#tree).jstree().is_disabled(val)){			
			$("#tree").jstree("check_node",val);			
		}
	}
});

</b>
With 14000 nodes , its taking more than 1 minute (some time around 50 seconds at least) to check the complete tree when I check the root node (top most).

Please advise me on this as with this much time I will not be able to use jsTree.


Thanks.

**Comment by vakata** [comment]
The above issue has a separate ticket which is already answered and closed. Please use separate tickets for issues that you find. If you need a discussion, or have general how-to questions - please DO NOT use the issue tracker - there is a discussion group for such questions.

Best regards,
Ivan
