### ISSUE TITLE
Rename Node When Tree state is closed

### ISSUE THREAD

**Issue by hiralbalar** [vakata/jstree#1183]
I am using the following code to bind jstree..

$(function() {
        objTree = $('#containerTree').jstree({
            'core': {
                'check_callback': true,
                "multiple": false,
                'data': function (node, callback) {
                    if (node.id === "#") {   //roots
                        callback([{
                            "id": "jPrograms",
                            "li_attr": {"customid": "jPrograms"},
                            "text": "Manage Programs",
                            "datatype": "Programs",
                            "children": true,
                            "icon": "fa fa-folder-open-o"
                        }]);
                    } else if (node.original.datatype === "Programs") {
                            callback(data);
                    }
                }
            }
        });
    });

var data = [
                { "li_attr": {"customid": "pr1"},"datatype":"Program", "dataid" : "1", "text" : "P 1", "children" : true, "icon" : "fa fa-files-o" },
                { "li_attr": {"customid": "pr2"},"datatype":"Program", "dataid" : "2", "text" : "P 2", "children" : true, "icon" : "fa fa-files-o" }
                { "li_attr": {"customid": "pr3"},"datatype":"Program", "dataid" : "3", "text" : "P 3", "children" : true, "icon" : "fa fa-files-o" }
        ]
 
function editNode(nodeid, nodename){        // function 
        treenodeid = $(objTree).find('li[customid='+customid+']').attr('id');
        $(objTree).jstree('rename_node', treenodeid, nodename);
    }

As soon as I call when tree state is closed
editNode('pr3', 'Program 3');
It doesn't seem to work

but when I try this when tree state is opened
It works..

Can you please help me with this?

**Comment by vakata** [comment]
Assign node IDs (besides the custom IDs) and use: 
```
$(objTree).jstree('rename_node', 'pr3', nodename);
```
Do not query the DOM - jsTree keeps only visible nodes in the DOM - all functions work with IDs directly.

**Comment by hiralbalar** [comment]
For any reasons there might be same custom ids for different programs for my case.

Is there any workaround for this?

**Comment by vakata** [comment]
Yes, you can traverse the internal model to find the node you are looking for by custom ID, and once you have it - rename it. I believe I already answered that question in the discussion group, but maybe it was not you:
```
var m = $('#tree').jstree(true)._model.data, i;
for(i in m) {
  if(m.hasOwnProperty(i) && i !== '#' && m[i].li_attr.customid === "THE_ID_YOU_NEED_HERE") {
    $('#tree').jstree(true).rename_node(i, nodename);
    break;
  }
}
```

**Comment by hiralbalar** [comment]
It worked.. Thank you for the quick response...
