### ISSUE TITLE
Any way to use font awsome stack icons?

### ISSUE THREAD

**Issue by erez-o** [vakata/jstree#1184]
I'm currently using the data-jstree, like 
`<li data-jstree='{"icon":"glyphicon glyphicon-leaf"}'>`

Is there a way to use Font-awsome stacking ability to plug a stacked icon into jstree? 

see details:
http://fortawesome.github.io/Font-Awesome/examples/

```
<span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-twitter fa-stack-1x"></i>
</span>
```

**Comment by vakata** [comment]
Currently no - I am not planning to add support for this, but it should be possible to create a plugin that does this - after creating a plugin that adds the stacked icons, the original icons can be hidden - there is a setting for that. Something like this:
http://jsfiddle.net/DGAF4/586/

**Comment by erez-o** [comment]
Looks very good. 

If it's well tested, I suggest adding it to the list of available plugins in http://www.jstree.com/plugins/

:thumbsup: for the help & very speedy response

**Comment by vakata** [comment]
No, it is not tested - I just created it for you - as a demo - feel free to modify it. It is added in the misc plugins, that are not part of the build.

**Comment by gpetrov** [comment]
this will be really nice to have built-in, or available via official plugin

**Comment by Jingkun-Hu** [comment]
any update for font-awesome?

**Comment by vakata** [comment]
It has been available for years - just specify the icon class in the ```icon``` property of the node.

**Comment by agnesgrusteven** [comment]
@vakata Thanks for nice idea http://jsfiddle.net/DGAF4/586/

In addition to this. Are there any way to change the color of the stack icons?? 

>  "data" : [{"state":{"icons":["fa fa-square-o fa-stack-2x **#CCCCCC**","fa fa-minus fa-stack-1x **#3498DB**"]}, "text":"Root"}],
