### ISSUE TITLE
Security Vulnerability in Demo Section

### ISSUE THREAD

**Issue by ITNerdbox** [vakata/jstree#1185]
Hi,

I have discovered a security vulnerability in the demo section of the jstree.com website. Since I do not want to disclose this to the public, who can I contact to report this issue?

Thanks in advance.

Jeroen - IT Nerdbox

**Comment by vakata** [comment]
You can write to me - I am the product owner - you can see my email in my profile card: https://github.com/vakata

Thank you.

**Comment by p09** [comment]
I wanted to know whether this mentioned vulnerability has been fixed or not.

**Comment by vakata** [comment]
Yes, it is fixed. It was am XSS vulnerability related to the site, not jstree itself.
Once again - thanks to @ITNerdbox for pointing it out.
