### ISSUE TITLE
Ddd custom context menu item dynamically

### ISSUE THREAD

**Issue by terrasoff** [vakata/jstree#1186]
Is it possible to add context menu items after plugin initialization? Something like that
```javascript
$tree.jstree().contextmenu.add(definition);
```

**Comment by vakata** [comment]
You can either return a custom contextmenu with each invokation by setting `contexmenu.items` to a function, or you can set `$.jstree.defaults.contextmenu.items` to an object, and then add to that object as necessary:
```js
$.jstree.defaults.contextmenu.items = $.jstree.defaults.contextmenu.items();

// when needed:
$.jstree.defaults.contextmenu.items.custom_entry = { ... };
```

Best regards,
Ivan

**Comment by wangzhaohui** [comment]
Hi,
I've follow your suggestion, but nothing happened. I can't modify any setting after the jstree plugin initialization.

**Comment by vakata** [comment]
Just set `contextmenu.items` to a function - it will be invoked each time the user wants a contextmenu shown, so you have full manual dynamic control over what items you want to be available. What you return from the function will be what is in the menu and the function WILL be invoked each and every time a contextmenu is shown.

**Comment by Gearyglov** [comment]
I am trying to dynamically create my contextmenu as follows;

++++++++++++++++++++++++++++++++++++++++++++++++++++++
       function contextMenu(node) {
          var tree = $("#itemTree").jstree(true);
            // The default set of all items
            var items = {
                addAsset: {
                    'label': 'Add Asset',
                    '_class': 'create-asset',
                    'action': function (obj) {
                        tree.open_node(node);
                        var newNode = { id: 'new_node', text: 'New Node', icon: false };
                        tree.create_node(node, newNode);
                        nodeToRemove = newNode;
                    }
                },
                addTap: {
                    'label': 'Add Tap',
                    'action': function (obj) {
                        tree.open_node(node);
                        var newNode = { id: 'new_node', text: 'New Tap', icon: false };
                        tree.create_node(node, newNode);
                        nodeToRemove = newNode;
                    }
                },
            }
            
           var arr = new Array();
            // or var arr = [];
            arr.push('Facility');
            arr.push('Employee');
            arr.push('Pump');
            arr.push('Bolt');

            for (i = 0; i < arr.length; i++) {
                var nodeName = arr[i];
                var propertyKey = "add" + arr[i];
                var propertyKeyLabelValue = "Add " + arr[i];

                var itemsData = {
                    'label': propertyKeyLabelValue,
                    'action': new Function('obj', 'tree', 'node',
                        "tree.open_node(node);" +
                        "var newNode = {id: 'new_node', text: 'New " + nodeName + "', icon: false }; " +
                        "tree.create_node(node, newNode); nodeToRemove = newNode; ")
                }
                items[propertyKey] = itemsData;
            }

            //alert(items['addEmployee'].action);
            return items;
        }


This works to return the context menu items but the function does not work. The first thing I get is
"Uncaught TypeError: Cannot read property 'open_node' of undefined."

I will need to build my contextmenu something like this because I will not know what type of items my end user will create (yes, that is a problem unto itself) so I will eventually be reading from a JSON list that will tell me what items the user code create. If I cannot do this then we will be dead in the water using jsTree, Someone please help me to resolve this problem and thanks.

**Comment by AaronNGray** [comment]
Because **$.jstree.defaults.contextmenu.items** is a function in jsTree's source adding items to it is not going to work !

**Comment by AaronNGray** [comment]
I would seriously suggest modifying jsTree's source something like the following :-
```
$.jstree.defaults.contextmenu.items = { ... }
$.jstree.defaults.contextmenu.fn = function(o, cb) {
    return $.jstree.defaults.contextmenu.items;
}
```
This would then give the best of both worlds.

**Comment by AaronNGray** [comment]
Pull request https://github.com/vakata/jstree/pull/2233 should solve this.

**Comment by vakata** [comment]
Adding one more redundant option just to avoid calling:
```$.jstree.defaults.contextmenu.items()```
Or am I missing something?

If you want to change the defaults you can do so easily:
```js
$.jstree.defaults.contextmenu.items = $.jstree.defaults.contextmenu.items();
// you can now change the object as much as you want
```

**Comment by kvelaro** [comment]
Sorry, for maybe silly question, could you please provide fulll example.

I cant dynamically remove/add menu items with code provided above

**Comment by javafoot** [comment]
our way here:
http://javafoot.net/index.php/en/48-add-customized-menu-items-to-jstree-contextmenu
