### ISSUE TITLE
Keydown in edit mode not working properly

### ISSUE THREAD

**Issue by nazarhussain** [vakata/jstree#1188]
Hello, 

I am implementing a scenario where I need to trigger different behavior of jstree based on user input in node `edit mode`. It is working excellent but having issue only with `Enter` key. 

```javascript
$(document).on('keydown', 'input.jstree-rename-input',function(event){
   keyCode = event.keyCode || event.which
   console.log(keyCode);
});
```
It captures and shows keydown for every key except `Enter` key, which have keyCode of `13`. 

Can you help me in solving this issue. 

Thanks

**Comment by vakata** [comment]
This is because the `keydown` event is caught and its propagation is stopped if the key in question is `Enter`. To resolve this - add your handler BEFORE creating the tree instance.

Best regards,
Ivan

**Comment by nazarhussain** [comment]
That solution did not work. Binding it first still trigger it after jstree own keydown. 

I used this solution: 

```coffee
$.fn.bindFirst = (name, fn) ->
# bind as you normally would
# don't want to miss out on any jQuery magic
  @on name, fn
  # Thanks to a comment by @Martin, adding support for
  # namespaced events too.
  @each ->
    handlers = $._data(this, 'events')[name.split('.')[0]]
    # take out the handler we just inserted from the end
    handler = handlers.pop()
    # move it at the beginning
    handlers.splice 0, 0, handler
    return
  return
```

and used it as 

```coffee
$(@element).on 'focus', 'input.jstree-rename-input', (event)=>
      $(event.target).bindFirst 'keydown', @change_parent
```

This solution works for me. Hope it will work for other people as well.
