### ISSUE TITLE
How to modify jstree contextmenu after the plugin initialization.

### ISSUE THREAD

**Issue by wangzhaohui** [vakata/jstree#1190]
I've tried so many times after the plugin initialization.

                    $.jstree.defaults.contextmenu.items = $.jstree.defaults.contextmenu.items();
                    $.jstree.defaults.contextmenu.items.remove = {
                        'label': '删除',
                        'icon': '<i class=""></i>',
                        'action': function () {
                            //
                        }
                    }

but the new setting didn't work. why?

**Comment by vakata** [comment]
Please keep it all in one ticket - no need to duplicate - I already answered there - just set `contextmenu.items` to a function.
