### ISSUE TITLE
mouse scroll wheel hold and move down move up cause hang chrome

### ISSUE THREAD

**Issue by tuong247** [vakata/jstree#1191]
Please see the picture attach for more information
![scroll wheel issue](https://cloud.githubusercontent.com/assets/9697099/9082992/f8ba6592-3b91-11e5-9624-b80c7cd220f7.png)

browser: chorme
After hold scroll wheel of mouse
The webpage is hang.
I can't click any link or do any thing on this page.
Please fix it soon

**Comment by vakata** [comment]
This is not a hang, it is your browser presenting you with an alternative way to scroll (press and hold the mouse wheel and move the mouse up and down). Just left click somewhere ... this has nothing to do with jstree.

**Comment by tuong247** [comment]
I try to test it again. then it is really hang.
Please view my video capture that issue
https://youtu.be/ltwtEFOCE18

**Comment by vakata** [comment]
Sorry - I can't reproduce this. Could you please specify your OS and Chrome versions. It is possible that this is caused by a driver / plugin / etc, could you verify that this happens for you in your own code - not only on jstree.com?

**Comment by tuong247** [comment]
I'm using windows 7. Lasted version from Chrome.
It happen on window 8 too.
I'd tried more than 2 PCs. it still have the same that error.
When you hold mouse on chrome it will show icon. then you move your mouse down and up. It will hang that page. we can't click or type or do something.

**Comment by vakata** [comment]
I see - well it is the same behavior on the video, which seems to be resolved when you click around a few times right? This is the normal mouse behavior - that icon comes from the operating system. This is an alternative way to scroll, which may be a bit jumpy in some OSs or computers.

**Comment by tuong247** [comment]
Yes, it seems be resolved when I try to reload page. 
But it has been hang browser until I close that page and open the other page.
I try to fix it but I can't so I think the best way to ask you.
Please try it hard, thank so much

**Comment by vakata** [comment]
Sorry, there is nothing I can try - I was able to reproduce this - the page does not hang - it is responsive, but cannot be interacted with. This seems like a Chrome problem to me - it should be reported to the Chrome team. I will also try to create a slimmed down demo of the issue and report it there.

**Comment by tuong247** [comment]
It also good way to make this better.
Thanks in advanced.

**Comment by vakata** [comment]
OK, I managed to get a bit more insight - the problem is with the iframe - so the problem is limited to using iframes and this alternative way of scrolling. If I manage to create a demo I will send it to the Chrome team, but as I suspected - it is not related to jstree.

**Comment by tuong247** [comment]
Sound good 

thanks.
