### ISSUE TITLE
jstree parent node does not get selected

### ISSUE THREAD

**Issue by crazyshock** [vakata/jstree#1193]
Hi, little problem.. :octopus: 

I am using the method to retrieve the selected values:

var selectedElmsIds = [];
        var selectedElms = $('#acesso_usuario').jstree("get_selected", true);
        $.each(selectedElms, function() {
            selectedElmsIds.push(this.id);
        });

All right here... my problem is being in the following case:

I have a parent node with four records, if I select only 3 records the value of the parent node does not return, but if you select the 4 records the parent node has correctly.

What I need to do for the parent node has the same value selected by selecting only some children and not all?

**Comment by vakata** [comment]
Hi,
First of all, use `get_selected()` without the `true` param if you only need the IDs.
As for the other question - I am not sure I understand, but maybe you need to use `get_top_selected` or `get_bottom_selected`.
If you are using checkboxes and need jstree to select parent nodes if any child is selected - that is not possible - you can do it yourself in event handlers though. If you need to get the parents of all selected nodes - use the loop from above and take a look at `this.parents` - this way you can collect all parents of selected nodes. 

Best regards,
Ivan
