### ISSUE TITLE
Add query parameters to the ajax search string

### ISSUE THREAD

**Issue by rshov** [vakata/jstree#1194]
Hello, I'm using the ajax search to return search results from the server. Everything is working well, but I'm wondering if it is possible to add additional query parameters when the search is performed such as: /tree/search?str=search_string**&customField=true**

My jstree config looks like:
```
		$(containerId).jstree({
			'core' : {
				'data' : {
					'url' : '/tree',
					'data' : function (node) {
						return {
							"id"               : node.id, 
							"selectSystemType" : true
						};
					}
				}
			},
			'search' : {
				'ajax' : {
					'url' : '/tree/search'
				}
			},
			'plugins' : ['search']
		});
```
I tried adding a `data` section similar to the "core" section in my config, but haven't had any luck:
```
			'search' : {
				'ajax' : {
					'url' : '/tree/search',
					'data' : function (str) {
						return {
							"str"              : str, 
							"selectSystemType" : true
						};
					}
				}
			},
```

Is this something that is possible?

Thanks very much. This is a great project by the way, I'm really impressed! You've put in a ton of time on this. Thanks for all your hard work.
Raymond

**Comment by vakata** [comment]
Hi,
Thank you for the kind words.

Yes, it is possible - just use a regular object (not a function).
```js
data : {
  selectSystemType : true
}
```
jsTree will automatically add the `str` parameter.

Best regards,
Ivan

**Comment by rshov** [comment]
Perfect! Thanks so much!
