### ISSUE TITLE
search plugin + show_only_matches = performance issues?

### ISSUE THREAD

**Issue by brunolellis** [vakata/jstree#1195]
Hi,
I have a tree with almost 300 json elements and an input text field to filter a node. Could someone help me find out what is happening, please?

If I configure jstree with "show_only_matches" = true in search section and type something, it freezes Google Chrome for some seconds. If "show_only_matches" is false, it doesn't freeze.

Here is a jsfiddle reproducing the described problem: http://jsfiddle.net/brunolellis/no430s1f/1/

This issue occurs with jstree 3.2.0 and it is working with jstree 3.0.8.

**Comment by vakata** [comment]
You had the wrong CSS file loaded, you also had the search function running on each keyup, which means a huge DOM update on each button pressed - that should be avoided. Here is a fixed demo (I see no problem with it in FF & Chrome):
http://jsfiddle.net/no430s1f/2/

I will investigate further and try to improve the search performance, but I believe the above fixes should be more than enough for a responsive tree.

Best regards,
Ivan

**Comment by brunolellis** [comment]
OK, thanks for your help.

It doesn't seem "natural" filtering while typing in this version, like it is in 3.0.8 version at least. I haven't tried later versions yet.

I will do some more investigation and let you know.

**Comment by vakata** [comment]
3.2.0 introduces the concept of hidden nodes, so the performance hit probably comes from there, I will investigate and try to speed things up a bit. Thank you for reporting.

**Comment by vakata** [comment]
I removed one additional full redraw when searching - searching with `show_only_matches` is two times faster now. 

Best regards,
Ivan

**Comment by nebadom** [comment]
There is something weird with the lastest versions: the "show_only_matches" it is just not working at all, and also becoming super slow. Version 3.1.1 works fine so I'm back to that one.

**Comment by vakata** [comment]
It works (as seen in the jsfiddle in my previous answer), just make sure you update the theme CSS file too - exactly what the author of this issue missed. 

If that is not it, please provide a demo of this feature not working so that I can fix it.

**Comment by ataft** [comment]
I was also having this problem with performance after 3.1.1 and figured out what was going on based on vakata's note about the introduction of hidden nodes in 3.2.0. I'm adding DOM content to nodes "after_open", and after the introduction of hidden nodes this was being applied to hidden nodes as well. Adding ":visible" to my selector solved the problem. For example, I'm adding an info icon with long searchable descriptions and a tooltip, where the tooltip has to be refreshed if/when nodes go in and out of the DOM. Maybe there's a better way to do this? For now, the ":visible" selector works great.

I'm going to double back to my code to see if I can use the
