### ISSUE TITLE
problems with refresh()

### ISSUE THREAD

**Issue by RobinL93** [vakata/jstree#1196]
Hello. I'm trying to move a node, and if I move a node to a node with the same name, I want it to jump back to original position.
I'm using .refresh() for that and it works fine. 

But the problem is if I create a new node, called "drinks" and already have a child that also name is "drinks",  and if I try to move that child out to where the other "drinks" was, it should jump back to the original position, which is does.

But the the newly created node are deleted, until I refresh the page then it's back.
 
Is there a way to go around this and fix it?

**Comment by vakata** [comment]
`refresh` is supposed to do that - it recreates the tree with the data you have provided in the `core.data` setting. If you want to persist the data on the client side - make sure you keep it in a variable and feed that variable to the tree:
```js
var data = { ... initial data ... };
$('#tree')
    .on('create_node.jstree copy_node.jstree move_node.jstree delete_node.jstree rename_node.jstree', function (e, data) {
        data = data.instance.get_json();
    })
    .jstree({
        core : {
            data : function (node, cb) { cb(data); },
            ... rest of your config ...
    });
```
I cannot help you further without seeing your config, but this should be enough to get you going. Please let me know if you have further questions (but share your config).

Best regards,
Ivan
