### ISSUE TITLE
Custom icon disappears when changing node type with set_type(node)

### ISSUE THREAD

**Issue by skenny** [vakata/jstree#1197]
Using jsTree 3.2.0 and jQuery 1.11.3.

I have a custom icon set on one of my types, defined as follows:

	'types' : {
		'default' : {
			'icon': 'jstree-icon jstree-folder'
		},
		'file' : {
			'icon': 'jstree-icon jstree-file'
		},
		'lockedFolder' : {
			'icon': '<c:url value="/css/jstree_themes/default/lockedFolder.png" />'
		}
	}

I have a context menu option set to toggle folder nodes between default and lockedFolder types, but when I change the type to "lockedFolder", the node's icon disappears because the jstree-icon class is removed from the `<i>` element.  When I toggle the node back to type "default", the default folder icon appears as expected.  I am changing the type as follows:

	tree.set_type(node, isLocked ? 'lockedFolder' : 'default');

I added a workaround in my function that toggles the type of the node that resolves the problem:

	// workaround for jsTree clearing the jstree-icon class from the icon element after setting a custom icon image
	var domNode = tree.get_node(node.id, true);
	var icon = $('i', domNode);
	if (!icon.hasClass('.jstree-icon')) {
		icon.addClass('jstree-icon');
	}

**Comment by vakata** [comment]
Do not set `jstree-icon` yourself. Just set the class you need:
```
'types' : {
    'default' : {
        'icon': 'jstree-folder'
    },
    'file' : {
        'icon': 'jstree-file'
    },
    'lockedFolder' : {
        'icon': '<c:url value="/css/jstree_themes/default/lockedFolder.png" />'
    }
}
```

**Comment by skenny** [comment]
Works great, thanks.
