### ISSUE TITLE
Deleteing child node checking parent's checkboxes

### ISSUE THREAD

**Issue by jakeYankovic** [vakata/jstree#1201]
Hello, I've run into a small issue and wanted to see what you think. I was trying to delete the last child node from a parent while using the checkbox plugin. When I deleted the child node from the parent it caused the parent's checkbox to be checked. This seems to happen when you delete the last child from a parent. 

Example: http://jsfiddle.net/jakeyankovic/rvLL10h6/

Thanks,
Jake

**Comment by jakeYankovic** [comment]
Thanks a lot for fixing this. Just got the latest and it works perfectly.

Jake

**Comment by rafikiass** [comment]
Hi Vekata, I'm using v3.3.5 and it seems that this issue still exists. If the last node is selected, as soon as I delete it, the tree checked the parent.  Any fix?
