### ISSUE TITLE
Submenu action functions being overwritten

### ISSUE THREAD

**Issue by selevanm** [vakata/jstree#1203]
I am having the same issue that was reported here:

http://osdir.com/ml/jstree/2011-02/msg00087.html

I tried setting unique ids to the sub menu items and their underlying json objects (ensuring they match) but that did not fix the issue.  We are currently using v1 rc 3 and are wondering if you are still supporting this version or if there is any advice to resolving the issue.  As a hack I can 'dummy' up some sub menu items (same number as my total number of items in SubB) at the front of SubA and hide them in the UI but figured I would check to see if there was a more robust solution,  thank you.

**Comment by vakata** [comment]
Sorry, v.1 has not been supported for years. I recommend upgrading to v.3. As for support - I check the google groups page a few times a day and the jstree stackoverflow tag once every few days, so if you have any how-to questions I will be happy to answer.

Best regards,
Ivan

**Comment by selevanm** [comment]
Thanks Ivan, we will attempt to upgrade the library, appreciate the quick
response and your work on the plugin.

Matt
