### ISSUE TITLE
Reloading node for each open

### ISSUE THREAD

**Issue by jmthomas** [vakata/jstree#1204]
You have a very sensible default of only doing the AJAX request the first time someone opens a node. However, I'd like to do the AJAX call every time a node is opened. I tried binding to the various open events and then calling load_node but that results in recursion because load_node (I assume) is then causing the open events to be re-issued. Is there an easy way to do this without deleting the child nodes after a close event and trying to reset the state?

**Comment by vakata** [comment]
You can try this:
```
$('#tree').on("close_node.jstree", function (e, data) {
    data.instance._model.data[data.node.id].state.loaded = false;
    data.instance.delete_node(data.node.children);
});
```
Just make sure `core.check_callback` is set to `true` so that the nodes can be deleted.

Best regards,
Ivan

**Comment by jmthomas** [comment]
Worked like a champ thanks!
