### ISSUE TITLE
Delete/Move multiple nodes in one fired event

### ISSUE THREAD

**Issue by ace-han** [vakata/jstree#1206]
For performance sake, I would like to send only one http request to server side with multiple node infos that are changing (deletion or moving from diff folders to the same folder with multiple=true). However event mechanism in `jstree` will fire event on each single node.

How can I consolidate them in one event or how can I achieve that?

I find a discuss in http://goobbe.com/questions/4741370/jstree-select-multiple-nodes-fire-one-event.
Using timeout mechanism.

Is that the proper way to do so? Help me out if I miss anything, thx

**Comment by vakata** [comment]
jsTree will never hit the server side itself as a part of triggering an event. It is your code that will do that. I guess that you can simply collect any events in an array and sync them in a timeout, and if an event fires before the timeout - clear the timeout and push it to the array. 
Keep in mind - that is only an idea, there could be many other approaches - it all depends on the logic of your application.
