### ISSUE TITLE
Rendering of vertical bars appears wrong in Chrome 44

### ISSUE THREAD

**Issue by HamptonNorth** [vakata/jstree#1207]
Correct in Firefox 40 and Edge 20
Attached screen illustrates - 
Thanks for a great bit of software

![jstree](https://cloud.githubusercontent.com/assets/1650551/9556097/0b6395ca-4dca-11e5-99ec-9e1c26c9ddee.jpg)

**Comment by vakata** [comment]
I just tested this with nothing but a single tree on the page and there is no visual glitch. Can you reproduce the problem on https://www.jstree.com/ ?

Check to see if the content is not zoomed in - it seems zoomed to me.

I am closing this for now, but I will reopen if it can be reproduced.

Best regards,
Ivan

**Comment by HamptonNorth** [comment]
Absolutely right. Had Chrome on 110% zoom without realising. Apologies for wasting your time
