### ISSUE TITLE
Adding A Class to Nodes of A Specific Type

### ISSUE THREAD

**Issue by brandonkboswell** [vakata/jstree#1208]
I'm using the types plugin and would like to style nodes of specific types differently. This seems most easily done by allowing the use of types as classes on the node. Is there any way to do this currently?

**Comment by vakata** [comment]
No sorry, there is no way to do this at the moment. There was a similar ticket or a pull request a week ago - the author proposed a solution that added a class to each node of a given type. You might want to give that code a try if you need this urgently.

However, I am currently considering extending the types plugin to be able to merge some default settings with each node (being able to set attributes / data / basically anything from the jstree JSON format from the type). I will keep you posted - it should be ready in a week or so.

Best regards,
Ivan

**Comment by brandonkboswell** [comment]
Thanks Ivan.
