### ISSUE TITLE
Disable all checkboxes and dnd programmatically

### ISSUE THREAD

**Issue by tharasp** [vakata/jstree#1211]
I am using  `jstree` with `checkbox` and `dnd`. After rendering tree with data, I check a variable `locked` and if it is `true`, I want to disable all `checkbox` and `dnd` functionality associated with the tree. 
How can I disable all `checkbox` and `dnd` programmatically?

    $('#treeViewDiv')
      .on('ready.jstree',function(e,data)
      {
          $('#treeViewDiv').jstree(true).open_all();
          if(locked == true)
          {
                //Code to disable checkbox and dnd
          }
      })
      .jstree({
           "core" : {
                  "check_callback" : true,
                  "data" : jsonData
       },
       "checkbox" : {
                  "keep_selected_style" : false,
                  "three_state"			: false,
                  "two_state"			: true,
                  "whole_node"			: false,
                  "tie_selection"		: false
        },
       "search" : {
                  "show_only_matches": true
        },
       "plugins" : [ "search", "checkbox", "wholerow", "dnd" ]
})

Thanks!

**Comment by vakata** [comment]
1) When locking the tree call:
```
$('#treeViewDiv').jstree(true).disable_checkbox(
    $('#treeViewDiv').jstree(true)._model.data["#"].children_d
);
```
2) Set the `dnd.is_draggable` config option to a function and return `false` when the tree is locked.

Best regards,
Ivan
