### ISSUE TITLE
Select a node through the API does not deselect the previous node.

### ISSUE THREAD

**Issue by icruces** [vakata/jstree#1218]
If I select nodes using the API then the tree keeps multiple nodes selected even though the "multiple" option is false:

```html
<div id="jstree">
    <ul><li id="test1">asdf</li></ul>
    <ul><li id="test2">asd2222f</li></ul>
</div>
```

```javascript
$("#jstree").jstree({"core" : { "multiple" : false }});

$("#jstree").on('ready.jstree', function () {
    var instance = $("#jstree").jstree(true);  
    instance.select_node("test1");
    instance.select_node("test2");
});
```

[fiddle](https://jsfiddle.net/1v4mbe7p/)

**Comment by vakata** [comment]
This is normal - `select_node` is a low-level method for developers - it is not limited by the `multiple` config option - only user interaction is limited by this config option. You can either call `deselect_all` prior to calling `select_node`, or use `activate_node` (which is the function that user interaction invokes).

Best regards,
Ivan
