### ISSUE TITLE
IE 8 Search problem

### ISSUE THREAD

**Issue by lantushenkoao** [vakata/jstree#1220]
Hello. 
Trying to use client-side search in JSTree in IE 8 and getting an error Object does not support this property or method. The method is querySelectorAll. However, using the following proxy method resolves the problem. When using proxy, JSTree works fine with IE7 as well.

        this.querySelectorAll = function(selector, parent){
            if(parent.querySelectorAll) {
                return parent.querySelectorAll(selector);
            }else {
                return jQuery(selector, parent);
            }
        };

**Comment by vakata** [comment]
IE7 is not supported, as for IE8 - it has `querySelectorAll`, if it is not working for you - that means you are in compatibility mode, either turn it off, or use a polyfill (as you have). 

Keep in mind such a polyfill will not be part of jstree.

Best regards,
Ivan
