### ISSUE TITLE
About Ajax

### ISSUE THREAD

**Issue by xujianghao** [vakata/jstree#1221]
$('#terminal').jstree({ 
		'core' : {
        	'data' : {
        		'url':function (node){     			
        			if(node.id=="#"||node.parent=="#"){
        				return 'allCategoryList.action';
        			}else if(node.parent=="0"){
        				return  'AllMaterialsList.action';
        			}else if(node.parent=="1"){
        				return 'getBsByMaterialsNmb.action';
        			}
        		},
        		'data':function (node){
        			return { 'ids' : node.id};
        		}
        	},
        	'check_callback' : false,
			'themes' : {
				'responsive' : false
			}
    },
    
    'plugins' : ['dnd','types','contextmenu','unique','wholerow']
	}).on("close_node.jstree", function (e, data) {
	    data.instance._model.data[data.node.id].state.loaded = false;
	    data.instance.delete_node(data.node.children);
	});
After the node load, URL will be returned as the URL of the current node to obtain data on the background, I imagine that the order followed by the implementation by the above URL returned, so there will be four-layer structure of the tree (because ROOT layer) but now after the URL returned perform the first implementation of the second, the formation of three tree structure, when performing a third URL, it will be replaced by data on the implementation of the results of the second URL.
How can I make URL loading each layer of the tree is not the same as it?

**Comment by vakata** [comment]
Sorry,  I have no idea what you mean. Setting `url` and `data` to functions is as flexible as it gets. You can use custom URLs with custom data for each loaded node (or level). Please clarify what the problem is.

**Comment by xujianghao** [comment]
So,I want to konw how to use custom URLs with custom data for each loaded node(or level)?like this:level 1 And Root use URL="allCategoryList.action",level 2 use URL="AllMaterialsList.action",then
level 3 use URL="getBsByMaterialsNmb.action".
![Uploading 捕获.JPG…]()

**Comment by xujianghao** [comment]
So,I want to konw how to use custom URLs with custom data for each loaded node(or level)?when I click the "<i class="jstree-icon jstree-ocl" role="presentation"></i>" like this:level 1 And Root use URL="allCategoryList.action",level 2 use URL="AllMaterialsList.action",then level 3 use URL="getBsByMaterialsNmb.action".

**Comment by vakata** [comment]
Just replace your last `else if` with `else` and make sure you know what root nodes are in jstree and loading means. "Loading a node" means loading it's children, root nodes are the base tree nodes which reside in a virtual parent with the ID `#`. 
So basically provided your data is correct your code should work. If it is not working - please provide a demo.
