### ISSUE TITLE
Documentation: submenu for contextmenu not exist

### ISSUE THREAD

**Issue by EifX** [vakata/jstree#1222]
Hi,

first of all: This is not a 'typical issue'. Please have a look to the API-Documentation:

https://www.jstree.com/api/#/?q=$.jstree.defaults.contextmenu&f=$.jstree.defaults.contextmenu.items

There are many things explained, but something is missing: It's possible to have a key called 'submenu'. This nice keyword allows, to create submenus in the contextmenu. Example-Code:

```
$('#foo').jstree({
'core' : {
	'check_callback' : true,
	'data' : {
		'url' : '/foo/bar',
		"dataType" : "json"
	}
},
'plugins' : ['contextmenu'],
'contextmenu' : {
	'items' : function($node){
		return {
			'example': {
				'label' : 'An Example',
				'submenu': {
					'subexample': {
						'label' : 'A Sub-Example'
					}
				}
			}
		};
	}
}
});
```

Please document this feature in the jstree.contextmenu API-Entry :)

**Comment by PjotrB** [comment]
Hmm, I tried to find the part about "submenu" that you say you added, but I can't seem to locate it.
Is it in https://www.jstree.com/api/#/?f=$.jstree.defaults.contextmenu.items or somewhere else? Or did it not get published somehow?
Thanks.

**Comment by vakata** [comment]
It will be live with the next 3.2.2 release (probably in a week).
