### ISSUE TITLE
About Ajax #1221

### ISSUE THREAD

**Issue by xujianghao** [vakata/jstree#1223]
So,I want to konw how to use custom URLs with custom data for each loaded node(or level)?when I click  like this:level 1 And Root use URL="allCategoryList.action",level 2 use URL="AllMaterialsList.action",then level 3 use URL="getBsByMaterialsNmb.action".

**Comment by xujianghao** [comment]
the each level json data like this:
[{"a_attr":null,"children":true,"eastcom":null,"icon":null,"id":"0","name":null,"parent":"#","sn":null,"text":"设备","type":null}]   Level 1 json

[{"a_attr":null,"children":true,"eastcom":"0","icon":null,"id":"1","name":null,"parent":"0","sn":null,"text":"基站","type":null},    Level 2 json
{"a_attr":null,"children":true,"eastcom":"0","icon":null,"id":"2","name":null,"parent":"0","sn":null,"text":"服务器","type":null},
{"a_attr":null,"children":true,"eastcom":"0","icon":null,"id":"3","name":null,"parent":"0","sn":null,"text":"PC机","type":null},
{"a_attr":null,"children":true,"eastcom":"0","icon":null,"id":"4","name":null,"parent":"0","sn":null,"text":"终端","type":null}]


[{"a_attr":null,"children":true,"eastcom":null,"icon":null,"id":"001","name":null,"parent":"1","sn":null,"text":"TETRA基站","type":null},  Level 3 json
{"a_attr":null,"children":true,"eastcom":null,"icon":null,"id":"002","name":null,"parent":"1","sn":null,"text":"傻瓜基站","type":null}]


[{"a_attr":{"onclick":"get(\"3\")"},"children":true,"eastcom":null,"icon":null,"id":"3","name":null,"parent":"002","sn":null,"text":"傻瓜基站1","type":null},  Level 4 json
{"a_attr":{"onclick":"get(\"4\")"},"children":true,"eastcom":null,"icon":null,"id":"4","name":null,"parent":"002","sn":null,"text":"傻瓜基站2","type":null}]

**Comment by xujianghao** [comment]
each level json data like this:

use the URL="allCategoryList.action" get the Level 1 json data
[{"a_attr":null,"children":true,"eastcom":null,"icon":null,"id":"0","name":null,"parent":"#","sn":null,"text":"设备","type":null}]   

use the URL="allCategoryList.action" get the Level 2 json data
[{"a_attr":null,"children":true,"eastcom":"0","icon":null,"id":"1","name":null,"parent":"0","sn":null,"text":"基站","type":null},    
{"a_attr":null,"children":true,"eastcom":"0","icon":null,"id":"2","name":null,"parent":"0","sn":null,"text":"服务器","type":null},
{"a_attr":null,"children":true,"eastcom":"0","icon":null,"id":"3","name":null,"parent":"0","sn":null,"text":"PC机","type":null},
{"a_attr":null,"children":true,"eastcom":"0","icon":null,"id":"4","name":null,"parent":"0","sn":null,"text":"终端","type":null}]

use the URL="AllMaterialsList.action" get the Level 3 json data
[{"a_attr":null,"children":true,"eastcom":null,"icon":null,"id":"001","name":null,"parent":"1","sn":null,"text":"TETRA基站","type":null},  
{"a_attr":null,"children":true,"eastcom":null,"icon":null,"id":"002","name":null,"parent":"1","sn":null,"text":"傻瓜基站","type":null}]

use the URL="getBsByMaterialsNmb.action" get the Level 4 json data
[{"a_attr":{"onclick":"get(\"3\")"},"children":true,"eastcom":null,"icon":null,"id":"3","name":null,"parent":"002","sn":null,"text":"傻瓜基站1","type":null},     
{"a_attr":{"onclick":"get(\"4\")"},"children":true,"eastcom":null,"icon":null,"id":"4","name":null,"parent":"002","sn":null,"text":"傻瓜基站2","type":null}]
how can i do like this?

**Comment by davidreghay** [comment]
$('#container').jstree({
        'core' : {
          'data' : {
            "url" : function(node) {
                // return whatever you want here based on the json data of the node
                // for example you can decide what URL based on node.parent since you 
                // seem to encode the level of the node in that field...
            }
            "data" : function (node) {
              // same here, pass whatever params you want to based on the node clicked
            }
          }
        }
      });

I hope the above makes sense and that I was some help to you.

**Comment by xujianghao** [comment]
I know this,my jsTree like this:
$('#terminal').jstree({ 
		'core' : {
        	'data' : {
        		'url':function (node){
		switch(node.parent){ 
		case "#": 
		    url = "allCategoryList.action"
			break;
		case null: 
		    url = "allCategoryList.action"
			break;
		case "0": 
		    url = "AllMaterialsList.action"
			break;
		case "1": 
		    url = "getBsByMaterialsNmb.action"
			break;
		case 6: 
		    url = "getLteUserList.action"
			break;
		case 7: 
		    url = "getBccUserList.action"
			break;
		case 8: 
		    url = "getBccGroupList.action"
			break;	
		case 1: 
		default: 
		    url = "getRadioUserList.action"
			break;
	}
		return url;
		
        		},
        		'data':function (node){
        			return { 'ids' : node.id};
        		}
        	},
        	'check_callback' : false,
			'themes' : {
				'responsive' : false
			}
    },
    
    'plugins' : ['dnd','types','contextmenu','unique','wholerow']
});
is there something wrong with it?

**Comment by xujianghao** [comment]
![default](https://cloud.githubusercontent.com/assets/12029702/9895533/2b48ed66-5c63-11e5-8acf-e8cdfcc0b86e.jpg)

Now URL execution order is the first level, level 2, 3 or 4, I want to order of execution is the first level, level 2, 3, 4

**Comment by xujianghao** [comment]
![1](https://cloud.githubusercontent.com/assets/12029702/9895656/7ea6fda8-5c64-11e5-9b80-dd3bf6ee3768.PNG)
![2](https://cloud.githubusercontent.com/assets/12029702/9895659/8a9f53f8-5c64-11e5-81f4-1a85e16c750e.PNG)


Now show effect into it, is not I want to quaternary structure

**Comment by xujianghao** [comment]
Or like this:
![3](https://cloud.githubusercontent.com/assets/12029702/9895718/74c6ceac-5c65-11e5-98f2-6e65dfdfd08e.PNG)

**Comment by davidreghay** [comment]
Sorry but I can't understand your question.  I'm sure you'll figure it out at this point though.  Good luck!

**Comment by vakata** [comment]
Please do not duplicate questions! Keep it all in the original thread. As I said in the other post - since I can not understand what is wrong with your code in spite of my best efforts, please provide a demo of the issue - there is something wrong with your implementation.

**Comment by vakata** [comment]
Also keep in mind `level` does not equal `parent` - maybe you need `node.parents.length - 1` in your function instead of `node.parent`

**Comment by xujianghao** [comment]
In my mind, the node.parent is return by action json,like the level 1 json data the parent="#" , so the 
node.parent="#",when i  click the level 1, the url="allCategoryList.action" will be used. then  like this.

**Comment by xujianghao** [comment]
I want the result like this :
![4](https://cloud.githubusercontent.com/assets/12029702/9898461/f61e8192-5c84-11e5-9ef9-b963ac46815a.PNG)

but now the result like this:
![0916_1](https://cloud.githubusercontent.com/assets/12029702/9898396/5fb73456-5c84-11e5-8af3-971fa3b82dc4.gif)
![0916_2](https://cloud.githubusercontent.com/assets/12029702/9898405/78695484-5c84-11e5-9ebf-2a8428614e20.gif)

**Comment by xujianghao** [comment]
Ok , I soved this problem! thanks
