### ISSUE TITLE
click scope after rename

### ISSUE THREAD

**Issue by sfp12** [vakata/jstree#1224]
I curious why design this solution?

this page : https://www.jstree.com/demo/    
this tree : div#jstree_demo

I must click in '#jstree_demo ul' after rename, then could rename success;
If I click in 'div#jstree_demo', not 'ul', then input still focus, not blur. I konw [enter] is useful, but second way is shoud supported.

**Comment by vakata** [comment]
This is related to #1212 so I will close it - please follow the other ticket.
