### ISSUE TITLE
Can't override background-size for custom node icons

### ISSUE THREAD

**Issue by rgonsalves** [vakata/jstree#1226]
On line 242 of jstree 3.2.1 we had to comment out:

```//node.childNodes[1].childNodes[0].style.backgroundSize = 'auto';```

This seems to hardwire the size. Once this line was commented out, we were able to set the background-size in CSS. The images for the nodes in our case are retrieved from S3.

**Comment by vakata** [comment]
I am aware of this issue, but 99% of the time - `auto` is what you need when using a custom icon. There is no way to reset the value back using CSS. 
You can fix this in your code by using `!important` for your icons - I know it is not recommended, but it is the only option until I figure out a better way of resetting the background size.
