### ISSUE TITLE
skip_redraw ignored on show/hide node when using array

### ISSUE THREAD

**Issue by twh1808** [vakata/jstree#1228]
The following `if` blocks located in [hide_node](https://github.com/vakata/jstree/blob/master/src/jstree.js#L2835-L2842) and [show_node](https://github.com/vakata/jstree/blob/master/src/jstree.js#L2871-L2878) are ignoring the `skip_redraw` parameter forcing a redraw when `obj` is an array. I believe the expectation of this is that if `skip_redraw` is specified as `true`, the tree does not redraw until explicitly told to do so.

**Comment by vakata** [comment]
As mentioned in the comment above - `skip_redraw` is an internal parameter, it serves the sole purpose of not redrawing after each node if `obj` is an array. Basically - `hide_node` and `show_node` will always redraw, but if you pass in an array, the methods will only redraw after setting the state on the whole collection of nodes and not after each node.

If I misunderstood you and this explanation is not enough - please clarify and I will reopen the issue.

Best regards,
Ivan

**Comment by twh1808** [comment]
Alright, I understand your intentions with that now. Providing details to that parameter in the documentation, although stated as internal, is what threw me off. If you had the intention of no one using it, I would've expected something along the lines of your `redraw` and `_redraw` approach to a private function.

In the end, I'm fine with your explanation and I found the root cause of my issue.

**Comment by twh1808** [comment]
I guess I could also explain the issue I found which caused me to create an issue.

I have two trees, one "source" tree and one "destination" tree. I took a simple approach of duplicating data in my first iteration of this code by simply showing/hiding nodes in the trees rather than copying/removing. I experienced a large speed issue by these few lines:
```
// Get selected nodes
var nodes = srcTree.get_selected();

// Show/hide the selected nodes
srcTree.hide_node(nodes);
destTree.show_node(nodes);
```
While the tree is referencing the wrong `nodes`, it still works because the ids were the same. What I found was that the `this.redraw()` line was firing a `redraw.jstree` event for each node I was showing/hiding. This meant if I moved 200 nodes, I had 400 redraws. Since your code didn't allow me to `skip_redraw` with an array, I iterated the nodes myself and forced a `skip_redraw`. After my manually iteration, I ran `srcTree.redraw(true);` and `destTree.redraw(true);` which proved to be exponentially faster with only a single `redraw.jstree` event.
```
// Get selected nodes
var nodes = srcTree.get_selected();

// Show/hide the selected nodes
_.each(nodes, function(node) {
    srcTree.hide_node(node, true);
    destTree.show_node(node, true);
});

// Now force redraw
srcTree.redraw(true);
destTree.redraw(true);
```

Perhaps I've stumbled onto another issue you may want to look into.

Thanks,
Troy

**Comment by vakata** [comment]
I see what you mean - this is now fixed and in the repo - skip_redraw is always respected - regardless if the first param is a single node or an array.
