### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded jstree

### ISSUE THREAD

**Issue by slavOuchka** [vakata/jstree#1229]
Hi,

I'm getting this "2jstree.min.js:2 Uncaught RangeError: Maximum call stack size exceeded" when clicking down to a 3-rd depth category on the tree. The output seems correct, and works right for the higher level categories.

	$(document).ready(function(){
		$('#jstree_categories').jstree({ 'core' : {
			'data' : <?php echo $treeData; ?>
		} });
		$('#jstree_categories').on("changed.jstree", function (e, data) {
			$('#CategoryID').val(data.selected);
		});
	});

// Edit: I'm building the $treeData in php. I can post the actual output if required.

**Comment by vakata** [comment]
Please use the non-minified version of the code when posting issues. As for the code you posted - you'd be better off using an array and `json_encode` - your way of building the JSON string is error prone. To get this error I am alwomost certain you have a duplicated ID.

I will reopen if needed when you provide more info (or a demo).

Best regards,
Ivan

**Comment by vakata** [comment]
My guess is your error is here:
```
foreach($childrenThird as $childThird){
$treeData .= '{ "text" : "' . $childSecond['CategoryName'] . '", "id" : "' . $childSecond['CategoryID'] . '"},';
}
```
You probably want to use `$childThird`?
