### ISSUE TITLE
get_json function does not export original data

### ISSUE THREAD

**Issue by pidatbnx** [vakata/jstree#1231]
Hello,
I am using latest version v3.2.1. My jsTree is created with direct JSON data containing custom attributes. When I export it using the get_json() function, those attributes are not exported. After debugging the jstree code, it appears that although the option no_data is set to false, the data array member is not assigned anything. I have patched the jstree.js code as follow in order to get the data correctly filled.
jstree.js, line 3581 (in get_json function, added 3 lines:
			if (options && !options.no_data) {
				tmp.data = obj.original;
			}
Do you think it is the correct way to achieve this.
If yes, could this patch be added to the next version ?
Thanks,
Pierre.

**Comment by vakata** [comment]
`data` is not the same as `original`. If you want custom attributes - use the `data` attribute to attach them to each node. Then you will get those back when exporting.
`original` is there just to help folks who did not read the docs and still want to salvage some old code and have access to the random attributes they added to each node.

In short - `original` is never exported, use the special `data` attribute for custom attributes.
