### ISSUE TITLE
'core.data' function callback issue when result is 'false'

### ISSUE THREAD

**Issue by Leonardas** [vakata/jstree#1233]
file: jstree.js
ln: 1336

looks like this line of code should go to IF's (ln 1333) else branch.

```javascript
if(d === false) {
   callback.call(this, false);
}
else {
   this[typeof d === 'string' ? '_append_html_data' : '_append_json_data'](obj, typeof d === 'string' ? $($.parseHTML(d)).filter(function () { return this.nodeType !== 3; }) : d, function (status) {
						callback.call(this, status);
  });
}
```

**Comment by vakata** [comment]
Did you run into a problem with this or is this just a general remark? 
Which file and revision is this, also dist or src folder, please add a link?

I am closing this until further information is provided.

Best regards,
Ivan

**Comment by Leonardas** [comment]
version: last
folder: src

let's take a look to example, I hope it makes things more clear.

```javascript
config: {
   core: {
     data: function(node, cb){
       try {
	     // try to load data
	     var childNodes = loadData();
		 cb.call(this, childNodes);
	   }
	   catch{
	     showErrorMessage();
		 // error occurred
		 cb.call(this, false);
		 // expected
		 // expand button stays (in other words, node stays in same state)
		 // current
		 // node expands and one child is added
	   }
     }
   }
}
```

**Comment by vakata** [comment]
Thanks for the clarification, I will have a look later today.

Best regards,
Ivan

**Comment by vakata** [comment]
Thank you - sorry it took me so long to respond.

Best regards,
Ivan
