### ISSUE TITLE
Plugin Checkbox. Whole_node option problem

### ISSUE THREAD

**Issue by aleksander79** [vakata/jstree#1234]
With Whole_node option when clicking on a node resets all other checkboxes.
Like input type='radio' does.

**Comment by vakata** [comment]
You probably have misconfigured the plugins. Here is a simple demo: http://jsfiddle.net/DGAF4/866/
You can see checkbox and wholerow work nicely together.

Best regards,
Ivan

**Comment by aleksander79** [comment]
I meant the whole_node property of a checkbox plugin. http://jsfiddle.net/p7w3yn7a/
I wish it sets checkbox only when clicking on checkbox, not on the name of node. Instead of this it switch checkboxes in "radio" style when I click on the node name.

**Comment by vakata** [comment]
This is the purpose of the setting - from what I see it is working according to the docs. Maye you need the `checkbox.tie_selection` option set to `false`?

**Comment by aleksander79** [comment]
checkbox.tie_selection seems no effect in my case

By clicking on the text of the node I need **not** to affect the checkbox. I need it happens only when you press directly on the checkbox. Instead, it switches on the checkboxes every time I click on the text of the node. It doesn't toggle it, only switchs on. Maybe some misunderstanding. Sorry
For example, I need to open contextmenu on the node, but not to select checkbox. Now, when I press right button on the node, it switchs on checkbox, and my old selection modified. It is not convenient.

Unfortunately, http://jsfiddle.net/p7w3yn7a/2/ doesn't show contextmenu for me too.

I’m sorry to bother you

**Comment by aleksander79** [comment]
I don't know is it bug or not, but by trial-and-error testing I found  that it needs both options: ```checkbox.whole_node``` to ```false``` and ```checkbox.tie_selection``` to ```false``` to work properly.
http://jsfiddle.net/p7w3yn7a/4/
