### ISSUE TITLE
Context menu Disable fails 

### ISSUE THREAD

**Issue by khanna2n** [vakata/jstree#1236]
I was able to disable the nodes of jstree using 

```
	var jstreeContents = $('#hierarchy').jstree(true).get_json('#', { 'flat': true });
	$.each(jstreeContents, function( key, value ) {
	    if (value.state.selected == false) {
	         $('#hierarchy').jstree('disable_node', value.id);
	    }
	});
```

The code above disables the nodes of all unselected items however,

In case the tree is collapsed, the context menu is NOT disabled for all disabled nodes and surfaces on right click (Issue).  

While if the tree is NOT collapsed the disable works just fine and context menu does not open up on right click.

**Comment by vakata** [comment]
Setting a node to disabled will not prevent the contextmenu. You must have some other code in place that prevents the contextmenu from showing, but this is not default jstree behavior. If you want to stop the contextmenu on disabled nodes use the `contextmenu.items` function and return `false` if the node in question is disabled.

Best regards,
Ivan
