### ISSUE TITLE
Performance for load_node function on large trees

### ISSUE THREAD

**Issue by vpanu** [vakata/jstree#1237]
In load_node function, for obj.state.loaded there are iterations trough obj.children_d and obj.parents:
```
if(obj.state.loaded) {
	obj.state.loaded = false;
	for(k = 0, l = obj.children_d.length; k < l; k++) {
		for(i = 0, j = obj.parents.length; i < j; i++) {
			this._model.data[obj.parents[i]].children_d = $.vakata.array_remove_item(this._model.data[obj.parents[i]].children_d, obj.children_d[k]);
		}
		if(this._model.data[obj.children_d[k]].state.selected) {
			c = true;
			this._data.core.selected = $.vakata.array_remove_item(this._data.core.selected, obj.children_d[k]);
		}
		delete this._model.data[obj.children_d[k]];
	}
	obj.children = [];
	obj.children_d = [];
	if(c) {
		this.trigger('changed', { 'action' : 'load_node', 'node' : obj, 'selected' : this._data.core.selected });
	}
}
```
For large trees (over 5000 nodes) it takes more that 10 seconds to execute.

If Array.filter it's used the time decrease to under 1 second:

			if(obj.state.loaded) {
				obj.state.loaded = false;
				for(i = 0, j = obj.parents.length; i < j; i++) {
					this._model.data[obj.parents[i]].children_d = this._model.data[obj.parents[i]].children_d.filter( function( el ) {
						return obj.children_d.indexOf( el ) < 0;
					} );
				}
				for(k = 0, l = obj.children_d.length; k < l; k++) {
					if(this._model.data[obj.children_d[k]].state.selected) {
						c = true;
						this._data.core.selected = $.vakata.array_remove_item(this._data.core.selected, obj.children_d[k]);
					}
					delete this._model.data[obj.children_d[k]];
				}
				obj.children = [];
				obj.children_d = [];
				if(c) {
					this.trigger('changed', { 'action' : 'load_node', 'node' : obj, 'selected' : this._data.core.selected });
				}
			}

I made some tests with trees up to 15000 nodes and there are no visible errors and the performance is very good. If you consider that this change has no impact on other features please use it.

**Comment by vakata** [comment]
This is very odd - I regularly test with 30.000 nodes and usually they are loaded within a second or two. Still - I will make sure I updated the code to use `Array.filter` where available.

**Comment by vpanu** [comment]
Hi Ivan,
Please find attached a test example. 
In order to reproduce the error please drag and drop a child to a parent from 1st level (drag a child to category 146) - you'll see in the console the time for refresh_node method.
Thank you,Valentin

**Comment by vakata** [comment]
There is no attachment. But from the description I presume it is not about the `load_node` function, but the `move_node` function. Anyway - as I said - I will add `Array.filter` where possible (I will probably add a polyfill for IE8).

Best regards,
Ivan

**Comment by vpanu** [comment]
In the move_node, tree.refresh_node (load_node is called here). 
Just the javascript:

 $('#tree').jstree({
        'plugins': ["json_data", "state", "contextmenu", "dnd"],
        'core' : {
            'data' : {
                'url': 'tree.json',
                "dataType": "json"
            },
            'check_callback': function (operation, node, node_parent, node_position, more) {
                return true;
            }
            }
    });
    $('#tree').on('move_node.jstree', function (e, data) {
        var tree = $("#tree").jstree(true);
        var parentNode = $("#tree").find("[id='".concat(data.parent).concat("']"));
        t0 = (new Date()).getTime();
        var tree = $('#tree').jstree(true);
        console.log("Start refreshing...");
        tree.refresh_node(parentNode);
        console.log((new Date()).getTime()-t0);
    })

Thank you,
Valentin

**Comment by brickplayer** [comment]
I am struggling with move_node performance problems also.  In Chrome v46. moving a node in a tree with 3000 nodes takes < 1 second.  In IE 11 it takes 5 seconds.

**Comment by mikjo** [comment]
@brickplayer — see #1274 for suggestion to not redraw/sort during bulk operations.
