### ISSUE TITLE
a_attr

### ISSUE THREAD

**Issue by Arvidas1** [vakata/jstree#1238]
As I`ve figured to completely disable d`n`d(not only plugin but also html5) I should configure a_attr as follows :  "a_attr":("draggable":flase) for each node. Is there any way  to do it via types property?

**Comment by vakata** [comment]
No need to add a property - it is enough to `preventDefault` on all `mousedown` or `touchStart` events firing on `.jstree-anchor` nodes. 
As for mass attribute assigning - yes, it is possible using the latest code from the repo. Add a `a_attr` property to the type configuration and list any properties you want added.
