### ISSUE TITLE
The dist/libs/jquery.js is not included

### ISSUE THREAD

**Issue by edalton87** [vakata/jstree#1239]
The "libs" directory is not included in your download files.

**Comment by vakata** [comment]
Yes, that is intentional - you should add your own jQuery. I used to have a copy of jQuery in that folder but that is redundant - most people already have jQuery in their projects, and that causes conflicts (versions, locations, etc).

Best regards,
Ivan

**Comment by edalton87** [comment]
I figured it out then.
Thanks a lot for your kind answer!

Best regards,
Edward
