### ISSUE TITLE
Custom attributes ignored

### ISSUE THREAD

**Issue by eddyuk** [vakata/jstree#1241]
If I render menu on server side and wish to place custom attributes in &lt;li /&gt; element, on root level they are preserved. But if there are nested, they are being ignored and not rendered. Example:
Actual HTML:
&lt;li data-ex="1"&gt;&lt;/li&gt;
&lt;li data-ex="2"&gt;
      &lt;li data-ex="3"&gt;&lt;/li&gt;
&lt;/li&gt;

After adding jstree HTML:
&lt;li data-ex="1"&gt;&lt;/li&gt;
&lt;li data-ex="2"&gt;
      &lt;li&gt;&lt;/li&gt;
&lt;/li&gt;

In output the data-ex attribute is missing

**Comment by vakata** [comment]
Your markup is invalid - do not nest a `LI` node directly inside another `LI` node. Here is a demo with valid markup - all attributes are preserved: http://jsfiddle.net/DGAF4/874/

Best regards,
Ivan

**Comment by eddyuk** [comment]
Thanks
