### ISSUE TITLE
Search when data is loaded via function

### ISSUE THREAD

**Issue by shactdeveloper** [vakata/jstree#1243]
Hello, I have a js tree where I populate the nodes with a function

    core: {
      data: function (node, cb) {
        globalDep.depend();
        var areas = [];
        if(node.id === '#') {
          areas = Areas.find({paiId:null})
        }else{
          areas = Areas.find({paiId:node.id})
        }
        var nodes = areas.map(function(area){
          var children = !!Areas.findOne({paiId: area._id});
          return {
            text: area.nome,
            id: area._id,
            children: children,
            icon:"fa fa-database"
          }
        });
        cb(nodes);
     }

The problem is: when using search plugin, it does not find the nodes that were not opened yet...
is there a workaround for this?

**Comment by shactdeveloper** [comment]
"pai" means "father"....

**Comment by vakata** [comment]
Yes, you can use the `search.ajax` config option:
https://www.jstree.com/api/#/?q=search&f=$.jstree.defaults.search.ajax

Do not worry about the name - you do not have to make an AJAX request - you can also set this to a function, and once ready with a list of nodes that need to be opened - invoke a callback. It is all in the above link.

Best regards,
Ivan
