### ISSUE TITLE
node is not closing if set animation to false

### ISSUE THREAD

**Issue by lrz-hal** [vakata/jstree#1244]
Nodes are not closing if animation is set to false.

    if(!animation || !d.length) {
				/**
				 * triggered when a node is closed and the animation is complete
				 * @event
				 * @name after_close.jstree
				 * @param {Object} node the closed node
				 */
				this.trigger("after_close", { "node" : obj });
			}
			else if(d.length) {
				if(!animation) {
					d[0].className = d[0].className.replace('jstree-open', 'jstree-closed');
					d.attr("aria-expanded", false).children('.jstree-children').remove();
				}

So if you set animation in config to false you never reach the point to close the node.

**Comment by vakata** [comment]
Thank you for reporting. I am terribly sorry - I do not know how I missed that.

Best regards,
Ivan

**Comment by lrz-hal** [comment]
No problem!

Martin
