### ISSUE TITLE
About Nuget Package

### ISSUE THREAD

**Issue by mganitombalak** [vakata/jstree#1245]
Please help about nuget package.Which one has been developing by you?

![image](https://cloud.githubusercontent.com/assets/6146729/10339947/7fe1287a-6d16-11e5-935a-8f7d2b42f662.png)

**Comment by vakata** [comment]
Hello,

Unfortunately I do not maintain the nuget package, as it was published because I could publish it myself. The most recent one should be this one:
https://www.nuget.org/packages/jsTree/

I will contact Tom to update to v.3.2.1

Best regards,
Ivan

**Comment by mganitombalak** [comment]
Thanks for your response. I will consider it.
