### ISSUE TITLE
Jstree renders a huge json incorrectly

### ISSUE THREAD

**Issue by myroman** [vakata/jstree#1247]
I'm using some basic demo javascript from jstree.com which loads a huge json, and jstree renders it incorrectly: the nodes "BugId" which should be second-level nodes, appear in the first level, and their parents are not shown in jstree. As an example, below I pasted a small fragment of that file which does work (I wasn't able to successfully attach a bigger version - but can send it to you).

{"text":"Snapshot 09/18/2015","children":[{"text":"Version: 364","type":"file"},{"text":"<empty>","children":[{"text":"BugId=1177","children":[],"id":"1177"},{"text":"BugId=1073","children":[],"id":"1073"},{"text":"BugId=1658","children":[],"id":"1658"}],"id":"628"},{"text":"12Mnkys","children":[{"text":"BugId=2961","children":[],"id":"2961"}],"id":"1875"},{"text":"1sponsor","children":[{"text":"BugId=3072","children":[],"id":"3072"}],"id":"1976"},{"text":"2leep","children":[{"text":"BugId=1128","children":[],"id":"1128"}],"id":"671"},{"text":"33Across","children":[{"text":"BugId=498","children":[],"id":"498"}],"id":"256"},{"text":"3DStats","children":[{"text":"BugId=466","children":[],"id":"466"}],"id":"267"},{"text":"4stats","children":[{"text":"BugId=2375","children":[],"id":"2375"}],"id":"1412"},{"text":"4w Marketplace","children":[{"text":"BugId=2321","children":[],"id":"2321"}],"id":"1366"}]}

**Comment by vakata** [comment]
`data` should be an array. Here is a demo using your data, I believe it is rendered correctly (provided you pass in an array instead of an object):
http://jsfiddle.net/DGAF4/878/

Best regards,
Ivan
