### ISSUE TITLE
Disabled:true causes Glyphicon to disappear

### ISSUE THREAD

**Issue by AtronSeige** [vakata/jstree#1248]
When i set a node to disabled:true the glyphicon disappears. The node still remains a hyperlink with mouseover color changes.

**Comment by vakata** [comment]
I just tested all modern browsers with a disabled node with both font-awesome & glyphicon icons and all worked as expected. I also experimented with image based icons and they too worked fine.

Using a font-based icon set should not cause issues - you may be using an old bootstrap version with image based icons? Could you please detailed information - bootstrap / glyphicon versions, jstree version, browser you are using - I will reopen the issue when further information is provided.

Best regards,
Ivan
