### ISSUE TITLE
Object not properly cloned when passed to web worker in IE10

### ISSUE THREAD

**Issue by viveleroi** [vakata/jstree#1252]
We're loading data via xhr, passed to the `core.data` callback function.

Looking into why `children` properties were vanishing from our data object, I've traced it to the `delete d.children` inside the `parse_nest` function, nested inside the `func` method run inside a web worker.

This is odd though because web workers should operate on *cloned* data. The `delete` operation works as expected in Chrome/Firefox, but in IE10, on Windows 7, it's modifying the original object too.

Deleting the property (`delete args.dat[0].children;`) as a test right before `w.postMessage(args);` is called, has the proper and same effect across all browsers.

Deleting the same property (`delete data.dat[0].children; `) inside `func = function (data, undefined) {` only tramples our original object in IE10.

**Comment by vakata** [comment]
If this really is the case - the bug is in IE, not jstree - there is not much a I can do - I can't stop using `delete`, sorry. 
I will however have a closer look as this is very interesting - I will see if I can confirm.

Best regards,
Ivan
