### ISSUE TITLE
Drag/drop helper arrow shows up when reordering is disabled

### ISSUE THREAD

**Issue by cchilds** [vakata/jstree#1255]
On a tree I have created, I am using both the dnd and sort plugins. When dragging one node over another, a little helper arrow shows up to indicate where the node will be dropped. The problem with this is that all of my nodes are in a specific order. It is then confusing to the user when they drag a node, and the helper arrow indicates they can reorder, but dropping does nothing. This is especially an issue when dragging a node over a folder. Depending on where you hover your mouse, the helper arrow will show up in 3 places: before, on, and after the folder. Since sorting is disabled, the before and after positions make no sense and don't do anything. In this case, it would be nice to only have the helper arrow on the folder, not before or after.

Please add an option to disable the reordering helper arrow when sorting is used.

**Comment by vakata** [comment]
Please use the documented `core.check_callback` config option and disable "before" and "after" drops.
If you have further questions - please use the discussion group.

Best regards,
Ivan

**Comment by cchilds** [comment]
That was exactly what I needed, thank you. However, I wouldn't have had this issue if the documentation for `core.check_callback` had some more helpful information in it. For example, a simple explanation of what each of the parameters are. Before you replied, I had no idea that "before" and "after" information was even available to me. Only after digging around with the chrome debugger and guessing that `more.pos = 'a'` was what I was looking for, was I actually able to make some progress.
