### ISSUE TITLE
Problem IE8 html source data

### ISSUE THREAD

**Issue by afboteroz** [vakata/jstree#1263]
Hi, i found a problem with IE8 when you use the html datasource, in the method redraw_node inside the if(this.settings.core.force_text) decision when you concat the string of the node object with the html it fails because of the quotes. (node.childNodes[1].innerHTML += obj.text;)
Ex: if obj.text has quote in the html passed as datasource fails in the assignation to innerHtml

**Comment by vakata** [comment]
Could you please provide a working demo of this issue as I can not reproduce it - maybe a jsfiddle? Also make sure IE8 is not in compatibility or quirks mode.

I will reopen the issue when more information is provided.

Best regards,
Ivan
