### ISSUE TITLE
selected_parent_open  can't work !

### ISSUE THREAD

**Issue by lakeoffaith** [vakata/jstree#1268]
i post my request on stackoverflow   
https://stackoverflow.com/questions/33405382/parent-node-should-be-closed-when-child-node-is-open

but no one answer,hope someone to give me a advisor.

**Comment by vakata** [comment]
There is no such option in v.3 - you are using v.3 code with options from jsTree v.1 - please read the docs (and API docs) to see how to work with v3.

Best regards,
Ivan
