### ISSUE TITLE
how to hide other nodes when search

### ISSUE THREAD

**Issue by futurist** [vakata/jstree#1269]
````
<form id="s">
  <input type="search" id="q" />
  <button type="submit">Search</button>
</form>
<script>
$("#container").jstree({
  "plugins" : ["search"]
});
$("#s").submit(function(e) {
  e.preventDefault();
  $("#container").jstree(true).search($("#q").val());
});
</script>
````

If using above demo code in fiddler,  if search with key word `Node 1`,  how to hide `Node 2` and other nodes, and only show `Node 1` and it's parent?

**Comment by vakata** [comment]
Hi,

Please use the discussion group for "how-to" questions. As for your question - read the API docs - you are looking for the `show_only_matches` option.

Best regards,
Ivan
