### ISSUE TITLE
How to develop jstree plugin and add own properties to nodes?

### ISSUE THREAD

**Issue by VoidVolker** [vakata/jstree#1270]
Hi!
I want develop plugin, which well operate additional data in nodes. But I don't understand how to add own fields into node when it's creates and bind inside plugin some actions to this data. Field 'data' is can transfer some simple values like string or numbers, but some jQuery objects is destroying and can't be transferred (looks like it is a bug).

**Comment by vakata** [comment]
Please use the discussion group for how-to questions. As for the question - examine the `src/misc.js` file - it has a lot of example plugins.

Best regards,
Ivan

**Comment by VoidVolker** [comment]
> discussion group for how-to
Where this group? Thanks for the answer and examples link.
