### ISSUE TITLE
custom attributes on `ul` nodes should be preserved

### ISSUE THREAD

**Issue by jochenberger** [vakata/jstree#1271]
http://jsfiddle.net/92w4uqkk/
If I initialize a jsTree from HTML data, custom attributes on the `li` elements appear in the target tree whereas those on the `ul` nodes are not preserved.

**Comment by vakata** [comment]
Hi,

Thank you for the demo, but sorry, this is how jstree works - it will not be possible to preserve attributes on `UL` nodes. Keep in mind HTML should be used for simple use cases - the HTML data source only exists to enable you to quickly convert existing navigations / small trees / etc. 

If you need something more complex - JSON is the way to go.

Best regards,
Ivan
