### ISSUE TITLE
Really poor performance for moderately sized trees

### ISSUE THREAD

**Issue by cchilds** [vakata/jstree#1274]
It is not uncommon for my users to have a few thousand nodes in their trees. For smaller trees, with less than a hundred nodes, performance is typically decent. When you start to get bigger than that, performance gets noticeably worse with size. I have created a [jsfiddle](http://jsfiddle.net/2Jg3B/82/) that demonstrates this poor performance with a simple tree with only 1000 nodes. Simply moving 1000 nodes takes about a minute and a half in Chrome. In IE 11, I waited for over an hour and the operation never finished. The tab just crashed.

When doing some profiling in Chrome, I noticed that almost all the time was spent in redrawing and sorting the nodes. There is no reason for the tree to be redrawing and sorting with each and every node changed. So I simply removed the redraw and sort methods (set them to jQuery noop), perform an operation, and then restore the methods. The performance is drastically better. IE was able to move and delete the same number of nodes nearly instantaneously. Please see this [jsfiddle](http://jsfiddle.net/2Jg3B/84/) for an example.

Bulk operations of all types should not be redrawing or sorting until the end. For my use case, I have used this hack to get around the abysmal performance in larger trees, but it would be nice if this was handled by the library in a less hackish way.

**Comment by vakata** [comment]
Hello, 

Thank you for the detailed description and the fiddles - that is really great. 

Unfortunately, I can not add this functionality as it is, as it will have side effects in some use cases - v.3 is build around sync operations and many developers depend on the DOM updating as the events trigger.

I am however working on a custom virtual DOM implementation for jstree v.4, which completely decouples the visualization from the underlying data structure and only redraws when the browser is free.

So I will hold off from such major changes in the v.3 branch and keep my focus on v.4, if it takes too long I will wrap your idea in a plugin and bundle it in v.3, but for now I am closing this as "won't fix in this version".

Best regards,
Ivan
