### ISSUE TITLE
Search with show_only_matches extremly slow

### ISSUE THREAD

**Issue by zottto** [vakata/jstree#1276]
We have a jsTree (3.1.1) implementation with a search field with show_only_matches enabled.
We had some performance issues with big trees (>5000 nodes), so I upgraded to version 3.2.1, because the release notes mentioned a performance increase for exactly this (search with show_macthes_only).
After the upgrade the search now is massively slow and unusable for trees with 500 nodes already. If I turn off "show_matches_only", the search is much faster again.
Downgrading to version 3.1.1 makes the search also much faster again.

**Comment by vakata** [comment]
Have you tried the code from the repo, as I believe this problem was fixed. Either get the source from the repo or wait for v.3.2.2 which will be available in a few days.

Best regards,
Ivan
