### ISSUE TITLE
What is the meaning the fields in the database: lft, rgt, pid, pos?

### ISSUE THREAD

**Issue by KoninSergey** [vakata/jstree#1277]
What is the meaning the fields in the database: lft, rgt, pid, pos?

**Comment by vakata** [comment]
The PHP / mySQL part is not supported, it just serves as a demo - keep that in mind.
As for the fields - I believe they are described in the source, they are: the left / rights indexes (nested set model), the parent id / position (adjacency model).

**Comment by ncross42** [comment]
"modified preorder tree traversal algorithm"  will be helpful for you~!
