### ISSUE TITLE
Error using JSON flat data when parent of child is not present

### ISSUE THREAD

**Issue by cfales** [vakata/jstree#1278]
I am using the Flat JSON format where all nodes (parent and child) are provided in a flat format, such that each child node contains its parent id.   The problem can arise in which a child node is present in the data but the parent node is not available.  In this case jsTree crashes with an exception on line 1718, due to the missing parent node and no data is loaded.   Now, this is a problem with the data, and not a bug in jsTree, but it would be nice if jsTree could fail gracefully and just skip that problem item rather than failing on the full data set.  In this case I do not have control over the source data being provided and it may be due to security/readership restrictions on the data that visibility to a higher folder has been limited but the child folder left visible. Resulting in the child node being returned in the data set but not the parent.  From a presentation perspective I just need to skip past the problem node.   

I have resolved the issue by adding a try/catch statement at line 1718 in the code as follows;
```
    // 2) populate children (foreach)
    for(i = 0, j = dat.length; i < j; i++) {
        try{
            m[dat[i].parent.toString()].children.push(dat[i].id.toString());
           // populate parent.children_d
           p.children_d.push(dat[i].id.toString());
        }catch(e){}
    }
```
This seems to do the trick perfectly.  All other nodes are rendered properly.  It would be great if this could be included in any future releases.  

Thanks, 

Chris

**Comment by vakata** [comment]
It is not a good idea to "mask" the error in this way. In my opinion it is better to fail, but I will think of a way to recover and notify of the failure for the next version.

Best regards,
Ivan
