### ISSUE TITLE
jsTree not working in modal

### ISSUE THREAD

**Issue by DanStopka1985** [vakata/jstree#1281]
http://plnkr.co/edit/DkKcAhKf1SG99rEx279g?p=preview
I wrote question on stackoverflow about this issue
http://stackoverflow.com/questions/33753321/contextmenu-plugin-not-work-in-modal-bug-in-jstree

**Comment by vakata** [comment]
This is not a bug, it has been discussed a lot here. I will not participate in z-index wars - just use your own CSS to make sure that the `.vakata-context` element has a high enough z-index for your application.

Best regards,
Ivan

**Comment by DanStopka1985** [comment]
thanks!

**Comment by BardhylGit** [comment]
Is there method to specify the container or context of the context menu, because the solution with z-index have problems with position of context menu while scrolling of the content of the modal?
