### ISSUE TITLE
Massload loads the nodes that already are loaded.

### ISSUE THREAD

**Issue by side-by-side** [vakata/jstree#1283]
When searching via ajax, "massload" plugin makes a request to load nodes even if they are already loaded.
Simple example: if we search for the same string two times, "massload" will make two requests to load the same nodes.

@gitSquirel (https://github.com/vakata/jstree/issues/1261#issuecomment-150928432) mentioned that.
The fix is easy, something like that:
```javascript
massload: function(nodes, callback) {
    var notLoadedNodes = [];
    for (var key in nodes) {
        if (!nodes.hasOwnProperty(key)) continue;
        if (!this.is_loaded(nodes[key])) {
            notLoadedNodes.push(nodes[key]);
        }
    }
    if (notLoadedNodes.length == 0) {
        callback([]);
        return;
    }

    $.get('/url', {ids: notLoadedNodes.join(',')}));
    ...
}
```

But this should be included in the plugin itself.

**Comment by vakata** [comment]
Thank you, but let's keep it all in one ticket - that way I can manage the tickets better. So I will close this one and keep working on #1261 

Best regards,
Ivan
