### ISSUE TITLE
Cannot know in which tree node is being moved to (DND)

### ISSUE THREAD

**Issue by lyz452** [vakata/jstree#1284]
Example of my problem:
I have 4 tree: 2 sources (1 blue, 1 red) and 2 targets (1 blue, 1 red).
The user can take element from the source and drop them in the target (and can put them back if they change their mind) but shouldn't be able to mix the blue and the red elements together.

With 'check_callback' to set my permissions, I know if it is dragged in a different tree (multi_tree == true) but I cannot know in what tree (tree ID) the item is being dragged on...

**Comment by vakata** [comment]
https://www.jstree.com/api/#/?q=copy_node&f=copy_node.jstree - there you have the `old_instance` and `new_instance` properties, and in `check_callback` you have `origin` and `this`.

Best regards,
Ivan
