### ISSUE TITLE
 select node in jsTree by click on title. Node should not change it checked state.

### ISSUE THREAD

**Issue by DanStopka1985** [vakata/jstree#1285]
I want to select node in jsTree by click on title. Node should not change it checked state.
I read jsTree checkbox plugin documentation, but have not found about this. 
Is it possible? 
http://stackoverflow.com/questions/33690452/can-i-select-a-node-but-not-check-uncheck-it-in-jstree

**Comment by vakata** [comment]
Yes, it is. Use the `tie_selection` checkbox config option when creating the tree:
```
$('#tree').jstree({
  checkbox : {
    tie_selection : false,
    ...
```
I would recommend reading about the other checkbox options in the API docs on jstree.com, as you might want to tweak those too (like `whole_node : false`).

Best regards,
Ivan

**Comment by DanStopka1985** [comment]
Thanks!
