### ISSUE TITLE
[BUG] Clicking an ajax-loaded node with subsequent data load results in Javascript error

### ISSUE THREAD

**Issue by temuri416** [vakata/jstree#1286]
Hi Ivan,

I cannot find anything wrong with what I'm doing, so I decided to file a bug.

Setup:
* My tree is loaded via AJAX on page load
* All my nodes are loading data on click from server
* I have one root node
* Clicking root node (or, any node for that matter) is supposed to reload children of that node from server

The initial look of the tree:

![image](https://cloud.githubusercontent.com/assets/3987203/11244219/6bc1798c-8dda-11e5-8d48-25274b9a1fe9.png)

The problem is that clicking root "**Item**" node correctly fetches data from server (i.e. refreshes the node), but then JSTree is crashing with the following error:

```
TypeError: this._model.data[obj.children_d[k]] is undefined
if(this._model.data[obj.children_d[k]].state.selected) {
```

This is the line: https://github.com/vakata/jstree/blob/master/dist/jstree.js#L1194.

I'm attaching source files to reproduce the problem. **Don't forget to rename them to *.html.**

[index.txt](https://github.com/vakata/jstree/files/37968/index.txt)
[data.txt](https://github.com/vakata/jstree/files/37969/data.txt)

Thank you!

**Comment by vakata** [comment]
This error only happens if you have duplicated IDs in your data (or if using the flat format you have nodes that are missing). In the next version this error will be handled gracefully, but still - you need to fix your data.

Best regards,
Ivan

**Comment by temuri416** [comment]
> if you have duplicated IDs in your data

But when re-fetching node's children - they will all have the same IDs (that map to object primary keys), right?

**Comment by vakata** [comment]
Yes, I believe there was a plugin in misc.js or in the discussion group somewhere that always fetched data from the server when opening a node (basically it was "unloading" the node when closed).

Best regards,
Ivan
