### ISSUE TITLE
Doesn't seem to work in Internet Explorer 8

### ISSUE THREAD

**Issue by sphengle** [vakata/jstree#1287]
I did my own example using Ajax and it works perfectly in Chrome but in IE I get Javascript errors.

I then looked at your website (jstree.com) and that too gives errors in IE8.

Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Zune 4.7)
Timestamp: Thu, 19 Nov 2015 15:56:46 UTC

Message: Script error
Line: 0
Char: 0
Code: 0
URI: https://static.jstree.com/3.2.1/assets/dist/jstree.min.js

**Comment by sphengle** [comment]
Also ....
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; Zune 4.7)
Timestamp: Thu, 19 Nov 2015 16:03:17 UTC


Message: Unexpected call to method or property access.
Line: 5929
Char: 5
Code: 0
URI: http://localhost:58272/Scripts/jquery-1.9.0.1.js


Message: Unexpected call to method or property access.
Line: 5929
Char: 5
Code: 0
URI: http://localhost:58272/Scripts/jquery-1.9.0.1.js

**Comment by sphengle** [comment]
Apologies - this error was related to how I was reacting to the change event and had nothing to do with the jsTree plugin.

**Comment by vakata** [comment]
No problem, thanks. Keep in mind IE8 will not work in compatibility mode.
