### ISSUE TITLE
How to dynamically enable a plugin?

### ISSUE THREAD

**Issue by dchaib** [vakata/jstree#1291]
I am trying to set up a tree with a "edit mode" triggered in JavaScript. This "edit mode" consists in enabling drag and drop and the context menu.

I have tried to dynamically enable the relevant plugins, but I haven't found a way to do this directly. I have also tried to recreate the tree, but this "breaks" the state plugin: the "new" treeview's node names start with "j2" and do not match the nodes in the saved state (which names start with "j1").

What would be the proper way of dynamically enabling a plugin?

**Comment by vakata** [comment]
Sorry, but you can't - the only way is to recreate the instance, I see you have already tried that and ran into a problem with autogenerated IDs, unfortunately the only way to avoid that is not to depend on autogenerated IDs and pass your own. You could also use the `state` callback and modify the state to match the new tree IDs but that won't be a very clean solution.

Once again - sorry, dynamically enabling a plugin will not be an option. 

Btw, wouldn't it be easier in your case to enable contextmenu and drag'n'drop, but if the user has not toggled the edit flag - to prevent them using `contextmenu.items` function and the `dnd.is_draggable` callback? 

Best regards,
Ivan

**Comment by dchaib** [comment]
Ivan, thanks for your quick and informative answer! That's exactly the kind of information I was looking for. I'll give it a try.

**Comment by dchaib** [comment]
it works like a charm! Many thanks Ivan, I really appreciate it!
