### ISSUE TITLE
html-based tree : jstree.search() will also match HTML and JS inside tree nodes

### ISSUE THREAD

**Issue by PjotrB** [vakata/jstree#1292]
I am using jstree 3.2.1, which has this search function:
search = function(str, skip_async, show_only_matches, inside, append, show_only_matches_children)

Our tree is derived from a div with nested `<ul><li>` nodes.
All of our li nodes contain multiple `<span>` elements + a button `<button onclick="...">...</button>` + a small piece of inline JS between `<script>` tags.

Then this occurs, which I believe is a bug:
If the user searches for html-ish text such as `span` or `<button` or `onclick`, or even part of the JS code(!), then ALL tree nodes are found as matches. Basically any piece of html or script inside the `<li>` will match.
I would expect it to only match the text of elements.

And what about this idea:
Define some kind of attribute or perhaps a css class that tells the search routine where it can search, so the rest is skipped (still text-only of course). That way I can prevent it from finding matches in e.g. my button text, and match only where I want it.
The css class or attribute text can be made a parameter of the search() function and/or of the global search settings, so it does not have to be hardcoded by you.

**Comment by vakata** [comment]
I will see if I can improve on this situation, but you need to keep all additional HTML outside of the anchor node and search will work fine (or add any additional markup using a plugin). In the mean time you can use the `search_callback` function and control what is considered a match manually.

Best regards,
Ivan

**Comment by PjotrB** [comment]
Thanks, yes I think using search_callback is the way to go for me.

If you decide to have a go at changing it, perhaps also better to rename the `.text` propery (which is what is currently being searched) to `.html` or even `.innerHtml` because that describes better what it actually contains.
Renaming it would help avoid further / future confusion, but would also break things for people who already use .text themselves to put their html into. Tough choice maybe...
