### ISSUE TITLE
After upgrading from v3.1.1 to v3.2.1 the search results are not properly shown as expected

### ISSUE THREAD

**Issue by ranadeepak** [vakata/jstree#1293]
Hi,
I recently upgraded from v3.1.1 to v3.2.1. I was using search plugin with 'show_only_matches' to true. With v3.1.1 it was not displaying the non matching nodes and displaying matching nodes with different css style. But after upgrade to v3.2.1 it is showing all the nodes and matching nodes in different css style.

For E.g. if I have following tree str:
A\B\C\USA
A\B\C\Germany
A\B\D\USA2
A\D\India

and user searches for string 'US' the matching nodes were displayed:
A\B\USA  //with different css styling
A\B\D\USA2  //with different css styling

But now the tree is displaying as:
A\B\C\USA //with different css styling
A\B\C\Germany
A\B\D\USA2  //with different css styling
A\D

I looked into the latest jstree code and found that there are changes in code related to deselecting the nodes earlier it was done directly by setting css classes but now the hidden state of node is set with other settings.
am I missing any setting or there is any other change required

Thanks

**Comment by vakata** [comment]
You probably forgot to update the CSS file as well as the JS file (or did not clear the cache). I got a similar ticket a few times, so I am pretty sure this is it. If it is not I will reopen.

Best regards,
Ivan

**Comment by ranadeepak** [comment]
Thanks the issue is resloved after css update
