### ISSUE TITLE
$.jstree.defaults.search.show_only_matches_children has no effect

### ISSUE THREAD

**Issue by hanneseilers** [vakata/jstree#1295]
If $.jstree.defaults.search.show_only_matches set to true and $.jstree.defaults.search.show_only_matches_children is set to true. Still only the found nodes are shown and not their child nodes.

**Comment by hanneseilers** [comment]
Sry. Had old version.

**Comment by LucienLaw** [comment]
hello,have you finally solved this issue? I caught the same problem.Hopes for your response.

**Comment by vakata** [comment]
@LucienLaw Here are the demos:
http://jsfiddle.net/DGAF4/1691/
http://jsfiddle.net/DGAF4/1692/
