### ISSUE TITLE
how to get nodes added dynamically

### ISSUE THREAD

**Issue by erick2014** [vakata/jstree#1299]
Hi guys, I was wondering how can I get all nodes that are added dynamically to the tree, if I have something like 
<pre>
$("#plugins2").jstree({
  "core" : {
     'force_text' : true,
     "check_callback" : true
   },
   "plugins" : [ "contextmenu" ]
})
</pre>
then, the user do a right click over a directory and he decides to create some directories, then which method can I invoke, to get the current tree? thanks!

**Comment by vakata** [comment]
You can use `get_json` which will get you the whole tree. Or if you want to react on each node creation - use the `create_node.jstree` event.

Best regards,
Ivan

**Comment by erick2014** [comment]
Thanks for your reply, I was trying something like :  
<pre>
$("#plugins2").jstree({
        "core" : {
          "data":[
            {
              "text":"Root node","children":[
                {"text":"Child node 1"},
                {"text":"Child node 2"}
              ]
            }
          ],
          'force_text' : true,
          "check_callback" : true
        },
        "plugins" : [ "contextmenu" ]
      });
     var ref=$.jstree.reference('#plugins2');
     var tree=ref.get_json({"flat":true});
</pre>

But how can I get the "data" that has the nodes, and child nodes? I want to save that array to later render it again
