### ISSUE TITLE
Cannot Load JsTree as AMD Module

### ISSUE THREAD

**Issue by erikthinkiq** [vakata/jstree#1302]
Regarding the line that jsTree "can be loaded as an AMD module" in the README, can you give an example using require? I have not been able to load jsTree as an AMD module using require. There is no return statement. When I add "return $.jstree;" at the end of the file, that object is imported successfully using require. But I have a feeling that's not the correct object to return.

**Comment by vakata** [comment]
jsTree is loaded entirely in the `jQuery` object (as it is a jQuery plugin), so you should access it using `jQuery.jstree`. I am using this template for universal loading:
https://github.com/umdjs/umd/blob/master/templates/jqueryPlugin.js

Best regards,
Ivan

**Comment by erikthinkiq** [comment]
Thanks for the clarification.
