### ISSUE TITLE
Massload state

### ISSUE THREAD

**Issue by dotomaz** [vakata/jstree#1303]
I would like to use massload plugin to load state in one request. Mass load url gets called bur regular ajax request are called also:

![](http://i.imgur.com/1Ff61kH.png)

*tree-node* loads single node, _tree-node**s**_ loads multiple nodes

If I comment out core.data in config the  regular ajax is not called. Massload request still gets caled. But the tree diesn't load.

Also the root node (#) is not included in the list of ids in call to the  massload.data function from config.

**Comment by vakata** [comment]
If the normal AJAX URL is called in spite of massload being configured that means that the data you return (in response to the massload request) is not in the correct format. Please read the docs on the format.

Best regards,
Ivan
