### ISSUE TITLE
Option to define the element the nodes are wrapped in a tree instead of always an `a`

### ISSUE THREAD

**Issue by guill3m** [vakata/jstree#1304]
Sadly this is a deal breaker in our case when trying to update from 1.0.0-rc3 to the latest version unless we can find a workaround to it.

In version 1 the content of the tree node was not wrapped in anything, in version 3 it gets wrapped in an `a` element that also has an `event.preventDefault()` for clicks, this completely breaks our implementation:

- Checkboxes inside the node (not jsTree ones but other rendered directly in the html) are not clickable.
- Labels for those checkboxes are not clickable either.
- `a` elements inside the node are not clickable either.

Those are just some problems with one implementation, I'm sure other implementations will have similar problems with using an element that has meaning and functionality instead of one without semantic or functionality already defined (like a `span`).

At first I thought it was to have the ability to navigate the tree with the tab key, but then I realized that the `a.jstree-anchor` elements have a `tabindex="-1"` attribute applied, which removes that tabbing.

What is then the reasoning for using `a` instead of `span`?

Is there a way to make this wrapper a `span` or a `div` if needed?

If there isn't: why not? is this required to be an `a` element?

**Comment by vakata** [comment]
Hello,

Please read up on accessibility for trees - jsTree is implemented with visually impaired people in mind - this is the reason why anchor elements are used, and the navigation is implemented according to the WAI tree specification - using the arrow keys (and some other keys like space, enter, etc).

As for adding additional elements to the tree - create a plugin for that - just setting an HTML string as a title of the node can work, but it will require more work than adding a plugin which is the correct way to handle this. Take a look at `src/misc.js` for sample plugins. 
By using a plugin you can render all kinds of elements (not necessarily inside the anchor node - the list item is a good option too) and can attach various events which will not affect the already attached events on the anchor nodes.

Best regards,
Ivan

P.S. v.4 (which is in the planning and experimenting phase) will likely have the draw part as a plugin, which will mean that you can easily swap out the DOM format with your own (if that is really what you need), but I doubt it will be ready before next summer.

**Comment by guill3m** [comment]
OK, will take a look. Thank you @vakata

**Comment by guill3m** [comment]
Hi @vakata, are there any news about that v.4 that you mentioned here? Thank you.

**Comment by vakata** [comment]
There is a new option in v.3 which allows you to change the default node structure: 
https://github.com/vakata/jstree/pull/1616

It is already in the core, you can use it right away - create a plugin which overrides the `_create_prototype_node` function and activate the plugin on your instance. The author of the pull request linked above has already done this if you want to get in touch with him.

As for v.4 - it won't be available until spring. So I am not sure if it will be a good idea to wait.
