### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by changbaishan** [vakata/jstree#1305]
First thank you for open sourcing your wonderful jstree.

Node text may be long, or additional information may be necessary to help users. I would suggest adding tooltips so we can truncate long node text, or present some additional information when displaying jstree..

Best regards.

**Comment by vakata** [comment]
Hi,

Thank you for the idea, but custom tooltips are out of the scope of jstree. As for built-in tooltips - you can use a title attribute on the anchor nodes (by using `a_attr` in your data), which will render the default browser tooltips. If you need custom tooltips - you can attach any library you like, just do not forget to update its bindings (if necessary) when jstree repaints.

Best regards,
Ivan

**Comment by changbaishan** [comment]
Thank you very much.


________________________________
