### ISSUE TITLE
Rename node strange behavior

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [vakata/jstree#1308]
Hi, when I click 'rename' on context menu, the label turns into an editable label as it should but less than 1 sec after, it turns back to a normal label, as if I clicked enter. I noticed this on my app and thought it was something wrong that I was doing. After some time trying fix it, I went to the official examples:
https://www.jstree.com/demo/
And found that the same thing was happening there! (on the Ajax demo, my app also uses 'ajax', in fact im using meteorJS, but still loads the nodes through a reactive data function)
Im on ubuntu 14.04 LTS, using chrome Version 47.0.2526.73 (64-bit)

**Comment by vakata** [comment]
Sorry about that - I will spin up a VM as soon as possible and fix it.

Best regards,
Ivan

**Comment by Sharvadze** [comment]
Same here... using OSX El Capitan and Chrome Version 48.0.2564.116 (64-bit)

**Comment by vakata** [comment]
@rafaelcorreiapoli @Sharvadze could you please confirm that this is still an issue in Chrome 49, as I just tested with that (on Ubuntu and Mint) and could not reproduce the issue. I will reopen if this is still an issue, sorry for taking so long to respond.
