### ISSUE TITLE
Some Plugins dont work

### ISSUE THREAD

**Issue by bennisen** [vakata/jstree#1312]
I have a tree with Types and Icons. This works fine, but some Plugins seems to be not working if i enable them. I make some tests, wholerow and sort dont work, but checkboxes works. At the Moment i only need the Plugin sort. Is there something i forgot? Here is my JS

$('#treeView').jstree({
        "types" : {
            "directory" : {
                "icon" : "folder outline icon"
            },
            "file" : {
                "icon" : "file text outline icon"
            },
            "pdf" : {
                "icon" : "file pdf outline icon"
            },
            "audio" : {
                "icon" : "file audio outline icon"
            },
            "image" : {
                "icon" : "file image outline icon"
            },
            "word" : {
                "icon" : "file word outline icon"
            },
            "excel" : {
                "icon" : "file excel outline icon"
            },
            "powerpoint" : {
                "icon" : "file powerpoint outline icon"
            },
            "video" : {
                "icon" : "file video outline icon"
            }
        },
        "plugins" : [ "types", "sort" ]
    });

edit: wholerow now works and sort too. I realized that sort differences between high and low alpabetics.

**Comment by vakata** [comment]
So, basically after the edit everything is working? Just for information: there are no conflicts between modules with the exception of wholerow hiding the theme "dots" option.

Best regards,
Ivan
