### ISSUE TITLE
selected data is wrong when define conditionalselect

### ISSUE THREAD

**Issue by h03yn** [vakata/jstree#1315]
When define conditionalselect like:
`conditionalselect: function (node) { return this.is_leaf(node); }`
tree must select leaf node, but when you select all children, parent and children all select in tree
and in selecte_node event data.selected is wrong
```
$('#tree'').jstree({
	"core": {
		"multiple": isMulti,
		'data': result,
		'themes': {
		'variant': 'medium',
		'icons': false
	}
},"plugins": ["conditionalselect", "wholerow", "checkbox"],
	conditionalselect: function (node) { return this.is_leaf(node); }
}).bind("select_node.jstree", function (evt, data) {
		data.selected ------>is wrong
}).bind("deselect_node.jstree", function (evt, data) {
                data.selected ------>is wrong
});
```

**Comment by vakata** [comment]
Please read the docs on the conditional select plugin and the checkbox plugin. Conditional select only limits what THE USER can select, all automatically selected nodes will not be affected, which is the case when you use the `checkbox` plugin. If this is not the desired effect - either disable the checkbox plugin or configure it according to your needs.

Best regards,
Ivan
