### ISSUE TITLE
Dont know how to use this Functions

### ISSUE THREAD

**Issue by bennisen** [vakata/jstree#1316]
I searched in the Web for Examples, but there are so many Users building own Functions for jsTree. But in the API from jsTree there are already given Functions to do what i want. But i dont understand how to use this Functions. At the moment i have Problems with is_selected() or get_parent(). The first Function always gives me false als return.

$('#showNewDirModal').click(function() {
        var tree = $('#treeView').jstree(true);
        var selectedNode = tree.get_selected(true);
        var parent, nodeName;

        if (tree.is_selected(selectedNode))
            console.log("Test");
    });

I see that i have to give a Parameter to this Functions, but what is obj? Can somebody show me Examples how to use the Function is_selected() or get_parent() please?

**Comment by vakata** [comment]
in your case `selectedNode` is an array, not a single node. Replace `is_selected(selectedNode)` with `is_selected(selectedNode[0])` and your test code will work properly.

Please use the discussion group for further how-to questions.

Best regards,
Ivan
