### ISSUE TITLE
Can't get search via ajax to work

### ISSUE THREAD

**Issue by natocTo** [vakata/jstree#1317]
Hello, I tried a lot of things before I post issue but I can't get it work. Can't figure out what I do wrong. Can you help me? No nodes are selected after successful server response.

(jsTree v3.2.1)

```javascript
$('#newtree').jstree({
    "core" : {
        "data"[
            { "id" : "ajson1", "parent" : "#", "text" : "Simple root node" },
	        { "id" : "ajson2", "parent" : "#", "text" : "Root node 2" },
	        { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1" },
	        { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2" },
	    ]
    },
    "search": {
        "ajax" : {
	        "url" : "/search"
	    }
    },
    "plugins" : [ "search" ]
});

var to = false;
$('#search_newtree').keyup(function () {
    if(to) { clearTimeout(to); }
    to = setTimeout(function () {
        var v = $('#search_newtree').val();
        if (v.length >= 3) {
      	    $('#newtree').jstree(true).search(v);
        };
    }, 250);
});
```

I tried this responses from search request: (not working)

```javascript
["ajson1"] or ["ajson2"] or ["ajson1","ajson2"]
```

Maybe I misunderstood how this search via ajax works.

I have tree with products. Search function look only to text (name). I need match also there product where context (product text) match searched keywords. I thought I could use there ajax search, find nodes in php on server a then return ids of nodes. But I dont know how make it work..

Now I have this code... It is working but it is not ideal. (I think)

```javascript
$('#relatedProduct_tree').on('search.jstree', function (e, res) {

		$.get("/admin/api/related_product_search", { str: res.str }, function(match) {

			$('#relatedProduct_tree').jstree(true).deselect_all();
			match.forEach(function(entry) {
				$('#relatedProduct_tree').jstree(true).select_node(entry, true);
			});
		});

	}).jstree({
	    "core" : {
	        "data" : {
	            "url" : "/admin/api/related_product"
	        }
 	   	},
 	   	"checkbox" : {
	      	"three_state" : false,
	      	"whole_node" : false,
	      	"tie_selection" : false,
	      	"cascade"  : "down",
	    },
	    "search": {
	    	"search_leaves_only" : true
        },
    	"plugins" : [ "checkbox", "search" ]
});

var to = false;
$('#search_relatedProduct').keyup(function () {
	  if(to) { clearTimeout(to); }
	  to = setTimeout(function () {
          var v = $('#search_relatedProduct').val();
	  if (v.length >= 3) {
	      	$('#relatedProduct_tree').jstree(true).search(v);
	  };
    }, 500);
});
```

Jstree search function finds nodes by name, and then I select node where match by context.

**Comment by vakata** [comment]
Let me clarify - sorry if the docs are lacking. 

The AJAX request is only used to load nodes, the search is always performed on the client. That means AJAX search only makes sense if your tree is lazy loaded. The response should be the nodes that need to be opened in order to reveal the matches. BUT if a node is considered a match is always determined on the client.

By default jstree only searches in the node text for the given string (which you can enhance by setting case sensitivity and enabling fuzzy searches), but if you need full control over what is considered a match - please use the `search_callback` option. That way you have full manual control over which nodes are matches.

Best regards,
Ivan

**Comment by natocTo** [comment]
I will stick with my solution for now but thanks for clarify. Good to know about ajax and search callback option.
