### ISSUE TITLE
Uncaught TypeError when deleting a focused node

### ISSUE THREAD

**Issue by federicotdn** [vakata/jstree#1318]
In some cases, calling `delete_node` on a node results in:
```
jstree.js:3802 Uncaught TypeError: this.get_node(...).children is not a function
$.jstree.core.delete_node @ jstree.js:3802
```

This happens if: the node was focused (after being clicked, in my case), and the node is the only child of the root node (in my case, the node didn't have any children itself).  Tested on `3.2.1`.

**Comment by vakata** [comment]
This was already fixed - use the version from the repo or wait a day or two for 3.2.2:
https://github.com/vakata/jstree/commit/9af6ac4cef99f01bf48c29f9cd6b998e985bfe25

Best regards,
Ivan
