### ISSUE TITLE
Performance issues executing search on medium size data

### ISSUE THREAD

**Issue by nebadom** [vakata/jstree#1319]
Hi,

It's me, once again. But this time is because I was trying to update to your latest jstree (3.2.1) but then, all of the sudden, I started experience performance issues when doing searches.

FYI, I was using version 3.0.8. I noticed that I could update to version 3.1.1 without performance problems. But once I jump to 3.2.X, the whole thing starts to fail. In fact, using 3.2.0 the browser hangs. 

I noticed that there were some changes with the CSS which I had to update just to get the show_only_matches working. 

Any ideas what could it be?

this is my current configuration.

     var options = {
				core : {
					data : treeData,			// I pass all the data to treeData
					check_callback : true,		// Added as per Ivan Bozhanov suggestion
					expand_selected_onload : false
				},
				plugins : ["checkbox","wholerow","contextmenu","search","sort"],
				contextmenu : {
					items : contextMenuCon		// It's declared elsewhere
				},
				search : {
					case_insensitive: true,
					show_only_matches : true
				},
				animation : false
			};

And for the tree data structure, I'm using the alternative JSON format.

Any ideas what can it be? Is there a way I can add some other parameter to core to improve the performance?

**Comment by vakata** [comment]
Have you tried running the version from the repo, not 3.2.1? It has a few speed improvements to searches. Please try it and if it is still slow - let me know and I will reopen the ticket.

Best regards,
Ivan

**Comment by nebadom** [comment]
I'm testing the version you have on master and it seems to work like a charm. What was it? because, honestly, I don't like working on untagged versions. Is there anything I can help you with?
