### ISSUE TITLE
package.json browser section is ignored

### ISSUE THREAD

**Issue by delenius** [vakata/jstree#1322]
I am using the jstree npm module with browserify. I have this in my package.json:

<code>
  "browser" : {
    "jquery" : "jquery/dist/jquery.min.js",
    "jstree" : "jstree/dist/jstree.min.js"
  }
</code>

and I do 

<code>
require('jstree');
require('jquery');
</code>

in my own code. This correctly picks up the jquery.min.js and jstree.min.js files.
However, the full jquery.js is also pulled into the bundle via jstree (as seen by browserify --list). It seems that jstree itself ignores package.json. Is there a nice way to get jstree to only use the minified jquery?

Perhaps I misunderstand how this is supposed to work. I'm pretty new to browserify.

**Comment by vakata** [comment]
I have no way to control this as far as I know. I do not use browserify too, in my tests I usually had to setup `jQuery` as a "shortcut". 

Anyway - I am almost certain that this is not something that can be controlled in the jstree package.json, if you have any ideas on how to do that - please create a pull request.

Best regards,
Ivan

**Comment by delenius** [comment]
I found that it is possible, by changing jstree's package.json in the same way I changed my own top-level package.json. Apparently these settings don't propagate to dependencies. PR created: 
https://github.com/vakata/jstree/pull/1325
