### ISSUE TITLE
ajax search

### ISSUE THREAD

**Issue by MohamedQabbani** [vakata/jstree#1329]
When i return ['n5000'] from server ajax serach not work

<form id="s">
    <input type="search" id="q" />
    <button type="submit">Search</button>
</form>
<div id="tree">
<ul>
    <?php foreach ($data as $key => $value): ?>
        <li class="<?= ($value['has_childes']) ? 'jstree-closed' : '' ?>" id="n<?= $key ?>"><?= $value['name'] ?></li>
    <?php endforeach; ?>
</ul>
</div>
<script>
    var topic_type_id = '<?= $topic_type->TopicTypeId ?>';
</script>

$(function () {
    if($('#tree').length){
        $('#tree').jstree({
            'core' : {
                'data' : {
                    'url' : '<?= Yii::$app->getUrlManager()->getBaseUrl()."/site/get3" ?>',
                    'data' : function (node) {
                        console.log(node);
                        return {'id': topic_type_id, 'node_id': node.id};
                    }
                }
            },
            "plugins" : ["search"],
            "search" : { "ajax" : { "url" : "<?= Yii::$app->getUrlManager()->getBaseUrl()."/site/get4" ?>" } }
        });
        $("#s").submit(function(e) {
            e.preventDefault();
            $("#tree").jstree(true).search($("#q").val());
        });
    }
});

**Comment by MohamedQabbani** [comment]
Should i use callback

**Comment by vakata** [comment]
Please read the docs - the server response should only consist of node IDs that need to be opened, so that the client side search can find the matches. If you want to modify what is considered a match - please use the `search_callback` option, where you have full manual control.

Best regards,
Ivan
