### ISSUE TITLE
Exclude files/folders from tree by pattern

### ISSUE THREAD

**Issue by arieljannai** [vakata/jstree#1330]
Hi,

If it exist, I couldn't find it.
Anyway, it would be great to have an option to exclude by pattern.
For example, show hidden files only when I want to, show only files that match `*.js|*.css` etc.

What do you think?

**Comment by vakata** [comment]
Sorry, this is not available and is not on my todo list. But you are more than welcome to create a plugin that does this. The native show/hide methods should be able to help. Tell me if you need assistance with such a plugin.

Best regards,
Ivan

**Comment by arieljannai** [comment]
Ok, thanks. I'll look at the plugins
