### ISSUE TITLE
jsTree functionality missing when dynamically created

### ISSUE THREAD

**Issue by syrakozz** [vakata/jstree#1333]
hello my code is 
jstree({
                'core': {
                    "check_callback" : true,
                    'data': {
                        "url": "<?php echo Yii::$app->request->baseUrl; ?>/index.php?r=accounting/treejs",
                        "data": function (node) {
                            return {"id": node.id};
                        }
                    }
                }
            });

the response disappear on linux but it works on my mac ,

**Comment by vakata** [comment]
Please create a demo, so that I can reproduce the issue - I can assure you thousands of people use jsTree with AJAX and it is not a known problem.

Best regards,
Ivan
