### ISSUE TITLE
When i aded node plugin try to change id node

### ISSUE THREAD

**Issue by KoninSergey** [vakata/jstree#1334]
When I added the plugin node is trying to change the node ID and error appears. At the same time I do not want to plug changed node ID.

Error: `Uncaught TypeError: Cannot read property 'toString' of undefined`

```
/**
		 * set (change) the ID of a node
		 * @name set_id(obj, id)
		 * @param  {mixed} obj the node
		 * @param  {String} id the new ID
		 * @return {Boolean}
		 */
		set_id : function (obj, id) {
			obj = this.get_node(obj);
			if(!obj || obj.id === $.jstree.root) { return false; }
			var i, j, m = this._model.data;
			id = id.toString(); //THIS APPEARS ERROR
			// update parents (replace current ID with new one in children and children_d)
			m[obj.parent].children[$.inArray(obj.id, m[obj.parent].children)] = id;
			for(i = 0, j = obj.parents.length; i < j; i++) {
				m[obj.parents[i]].children_d[$.inArray(obj.id, m[obj.parents[i]].children_d)] = id;
			}
```

**Comment by vakata** [comment]
What is the "node plugin"? From what I see `set_id` is invoked without the second `id` parameter. If it is your code that is calling `set_id` - make sure you pass in the second parameter.

I am closing this, if you think it is jstree's own code that is calling `set_id` - please provide more info so that I can reproduce the issue.

Best regards,
Ivan

**Comment by KoninSergey** [comment]
>What is the "node plugin"? 

Sorry for spelling. When i aded node, jstree plugin try to change id node

> if you think it is jstree's own code 

Yes it is jstree code 

> please provide more info so that I can reproduce the issue.

If it can help i maked screenshoot
https://www.dropbox.com/s/70g9xx5kpd4ts1t/%D0%91%D0%B5%D0%B7%D1%8B%D0%BC%D1%8F%D0%BD%D0%BD%D1%8B%D0%B9.png?dl=0

**Comment by vakata** [comment]
I think it is obvious from the screenshot that it is NOT jstree's own code. 
Please, take a look at the stack trace and fix the function call from the anonymous inline function in your page.

Best regards,
Ivan

**Comment by KoninSergey** [comment]
It is jstree's own code.
But it does'not matter. The problem was that i returned id after add node, simple id, but the correct was returm array {'id':1}.
Thanks for help.
