### ISSUE TITLE
Can I by drug and drop to move the nodes which are on the same level, those change the sorting nodes?

### ISSUE THREAD

**Issue by KoninSergey** [vakata/jstree#1335]
Now if I take the mouse and move over the node it is moved to the new folder, but I would like to change the order of the nodes on the same level.

**Comment by vakata** [comment]
Yes, this functionality is available and you can see it in action in the demos on jstree.com - just drag slowly and you will see an arrow showing you where the node will be dropped (inside, before or after the hovered node), which basically means that you can sort with drag and drop.

Best regards,
Ivan
