### ISSUE TITLE
Whole Node Checkbox Not Working as Expected

### ISSUE THREAD

**Issue by JordanSinko** [vakata/jstree#1338]
When I enabled the checkbox plugin, and set the 'whole_node' property to false, if the node is unchecked, clicking the node and not the checkbox, checks the checkbox. If the checkbox is already checked, it behaves like expected and doesn't uncheck the node. With the description of the property, I would expect this not to check/uncheck unless physically clicking the checkbox.

**Comment by JordanSinko** [comment]
Here is the jsfiddle of the issue:

https://jsfiddle.net/wh5kko1a

**Comment by vakata** [comment]
Read on the `tie_selection` property - in your case - you need to set it to `false`. By default checked and selected are the same thing.

Best regards,
Ivan

**Comment by aartek** [comment]
I don't know what `tie_selection` exactly do, but `whole_node` probably should not be related with `tie_selection` property. I'd like to keep tree behavior with `tie_selection` enabled, and use `whole_node` at the same time. 

I have something like product explorer, where categories are displayed in tree on the left, and product list is loaded on the right, based on clicked category. User may only want to browse products, so I don't want to check checkbox when he clicks on category name. `whole_node` is exactly what I need, but like Jordan said - it doesn't work as expected.

Even in docs there is description to `tie_selection`

> This setting controls if checkbox are bound to the general tree selection or to an internal array maintained by the checkbox plugin. Defaults to true, only set to false if you know exactly what you are doing.

But I don't know what I'm doing when disabling it, so I won't do it.

**Comment by kpetrow** [comment]
I'm still having this issue.  I have a decently large code base and dont want to change all the select_nodes to check_nodes just to get my context menu to work without having the checkbox fire.  Can I catch this maybe in the check_callback?
