### ISSUE TITLE
jsTree with big data problem

### ISSUE THREAD

**Issue by xujianghao** [vakata/jstree#1339]
Hi:
I have a problem with jsTree.I used ajax and json data to build tree.when one parent node have 1600+
children node should be show,Internet explorer 8 collapse or jammed.
my js like this:
$('#terminalTree').jstree({ /*附件树定义*/
		'core' : {
		'data' : { 
		'cache':false,
		'url':function (node){
		if(node.id=="#"||node.parent=="#"){
			return 'allSecondCategoryList.action';
		}else{
			return  'AllSecondMaterialsList.action';
		} 
	},
	'data':function (node){
		return { 'ids' : node.id};
	}
	},
	'check_callback' : true,
	'worker':false,
	'themes' : {
		'responsive' : false
	},
	'strings' : {
		 'Loading ...' : '正在载入,请稍后...'
	}
	},
	
	'plugins' : ['types','contextmenu','unique','changed'],
	'contextmenu':{'items':contextMenu1}
	}).on("close_node.jstree", function (e, data) {
	    data.instance._model.data[data.node.id].state.loaded = false;
//	    data.instance.delete_node(data.node.children);
	}).on("changed.jstree", function (e, data) {
	      if (data.node.parents.length<3) {
	    	    $("#tab-1").removeClass("active");
	    		$("#tab-3").removeClass("active");
	    		$("#tab-4").removeClass("active");
	    		$("#tab-2").removeClass("active");
	    		if(data.node.children.length==0){
	    			$('#noDataShow').modal({backdrop: 'static', keyboard: false},'show');
	    		}
		}
	});
I should how to optimize？

**Comment by vakata** [comment]
Is the tree fine in IE8 if there are fewer items? As the issue might be with quirks mode or compatibility mode.

**Comment by xujianghao** [comment]
yes,the fewer items is ok!

**Comment by vakata** [comment]
I am sorry - I can only help you if you provide a demo, I can not reproduce the issue with 1600 nodes. I will reopen when I can see a demo.

Best regards,
Ivan
