### ISSUE TITLE
Cannot use _open_to() or children() when using URLs as selector ids

### ISSUE THREAD

**Issue by slimandslam** [vakata/jstree#1340]
jstree v3.2.1

When using DOM elements that have URLs as selector ids
example DOM: 
```
<li role="treeitem" aria-selected="true" aria-level="6" aria-`labelledby="http://purl.obolibrary.org/obo/OGMS_0000015_anchor" id="http://purl.obolibrary.org/obo/OGMS_0000015" class="jstree-node ismapped jstree-leaf"><i class="jstree-icon jstree-ocl" role="presentation"></i><a class="jstree-anchor  jstree-clicked" href="#" tabindex="-1" id="http://purl.obolibrary.org/obo/OGMS_0000015_anchor"><i class="jstree-icon jstree-themeicon checkmark jstree-themeicon-custom" role="presentation"></i>clinical history</a></li>
```
The jstree code:
```
var firstSuggClassVal = 'http://purl.obolibrary.org/obo/OGMS_0000015';
 $('#jst_classr').jstree(true)._open_to(firstSuggClassVal).focus();
```
Fails with:

`TypeError: $('#jst_classr').jstree(true)._open_to(firstSuggClassVal).focus is not a function. (In '$('#jst_classr').jstree(true)._open_to(firstSuggClassVal).focus()', '$('#jst_classr').jstree(true)._open_to(firstSuggClassVal).focus' is undefined)`

This fails in the same way:
`$('#jst_classr').jstree(true).get_node(firstSuggClassVal, true).children('.jstree-anchor')[0].focus();`

**Comment by vakata** [comment]
There is no such thing as an URL selector - jstree will be very forgiving about ID format but you still need to be careful when specifying IDs - there are a many problems and invalid characters when using an URL as an ID. Sorry - you will just have to use cleaner IDs. Still I will have a look and determine exactly why this ID fails and do further escaping, but I do not consider this to be a jstree bug.

Best regards,
Ivan

**Comment by slimandslam** [comment]
Hi Ivan,

   I've tried escaping all the special characters in the URL but Jstree still complains.

J

**Comment by slimandslam** [comment]
Hi Ivan, I cannot get any form of this to work.  Do you actually have a working example of moving a selected jstree element into view using scrollintoview, scrollto, scrolltop, focus, or one of the other approaches? I think the world would like to see it.  :-)

**Comment by edc65** [comment]
Notice to the world: while not perfect, this example works in FireFox, Chrome and Explorer 11 [.](http://jsfiddle.net/k0mkhfpm/1/) Probably using scrolltop can give better results.

**Comment by slimandslam** [comment]
Do you have a jsfiddle demonstrating the functionality?

**Comment by edc65** [comment]
Yes I put the link in the post but (???) it go lost... http://jsfiddle.net/k0mkhfpm/1/

**Comment by slimandslam** [comment]
Thanks. I modified your Fiddle to use URLs as CSS ids and now I can't get it to work:

Yours (works):  http://jsfiddle.net/slimandslam/2v5ybp28/

Here's my forked version with URLs as ids and my attempt to make it work:
http://jsfiddle.net/slimandslam/p524dpuq/

Any ideas?  Ivan?

**Comment by slimandslam** [comment]
I figured out an answer:   https://groups.google.com/forum/#!topic/jstree/SjKrt25YS4s
