### ISSUE TITLE
Problem calling move_node to change position

### ISSUE THREAD

**Issue by edc65** [vakata/jstree#1344]
I have problems calling move_node to change the position of a node without changing the parent node. The result is variable: some time the position is changed correctly, other times it's off by one.
JSFiddle:https://jsfiddle.net/j6obnath/2/ (should be the right one this time)

**Comment by edc65** [comment]
I'll try to solve this issues changing the lines 3972...3982 of jstree.js to 
tmp = [];
for(k = new_par.children.length, i = j = 0; j < k;)
{
  if(j !== pos)
  {
    p = new_par.children[i].id
    if(p !== obj.id) { j = tmp.push(p); }
    ++i;
  }
  else
  {
    j = tmp.push(obj.id)
  }
} 
///// TEST NEEDED /////

**Comment by edc65** [comment]
**No** The proposed change break the dnd plugin, as the move inside parent by dragging will choose the wrong position.
After a more than week of attempts, I have no other choice than reverting to jstree release 1 for my project.

**Comment by vakata** [comment]
Just read the docs on the move_node operation and keep in mind when reordering it depends whether you are moving the node up or down.

Best regards,
Ivan

**Comment by edc65** [comment]
It's better not speak about the docs on move_node ... all the 8 lines of it. And there's nothing to be found in the docs about the way reordering is done, one have to find it by trial and error.

**Comment by vakata** [comment]
You are more than welcome to create pull requests with better
documentation. It will be appreciated :)

Best regards,
Ivan

**Comment by edc65** [comment]
Ok, I put it in my todo list. Unfortunately I need to learn how to create a pull request, before.
Following your advice, here is a jsfiddle with  the check on moving up or down. https://jsfiddle.net/j6obnath/6/ It could be useful as a reference for someone else facing the same problem
