### ISSUE TITLE
Hard-coded icon fit

### ISSUE THREAD

**Issue by willstott101** [vakata/jstree#1347]
[This line here](https://github.com/vakata/jstree/blob/04e9ee2f4859a8ec8a790a67f3769aa5fef44ec4/src/jstree.js#L2435) is not override-able in any sensible way. This is applied to all nodes with a given icon url.

    node.childNodes[1].childNodes[0].style.backgroundSize = 'auto';

Posting as an issue instead of suggesting a patch because I don't know whether a config option would be appropriate. Perhaps this line should append another css class instead? e.g. `jstree-themeicon-url`

**Comment by vakata** [comment]
This is the way it is meant to be - if you need flexibility - provide a CSS class, not a path to a file. I think it is better to leave CSS settings in CSS realm, it will be a bad design choice to make all possible CSS properties config options. 
So basically - if you need flexibility - use a CSS class string, not a file path. File paths are limited to what you have already seen.

Best regards,
Ivan

**Comment by willstott101** [comment]
OK. But I need a different icon for each tree item. And I'd like them to fit using cover or contain.

I agree about the config/css seperation (obviously, because otherwise I'd be happy with my JS hack I am having to use already, to override this). 

I was initially wary swapping this line for a css class because IDK how reluctant you would be to change the less files. As themes would need updating. Which is why I suggested the config, which would be more backward compatible.

Ta,
Will
