### ISSUE TITLE
Node_Customize plugin incompatible with Explorer 8

### ISSUE THREAD

**Issue by edc65** [vakata/jstree#1349]
Not a real issue with the library, as it's an optional plugin.
This line:

	var customizer = (type && cfg.switch[type]) || cfg.default;

Uses `switch` and `default` that are keywords, and this cause an error with Microsoft Internet Explorer 8 only. No problem for Explorer 10 or Firefox or Chrome.

I solved the issue using

    var customizer = (type && cfg["switch"][type]) || cfg["default"];

**Comment by vakata** [comment]
Sorry, but this is not even a plugin I maintain. I can not help you, but you can contact the plugin author - I am sure he will be glad you solved an issue.

Best regards,
Ivan
