### ISSUE TITLE
contextmenu items.action called on cm startup

### ISSUE THREAD

**Issue by garyee** [vakata/jstree#1350]
Hi,

My items config is:

```
items = {
                addSibblingItem: { // The "rename" menu item
                    label: "Add Sibling",
                    action: addEntity(type)
                },
                addParentItem: { // The "rename" menu item
                "separator_after": true,
                    label: "Add Parent",
                    action: addEntity(type,node)
                },
                deleteItem: { // The "delete" menu item
                    label: "Delete",
                    action: deleteEntity(id,type)
                }
            };
```

oddly the actions are called when the context menu popps up, not when the items are clicked.
When the actions are defined as:
`deleteItem: { // The "delete" menu item
                    label: "Delete",
                    action: function(id,type){
                     ....
      }
                }`

It works and the function is executed on click.

using version 3.2.1

**Comment by vakata** [comment]
This is not related to jsTree - it is basic JavaScript:
Your code is actually calling the functions. If you want to assign the object property to the function you should use: `action: deleteEntity, ...`. Please note there are no braces.

Best regards,
Ivan
