### ISSUE TITLE
dnd plugin event on multiple trees

### ISSUE THREAD

**Issue by Myrdivar** [vakata/jstree#1354]
Hi,

I have a problem setting the dnd events. Since I have to set them on 'document' if I add a second tree it shares the same dnd plugin event.

Is there a way to specify different events for different trees?

**Comment by vakata** [comment]
You are probably using the wrong events - only the dnd* events in the vakata namespace fire on the document and they are related to the DND lib which is separate from jstree. You can however inspect the data you receive in the event and determine on which instance the drag was started. As for the currently hovered instance (or DOM element) - you have that information in the form of the e.target property.

Best regards,
Ivan

**Comment by Myrdivar** [comment]
Yes, I was talking for example of the 'dnd_start.vakata' event that because it's set on document it will fire from different trees.
