### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element'

### ISSUE THREAD

**Issue by swamim** [vakata/jstree#1355]
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': '#?23423test' is not a valid selector. 

Line number 2208 - jstree.js
Please help.

**Comment by vakata** [comment]
Use valid IDs - jsTree will do its best to escape all kind of IDs, but IDs starting with a question mark will not work. Sorry.
