### ISSUE TITLE
Checkbox Plugin - Form data

### ISSUE THREAD

**Issue by shivram2609** [vakata/jstree#1359]
Is there any way to submit checked checkboxes using checkbox plugin? Also i want to rename checkboxes as per my requirements. I already used "real_checkboxes" but nothing works. With some jquery tweaks i got all the checked checkboxes but i am unable to find actual names. output is like j1_1,j1_3,j1_4,j1_5,j1_6,j1_7,j1_9,j1_10

Version : jsTree 3.0.4

Thanks for your time..

**Comment by vakata** [comment]
It depends on where you store the IDs you want to get back. If I were you I'd use the `get_checked`, `get_top_checked` or `get_bottom_checked` methods (which one depends on your setup - it depends on what you need - read the API docs for each of those). DO NOT use "jQuery tweaks" as jQuery can only read from the DOM, and some of the checked nodes may not be rendered (if their parent is closed).

Once you found the method - call it right before your form submits, and make sure the first argument is `true` - that way you will get the whole node info for each of the checked nodes. You can take it from there I guess. You could probably store the IDs you want either in the ID property of each node, or as data attributes.

Best regards,
Ivan
