### ISSUE TITLE
Plugin Dnd and Sort 

### ISSUE THREAD

**Issue by kuyaninja** [vakata/jstree#1362]
when apply this plugin, i cant do drag and drop,  but event is firing. 

http://jsfiddle.net/c526p7mm/25/

**Comment by vakata** [comment]
You can drag and drop - you just can't reorder - that is the idea of the sort plugin. 

You should disable the before and after drops in your check_callback (return `false` for those types of moves in order not to confuse the user).

Best regards,
Ivan
