### ISSUE TITLE
when node is created there is no data-jstree attribute in dom

### ISSUE THREAD

**Issue by garyee** [vakata/jstree#1364]
Hi,

I'm creating a node like this:

```
var newNode = {
        "text" : text,
        "type":type,
    };
treeElem.jstree(true).create_node(parent,newNode, "last");
```
But when the node is inserted into the dom tree it has no data-jstree attribute.
Is that normal behavior or a bug?

**Comment by vakata** [comment]
Sorry, but I am not sure I understand - why would you expect there to be a data-type attribute? Maybe the docs is misleading - the type will be stored in the JS representation of the node, not as a DOM node property.
