### ISSUE TITLE
jsTree selection wait message

### ISSUE THREAD

**Issue by honey07** [vakata/jstree#1366]
Hi,

I am using jsTree with around 18000 nodes. 
When I select root node , it takes some time to select the whole hierarchy. 
So, can I show any wait message to the user while complete tree gets checked??
How can I do this?

Thanks

**Comment by vakata** [comment]
There is no built-in functionality that displays a message. You can however attach a handler (to either the `click` event, or the `select_node.jstree` event) and display a notice, which you will remove once `changed.jstree` fires.

Best regards,
Ivan
