### ISSUE TITLE
Nothing works 2.0

### ISSUE THREAD

**Issue by CaptainMad** [vakata/jstree#1367]
Obviously you didn't like my first post so let me give you some additional information to debug your master piece. 
You told me that you have provided NASA with your code: As 2 shuttles have been crashed, should NASA sue you for this ? Anyway. Here is an example of what demo/sitebrowser returns

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236

Notice: Use of undefined constant MYSQL_BOTH - assumed 'MYSQL_BOTH' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 570

Warning: Invalid argument supplied for foreach() in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-www\jstree-master\demo\sitebrowser\class.db.php on line 236
array(2) { [0]=> string(30) "No or more than one root node." [1]=> string(32) "Root node's left index is not 1." }

**Comment by CaptainMad** [comment]
additional errors traces if this can help

Connect error: 2006

**Comment by vakata** [comment]
The PHP part is just a quick mockup - it is not supported and has never been part of jstree. jsTree (as the name suggests) is a JavaScript component. 

As for the error - the class obviously uses the deprecated `mysql` extension - hence the missing constant (you obviously do not have that installed).

Once again - jsTree is a JAVASCRIPT library - use and/or modify the PHP part on your risk - as I said - you may need the missing mysql extension.

Best regards,
Ivan

**Comment by vakata** [comment]
Just in case that is too hard for you - I just updated the constant name.

Best regards,
Ivan
