### ISSUE TITLE
contextmenu right-click should not check a node when 'select_node' is true but 'tie_selection' is false

### ISSUE THREAD

**Issue by jalipert** [vakata/jstree#1368]
Tree configuration:
checkbox plugin with "tie_selection" set to false
contextmenu plugin with "select_node" set to true

Desired behavior: right-clicking on the tree should highlight the node but not check a checkbox.  Currently if you right click over a checkbox, the checkbox is toggled when the context menu comes up.

**Comment by vakata** [comment]
Sorry - this is the way it will work - when clicking over the checkbox it will be checked. Anywhere else will be fine. There is no correct behavior for this, the reason it is checked now is that someone in the groups requested exactly the opposite - to check the checkbox when right-clicking on it. This is why the plugin now simply lets the click event propagate, which means right-clicking the checkbox will check it.

Best regards,
Ivan

**Comment by rqx110** [comment]
Is there a way to  not check the checkbox?

**Comment by jeanpaulvanbenthum** [comment]
@rqx110 According to https://stackoverflow.com/questions/35756848/jstree-context-menu-supress-changed-event-on-select-node-right-click you can add `contextmenu: { select_node: false}` to the jstree config.
