### ISSUE TITLE
keyboard enter

### ISSUE THREAD

**Issue by TZanke** [vakata/jstree#1371]
Hello,

we replaced an old tree implementation with the nice jstree.

But now our customer complained, he was editing his checkbox-tree with space bar (toggle selection) and pressing enter to send the form with the tree.

After investigation, I see the jstree 3 does not have a customization keyboard plugin anymore.

How can we modify the jstree shortcuts? Or disable them completely?

**Comment by vakata** [comment]
There is no customization as jstTree follows the ARIA spec for trees to enable keyboard navigation for visually impaired people.

You can detach the handler after jstree is ready (in a `ready.jstree` handler):
`$('#tree-container').off('keydown.jstree', '.jstree-anchor');`

After this you can define your own handlers.

Best regards,
Ivan

**Comment by TZanke** [comment]
Hello Ivan,

after disabling the event with .off() i ran into an problem with the click.jstree event.
I do not know exactly why, but the click event is still triggered if Enter is pressed.

**Comment by vakata** [comment]
Did you capture and prevent the default for this event? As the browser default is to activate the link (which might seem like a click event).

Best regards,
Ivan

**Comment by TZanke** [comment]
Hello,

ok, good point!

Just to help others with the same problem,  here my solution:

```
   $('#tree-container').on("keydown.tree", '.jstree-anchor', function (e) {
            if (e.target.tagName && e.target.tagName.toLowerCase() === "input") {
                return true;
            }
            switch (e.which) {
                case 32: // space
                    $(e.target).trigger('click');
                    break;
                case 13: // enter
                    $(e.target.closest('form')).trigger("submit");
                    break;
                default:
                    // do nothing, propagate to jstree internal events
                    return true;
            }
            e.stopImmediatePropagation();
            return false;
        });
```

To work properly, it needs to be definded **before** jstree initialization, so the custom event handler is called first.
