### ISSUE TITLE
Set node as hidden in state?

### ISSUE THREAD

**Issue by andersRetteras** [vakata/jstree#1372]
Hi 
We use your jstree component to visualize a hierarchyal structure in our app.
I have implemented styling of "inactive" nodes through a css class.

Now we would like to show/hide these nodes based on a checkbox or a icon somewhere on the page.
Then we could use show_node / hide_node methods but that does not work if the node is not rendered in the DOM yet...

Is there a way to set "state.visible: hidden" in the jsondata/model to make the jstree render them only if state.visible == true or something?

If you understand our scenario, do you have a suggestion on how to accomplish this?

Regards,
Anders

**Comment by vakata** [comment]
`state` can be passed in with the rest of the node's data, so you can use:
```
state : { hidden : true, ... }
```

Best regards,
Ivan

**Comment by andersRetteras** [comment]
I understand that I can add hidden as a variable to state object but that does not make the node hidden unless the rendering code understand this variable and makes the node hidden?

My question was maybe not too precise:
Is there a way of setting state so that the tree will not render the node (without removing the node from data)?

For example if I set node.state.hidden = true, it would be nice if the node were not rendered.
When the user wants to see these nodes I could set the same property to false and refresh the tree to make them appear again.

**Comment by vakata** [comment]
Here is a demo:
http://jsfiddle.net/DGAF4/1222/

Make sure you are using the latest JS and CSS (this fiddle uses 3.2.1)

Best regards,
Ivan
