### ISSUE TITLE
how do i get data.node.children > text ? its giving only id not text how can i do it ?  

### ISSUE THREAD

**Issue by cagatayucar** [vakata/jstree#1377]
for(var i in data.node.children){
			var selectedNodeChildren = data.node.children[i];
			alert(selectedNodeChildren);
                        // var id = data.node.children[i].id;    ???

**Comment by vakata** [comment]
`data.instance.get_node(data.node.children[i]).text)`

Best regards,
Ivan

**Comment by cagatayucar** [comment]
Ty for help Ivan .

2016-03-13 19:17 GMT+02:00 Ivan Bozhanov <notifications@github.com>:
