### ISSUE TITLE
Node children info

### ISSUE THREAD

**Issue by frontenddeveloping** [vakata/jstree#1378]
I init jstree with root info only and I know which root has a children. When I select root node I want to know usign node object has root node children or not:
```
function jsTreeObjectFabric(nodeObject) {
    return {
        children: nodeObject.hasChildren,
        text: nodeObject.name,
        id: nodeObject.id,
        parent: nodeObject.parent ? nodeObject.parent : '#'
    };
}
$('#jstree').jstree({
    'core' : {
        'data': data.map(jsTreeObjectFabric)// data is some data from server
    }
}).on('selecte_node.jstree', function(e, data) {
    console.log(arguments);// no info about has children or not,
});
```

**Comment by vakata** [comment]
Use `data.node` in the `select_node.jstree` event handler. 

You can even use methods like `data.instance.isParent(data.node)`, etc - just read the API docs on the event properties you get.

Best regards,
Ivan

**Comment by frontenddeveloping** [comment]
Thank you, @vakata
