### ISSUE TITLE
rename_node.jstree event, mistakes in the docs

### ISSUE THREAD

**Issue by GarryOne** [vakata/jstree#1379]
https://www.jstree.com/api/#/?q=.jstree%20Event&f=rename_node.jstree
The "rename_node.jstree" is shown to have 3 parameters: node, text, old. 
Actually, the parameters are: node, action.

The "rename_node.jstree" is shown to have 3 parameters: node, parent, position.
Actually, the parameters are: node, action.

**Comment by vakata** [comment]
You may have mistaken the event and the method. Here is the even - it has exactly those 3 properties when triggered.
https://github.com/vakata/jstree/blob/master/src/jstree.js#L3761

**Comment by GarryOne** [comment]
It was probabbly, because I was not using the latest version.
Sorry.

2016-03-13 19:16 GMT+02:00 Ivan Bozhanov <notifications@github.com>:

> You may have mistaken the event and the method. Here is the even - it has
> exactly those 3 properties when triggered.
> https://github.com/vakata/jstree/blob/master/src/jstree.js#L3761
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vakata/jstree/issues/1379#issuecomment-196004313>.
>



-- 
Cu stima, Mardari Igor!
ID Messenger/Skype: igor.mardari
Telefon: 0773810487
