### ISSUE TITLE
jstree is not populated in IE 11.0.29 

### ISSUE THREAD

**Issue by Laxman2015** [vakata/jstree#1381]
Hi,

I have used jstree 3.2.1 plugins but facing some browser specific issues as tree is not populated on "IE 11.0.29" but its working fine on "IE 11.0.27"

FYI.. i have used json data to populate tree.

FYI...:
http://stackoverflow.com/q/35942493/1166364?sem=2 

Need your help.

Thanks,
Laxman

**Comment by vakata** [comment]
Can you open http://www.jstree.com in the same browser and report if the demos work. If they do - it is not a browser or jstree issue, but something related to your data. If it does not - could you please provide a jsFiddle demo and I will reopen the issue. 

Best regards,
Ivan

**Comment by Laxman2015** [comment]
Ivan,

Its working fine with IE 11.0.27 and other version, except IE 11.0.29.

We checked  jstree demo directly "https://www.jstree.com/demo/" its also not populated tree on IE 11.0.29 version, 

could you please check the same.

Thanks,
Laxman

**Comment by vakata** [comment]
I just did - 11.0.29 is a version from 3 years ago (2013) - maybe there was a bug with the browser itself. I doubt I will be able to do anything about this, but still - do you get any errors in the console?

**Comment by Laxman2015** [comment]
We don't get any error on the console.

**Comment by Laxman2015** [comment]
Please suggest if you are able to reproduce the same.

**Comment by Laxman2015** [comment]
Its working fine on IE 11.0.29 also. Thanks
