### ISSUE TITLE
Allow to specify style for node type

### ISSUE THREAD

**Issue by jochenberger** [vakata/jstree#1382]
When using the types plugin, it is possible to assign a custom CSS class for nodes with a certain type via the `icon` property.
I'd like to be able to specify the style inline, like in:
```json
"types" : {
  "root": {
    "valid_children": ["child"],
    "icon": "glyphicon glyphicon-folder-open",
    "style": {"backgroundColor": "green"}
  }
}
```

**Comment by vakata** [comment]
Yes, you can - it is mentioned in the docs too.

Best regards,
Ivan

**Comment by jochenberger** [comment]
https://www.jstree.com/api/#/?f=$.jstree.defaults.types does not contain any information in that regard.

**Comment by jochenberger** [comment]
Are you sure this is supported? Could you please re-read my question?

**Comment by vakata** [comment]
Oh, sorry, my bad - I missed the `style` property and responded with regard to the `icon` one. No, this is not supported and never will be - I do not believe the proper way to assign css properties is through config options in jstree. 
I am however working on a feature that will allow the type property to specify the defaults for any new node that is of that type (any key in the node JSON definition), so basically it will be possible to set `li_attr : { style : "..."`, or `a_attr : { style : "..."`. 

Best regards,
Ivan

**Comment by vakata** [comment]
And here is a demo (note I am using github as a CDN, which is a bad practice):
http://jsfiddle.net/DGAF4/1231/

Best regards,
Ivan

**Comment by jochenberger** [comment]
Thanks, I'll wait patiently.
> do not believe the proper way to assign css properties is through config options in jstree.
Well, you can assign the icon/class through a config option. IMHO that is similar to CSS properties as it also affects how the node is displayed. But I can see what you mean.

**Comment by jochenberger** [comment]
To be able to achieve what I want, I'd actually have to be able to specify `i_attr`, because I only want to color the icon. I suppose you don't want to add support for that too? ;-)

**Comment by vakata** [comment]
Simply use the `icon` property - it actually takes a list of classes - specify a class for that. And no - I will not add the ability to style the icon using a style attribute - it is a simple string - either a path or a class list. Any modifications you want to the icon - use a class list, for example: `"fa fa-eye my-red-class"`

Best regards,
Ivan

**Comment by jochenberger** [comment]
That's my current solution and what I actually wanted to avoid.
The `glyphicon` and `glyphicon-folder-open` classes come from `bootstrap.css`. They define the icons but not the color. See http://jsfiddle.net/DGAF4/1232/. To color the icon, I have to add a class and include an extra CSS file. But I guess I can live with it. ;-)
