### ISSUE TITLE
Change plugin configurations at runtime

### ISSUE THREAD

**Issue by drbarto** [vakata/jstree#1383]
Is it possible to change the configuration of a plugin after the jstree has been created?

More specifically, I'd like to toggle the `three_state` property of the `checkbox` plugin configuration of an existing jstree to support cascading as well as non-cascading selection, based on the user's preference.

**Comment by vakata** [comment]
Most setting will work when changed at runtime, but that is not officially supported. But the `three_state` setting will not work I am afraid, and I do not plan on adding support for that - sorry.
