### ISSUE TITLE
missed ")" in API 

### ISSUE THREAD

**Issue by evser** [vakata/jstree#1384]
$('#tree').jstree({
    'core' : {
        'data' : [
            'Simple root node',
            {
                'id' : 'node_2',
                'text' : 'Root node with options',
                'state' : { 'opened' : true, 'selected' : true },
                'children' : [ { 'text' : 'Child 1' }, 'Child 2']
            }
        ]
    });

**Comment by davidreghay** [comment]
You're missing a '}' before the closing parentheses.  The one you have there matches the 'core' object, not the options hash itself.  In other words, you have:

```javascript
$('#tree').jstree({
	'core' : {
		'data' : [
			'Simple root node', {
				'id' : 'node_2',
				'text' : 'Root node with options',
				'state' : {
					'opened' : true,
					'selected' : true
				},
				'children' : [{
						'text' : 'Child 1'
					}, 'Child 2']
			}
		]
	});
```

When you should have:

```javascript
$('#tree').jstree({
	'core' : {
		'data' : [
			'Simple root node', {
				'id' : 'node_2',
				'text' : 'Root node with options',
				'state' : {
					'opened' : true,
					'selected' : true
				},
				'children' : [{
						'text' : 'Child 1'
					}, 'Child 2']
			}
		]
	}
});
```

**Comment by evser** [comment]
I know, I fixed it. I send it to you to adjust docs :)
