### ISSUE TITLE
How to show selected nodes when search is cleared?

### ISSUE THREAD

**Issue by srkunze** [vakata/jstree#1389]
When combining search plugin and checkbox plugin, we would like to leave (the) selected node(s) open.

That is when a user searches, discovered the node he searched for, selects the node and then clears the search, the node stays selected but is hidden deep within the tree.

How can this be achieved?

**Comment by vakata** [comment]
The only option I can think of is this one:
https://www.jstree.com/api/#/?q=close_opene&f=$.jstree.defaults.search.close_opened_onclear

If that does not work - there is no config option that can help, but you can achieve what you need manually - on search - set a search flag (variable) as `true`, listen for `select_node` events and collect all selected nodes in an array, on clear search if there is something in the array - use the `_open_to` function to reveal those nodes and clear the array. It should be no more than 20 lines of code.

Best regards,
Ivan

**Comment by srkunze** [comment]
> The only option I can think of is this one:
https://www.jstree.com/api/#/?q=close_opene&f=$.jstree.defaults.search.close_opened_onclear

Yes, I was thinking about this as well however, the tree is too big to stay open.

> If that does not work - there is no config option that can help, but you can achieve what you need manually - on search - set a search flag (variable) as true, listen for select_node events and collect all selected nodes in an array, on clear search if there is something in the array - use the _open_to function to reveal those nodes and clear the array. It should be no more than 20 lines of code.

Will look into this as it sounds reasonable.

Could this make a valuable addition to jstree aka. would you like to see a pull request/js snippet?

Best,
Sven
