### ISSUE TITLE
refresh_node does not work with flat/alternative JSON format

### ISSUE THREAD

**Issue by kurtgronbech** [vakata/jstree#1390]
refresh_node doesn't seem to work with the flat/alternative JSON format. Is it a bug or am I doing something wrong? 

To reproduce: 

$('#frmt').jstree({
	'core' : {
			'data' : [
 { "data": "div1", "text": "div1", "id": "div1", "type": "default", "state": {"opened":false}, "parent": "#"},
 { "data": "div2", "text": "div2", "id": "div2", "type": "default", "state": {"opened":false}, "parent": "div1"}

 ]
		}
	});

Then update the data with another node and call refresh_node: 

 $("#btnTest").click(function() {
 		var tree= $('#frmt');
			tree.jstree(true).settings.core.data =  [
 { "data": "div1", "text": "div1", "id": "div1", "type": "default", "state": {"opened":false}, "parent": "#"},
 { "data": "div2", "text": "div2", "id": "div2", "type": "default", "state": {"opened":false}, "parent": "div1"},
 { "data": "div3", "text": "div3", "id": "div3", "type": "default", "state": {"opened":false}, "parent": "div2"}

 ];

 var node = tree.jstree(true).get_node("div2");
 tree.jstree(true).refresh_node(node); // Doesn't work. div3 is not shown
 //tree.jstree(true).refresh(); // this works 

});

**Comment by vakata** [comment]
jsTree creates a copy of the data - it will not pick up on changes you make to the settings object. So if you want to modify it - set `core.data` to a function and return the new data as needed.

Best regards,
Ivan

**Comment by kurtgronbech** [comment]
Thanks, I will try that.
