### ISSUE TITLE
DND Drop Check not Working

### ISSUE THREAD

**Issue by samatha123** [vakata/jstree#1391]
Hi ,

I am currently using Jstree 1.0, with plugins themes,json_data,checkbox,ui,dnd,crrm and sort.

I am trying to restrict the dropping of a node to to specific nodes(Any node on level n). I am trying to achieve the same using the drop_check functionality with the DND plugin. When a node is dropped I dont see any activity in the DND plugin apart from Drop_Finished. Could you please suggest a work around for the same.

Thanks
Samatha

**Comment by vakata** [comment]
Sorry, v.1 is no longer supported - it has not been for years. Maybe someone on stackoverflow or the groups page will be able to help.

Best regards,
Ivan
