### ISSUE TITLE
lazy loading while initial tree population not through ajax

### ISSUE THREAD

**Issue by erez-o** [vakata/jstree#1392]
In your examples, you describe an option to [populate the tree using ajax and lazy loading nodes](https://github.com/vakata/jstree#populating-the-tree-using-ajax-and-lazy-loading-nodes).

Is there an option to initially [populate the tree from the html](https://github.com/vakata/jstree#populating-a-tree-using-html), and only using ajax to lazy loading the nodes?

Can you please give a short example?

Thx

**Comment by vakata** [comment]
You should set `core.data` to a function. Then if the processed node is the root node - return the HTML, otherwise - make an AJAX call. Here is a demo:
http://jsfiddle.net/2kwkh2uL/3795/

Best regards,
Ivan
