### ISSUE TITLE
Events should be triggered via trigger() vs. triggerHandler()

### ISSUE THREAD

**Issue by sirianni** [vakata/jstree#1393]
`triggerHandler()` does not bubble up the DOM tree, whereas `trigger()` does.

JSTree's use of `triggerHandler()` precludes using jquery delegate events to handle jstree events.  Many JS frameworks (e.g. Backbone) support declaratively specifying events on a root view element and relying on event bubbling to catch events on child components.

**Comment by vakata** [comment]
This was done on purpose, as bubbling events were way too expensive when jstree v.3 was being created. I will consider bubbling events for version 4, although it may have a different approach to events. I will not be changing this in v.3, but I will add it in v.4 if applicable, so I am closing this for now.

Best regards,
Ivan
