### ISSUE TITLE
Using custom field for node's "text" or How to set node's text from another field?

### ISSUE THREAD

**Issue by oneumyvakin** [vakata/jstree#1396]
Hi,

I've faced with issue that i've to always keep "text" field for entities which need to be showed in JStree,  like
```
type Person struct {
        Name string
        Text string `json:"text"` // Need only for JStree, duplicates "Name", always need storing and extra processing
}
```
or
```
type Person struct {
	Name string `json:"text"`         // Maybe not acceptable in some cases
}
```

It there way to define in JStree to use different field for "text"("name" in this case) ?

And thanks for great plugin!

**Comment by vakata** [comment]
Hi,

There is no built-in way to map jstree's structure to your structure using a config, but you can set `core.data` to a function and transform any data you want to jstree's required structure. There are docs on setting core.data to a function both here on the repo homepage and on jstree.com

Best regards,
Ivan

**Comment by mikila85** [comment]
could be really useful. instead of doing 
```
'data' : function (node, cb) {
            self.treeFetchFunction().then(function (data) {
                cb(***Here try to manufacture a new object from the old one***)
            });
        }
```

it comes down to using parameters instead of hardcoded values.
