### ISSUE TITLE
del hotkey does not work

### ISSUE THREAD

**Issue by ahmadbadpey** [vakata/jstree#1397]
According to [hotkeys documentations](http://johntang.github.io/JsTree/_docs/hotkeys.html) , I want that use can delete a selected node via pressing **del** keyboard. 

documentation says that by default keys like up, down , right , left enter and etc is enabled , but seems **del** button is not and I want to enable it too. **del** button does not work for me but other hotkeys works fine.

**Comment by vakata** [comment]
The docs you are referring to are not official (it is a fork of jstree made by another user) and are a for jstree v.1, which has not been supported for years. `vakata/jstree` is he official repo - read docs from this repo's homepage and on https://www.jstree.com
If you are still using v.1 I cannot help you, if you are using v.3 use this snippet:
```js
$('#tree').on('keydown.jstree', '.jstree-anchor', function (e) {
    if(e.target.tagName && e.target.tagName.toLowerCase() === "input") { return true; }
    if (e.which === 46) {
        e.preventDefault();
        $.jstree.reference(this).delete_node(this);
    }
});
```

**Comment by ahmadbadpey** [comment]
Thanks @vakata , you are awesome
