### ISSUE TITLE
add create and edit icons in front of each node on hover 

### ISSUE THREAD

**Issue by ahmadbadpey** [vakata/jstree#1399]
I want to add a capability to my jstree instance So that in front of each node display icons with custom actions like create multi node , delete , edit and etc on node mouse hovering like this picture : 
![image](http://i.imgur.com/t2vmbhx.png?1)

I there any way to add this capability?

**Comment by vakata** [comment]
There is no built-in way to do this, but you can achieve that using a plugin - it has been discussed on stackoverflow and the discussion forum. You can also get away with using pure JS and CSS as well.

Best regards,
Ivan

**Comment by ahmadbadpey** [comment]
I searched before too much, but could not found any solution. can you suggest a stackoverflow or other topics address?

**Comment by rocchidavide** [comment]
@ahmadbadpey should be this: https://github.com/deitch/jstree-grid

**Comment by jabernalv** [comment]
You can put html code in json text field
