### ISSUE TITLE
set_id does not work in node creation

### ISSUE THREAD

**Issue by ahmadbadpey** [vakata/jstree#1401]
I want to assign specific id to newly created node. I write this :
```
$treeview.on('create_node.jstree', function (e,node) {
        $treeview.jstree(true).set_id(node.id,15);
    });
```
But this does not work and default id assigned to newly created nodes .
what is problem and right way ?

**Comment by vakata** [comment]
Set your ID in a `create_node.jstree` event handler. Besides, it does work, here is a demo: http://jsfiddle.net/DGAF4/1248/
Maybe your angular directive does not work or is using old code?

**Comment by ahmadbadpey** [comment]
I found the problem.
I most use `node` property of second parameter passed to `create_node.jstree` that has `node` name.
in fact this is right way : 
```
$treeview.on('create_node.jstree', function (e,node) {
        $treeview.jstree(true).set_id(**node.node**,15);
    });
```
