### ISSUE TITLE
Cannot open nodes programatically with lazy loading 

### ISSUE THREAD

**Issue by lahirue** [vakata/jstree#1402]
is there any way to open nodes programatically with lazy loading ? since its open nodes lazy loading , it will not render while our loop going in. So how to wait until node open and render, then open next node after lazy loading ?

**Comment by vakata** [comment]
You can use the `load_node` function and pass in an array of nodes to load, and then call `_open_to` to reveal the deep node you need.

Best regards,
Ivan
