### ISSUE TITLE
Object doesn't support property or method 'jstree'

### ISSUE THREAD

**Issue by robinmaple** [vakata/jstree#1403]
Here is full code, and yes the path to jQuery and jstree is correct. Thanks!

<script src="/Scripts/jquery-2.1.1.js"></script>
<script src="/Scripts/jstree.js"></script>
<link rel="stylesheet" href="/Content/MWorks/style.css" />

<div id="jstreecontainer">
    <ul>
        <li>
            Root node
            <ul>
                <li>Child node 1</li>
                <li>Child node 2</li>
            </ul>
        </li>
    </ul>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#jstreecontainer").jstree();
    });
</script>
![image](https://cloud.githubusercontent.com/assets/7815640/14113457/45b0f57e-f590-11e5-88ee-520184eeac4d.png)

**Comment by vakata** [comment]
There is something wrong with your code, but I cannot tell you what without a demo. This is not a problem with jstree itself. It simply is not loaded. If you provide a demo or some code I can help you debug, but this definitely is not a jstree problem.

Best regards,
Ivan

**Comment by robinmaple** [comment]
Thanks a lot vakata. I'm new to this and I really respect your work!

I'm trying this in ASP.NET Razor page, and I've tried both CDN and local copies, get same error. I'm using IE11, disabled compatibility view by the way. Really appreciate if you could shed some light. 

Thanks!

[txt.txt](https://github.com/vakata/jstree/files/193842/txt.txt)

**Comment by robinmaple** [comment]
I copied everything into plain html and it works. Must be my ASP.NET page issue. I'll look into it, thanks for your response. And again great respect to your elegant work!
