### ISSUE TITLE
Not able to get undetermined state

### ISSUE THREAD

**Issue by nayeem4umd** [vakata/jstree#1404]
hi 
am not able to get undetermined state while traversing tree, is it supported or not UNDERTERMINED state

**Comment by vakata** [comment]
That state is not kept on the model, it is visual only. Basically any non-checked node with checked descendants is in that state. There is a is_undetermined helper function, if you need that.

**Comment by nayeem4umd** [comment]
That worked for me - thanks a lot lot lot buddy
