### ISSUE TITLE
toggle entire tree by a simple button

### ISSUE THREAD

**Issue by ahmadbadpey** [vakata/jstree#1409]
I know that is ways to open and close entire tree with two different element like this : 
```
$('#collapse-all').click(function () {
        $treeview.jstree('close_all');
    });
    $('#expand-all').click(function () {
        $treeview.jstree('open_all');
    });
```
But how can I open and close entire tree with a button so that with click on the button if tree is open be closed and if it closed , open it ?

**Comment by vakata** [comment]
That is outside the scope of jstree, all I can help you with is a selector - if you have at least one `.jstree-open` node in jstree - call `close_all`, otherwise - `open_all`.

Best regards,
Ivan
