### ISSUE TITLE
delete all checked nodes 

### ISSUE THREAD

**Issue by ahmadbadpey** [vakata/jstree#1410]
In my jstree instances all nodes have a checkbox. 
I want to remove all node that have checked checkbox via a button.

I wrote this to delete nodes : 

```
$treeview.on('delete_node.jstree', function (e, data) {
        $.delete('/admin/orgLevel/'+ data.node.id,{},function(res){
            console.log(res);
        },'json');
    });
```

but this event fired for each separated node and send different ajax request to server while I want after node checkbox selection then click on button , I get ID of all selected nodes and send to server as an array via just one request . 

How can I do that ?

**Comment by vakata** [comment]
Please use the discussion group for how-to questions. Now onto the question - use `get_checked` (or `get_top_checked` for that matter) and pass the array you get to `delete_node`. As for grouping the queries to the server - you have to implement that in your own code logic. Use a small timeout in your `delete_node.jstree` handler and collect all nodes in an array - each time the event fires - clear the timeout, that way after the last node is collected the timeout will expire and you will hit the server with all the nodes in your array (known as throttling).

Best regards,
Ivan
