### ISSUE TITLE
 Calling a function

### ISSUE THREAD

**Issue by m4mune** [vakata/jstree#1411]
How to alter values in other functions while renaming the node?
@vakata 
I want to change the value of x to y from below sample:

 value of htmlsrc is set as x as in below:
` var x = $('#jstree').html();
                    $scope.htmlsrc = x;`

this doesnt change the value of x to y:
` $('#jstree').on("rename_node.jstree", function (e, data)
 {
                var y = $("#jstree").html();
              $scope.htmlsrc=y;
 }
);`

I want the value of htmlsrc as in y

**Comment by vakata** [comment]
Hi,

I am afraid I can not help you. Direct any angular directive questions to the directive author. I am not experienced with Angular and jstree does not include an angular directive.

Best regards,
Ivan
