### ISSUE TITLE
How to define types in Node and Disable drag and drop for certain types

### ISSUE THREAD

**Issue by Atul844** [vakata/jstree#1413]
I Want to have following kind of tree structure for one of my module:

- **Order1**
 -  Formulation1
        - Task-1
        - Task-2
        - Task-3
            - Task-3-1                
            - Task-3-2
                 - Task-3-2-1
                    -  Task-3-2-1-1

     - Task4
   - Formulation2
   - Formulation3
             -  Task-1
             - Task-2
                   
                   - Task-2-1

**Order2**
-   Formulation1
-         Task-1
-         Task-2
-         Task-3
-             Task-3-1                
-             Task-3-2

My problem is i want to have three types of Nodes:
**Order**- will be always a root node - ### _Should not allowed to drag and drop_
**Formulation** - it always be a immediate child of a Branch - ### _Should not allowed to drag and drop_
**Task**- Always a child of Formulation or Task not a Order type  - ### _Should  allowed to drag and drop under same Order not to outside of Order_

I also have another question:
how shall i create new node with type, currently i tried to use Context menu option but it does not tell the type.
So when i'm creating a node:
It should based on from which level i'm creating it:
If i'm creating it from Order level- it should be Formulation
If i'm creating it from Formulation level - it should be task
if i'm creating it from task level - it should be task

Kindly suggest me any way to achieve this. 
Your help will be appreciated, Thanks in Advance.

**Comment by Atul844** [comment]
My Code for reference:

**HTML**
    <div id='treeview'></div>
    <script type="text/javascript">
    // Begin JSTree: courtesy Ivan Bozhanov: http://www.jstree.com:
        $('#treeview').jstree({
           
            //"plugins": ["search", "wholerow"],
            'core': {
                'data': {
                    'url': function (node) {
                        return node.id === '#' ? "/en-us/TreeView/GetRoot" : "/en-us/TreeView/GetChildren/" + node.id;
                    },
                    'data': function (node) {
                        return { 'id': node.id };
                    }
                },
                "check_callback":  true, // allow everything else
        } ,

            "plugins": ["dnd", "contextmenu"]
           
        });

        $('#treeview').on('changed.jstree', function (e, data) {
            console.log("=> selected node: " + data.node.id);
        });
</script>



### Model
public class TreeModel
    {
            public string id { get; set; }
            public string parent { get; set; }
            public string text { get; set; }
            public bool children { get; set; } // if node has sub-nodes set true or not set false
      } 


**Controller:**
This code is only for creating branch and item but i dont have way to create a type of node.

public JsonResult GetRoot()
        {
            List<TreeModel> items = GetTree();

            return new JsonResult { Data = items, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetChildren(string id)
        {
            List<TreeModel> items = GetTree(id);


            return new JsonResult { Data = items, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public List<TreeModel> GetTree()
        {
            var Orders = db.tblOrders;
            var items = new List<TreeModel>();
            foreach (var d in Orders)
            {
                // create a new node
                TreeModel t = new TreeModel();
                t.id = d.OrderID.ToString();
                t.parent = "#";
                t.text = d.OrderName;
                t.children = true; 
                items.Add(t); // add the node to the "master" node
            }
            return items;
        }

        static List<TreeModel> GetTree(string id)
        {
            Orders objOrder = new Orders();
            var Orders = objOrder.Get_TreeFormulation(Convert.ToInt32(id));
            var items = new List<TreeModel>();
            foreach (var d in Orders)
            {
                // create a new node
                TreeModel t = new TreeModel();
                t.id = d.FormulationID.ToString();
                t.parent = id;
                t.text = d.FormulationNumber;
                t.children = true;
                items.Add(t); // add the node to the "master" node
            }
            // set items in here
            return items;

        }

**Comment by vakata** [comment]
Hi,

1) Take a look at the `dnd.is_draggable` calback to prevent drags where not desired.

2) As for the contextmenu - either call `set_type` in a `create_node.jstree` event handler (easier), or override the `contextmenu.items` create function.

Best regards,
Ivan
