### ISSUE TITLE
show_only_matches change in behavior

### ISSUE THREAD

**Issue by remygrandin** [vakata/jstree#1414]
Hi,

I recently updated my jstree version and I noticed a change of behaviour of the show_only_matches option of the search plugin.

on 3.0.0 beta, it was working as(i think) intended, 
Fiddle [http://jsfiddle.net/53cvtbv9/1/](http://jsfiddle.net/53cvtbv9/1/)
If you search for "sea", only the seafood note are shown, all other one (except the seafood parents) are hidden.

on the lastest (3.3.0), The behavior is not the same
Fiddle [http://jsfiddle.net/kvq8g6f2/](http://jsfiddle.net/kvq8g6f2/)
If you search for "sea", all the root nodes are still present and all the found nodes sibling are show too.

Is it a bug or a vonluntary change in behavior ? If the later, could we have an option to get the old one ?

**Comment by vakata** [comment]
You probably forgot to update your CSS files. But just to be clear - show_only_matches will show all matching nodes AND their parents.

Best regards,
Ivan

**Comment by remygrandin** [comment]
Indeed it was that, the proton theme I was using, hasn't been updated with the new ".jstree-hidden" class. adding in with a simple display:none did the trick !

**Comment by pieterlukasse** [comment]
I would like to show only matches AND their parents AND their children...how to achieve that?

**Comment by pieterlukasse** [comment]
ah, found it https://github.com/vakata/jstree/issues/668 . Thanks
