### ISSUE TITLE
'show_only_matches_children' revealing Hidden nodes

### ISSUE THREAD

**Issue by fbonet1** [vakata/jstree#1415]
Hello Vakata: firstly thanks for a great plugin.

I've updated to v3.3.0 recently and started using the newly supported hidden nodes. I think I've found a bug.
When you initialize a tree with a hidden node and the search plugin with the 'show_only_matches_children' option enabled there's a weird behaviour.

If you search for the parent of the hidden node, then all of its children are revealed, even hidden ones. That could be ok. But, after clearing the search input,** the now revealed hidden nodes stay revealed and don't hide again.**

I've created a small example:
https://jsfiddle.net/fbonet/53fsjgv9/10/

Run that script, search for 'publish' and see that the 4th child node stays shown even after clearing your search input.
Could this possibly be a bug?
Thanks.

**Comment by vakata** [comment]
Here is the same fiddle with the new version from the repo:
https://jsfiddle.net/53fsjgv9/11/

Best regards,
Ivan
