### ISSUE TITLE
Tree loading after node creation

### ISSUE THREAD

**Issue by roneyrogerio** [vakata/jstree#1417]
I met jstree yesterday, and I'm finding it incredible.
But, every time when i create new node in demo example on /jstree-master/demo/sitebrowser/ and simultaneously click on any area outside. the tree reload. 
Animated gif to see what i say http://i.imgur.com/uZKi71E.gif
This is expected operation?

**Comment by vakata** [comment]
No - that demo is buggy and needs to be fixed, I just haven't got round to it yet. You will not get that behavior when using jstree yourself.

Best regards,
Ivan

**Comment by roneyrogerio** [comment]
I understand. But my case is this, I'm not programmer, and the example we have in the demo is exactly what I need, even I have implemented the example in my system, the only issue I found strange was that I put up.
Any chance to help me or refer to the solution?

**Comment by vakata** [comment]
The problem is with the underlying database which is corrupted and needs to be optimized.
So you can simply grab the files from the repo and use them - you should be fine, just keep in mind that **the PHP classes that are part of the demo are not part of jstree and are not supported** - you are free to use them at your own risk. 

Best regards,
Ivan

**Comment by roneyrogerio** [comment]
OK, I began to investigate the problem, and found that
when he calls
?operation=create_node&id=1&position=3&text=New+node
return json with id of newly created node, example:
**id: 1094**
but, jstree opem rename and when i click on any outside area, the name are salved with this call
?operation=rename_node&id=**j1_9**&text=New+node
but looking at the id it is not an integer, and returns an error code 500:
**Could not rename non-existing node**
Correct me if I'm wrong, but the error occurs when the code returns the id "j1_9" instead of id "1094"
This is the problem?

**Comment by vakata** [comment]
Yes, as I said - the database is corrupted, but that should not be an issue for you - feel free to use the scrips on your machine. The problem is with the actual database on jstree.com, not related to the code.

Best regards,
Ivan

**Comment by roneyrogerio** [comment]
This is the problem, lack the .id
`				.on('create_node.jstree', function (e, data) {
					$.get('?operation=create_node', { 'id' : data.node.parent, 'position' : data.position, 'text' : data.node.text })
						.done(function (d) {
							data.instance.set_id(data.node**.id**, d.id);
							alert(d.id);
						})
						.fail(function () {
							data.instance.refresh();
						});
				})`
I still do not understand the part of the corrupted database

**Comment by roneyrogerio** [comment]
I'm using the code on my own server. so it's not an isolated problem.
I've looked in my mysql database and the values of id that are returned by javascript are not at any time in the database.
What I realized is that the id in data.node.id object is corrupted quickly after the script tries to create the node also try to rename it. If waited a while until the script to get the request to add the node, the problem does not occur.

**Comment by roneyrogerio** [comment]
I appreciate the Jstree but unfortunately, after much effort, I could not use the available php example with jstree without the problem I reported.
For me, a semi layperson in programming, php example was what I needed.
But congratulations jstree was the best I've seen so far.

**Comment by vakata** [comment]
Sorry for the disappointment - unfortunately as I said - that example is not part of jstree. jsTree is the client side lib only. I plan on releasing official examples for many languages with v.4, but I believe that will happen at the end of this year.

Best regards,
Ivan
