### ISSUE TITLE
Create node not working..

### ISSUE THREAD

**Issue by praveenindaliya** [vakata/jstree#1418]
hi,
When i'am using types with "valid_children" the create node stopped working, Actually i used types to set a level for drag-drop but create node functionality stopped working if use that.. pls can help me on this.. here is my code -

$(function () {
        $('#container').jstree({
            "core": {
                "themes": {
                    "variant": "large",
                    "dots": false,
                },
                "check_callback": true,
            },
            "types": {
                "#": {
                    "valid_children": ["asset"]
                },
                "asset": {
                    "valid_children": ["section"],
                },
                "section": {
                    "valid_children": ["machine"],
                },
                "machine": {
                    "valid_children": ["componenet"],
                },
                "componenet": {
                    "valid_children": [],
                }
            },
            "plugins": ["contextmenu", "dnd", "search", "types", "wholerow"],
        })
          .bind("create_node.jstree", function (e, data) {
              console.log(data);
          })
          .bind("move_node.jstree", function (e, data) {
              if (data.parent != data.old_parent) {
                  $.ajax({
                      type: "POST",
                      url: '/Home/DragDrop',
                      traditional: true,
                      data: { type: data.node.type, id: data.node.id, parents: data.node.parents },
                      success: function (result) {
                          console.log(result);
                      }
                  });
              }
          })
         .bind("select_node.jstree", function (e, data) {
             //console.log(data);
         });
        var to = false;
        $('#nodesecrch').keyup(function () {
            if (to) { clearTimeout(to); }
            to = setTimeout(function () {
                var value = $('#nodesecrch').val();
                $('#container').jstree(true).search(value);
            }, 250);
        });
    })

**Comment by vakata** [comment]
When calling `create_node` make sure you pass in the right type. The `valid_children` property affects all operations. You are probably creating a node with the default type, which is not allowed anywhere in your structure. 
You can also check `$('#container').jstree(true).last_error()` to see what actually happened after trying to create. Let me know if you need more help.

Best regards,
Ivan

**Comment by praveenindaliya** [comment]
thanks for reply,
now i got this error when creating node -
Object {error: "check", plugin: "types", id: "types_02", reason: "valid_children prevents function: create_node", data: "{"chk":"create_node","pos":15,"obj":true,"par":"asset_1"}"}
from this code -
"contextmenu": {
                "items": {
                    "Create": {
                        "label": "Create",
                        "action": function (data) {
                            var ref = $.jstree.reference(data.reference);
                            sel = ref.get_selected();
                            if (!sel.length) { return false; }
                            sel = sel[0];
                            sel = ref.create_node(sel, { "type": "file" });
                            if (sel) {
                                ref.edit(sel);
                            }
                            console.log($('#container').jstree(true).last_error());

                        }
                    },
                }
            },

which means "valid_children" prevents this to not allow me to create node, But i need to use "valid_children" to restrict drag-drop the levels.. So what i need to create new node with "valid_children".

**Comment by LucasE2996** [comment]
I tried to create node with drop action. I have two jstree object in the same page, and when I try to move one element from one tree to the other one the _create_node_ event do not fire. Only when I create node through context menu plugin it triggers successfully. Can anyone help with that?

**Comment by vakata** [comment]
The event you need is most likely ```copy_node.jstree``` not ```create_node.jstree```
