### ISSUE TITLE
Search fail when some node has just number in text field

### ISSUE THREAD

**Issue by natocTo** [vakata/jstree#1419]
One of my node contain data like:

php generated:
```
$response[] = [
    'id'        => 'ch3-2016',
    'parent'    => 'ch3',
    'text'      => '2016'
];
```

With this data search do not work. I must edit id as:

```
$response[] = [
    'id'        => 'ch3-2016',
    'parent'    => 'ch3',
    'text'      => '2016&nbsp;'
];
```

Wonder if it is working as expected or some bug.

**Comment by vakata** [comment]
I cannot reproduce this issue. Here is a demo using `2016` as node text and then searching for `2016`:
http://jsfiddle.net/DGAF4/1285/

Best regards,
Ivan
