### ISSUE TITLE
Make selector element available to plugin

### ISSUE THREAD

**Issue by SuricateCan** [vakata/jstree#1420]
Hi,

I am writing a plugin and found myself in need of the selector element that is being used by jstree for the init process.

I then did some minor changes to the code to accomplish that.

On ```$.jstree.create``` made the element available to the ```plugin``` function:

```javascript

	$.jstree.create = function (el, options) {
		var tmp = new $.jstree.core(++instance_counter),
			opt = options;
		options = $.extend(true, {}, $.jstree.defaults, options);
		if(opt && opt.plugins) {
			options.plugins = opt.plugins;
		}
		$.each(options.plugins, function (i, k) {
			if(i !== 'core') {
                                //made el available to plugin function
				tmp = tmp.plugin(k, options[k], el);
			}
		});
		$(el).data('jstree', tmp);
		tmp.init(el, options);
		return tmp;
	};
```

On ```$.jstree.core.prototype.plugin```, made the element available to the plugin constructor

```javascript
                //added the element as parameter
		plugin : function (deco, opts, el) {
			var Child = $.jstree.plugins[deco];
			if(Child) {
				this._data[deco] = {};
				Child.prototype = this;
                                //sent the element to the plugin constructor
				return new Child(opts, this, el);
			}
			return this;
		},
```

This is the approach I am using.

Is there a better way, or a way that does not need tampering with the core?

**Comment by vakata** [comment]
You already have the element available as `this.element`. 

Best regards,
Ivan

**Comment by SuricateCan** [comment]
Thanks for the answer @vakata, but the element is not there yet, at least not at the time the plugin function is called.
Should I tap into one of the functions before I can access that?
