### ISSUE TITLE
checkbox: How to display on the specified node ?tks

### ISSUE THREAD

**Issue by Wizzercn** [vakata/jstree#1421]
![qq 20160425150216](https://cloud.githubusercontent.com/assets/2408114/14776104/9680bdec-0af6-11e6-9048-f069b44e33d0.png)

**Comment by vakata** [comment]
Use CSS selectors and set `display:none` to the checkboxes that you do not need. I can't help you with a selector as that is specific to your structure. 

Best regards,
Ivan
