### ISSUE TITLE
Crash when deleting the root children while having keyboard focus

### ISSUE THREAD

**Issue by BrownBear2** [vakata/jstree#1422]
Hi there, when you have keyboard focus on the tree and call:

```
tree.delete_node(tree._model.data["#"].children)
```

jsTree crashes in line 3849:

```
this.get_node(this._model.data[$.jstree.root].children[0], true).children('.jstree-anchor').focus();
```

Uncaught TypeError: this.get_node(...).children is not a function

**Comment by vakata** [comment]
Could you please provide a demo (jsfiddle perhaps?), as I believe this was fixed in 3.3.0 - which version are you using?

**Comment by BrownBear2** [comment]
Hi I can do that later. I updated to the newest version to see if the problem was fixed and it didn't change.

**Comment by BrownBear2** [comment]
Sorry for wasting your time. I didn't have the option "disable cache when devtools is open" enabled and apparently was still using the older version of jstree. It works now. Thanks for the quick reply.
