### ISSUE TITLE
There is a bug on 3.3.0 when refresh TREE

### ISSUE THREAD

**Issue by zjl1985** [vakata/jstree#1423]
in 3.0.4 its ok
but in 3.3.0
when refresh  tree
node state selected and checked not show

**Comment by zjl1985** [comment]
I found that the difference between
3.3.0 has
```
this._data.core.selected = [];
this._data.core.last_clicked = null;
this._data.core.focused = null;
```

**Comment by vakata** [comment]
Please show me a demo, I cannot reproduce anything based on this description, sorry.

Best regards,
Ivan

**Comment by vakata** [comment]
Please clarify or provide a demo and I will reopen, I can not reproduce this for now.

Best regards,
Ivan
