### ISSUE TITLE
[Feature] Nice to have get_undetermined method

### ISSUE THREAD

**Issue by thanhkhanhcntt** [vakata/jstree#1425]
Dear,
I see the framework has two method "get_checked" and "get_selected", 
so I want get_checked and  parents of them. So get_undetermined is nice to have.

**Comment by vakata** [comment]
There is no quick way to get the undetermined nodes as that is a visual property only, but you can certainly use `get_top_checked` / `get_top_selected` and get the parents of each of those nodes - the list you get will be all the undetermined nodes.
