### ISSUE TITLE
Search Plugin Performance when 'show_only_matches': true

### ISSUE THREAD

**Issue by srkunze** [vakata/jstree#1426]
Searching in a tree of size 1000 to 2000 nodes works fine **and** fast.

However, having show_only_matches enabled in the same tree is extremely slow. Is there something that can be done here? Or have I done something wrong?

**Comment by srkunze** [comment]
We found that 

```
if(this._data.search.res.length && !append) {
    this.clear_search();
}
```

in `this.search` takes a huge amount of time. Why not, instead of clearing, redrawing the tree as during initial rendering?

**Comment by vakata** [comment]
Which version are you using? 

Keep in mind `show_only_matches` will always be slower, but there was a large improvement with 3.3.0.

If you are already using 3.3.0 - I am sorry, I will keep trying to improve the performance, but for now this is the best I can do. I will let you know if I make further improvements.

If you are not using 3.3.0 - I recommend the update - in some cases the search performance improved 4 to 5 times.

Best regards,
Ivan

**Comment by srkunze** [comment]
Thanks a lot. 3.3.0 makes "show_only_matches" extremely fast! +1
