### ISSUE TITLE
When nothing found, entire tree is shown although "show_only_matches=true"

### ISSUE THREAD

**Issue by srkunze** [vakata/jstree#1427]
Our internal tests revealed, that users would expect nothing to see instead; with a note to clear the search input.

How can this be achieved?

**Comment by vakata** [comment]
Use the `search.jstree` event to achieve that. As for the cause of this - a few versions back an empty container was shown, but then there were a few tickets on this being confusing. Anyway - you can use the event as I mentioned and show a custom message to the user.

**Comment by oritstone** [comment]
What do you mean by using the `search.jstree` event? 
Do you have a code example on how to achieve a behavior where nothing is shown in the tree when no results are found?
