### ISSUE TITLE
destroy() causing a "Cannot read property 'triggerHandler' of null" error

### ISSUE THREAD

**Issue by du002cl** [vakata/jstree#1428]
I replicated my issue, mostly, in this jsfiddle.

[http://jsfiddle.net/DGAF4/1293/](http://jsfiddle.net/DGAF4/1293/)

The only way I could solve my problem  was by changing the jstree code. By checking if this.element is null at the start of the draw_children function AND at the start of the trigger function. 

Im not certain the above jsFiddler replicates my issue with draw_children, but it would be great if that could be checked as well.

**Comment by vakata** [comment]
I can see the error, but I won't be adding such a check. It is counter intuitive to check if the tree has been destroyed in every place where there is an async operation happening. I will see how I can improve on this by changing the destroy method.
