### ISSUE TITLE
TypeError: Cannot read property 'get_node' of null

### ISSUE THREAD

**Issue by vKarter** [vakata/jstree#1431]
When we choose option Rename from context menu and then we will try to copy or delete a node the error above occur.

**Comment by vakata** [comment]
Please provide a demo (jsfiddle perhaps?), as I can not reproduce this, also please tell me the jstree version you are using.

**Comment by vKarter** [comment]
![jstree](https://cloud.githubusercontent.com/assets/1113891/15016544/fecc1f0a-1211-11e6-919e-c3bd554b89b9.gif)

**Comment by vKarter** [comment]
Thank you for so fast fix.
