### ISSUE TITLE
Meteor Integration

### ISSUE THREAD

**Issue by Joe312341** [vakata/jstree#1433]
Hello,

To integrate jstree npm package into MeteorJS you need to do some slight changes to how jstree imports jquery plus how to organize the theme folders. Can I write this up so it can be added somewhere on github faq / readme or do you want me to fork a separate project?

Great plugin btw :)

Joe

**Comment by vakata** [comment]
Please do share the differences and I will include them in the docs. 

Best regards,
Ivan
