### ISSUE TITLE
refresh_node() does nothing for AJAX-loaded trees

### ISSUE THREAD

**Issue by tw3** [vakata/jstree#1434]
You can see this by trying to refresh a node in the AJAX tree on the jstree web site.

1) Go here in Chrome: https://www.jstree.com/docs/json/
2) Open the developer console (F12)
3) Run this command in the console:
$('div.demo.jstree-5').jstree(true).open_node('j5_1')
4) As you will see under the "Using AJAX" section the "Root 1" folder opens and loads the subnodes
5) Run this command in the console:
$('div.demo.jstree-5').jstree(true).refresh_node('j5_1')
6) Nothing happens, there is no network activity

**Comment by vakata** [comment]
This is because `refresh_node` will only reload any opened children inside the specified node, not the node itself (as specified in the docs). 

Best regards,
Ivan

**Comment by tw3** [comment]
So this behavior changed from 3.2.1 to 3.3.0?

**Comment by tw3** [comment]
Looks like this is fixed in 3.3.1, thanks!
