### ISSUE TITLE
Loading time is so large

### ISSUE THREAD

**Issue by devendrakeshari** [vakata/jstree#1435]
Hello sir
 i have written  a code of JSTree but there is a problem of loading time .
 can you please explain what is the problem in my code .
 function loadNodes(tree, node, cb) {
          var nodeId = node.id == "#" ? "" : node.id;              
          var sfNode = new SObjectModel.sfNode();
          sfNode.retrieve({ 
              where: {Parent: {eq: nodeId}}, 
              limit: 5 }, 
              function(err, records) {
              if (err) {
                  displayErr(err);
              } else {
                  var nodes = [];
                  records.forEach(function(record) {
                     // alert('parent record.get("DisplayName__c")::' + record.get("DisplayName__c"));
                      
                      if(record.get("DisplayName__c") != null 
                          && record.get("DisplayName__c") != '' 
                          && record.get("DisplayName__c") != undefined
                      ){
                          nodes.push({ 
                              id: record.get("Id"),
                              description: record.get("PartDescription__c"),
                              text: record.get("DisplayName__c"),                          
                              children: true
                          });
                      }
                  });       
                  cb.call(tree, nodes);
              }
          });

**Comment by vakata** [comment]
Sorry, I can only help with problems with jstree's own code, I have no idea why you get speed issues with your code. Try debugging the standard way - check your net tab, or profile your JS depending on how the data comes in.

As for jstree tips - for huge volumes of data it may help to disable `core.worker`, but keep in mind that this will block the main thread - check it out and see.
