### ISSUE TITLE
Option to save state data on DND operations

### ISSUE THREAD

**Issue by jacobbunkley** [vakata/jstree#1437]
Hello,
Is there a way for jstree to save the state object of a node as it is dragged and dropped from one table to another? I am specifically talking about the checked: true | false attribute...

https://jsfiddle.net/bqjyn35c/2/

The nodes start off checked, but when I move them to another tree, then the state is destroyed (I'm guessing here). However, if I move them within the same tree, the state is preserved.

I would expect the state to be preserved when moving nodes from one tree to another, and in all DND operations.

**Comment by vakata** [comment]
No, there is no way to do that with a config option. The only way to achieve that is to do it manually in a `copy_node.jstree` event handler. There is a reference to the old and the new node, so the state can be reapplied manually.

Best regards,
Ivan
