### ISSUE TITLE
auto load after 30 seconds

### ISSUE THREAD

**Issue by anyway111** [vakata/jstree#1438]
Hi ad,
sorry my bad English.
I'm using jstree library, It's great!
I have a menu use jstree, when I click on 1 node and call function load data from server.
and now i want to setimeout for loading data from server after about 30 seconds.
How i can get again node clicked(auto load after 30s) to submit to server?

**Comment by vakata** [comment]
Hi,

I am not sure I understand what you need. If it is to refresh the data - call `.refresh()` in a `setInterval`. If you need to get the tree content and send it to the server - call `.get_json()` in a `setInterval` and use `$.ajax` to sync to a server.

Anyway - this is not a jstree issue, so I am closing this.

Best regards,
Ivan
