### ISSUE TITLE
TypeError: Cannot read property 'get_node' of null - When Deleting 

### ISSUE THREAD

**Issue by danielflippance** [vakata/jstree#1439]
Similar to issue https://github.com/vakata/jstree/issues/1431 - When I try to delete a node from the tree using the context menu I see this error:

jstree.js:5708 Uncaught TypeError: Cannot read property 'get_node' of nullremove.action @ jstree.js:5708$.vakata.context._execute @ jstree.js:5958(anonymous function) @ jstree.js:6183b.event.dispatch @ jquery-1.9.1.min.js:1y.handle @ jquery-1.9.1.min.js:1
main.min.js?1.0.893:136 ++ saved

The line of code with the error is 5708:

    5705    "label"				: "Delete",
    5706    "action"			: function (data) {
    5707        var inst = $.jstree.reference(data.reference),
    5708            obj = inst.get_node(data.reference);  //Error here
    5709        if(inst.is_selected(obj)) {
    5710            inst.delete_node(inst.get_selected());
    5711        }

**Comment by vakata** [comment]
How is it similar to the previous issue? Does this happen when renaming only - if so - did you try the fix from the referenced issue? If not - could you please provide a demo, as I can not reproduce it:
http://jsfiddle.net/DGAF4/1303/

Best regards,
Ivan

**Comment by vakata** [comment]
I am closing this until further info is provided.

**Comment by danielflippance** [comment]
It's similar in that the error happens when clicking a context menu item and the error message is the same. Working on fiddle:

![jstree](https://cloud.githubusercontent.com/assets/5957235/15403952/1ebca7f4-1db0-11e6-8419-ea5ac45ad9ba.gif)

**Comment by danielflippance** [comment]
It happens when a node is made editable by clicking it:
http://jsfiddle.net/vt8bmvt3/

    $('#jstree').bind("select_node.jstree", function (e, data) {
        $('#jstree').jstree(true).edit(data.node, null, function(node, status, cancelled){ });
    });

![jstree2](https://cloud.githubusercontent.com/assets/5957235/15404462/76f84d2c-1db2-11e6-9398-07380eeb5ae9.gif)
