### ISSUE TITLE
Cascade 2 Levels

### ISSUE THREAD

**Issue by spirewebsitedesign** [vakata/jstree#1442]
Hello

Is there anyway to limit the cascading feature? So cascading would apply only to levels 1,2,3 but not 4?

Thank you for your time,
Arthur

**Comment by vakata** [comment]
What do you mean by cascading? If you mean to render all children flat after the fourth level - no that is not possible, you should convert your data to match what you need to achieve.

If I misunderstood - please clarify?

**Comment by spirewebsitedesign** [comment]
I'm referring to the checkbox plugin. By default checking one of the boxes will also check all the children & grandchildren, etc. of that node. I want it to only check the children, not the grandchildren or any deeper levels.
