### ISSUE TITLE
redirection by link doesn't work in jstree

### ISSUE THREAD

**Issue by ahmadbadpey** [vakata/jstree#1446]
In jstree jquery plugin,I want when user click on a node , be redirected to href of clicked link.

this is data that is passed to jstree:

```
[
    {
        "id": 4,
        "contentable_id": 8,
        "contentable_type": "App\\Unit",
        "text": "واحد جدید",
        "parent_id": "#",
        "icon": "fa fa-file-text-o",
        "a_attr": {
            "href": "./unit/8/edit"
        }
    },
    {
        "id": 5,
        "contentable_id": 5,
        "contentable_type": "App\\Unit",
        "text": "واحد من ",
        "parent_id": "#",
        "icon": "fa fa-file-text-o",
        "a_attr": {
            "href": "./unit/5/edit"
        }
    }
]

```
And below is jstree calling codes:

```
$treeview.jstree({
    "core": {
        'data': {
            'url': targetUrl
        },
        "check_callback": true,
        "animation": 200,
        "dblclick_toggle": false,
        "keep_selected_style": false
    },
    "plugins": ["dnd", "contextmenu"],
    "contextmenu": {
        "select_node": false, 
        "show_at_node": false,
    }
    }).on('changed.jstree', function (e, data) {
        document.location = data.instance.get_node(data.selected[0], true).a_attr.href;
    });

```

As you see I used changed jstree event to capture click event and redirection as jstree author is recommended [here](https://github.com/vakata/jstree/pull/712#issuecomment-46044101) .

But when click on a link on a node this error occured :

`Uncaught TypeError: Cannot read property 'href' of undefined`

what is Problem and what is proper solution?

**Comment by koukimetal** [comment]
Do following lines work for you?
bind("changed.jstree", function (e, data) {
    if(data.node) {
        document.location = data.node.a_attr.href;
    }
});
