### ISSUE TITLE
Setting state on tree manually

### ISSUE THREAD

**Issue by Asken** [vakata/jstree#1447]
How do I set the state of the tree manually? From the docs I find the method `set_state (state [, callback])` but it is marked as private and it also states:

> sets the state of the tree. Used internally.

Can I still use it to set the state?

**Comment by koukimetal** [comment]
If you want to use HTML format you can read Setting initial state with classes in https://www.jstree.com/docs/html/
If you want to use JSON format you can read The format in https://www.jstree.com/docs/json/

**Comment by Asken** [comment]
I actually wanted to set the state on load from a `localStorage` state and it is possible to alter state before it's set on the tree. This is what I did:

```
'state': {
        'filter': function (state) {
                return app.user.tree.state;
        }
}
```

**Comment by koukimetal** [comment]
By the way,  isn't State plugin enought?

**Comment by Asken** [comment]
Normally it probably would but the tree state is coming from remote source and is kept per user. When changing browser and/or computer it follows you.
