### ISSUE TITLE
Use of copy_node for copy one tree node to another tree

### ISSUE THREAD

**Issue by dipeshloke** [vakata/jstree#1450]
Hey I'm using this awesome JsTee 3.0 but i stuck on one thing, I have two jstree, lets give name A and B.  On my page I just want copy one node of  A tree to B tree, when i use following code

```
var ref = $('#A').jstree(true), codeRef = $('#B').jstree(true);
ref.copy_node(codeRef.get_node('Node1'), ref.get_node('Node2'));
```

on check_callback I noticed Jstree takes 'Node1' of A tree (instead of B tree which I'm sending) and simply copying into A tree itself. Please help to resolve this issue.
Thanks

**Comment by vakata** [comment]
I am afraid I can not reproduce the issue. Here is a demo:
http://jsfiddle.net/DGAF4/1322/

Please update the fiddle so that I can see the issue and I will reopen.

Best regards,
Ivan
