### ISSUE TITLE
Nested <ul> goes missing

### ISSUE THREAD

**Issue by bytestream** [vakata/jstree#1451]
Hi,

I'm trying to initialise jstree with nested ````<ul>````'s but it seems to be disappearing... I've replicated this here: https://jsfiddle.net/0zwwk8ts/

Any suggestions?

**Comment by vakata** [comment]
You are nesting an `<ul>` node inside another `<ul>` node, which is not valid HTML, plase provide a wrapping `<li>`

Best regards,
Ivan
