### ISSUE TITLE
Show only matched nodes..and hide rest of the nodes including parent nodes

### ISSUE THREAD

**Issue by dipeshloke** [vakata/jstree#1452]
@vakata Hi Vakata,

While m using JSTree seach plugin it do search for "believe" it highlights correct node but also it shows other node too, even though I've written ```
"search": {
                        'case_insensitive': true,
                        'show_only_matches': true                        
                    },
```
[http://imgh.us/SC_6.jpg](url)
Please see attached image and please help me! Thank you.

**Comment by dipeshloke** [comment]
@

**Comment by vakata** [comment]
Parents will always be shown - sorry. After all - it is a tree structure - showing only matches in a list will defeat the purpose of jstree. Imagine you have two matches with the same name - without the parents it won't be possible to know which one is which.

Best regards,
Ivan

**Comment by dipeshloke** [comment]
Yes i can understand. But is it possible to do with JStree?? because its client requirement ..haha  
Appreciate your help
