### ISSUE TITLE
Safari 5.1.4: SubNode is automatically getting clicked when I right click at the menu at the Jstree ContextMenu 

### ISSUE THREAD

**Issue by rajesh-51kannan** [vakata/jstree#1454]
Steps to reproduce:
1. Resize the safari 5.1.4
2. Right click on the menu (popup opens which is overlapped above the menu as the browser has been resized)
3. Without even clicking on the submenu or subnodes, the specific event will get triggered.

FYI, it is working fine on all other browsers.

**Comment by ameti** [comment]
This happens in chrome too when right-clicking the node gets selected.

**Comment by vakata** [comment]
Clicking on any item on the already opened contextmenu will trigger the action, jsTree only listens for a `click` event - if the browser fires it, the action will be executed - jstree will not check the `e.which` property to ensure a left click, as this is historically buggy. So basically - this is a won't fix - sorry. 

Let me know if I misunderstood and I will reopen.

Best regards,
Ivan
