### ISSUE TITLE
[Checkbox plugin] Selection of parent of last Node in some nested nodes, selects all other previous nodes 

### ISSUE THREAD

**Issue by ameti** [vakata/jstree#1455]
I was testing the sitebrowser demo, and I added the checkbox plugin. I created some nested nodes like in the picture, when I select the parent of the last nested Node(Node 8 in the pic), all other previous nodes get selected. Is it possible to select only the child nodes?
Ex. I want to delete only that selected node with its child, can I do that without deleting every child first?

![image](https://cloud.githubusercontent.com/assets/6298453/15538222/2828aafc-227b-11e6-815f-c024813fef23.png)

**Comment by vakata** [comment]
Yes, if is possible - check out the `cascade` and `three_state` contextmenu options. You can fine tune how selections propagate.

Best regards,
Ivan
