### ISSUE TITLE
When move back not selected node then node becomes selected.

### ISSUE THREAD

**Issue by intsitesdotru** [vakata/jstree#1458]
Probably it is not an issue, please consider.

When we move some not selected node to some NEW position then node stays NOT selected.
BUT when we start (start event is fired) to move some not selected node and back it to the SAME position then it becomes SELECTED and Selected even is fired.

**Comment by vakata** [comment]
State is cleared when a node is moved. If returned to the same position there is no actual move. This is the expected behavior.

Thank you for asking,
Ivan

**Comment by intsitesdotru** [comment]
When we try move node we don't want to click on it.

**Comment by vakata** [comment]
Oh, sorry - I misunderstood. As far as I understand - a click is triggered. I will see what I can do.

**Comment by intsitesdotru** [comment]
right, click is triggered and as a resut Selected triggered also. Thank you Ivan.
