### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by mahmoudHosny** [vakata/jstree#1460]
Hi
I want to set the tree to RTL
is set the themes options as follow:
"themes": {
                "rtl":true,
                "theme" : "default-rtl"
            },
            "core":{
                'data': function(node,cb){
                    cb(require("../SearchPages/searchTreeData"));
                }
}
BUT the tree still LTR

**Comment by vakata** [comment]
jsTree will use the `direction` CSS property of its container - it is not a config option. Basically - either set it anywhere in your CSS (there is no need to be inline). Here is a demo:
http://jsfiddle.net/DGAF4/1348/

Best regards,
Ivan

**Comment by mahmoudHosny** [comment]
Thanks it's worked.
