### ISSUE TITLE
Loading checkbox state from JSON

### ISSUE THREAD

**Issue by BorisKrones** [vakata/jstree#1461]
Hi together,

since some weeks i use jstree. It passes all my requirements.
Some days ago i wanted to add checkboxes, but if i load JSON data the state of the checkbox is not loaded. So i now would like to clarify if it is an issue or my fault.

//Edit: I would like to load check state of children, not root node.

Loading the nodes and childs:

`'data' : {
    'url' : function (node) {
      return node.id === '#' ?
        'vehicleGroups.php' :
        'singleVehicles.php?nid=' + node.id;`

The child itself:
`{ "text" : "Kermit","children" : false, "icon" : "fa x icon-state-danger",  state       : {    selected: true } }`

I tried with:
 "class": "jstree-checked" // Not working
 state       : {    selected: true } // Not working
 state       : {    check: true } // Not working

is it a bug / issue or didnt i have enough coffee?

Best regards from germany
Boris

**Comment by vakata** [comment]
Hi,
It depends on your config. If you use `tie_selection : false`, then `state : { checked : true }` is the way to go, otherwise `state : { selected : true }`.

If you still have issues I will reopen - just let me know, but please provide your full config as well.

Best regards,
Ivan

**Comment by mdelerue** [comment]
Hi,

I'm facing the same issue. When I load data from my AJAX call the checkbox is always selected.

Here is the JS code : 
```
$("#arbre_comp").on('ready.jstree', function (e, data) {

        }).jstree({
            "checkbox": {
                "keep_selected_style": false
            },
            "contextmenu": {
                "items": function ($node) {

                    if ($node.original.niveauArbre != 3) {
                        return {
                            "Ajouter": {
                                "label": "Ajouter",
                                "action": function (obj) {
                                    console.log(obj);
                                },
                                icon: "fa fa-plus"
                            }
                        };
                    } else {
                        return undefined;
                    }
                }
            },
            "plugins": ["checkbox", "contextmenu"],
            'core': {
                'multiple': true,
                data: {
                    'url': function (node) {
                        return node.id === '#'
                                ? "/api/n1"
                                : "/api/children/" + node.id;
                    },
                    'type': 'GET'
                }
            }

        }).on('changed.jstree', function (e, data) {
            if (data.action == 'deselect_node') {
                changeStatut(data, false);
            } else if (data.action == 'select_node') {
                changeStatut(data, true);
            }

        });
```

And the kind of JSON data I use : 

```
{
"id":"94",
"text":"4.1.1.1",
"idCreateur":0,
"builtin":true,
"state":{
    "selected":false,
    "checked":false,
    "disabled":false,
    "opened":true
},
"children":false,
"parent":"29",
"niveauArbre":3,
"code":"4.1.1.1"
}
```

I just updated to use the version 3.3.2.

If you have any idea, it will be wonderful.
Thank you.
Marc

**Comment by mdelerue** [comment]
OK, 
I was messing with the three_state parameter. Everything's ok now.
