### ISSUE TITLE
new nodes buttons events loss after adding more nodes

### ISSUE THREAD

**Issue by sakhno** [vakata/jstree#1462]
I am not sure this is issue. When I am adding new nodes with buttons inside them, buttons event works only until more new nodes added.

var node = new Object();
node.id = data.newWordId;
node.text = "<span class='textvalue'>"+data.newWordName+"</span><span class='buttons'><input class='delete' type='image' src=''/></span>
$("#tree").jstree().create_node($("#"+parentId), node);
$("#"+node.id).children(".jstree-anchor").children(".buttons").children(".delete").click(function () {
		deleteNode();
	});
So, just after creation button works well, but after adding new node, old buttons doesn’t work.

**Comment by vakata** [comment]
Use event delegation (attach the handlers to the main tree container) - do not bind events to the actual DOM elements, as they will be redrawn by jstree.

Best regards,
Ivan
