### ISSUE TITLE
deselect_all.jstree event not properly passing current selection

### ISSUE THREAD

**Issue by auntiewarhol** [vakata/jstree#1464]
According to the docs, the deselect_all.jstree event should be passing an array of the current (which I take to mean the new) selections. Except what I'm actually receiving is what looks like such an array when you dump it to the console, but which has had the length truncated, so you can't actually access the data in it.

I presume this is because of line 3202:
			this._data.core.selected = [];

Should that be moved down below line 3214, so that it happens after the trigger is fired?

![zero-length-array-w-element](https://cloud.githubusercontent.com/assets/299264/15781109/394dbaca-296a-11e6-8e82-8400d0819a13.png)

**Comment by auntiewarhol** [comment]
also note: calling get_selected() from inside my deselect_all event handler returns the same thing, for what looks like the same reason.

**Comment by auntiewarhol** [comment]
Sorry, one more note: I thought I had the latest, but I was actually referencing version 3.2.1; the issue still exists in 3.3.1, but the line in question is now 3244.

**Comment by vakata** [comment]
`selected` will always be an empty array inside a `deselect_all.jstree` event handler, as the whole selection was just cleared (which is what `deselect_all` does, as the name suggests). 

If you need the old selection - it is available as well. 

Best regards,
Ivan
