### ISSUE TITLE
load_node event not getting fired for each row

### ISSUE THREAD

**Issue by sousarka** [vakata/jstree#1465]
Hi,
When loading the jstree from a data array, I'm assuming the load_node method should be called for each loaded node. But that's not happening currently as load_node is only called once for the root node.

[https://jsfiddle.net/4Lk049pb/1/](url)

I'm looking for a callback method where I can get/set each node's text based on the number of children it has e.g., " node has y children" etc). Is that possible within the current framework? If so, could you please help? 

Thanks.

**Comment by vakata** [comment]
This is by design and will not change - you can use the `load_node.jstree` event, or better - the `model.jstree` event to loop through the nodes and change the text. 

Best regards,
Ivan
