### ISSUE TITLE
Display same tree multiple times on same page

### ISSUE THREAD

**Issue by unkrich5** [vakata/jstree#1466]
Hi,

I am confused on how to make the same tree be called multiple times on the same page. As of right now, only the first time it is called like below does it show up. 

```
	<div id="jstree_demo" class="demo" style="margin-top:1em; min-height:200px;">
	</div>
```

Does anyone know a workaround/fix? Thanks!

**Comment by mccalluc** [comment]
@unkrich5 : I can't replicate your problem. I have this:
```
<div class="output"></div>
<div class="output"></div>
```
and then call this:
```
$('.output').jstree({
  core: {
    data: data
  }
});
```
and I get two identical trees. Could you provide more html and the javascript you're actually using to create the trees?

**Comment by unkrich5** [comment]
Absolutely, here's the code that I am using.

```
<div id="jstree_demo" class="demo" style="margin-top:1em; min-height:200px;">
</div>
```

```
$(function () {
	var to = false;
	$('#demo_q').keyup(function () {
		if(to) { clearTimeout(to); }
		to = setTimeout(function () {
			var v = $('#demo_q').val();
			$('#jstree_demo').jstree(true).search(v);
		}, 250);
	});
	

	$('#jstree_demo').jstree({
			"core" : {
				"animation" : 0,
				"check_callback" : true,
		        'themes': {
		            'name': 'proton',
		            'responsive': true
		        },
			    'data' : {
			      "url" : "/jsons/u/",
			      "success": function(data){
                     series = data;
            },
			      "dataType" : "json" // needed only if you do not supply JSON headers
			    }
			},

			"plugins" : [ "contextmenu", "dnd", "search", "state", "types", "wholerow" ]
		});
});

```

It'll display one tree, but if I want to display it again and copy/paste the div to do so somewhere else in the same html file, it's not working. Just to note I am using Rails and this gem to use jsTree https://github.com/kesha-antonov/jstree-rails-4

**Comment by vakata** [comment]
This problem is not related to jstree - my guess is that you have two IDENTICAL divs, along with the DIV ID attribute, which is illegal, as the ID must be unique on a page according to the HTML spec.

Best regards,
Ivan
