### ISSUE TITLE
data function will run twice

### ISSUE THREAD

**Issue by csonlai** [vakata/jstree#1467]
Onto the next difference - "Child node 1" appears closed - that is because in the data we supplied true as the "children" property of this node (you can see it in the server response). This special value indicated to jstree, that it has to lazy load the "Child node 1" node.

	data: function (node, cb) {
		if(node.id === "#") {
		    cb(data); // initial data here
		}
		else {
		    cb([]);
		}
	}

but when i  set data with a function to use custom lazy loading,i use cb with initial data, data function will run twice at first load.
Initial data is only one node with children value is 'true'.

**Comment by vakata** [comment]
The function will be called as many times as needed to populate the tree - if you have opened nodes or the state plugin enabled it will be called as many times as there are open node (+ one more for the root node).

If this does not answer you question and you need further assistance please provide a demo of the problem (a jsfiddle perhaps).

Best regards,
