### ISSUE TITLE
How to add herf into tree node ?

### ISSUE THREAD

**Issue by diypyh** [vakata/jstree#1468]
Hi, How to add herf into tree node ?

I want to click the node to jump to other pages.

like this:
`data : {
    id : 'handler_root_node',
    href : 'www.google.com',
    text : "mytree"
}`

but it no work.

**Comment by koukimetal** [comment]
`data : { id : 'handler_root_node', a_attr: {href : 'www.google.com'}, text : "mytree" }`

$('#yourTreeId').jstree({})
.bind('changed.jstree', function (e, data) {
        if(data.node) {
            var href = data.node.a_attr.href;
            if(href !== '#') {
                window.open(href, '_blank');
            }
        }
    })

**Comment by diypyh** [comment]
Thanks
