### ISSUE TITLE
How to add button in the node?

### ISSUE THREAD

**Issue by diypyh** [vakata/jstree#1469]
Hi, I want to add button in the node, How to achieve?

like this:

+ Root node
   -  Sub node1      [Button]
   -  Sub node2      [Button]

**Comment by mccalluc** [comment]
@diypyh: The "text" you supply is actually treated as html by default:
```js
$('#output').jstree({
  core: {
   data: [{id: 'x', text: '<button>hello</button>'}]
}})
```

See https://www.jstree.com/api/#/?f=$.jstree.defaults.core.force_text if that's not the behavior you want.

**Comment by vakata** [comment]
This has also been answered many times in the discussion group. You can either use the text of the node (as @mccalluc suggested) or create a custom plugin (which is a bigger task) it all depends on the functionality you need.

Best regards,
