### ISSUE TITLE
jsTree - issue when checking last subnode (using AJAX) - jstree 3.3.1, jQuery 2.1.4

### ISSUE THREAD

**Issue by eckopage** [vakata/jstree#1471]
Hi All.

I have some issue with check module. It means when i check the subnode then tree will freeze. I tried to debug in chrome debugger and i can see some mishmatch.

Scenario before i check subnode.

data1: (initial data - only one parent node)

{"id":23,"text":"AgentRoot Tomek","children":true}

data2: (data with childnodes)

{"id":23,"text":"AgentRoot Tomek","children":[{"id":"9","text":"Agent 2 Agent","children":true},{"id":"51","text":"Agent Marek","children":false},{"id":"52","text":"Agent Mietek","children":false},{"id":"53","text":"Agent Adam","children":false},{"id":"54","text":"Agent Zenon","children":false},{"id":"55","text":"Agent Zbigniew","children":false}]}

This is my source code:

`   angular.element(document).ready(function() {
            $('#containerJsTree')
                .on("changed.jstree", function(e, data) {
                    $scope.selected = data.selected;
                    if (!$scope.selected) {
                        $scope.selected = [];
                    }
                })
                .jstree({
                    "core": {
                        "data": {
                            "dataType": "JSON",
                            "url": function(node) {
                                return "api/reports/agents/getAgentHierarchyNode?id=" + node.id;
                            },
                            "data": function(node) {
                                return { 'id': node };
                            }
                        }
                    },
                    "checkbox": {
                       // 'keep_selected_style': false,
                        //'three_state': false,
                        'cascade': ''
                    },
                    "plugins": ["checkbox"]
                });
      });`

Jstree method is looping all the time.
It is strange but as_dom is undefined. Is it ok?
as_dom -> obj = Object {id: "9", text: "Agent 2 Agent", icon: true, parent: "9", parents: Array[4]…}, **as_dom = undefined**
945
            if(obj && obj.id) {
946
                obj = obj.id;
947
            }
948
            var dom;

		get_node : function (obj, as_dom) {
			if(obj && obj.id) {
				obj = obj.id;
			}
			var dom;
			try {
				if(this._model.data[obj]) {
					obj = this._model.data[obj];
				}
				else if(typeof obj === "string" && this._model.data[obj.replace(/^#/, '')]) {
					obj = this._model.data[obj.replace(/^#/, '')];
				}
				else if(typeof obj === "string" && (dom = $('#' + obj.replace($.jstree.idregex,'\\$&'), this.element)).length && this._model.data[dom.closest('.jstree-node').attr('id')]) {
					obj = this._model.data[dom.closest('.jstree-node').attr('id')];
				}
				else if((dom = $(obj, this.element)).length && this._model.data[dom.closest('.jstree-node').attr('id')]) {
					obj = this._model.data[dom.closest('.jstree-node').attr('id')];
				}
				else if((dom = $(obj, this.element)).length && dom.hasClass('jstree')) {
					obj = this._model.data[$.jstree.root];
				}
				else {
					return false;
				}

				if(as_dom) {
					obj = obj.id === $.jstree.root ? this.element : $('#' + obj.id.replace($.jstree.idregex,'\\$&'), this.element);
				}
				return obj;
			} catch (ex) { return false; }
		}

Thanks a lot.
Regards,
E.Cz

**Comment by vakata** [comment]
You have duplicate IDs (I can see `23` multiple times). jsTree does not support duplicate IDs - the whole idea of the ID is to be unique, if you cannot provide unique IDs - leave that to jstree and do not specify IDs in your data.

Best regards,

**Comment by eckopage** [comment]
Thank You do much. I thought that i missed something. 

Wysłane z iPhone'a

Dnia 10.06.2016 o godz. 17:40 Ivan Bozhanov <notifications@github.com> napisał(a):

**Comment by eckopage** [comment]
Hi Ivan.

I just wondering becouse i am using AJAX in jstree. I would like to display
user relation (parent - child) and i suppose that i need to pass some id.
You mentioned that i should use the unique id. I am using checkbox plugin
as well and how to pass id parameter into webservice?

I can create some unique id like dsfsfsfdx3423x4t43_23 and use only digit
after underscore. Is it corrent idea? What do You think?

Kind regards,

Erwin Czerniawski.

2016-06-10 17:40 GMT+02:00 Ivan Bozhanov <notifications@github.com>:

> You have duplicate IDs (I can see 23 multiple times). jsTree does not
> support duplicate IDs - the whole idea of the ID is to be unique, if you
> cannot provide unique IDs - leave that to jstree and do not specify IDs in
> your data.
>
> Best regards,
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vakata/jstree/issues/1471#issuecomment-225217797>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFWK3MwzSivMthbWZrECaXnfa0mSVsypks5qKYVigaJpZM4Iyv4m>
> .
>



-- 
Pozdrawiam,
Czerniawski Erwin.
