### ISSUE TITLE
How to add text and herf into tree node ?

### ISSUE THREAD

**Issue by akmil** [vakata/jstree#1473]
For example I have to make this workaround if I want to see text and href inside leaf:
http://plnkr.co/edit/TqdkXU0fLtjy11dnsckL
Also you can see small gap when leaf is opens with animation.

I think it would be better to generete 'span' instead of 'a' (pull req: https://github.com/vakata/jstree/pull/1472 ). And this feature would be more flexible if I can define it in 'core' options

**Comment by vakata** [comment]
SPAN has absolutely no semantic meaning, as opposed to an anchor. I insist on using anchors, as those enable a smooth experience for disabled users. This is why jsTree is designed according to the WAI ARIA tree spec.

Best regards,
