### ISSUE TITLE
Configure more than one child array

### ISSUE THREAD

**Issue by rafakwolf** [vakata/jstree#1475]
I'm trying to load this json data:
`{
    "nome": "Ministérios Ordenados",
    "tipoModeloGrupoDependeId": 177,
    "tipoModeloGrupos": [
        {
            "nome": "Ordenação de Diácono",
            "tipoModeloGrupoDependeId": 579,
            "tipoModeloGrupos": [
                {
                    "nome": "Celibatário",
                    "tipoModeloGrupoDependeId": 580,
                    "tipoModeloGrupos": [
                        {
                            "nome": "Em Vista do Presbiterato",
                            "tipoModeloGrupoDependeId": 586,
                            "tipoModeloGrupos": [],
                            "tipoModelos": [
                                {
                                    "nome": "Rito de Admissão",
                                    "id": 1098
                                },
                                {
                                    "nome": "Investigação Prévia à Ordenação",
                                    "id": 1099
                                },
                                {
                                    "nome": "Ordenação",
                                    "id": 1103
                                },
                                {
                                    "nome": "Juramento, Instrução e Questionário de Perito",
                                    "id": 1107
                                }
                            ],
                            "id": 589
                        },
                        {
                            "nome": "Permanente",
                            "tipoModeloGrupoDependeId": 586,
                            "tipoModeloGrupos": [],
                            "tipoModelos": [
                                {
                                    "nome": "Rito de Admissão",
                                    "id": 1104
                                },
                                {
                                    "nome": "Ordenação",
                                    "id": 1106
                                },
                                {
                                    "nome": "Investigação Prévia à Ordenação",
                                    "id": 1108
                                },
                                {
                                    "nome": "Juramento, Instrução da Perícia e Quetionário do Perito",
                                    "id": 1109
                                }
                            ],
                            "id": 590
                        }
                    ],
                    "tipoModelos": [],
                    "id": 586
                },
                {
                    "nome": "Casado",
                    "tipoModeloGrupoDependeId": 580,
                    "tipoModeloGrupos": [],
                    "tipoModelos": [
                        {
                            "nome": "Rito de Admissão",
                            "id": 1110
                        },
                        {
                            "nome": "Investigação Prévia à Ordenação",
                            "id": 1111
                        },
                        {
                            "nome": "Juramento, Instrução e Questionário de Perito",
                            "id": 1112
                        },
                        {
                            "nome": "Ordenação",
                            "id": 1113
                        }
                    ],
                    "id": 587
                },
                {
                    "nome": "Viúvo",
                    "tipoModeloGrupoDependeId": 580,
                    "tipoModeloGrupos": [
                        {
                            "nome": "Em Vista do Presbiterato",
                            "tipoModeloGrupoDependeId": 588,
                            "tipoModeloGrupos": [],
                            "tipoModelos": [
                                {
                                    "nome": "Rito de Admissão",
                                    "id": 1114
                                },
                                {
                                    "nome": "Investigação Prévia à Ordenação",
                                    "id": 1115
                                },
                                {
                                    "nome": "Juramento, Instrução e Questionário da Perícia",
                                    "id": 1116
                                },
                                {
                                    "nome": "Ordenação",
                                    "id": 1117
                                }
                            ],
                            "id": 593
                        },
                        {
                            "nome": "Permanente",
                            "tipoModeloGrupoDependeId": 588,
                            "tipoModeloGrupos": [],
                            "tipoModelos": [
                                {
                                    "nome": "Rito de Admissão",
                                    "id": 1119
                                },
                                {
                                    "nome": "Investigação Prévia à Ordenação",
                                    "id": 1120
                                },
                                {
                                    "nome": "Juramento, Instrução e Questionário da Perícia",
                                    "id": 1121
                                },
                                {
                                    "nome": "Ordenação",
                                    "id": 1122
                                }
                            ],
                            "id": 594
                        }
                    ],
                    "tipoModelos": [],
                    "id": 588
                }
            ],
            "tipoModelos": [],
            "id": 580
        },
        {
            "nome": "Ordenação de Presbítero",
            "tipoModeloGrupoDependeId": 579,
            "tipoModeloGrupos": [
                {
                    "nome": "Celibatário",
                    "tipoModeloGrupoDependeId": 581,
                    "tipoModeloGrupos": [],
                    "tipoModelos": [
                        {
                            "nome": "Pedido de Ordenação",
                            "id": 1123
                        },
                        {
                            "nome": "Investigação Prévia à Ordenação",
                            "id": 1124
                        },
                        {
                            "nome": "Juramento, Instrução e Questionário da Perícia",
                            "id": 1125
                        },
                        {
                            "nome": "Ordenação",
                            "id": 1126
                        }
                    ],
                    "id": 595
                },
                {
                    "nome": "Viúvo",
                    "tipoModeloGrupoDependeId": 581,
                    "tipoModeloGrupos": [],
                    "tipoModelos": [
                        {
                            "nome": "Pedido de Ordenação",
                            "id": 1127
                        },
                        {
                            "nome": "Investigação Prévia",
                            "id": 1128
                        },
                        {
                            "nome": "Juramento, Instrução e Questionário da Perícia",
                            "id": 1129
                        },
                        {
                            "nome": "Ordenação",
                            "id": 1130
                        }
                    ],
                    "id": 596
                }
            ],
            "tipoModelos": [],
            "id": 581
        },
        {
            "nome": "Incardinação Mediante Excardinação",
            "tipoModeloGrupoDependeId": 579,
            "tipoModeloGrupos": [
                {
                    "nome": "Clérigos",
                    "tipoModeloGrupoDependeId": 582,
                    "tipoModeloGrupos": [
                        {
                            "nome": "Diocesanos",
                            "tipoModeloGrupoDependeId": 597,
                            "tipoModeloGrupos": [],
                            "tipoModelos": [
                                {
                                    "nome": "Diácono",
                                    "id": 1131
                                },
                                {
                                    "nome": "Presbítero",
                                    "id": 1132
                                }
                            ],
                            "id": 598
                        },
                        {
                            "nome": "Religiosos",
                            "tipoModeloGrupoDependeId": 597,
                            "tipoModeloGrupos": [
                                {
                                    "nome": "Instituto de Direito",
                                    "tipoModeloGrupoDependeId": 599,
                                    "tipoModeloGrupos": [
                                        {
                                            "nome": "Diocesano",
                                            "tipoModeloGrupoDependeId": 601,
                                            "tipoModeloGrupos": [],
                                            "tipoModelos": [
                                                {
                                                    "nome": "Diácono",
                                                    "id": 1133
                                                },
                                                {
                                                    "nome": "Presbítero",
                                                    "id": 1134
                                                }
                                            ],
                                            "id": 602
                                        },
                                        {
                                            "nome": "Pontifício",
                                            "tipoModeloGrupoDependeId": 601,
                                            "tipoModeloGrupos": [],
                                            "tipoModelos": [
                                                {
                                                    "nome": "Diácono",
                                                    "id": 1135
                                                },
                                                {
                                                    "nome": "Presbítero",
                                                    "id": 1136
                                                }
                                            ],
                                            "id": 603
                                        }
                                    ],
                                    "tipoModelos": [],
                                    "id": 601
                                }
                            ],
                            "tipoModelos": [],
                            "id": 599
                        },
                        {
                            "nome": "Seculares",
                            "tipoModeloGrupoDependeId": 597,
                            "tipoModeloGrupos": [],
                            "tipoModelos": [
                                {
                                    "nome": "Diácono",
                                    "id": 1137
                                },
                                {
                                    "nome": "Presbítero",
                                    "id": 1138
                                }
                            ],
                            "id": 600
                        }
                    ],
                    "tipoModelos": [],
                    "id": 597
                }
            ],
            "tipoModelos": [],
            "id": 582
        },
        {
            "nome": "Excardinação",
            "tipoModeloGrupoDependeId": 579,
            "tipoModeloGrupos": [],
            "tipoModelos": [
                {
                    "nome": "Diácono",
                    "id": 1139
                },
                {
                    "nome": "Presbítero",
                    "id": 1140
                }
            ],
            "id": 583
        },
        {
            "nome": "Transferência de Diocese",
            "tipoModeloGrupoDependeId": 579,
            "tipoModeloGrupos": [],
            "tipoModelos": [
                {
                    "nome": "Diácono",
                    "id": 1141
                },
                {
                    "nome": "Presbítero",
                    "id": 1142
                }
            ],
            "id": 584
        }
    ],
    "tipoModelos": [
        {
            "nome": "Celebret",
            "id": 1143
        },
        {
            "nome": "Livro de Ordenações",
            "id": 1145
        }
    ],
    "id": 579
}`
but JSTree expects "children" as child node, but i have many child properties.

Sorry for the big JSON

**Comment by vakata** [comment]
Use `core.data` as a function and transform your JSON to the JSON structure required by jsTree. There is an example of using `core.data` as a function in the README of this repo, along with a jsfiddle.

Best regards,
Ivan
