### ISSUE TITLE
I have a requirement to show more than 100 nodes to be shown on an jstree.Can you help me out how to acheive it ?

### ISSUE THREAD

**Issue by Tejdeep2** [vakata/jstree#1476]
There are total 260 nodes under a node.My Existing jstree shows only 100 of them even after increasing the limit.

**Comment by vakata** [comment]
There is something wrong with your data - either duplicate IDs, or that the nodes are simply not there. I regularly test jstree with 60.000 (sixty thousand) nodes.

Best regards,
Ivan

**Comment by Tejdeep2** [comment]
Problem here is all the 260 nodes are child to a single node.

**Comment by vakata** [comment]
jsTree does not have a problem with that - something is wrong with your data. As I said - I have tested with thousands of nodes - both nested and as a flat list.

**Comment by vakata** [comment]
I can not help you further without you providing a demo, all I can say is that jstree has absolutely no problem with thousands of nodes as children of a single parent node.

**Comment by sarankumarBVS** [comment]
Hello Vakata,

I am colleague for Tejdeep. I can able to provide the demo for you. So, please let me know how can i able to connect you using skype or anything else.

Please find the below URL's for the reference where the limit is specified..
http://peterknolle.com/hierarchies-with-remote-objects-and-jstree/

https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_remote_objects_using_retrieve_query_object.htm

https://developer.salesforce.com/docs/atlas.en-us.pages.meta/pages/pages_remote_objects_limitations.htm

Regards,
Saran Kumar BVS

**Comment by vakata** [comment]
The API & demo you provided has a 100 node limit hard coded in the query, this is in NO WAY related to jsTree. The data you provide to jstree has 100 nodes in it. 

Next time - please examine the code you use more carefully.

Best regards,
Ivan

**Comment by sarankumarBVS** [comment]
It's not my code.
Those are just the links that i have referred when i faced the issue.

We have developed an Visualforce page in Salesforce.

Please let me know when we can discuss on it. I will give you an demo on this.

My skype ID : saransfdc

**Comment by vakata** [comment]
As I said - there is a hard-coded limit in the source you showed me. 

This is **NOT** a problem with jstree - thousands of developers use it, none of which complain about a 100 node limit. I wrote the lib myself, and I assure you that there is **NO LIMIT** in the source code.

I do not have time to help you fix the server-side code you are using. If you still think that this is a problem with jstree - provide a link to a demo here (preferably a jsfiddle). 

Best regards,
Ivan
