### ISSUE TITLE
Mistake in the documentation

### ISSUE THREAD

**Issue by aonez** [vakata/jstree#1478]
Just wanted to point you that one of the examples of the documentation (Setting initial state with classes) has a `</li>` duplicated, and it does not work like it is. Thanks for the great plugin :+1: 
![image](https://cloud.githubusercontent.com/assets/480163/16085131/5994a0fe-331b-11e6-89e9-b1da5abfbdd7.png)

**Comment by vakata** [comment]
Thank you for noticing.

Best regards,
Ivan
