### ISSUE TITLE
Overriding node image using css

### ISSUE THREAD

**Issue by Asken** [vakata/jstree#1482]
I'm using 3.3.0 and I'm trying to use a class. Now I can add my class using "icon": "icon-class" but there are classes overriding my class. My class is defined:

.js_tree_folder {
    background-image: url(resources/images/folder.svg);
    background-size: 16px;
}

The resulting css is this and my style is overwritten as shown by the image attached.
![2016-06-17 13_26_52-google groups](https://cloud.githubusercontent.com/assets/1590137/16185509/a180a0e6-36c4-11e6-936f-c7e9bf06bd2e.png)

**Comment by vakata** [comment]
There is no way to make the jstree selector less specific, so make sure your selector is more specific. For example go for: `.jstree .js_tree_folder` or add a container ID.

Best regards,
Ivan

**Comment by Asken** [comment]
Ah, sorry. Missed the "-default" and works now. Thanks!
