### ISSUE TITLE
contextMenu action do not update the data of _model

### ISSUE THREAD

**Issue by xiaohan2013** [vakata/jstree#1483]
my case is that 
```js
tmp.remove.action = function (data) {
	var inst = $.jstree.reference(data.reference),obj = inst.get_node(data.reference);
	$.post('/ajax/voucher/department/delete', { 'department_id' : obj.id, "_xsrf": util.getCookie("_xsrf") })
		.done(function (d) {
			d = $.parseJSON(d);
			if(d.code == 0){
				if(inst.is_selected(obj)) {
					inst.delete_node(inst.get_selected());
				}else {
					inst.delete_node(obj);
				}
				inst.refresh();
				util.msgShow("success", d.msg);
			}else{
				util.msgShow("error", d.msg);
				// inst.refresh();
			}
		})
};
```
the result is that the data of _model didn't update, still old data

**Comment by vakata** [comment]
If you supplied an object for `core.data` after calling `refresh` the tree will be restored using that object, which means the nodes you deleted are no longer deleted. 

I can't help you without seeing your full config, but I seriously doubt that `delete_node` does not work.

I am closing this until further information is provided, when you share your full config I will reopen.

Best regards,
Ivan

**Comment by xiaohan2013** [comment]
This is my full code using the jstree,
`
var treeDataCollection = this.collection;
			this.treeDataConverter(this.collection);

			treeRootNode.jstree({
				core:{
					data:this.treeData,
					themes:{
						'responsive' : false
					},
					'check_callback' : true,
				},
				'force_text':true,
				'contextmenu':{
					items:function(node){
						var tmp = $.jstree.defaults.contextmenu.items();
							tmp.create.label = "增加子部门";
							tmp.rename.label = "重命名";
							tmp.remove.label = "删除";

							tmp.remove.action = function (data) {
								var inst = $.jstree.reference(data.reference),obj = inst.get_node(data.reference);

								$.post('/ajax/voucher/department/delete', { 'department_id' : obj.id, "_xsrf": util.getCookie("_xsrf") })
									.done(function (d) {
										d = $.parseJSON(d);
										if(d.code == 0){
											if(inst.is_selected(obj)) {
												inst.delete_node(inst.get_selected());
											}else {
												inst.delete_node(obj);
											}
											inst.refresh();
											util.msgShow("success", d.msg);
										}else{
											util.msgShow("error", d.msg);
											// inst.refresh();
										}
									})
							};

							tmp.create.action = function(data){
								console.log("create action")
								var inst = $.jstree.reference(data.reference),obj = inst.get_node(data.reference);
								inst.create_node(obj, {}, "last", function (new_node) {
									setTimeout(function () { inst.edit(new_node,"新部门", function(data){

										$.post('/ajax/voucher/department/add', {'parent_id':obj.id, 'name':data.text, "_xsrf":util.getCookie("_xsrf")})
											.done(function (d) {
												d = $.parseJSON(d);
												if(d.code == 0){
													inst.set_id(data, ""+d.data);
													treeDataCollection.add(_.extend(node, {id:d.data}));
													self.parentView.departmentMappingView.refreshView();
													util.msgShow("success", d.msg);
													inst.refresh();

												}else{
													util.msgShow("error", d.msg);
													inst.refresh();
												}
											})
											.fail(function () {
												inst.refresh();
											});

									}); },0);
								});
							};

							tmp.rename.action = function(data){
								var inst = $.jstree.reference(data.reference),obj = inst.get_node(data.reference);
								inst.edit(obj, obj.text, function(data){
									var departmentId = obj.id;
									if(obj.text != obj.old){
										$.post('/ajax/voucher/department/update', { 'parent_id' : obj.parent, department_id:obj.id, 'name' : data.text, "_xsrf": util.getCookie("_xsrf") })
											.done(function (d) {
												d = $.parseJSON(d);
												if(d.code == 0){
													inst.set_id(data, departmentId);
													self.parentView.departmentMappingView.refreshView();
													util.msgShow("success", d.msg);
												}else{
													util.msgShow("error", d.msg);
												}
											})
									}
								});
							};

							return {
								create:tmp.create,
								rename:tmp.rename,
								remove:tmp.remove
							};
					}
				},
				plugins : ['state','contextmenu','wholerow']
			})
			.on('create_node.jstree', function (e, data) {})
			.on('rename_node.jstree', function (e, data) {})
			.on('delete_node.jstree', function (e, data) {
				var inst = data.instance, node = data.node,pid = data.parent;
				var node = treeDataCollection.findWhere({id:parseInt(node.id)});

				treeDataCollection.remove(node);
				self.treeDataConverter(treeDataCollection);
				self.parentView.departmentMappingView.refreshView();

				// inst.refresh();
			})
			.on('select_node.jstree', function (e, data) {
				self.parentView.departmentPeopleView.department = {
					departmentId:data.node.id,departmentName:data.node.text
				};
				self.parentView.departmentPeopleModel.fetch({data:{department_id:data.node.id}});
			})
			// .on('move_node.jstree', function (e, data) {
			// 	$.post('/ajax/voucher/department/update', { 'parent_id' : data.parent, department_id:data.node.id, 'name' : data.text, "_xsrf": util.getCookie("_xsrf") })
			// 		.done(function (d) {
			// 			d = $.parseJSON(d);
			// 			if(d.code == 0){
			// 				data.instance.refresh();
			// 				console.log(self.parentView)
			// 				util.msgShow("success", d.msg);
			// 			}else{
			// 				util.msgShow("error", d.msg);
			// 			}
			// 		})
			// })
		},
		treeDataConverter:function(collection){
		    var treeData = [];
		    var treeDataCollection = collection;
			var dataMap = _.reduce(collection.toJSON(), function(map,  node){
				var n = {
					id: node.id,
					text:node.name,
					parent_id:node.parent_id
				}
				map[n.id] = n;
				return map;
			},{})
			_.each(dataMap, function(node){
				var parent = dataMap[node.parent_id];
				if(parent){
					(parent.children || (parent.children = [])).push(node);
				}else{
					treeData.push(node)
				}
			});

			this.treeData = treeData;
		},
		treeeData:[]
`

**Comment by vakata** [comment]
I see - so my initial guess was correct - you are supplying a static object. After calling `refresh` the tree is repopulated using that static object. So nothing is lost - simply do not call `refresh` of make sure you persist the new state.

**Comment by xiaohan2013** [comment]
yes,you are right.now what should I do for the case
