### ISSUE TITLE
data attributes aren't preserved when creating child nodes

### ISSUE THREAD

**Issue by pflannery** [vakata/jstree#1484]
Example:
```
<li data-tag="123"></li>
```

When creating a child node the dataset vanishes from the parent node

**Comment by vakata** [comment]
From what I see the data attributes are preserved: https://jsfiddle.net/7mo0nk3z/7/

Please provide a demo so that I can help you. 

Best regards,
Ivan

**Comment by vakata** [comment]
I see - sorry, those will not be preserved. When using HTML to build a tree the attributes are read only once at initialization, monitoring the DOM nodes for changes will be too expensive, as jstree only keeps visible nodes in the DOM. 
You can however use the internal jstree data storage to attach data to a node (the `data` property).

Best regards,
Ivan

**Comment by pflannery** [comment]
ah ok great. 
 will try that thanks
