### ISSUE TITLE
cookies plugin was removed?

### ISSUE THREAD

**Issue by haengjin** [vakata/jstree#1485]
hi~
I want to save state using cookie.

I found jstree had cookies plugin in old version.
(https://old.jstree.com/documentation/cookies)
But I can not find api related to cookies plugin in v3.x(current version)

cookies plugin was removed?

**Comment by vakata** [comment]
Yes, state is preserved in localStorage, as it is supported in all browsers that jstree supports. You can create a custom plugin that uses cookies, based on the `state` plugin - it should be a small change, but it is not on my TODO list, I will not be adding such a plugin to the core.

Best regards,
Ivan
