### ISSUE TITLE
with rails-4 arrow does not appear

### ISSUE THREAD

**Issue by jerome-diver** [vakata/jstree#1486]
arrows for expand/collapse doesn't appear. Then the tree always stay on the initial state (open or close, depend of the state status given from data content attribution.
i try to use it with rails-4, jquery-1.11 or jquery-2 the same, and use of bootstrap.
All the other works (try add style plugin for glyphicons is working...).
How to find why this doesn't works ? what i should provide for try to target the problem and then, fix it ?

thank you.

**Comment by vakata** [comment]
Please provide a demo, the only reason for the arrows to not be shown is to have some CSS on your page that overrides the jstree icons, so I can not help you debug without a demo.
I am closing this until a demo is provided.

Best regards,
Ivan

**Comment by jerome-diver** [comment]
@vakata, i find a solution. My jstree.min.css was well on stylesheet directory, but i also needed to include the css file with "@import 'jstree.min' " from aplication.sass file.
Now works fine.
It was not from jstree, but from myself who not use well with rails-4.
Sorry and hope this could help an other one noobs like me... lol
