### ISSUE TITLE
My requirement is that when i select something it should also be show in input text (i.e in search box) like in gmail

### ISSUE THREAD

**Issue by shivamg705** [vakata/jstree#1487]
You have created awesome plugin for displaying menu in tree view with search functionality.But my requirement is that when i select something it should also be show in input text (i.e in search box) like in gmail.Is it possible or not?
I am appreciate your help and i am waiting for your reply thanks in advance.

**Comment by vakata** [comment]
You can use the built-in events:
```js
$('#your-tree').on('select_node.jstree', function (e, data) { $('#your-input').val(data.node.text); });
```

Best regards,
Ivan
