### ISSUE TITLE
Start Drag Event 

### ISSUE THREAD

**Issue by egr2** [vakata/jstree#1488]
Hello,

I need to start the drag event for a node when clicking on it. Is there a way to do that?

My Scenario looks like that: 
On each Node there should exist a button and only when clicking on that button the drag of that element should be started. This is necessary for a good user experience when using mobile devices. The Creation of that buttons inside the nodes is not that big deal but how can i start the drag?

Can you help me?
Thanks in Advance

**Comment by vakata** [comment]
Take a look at the `jstree.dnd.js` file. You need to include the DND plugin, and then in your code:
1) unbind the `mousedown touchstart` handler (using container.off(...)) 
2) attach the same code to another handler (which will listen only for drags on the drag handle)

That should do it. I will add the handle feature in jstree 4, so I am closing this for now.

Best regards,
Ivan

**Comment by egr2** [comment]
Thank you Ivan :-),

your tip helped me completely out.

No I am be able to scroll and also performing dnd on mobile devices.

Maybe this feature could be interesting for a further version of your 
articletree. So I send you a screenshot of what I meant with: "the drag 
button inside the article row".

Works really fine :-)


best regards

Stephan and the EaternGraphics Team


Am 28.06.2016 um 18:40 schrieb Ivan Bozhanov:
>
> Take a look at the |jstree.dnd.js| file. You need to include the DND 
> plugin, and then in your code:
> 1) unbind the |mousedown touchstart| handler (using container.off(...))
> 2) attach the same code to another handler (which will listen only for 
> drags on the drag handle)
>
> That should do it. I will add the handle feature in jstree 4, so I am 
> closing this for now.
>
> Best regards,
> Ivan
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/vakata/jstree/issues/1488#issuecomment-229107381>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ATQKtxGe8jHgEEjTAVF6Ge0cnNqQEWf4ks5qQU52gaJpZM4JAGBk>.
>

-- 
EasternGraphics - visualize your business

Stephan, Gasterstädt
Entwickler - pCon.basket
http://www.EasternGraphics.com
phone: +49 3677 678286
fax:   +49 3677 678250

EasternGraphics GmbH - Albert-Einstein-Strasse 1 - DE-98693 Ilmenau
Amtsgericht Jena - HRB 304052
Geschaeftsfuehrer: Volker Blankenberg, Frank Wicht, Andreas Winkler
