### ISSUE TITLE
Comment nodes are considered tree entries when loading markup.

### ISSUE THREAD

**Issue by vxsx** [vakata/jstree#1489]
When appending html data the text nodes are skipped here https://github.com/vakata/jstree/blob/master/src/jstree.js#L1377 but comment nodes are not, which leads to empty tree items created from them. Is that intentional?

I can provide a pull request with the fix if necessary.

**Comment by vakata** [comment]
That is a bug indeed. I will have a look, or if you have already fixed it - please do create a pull request.

Best regards,
Ivan
