### ISSUE TITLE
Alternate JSON syntax doesn't seem to work or documentation outdated

### ISSUE THREAD

**Issue by tom-mayer** [vakata/jstree#1494]
Hi, 

 was skipping through the jstree documentation and found an example of how to create the tree using parent relations, which is just what I needed. However I cannot get the example working. Here is a [fiddle](https://jsfiddle.net/7mo0nk3z/5/), am I doing something completely obvious wrong?

Cheers

**Comment by vakata** [comment]
You did not have the CSS loaded, here is a fixed fiddle, all I did was add the theme CSS file:
https://jsfiddle.net/7mo0nk3z/6/

**Comment by tom-mayer** [comment]
Thanks! I did have a css loaded from a cdn but it seems that wasn't the full css only a theme or something, that's why I removed it from the example.
