### ISSUE TITLE
Click an item with a duplicated id selects the last item with that id instead of the clicked one

### ISSUE THREAD

**Issue by danielefenix** [vakata/jstree#1496]
Hi vakata,

First of all, I want to thank you for your amazing and useful library.

I would like to report the following: 
> jstree version: v3.3.1

I would like to have a statically-populated tree that has two root items (their id are `root_1` and `root_2`). Each one of them has one single child and both children have the same id ( `child` )

Like this:

- `root_1`
 - `child`
- `root_2`
 - `child`

If i do the following:

1. Click on the opener of `root_1` to show its children
2. Click on `child` of `root_1`

the `child` of  `root_2` is selected instead of the clicked one, the children of `root_1` are hidden, the lateral opener of `root_1` keep showing that the children are shown.

```javascript

$("#tree").jstree({
    core: {
        data: [
            {
                "id": "root_1",
                "text": "Root 1",
                "parent": "#"
            },
            {
                "id": "root_2",
                "text": "Root 2",
                "parent": "#"
            },
            {
                "id": "child",
                "text": "Child",
                "parent": "root_1"
            },
            {
                "id": "child",
                "text": "Child",
                "parent": "root_2"
            }
        ],
    }
});

```

Does it make sense in your own opinion to take into consideration the parent item when an item is clicked to fix the described situation?

**Comment by vakata** [comment]
jstree never has and never will support duplicate IDs, the whole idea of an ID is to be unique. Make sure you do not have duplicate IDs, or leave the ID generation to jstree.

Best regards,
Ivan
