### ISSUE TITLE
Treeview in iframe : document.activeElement in IE9

### ISSUE THREAD

**Issue by warmes09** [vakata/jstree#1497]
Hi I have a error on  IE9 when I used treeview in a iframe.
https://www.tjvantoll.com/2013/08/30/bugs-with-document-activeelement-in-internet-explorer/

"Unspecified error. "

Thx

**Comment by vakata** [comment]
Can you please provide a demo, as jstree will not search for parent - it looks for the activeElement in the current document, not the parent?

**Comment by vakata** [comment]
I am closing this until a demo is provided, then I will reopen.
