### ISSUE TITLE
Firefox 47.0.1

### ISSUE THREAD

**Issue by Schuey25** [vakata/jstree#1498]
The demos no longer work in the latest version of firefox.
https://www.jstree.com/demo/

**Comment by Schuey25** [comment]
Sorry that should say version 47.0.1

**Comment by vakata** [comment]
The only demo that was broken was the filebrowser one which was broken due to invalid data. Do you see all the demos now?

**Comment by Schuey25** [comment]
Thanks for the quick response!  

All three appear to be broken in Firefox 47.0.1 when I'm using Windows 8.1

There are no javascript errors reported, I just see the loading spinner.

I just checked with a colleague who is using Widows 7 and it works for her.  I'll check around with a few more people and let you know what I find.

**Comment by vakata** [comment]
Seems related to this issue:
https://github.com/vakata/jstree/issues/1490 - it turned out to be a local problem.
