### ISSUE TITLE
Sort plugin issue

### ISSUE THREAD

**Issue by anjanavijayakrishnan** [vakata/jstree#1499]
I have implemented the jstree and it is working great. I have to implement a sort functionality to the jstree. The requirement is as below.

1)	I want to sort only the nodes in leaf level(type =  file). The node levels above should not be sorted.
2)	I have a global variable(external to tree) set with values like alphanumeric or date.
3)	When I click a button, based on the above global value the sort should work. [When I click sort and global value is alphanumeric, I want all leaf nodes which belong to different parents to sort in alphabetical order].
4)	I don’t want the global sort to be enabled.

Could you please help me on this?

**Comment by vakata** [comment]
Hi,

First of all - this is not an issue - you are simply asking for help - I'd recommend StackOverflow or the Google groups page for that.

Secondly, when you need help - please keep it to a single medium - the personal mail was more than enough. 

I already answered in an email, but here it goes again:
Take a look at the sort plugin and read the docs on the options. There is a standard JS sorting function you can set (the same return values as with Array.sort), and that function will be able to read the global state. That should do the trick.
