### ISSUE TITLE
State plugin ignoring selected information in JSON data

### ISSUE THREAD

**Issue by mubbo** [vakata/jstree#1500]
If a user deselects the selected node in the tree then naturally the state object saves the fact that there are no selected nodes.  If I then "refresh" the tree thereby retrieving the data once again from the server where the server has indicated that the node that was just deselected by the user is actually selected the state object will ignore the information in the state.

e.g.

node 1 - selected / open
  -child 1
 - child 2

user deselects node1 thereby having no selected nodes

node 1 - open
 - child1 
 - child 2

refresh the tree - all data is pulled from the server

information returned from server for node 1
node 1: {
state : { selected=true,  opened=true}
...}

The tree is refreshed with node 1 being selected for a brief moment then it is deselected...

I should mention before you think too long about it I am currently using jQuery 3.0 Alpha which may in fact be causing the problem.

Cheers,

Gary

**Comment by vakata** [comment]
Hi,

This is the way the state plugin is intended to work - it will override any selection passed from the server when restoring the client selection. 

Best regards,
Ivan
