### ISSUE TITLE
Ajax search not calling URL

### ISSUE THREAD

**Issue by idkelly** [vakata/jstree#1502]
Hi There,
JSTree is awesome.  I admittedly have troubles deciphering the documentation but have muddled my way through most of what I need with the examples and Google Search results.  I am sure it is something I am doing but I can't seem to figure out what.  I have spent a few hours looking at similar issues but haven't found a solution for my problem.  I seem to have a configuration issue where the tree is not calling the ajax search URL.  I have used firebug and looked at the server logs and my search URL is not being called.  My code for the tree is below.  What am I missing?  Thanks in advance.

```
   <script type="text/javascript">
        $(function(){
            $('#catalogTree').jstree({
                "plugins": ["themes","search"],
                "core": {
                    'multiple': false,
                    'themes':{
                        'theme':'default',
                        'dots' : false},
                    'data' : {
                        "url" : "/CatTree.asp",
						'data' : function (node) {
							return {'id': node.id };
                        },
						'dataType' : 'json'
                    },
					'search' : {
						'ajax' : {
							'url' : "/Cattest.asp"
							}
						},
					}
                });
            $('#catalogTree').on("changed.jstree", function (e, data) {
                DisplaySelectedCat(data.selected);
            });
            var to = false;
            $('#catalogTree_q').keyup(function () {
                if (to) { clearTimeout(to); }
                to = setTimeout(function () {
                    var v = $('#catalogTree_q').val();
                    $('#catalogTree').jstree(true).search(v);
                }, 250);
            });
			
        });
    </script>
```

**Comment by vakata** [comment]
The `search` config key should not be inside the `core` key, it should be on the same level as the `core` key (one level up from where it currently is).

Best regards,
Ivan

**Comment by idkelly** [comment]
Thanks! that solved the problem.
