### ISSUE TITLE
Issue with checkbox

### ISSUE THREAD

**Issue by gauravoodles** [vakata/jstree#1503]
Hi, I want that when I checked all the parent checkboxes a class should add on the body, could you help me on the same.

**Comment by vakata** [comment]
Please use the discussion group or stackoverflow for how-to questions. To the question: listen for the changed.jstree event and if all top level nodes are checked - add the class to the body, if not - remove it. Something like this:
```
$('#tree').on('changed.jstree', function () {
  if ($('#tree').find(' > ul > li > a').not('.jstree-clicked').length) {
    $('body').removeClass('all-checked');
  } else {
    $('body').addClass('all-checked');
  }
})
```
