### ISSUE TITLE
AJAX Search hitting URL but results not found

### ISSUE THREAD

**Issue by idkelly** [vakata/jstree#1504]
Thanks for your previous help getting the search to go to the server.  The fixed code is:

```
<script type="text/javascript">
        $(function(){
            $('#catalogTree').jstree({
                "plugins": ["themes","search"],
                "core": {
                    'multiple': false,
                    'themes':{
                        'theme':'default',
                        'dots' : false},
                    'data' : {
                        "url" : "/CatTree.asp",
						'data' : function (node) {
							return {'id': node.id };
                        },
						'dataType' : 'json'
						},
					},
				'search' : {
					'ajax' : {
						'url' : "/Cattest.asp",
						'dataType' : 'json',
						'method' : 'GET',
						},
					},
					
                });
            $('#catalogTree').on("changed.jstree", function (e, data) {
                DisplaySelectedCat(data.selected);
            });
            var to = false;
            $('#catalogTree_q').keyup(function () {
                if (to) { clearTimeout(to); }
                to = setTimeout(function () {
                    var v = $('#catalogTree_q').val();
                    $('#catalogTree').jstree(true).search(v);
                }, 250);
            });
			
        });
    </script>
```
The "cattest.asp" file returns the following:
`["102"]`

I have also tried:
```
[
    {
        "id": "102"
    }
]
```

when cattree.asp is called with an ID of 102 it returns:
```
[{
	"id": "P1730",
	"parent": "102",
	"text": "SEN00510 - BOX,SAFE,KEY/LOCK,11 13/16X9.25X3 9/16\",BLK",
	"children": false
},
{
	"id": "P1731",
	"parent": "102",
	"text": "SEN00496 - BOX,SAFE,KEY/LOCK,11 13/16X9.25X3 5/8\",BLK",
	"children": false
},
{
	"id": "P1732",
	"parent": "102",
	"text": "SEN01879 - BOX,CASH,DRAWERSAFE,KEY/LOCK.7\",BLK",
	"children": false
}]
```

So if I understand the AJAX search correctly, the above nodes should be loaded into the tree and then the searched (on the client side) for the text that is entered.  I have tried typing in a number of different strings in the "text" attribute from the above and nothing is matched.  Should the search not also call my "cattree.asp" with a parameter of 102 to load those nodes so they can be searched?  There is no evidence of that happening when I use both Firebug and check the server logs.  What am I missing?  Thanks in advance.
Ian

**Comment by vakata** [comment]
Please provide a full demo, I can not help you like this - I do not have the full information to debug. All I can do is assure you that the above functionality works properly and the steps that jstree will take for searching in a lazy loaded tree are:
1) It will hit the server with the search string, you are expected to return AN ARRAY with each parent ID that needs to be opened to reveal the results. Which means that if the user searches for Passat, and you have 0-Cars -> 1-Volkswagen -> 3-Passat you need to return `["1","2"]`
2) jsTree will load all the needed parents (but only if they are not already loaded)
3) after loading is completed jstree will perform a client-side search on the tree and will highlight the matches (you can affect the results using `search_callback`)

Best regards,
Ivan

**Comment by idkelly** [comment]
Thank you, I got it working.  The part that I was missing was the piece about returning ALL the parents back to the root of the tree.  I was only returning the immediate parent.
Take Care
Ian

**Comment by apprehensive-reactcsstra** [comment]
https://xslt-follow-up.github.io/Sz2OKQ373gpMHEGTXOnYZFBv45CNAnaTtbY/



I resolved the dilemma
