### ISSUE TITLE
Drag and Drop is not working using move_node event

### ISSUE THREAD

**Issue by sreenivasa123** [vakata/jstree#1505]
Hi,

1. The drag and drop is not working within jstree div. As the selected node is showing outside the jstree div/area.
2. When we select any node and click on mouse right click we are showing create, rename, delete, etc. if we want to cancel this small popup clicking on the jstree is not going away

Below is the  code snippet:
 ```
'plugins': [
                    "contextmenu", "dnd", /*"search",*/ "types", "themes"
                ],

 $("#jstreeID").bind("move_node.jstree", function (e, data) {
...............
...............
}
```

**Comment by sreenivasa123** [comment]
Please see the attached screenshot
![outsidejstree](https://cloud.githubusercontent.com/assets/20420377/16768660/d27d8c22-4862-11e6-9b9a-f3446b9fc0b7.png)

**Comment by sreenivasa123** [comment]
when we select any node within in jstree its not showing the selected, when we moive the cursor out of the div/widget its showing like that. And also its not allowed to drop in any other node witnin User links.  Earlier its worked fine. All of sudden its not working . I am suspecting jstree version. Today i udpated jstree 3.* version

**Comment by vakata** [comment]
Sorry, I can't help you without a demo of the problem - can you provide a jsFiddle? My guess is you are in quirksmode, or in IE compatibility mode (which are both not supported by jstree). 

I will reopen on more info. Please provide a demo and information about the browser you are using. I can assure you a basic feature such as selection works properly.

Best regards,
Ivan

**Comment by sreenivasa123** [comment]
i am using chrome browser. Right now i dont have something in fiddle for handy. when we select any node in jstree the move_node event is not triggering. before 2 months back its worked fine without any issues.

**Comment by vakata** [comment]
Selecting a node should not trigger a move event. I am not sure what you mean. Once again - I can't help you without a demo.
