### ISSUE TITLE
dnd, how to restrict dropping to certain node types?

### ISSUE THREAD

**Issue by OscarMC** [vakata/jstree#1508]
I need to restrict dropping to certain node types, but I find no way to get it, searching over the internet I found this: 

[http://goo.gl/mPfwHG](url)

I'm interested on **izmaxx**'s comment about this post [http://stackoverflow.com/a/23486435](url)

There'is any way to do this?

Thanks is advance!!

**Comment by vakata** [comment]
It is all in the docs - use the `valid_children` option of the types plugin.
