### ISSUE TITLE
How to get the target ID when dropping a foreign element?

### ISSUE THREAD

**Issue by apasho** [vakata/jstree#1510]
I have jsTree configured like so:

jQuery(document).ready(function(){      
        var treeMain = jQuery('#folder-tree').jstree({ 'core' : 
        {
            'data' : folders,
        },
        'force_text' : true,
        'themes' : {
            'responsive' : false,
            'variant' : 'small',
            'stripes' : true
        },      
        'types' : {
            'default' : { 'icon' : 'folder' }
    },
    'sort' : function(a, b) {
        return this.get_type(a) === this.get_type(b) ? (this.get_text(a) > this.get_text(b) ? 1 : -1) : (this.get_type(a) >= this.get_type(b) ? 1 : -1);
    },      
    'plugins' : [ 'sort','types' ]
 });

This code allows an HTML element, which is not a part of the tree, to be dropped into a node:

    jQuery('#folder-tree').droppable( {
            accept: 'li a.media-attachment',
            hoverClass: 'droppable-hover',
            drop: handleTreeDropEvent
    });

This function will process the drop event:

function handleTreeDropEvent(event, ui ) {

}

What do I do in handleTreeDropEvent to get the ID of the target node of the drop event? Also, is there a better way to define droppable target element? It does not work using the jstree-anchor class.

**Comment by vakata** [comment]
To check the ID of the element refer to jQuery UI and the droppable documentation - I can not help you with that. 

jsTree provides its own way of dropping elements, here is the code: https://groups.google.com/forum/#!topic/jstree/BYppISuCFRE

That does not mean hooking up droppable is not possible, but you need to refer to their docs.

Best regards,
Ivan

**Comment by apasho** [comment]
The problem with using the DND plugin is that it allows nodes to be moved which I don't want that to happen. Is there a way to totally stop node dragging when DND is in use?

**Comment by apasho** [comment]
Following Ivan's advice I was able to get the ID of the node:

function handleTreeDropEvent(event, ui ) {		
	var target = event.target || event.srcElement;
	var node_id = $(target).attr("aria-activedescendant");	
        ...
}

**Comment by vakata** [comment]
To totally stop dragging use the is_draggable callback in dnd settings, and always return false from it.
