### ISSUE TITLE
Unable to add data-candelete option on newly created node.

### ISSUE THREAD

**Issue by cygnetayjaha** [vakata/jstree#1514]
Hello,

I have tried to add new param "data-candelete" on newly created node to remove newly created category on fly, but it seems not working.

I tried with following code.

var inst = jQuery.jstree.reference(data.reference),
obj  = inst.get_node(data.reference);
inst.create_node(obj, { "text": defaultNodeName, 'data-candelete ': true }, "last", function (new_node)
	{

setTimeout(function () { inst.edit(new_node); },0);
});

Can you quick suggest.

**Comment by vakata** [comment]
Please read the docs on the node format. There is no `data-candelete` property in the format. Take a look at the `li_attr`, `a_attr` and `data` docs (on the homepage of this repo).

**Comment by cygnetayjaha** [comment]
Can You please guide how to allow delete node that is just created recently.

**Comment by vakata** [comment]
Please read the docs on `check_callback`, your question is answered on jstree.com's homepage, as well as the API section, as well as this repo's homepage.

Best regards,
Ivan
