### ISSUE TITLE
The state property of ._model.data does not have an undetermined option

### ISSUE THREAD

**Issue by vincentwansink** [vakata/jstree#1516]
I'm generating an SQL update statement by iterating through a serialized string of values from the tree view.  This is how I generate that string:

```
var treedata = $('#securityprofile_tree_div').jstree()._model.data;
  // Build serialized string from tree data
  for(var nodename in treedata){
    if(nodename != '#' && nodename != '__proto__'){
      var nodevalue = treedata[nodename].state.selected ? 'Y' : 'N';
      serialized += nodename + '=' + nodevalue + '&';
    }
  }
```
Unfortunately, undetermined nodes are not "selected" so they end up with an "N" value, though I need them to be "Y".  There doesn't seem to be any way to determine if a node is "undetermined" as the only states I see are disabled, loaded, opened and selected.

What's the trick here?  Is there a better way to generate a serialized string?

**Comment by vakata** [comment]
`_model.data` is internal, as such - use with caution. As for undetermined - it is not stored as state, but calculated on demand. You can either use this function: https://www.jstree.com/api/#/?q=undetermined&f=is_undetermined(obj) or check its source to see how it is calculated.

Best regards,
Ivan
