### ISSUE TITLE
checkbox, how to do, choose the child nodes, do not automatically selected parent?

### ISSUE THREAD

**Issue by keeleys** [vakata/jstree#1522]
tree,checkbox, how to do, choose the child nodes, do not automatically selected parent?

**Comment by aadrian** [comment]
https://www.jstree.com/api/#/?q=$.jstree.defaults.checkbox&f=$.jstree.defaults.checkbox.cascade

**Comment by vakata** [comment]
As @aadrian pointed out - read the docs.
