### ISSUE TITLE
can't use checkboxes inside <li>

### ISSUE THREAD

**Issue by LeonardoChirivi** [vakata/jstree#1524]
Hello, I'm having a problem with the tree, it looks something like this:
```
<ul>elements
	<li>
	    <input type="checkbox"> 123 (ABC456DE)
	</li>
	<li>
	    <input type="checkbox"> 123 (ABC456DE)
       </li>
</ul>
```

But I'can't check the inputs in the browser for some reason. Is there something wrong??
Thanks in advance for the help.

**Comment by LeonardoChirivi** [comment]
```html
<ul>elements
	<li>
	    <input type="checkbox"> 123 (ABC456DE)
	</li>
	<li>
		<input type="checkbox"> 123 (ABC456DE)
	</li>
</ul>
```

Here is the code. sorry!

**Comment by vakata** [comment]
jsTree has its own checkbox plugin - you are welcome to use that.
You can also add real checkboxes using this plugin:
https://github.com/vakata/jstree/blob/master/src/misc.js#L65)

having clickable elements inside the nodes will not work unless you add event handlers as jsTree captures most events which fire on the node.

Best regards,
Ivan

**Comment by LeonardoChirivi** [comment]
Thanks for the reply, I've used jsTree own checkboxes and it seems to work.
Just one question, if I click the root node can I get just the values between <li> tags? 
My web app needs to do so..

**Comment by LeonardoChirivi** [comment]
```html
<li>
```
tags sorry
