### ISSUE TITLE
[BUG] Rename node text input messes up character encoding

### ISSUE THREAD

**Issue by temuri416** [vakata/jstree#1525]
Hi Ivan,

Looks like there's a new bug.

http://jsfiddle.net/7b05o9qt/3/

1. Right-click "Node1", click "Rename"
2. Type "<>", click away - node will get renamed
3. Right-click "<>" again and click "Rename"
4. You will see this:

![image](https://cloud.githubusercontent.com/assets/3987203/17310139/8e8e27a2-5810-11e6-84df-06ed13e9cff7.png)

That's using 3.3.1 version, but the issue isn't there in 3.0.x.

Thanks!

**Comment by vakata** [comment]
This is because of the escaping which prevents XSS attacks from happening (since jsTree allows the users to input HTML in the nodes). If you want the above example to work - disable HTML input:
http://jsfiddle.net/7b05o9qt/4/

Best regards,
Ivan

**Comment by temuri416** [comment]
Yes, I know about `force_text` flag. But I have a scenario where I use HTML in node names - I'm adding children count: `Node A <small title="This node has 6 children">(6)</small>` AND I allow users to rename them.

Is there any chance that you'd decode entities before setting value of rename text input?

Thanks!
