### ISSUE TITLE
JSFiddles with all examples and links

### ISSUE THREAD

**Issue by aadrian** [vakata/jstree#1526]
It would be really helpful if there were JSFiddles for all the examples (and links from the example pages).

The users could give the dev team a much faster and more precise feedback.
Since it's easy to just clone an existing fiddle, it would be easier to enforce fiddles as test cases for most errors reported by users.

This reduces greatly the required time to pinpoint and fix problems.

Thank you.

**Comment by vakata** [comment]
Check the homepage of this repo - each point has a jsFiddle :)

**Comment by aadrian** [comment]
> Check the homepage of this repo - each point has a jsFiddle :)

That's nice, but I was using the jstree.com since it's nicer styled :).

**Comment by aadrian** [comment]
> each point has a jsFiddle :)

They don't use all the latest officially released version of jstree.

**Comment by aadrian** [comment]
Please use this http://doc.jsfiddle.net/use/github.html to be able to keep the fiddles updated.

**Comment by vakata** [comment]
Thanks for the tip - I will update with the next version.
