### ISSUE TITLE
set_type does not update a_attr title

### ISSUE THREAD

**Issue by iled** [vakata/jstree#1527]
Ivan, thank you for this amazing plugin.

I'm not sure this issue is in jstree scope.

Consider a tree where a child node has a tooltip defined with the `a_attr.title` attribute.

```javascript
"data": [{
        "text": "Root node",
        "state": {
          "opened": true
        },
        "icon": "fa fa-circle",
        "children": [{
          "id": "c1",
          "text": "Child node 1",
          "state": {
            "selected": true
          },
          "a_attr": {
            "title": "1"
          }
          // "type": "no"
        }]
```

Later, if we change the type of the node to a type that has a different `a_attr.title`, it will not change.

```javascript
"types": {
      "no": {
        "icon": "fa fa-ban",
        "a_attr": {
          "title": "no!"
        }
      }
    }
```

The same happens when the type is directly set in node object (commented line).

Is this a feature or a bug? How to workaround this and change an already existing `a_attr.title`?

Please check [this working example](https://jsfiddle.net/hd4pcttg/2/)

**Comment by vakata** [comment]
The type property will never overwrite an "inline" property - in your case - the title is set from the node data, that is why it is not updating. Check this fiddle - it will first be `no`, and then `yes` after the type change: https://jsfiddle.net/hd4pcttg/4/

**Comment by iled** [comment]
Thank you for your fast reply.

I understand that your solution is to avoid setting  property directly in the node definition.

In my case, the `a_attr` is different for every node, and it is built using some metadata (stored in `node.data`). That is why it is set as *inline*.

So I still have the same question:

How to change a property when it is defined in the node (it doesn't have to be through `set_type`)? Perhaps reconstructing the node is the only solution?

**Comment by vakata** [comment]
No, simply change the property like so:
```
var instance = $('#tree').jstree(true);
instance.get_node("c1").a_attr.title = "New title";
```
If you need the new title to visible immediately you can also update it in the DOM:
```
var dom = instance.get_node("c1", true);
if (dom && dom.length) {
  dom.children('.jstree-anchor').attr('title', 'New title');
}
```

Best regards,
Ivan

**Comment by iled** [comment]
Thank you so much, Ivan!

I was missing the update in the DOM.

Best regards
