### ISSUE TITLE
Adding icons to node based on json data

### ISSUE THREAD

**Issue by aswa12** [vakata/jstree#1529]
Hi,

I was trying to add custom icons based on the node type from my json data. Here's the fiddle that I'm working on: https://jsfiddle.net/sreedevi/h2y6aLk1/

The code seems to work only when I change ctype to type in my json, and remove the ctype from types list. Does jstree accept only 'type'? Can I not give any custom name ?

Types:
```
            'types': {
            	'ctype': {
              	"folder": {
                    "icon": "jstree-icon jstree-folder"
                },
                "file": {
                    "icon": "jstree-icon jstree-file"
                }
              }


            }
```

JSON:
```
[{"id":"cb70bc8b-dcde-4c54-b69e-6cc331212cf1",
  "text":"Internal Reports",
  "ctype":"folder",
  "state":{"opened":true,"selected":false,},
  "children":
    [{"id":"7eac0622-f915-40b0-bb8b-00bf8fbe55a9",
      "text":"Client Service Center",
      "ctype":"folder",
      "state":{"opened":true,"selected":false,},
      "children":
        [{"id":"6a5a9552-f021-472e-b166-ff1ef4e00328",
          "text":"Navigator Report",
          "ctype":"file",
          "state":{"opened":false,"selected":false}
        }]
    }]
}]
```
I'm new to jstree. Sorry if this is something very basic.
Thanks in advance.

**Comment by vakata** [comment]
Please read the docs on the types plugin (or have a look at the examples). It seems to me you are trying to add a "subtype". There are no separate folder / file icons. Use `type : "file"` or `type : "folder"`, and in the `types` config options specify only `file` and `folder` (no wrapping `ctype`).

**Comment by aadrian** [comment]
> Please read the docs on the types plugin (or have a look at the examples). 

The problem seems to be that the two "groups" of icons (from the type definition and from the data) are not merged but overriden :(.

E.g. if I have in the type plug-in definition for a specific type ```"icon": "cls1 cls2"```, and in the data for that node only for the very few (that are of the same type, but have an exception, e.g. need a color style to color the icons), ```"icon": "warn"```, than the rendered node's class for icon will be ```"warn"``` instead of ```"cls1 cls2 warn"```.

**Comment by vakata** [comment]
Of course - it was never the idea to have icons "stack" on top of eachother. Sorry, this is exactly how the types plugin is supposed to work.

**Comment by aadrian** [comment]
> it was never the idea to have icons "stack" on top of eachother.

Not "icon stacks" but more classes that build up the final appearance of an icon. With many icon libraries one class is required to create an "icon appearance". E.g. Font Awesome needs even more: http://fontawesome.io/examples/

> Sorry, this is exactly how the types plugin is supposed to work.

IMHO this is buggy and the class attributes should be merged, not overriden. I understand that there are other properties where override makes sense (e.g. titles, or other non-additive properties), but styling shouldn't be one.

**Comment by vakata** [comment]
The only idea that comes to mind is a more complex types plugin for v.4. There should be a way to specify if a given property should be merged or overridden.
