### ISSUE TITLE
Include a Bootstrap theme too.

### ISSUE THREAD

**Issue by aadrian** [vakata/jstree#1530]
Please include a Twitter Bootstrap theme with jstree in the distribution.

There's one: https://github.com/orangehill/jstree-bootstrap-theme/
but it's always out of sync with jstree (since jstree has a much faster development) :(.

Thank you.

**Comment by vakata** [comment]
Sorry, I will not be maintaining framework specific themes - that is something I tried in the past, and will not do with this version of jstree. 

Currently building themes is:
 * very easy (create a less file with a few variables and build)
 * jstree inherits the document's CSS
 * icon-fonts are supported and trivial to use. 

Given that information a bootstrap theme should be easy to achieve.

Best regards,
Ivan

**Comment by aadrian** [comment]
> I will not be maintaining framework specific themes - that is something I tried in the past, and will not do with this version of jstree. 

There are many possible themes so this is very understandable. 
Twitter Bootstrap is however the most popular one by a big margin. Many JS Components offer a bootstrap theme that is actual in order to boost adoption.

> Given that information a bootstrap theme should be easy to achieve.

Sorry but it is not. Just look at the theme I've linked (proton) and see how "not simple" it is, and how easily does break jstree functionality because it gets out of sync or it was buggy in the first place (since it's not simple). With that theme active, editing is not working correctly,  drag and drop is also buggy, etc.

**Comment by vakata** [comment]
OK, even so - I do not want to couple jstree with bootstrap in anyway, and as soon as I provide a bootstrap theme request for a semantic theme and a pure theme will fly in. I prefer to give a healthy theme system and not to maintain many themes (as was the case with v.1).

To the point - a bootstrap theme can mean many things. For me - inheriting the line-height, font style and using the glyphicons is enough, and that is doable by just setting the proper icons and a few variables in the less file - that is what I mean by easy. Trying to use bootstrap classes and containers on jstree will not render good results - jstree is not part of the bootstrap framework so using the bootstrap classes will not render good results.

**Comment by aadrian** [comment]
>  as soon as I provide a bootstrap theme requests for a foundation, semantic, pure, etc themes will fly in.

If you would provide a bootstrap theme that is easy to understand and be used as a starting point, the users would make themselves themes for the other frameworks too (usually if something exists for Boostrap, it's quickly copied by the others). 

> I prefer to give a healthy theme system and not to maintain many themes (as was the case with v.1).

It his however not "healthy" at all IMO - there are no other themes for JSTree besides the one I mentioned above :) .

> To the point - a bootstrap theme can mean many things. 

For most users a (Twitter) theme means just this: https://github.com/orangehill/jstree-bootstrap-theme - something that one can simply just include in a project and it's using the standard boostrap styles and dimensions, and it does not break other parts of the UI.

Unfortunately the author of that theme seems to have abandoned it and it's also not merging the PRs.

> inheriting the line-height, font style and using the glyphicons is enough, and that is doable by just setting the proper icons and a few variables in the less file - that is what I mean by easy

It's really not, and jstree it's always visible that it does not look and behave like the other parts of an application unfortunately.
What it's easy however is to just include a CSS (like the one above) and have everything behave and look like it would be part of the same application :) .

**Comment by vakata** [comment]
I will consider this for v.4 which approaches rendering very differently, so theme creation should be a lot easier.
