### ISSUE TITLE
Checkboxes 

### ISSUE THREAD

**Issue by LeonardoChirivi** [vakata/jstree#1531]
Hello, I've used jsTree own checkboxes and they work fine. But i need to have check boxes just on the children nodes, not the roots, is there a way to do so?

**Comment by aadrian** [comment]
to those nodes that don't need the checkbox, use the ```"class":"no_checkbox"``` style in the ```"a_attr":{}``` property.

**Comment by vakata** [comment]
Exactly - you can hide the checkboxes using regular CSS - inspect the checkbox elements and add some CSS to hide them.
