### ISSUE TITLE
search ajax url function not working

### ISSUE THREAD

**Issue by biliboc** [vakata/jstree#1533]
I have this setting:

```
'search': {
		        'show_only_matches': true,
		        'ajax': {
		            'url': function(node){
		            	return GOLD_REST_ENDPOINT + "/rec/by-run/" + node.original.payload.id + "/search";
		            },
		        	'dataType': 'json',
		            'type': 'GET'
		        }
		    }
```
but when I invoke the url is as if the function definition has been transformed to string instead of being invoked to get its returned value.

**Comment by vakata** [comment]
Setting `url` to a function is not supported. You can set `search.ajax` itself to a function, as stated in the API docs: https://www.jstree.com/api/#/?q=search&f=$.jstree.defaults.search.ajax
