### ISSUE TITLE
Issue with json file using url.

### ISSUE THREAD

**Issue by gauravoodles** [vakata/jstree#1534]
Hi,
I'm facing an issue, like if I use json data on html page js tree works proper, but when I use url to import json file the tree stops  rendering. So could you please help me on the same where I'm doing wrong.
```
$('#data').jstree({
    'core' : {
        'data' : {
            'url':'treegrid-data.json',
        }
    }
});
```

**Comment by vakata** [comment]
Please make sure:
1) you are using the tree from a web server (not from the file system, as that would cause the AJAX request to fail in most browsers)
2) the file is really there (check your console / network tab for errors)
3) the data in the file is valid JSON (use a JSON validation service)
4) the data in the file is in the format expected by jstree

I can assure you this is not a jstree issue.

Best regards,
Ivan
