### ISSUE TITLE
vakata-dnd on modal.

### ISSUE THREAD

**Issue by poliam** [vakata/jstree#1536]
Hi I have a problem using jstree in a modal. I have used your plugin dnd, and for some reason the vakata-dnd is appending onto the body of the html. The result is that the selected node being dragged shows up behind the modal.  Is there a way I could make it append onto a specific div or tag in html?  

Or, is there an easier way to use dnd on a modal? Thanks!

**Comment by vakata** [comment]
This has been answered many times. If there is a problem with z-index in your layout please make sure that the `#jstree-dnd` and `#jstree-markers` have a high enough z-index that suits your needs (which means - add a rule in your CSS for those elements and adjust their z-index accordingly).

Best regards,
Ivan
