### ISSUE TITLE
Firefox Error

### ISSUE THREAD

**Issue by RicoLiu** [vakata/jstree#1538]
![qq 20160812112349](https://cloud.githubusercontent.com/assets/12722992/17612019/4402100a-607f-11e6-9d20-3d97213a4d23.png)
![qq 20160812112340](https://cloud.githubusercontent.com/assets/12722992/17612030/6b7444be-607f-11e6-8018-4aa43898ca61.png)
In Firefox,
I encountered this problem, HTTP Request is ok.
but dont appear. Always appear gif. 
But Chrome is ok.
Why?

**Comment by vakata** [comment]
I can't help without the actual data you return. I can assure you it is not a problem with jstree, but just to be sure - can you provide a demo - a jsfiddle perhaps?
I will reopen when more information is provided.
