### ISSUE TITLE
Reload children 

### ISSUE THREAD

**Issue by aswa12** [vakata/jstree#1543]
Hi,

I have a lazy loading tree. I'm unable to reload the children on expanding a node again.
Is there any way of achieving this functionality?

Many Thanks.
```
$('#container').jstree({
        'core' : {
          "animation" : 0,
          "check_callback" : true,
          'data' : {
  			url: function (node) {
                  return node.id === '#' ? 'api/configtree'
                                         : 'api/configtree/getchildren?id=' + node.id;
                }
            }
        } });
```

**Comment by vakata** [comment]
No, there is no way to `unload` children, you can however use `refresh(node)` to refresh a given node when it is about to be opened. You can also try fiddling with the internal jstree properties on `closed.jstree` (removing all child nodes and setting the `children` property to `true`), but I would not recommend that.
