### ISSUE TITLE
Disable all keyboard shortcuts (such as F2)

### ISSUE THREAD

**Issue by bs-thomas** [vakata/jstree#1546]
I have a tree instance, which I want to disable all browser-based modifications on it.  I have used "check_callback" to disable all actions already, which is great.

However, I'm unable to disable the F2 keyboard shortcut, or any other keyboard shortcuts (if there are any I didn't know of).  When I press F2 on a selected node, the node item still gets changed into an <input> field, though I know it won't get saved because I have prevented it via "check_callback"

Is there any way of completing disabling the keyboard shortcuts, so that it won't even have a change to change to an <input text field?

Your help is greatly appreciated.

**Comment by bs-thomas** [comment]
Oh and just to add, I did read one of your previous issues regarding on keydown.jstree,  and tried to return false in that callback, but seemed like there wasn't any effect.

Thanks!!

**Comment by vakata** [comment]
You should set `check_callback` to boolean `false` (or do not set it at all) - that way the rename input won't be shown. Or you can `.off` the keydown event on the tree container.

**Comment by Llorx** [comment]
Reopening. This will also disable editing the tree elsewhere when I just want to block F2.

Also, offing the `keydown` event will unbind all other shortcuts too.

**Comment by ltoledozt** [comment]
I'm having the same problem.

I'd like to be able to disable just the F2 key. 
I don't wanna lose the features where I can "edit" the tree neither lose all others key shortcuts.

Could you reopen the case, please?

**Comment by vakata** [comment]
The only thing I can think of is remove the f2 binding all together. Otherwise I would have to create several config options, which is not desired.
How does that sound? Any ideas?

**Comment by s--g** [comment]
> remove the f2 binding all together, and if anyone wants it - they will have to manually create a listener

I support this suggestion
