### ISSUE TITLE
types li_attr issue

### ISSUE THREAD

**Issue by blowsie** [vakata/jstree#1547]
Hello, great plugin :+1: 

I think I have found an issue with the types plugin and the `li_attr` configuration, or  perhaps the documentation is unclear.

When i define `li_attr`s in the data, they work as expected, but when i define `li_attr`s in the `type` configuration it does not work.

I have followed the documentation and created a super simple example of the issue here.
http://jsfiddle.net/DGAF4/1518/

**Comment by aadrian** [comment]
@blowsie that example fiddle of yours is using a very old version of JSTree (since 3.0.4 there are at least 10 new releases), so maybe the issue is already fixed (or is even worse :) ) ?

**Comment by vakata** [comment]
The feature you are trying to use was added in v.3.3.0

**Comment by blowsie** [comment]
Perhaps its a good idea to update the site / git / documentation with the latest version, especially as the docs mentions this feature but says to use 3.2.1
