### ISSUE TITLE
Database demo seems to select wrong node?

### ISSUE THREAD

**Issue by tollus** [vakata/jstree#1549]
When selecting a node, `/ESPNs/peelelg/p` it thinks the selected node is `/ESPNs/peelelg/New node/p`

Hopefully the screenshot will work:
![image](https://cloud.githubusercontent.com/assets/1820386/17866326/22d386e6-6874-11e6-9603-410148b0d9a2.png)

**Comment by vakata** [comment]
This is a bug with the underlying PHP classes, which are not part of jstree and are not supported. It is not a jsTree problem, I will rebuild the database tomorrow.
