### ISSUE TITLE
Single clicking on an expanded parent results in freezing browser

### ISSUE THREAD

**Issue by rasoulabbasi20n** [vakata/jstree#1550]
Hi, I'm using jstree 3.3.2 and Chrome as browser. I encountered an issue. I don't know what's the cause. 
I fill the data with ajax, and data structure of nodes from server is like this:

```
Node{
bool isLeaf, 
List<Node> children,
string text,
Guid id,
}
```
 After expanding parents, double clicking on them make browser freeze. 
I tested this scenario with static list of nodes in client side and it was OK, no problem was seen. 
I checked open_node, before_open, after_open events but the debugger won't go in there. It means before even these events fire, the problem arises.
Any clue ?

**Comment by aadrian** [comment]
without a working JSFiddle or some GitHub example that can be tried out directly, is quite hard to reproduce your problem :).

**Comment by rasoulabbasi20n** [comment]
Yes, unfortunately I'm working in a strict company :D I couldn't simulate the condition in  jsfiddle yet but I'm working on it. That aside, I found that it's not the double click, it's single click on expanded parents. I'll keep working on simulating the situation.

**Comment by rasoulabbasi20n** [comment]
I tested this with Firefox , it goes 'not responding' and then showed 'stop jstree.min.js script" message.

**Comment by aadrian** [comment]
> I couldn't simulate the condition in jsfiddle yet but I'm working on it. 

It must not be jsfiddle (since dynamic stuff is more complicated to simulate) but any simple example that the developers can simply run and see the effect: something they can just check-out from GitHub and run.

**Comment by rasoulabbasi20n** [comment]
The problem solved! I had done some manipulation in success call back which was the problem. But still I don't what was wrong.
