### ISSUE TITLE
"wholerow" plugin is not work right.

### ISSUE THREAD

**Issue by tiandian** [vakata/jstree#1551]
When use the "wholerow" plugin, the tree nodes show right, but not work as windows's treeview control.

In windows, when double click any position of the whole tree node, the tree node can expand/collapse, 
but  when use the "wholerow" plugin,  we must double click on the tree node text to expand/collapse the node, double click other position will not expand/collapse the tree  node.

Thanks!

**Comment by aadrian** [comment]
with the "checkbox" plug-in, the effect is even worse: when double-click on the name, for a node that has children, where only some are checked, the values of those checkboxes are lost: this is totally an unexpected behavior.

@tiandian the effect you describe seems correct, but only for desktop mode. In tablet (touch interaction) most users expect something else.
