### ISSUE TITLE
How to find out if all child node of parent node are selected in jstree ?

### ISSUE THREAD

**Issue by sunny-srivastava** [vakata/jstree#1552]
I am working on a jstree. Here is my sample code 

var data1 = [{
	"id":1,
	"text":"C",
	"size":"",
	"date":"02/19/2010",
	"children":[{
		"id":2,
		"text":"Program Files",
		"size":"120 MB",
		"date":"03/20/2010",
		"children":[{
			"id":21,
			"text":"Java",
			"size":"",
			"date":"01/13/2010",
			"state":"closed",
			"children":[{
				"id":211,
				"text":"java.exe",
				"size":"142 KB",
				"date":"01/13/2010"
			},{
				"id":212,
				"text":"jawt.dll",
				"size":"5 KB",
				"date":"01/13/2010"
			}]
		},{
			"id":22,
			"text":"MySQL",
			"size":"",
			"date":"01/13/2010",
			"state":"closed",
			"children":[{
				"id":221,
				"text":"my.ini",
				"size":"10 KB",
				"date":"02/26/2009"
			},{
				"id":222,
				"text":"my-huge.ini",
				"size":"5 KB",
				"date":"02/26/2009"
			},{
				"id":223,
				"text":"my-large.ini",
				"size":"5 KB",
				"date":"02/26/2009"
			}]
		}]
	},{
		"id":3,
		"text":"eclipse",
		"size":"",
		"date":"01/20/2010",
		"children":[{
			"id":31,
			"text":"eclipse.exe",
			"size":"56 KB",
			"date":"05/19/2009"
		},{
			"id":32,
			"text":"eclipse.ini",
			"size":"1 KB",
			"date":"04/20/2010"
		},{
			"id":33,
			"text":"notice.html",
			"size":"7 KB",
			"date":"03/17/2005"
		}]
	}]
},{
	"id":4,
	"text":"Grails",
	"size":"",
	"date":"02/19/2010",
	"children":[{
		"id":5,
		"text":"Program Files",
		"size":"120 MB",
		"date":"03/20/2010",
		"children":[{
			"id":51,
			"text":"groovy",
			"size":"",
			"date":"01/13/2010",
			"state":"closed",
			"children":[{
				"id":511,
				"text":"java.exe",
				"size":"142 KB",
				"date":"01/13/2010"
			},{
				"id":512,
				"text":"jawt.dll",
				"size":"5 KB",
				"date":"01/13/2010"
			}]
		},{
			"id":52,
			"text":"MySQL",
			"size":"",
			"date":"01/13/2010",
			"state":"closed",
			"children":[{
				"id":521,
				"text":"my.ini",
				"size":"10 KB",
				"date":"02/26/2009"
			},{
				"id":522,
				"text":"my-huge.ini",
				"size":"5 KB",
				"date":"02/26/2009"
			},{
				"id":523,
				"text":"my-large.ini",
				"size":"5 KB",
				"date":"02/26/2009"
			}]
		}]
	},{
		"id":6,
		"text":"eclipse",
		"size":"",
		"date":"01/20/2010",
		"children":[{
			"id":61,
			"text":"eclipse.exe",
			"size":"56 KB",
			"date":"05/19/2009"
		},{
			"id":62,
			"text":"eclipse.ini",
			"size":"1 KB",
			"date":"04/20/2010"
		},{
			"id":63,
			"text":"notice.html",
			"size":"7 KB",
			"date":"03/17/2005"
		}]
	}]
}]

$('#data').jstree({ 
    core: {
      data: data1, 
      check_callback: false
    }, 
    checkbox: {       
     
      whole_node : false,
      tie_selection : false 
    },
    plugins: ['checkbox','search']
})

Now I want to find out that if all child node of a parent node is selected or not .
I am using this event.
$("#data").on('check_node.jstree.jstree', function(e, data) {   //some logic here });

**Comment by aadrian** [comment]
@sunny-srivastava selected or checked? (these are two different things, both possible)

**Comment by sunny-srivastava** [comment]
checked.

**Comment by aadrian** [comment]
See example: http://jsfiddle.net/2kwkh2uL/4540/

**Comment by sunny-srivastava** [comment]
This solution works fine when you are using 'changed.jstree' not when you are using 'check_node.jstree'.
As I have whole_node and tie_selection property set to false So I am performing some logic based on 'check_node.jstree.jstree' event. So, in that case, how should I checked that whether a child node os parent node is checked or not. Is it possible ?

**Comment by aadrian** [comment]
>  I am performing some logic based on 'check_node.jstree.jstree' event. 

I'm unaware of such an event in the JSTree official Documentation API:
https://www.jstree.com/api/

**Comment by vakata** [comment]
@sunny-srivastava the event to listen to is your choice - it depends on your needs, but remove the double `.jstree` event namespace. As for the task - you can use the `get_node()` method, and loop through the `children` array for that node and check if each of those node IDs is checked / selected.
