### ISSUE TITLE
lazy AJAX + JSON nested children = freeze if hovering using dnd

### ISSUE THREAD

**Issue by coz-eduardo-hernandez** [vakata/jstree#1553]
If I drag a node over another node using the drag and drop (dnd) plugin, my browser freezes. This happens only for lazy-loaded nodes using the nested children JSON format, that were not requested as root nodes. It does not happen when using the alternative JSON format.

I load my tree using AJAX, following the nested children JSON format. I return the requested node with it's children nodes inside the 'children' list.

After checking with the javascript debugger, it seems that in the function where it checks if dropping is a valid action on a node, it enters an eternal loop. When debugging and examining the arguments passed to the load_node event by logging to the javascript console, the reason seems to be that the parent ID of the node that's being checked is same the as the node's ID. I checked that my tree structure is not malformed and showing wrong parent-children relationships.

Even though I haven't checked this part of jstree's code, my impression is that this happens because, when I return data in the nested children format, all nodes received have their parent ID to the requested node; including the requested node itself. It's logical that if this is the case, root nodes requested using '#' or using the alternative JSON format that requires setting the parent explicitly, are not affected.

When using the nested children format with lazy-loading, changing the parent only on children and not on the requested node might fix the issue.

I'm using jstree 3.3.2(the issue was also present in 3.3.1 though), firefox 48.0, on Arch Linux.

**Comment by vakata** [comment]
I am afraid I can not help you without a demo. Such a general problem should be reproducable on jstree.com, and since it is not I suspect there is an issue with your data. 
Please provide a demo and I will reopen.

Best regards,
Ivan
