### ISSUE TITLE
Cascade Event in jstree.

### ISSUE THREAD

**Issue by sunny-srivastava** [vakata/jstree#1554]
I am working on jstree and using "check_node.jstree" event to perform some logic . So is it possible that I can cascade two events and my call back function work for both event like this.
$('#data').on("check_node.jstree changed.jstree", function (e, data) {
//some logic 
});

**Comment by vakata** [comment]
Yes you can listen for multiple events, but keep in mind - this is not jstree related - it is just how the `.on` jQuery method works.

**Comment by sunny-srivastava** [comment]
But this is not working.
$('#data').on("check_node.jstree changed.jstree", function (e, data) {
//some logic 
})
I have "toe_selection" and "whole_node" property  set to false

**Comment by vakata** [comment]
Please provide a demo (jsfiddle perhaps), which demonstrates what isn't working.
Here is the opposite - a demo showing that both selecting and checking will trigger the same code:
http://jsfiddle.net/DGAF4/1526/
