### ISSUE TITLE
Is there anyway to pass loaded nodes to search api instead of list of node ids? 

### ISSUE THREAD

**Issue by rasoulabbasi20n** [vakata/jstree#1555]
Hi, I'm using jstree, in search scenario, I want to load all results before passing to client side because of thousands of requests jstree-search would make to fill necessary children. Is there a way to avoid these too many requests ?

**Comment by rasoulabbasi20n** [comment]
I read this [QA](https://groups.google.com/forum/#!topic/jstree/w4VRF8mEjeE) and I want to know how to manually set configs to do that as Ivan mentioned in one of comments.

**Comment by vakata** [comment]
Simple enable the `massload` plugin and add the appropriate URL in your config, where you return the nodes jstree asks you for. Then there will only be a single request.

Best regards,
Ivan

**Comment by rasoulabbasi20n** [comment]
Sorry I wasn't around. Thanks, that worked like a charm :+1:
