### ISSUE TITLE
Disable check box of parent node.

### ISSUE THREAD

**Issue by sunny-srivastava** [vakata/jstree#1558]
I want to tweak the default behaviour of jstree. In jstree by default, all child and parent node have a check box . What I want is that I want to check box only for the child node, not for the parent node and when clicking on parent node it just simply lists out its children, it has using jquery.

**Comment by aadrian** [comment]
This question was already answered, e.g. here https://github.com/vakata/jstree/issues/1532

so the solution is using for those nodes another class that will hide the ckeckbox: http://jsfiddle.net/2kwkh2uL/4426/

**Comment by sunny-srivastava** [comment]
Ok, I get it that by using CSS we can disable the parent node checkbox. But what I want is based on  some condition, if true I want to disable all parent check box using jquery. So  how should I get these 
" .jstree li.jstree-open > a.jstree-anchor > i.jstree-checkbox, 
.jstree li.jstree-closed > a.jstree-anchor > i.jstree-checkbox { display:none; }"
using jquery. I don't want to apply it manually to css and also I dont want to manually set no_checkbox property to false. I want to apply it dynamically based on some condition.
Please help, thanks.

**Comment by aadrian** [comment]
> I want to apply it dynamically based on some condition.

What do you really mean by that? (your initial request mentioned nothing about this second scenario). 
 1. Dynamically when generating the page, or 
 2. at runtime after the page is generated and the tree is already rendered based on some user action (event) e.g. click on some button?

**Comment by sunny-srivastava** [comment]
Sorry, for not clearing the context earlier.
I want both the scenario, like dynamically when the tree is loaded the first time and based on some user event also.

**Comment by aadrian** [comment]
I still don't understand why is not working for you.
Here's an updated example that hides the checkbox for the parents when that button is clicked:
http://jsfiddle.net/2kwkh2uL/4553/

**Comment by vakata** [comment]
@aadrian thanks for helping out.
