### ISSUE TITLE
Activate the GitHub Wiki!

### ISSUE THREAD

**Issue by aadrian** [vakata/jstree#1559]
Please activate the WIKI pages provided by GitHub for this project!

**Comment by vakata** [comment]
I'd rather not do that as it will be one more place where the same information will be displayed - right now there are two places - jstree.com and the readme.md in this repo. I believe the wiki pages will be redundant. But please share your thoughts? I have not used the wiki so maybe there is something I am missing?

**Comment by aadrian** [comment]
> But please share your thoughts? I have not used the wiki so maybe there is something I am missing?

It seems that the users don't search in the closed issues for answers to their questions, since the same questions are getting asked over and over again and in the mailing list apparently too :).

The WIKI if configured right can be updated by everybody (with a GitHub account) not just project members, so it's quite fast to add stuff there, instead of modifying the main page with pull requests.

The idea would be to put stuff in the WIKI quickly (e.g. FAQ, more examples, common errors) and after it gets to a more "publishable" form, than to add them to the main page or the site.

Also it might make sense to configure/add Issue labels (tags) in GitHub, e.g. "bug", "feature", "question" since most of the closed issues are not "fixed bugs" but support questions that were answered :) .

**Comment by vakata** [comment]
I took your advice and added labels - thank you.
Could you please share your vision for a properly configured wiki, or point me to a project with a good github wiki so that I can learn from example before enabling the feature?

**Comment by aadrian** [comment]
> ... a properly configured wiki ...

Since with GitHub this is extremely easy: only activate the checkbox in the project settings, add some stub pages for the stuff you wish/think people will contribute, in order to give it a direction and purpose (e.g FAQ, roadmap, development, examples, etc.), and link them from the home page to be easier to be found.

Than when there's content that can be moved to the main site/page, it should be "moved" not just copied from the WIKI, to avoid duplicated content in older versions/state.

> .. before enabling the feature?

I guess, you can deactivate it anytime if it does not bring more value to the project.
