### ISSUE TITLE
Disable specific nodes when the tree loads

### ISSUE THREAD

**Issue by aswa12** [vakata/jstree#1563]
Hi,
I have a requirement to disable selection on specific nodes (whose 'template' value is false)  when the tree loads. I'm using conditional select right now, **but I want the nodes to disabled when the tree loads and not when the user clicks on a node**. Is there anyway of achieving this ? Please help

Thanks.
Below is my conditionalselect function and json data:
```

		     "conditionalselect" : function (node) {
		      	   return node.original.template == false ? false : true;
		         },

[
    {
        "id": "8458b8bd-5b7e-4ed0-8060-d833db7f86d5",
        "template": false,
        "children": false,
        "type": "folder",
        "text": "dnp ds"
    },
    {
        "id": "f13e4bfa-0a18-4bf9-946f-ca6f4e4e6840",
        "template": false,
        "children": false,
        "type": "OPCDataSource",
        "text": "opc ds"
    },
    {
        "id": "052c4c59-e9e5-4ed5-8669-e3d05b3559f5",
        "template": true,
        "children": false,
        "type": "GroupFolder",
        "text": "sree"
    },
    {
        "id": "87664ffe-e7a0-4d79-9cff-69f995fdc713",
        "template": false,
        "children": false,
        "type": "BinaryDataPoint",
        "text": "binary"
    }
];
```

**Comment by aswa12** [comment]
I think I found the answer:  :) 

		    $("#templatetree").bind("after_open.jstree", function (event, data) {
		    	$.each(data.instance._model.data, function (i) {
		    		if(data.instance._model.data[i].id != "#"){		    			
		    			if(!data.instance._model.data[i].original.template)
		    				$("#templatetree").jstree("disable_node", data.instance._model.data[i].id);
		    		}
		    	})
		     })

**Comment by vakata** [comment]
Since you already have the `"template" : false` part in your JSON, it would be best to add the disabled property in the JSON as well - using `"state" : { "disabled" : true }`. 

If you can not control the JSON jstree receives, then your approach is OK, but I'd use the `model` or `load_node` events, not `after_open`.
