### ISSUE TITLE
TypeError: obj is undefined when node is pre-selected

### ISSUE THREAD

**Issue by mcory** [vakata/jstree#1564]
Hi,
I want to display the path of the selected node when the page loads and update the display when the user selects a different node.

I found this code to display the path in a div:
```
.on('changed.jstree', function (e, data) {
  var path = data.instance.get_path(data.node, '\\');
  $('#event_result').html(path);
});
```
This works fine except when I have selected a node programmatically - then I get this error:
```
TypeError: obj is undefined
obj = obj.parents ? obj : this.get_node(obj);
```

on line 984 - in the first line of the `get_path()` method.
I am using jsTree version 3.3.2 (the latest I could download).

By "programmatically" I mean that I set the 'selected' attribute in the code I have for populating the jsTree.
Here is the JSON used to populate my test page:
```
[{"id":1,"parent":"#","text":"Root","state":{"opened":true,"disabled":false,"selected":true}},{"id":123
,"parent":"1","text":"folderA","state":{"opened":false,"disabled":false,"selected":false}},{"id":500
,"parent":"123","text":"Sub Folder A1","state":{"opened":false,"disabled":false,"selected":false}},{"id"
:501,"parent":"123","text":"Sub Folder A2","state":{"opened":false,"disabled":false,"selected":false
}},{"id":124,"parent":"1","text":"folderB","state":{"opened":false,"disabled":false,"selected":false
}}]
```

Any help would be greatly appreciated.
The script I used to build and populate the tree is here:

```
        /*
         * Populate a jsTree with JSON data.
         * If the JSON response is empty then empty the tree.
         */
        function buildTree(jsonData) {
            if (jsonData != null
                && typeof jsonData !== 'undefined'
                && jsonData.length > 0) {

                // build the tree
                $('#spanTree').jstree({
                    'core': {
                        'data': jsonData
                    }
                }).on('changed.jstree', function (e, data) {
                    var path = data.instance.get_path(data.node, '\\');
                    $('#event_result').html(path);
                });

            } else {
                $('#spanTree').empty();
            }
        }
```

Thank You!

**Comment by vakata** [comment]
Next time please provice a fiddle like this one:
http://jsfiddle.net/DGAF4/1550/

You will see that I replaced `data.node` with `data.selected[0]` - you can not depend on `data.node` being present all the time - initially there is no concrete node that triggered the event.

**Comment by mcory** [comment]
Ivan,
                Thank you so much for your reply.
                This does correct the issue I had – of course.
                I did create a simple test project to isolate my jsTree test code from the rest of my web app, but I apologize for not providing a jsFiddle.

                BTW – great work on this library!
MCory
