### ISSUE TITLE
Search Plugin option to search from beginning of node text

### ISSUE THREAD

**Issue by PranKe01** [vakata/jstree#1565]
Hi there,
I need a search which searches exactly for a string from the beginning of a nodes text. For example when I search for "he" it should find nodes like "HEll" and "HEllo" but not "sHE" or "wHEn". Is this possible right now?
I am using a a ajax search and when my server returns for example one node, the search plugin still searches for other cached nodes if the search query is available in one of those. That way the search plugin may show different search results, than my search engine is returning :( Is it possible to limit rhe results to only those which came from the server?

Thanks in advice!

**Comment by PranKe01** [comment]
Okay, after going through the issues-list I found one solution, by calling the search_callback:

```
search_callback: function(str, node) {
   if (node.text.toLowerCase().indexOf(str.toLowerCase()) === 0) {
      return true;
   }
   return false;
}
```
Regards!

**Comment by vakata** [comment]
No, using server results are not possible and I do not plan to add such functionality - sorry. You can however make sure that you implement exactly what you need using `search_callback`.
