### ISSUE TITLE
Search Plugin ajax-requests may get wrong order

### ISSUE THREAD

**Issue by PranKe01** [vakata/jstree#1566]
Hi there,
if I am making a search request with "A" which takes 5 seconds and then continue writing "AB" which takes only 2 seconds, the result from "AB" is showing before "A" and after that it gets overriden by the first request! So instead of showing the results from "AB" it now shows the results from search query "A".
I tried to use the search.jstree event, but there I can not cancel the refresh of the jstree.
Is there a solution to this problem?

Best Regards!

**Comment by vakata** [comment]
Unfortunately no - there is no solution. I will fix this ASAP by making sure any AJAX requests are aborted before firing the new one.

**Comment by PranKe01** [comment]
Perfect =)
