### ISSUE TITLE
Lazy loading json alternative

### ISSUE THREAD

**Issue by alan12111** [vakata/jstree#1570]
nevermind

**Comment by alan12111** [comment]
Console is returning this for every node expanded..
"Uncaught TypeError: Cannot read property 'concat' of undefined"

**Comment by vakata** [comment]
Sorry, I wasn't here to help earlier, I guess we live in very different timezones. It would be better to leave the issue in tact when you find a solution, post the solution and close the issue - that way others may benefit from your solution.

I believe the error you posted is not related to jstree, calling `concat` on `undefined` would indicate either code not in jstree, or some modification of the internal structures inside jstree which should not be modified from outside code, another possibility is having invalid data (like duplicated IDs).

Anyway, I hope you solved the problem.
