### ISSUE TITLE
Collapsing all jstree nodes after refreshing or loading HTML page in ie

### ISSUE THREAD

**Issue by baarei** [vakata/jstree#1571]
A have a simple html page with an jstree. After refreshing the page all nodes of the jstree are collapsed. This behavior occurs in ie 11 and edge browser. In firefox it works well. I haven't found any solution for this problem. Is this a bug in the jstree? Or is there a solution for this behavior in the ie?

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
	<head>
		<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title> Prozesscluster</title>
		<link media="all" href="inodocu.css" type="text/css" rel="stylesheet">
		<link media="print" href="inodocuprint.css" type="text/css" rel="stylesheet">
		<script type="text/javascript" src="searchresult.js"></script>
		<link href="jslib/jquery.treeview.css" rel="stylesheet">
		<link rel="stylesheet" href="jslib/themes/default/style.min.css">
		<script src="jslib/lib/jquery-3.1.0.min.js" type="text/javascript"></script>
		<script type="text/javascript" src="jslib/lib/jquery.cookie.js"></script>
		<script type="text/javascript" src="jslib/lib/jquery.hotkeys.js"></script>
		<script src="jslib/jstree.min.js" type="text/javascript"></script>
		<script type="text/javascript" src="jslib/text-overflow.js"></script>
		<script type="text/javascript">
			$(document).ready(function(){
				$("#browser").jstree({
					"state" : { "key" : "state_demo" },
					"plugins" : ["state"]
				});
			});
		</script>
	</head>
	<body>
		<div id="browser">
		  <ul>
			<li>Root node
			  <ul>
				<li>b</li>
				<li>a</li>
			  </ul>
			</li>
		  </ul>
		</div>
	</body>
</html>
```

I'm have tested the jstree in version 3.3.1 and 3.3.2.

**Comment by vakata** [comment]
I am afraid I can not reproduce this. I ran this fiddle a couple of times in IE11 and Edge and each time I get the tree in the same state I left it in (as should be with the `state` plugin active):
http://jsfiddle.net/DGAF4/1563/

The only thing I can think of is Compatibility and Quirks modes - if the page is in one of those - it will not work properly - jstree does not support IE compatibility view or quirks mode.

Let me know if the fiddle works for you? If it does - then the issue is not with jstree itself.

**Comment by aadrian** [comment]
Another possibility is the configuration of IE, e.g. no cookies or local storage (in corporate environments these settings are usually not even under the control of the user).

**Comment by baarei** [comment]
Thank you for your reply. I have identified the problem now. IE and Edge seem to have problems with the local storage when executing an local HTML file. However, I have found no solution, with which I can solve the problem. The only workaround is to deploy the site on a web server.

**Comment by aadrian** [comment]
> I have identified the problem now. IE and Edge seem to have problems with the local storage when executing an local HTML file.

Have you used a local "server" like https://www.npmjs.com/package/http-server or some other one
serving the static resources? Or have you just opened the file with the file protocol?

**Comment by baarei** [comment]
I have just opened the file with the file protocol.

**Comment by aadrian** [comment]
> I have just opened the file with the file protocol.

:) .

So always use https://www.npmjs.com/package/http-server or some similar solution so that the browser gets the http/https protocol. 

Another option is to use a better IDE (e.g. IntelliJ) that will serve/open file over the http protocol using an embedded server for you.
