### ISSUE TITLE
can't get jstree to work!

### ISSUE THREAD

**Issue by kilgorejd** [vakata/jstree#1572]
My app is using Python Flask and Jinja2 to create webpages. I have my checkbox jstree built using items Python Flask pulled from our MySql database, which are then passed in to the HTML template where jstree is initialized on document ready.  Jinja2 is used to put those in as the values for the jstree UL and LI elements. It all 'looks' good. At the end of the document ready, there's a call to a separate javascript function (that's also tied to a 'Reset' button on my jstree HTML page) that is supposed to set the 'checkboxes' in the jstree with the current database values. Currently, the only way that works is if I wrap the jstree init in a blank function, and use the $('#jstree_div').bind('loaded.jstree', function method culled from the internet.

The problem with this approach is 'finding' the jstree instance.  After the initial set up, any further calls to the same 'reset' function do not work. Also, there's a requirement to list the total number of items/selected items next to the checkbox text; that only works the first time too.  Can you look at my code and tell me what basic principle I'm missing??

```javascript
$(document).ready(function() {
    $(function() {
        $("#jstree_div").jstree({
            checkbox: {
                tie_selection: false
            },
            "plugins" : ["checkbox"]
        }, "load_all")
        .on('check_node.jstree uncheck_node.jstree', function(e, data){
            console.log("something changed");
            authorizationsChanged();  //external js to CSS enable page's update and reset buttons, also calls update_category_count
    });
    //external function to look at data items passed in from mysql and check the corresponding LI
    auth_reset();
});

function auth_reset(){
    console.log("in auth reset")
    $('#jstree_div').find('li').each(function() {
        var mynode = $(this);
        var id = mynode.data('id');
        //authorized_packages come from mysql data passed in
        if(authorized_packages[id]){
            $('#jstree_div').bind('loaded.jstree', function(){
                $(this).jstree('check_node', mynode.attr('id')));
            });
        }
    });

    //function to calc the number of items/selected items
    $("li.category-name").each(function () {
        update_category_count($(this));
    }
}

function update_category_count(cat) {
    var rows = $(cat).find("*");
    var packages = rows.find(".package-name");
    var capabilities = rows.find(".capability-name");
    
    var p_total = packages.length;
    var p_count = 0;
    var c_total = capabilities.length;
    var c_count = 0;
    var text = "(";

    $('jstree_div').bind('loaded.jstree', function () {
        var mytest = $(this).jstree("get_checked", false);
        for (i in mytest){
                for (y in packages){
                        if (packages[y].id == mytest[i]){
                                p_count += 1;
                        }
                }
                if (capabilities.length > 0) {
                        for (z in capabilities){
                                if(capabilities[z].id == mytest[i]){
                                        c_count += 1;
                                }
                        }
                }
        }

        text += p_count;
        text += "/";
        text += p_total;
        text += (p_total == 1) ? " package" : "packages";
        if (c_total > 0){
                text += ", ";
                text += c_count;
                text += "/";
                text += c_total;
                text += (c_total == 1) ? " capability" : "capabilities";
        }
        text += ")";
        //had to call this because within the bind, i couldn't get the value of text out
        appendCount(cat.attr('id'), text);
    });
}


function appendCount(myid, mycount){
    var myselector = "#" + myid;
    $(myselector).find(".count").text(mycount);
}
```

And some of the HTML tree:
```HTML
<div class="controls" style="overflow-y: auto" id="jstree_div">
    <ul class="package-selection">
        {% for category in categories %}
            <li id="category-{{ category.id }}" class="category-name"> {{ category.name }}
            <span class="count"></span>
                <ul>
                    {% for package in category['packages'] %}
                        <li id="package-{{ package.id }}" data-id="{{ package.id }}"> {{ package.name }}
                        {% if package['capabilities'] %}
                            <span class="count"></span>
                            <ul>
                                {% for capability in package['capabilities'] %}
                                    <li id="capability-{{capability.id}}" class="capability-name" data-id="{{capability.id}}"> {{capability.name}} </li>
etc etc
```

As I said, it all works the first time. Subsequent checking does not alter the tree.

cheers,
...john

**Comment by vakata** [comment]
From what I see you are trying to use the HTML data source, but modify it after creation? Is that right - if so - keep in mind jstree does not support that - the HTML data source is intended for small trees and navigation menus without much custom logic. Once parsed the HTML that you have is stored in an internal jstree object and then the actual markup is redrawn as needed, so modifying the `LI` nodes after creating the instance will not do you any good - if you go that route you need to update the markup every time a node is opened or closed. 

To modify the generated markup you need to build a plugin, or use the `set_text` method. Think of it this way - jstree always draws the tree as you interact with it from its internal storage, and has a template it uses, if you want to modify the HTML you either need to make your changes every time the tree is redrawn or modify the "template" - the latter is achieved with a plugin.

As for finding the instance - `$('#div').jstree(true)` will do it every time.

As for the code you are using - it seems unnecessarily complex. How about this:
```
$("#jstree_div").jstree({
    checkbox: {
        tie_selection: false
    },
    "plugins" : ["checkbox"]
})
.on("ready.jstree", function () { auth_reset(); })
.on("check_node.jstree uncheck_node.jstree", function () { auth_changed(); });

function auth_reset() {
    var instance = $('#jstree_div').jstree(true);
    for (id in authorized_packages) {
        if (authorized_packages.hasOwnProperty(id)) {
            instance.check_node(id);
        }
    }
}
```
As for the count - either use a plugin or `set_text`. The reason your code is not working is that you attach an event handler in the function, and no matter how many times you attach it - `loaded.jstree` will only fire once. And even if it did fire many times your code will be invoked many times, as you attach the event many times. The above example should point you in the right direction.

**Comment by kilgorejd** [comment]
Thanks very much, that helps!!
