### ISSUE TITLE
jstree website

### ISSUE THREAD

**Issue by wnasirou** [vakata/jstree#1573]
I am realize that **jstree website** don't work. I need to see jstree API documentations.

**Comment by aadrian** [comment]
https://www.jstree.com/api/

**Comment by wnasirou** [comment]
Are you trying to access to the website ? It doesn't always works.

**Comment by vakata** [comment]
Where are you accessing the site from? I haven't had downtime reports in years. If you are having trouble accessing the site you can use the source comments - they are what the API docs are generated from.
