### ISSUE TITLE
Create_node function doesn't work properly after full redraw

### ISSUE THREAD

**Issue by piuliano79** [vakata/jstree#1574]
I create dynamically node inside my jstree div.
This is the code I use:
`var newPosition = curPosition + 1;
var data = "#edit_inline_page"+newPosition;
var new_elem = $("#dragdiv").jstree().create_node("#", { "data": data, "text": "Page "+newPosition }, 'last', false, false);
$("#"+new_elem+" a").addClass("icon-pen");
$("#"+new_elem+" a").attr("href", "#edit_inline_page"+newPosition);`

The only plugin I use is "dnd".

The node creation works fine until I try to move a node or create another one.
When this happens, a full redraw is autocalled and created nodes lost all parameters. Lost assigned class, lost assigned href. This happens only for dynamically created node, not for node created before JSTREE init.
Example of node before and after "dnd"

`<li role="treeitem" aria-selected="true" aria-level="1" aria-labelledby="j1_4_anchor" id="j1_4" class="jstree-node  jstree-leaf jstree-last active">
<i class="jstree-icon jstree-ocl" role="presentation"></i>
<a class="jstree-anchor icon-pen jstree-clicked" href="#edit_inline_page5" tabindex="-1" id="j1_4_anchor">
<i class="jstree-icon jstree-themeicon" role="presentation"></i>
Page 5
</a>
</li>`

`<li role="treeitem" aria-selected="true" aria-level="1" aria-labelledby="j1_4_anchor" id="j1_4" class="jstree-node  jstree-leaf jstree-last">
<i class="jstree-icon jstree-ocl" role="presentation"></i>
<a class="jstree-anchor  jstree-clicked" href="#" tabindex="-1" id="j1_4_anchor">
<i class="jstree-icon jstree-themeicon" role="presentation"></i>
Page 5
</a>
</li>`

Cheers

**Comment by vakata** [comment]
This is normal - jstree will only read the underlying HTML when creating the instance. If you want to persist any changes to the structure - change them in the internal model as well:
```
$('#drag_div').jstree(true).get_node(new_elem).a_attr.class = 'icon-pen';
$('#drag_div').jstree(true).get_node(new_elem).a_attr.href = '...';
```

Best regards,
Ivan

**Comment by piuliano79** [comment]
Thanks for your reply.

Only a bit:
When I call
`$('#drag_div').jstree(true)`
the function return false

but when I call
`$('#drag_div').jstree(true).get_node(new_elem)`
$(...).jstree(...).get_node is not a function(…)

Thanks for your help.
Paolo.

**Comment by vakata** [comment]
Use the correct ID of the DIV where you initialized jstree - in your case that is `#dragdiv` without the underscore.

**Comment by piuliano79** [comment]
I'm a dumb chicken.
Thanks for your help :)
