### ISSUE TITLE
Cannot update tree

### ISSUE THREAD

**Issue by martinellison** [vakata/jstree#1575]
I can assign data to the tree and the data is displayed properly. But if I then change the data, the updated data is not displayed.

I have tried this with (a) setting the data in the HTML and (b) setting the data using `core.data`. I have the same problem both times.

I am basically doing `$('#mytree').jstree({core: {data: [{text: "aaa"}]}}); ` (which works) and then `$('#mytree').jstree({core: {data: [{text: "aaa"},{text: "bbb"}]}}); ` which does not work (it still only displays one node with 'aaa'; it should display two nodes).

Do I need to do something different (maybe, somehow call refresh?) Or is this a bug?

**Comment by vakata** [comment]
You need to call refresh if you are changing the `core.data` property, although I would recommend setting `core.data` to a function and calling refresh - it is cleaner that way:
```
var data = [{text: "aaa"}];
$('#mytree').jstree({core: {data: function (node, cb) { cb(data); } }});
// and then later on
data = [{text: "aaa"},{text: "bbb"}];
$('#mytree').jstree(true).refresh();
```

**Comment by martinellison** [comment]
Yes, that works thanks.
