### ISSUE TITLE
problems with brackets "<", ">" in id of node

### ISSUE THREAD

**Issue by erez-o** [vakata/jstree#1576]
Hi, 

Tried on the v3.3.2.

select_node and open_node fail to select/open it.

If it helps, the full string is `struct-LongFitsIntoSizeTMinusOne< false >`. Without the brackets it works.

Thx for a great project

**Comment by vakata** [comment]
jsTree will try to escape IDs but keep in mind it is best to use valid CSS ID strings - which means no spaces and keep the brackets to a minimum. 
Still, the ID you provided seems to work - I have no problem selecting this node:
http://jsfiddle.net/DGAF4/1600/

Best regards,
Ivan

**Comment by erez-o** [comment]
Thx, 

You're correct, the bug was in my court. Sorry for the trouble
