### ISSUE TITLE
"select_node_list"

### ISSUE THREAD

**Issue by Nazz340** [vakata/jstree#1577]
Have a huge tree, where on ready need to select big list of nodes(sometimes from 300 to 1000). 
Using "$.jstree.reference('#jstree').select_node(node_list);" takes too much time, tried "data.instance._model.data[id].state.selected = true;" as solution, nodes get selected but jstree dont see it as "event" and do not update parrent nodes...
is there'a any soluton?

**Comment by vakata** [comment]
You could try passing the selected state with the data you feed to jstree - that is the best option. 

Or you could try calling `select_node` with the `supress_event` and `prevent_open` params set to `true` and then trigger `changed.jstree` manually once done - that should be much quicker.

And third option is taking what you have already done a step further - aside from setting `state.selected` on the nodes you want you should also populate the `data.instance.data.core.selected` array accordingly (array of all selected IDs) and then trigger `changed.jstree` just in case.

Let me know if I can help in any way.
