### ISSUE TITLE
Drag  and Drop is not working in Jstree

### ISSUE THREAD

**Issue by srinadh14** [vakata/jstree#1579]
HI,

I have requirement that i need to load child nodes data(ajax call) based on expand icon click. so i added mouse down event to jstree to fetch and updated settings.core.data

now drag and drop is not working if do like that even i added dnd plugin initially.
  
So Please help me out.

 $('#jstreeEthics')
                    .jstree({
                        "core": {
                            "themes": { "icons": false },
                            "check_callback": true,
                            "data": ethicsTree,
                        },
                        "plugins": ["dnd", "wholerow"]
                    });
            });
        $('#jstreeEthics')
            .bind("mousedown.jstree", LoadSubTopics);

**Comment by vakata** [comment]
Please read the docs on lazy loading nodes - attaching a mousedown event is not the way to do it. jsTree supports AJAX out of the box, and there is also the most flexible callback option. It is all in the docs and on the home page of this repo.

**Comment by srinadh14** [comment]
HI,
Your right.I tried previously but that process doesn't meet my custom requirement.
First I'll explain my scenario and add  necessary files now.

**Requirement** 
I need to load 6 to 7 different tree view's in a page So initially call the api(Service) function through ajax then i iterate the each item which has the children properties.

I faced below problems.
1. If i modify this process as per your suggestion or doc then i need to fetch the all roots in each and every time of tree view.It will be duplicate call's to api function(Service call)

2. I need to modify the json data after coming from api call(service) so i used DataFilter in normal suggested approach.In this approach i couldn't find the first call response or lazy load call response.

Avoid these problems i added mouse down event.In this situation dnd properties didn't change but drag and drop option didn't work.

Please Check this customized requirement and necessary attached docs.

Please suggest me how to proceed further.

![image](https://cloud.githubusercontent.com/assets/20988015/18882713/0580736e-84fe-11e6-8808-d4c5df11b1e0.png)
