### ISSUE TITLE
Custom UI for create/edit node in Context Menu plugin

### ISSUE THREAD

**Issue by rstevehole** [vakata/jstree#1581]
We are using jstree to provide a management interface for a set of hierarchical categories/tags. Ultimately we need to link several different object types to the nodes in the tree at leaf positions. To do this properly we need to render a selection control as a result of a "Create" context menu action rather than the in-place string input box that is currently rendered by the context menu plugin. We have a number of custom selection controls that support AJAX completing (type down) selections over large search spaces. We must pick from an existing set of database defined objects to "link" to the parent node by id.

I looked through the issue history and stackoverflow without hitting on anything. Am I missing some obvious way to do this?  It looks like I'd have to do a custom plugin that would override the edit_node method, extending it to allow injection via node data of some custom HTML, including supports JS to do this. 

Assuming a plugin, I'm looking for some advice on how best to support this within the jstree package as a whole. Do we only need to replace the edit_node method or are we going to have to get into create_node and rename_node as well?

**Comment by rstevehole** [comment]
Sigh ... never mind :-)

Everything I need is already there and I just need to do it in the right order. I got confused by the order of events that I had implemented in my action handler, thinking that I had to do a create_node first to get the UI, when obviously I don't. When you assemble UI via tags (Grails GSP in this case) it is easy to get lost as to when things are being done.

My bad.

**Comment by vakata** [comment]
No problem, glad you worked it out.
