### ISSUE TITLE
Issue with Lazy loading  

### ISSUE THREAD

**Issue by srinadh14** [vakata/jstree#1582]
HI,
I tried normal lazy loading approach but that process doesn't meet my custom requirement.
First I'll explain my scenario and add  necessary files now.

**Requirement** 
I need to load 6 to 7 different tree view's in a page So initially call the api(Service) function through ajax then i iterate the each item which has the children properties(Implemented Approach) bind to the different tree view

I faced below problems with lazy loading approach(As suggested)
1. If i modify this process as per your suggestion or doc then i need to fetch the all roots in each and every time of tree view binding .It will be duplicate call's to api function(Service call)

2. I need to modify the json data after coming from api call(service) so i used DataFilter in normal suggested approach.In this approach i couldn't find the first call response or lazy load call response.

Avoid these problems i added mouse down event.In this situation drag and drop option didn't work.

Please Check this customized requirement and necessary attached docs.

Please suggest me how to proceed further.

![image](https://cloud.githubusercontent.com/assets/20988015/18882713/0580736e-84fe-11e6-8808-d4c5df11b1e0.png)

In first api call i got the list tree's collection.I think as per normal lazy load approach doesn't meet my requirement and if i use that approach api(Service) call's will be duplicated

**Comment by vakata** [comment]
Use `core.data` as a function - you have full control then - you can fetch the resource once and feed it to all trees. Having a function as `core.data` gives you full control and maximum flexibility - you can fetch / cache data however you need. 

If you absolutely want to go the hard way and do things manually - try not to break existing event handlers and you should be fine. If you are preventing the mousedown event from bubbling - that will break the DND functionality.

**Comment by srinadh14** [comment]
HI,
please suggest any reference links to help my scenario so that i can get full idea.
