### ISSUE TITLE
jstree is horizontal instead of vertical

### ISSUE THREAD

**Issue by vinothrao** [vakata/jstree#1583]
![image](https://cloud.githubusercontent.com/assets/5294130/18929969/dc70ba10-85e3-11e6-9306-886f6d0996d4.png)

jstree is coming as horizontal and not as vertical please help.

**Comment by vakata** [comment]
Please provide a demo of the issue. It appears you have custom CSS in your page that overrides jstree's styles - you most probably have all LI nodes display as `inline` or `inline-block`. Make sure your CSS does not affect jstree's styles - either use a lower strength selector, or be sure to craft the selector in such a way that it does not affect jstree's container. 
I can not tell you more without a demo, but I believe you have enough to go on. Just inspect the nodes and see which of your page's styles break the tree.
