### ISSUE TITLE
Unable to Drag-n-Drop root level items

### ISSUE THREAD

**Issue by SimonOrdo** [vakata/jstree#1585]
Using the DND plugin, I'm unable to reorder root level items.  Elements at other levels are able to be reordered without issue.  

The error I'm getting is 

> "Moving parent inside child"

Fiddle here:  https://jsfiddle.net/mhdrk7fa/21/

Steps to reproduce:
1. Add several items by clicking "Add New Node"
2. Attempts to re-order green colored child level book icon nodes and observe success.
3. Attempt to re-order blue root level folder icon items by dragging an dropping.
3. Observe error message

**Comment by vakata** [comment]
Removing your custom check function solves the issue:
https://jsfiddle.net/mhdrk7fa/22/

So the problem is with the function you added - I did not examine it in detail, but maybe you can avoid using a custom plugin and set `core.check_callback` to a function?
