### ISSUE TITLE
Search function with show_only_matches doesn't work

### ISSUE THREAD

**Issue by CHuLoYo** [vakata/jstree#1587]
Hello. I have a weird issue with the search function on jstree. I build a simple example to test the capabilities. The search function works well, but when I set the `show_only_matches` property the plugin crashes.

The error:

> TypeError: this.get_container_ul(...)[0] is undefined
> a.jstree.core.prototype._redraw()
> jstree.min.js:2
> a.jstree.core.prototype.redraw()
> jstree.min.js:2
> a.jstree.plugins.search/this.bind/<()
> jstree.min.js:5

My code is like the following:

```
$('#jstree').jstree({
	"core" : {
		"multiple" : true,
		"check_callback" : true
	},
	"checkbox" : {
		"keep_selected_style" : true
	},
	"search": {
		"show_only_matches": true
	},
	'types' : {
		'default' : {
			'icon' : 'fa fa-folder-o fa-fw',
			'li_attr': {'class': "tree-closed-folder" }
		},
		'item' : {
			'icon' : 'fa fa-file-o fa-fw',
			'li_attr': {'class': "tree-closed-folder" }
		},
		'f-open' : {
			'icon' : 'fa fa-folder-open-o fa-fw',
			'li_attr': {'class': "tree-open-folder" }
		},
		'f-closed' : {
			'icon' : 'fa fa-folder-o fa-fw',
			'li_attr': {'class': "tree-closed-folder" }
		}
	},
	"plugins" : [ 
		"checkbox",
		"contextmenu",
		"dnd",
		"search",
		"state",
		"types",
		"changed",
		"conditionalselect"
	]
});
var to = false;
$('#tree-search').keyup( function(e) {
	if(to) { clearTimeout(to); }
	to = setTimeout(function () {
		var v = $('#tree-search').val();
		$('#jstree').jstree(true).search(v);
	}, 50);
});
$("#jstree").on('open_node.jstree', function (event, data) {
	data.instance.set_type(data.node,'f-open');
});
$("#jstree").on('close_node.jstree', function (event, data) {
	data.instance.set_type(data.node,'f-closed');
});
```

This makes impossible to find items on a large tree. I need the search working with `show_only_matches`. What can I do?

**Comment by CHuLoYo** [comment]
Sorry, the problem was the mCustomScrollbar plugin, it makes crash all. Just set in another box and search works. Sorry!

**Comment by ungureanualex** [comment]
I have a similar tree , but when i try to perform a search , it give's me an error $(...).jstree(...).search is not a function. What should be the problem?

**Comment by bagric** [comment]
It should look like this: $(...).jstree("search",value) the value is what you are searching for.

**Comment by ungureanualex** [comment]
I resolved it 'till now. Thanks anyway for the answer.
