### ISSUE TITLE
Cannot check multiple nodes at same level.

### ISSUE THREAD

**Issue by Sam89Jha** [vakata/jstree#1589]
When we checked any node, then It first deselect all nodes and checked that particular node. 

Issue diagnosed and found a line of code which cause this, please find path below for reference

..\demo\bower_components\jstree\dist\jstree.js .. line no : 3018 //this.deselect_all(true);

**Comment by vakata** [comment]
Please read the docs on the checkbox plugin more carefully. Also take a look at the `core.multiple` setting.
