### ISSUE TITLE
Why does open_node call redraw_node for all children?

### ISSUE THREAD

**Issue by deitch** [vakata/jstree#1591]
Simple tree, with one parent node and three children. I set `show_only_matches=true`. Then I search for a match with just one child. 

(simplified data structure)

````yml
parent
  child1
  child2
  child3
````

If I search for `child2`, I get the second child highlighted and shown; the first (`child1`) and the third (`child3`) are hidden, correctly, because `show_only_matches=true`.

Now close and open the parent. The correct _visual_ behaviour occurs. But I can see that `redraw_node` is called three times, once for each of `child1`, `child2`, `child3`. 

1. Why does it call it for each child if it only is redrawing `child2`?
2. How does it *not* display `child1` and `child3` if it called `redraw_node` on all of three of them?

I looked in the source for `jstree.search`, it overrides `redraw_node` but doesn't hide it, just adds the search class if it matches the results. It doesn't override or even create a handler for any of the `open` events.

**Comment by deitch** [comment]
I also looked at the `search.jstree` event, but that only is called when a new search occurs, not when a node is opened while a search already is active.

**Comment by deitch** [comment]
Unless... does calling `hide_node(node)` hide it for all subsequent searches and opens until `show_node(node)` is called?

**Comment by vakata** [comment]
Hi, sorry I was not able to answer sooner - yes, the `hide`/`show` functions do the trick, but the way those functions work is that the node is actually in the DOM and hidden via CSS. If you want to skip some processing on such nodes you can always check the `state.hidden` property in your `redraw_node` override.
I am still considering features for v.4 so I will keep this in mind.

**Comment by deitch** [comment]
Thanks, I will work with that for now. I will worry about v4 then.
