### ISSUE TITLE
$.inArray is slow

### ISSUE THREAD

**Issue by ninichki** [vakata/jstree#1592]
Thanks for your create work,

I have a tree with about 100000 leafs.
If I uncheck all nodes by clicking on the root node, the tree needs about 45s to uncheck all nodes.

The reason is this part of code:
Row: 5030
 for (i = 0, j = cur.length; i < j; i++) {
					        // apply down + apply up
					        if (
                                (s.indexOf('down') === -1 || $.inArray(cur[i], obj.children_d) === -1) &&
                                (s.indexOf('up') === -1 || $.inArray(cur[i], obj.parents) === -1)
                            ) {
					            sel[cur[i]] = true;
					        }
					    }

If I search in an Object it's much faster
children = {};
					    for (i = 0, j = obj.children_d.length; i < j; i++) {
					        children[obj.children_d[i]] = true;
					    }
					    for (i = 0, j = cur.length; i < j; i++) {
					        // apply down + apply up
					        if (
                                (s.indexOf('down') === -1 || children[cur[i]] !== true) &&
                                (s.indexOf('up') === -1 || $.inArray(cur[i], obj.parents) === -1)
                            ) {
					            sel[cur[i]] = true;
					        }
					    }

Tested with Chrome Version 53.0.2785.143 m (64-bit)

Maybe there are potentials for making the tree faster

**Comment by vakata** [comment]
Hi,

Thank you for the input and sorry for taking so long to reply.

Yes, that is a good catch, but there is no good solution at the moment - converting the array to an object with boolean keys will consume more memory, so it is a trade-off. 

The best solution would be not to rely on arrays for the internal representation of the nodes, but I am afraid that is quite a huge task (rewriting all the code which depends on those arrays). 

This problem will not exist for v.4 as it uses a different internal structure, but I can't invest the time to rewrite v.3 now.

So I am closing this as won't fix, but if I come to a bump in the road with v.4, I will revisit this ticket.

Best regards,
Ivan
