### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by XFXScorpion17** [vakata/jstree#1593]
I have a problem with the menu since 1000 have more nodes to display. The problem is that if I select an item I click to display the menu and under the scroll shown in this way and not stay fixed on the node.

Like this : 

![image](https://cloud.githubusercontent.com/assets/14335244/19370814/c4a5c236-9173-11e6-9e4c-cf1e4b514ee6.png)

The tree are in element DIV ( with Scroll) , that is the problem ? or is a BUG or Issue ? 

Thanks , sorry my english is not Good. :/

**Comment by vakata** [comment]
If you are talking about the contextmenu and scrolling after the contextmenu is shown? If yes - this has never been a feature and never will be. If I misunderstood - please clarify and I will reopen.
