### ISSUE TITLE
feature request: Ellipsis when text of node goes outside of the jstree container

### ISSUE THREAD

**Issue by QueroBartK** [vakata/jstree#1594]
First look at this [Fiddle](https://jsfiddle.net/n0rduyfd/8/)

as you can see the jstree is contained within it's container but unlike the div underneath it I can't get ellipsis to appear on nodes with text that go outside the container.  In order to do this I would probably need to know the indentation and the width of each node .

So could this be a setting in jstree? (maybe not only allow Ellipsis but also other characters.)

**Comment by QueroBartK** [comment]
ok, I've actually been able to solve it using the css calc() function. You can see how in the following [fiddle](https://jsfiddle.net/n0rduyfd/10/)

**Comment by QueroBartK** [comment]
A concern with this solution is when the values used in the calc are changed in jstree.

Another concern is adding a scrollbar to see the rest of the text:
1) This might be hard to do correctly with the tree as we don't want a scrollbar per node but one scrollbar for the entire tree
2) in most browsers you wouldn't see the text. only firefox (at this moment) seems to properly support this behaviour

**Comment by QueroBartK** [comment]
After discussing this some more it seems that the concern that the values used in the calc might change is big enough to warrant reopening this issue.

**Comment by vakata** [comment]
Sorry, but I do not plan on adding such functionality. 

All systems I have seen either cut off the text (without an ellipsis) and let you resize the tree container or provide a horizontal scrollbar on the tree container - jstree supports both those scenarios. 

Quite frankly - I do not see the need for it - can you provide a screenshot of a tree that uses this (OS file manager, or something else), as I can't even imagine a good implementation. The idea of cutting off using ellipsis and still allowing resizing or scrolling is counter intuitive for me. As for cutting off and not providing a means of resizing - it would be very confusing for the user as whole levels of the tree will be unaccessible, but still - if you need that you can use your calc solution - kudos for that!

I am closing this for now, but feel free to share any ideas and / or implementation - if something good comes from the discussion I will reopen.

Best regards,
Ivan

**Comment by vakata** [comment]
After reading the whole thread over at jstree-grid I realized that the calc solution is usable, provided it is in the theme file, so I am reopening this - thanks: https://github.com/deitch/jstree-grid/issues/184
