### ISSUE TITLE
TypeError: $.expr.createPseudo is not a function

### ISSUE THREAD

**Issue by muthulatha07** [vakata/jstree#1595]
Whenever I load the jstree library function, I get this error. I have tried using JQuery verison from 1.12 - 2.2 but no luck. Please help

**Comment by vakata** [comment]
Can you provide a demo of the issue (a jsFiddle perhaps?) `createPseudo` was added in jQuery 1.8.1, and had been the preferred method of creating custom selectors ever since, all other options were deprecated in jQuery 3.
I will reopen whe you can provide a demo of the issue.
