### ISSUE TITLE
Delete node issue 

### ISSUE THREAD

**Issue by srinadh14** [vakata/jstree#1596]
Hi,

I deleted node from jstree  but is it showing when jstree refreshed(not JSON).I observed this in one scenario.I think it's not updating in core.data

**Comment by vakata** [comment]
Please provide a demo - I can not help you without one. Keep in mind you need to use `get_json` to get the updated JSON back, jsTree does NOT update whatever you pass in core.data - it is not used as a reference.

If this does not anwser your question, please provide a demo and I will reopen.
