### ISSUE TITLE
Make jstree checkboxes behave like actual checkboxes that can be submitted

### ISSUE THREAD

**Issue by pmishev** [vakata/jstree#1597]
Is there any way to make jstree with the checkboxes plugin actually behave like real checkboxes used in a form?

I made a workaround that adds actual submittable checkboxes inside the `<li>`, during the initial generation of the tree and then adding some additional handling code in the js:

```
.on('changed.jstree', function(node, action, selected, event) {
    if (action.node) {
        // Set the state of the belonging checkbox and children checkboxes recursively
        childrenNodes = action.instance.get_json(action.node.id, { flat: true });
        childrenNodes.forEach(function(childNode) {
            $('#'+childNode.a_attr.id).find('input:checkbox:first').prop('checked', action.node.state.selected);
        });

        // Set the state of the parent checkboxes recursively
        parentNode = action.instance.get_node(action.node.parent);
        while (parentNode.hasOwnProperty('a_attr')) {
            $('#'+parentNode.a_attr.id).find('input:checkbox:first').prop('checked', parentNode.state.selected);
            parentNode = action.instance.get_node(parentNode.parent);
        }
    }
});
```

All worked well, until I realized that when you collapse a node, the entire `<li>` gets removed from the DOM and the real checkbox along with it.

I saw some suggestions to use `$('#your_tree').jstree('get_selected');`, serialize it and put inside a hidden field that can be submitted, but this is no good - I need to change my server-side handling as well to unserialize the data. 

I want to get the data in the request as array, as with actual checkbox inputs. How can I do that?

**Comment by vakata** [comment]
Visually this is already implemented in a plugin that you can add to your page if you want:
https://github.com/vakata/jstree/blob/master/src/misc.js#L66

However submitting those will not work, as jstree does not keep all nodes in the DOM, so it is not possible to submit those checkboxes - you will get only visible ones on the server.
The only solution is to add a `changed` event handler and populate some hidden fields outside of the tree container.

Best regards,
Ivan

**Comment by pmishev** [comment]
Correct me if I'm wrong, but the `changed` event gets called only on the actual clicked checkbox. If it has children under it, they will be checked as well, but the event will not fire for them?
So, I'm left with doing some gymnastics as in the code I pasted above.

Is there no way to disable removing of the nodes from the DOM when they are hidden, as an option?

**Comment by vakata** [comment]
The `changed` event fires AFTER all changes to the selection are propagated, so if you get the selection using `data.selected` you will get all checked nodes. If getting the whole selection is not enough for you - you can track changes to the selection - add the changed plugin to your plugins setting.

**Comment by pmishev** [comment]
There seems to inconsistency between the examples and the documentation about the arguments of the event handler: https://www.jstree.com/api/#/?q=.jstree%20Event&f=changed.jstree.

**Comment by vakata** [comment]
Could you provide more info about the inconsistency, so that I can fix it?

**Comment by pmishev** [comment]
On the above link, it says the handler accepts 4 params: `node`, `action`, `selected`, `event`
And looking at the examples, the actual params are `e`, `data`

**Comment by vakata** [comment]
There are two params - event and data, as with all jQuery event handlers - the 4 listed properties are the keys INSIDE the `data` object.

**Comment by pmishev** [comment]
sorry, my bad, my jQuery is a bit rusty.
I finally resorted to removing the actual checkboxes, and instead added onSubmit handler on the form that generates a list of input fields to actually be submitted. It looks something like this:
```
        $('#jstree').closest('form').submit(function(e) {
                jsTreeInstance = $('#jstree').jstree(true);
                selectedNodes = jsTreeInstance.get_selected();

                // Make sure the inputs placeholder is empty
                $('#jstree_inputs').empty();

                // Add input elements for all selected nodes
                selectedNodes.forEach(function(id) {
                    nodeValue = jsTreeInstance.get_node(id).data.value;

                    $('#jstree_inputs').append($('<input>', {
                        type: 'hidden',
                        name: 'myCheckboxField[]',
                        value: nodeValue
                    }));
                });
            });
        });
```

However, I'm worried that if a user submits the form, before JS has initialized, the checkbox values coming from the server will be lost. Do you have any suggestion how to overcome this problem?

**Comment by vakata** [comment]
I am not sure what you mean.
1) If the form is prepopulated with the current server selection (so basically if you have a bunch of hidden inputs before jstree initializes) then you will get the exact same selection on the server side, so no problem.
2) If the form is not prepopulated - make sure you add one extra hidden input with the value of "0" - that way if the form is submitted and the zero value is not there you will know not to process the checkboxes.

**Comment by pmishev** [comment]
Yes, the first is what I meant. I'll just generate the hidden fields from the server initially. Thanks.
