### ISSUE TITLE
Replace image map with Fonts (Font Awesome)

### ISSUE THREAD

**Issue by NJDave71** [vakata/jstree#1601]
What's the easiest way to replace the Images with Fonts?   

Thanks

**Comment by vakata** [comment]
On any given node you can set the icon property to a class name, so you can use `"icon" : "fa fa-flash"` for example. 
You can even see the leaf icon on the jstree homepage: https://www.jstree.com/ (second tree)

**Comment by NJDave71** [comment]
I wanted know if the [+] and [-] can use a font font instead of using the 32px.png file  plus turn off the connecting lines.

**Comment by vakata** [comment]
The only way to customize the plus / minus icons is to create a plugin, as for the dots - use the core.themes.dots setting.

**Comment by vakata** [comment]
The only way to customize the plus / minus icons is to create a plugin, as for the dots - use the core.themes.dots setting.

**Comment by karlingen** [comment]
@NJDave71 did you manage to solve this?
Also looking for a way to replace the icon with  [+] and [-] without having to hack the png file.

**Comment by NJDave71** [comment]
No, i never got around to it.  got caught up in other projects.
