### ISSUE TITLE
Preventing node selection and preserving current selection

### ISSUE THREAD

**Issue by GRMule** [vakata/jstree#1604]
Briefly about my usecase: I am using the tree view to present a categorized inventory. When a node is selected, I am displaying a form to edit the item record. If the user makes changes to the form and attempts to select a different node without first clicking a save or discard button, I want to prevent the selection and ask the user to either save or discard the changes.

In the demos below, I am trying to reproduce my usecase in a simple form by stopping any selection beyond the first one. So, click Child 1, then click Child 2 and the expected behavior is that you should be stopped with a message in the console and Child 1 should remain selected.

I tried to prevent the selection by using preventDefault() on the select_node event, and returning false. This does not appear to work at all: http://jsfiddle.net/a2kntaw7/

I found some code floating around that sets up a "conditionalselect" plugin. I implemented that, and now we have some progress: http://jsfiddle.net/Lnkzp7n2/

However, the current selection is also lost -- note that NO node is selected after the event is prevented. 

I turned to the deselect_node event hoping for some help: http://jsfiddle.net/hpb0m2v0/

It doesn't appear to fire in this instance.

So, this is a question/bug report/feature request. If one wants to attach conditions to node selection, it seems the easiest thing would be stopping the select_node event. If that's the desired behavior, then the -deselection- of the current node is a bug, yeah? If the conditionalselect plugin solution is the preferred way to do this, the deselection issue persists. If there's no intended way to do this, then can we get one? A before_select event?

**Comment by vakata** [comment]
You are using an old beta of jstree. Here is an updated fiddle - conditionalselect is now part of jstree, so all you need is this:
http://jsfiddle.net/2kwkh2uL/4797/

**Comment by GRMule** [comment]
Bah! Didn't even check the plugins page, just Googled what I wanted and ended up going down a rabbit hole I didn't need to. The jsfiddles are recycled ones I found around the internet, my actual code is using the current version. Adding the old "conditionalselect" code that I did broke what was already built in, prompting me to create this issue. Sorry for the time waste.
