### ISSUE TITLE
Submit a bug

### ISSUE THREAD

**Issue by M7lrv** [vakata/jstree#1605]
First of all, this should be a bug, when plugins: [ "contextmenu", "checkbox"], with the existence of right-click will be selected, this should be bug? If not ask if you want to avoid this problem?

**Comment by vakata** [comment]
This is a setting - please read the docs on the contextmenu plugin.

**Comment by M7lrv** [comment]
Thank you, found, "select_node" This parameter is not set。About this page "https://www.jstree.com/demo/", inside the "Filebrowser demo" case inside the right-click menu js where? I can not see the source code, I would like to look at the assignment, paste the code

**Comment by vakata** [comment]
It is in the source of the page you mentioned.

**Comment by M7lrv** [comment]
Very grateful, I solved the problem, thank you.
