### ISSUE TITLE
Separate main file to jquery wrapper and widget jstree class

### ISSUE THREAD

**Issue by sashaaro** [vakata/jstree#1606]
Separete jstree.js to two files
jstree.js (where main class-prototype contents)
```javascript
var JSTreeWidget = function(element, options) {}
JSTreeWidget.prototype.addPlugin = function(...
JSTreeWidget.prototype.init = function(...
JSTreeWidget.prototype._createNode = function(...
```
and jstree.jqueryWrapper.js something like that without BC
```javascript
$.fn.jstree = function(options) {
    var instance = new JSTreeWidget(this.get(0), options) ...
   instance.addPlugin(new JSTreeDropDownPlugin(pluginOptions))
   instance.init()
....
}
```
Make more clear api and independency from jquery plagun and jquery style. 
And allow use more nice api and flexible use pure class.
Possible in future we will can remove jquery inside main class more easy.

**Comment by vakata** [comment]
This is a great idea - it is already done for v4, but I will not be porting back to v3. 

v4 has `Tree` and `Node` classes, which have no visualization, and separate renderer classes which allow for pure JS rendering, optional Virtual DOM, or even separate SVG/Canvas rendering, etc. I even plan to drop jQuery entirely, along with IE8 support.

I will have time to focus on v.4 in a month or two, so I guess I will publish the first aplha versions in early spring.
