### ISSUE TITLE
create_node cause other nodes redrawed

### ISSUE THREAD

**Issue by xd125** [vakata/jstree#1610]
we use create_node add large quntity  nodes dynamically, it happens every 200 ms, during this time, user can start to check the checkbox before the nodes, the problem is when the tree add the new nodes, looks like other nodes got redraw, it will impact user's selection if the node is redrawing.

**Comment by nikodz** [comment]
Came here with same issue.
Just in my case, I'm not using checkboxes, but I have changeable content inside node text, which resets on create_node.

**Comment by vakata** [comment]
`create_node` is not intended for adding huge amounts of nodes to the tree - it is a "user-level" function - its purpose is to visualize a node, that the user is creating via an interaction with the tree. For all other purposes - you should take advantage of the loading functions - `load_node` \ `load_nodes` and `core.data` - you have many options there (AJAX, callback, etc).
v.4 will feature a more optimized redraw mechanism, but it won't be available until spring 2017.
