### ISSUE TITLE
Search Crashes 

### ISSUE THREAD

**Issue by saumen88** [vakata/jstree#1611]
Hi

I have 3lakhs nodes in jstree loaded from ajax.
The search crashes when a specific string whose number is large.
Could anyone please suggest me some solution?

**Comment by vakata** [comment]
I can not help you without a demo, but usually this means you have duplicated node IDs. I will reopen if this is not the case and you are able to provide a demo.

**Comment by saumen88** [comment]
Hi,
I am quite sure I am not providing duplicate node id.I can only provide you the demo if you can connect to my machine remotely as I am using data from  WEBservice to build the tree.If possible please let me know.
 With RegardsSaumen Dasgupta 

    On Tuesday, 1 November 2016, 22:02, Ivan Bozhanov <notifications@github.com> wrote:
 

 Closed #1611.—

**Comment by saumen88** [comment]
Hi 
Please let me know your appropiate time so that you can take remote.
 With RegardsSaumen Dasgupta 

    On Wednesday, 2 November 2016, 10:39, Saumen Dasgupta <dasguptasaumen@yahoo.com> wrote:
 

 Hi,
I am quite sure I am not providing duplicate node id.I can only provide you the demo if you can connect to my machine remotely as I am using data from  WEBservice to build the tree.If possible please let me know.
 With RegardsSaumen Dasgupta 

    On Tuesday, 1 November 2016, 22:02, Ivan Bozhanov <notifications@github.com> wrote:
 

 Closed #1611.—

**Comment by saumen88** [comment]
Hi ,
I am unable to load a 3lakhs files at a go in jstree. I would need help on that.I am ready to pay charges for the same.Please revert if it is possible With RegardsSaumen Dasgupta 

    On Tuesday, 8 November 2016, 15:46, Saumen Dasgupta <dasguptasaumen@yahoo.com> wrote:
 

 Hi 
Please let me know your appropiate time so that you can take remote.
 With RegardsSaumen Dasgupta 

    On Wednesday, 2 November 2016, 10:39, Saumen Dasgupta <dasguptasaumen@yahoo.com> wrote:
 

 Hi,
I am quite sure I am not providing duplicate node id.I can only provide you the demo if you can connect to my machine remotely as I am using data from  WEBservice to build the tree.If possible please let me know.
 With RegardsSaumen Dasgupta 

    On Tuesday, 1 November 2016, 22:02, Ivan Bozhanov <notifications@github.com> wrote:
 

 Closed #1611.—

**Comment by vakata** [comment]
Once again - I can't help you without a demo - I can not reproduce the issue. I am currently not available for contract work.
