### ISSUE TITLE
jstree populating html with Angular2

### ISSUE THREAD

**Issue by tigrenok00** [vakata/jstree#1613]
Hi,

I want to populate the tree with HTML using Angular2 directives, like in the example below.
The problem is that it's not working, only the root element is displayed. 
Does it not support Angular2 and I must use json data?
Thank you

P.S. The *ngFor directives themselves are correct, I get the correct HTML tree when I don't use jstree.

> 		<div id="jstree-cust" class="jstree jstree-cust">
> 			<ul>
> 				<li>כל הלקוחות
> 					<ul>
> 						<li *ngFor="let a of custTree">{{a.text}}
> 							<ul>
> 								<li *ngFor="let b of a.children">{{b.text}}</li>
> 							</ul>
> 						</li>
> 					</ul>
> 				</li>
> 			</ul>
> 		</div>

**Comment by vakata** [comment]
jsTree does not work with angular out of the box, but there are a few angular directives that you can use. For example: https://github.com/ezraroi/ngJsTree
