### ISSUE TITLE
Outside element drag and drop into folder in jstree

### ISSUE THREAD

**Issue by ravenet** [vakata/jstree#1614]
Hi,

Firstly, I would say this is an extraordinary control and thank you for that. However, there is a small problem in that control when I want to drag  a element from outside the jstree and drop into the folder it is not allow to do so how we can do this or do you have options to do.

Thank you

**Comment by vakata** [comment]
Hi,

Check the accepted answer: https://groups.google.com/forum/#!topic/jstree/BYppISuCFRE

Best regards,
Ivan
