### ISSUE TITLE
The instance is called when jstree is created

### ISSUE THREAD

**Issue by leeir** [vakata/jstree#1615]
![wechatimg3](https://cloud.githubusercontent.com/assets/5330071/19996238/168e938a-a299-11e6-92eb-260fae620ac1.jpeg)

    $(function () {
      $.jstree.create('#demo',{
        'core' : {
            'data' : [
               {
                id : "1",
                parent : "#",
                text : "11111" ,
                state: {
                    opened: false,
                    selected  : true
                  }
                },

               { id: "2", parent: "1", text: "2222" },
               { id: "3", parent: "1", text: "33333" },
               { id: "4", parent: "1", text: "4444" },
               {
                 id: "5",
                 parent: "1",
                 text: "555555",
                 state: {
                    opened: false

                  }
                },
               {
                id: "6",
                parent: "5",
                text: "6666" ,
                state: {
                    selected: true
                  }
                },
            ]
        },
        checkbox: {
            keep_selected_style: false
        },
        plugins : [ "checkbox" ],
      });
      console.log($.jstree.reference('#demo').get_checked(true));

      $('#btn').click(function(){
       console.log($.jstree.reference('#demo').get_checked(true));

      })
    });

**Comment by vakata** [comment]
Use the `ready.jstree` event - the tree is not yet ready and loaded when you log for the first time.
