### ISSUE TITLE
Improvement: Allow single quotation in HTML data-attributes

### ISSUE THREAD

**Issue by Tobse** [vakata/jstree#1617]
When adding aditional data to HTML-trees, the data is ignored when formated like this:

`<li data-jstree="{'selected' : true, 'opened' : true }">Root node ...`

jstree expects: 

`<li data-jstree='{"selected" : true, "opened" : true }'>Root node ...`

If you build a jstree via HTML it may be common that you get the HTML data in the described format. 
I.e. in my case: using CakePHP with a tree-helper.

**Comment by vakata** [comment]
This is a limitation of jQuery, not jsTree, nothing I can do about that, sorry.

Best regards,
Ivan

**Comment by Tobse** [comment]
Thank you for the information. It took me some hours to figure out where the problem was :-) 

Thank you for your great work,
Tobias.
