### ISSUE TITLE
Stop loading/opening tree nodes, when the user clicks on a node

### ISSUE THREAD

**Issue by dominiklaube** [vakata/jstree#1622]
When using the state plugin, the tree will restore the last state. That's fine. Now we have deeply nested trees, so that loading the last state will take some time. Clicking on an node will navigate the user to another page. Now imagine the user clicks on a node while the tree is loading. Wouldn't it be nice if the tree now stops loading? If loading does not stop and the user clicked, the "clicked state" of a node will than be applied to the last opened node and not to the node the user really wants. How can we fix this?

**Comment by Baedda** [comment]
Yes this would be a really nice feature. We use the jstree for a file browser in our cms. When the user comes back the tree loads up the last visited file folder - what is great. But if the user clicks on another folder while the tree is still loading then the clicked folder opens up. But then after the tree finished loading it sets it state to the state that is safed in local storage and the old folder shows up what is a litte bit annoying. 
We fixed this on our side by showing a progress bar until the tree is completly loaded. It would be much nicer if the tree would stop loading its safed state if the user clicks on a folder while loading.

**Comment by vakata** [comment]
Thank you for the idea - I will get on it. 

In the mean time you can use a loading indicator and stop any user interaction with the tree. I would also recommend using the massload plugin which will load all nodes needed to recreate the state in a single request (a much better user experience). 

I will get back to you soon with a fix for this.

**Comment by vakata** [comment]
The fix is in, keep in mind this will only prevent changing the selection - the nodes will still be loaded (and opened), but selection will not be lost.

**Comment by dominiklaube** [comment]
Good job. Thank you.
