### ISSUE TITLE
select_node function not working if node is not visible

### ISSUE THREAD

**Issue by selamialtin** [vakata/jstree#1623]
select_node function not working if node is not visible.

i try to select hidden node with select_node function, this operation not firing any error, but i can not get that selected nodes by get_selected function, only visible nodes are returning this function, i'm not sure get_selected function may be causing problem or select_node function.

**Comment by vakata** [comment]
I am afraid this is not true - can you provide a demo? Keep in mind you need to use a node ID, not a selector when invoking `select_node` and also make sure the node is actually loaded - if you are using lazy loading and are trying to select a node that jstree is not aware of - it will not work. 
I will reopen on more information.

**Comment by tcharlss** [comment]
I have the same issue, `select_node` doesn't seem to work unless the node is already visible, even with `prevent_open` set to false.

This doesn't work :
```
$(plan).bind('ready.jstree', function(e, data) {
   $(this).jstree('select_node', $(plan + ' li.expose'), true, false);
}
```

But this does :
```
$(plan).bind('ready.jstree', function(e, data) {
   $(this).jstree('open_all);
   $(this).jstree('select_node', $(plan + ' li.expose'), true, false);
}
```

Using version 3.3.4

**Comment by vakata** [comment]
Do not use a DOM selector - jstree will only keep visible nodes in the DOM - select the node by its ID (not a CSS selector) and it will work.
