### ISSUE TITLE
When show_only_matches_children is set to true,it doesn't work!

### ISSUE THREAD

**Issue by LucienLaw** [vakata/jstree#1628]
I'v set show_only_matches as true and show_only_matches_children as true,but the child nodes of matched nodes still hide.
I code it with ngJsTree.
`$scope.treeConfig = {
                'plugins': ['types', 'dnd', 'search'],
                'search': {
                    show_only_matches: true,
                    show_only_matches_children: true
}`

**Comment by vakata** [comment]
Here is a demo: http://jsfiddle.net/DGAF4/1691/
It obviously works as it should, provided you did not set the `show_only_matches_children` config option. If you still have problems - contact whoever made the angular directive.
