### ISSUE TITLE
angular2 ViewEncapsulation.Native plugin not working

### ISSUE THREAD

**Issue by baaroz** [vakata/jstree#1629]
Hi

when using jstree plugin in angular2 and encapsulation is set to  ViewEncapsulation.Native(create shadow doom) the plugin doesn't work at all.set encapsulation to  ViewEncapsulation.none and the plugin works again.

**Comment by vakata** [comment]
Sorry, the issue is probably angular related - you might want to discuss this with the angular directive you are using. If there is any way for me to help - let me know.
