### ISSUE TITLE
Checkboxes with All Nodes selected causing lag in expand

### ISSUE THREAD

**Issue by dhruv1790** [vakata/jstree#1630]
I have a tree with more than 10K nodes and 5 levels. In my index page I use jstree on Modality div to filter content of my grid. By default, all nodes are selected. With all nodes selected, when I expand the tree levels, it lags which is observable. But when nodes are not checked or selected, there is no lag in expand. If I decrease the levels, lag is not observable.
Could you please help resolve the lag I am facing for expand?

Default state when tree loaded.

 $('#modalitySystemTypeFilter').jstree({
        "core": {
            "themes":{
                "icons":false
            }
        },
        "checkbox": {
            "keep_selected_style": false
        },
        "plugins": [
           "dnd", "search", "wholerow", "checkbox"
        ]
    });

    $('#modalitySystemTypeFilter').jstree(true).select_node('Modality-All');
    $("#modalitySystemTypeFilter").jstree("open_node", $('#Modality-All'));

**Comment by vakata** [comment]
Could you please let me know which version of jsTree you are using? A demo of the issue would be helpful as well.

**Comment by vakata** [comment]
Closing this for now because no further information was provided, will reopen on more information.
