### ISSUE TITLE
Suppressing events

### ISSUE THREAD

**Issue by Spookenator** [vakata/jstree#1637]
Hi,

Thank you for your continued efforts with JSTree, without it, most of my web projects would die a slow and horrible death.

I was wondering if it possible to suppress events. I have a scenario where i have multiple concurrent users looking at a tree using websockets. A user executes move_node. The problem is, that once i execute move_node, it fires the event which triggers all clients(using websockets) to execute move_node, causing a endless loop.

Unfortunately i cant refresh the state instance of the tree, as the tree is currently 41k nodes, and other connected users will have a tree rebuilding constantly as people are making changes to the structure.

**Comment by vakata** [comment]
Hi,

I believe you may try a few things:
- check if moving would make a difference and if not - do not commence with the move
- you can also use a state variable - for example keep the last move event data and if a new move comes from the socket - do not execute it if it matches the last state
- the final option - if you need to modify what events get triggered - take a look at this: https://github.com/vakata/jstree/blob/master/src/misc.js#L4

Let me know if you need any help.

Best regards,
Ivan
