### ISSUE TITLE
Adding tooltip in nodes

### ISSUE THREAD

**Issue by mohammedibrahimlj** [vakata/jstree#1638]
Hi,

how to add dynamic tooltip in every node in jstree node.

thanks,
Mohammed Ibrahim

**Comment by vakata** [comment]
You can set a title attribute on any of the nodes (use `a_attr` when feeding JSON to the tree - look it up in the docs) - that means there will be a browser tooltip. If you need a fancier tooltip use any of the available libraries, just keep in mind nodes are added to the DOM when their parent is opened, so either use a lib that uses event delegation, or initialize the tooltip every time a node is opened (using the `open_node` event).

**Comment by naganand123** [comment]
I want to implement the Tool Tip to show count of child nodes.
How to implement tool tip in JSTree. Please provide any examples.

**Comment by agnesgrusteven** [comment]
Got any examples @naganand123 

@vakata , Thanks for the wonderful plugin 🥇 

I am using JSON data for my JSTREE. I have also referred to the doc. But could not find any samples or details on how to add a tooltip while clicking any nodes.

@vakata Could you please provide me any hint or sample ??
