### ISSUE TITLE
jstree working unexpectedly

### ISSUE THREAD

**Issue by baaroz** [vakata/jstree#1639]
I have a long json that populate the tree using this code

 ```
 jQuery('#data').jstree({
            'core': {
                "check_callback": true,
                "themes": { "stripes": true },

                'data': d

            }
        })
```
first load everything seem normal, but when trying to open child's node the tree working unexpectedly.
after opening one of node the tree disappear.on other node the order of the tree change incorrectly, place root inside other child nodes.

any idea what causing this bug?

**Comment by vakata** [comment]
This means you have duplicate IDs in the data you pass to jstree. Ensure that the IDs are unique (or omit them).
