### ISSUE TITLE
Do not want to drag inside,how to do？

### ISSUE THREAD

**Issue by zjl1985** [vakata/jstree#1640]
hello,
I use dnd plugin,but  I only want to drop to before and after ,not inside

Where can I set or write :)

**Comment by vakata** [comment]
Use the `core.check_callback` setting as function and prevent all inside drops - I would recommend logging out what parameters you get while dragging, You'd probably want to return `false` when `more.plugin` is `dnd` and `more.pos` is `"i"` (if I remember correctly). Let me know if you need further assistance.
