### ISSUE TITLE
Prevent checking parent by checking all children

### ISSUE THREAD

**Issue by vitaliy-patsay** [vakata/jstree#1643]
Hi @vakata ,

Thanks for the great plugin. Not really an issue. It's more a use case. Is it possible to configure jsTree (with checkbox plugin) to not to select parent node by selecting all its children. At the same time I'm satisfied with cascade up when unchecking some of children and setting undetermined/unchecked. 

The reason is that we can add more branches for the root on serverside, so selecting all CURRENT branches is not necessaryly selecting root.

**Comment by vakata** [comment]
Hi, 

you can use the `checkbox.cascade` option and prevent the UP propagation:
https://www.jstree.com/api/#/?q=cascade&f=$.jstree.defaults.checkbox.cascade

Try using `down+undetermined`. Aside from that there are no further config options, if you want to achieve something more you'd have to listen for checked events and react accordingly.
