### ISSUE TITLE
API for setting state

### ISSUE THREAD

**Issue by sauliuni** [vakata/jstree#1644]
Im using jstree in angularjs, and i have problems setting explicit the state of all nodes  (e.g. hidden). The helper functions like `set_type` or `rename_node` are very convenient for usage with bi-directional binding, but i cant find any (except private ones) where i can set state of the node.

In my use case i hide some nodes in search callback, and after the search is completed the nodes are still hidden. Im using now a workaround, calling show_all()

**Comment by vakata** [comment]
Well, you can use `hide_node` & `show_node` if that is what you are after. 

Or if you really want to modify anything the internal state - use `instance.get_node("NODE_ID").state.some = "value"`, but I'd advise against modifying the internal state unless you are really sure that it won't affect how the tree works. Use at your own risk.

**Comment by sauliuni** [comment]
Thanks!
