### ISSUE TITLE
Editing titles with counters

### ISSUE THREAD

**Issue by activestylus** [vakata/jstree#1646]
I've got a counter for some folders, the number is fetched from the database and stored in data attr of `node.li_attr`.

http://jsfiddle.net/DGAF4/1740/

The only problem I am having is updating the title with a double click.

As you can see it includes the counter span element in the input text.

Is there a way to filter this out so when you double click only the title itself shows up in the text field?

**Comment by activestylus** [comment]
Made a tiny bit of progress here. I can now edit the raw title, but when I hit return and commit the change, I lose my counter span. Is there an after save callback where I can restore this span to its rightful place?

http://jsfiddle.net/DGAF4/1742/

**Comment by vakata** [comment]
It would be better to use a plugin but this will work too:
http://jsfiddle.net/DGAF4/1744/

**Comment by activestylus** [comment]
Awesome! Never even used jquery `end()` before. Very useful indeed
