### ISSUE TITLE
Event for loading data on expand button/icon

### ISSUE THREAD

**Issue by sauliuni** [vakata/jstree#1647]
I have problems for identifying the right event. In my use case i want to load data via ajax if user clicks on the expand/open node icon. I trying to use the 'node_open', 'before_open' or other events for nodes, but they are not triggered if the data does not exist. 

The parent nodes have already a tag `children = true`, so that users can visually see that it can be opened. 

If i disable the ajax load, and use my other approach by loading the data completely from server on one shot, the events like 'node_open' are fired.

Witch events suits best for my described use case?

**Comment by vakata** [comment]
You do not need the events. Take a look at the `core.data` option (all you need for AJAX loading):
https://github.com/vakata/jstree#populating-the-tree-using-ajax-and-lazy-loading-nodes

If you need something more flexible (and async as well) use the function approach:
https://github.com/vakata/jstree#populating-the-tree-using-a-callback-function
