### ISSUE TITLE
Open node from tree root is not possible

### ISSUE THREAD

**Issue by sauliuni** [vakata/jstree#1649]
Hello,

i wanted to open the node using the jsTree instance with `treeInstance.open_node(nodeFromEvent)`, where the `nodeFromEvent` is a node that it is passed by node_selected event. Unfortunately i saw in the jsTree sourceCode that if the `obj.id === $.jstree.root`, the opening of the nodes is skipped. But its what i want to use, since i want to control what happens if nodes are selected and then, reuse the e.g. `before_open` events to do my own calculations for each children. Could you clarify the design decision of this event, and maybe give a hint how can i propagate opening events for the children and their children without big interference in jsTree code?

**Comment by vakata** [comment]
I am afraid you are doing something wrong - the `jstree.root` is not what you think it is. 
It is not a root node that you can see - it is an "invisible" parent over your root nodes. As such - it has no UI, can't be opened and can't be selected. 
If you provide a demo of what you are trying to do I may be able to help you debug.
