### ISSUE TITLE
SQL: Move nodeName to struct-table or even merge all to one table

### ISSUE THREAD

**Issue by Toppi68** [vakata/jstree#1650]
Hello Ivan :)
i just implement your tree in one of my project - really good work - big thank for it!

But - what do you think about to put at least the nodeName to the struct-table?

So its going to be much more easier to trigger the database on update/insert/delete
Otherwise you have to trigger always two tables by differnt sql-statements (its mad).

I rewrite your php-class in a few minutes (merge all in one table) and its much more easier on the sql-side.
The use of two tables as a 1on1 relation seems to be a little useless at all (imo)

Just an idea.

Thank you very much
Michael

Example:
I used it now for a high perfomant search-index.

getNodeByPath( md5('root/node1/node2/abc.html') );

By using a trigger for a sites_tree_index table

CREATE TRIGGER `sites_tree_data_setMD5path_AFTERINSERT` AFTER INSERT ON `sites_tree_data`
 FOR EACH ROW BEGIN          
                    SET @newPath = (
                        SELECT (GROUP_CONCAT(t1.nodeName ORDER BY t1.lft SEPARATOR '/')) as path
                        FROM sites_tree_data t1
                        WHERE 
                        t1.lft <= NEW.lft 
                        AND t1.rgt >=  NEW.rgt
                        AND t1.lft > 1
                        ORDER BY t1.lft
                    );
                    INSERT INTO sites_tree_index (id, md5Path) 
                    VALUES 
                    (NEW.id, MD5(@newPath))
                    ON DUPLICATE KEY UPDATE md5Path=MD5(@newPath);
                END

**Comment by vakata** [comment]
Hi,

The PHP / SQL demo is not part of jstree - it is just something quick I built a few years back - feel free to modify it - it is just an example - not part of jstree and I do not support it.

There is a PHP class I use regularly if you are interested, but it is also pretty basic: 
https://github.com/vakata/phptree

Best regards,
Ivan
