### ISSUE TITLE
Block access to demo filebrowser

### ISSUE THREAD

**Issue by Guite** [vakata/jstree#1651]
When jstree is included using composer there is a potential security risk which has been reported to us at https://github.com/zikula/core/issues/3260 because everybody can access the filebrowser demo.
For the meanwhile we fixed that by adding a custom rewrite rule blocking these requests, see https://github.com/zikula/core/pull/3261
It would be better though if jstree would provide some protection out of the box, as this could affect multiple projects using it.

**Comment by vakata** [comment]
Thank you for notifying me, I will remove the demos from this repo and move them to a separate one.
