### ISSUE TITLE
Allow programatically manipulate the tree, but not via the UI

### ISSUE THREAD

**Issue by bs-thomas** [vakata/jstree#1652]
I followed the API manual here (https://www.jstree.com/api/#/?f=get_container()) to programmatically copy_node().  This worked well.

However, I would like to prevent users from using the "Hold Ctrl + drag" user interface shortcut to copy a node.  But once I define core.check_callback() to "return false" when operation == 'copy_node', my programatically called API stops working as well.

Is it possible to make the API calls still work, but user interface to not work?

I'm facing the same problem with create_node() and other similar operations.

Your help is greatly appreciated.

Cheers,
Thomas

**Comment by vakata** [comment]
I will think of a way to improve on the situation for version 4. As for v.3 - you can disable drag'n'drop by not loading that plugin, and the only way for a user to create a node using jstree's default modules is to use the contextmenu - if you do not want that - make sure the option to create is not there (or disable the plugin all together).
Also - if you log out what you have available in `check_callback` you will see that usually if the action happened as a result of user interaction you get the event that caused this - so if that is missing - it was a programmatic call.
As I said - that is not very convenient but it works, any further improvements will be added to v.4, as any general change would require a major version bump anyway.

**Comment by bs-thomas** [comment]
Understood, and thanks for the assistance.

Just one question, when approximately will v4 be released?  Anytime soon, or might take a while?  I was just trying to decide between waiting, and going for the method you suggest above.

Thanks!
