### ISSUE TITLE
tmp.state is undefined

### ISSUE THREAD

**Issue by xulinyang** [vakata/jstree#1653]
Enabled checkbook plugin and select the ID=41 of the node and its sub-nodes, but my refresh_node (41) will be error, the error message: tmp.state is undefined -jstree.js (5269, column 9), thank you!
--from China

**Comment by vakata** [comment]
Please provide a demo of the issue (for example jsFiddle), this is not a known issue and the description is not enough, so I can not help you without a demo. I will reopen when you provide a demo.
