### ISSUE TITLE
Replacing existing li_attr or a_attr values.

### ISSUE THREAD

**Issue by JackDarth** [vakata/jstree#1654]
Hi 

I tried to use li_attr or a_attr to replace the existing value but it was not successful.  Can you tell me how can I replace the value on those generated li_attr or a_attr with custom values?

Thanks.

**Comment by vakata** [comment]
Provided you are using JSON as a data source, - just include the attributes you want in the definition of the node, for example:
```js
$('#tree').jstree({
  core : {
    data : [
      { text : 'Some text', a_attr : { 'href' : 'https://google.com' } }
    ]
  }
});
```

Here is an example:
http://jsfiddle.net/DGAF4/1763/
