### ISSUE TITLE
Remove default '#' on link

### ISSUE THREAD

**Issue by twoeo** [vakata/jstree#1655]
As title refers,
If there is `href` on `<a>`, it would show a status bar when mouse over the link.
Even `a_attr: {href: ''}` not works, still have a status bar.

Maybe it's better to remove the default value `#` on `<a>`,
that is no `href` attribute on `<a>` by default.

**Comment by vakata** [comment]
That would make the markup invalid. You can replace the A tag with a SPAN by overriding the `_create_prototype_node` method https://github.com/vakata/jstree/pull/1616
