### ISSUE TITLE
While removing parent node it also remove its child

### ISSUE THREAD

**Issue by gauravoodles** [vakata/jstree#1656]
Hi, 
I'm having an structure like when I select any node, it appears in the search box with a cross icon with all its childs. But when I delete that parent node from the search box all the child elements also gets deleted, but I don't want that. I want that if I click on the parent node only that particular node gets deleted and all the childs remains same. Is there any way to do that ?

Regards,

**Comment by vakata** [comment]
Sorry, no this is not possible using any built-in method, as there is no place for those children to go. But you can easily achieve this in your code - before deleting the node move all its children to whatever new location you need them to go to.
