### ISSUE TITLE
How to add cascade property on click of some other element

### ISSUE THREAD

**Issue by gauravoodles** [vakata/jstree#1658]
Hi, 
I'm having a structure like when I click on parent node its all the child appears in a text box with a delete option. And if I delete the parent  all its child got deleted. So, Is there any way that I can add cascade property to my tree structure on click of that delete button, and after that If I again click on the parent node  in the tree than cascade property should remove. Any suggestions?

Regards,

**Comment by vakata** [comment]
Sorry, I could not understand what you mean. If you mean you want to traverse down a node's children and grandchildren, etc - you can do that - all the node's descendant IDs are stored in a `children_d` property on the node. So you can use:
```
instance.get_node(id).children_d
    .map(function (x) { instance.get_node(x) })
    .forEach(function (x) {
         // do whatever you need with the node (add a property, clear a property, etc)
    })
```

If this is not what you need - please clarify.

**Comment by gauravoodles** [comment]
Hi,
Let me clear this thing.
I'm having a js tree structure with checkbox in which if I select the parent node than all its elements appears in a textbox (which is perfect as per my requirement) above in the form of tags like the below image.
https://cloud.githubusercontent.com/assets/12791621/21007532/4ac706fc-bd63-11e6-98e0-7f8068652b40.jpg

But the thing is that if I delete the parent node its child also gets deleted. And my requirement is that if I parent node only that parent tag delete, not all the child they should remain in that box. Any suggestion?

Regards,

**Comment by vakata** [comment]
Sorry, this is very custom functionality - I wouldn't know where to begin. I am afraid I can't help you - I only maintain jstree which is a lib to visualize trees, whatever you do with the textbox you mentioned is up to you.
Normally in a tree if you delete a node all its descendants are also deleted, as they have nowhere to go. If you want to change that - use custom code - move them to a new location before you delete the parent or decouple your textbox from the actual tree.
