### ISSUE TITLE
Remove parent node instead of child

### ISSUE THREAD

**Issue by gauravoodles** [vakata/jstree#1659]
Hi,
This is in the reference of this issue:
https://github.com/vakata/jstree/issues/1658

I'm having a js tree structure with checkbox in which if I select the parent node than all its elements appears in a textbox (which is perfect as per my requirement) above in the form of tags like the below image.
https://cloud.githubusercontent.com/assets/12791621/21007532/4ac706fc-bd63-11e6-98e0-7f8068652b40.jpg

But the thing is that if I delete the parent node its child also gets deleted. And my requirement is that if I parent node only that parent tag delete, not all the child they should remain in that box. Any suggestion?

Regards,

**Comment by vakata** [comment]
Please keep the discussion in a single thread, as I told you in the other ticket - this is something custom you are doing - I can't help you with it - I maintain jstree which visualizes trees - whatever you do with a textbox full of tags is up to you. In a tree if you delete a node its descendants are also deleted, if you want to change that - use custom code to move the parent's children to a new location before deleting the parent.
