### ISSUE TITLE
Numerical instead of icons

### ISSUE THREAD

**Issue by rocchidavide** [vakata/jstree#1660]
How can I set numerical instead of icons for each node? Something like ol:

1. foo
   1.1. bar
2. cletus

**Comment by vakata** [comment]
There is a n experimental plugin for that - include it in your page and activate it on you instance: 
https://github.com/vakata/jstree/blob/master/src/misc.js#L182

As for the icons - disable them using `core.themes.icons` : 
https://www.jstree.com/api/#/?q=icon&f=$.jstree.defaults.core.themes.icons

**Comment by rocchidavide** [comment]
I tried numbering plugin, but it doesn't work. I add in config object:

"plugins": ["numbering"]

and i disable icons

**Comment by vakata** [comment]
As I said - you also need to include the experimental plugin to your page. It is NOT included in the build.

**Comment by rocchidavide** [comment]
Thank you for your response.
Since i'm using ES6 and i'm import jstree with its modules, is it possible to import also misc.js?
