### ISSUE TITLE
<select> inside a node text

### ISSUE THREAD

**Issue by izn** [vakata/jstree#1663]
Check my fiddle: https://jsfiddle.net/kedfh74x/2/

**Is there a way to have a working `<select>` inside my Tree?**

I have a list (`ul li`) with some options.

I need to link a node from this list in the **same level** on a existing tree node with a `<select>` with all previous options linked in this node.

The main idea is to have N options in the same node.

Thanks!

**Comment by vakata** [comment]
The only way to achieve this would be by creating a plugin and carefully binding and unbinding the default click events. I am afraid I can't help you with this.

**Comment by izn** [comment]
@vakata How can I bind/unbind the default click events? I'm trying to figure out why click is "disabled" on nodes. Thanks in advance!

**Comment by vakata** [comment]
Take a look at the code - it uses jQuery `.on()` but on the tree container (event delegation). If you want to provide your own event handlers - use `.off`, all jstree events are in the `.jstree` "namespace" so you can easily unbind: `$('#tree').off('click.jstree')`.

As for why - well, jstree's nodes are anchor elements, if the click is not handled it will cause a navigation.

**Comment by izn** [comment]
Just for information...

I've solved using `selectpicker`. It works 'cause this plugin creates a new dropdown menu div outside the tree.

https://github.com/silviomoreto/bootstrap-select
