### ISSUE TITLE
only Root Nodes Getting Selected

### ISSUE THREAD

**Issue by arunkumargutluri** [vakata/jstree#1665]
not sure whats problem with my jstree. i am not able to select any node.by default parent node is getting  selected. need your help ASAP.

Please look for the attached file.

 Please find  below page.I am trying to implement in asp.net MVC
.chtml
----------------
<div id="divTreeview">
                    <ul>
                        @foreach (var parentnode in Model)
                        {
                            <li id="@(parentnode.ParentNodeId)" data-jstree='{"opened":true,"icon":"@(parentnode.ParentNodeIcon)"}' status="@(parentnode.RunStatus)">
                                @(parentnode.NodeText)

                                @if (parentnode.NoofChildNodes > 0)
                                {
                                    <ul>
                                        @foreach (var childnode in parentnode.objChildNodes)
                                        {
                                            <li data-jstree='{"icon":"@(childnode.ChildNodeIcon)"}'>
                                                <a href="#" id="@(childnode.ChildNodeId)" status="@(childnode.RunStatus)" title="@(childnode.ErrorDescription)">
                                                    @(childnode.NodeText)
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                }
                            </li>
                        }
                    </ul>
                </div>
-------
Script 
-------

   $(document).ready(function () {
tried option 1:
            //$.jstree.defaults.core.themes.variant = "large";
            //$('#divTreeview').jstree();
Tried Option 2:
            $("#divTreeview").jstree({
                "plugins": ["ui"],
                "ui": { "initially_select": ["#ref565"] },
                "core": {
                    "initially_open": ["#ref565"],
                    "open_parents": true,
                    "load_open": true
                }
            }).bind("loaded.jstree", function (e, data) {
                $('#divTreeview').jstree("select_node", '#ref565', true);
            })
        });

I have included necessary script and css as specified in 

https://www.jstree.com/

[problem.txt](https://github.com/vakata/jstree/files/648481/problem.txt)

**Comment by arunkumargutluri** [comment]
<div id="divTreeview">
                    <ul>
                        @foreach (var parentnode in Model)
                        {
                            <li id="@(parentnode.ParentNodeId)" data-     jstree='{"opened":true,"icon":"@(parentnode.ParentNodeIcon)"}' status="@(parentnode.RunStatus)">
                                @(parentnode.NodeText)

                                @if (parentnode.NoofChildNodes > 0)
                                {
                                    <ul>
                                        @foreach (var childnode in parentnode.objChildNodes)
                                        {
                                            <li data-jstree='{"icon":"@(childnode.ChildNodeIcon)"}'>
                                                <a href="#" id="@(childnode.ChildNodeId)" status="@(childnode.RunStatus)" title="@(childnode.ErrorDescription)">
                                                    @(childnode.NodeText)
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                }
                            </li>
                        }
                    </ul>
                </div>

**Comment by vakata** [comment]
Sorry, but this is not a problem with jstree, but with your code. As you can see on all of the demos - selecting nodes works just fine. 
It seems to me you are using v.1 code, v.1 is no longer supported and has not been supported for years. If you are in fact using v.3 - please update your code and then provide a demo of the problem if it is still there.
