### ISSUE TITLE
quotes in `data-jstree`

### ISSUE THREAD

**Issue by vmarquet** [vakata/jstree#1668]
I lost 3 hours because `data-jstree="{'icon':'jstree-file'}"` is not equivalent to `data-jstree='{"icon":"jstree-file"}'`... (notice the quotes) ...

Solution: accept both combinations:

* outer `'` and inner `"` (currently supported)
* outer `"` and inner `'` (currently failing silently)

**Comment by vakata** [comment]
This is not something that can be changed inside jsTree. As you probably know jsTree uses jQuery under the hood - this limitation comes from jQuery's `.data` method, so there is nothing I can do. 
As far as I know single quotes are the only supported way of defining data attributes with JSON in them.
