### ISSUE TITLE
Is there a way to skip particular node creation?

### ISSUE THREAD

**Issue by am11** [vakata/jstree#1671]
I have a complex grouping object, where some nodes have flagged (text) values that need to be skipped discretely.

As far as I have understood, `create_node.jstree` event gets fired after the node has been created?

I am trying to do something like:

```javascript
$mytree.on('something_like_____onNodeCreation___before__create_node.jstree', function (x, y, z) {
   if(validateAncestry (x,y,z,this)) {
     return $mytree.createNode.call(this, x, y, z);
   }
  // and hence we skipped the node creation when `validateAncestry()` returned falsy
  // note this will not skip the children of this node (whole branch)
});
```

I can certainly control this flow on server-side, but since the object graph is quite complex, I am contemplating the option to handle it with jstree without cluttering my server-side recursive implementation (with flow control statements).

Is it possible?

**Comment by vakata** [comment]
I am afraid this is not possible - `create_node.jstree` fires when a node is created as a result of calling `create_node`, no when loading data, basically it is a result of user interaction. 
There is no way to intercept loading of nodes, I am afraid you will have to do this on the server side.
