### ISSUE TITLE
Errors When Creating Nodes While Nodes Are Loading

### ISSUE THREAD

**Issue by dkristo1** [vakata/jstree#1672]
I've been experiencing a number of different errors in a project I'm working on that seem to occur when attempting to create nodes while other nodes are in the loading state.  I've simplified my code as much as possible and created this minimal fiddle which demonstrates the issue.

Typically if the timing is such that all nodes are created before loading occurs things will go smoothly.  If the timing is such that a node is created after loading of another node has already started there will be an error thrown, the tree will be in a crashed state with loading animation running indefinitely.

https://jsfiddle.net/o2rjx9fe/16/

**Comment by vakata** [comment]
Thank you for the report. I simplified the fiddle a bit:
https://jsfiddle.net/o2rjx9fe/17/

Disabling the worker fixes the issue:
https://jsfiddle.net/o2rjx9fe/18/

`create_node` is not designed to "load" nodes, the idea behind create node is to be used on the user side, not to populate the tree with it. So the method does not take care to move the whole structure in and out of the worker thread - this is what causes the problem. 

This behavior will change with v.4 where there won't be separate load / create operations. I will not try to resolve the issue, as the fix above (disabling core.worker) should be enough, I'd rather focus on v.4.
