### ISSUE TITLE
Edit node after creation with sort plugin enabled

### ISSUE THREAD

**Issue by Llorx** [vakata/jstree#1673]
I have this code:
```js
tree.jstree("create_node", "#", obj, "last", (function(node) {
    tree.jstree("edit", node);
}).bind(this));
```

The idea is to let the user create a node and edit it inline inside the tree. Works fine but when I enable the `sort` plugin it stops working.

I guess because the thing goes this way:
 - Node created.
 - callback fired, so edit is called.
 - `sort` detects the addition, so reorders, breaking the edit.

Is there a better way of editing a node right after creating it?

**Comment by vakata** [comment]
Add a `setTimeout` to the mix. - wrap the `.edit` call in a `setTimeout(function () { ... }, 0)`. I will try to improve on this in v.4, but for now it should work properly.

**Comment by Llorx** [comment]
Ok, I'll try it. Thanks.
