### ISSUE TITLE
Anyone knows how to use jstree with webpack, thanks ?

### ISSUE THREAD

**Issue by imjamespond** [vakata/jstree#1675]
i try to import jstree.js in webpack project but i got this error
Uncaught ReferenceError: _typeof is not defined

**Comment by vakata** [comment]
Sorry, I can't help you, but judging from the error message I doubt this is an issue with jstree itself. I will bundle it with webpack in a few days - I will let you know if there were any issues I had to solve.

**Comment by imjamespond** [comment]
thanks, i have solved this problem by importing jstree installed  from npm and this error disappear. while before i import the source code directly

**Comment by ReynerHL** [comment]
Does anyone have an example for use jstree with webpack ?? :(

**Comment by ReynerHL** [comment]
@imjamespond can you provide some code examples please? After imported as a npm module in a VueJS project, it seems to fail registration with jQuery. Calling $('#myTreeDomEl').jstree({"..."}); falls in a error telling us that jstree is not a function.

**Comment by imjamespond** [comment]
maybe you didn't register jstree properly, and these code works fine for me
npm install --save jquery jstree
in webpack.config.js
    new webpack.ProvidePlugin({
		$ : "jquery",
		jQuery : "jquery",
		"window.jQuery" : "jquery"
	})
	]
....
import 'jstree';
$('#jstreeDiv').jstree({"plugins" :{"dnd", "search", "state", "types", "wholerow"}....

**Comment by auspex** [comment]
This is still an issue, though not directly related to `jstree`. It's caused by `babel`, so won't be an issue if you're not using `babel` as well as `webpack`. It popped up in a completely unrelated tool: https://github.com/mapbox/mapbox-gl-js/issues/3422

The fix is to add `exclude: /jstree/` to the `babel-loader` options:
```
                    loader: 'babel-loader', options: {
                    	exclude: /jstree/,
                    	...
                    }

```
