### ISSUE TITLE
generate JSON from jstree

### ISSUE THREAD

**Issue by sadhnaprajapati** [vakata/jstree#1676]
help to generate JSON data from a jstree

**Comment by vakata** [comment]
Please, read the docs:
https://www.jstree.com/api/#/?q=json&f=get_json([obj,%20options])

**Comment by sadhnaprajapati** [comment]
I got this JSON data from jstree

{"id":"j1_1","text":"Root","icon":"glyphicon glyphicon-flash","li_attr":{"id":false},"a_attr":{"href":"#","id":"j1_1_anchor"},"state":{},"data":false,"parent":"#","type":"default"}]

but i want to get only id and text.help me solve it...


Thanks

**Comment by vakata** [comment]
Loop through the array (or use the native JS `.map` function) and leave only what you need.
