### ISSUE TITLE
Filebrowser add folder and file icon dynamically using jsp

### ISSUE THREAD

**Issue by mosfiz** [vakata/jstree#1680]
Hello vakata,
I want to use your Filebrowser concept to generate the tree dynamically with folder and file icon. How could i add separate icon for folder and file?. if i use "types" plugin **default** as folder icon and also add **file** icon then all file and folder gets the same default icon. I am trying to understand your Filebrowser Demo concept. However, you used php to differentiate the file and folder while i am trying to solve with jsp and java code. 
could you please help me as because i am new in jquery and jstree. 

$(function() {
    $.ajax({
        async : true,
        type : "GET",
        url : "<%= sessionBean.getAppBean().getContext() %>/pages/dipFolderTreeJsonScript.jsp",
        dataType : "json",  
  
        success : function(json) {
            createJSTrees(json);
        },    

        error : function(xhr, ajaxOptions, thrownError) {
            alert(xhr.status);
            alert(thrownError);
        }
    });
});    

function createJSTrees(jsonData) {
    $("#container").jstree({
    
    	plugins: ["search", "themes", "types"],
    	
	    'core': {
	      'data': jsonData
	    },
	    types: {
	        
	        "default" : {
	        	'icon': 'jstree-folder'
	        },
	        'file' : {
	            'icon': 'jstree-file'
	        }
	        }
	    
    }).on('open_node.jstree', function (e, data) { data.instance.set_icon(data.node, "glyphicon glyphicon-minus"); 
    }).on('close_node.jstree', function (e, data) { data.instance.set_icon(data.node, "glyphicon glyphicon-plus"); });
}

**Comment by vakata** [comment]
It comes from your data - supply a `type` property for each node, for example `"type" : "file"`
