### ISSUE TITLE
Possible to use folder icon, file icon

### ISSUE THREAD

**Issue by phpmydev** [vakata/jstree#1682]
I wonder how to use folder icon when there are children and file icon when no more children?
![jstree](https://cloud.githubusercontent.com/assets/746353/21722256/098e3ae2-d3e9-11e6-8fd1-52bcb7e63dba.png)

**Comment by phpmydev** [comment]
I see that this question was asked 2 days ago by another user.  Is there an easy way to use both folder and file icons depending on children (folder)  or lack of (file)?  Thank you!

**Comment by phpmydev** [comment]
I have this
	data-jstree="file" in one node and data-jstree="folder" in another
with:		
		types : {
						file : {
							icon : "jstree-file"
						},
						folder : {
							icon : "fa fa-folder"
						}
					},
and this just shows folders everyhwere

**Comment by vakata** [comment]
The data-jstree attribute should be valid JSON, like: `data-jstree='{"type":"folder"}'` (notice the single quotes).
