### ISSUE TITLE
Question] outline blue box???

### ISSUE THREAD

**Issue by adam0605** [vakata/jstree#1685]
hi. I using jstree, ngjstree (angular 1.5x) 

if my web site jstree outline click , I see a blue outline box.

and jstree homepage same.

how to delete blue box?

![outline](https://cloud.githubusercontent.com/assets/15608069/21886246/4791f396-d8fe-11e6-88aa-fc68c1543673.jpg)

![outline2](https://cloud.githubusercontent.com/assets/15608069/21886242/44fa28ce-d8fe-11e6-875e-b2e47cd092a6.jpg)

**Comment by vakata** [comment]
This is not part of jstree's css - sorry. Maybe this is something your browser does, when dealing with focused elements? Anyway - you can try to remove it using CSS: ```.jstree, .jstree:focus { outline:none; }```

**Comment by adam0605** [comment]
Thank you!!!! 
I solve it.
