### ISSUE TITLE
[Question/Problem] - Scroll while DND is enabled

### ISSUE THREAD

**Issue by graphefruit** [vakata/jstree#1687]
Hello @vakata, 
is it possible to scroll the page on a smartphone/tablet (touch) when Drag & Drop is enabled?

The problem is, if you got a larger amount of folders which covers the whole screen area, you cant scroll left or scroll top, because the drag & drop event will get executed and the scroll event cant even start.

Any suggestions?
Thanks & Greetings
Graphefruit

**Comment by vakata** [comment]
Hi,

You can set `dnd.touch` to `"selected"`:
https://www.jstree.com/api/#/?q=dnd.touch&f=$.jstree.defaults.dnd.touch

**Comment by graphefruit** [comment]
Thank you! Man this plugin is so incredible awesome
