### ISSUE TITLE
jstree virtualization

### ISSUE THREAD

**Issue by jbacalo** [vakata/jstree#1688]
Hi Ivan,
Is there a way to virtualize the tree? 
i have ~100K nodes in it and it takes it about 20-25 seconds to responds(sometimes the page stops responding at all).
is there a way to render the tree nodes when the user actually scrolls to the point they are at?

Thanks,
Jonathan

**Comment by graphefruit** [comment]
Hi @jbacalo,
I didn't try it but maybe an approach:
Catch the "open_node" event get the ID of the node, and add the nodes yourself:
http://stackoverflow.com/questions/20632707/progressive-loading-of-jstree-on-node-open

Or maybe this approach could help aswell:
http://stackoverflow.com/questions/8078534/jstree-loading-subnodes-via-ajax-on-demand

**Comment by vakata** [comment]
Hi, 

The lazy-loading techniques by @graphefruit will be a good fit if this tree has many levels. If lazy-loading is what you are looking for - it is cleanly explained both in text and examples on the homepage of this repo.

If you have a large amount of nodes on the same level (with a common parent) lazy loading will not help in any way. You can experiment with disabling `core.worker` but my guess is that if you have a flat list of 100K nodes it won't help much. 

The idea you describe will be pretty hard to implement on a deep structure like a tree, but I am working on a VDOM implementation so I hope that will decouple jstree from the DOM and will give a speed boost in rendering. It would also open up the possibility to render nodes only when they are visible.

So I am closing this for now as it is not doable for v.3, but I hope v.4 will solve any problems with large amount of nodes.

**Comment by jbacalo** [comment]
Hi @vakata ,
Thanks for you quick answer!
Do you have an assumption when will v.4 be released? 
Also do you maybe have a suggestion for a control i could use that does support this capability and looks like a tree?

**Comment by vakata** [comment]
I hope to push out some betas in a month or two.

**Comment by jbacalo** [comment]
Thanks!
Will keep following the project
