### ISSUE TITLE
Children cannot be loaded when jstree assumes it's a flat structure.

### ISSUE THREAD

**Issue by Jezza** [vakata/jstree#1689]
While loading nodes via ajax, we send a fairly detailed tree, and didn't realise that you use two differing structures and have to guess as to which one was sent, as a result it kept on loading it as a flat structure.

It was a simple enough fix; we just don't send the first node's parent id, but it would be a lot easier if the callback just accepted some argument that told jstree what it should parse it as.

https://github.com/vakata/jstree/blob/master/src/jstree.js#L1751

**Comment by vakata** [comment]
Hi,

You correctly noticed that jstree decides what to use depending on the presence of a `parent` key in the first loaded node. Unfortunately this can not be changed without a major version bump as it has been this way for years. 
I am already working on v.4 and I will add a config option which will default to autodetect, but it would be possible to explicitly define the loading method.

Thank you.
