### ISSUE TITLE
[FEATURES] Limit selected nodes with checkbox plugin activated

### ISSUE THREAD

**Issue by vincent-guesnard** [vakata/jstree#1691]
Hello,

Thank you so much for this amazing job. It's a great library.

I was searching arround to find how limit the number of selected nodes. 

Since v3, it seems that it has been deleted from the project (no more ui plugin with select_limit and according to StackOverflow, there was issues with the checkbox plugins).

Did you plan to recover this function in a near futur ? It would be awesome.

Best regards,

V

**Comment by vakata** [comment]
No, I do not plan on implementing this functionality again. Now there is the `conditionalselect` plugin, which is bundled and can be used to prevent selection, and is way more flexible than `select_limit` ever was. You can check it out in the API docs - it is basically a callback.

Best regards,
Ivan

**Comment by vincent-guesnard** [comment]
Hello,

Thank you for this quicky reply. Conditionalselect works flawlessly.

I didn't succeed to do something perfect but it do the most of what i need.

Here is the fiddle in case someone need it : https://jsfiddle.net/xeobkm9u/
