### ISSUE TITLE
Jstreetable plugin help?

### ISSUE THREAD

**Issue by sandipg76** [vakata/jstree#1692]
I want to make some columns which I have added using the table plugin to jstree, dynamically read only, so that editing should be disabled on those cells. I have set the contextmenu plugin to true. Now when I right click on the column, an edit pop-up shows up and then allows me to edit the field. I want this to be conditional logic so that some fields are editable and some are read only.
Any help would really be appreciated?

**Comment by vakata** [comment]
The contextmenu is configurable on a per-node basis - set `contextmenu.items` to a function - it will be called each time a contextmenu is needed and will receive the node in question. Read more in the API docs.

**Comment by sandipg76** [comment]
Thanks for the quick response. By the way awesome plugin.  Great work.
