### ISSUE TITLE
Not able to hide sibling nodes using hide_node (obj) 

### ISSUE THREAD

**Issue by mightyspec** [vakata/jstree#1693]
Hello Ivan,

Thank you for a great plugin!

Everything working for me for what I need except this API **hide_node(obj)**. I'm not able to hide a sibling node, for e.g. if a parent node has two children then I'm not able to hide the second child. 

I think internally the node is getting hidden but it is still displayed in the tree, this is because when I try to hide the first child(after hiding second child) both children disappear. 

I'm not certain that this is an issue(may be I'm doing something wrong). Please advise if you had come across this behavior. 

Thanks in advance. Have a wonderful day!

-Mithun

**Comment by vakata** [comment]
Hi,

Thank you for the kind words.

I am afraid I have not seen this before. I can only help you if you provide a demo as this is not something I can reproduce. A minimal jsFiddle perhaps? I will reopen on more information, for now - I can not reproduce.

Best regards,
Ivan
