### ISSUE TITLE
[Question] Current state is not reflected using refresh, when tree is filled with async requests

### ISSUE THREAD

**Issue by MarceloFonseca** [vakata/jstree#1695]
Consider the following scenario:

- The tree is rendered with an initial set of nodes;
- A set of service requests are launched at the same time and the tree data is being updated as requests arrive, each update followed by the use of the API refresh method;
- If you open a given node in the meantime, it will collapse automatically after a refresh operation, as the state obtained (within refresh method) does not reflect the current state of the tree;

Do you have any clue on whats happening or how to overcome it?

Thanks in advance!

**Comment by vakata** [comment]
The sole purpose of `refresh` is to refresh (replace) the local state with a fresh copy from the remote. As such by design all local changes that were not persisted are lost. Let me know if I misunderstood and I will reopen.
