### ISSUE TITLE
jstree  hide nodes and show updated treeview

### ISSUE THREAD

**Issue by ahashim123** [vakata/jstree#1697]
Hi, we are using jstree.com to generate treeview. 

Initial Treeview created:

Fruits (category)
 - Mango (item)
-  Orange (item)
Countries (category)
- US (item)
- Canada (item)

we want that upon button click, on client side treeview should hide the categories and display only items without AJAX call,

Desired treeview outcome: (using javascript)
 - Mango
-  Orange
- US
- Canada

Is there a way to do this in a way that the updated tree aligns automatically without leaving spaces for hidden nodes?

Thanks

**Comment by vakata** [comment]
Hi,

Hiding parents without hiding their children is not supported. You can however reinitialize the tree and filter the data on your end - set core.data to a function, in that function respect the state of the button and return accordingly, onclick invoke `.refresh()`.

Best regards,
Ivan

**Comment by ahashim123** [comment]
yes, i did the same way, thanks
