### ISSUE TITLE
Multiple tree instances behaving strangly

### ISSUE THREAD

**Issue by klinki** [vakata/jstree#1698]
Hello,
I'm playing with having multiple trees in plunker and it behaves very strangly. See http://plnkr.co/edit/XyoYrb?p=preview and try to collapse/expand some tree nodes. 

(I noticed there has already been similar issue, https://github.com/vakata/jstree/issues/568, but I guess this is either another problem or the problem hasn't been fixed yet).

**Comment by vakata** [comment]
There must be something wrong with the rendering when the tree is floated and has no dimensions. Try this one: http://plnkr.co/edit/CErqU1F10i2uxj1MvkID (basically the tree DIV is not floated - wrap each tree div in a parent DIV and float the parent).
