### ISSUE TITLE
Can I use jstree with this kind of JSON?

### ISSUE THREAD

**Issue by estradamarkie** [vakata/jstree#1700]
Just wondering if this JSON is allowed to be used in jstree? Though I tried it but it didn't really work but want a feedback from the other guys.

I'm trying to use this JSON from a separate ajax request so I can render a jstree checkbox. So basically just going to pass this JSON string in jstree.

This is what it gave me [JsFiddle](https://jsfiddle.net/my4sv6ue/l)

```
{
   "type":"object",
   "properties":[
      {
         "name":"id",
         "in":"query",
         "required":false,
         "type":"string",
         "items":{
            "type":"integer",
            "format":"int32"
         },
         "collectionFormat":"multi",
         "title":"id",
         "format":"text"
      },
      {
         "name":"sku",
         "in":"query",
         "required":false,
         "type":"string",
         "items":{
            "type":"string"
         },
         "collectionFormat":"multi",
         "title":"sku",
         "format":"text"
      },
      {
         "name":"code",
         "in":"query",
         "required":false,
         "type":"string",
         "items":{
            "type":"string"
         },
         "collectionFormat":"multi",
         "title":"code",
         "format":"text"
      }
   ]
}
```
or with deep nested data object https://jsfiddle.net/yr0mkvmd/1/

**Comment by vakata** [comment]
The required JSON format is documented on the homepage of this repo and on jstree.com - the JSON above will not work. You can however use core.data as a function (also documented) and make the AJAX request yourself and map this JSON to the structure required by jstree.
