### ISSUE TITLE
Support progressive load of node children

### ISSUE THREAD

**Issue by gmathis** [vakata/jstree#1701]
jsTree's lazy loading support is very useful if you can afford to load all the children of any particular node at once.
In our use case, however, at large scale, there may be many thousands of root nodes or children of a particular node.
Fetching / rendering these in a single pass makes our UI unresponsive.
The ability to load / render child nodes progressively would be very useful.
For example, the callback provided to the `core.data` function could accept an argument indicating whether the response was complete, and the callback could be called multiple times to return nodes progressively until the response indicated that all the nodes had been returned.

I've found that calling the existing callback multiple times in the plugin as shipped doesn't work because internally, `_append_json_data()` clears the node's children before adding new nodes. I've had some success experimenting with modifying that function to preserve `dom.children[_d]`, but various workarounds are necessary to preserve normal tree state behavior we rely on, and I worry about generally destabilizing our solution.

Thanks for your consideration!

**Comment by vakata** [comment]
Hi,

This will not be implemented for v.3, but v.4 will have a cleaner model, which will not differentiate between loading and creating nodes. That means there will be an easy way to implement "paging" and on-demand loading of children. 
If all goes according to plan that may not be necessary (but will be possible), as the client side should be able to handle a lot more nodes and faster (by only rendering visible nodes and reusing old DOM).

v.4 is in the making and I hope to have a beta out in the spring.

Best regards,
Ivan

**Comment by gmathis** [comment]
Thanks Ivan, I'll check out v4 when it's out.

**Comment by virtuallyp** [comment]
Hi,

I am looking for a complete example using callback functions. Can you please direct me in the right direction? 

In my scenario, I have to get data from a SharePoint List (which has stored the data in adjacency list format). I can make a REST call to SharePoint list with Datafilter options to convert return data to the requirement format but after that I am not sure how to use it. Please let me know if you have a complete examples that show:
REST Service JSON response for parent and children
HTML and JS

Regards,

virtually

**Comment by vakata** [comment]
The homepage of this repo had many examples. Here are some PHP examples: https://github.com/vakata/jstree-php-demos

**Comment by vakata** [comment]
The homepage of this repo had many examples. Here are some PHP examples: https://github.com/vakata/jstree-php-demos
