### ISSUE TITLE
State plugin does not restore open/collapsed node state

### ISSUE THREAD

**Issue by DmitriPopov** [vakata/jstree#1702]
How to reproduce:

1. Go to official "Plugins" page

[https://www.jstree.com/plugins/](https://www.jstree.com/plugins/)

2. Scroll down to "State" plugin

3. Select "Root node 2"

4. Collapse "Root node"

5. Refresh the page

Result: "Root node" appears expanded while it should be restored as collapsed.

**Comment by vakata** [comment]
The opened state of the root node is passed with the data (in the demo's case - the markup) - the state plugin will not modify that, it will apply the saved state on top of that. The assumption is that the state is always older than the data you feed into jstree.

**Comment by DmitriPopov** [comment]
So if I pass at least one node state via data-jstree, the state plugin ignores the last saved state as a whole? I can not make it work together. Chrome DevTools shows "Uncaught TypeError: Cannot read property 'a_attr' of undefined" in state plugin. When I remove data-jstree or state plugin everything is OK.

**Comment by FrGffe** [comment]
Yes but in the jsfiddle http://jsfiddle.net/vakata/2kwkh2uL/4493/ it works.
So what can be the reasons when it does not work. I have the same problem after a nodes refresh.

**Comment by raylight75** [comment]
After 3 years this problem still exists, does someone have solution.
