### ISSUE TITLE
Compare parent with old_parent on check_callback

### ISSUE THREAD

**Issue by Resin01** [vakata/jstree#1703]
I am trying to check the move_node callback to see if the new parent is equal to the old parent (the user can not change levels of items). Sadly it seems that this is not possible. I can check it on the easily on the move_node.jstree event, but not in the check_callback. Am I missing something?

**Comment by vakata** [comment]
I can not help you without you showing me what you already tried. It should be pretty trivial - you get the new position and the node. From the new position and the reference node you can calculate the (new) parent, and from the node you can get the current parent of the node, so you can compare if those two are the same.

**Comment by Resin01** [comment]
Sorry just figured it out.
`    check_callback: function (operation, node, new_parent) {
                        if (operation === 'move_node') {
                            if (node.parent === new_parent.id) {
                                return true;
                            }
                        }

                        return false;
                    },`
