### ISSUE TITLE
themes.dots is ignored

### ISSUE THREAD

**Issue by pixelplant** [vakata/jstree#1704]
Hello

There's a small issue with the display of dots in a theme...
Setting themes.dots = true does not work, the reason being that the dots are always hidden after the tree is loaded, at line 8191 in jstree v3.3.3
```
.on('ready.jstree set_state.jstree', $.proxy(function () {
	this.hide_dots();
}, this))
```

As you can see, when the tree is loaded the dots are being hidden as this.hide_dots() is being forced. Commenting this line makes the dots work correctly, while set to true, and they're not displayed when set to false.

**Comment by vakata** [comment]
The only reason for dots not to work is if you have the wholerow plugin active - those 2 do not work together. If that is not the case - I will reopen the issue.

**Comment by pixelplant** [comment]
Indeed, I was using the wholerow plugin. Commenting the this.hide_dots() line though makes it work great with the wholerow plugin while keeping the dots display.
