### ISSUE TITLE
A children node is check and disable, and i unckeck this node's parent node,the children node is uncheck.

### ISSUE THREAD

**Issue by vowtree** [vakata/jstree#1706]
A children node is check and disable, and i unckeck this node's parent node,the children node is uncheck too.  I want this, if the children node is disable, the state of node's check is no change with it's parent.

**Comment by vakata** [comment]
This is not supported. You can disable tri-state all together and handle changes manually, but cascading the checked state depending on criteria in the nodes is not supported. As for cascade - take a look at the `checkbox.cascade` option.
