### ISSUE TITLE
Checkbox plugin - checked state does not work

### ISSUE THREAD

**Issue by tpck** [vakata/jstree#1708]
When getting JSON data from the server (in the alternative JSON format) and setting _**jstree(true).settings.core.data**_ to the new data, the state is ignored (e.g. _state: {'checked': true }_).

Here is my [jsfiddle](https://jsfiddle.net/7n93o467/).

**Comment by vakata** [comment]
This is by design - be default the current state is reapplied after a `refresh`. To prevent this use the `forget_state` parameter: ```$('#jsTree').jstree(true).refresh(true, true);```
