### ISSUE TITLE
When renaming a node with ampersand

### ISSUE THREAD

**Issue by cigamit** [vakata/jstree#1709]
If a node name includes an htmlspecialchars() value of say "Testing & Training", which when escaped for XSS protection becomes "Test &amp; Training", and then when you press F2 (rename), creates the input box as expected, but the value instead of being "Testing & Training" displays as the escaped value.

Should you always unescape(default_text) for the value in the input box during rename?

**Comment by vakata** [comment]
Play around with this option: https://www.jstree.com/api/#/?q=text&f=$.jstree.defaults.core.force_text
