### ISSUE TITLE
add Chinese Translation - 中文文档

### ISSUE THREAD

**Issue by Viky-zhang** [vakata/jstree#1710]
Recently, I translate official doc to chinese.

GitBook: https://viky-zhang.gitbooks.io/jstree-doc

GitHub: https://github.com/Viky-zhang/jsTree-doc

Both GitBook and GitHub sync.

just have fun.

中文文档

**Comment by vakata** [comment]
Thank you for the effort - I really appreciate this. I will add a link on the main page.
