### ISSUE TITLE
Drag and drop problem

### ISSUE THREAD

**Issue by zeeshanu** [vakata/jstree#1711]
I can't drop the node that does't have any child before the tree first node. But if i drop it after the first node it places before first node.

```
$('#page-tree').jstree({
            core: {
                "check_callback" : true,
                "check_while_dragging": true,
                "animation" : 250,
                "themes" : {
                    'icons': false,
                    'dots' : false,
                    'responsive': true,
                    'variant': "large",
                },
                'data' : {
                    url: function (node) {
                        return '/api/pages';
                    },
                }
            },
            plugins: [ "wholerow", "dnd" ]
        });
```

![jstree](https://cloud.githubusercontent.com/assets/16267321/23370087/5eb8e1dc-fd35-11e6-8a88-7382b3fecde6.gif)

**Comment by vakata** [comment]
As you can see in this fiddle what you described works fine: http://jsfiddle.net/DGAF4/2001/

Please provide a similar fiddle demonstrating the problem as I can not reproduce it. Also - check for duplicate IDs, as that is a common problem.

I am closing this until a demo is provided.
