### ISSUE TITLE
jstree with validator (name of .jstree-rename-input, keep edit mode, validation errmsg)

### ISSUE THREAD

**Issue by aubreybox** [vakata/jstree#1713]
Ive been testing some hours now but didnt get as far as I wished.
How can I achieve the following:
On rename: check text.
If invalid: keep edit mode and show error next to the input field

Usually I would use jQuery.validate (that would take care of the error msg), but therefore the .jstree-rename-input must have a name. Is it possible to add one? Where would I do that?

**Comment by vakata** [comment]
The edit mode is exited and changes are applied when the node is blurred. So you have a few options:
1) Listen on the container for blur events on `.jstree-rename-input` and validate the data, if needed - you can put the node back in edit mode
2) Use check_callback - prevent the rename altogether and put the node back in edit mode if it does not meet your validation
3) Use the third param of `edit` - it is a callback function which will be invoked when the node is blurred along with some data: 
https://www.jstree.com/api/#/?q=edit&f=edit(obj%20[,%20default_text,%20callback])

I guess 2) is your best bet.

**Comment by aubreybox** [comment]
Ok so Ill try 2.: how would I prevent jstree from closing the edit-field? 
returning false in check_callback does not work

**Comment by aubreybox** [comment]
?

**Comment by vakata** [comment]
As I described - if you go with number 2 - you need to manually `put the node back in edit mode if it does not meet your validation`
