### ISSUE TITLE
efficient way to select or move nodes (hundreds or more)

### ISSUE THREAD

**Issue by zcliu** [vakata/jstree#1714]
I'd like to move or select multiple nodes programmatically, doing so with 'select_node' and 'move_node' seems very slow for hundreds of nodes, because the system triggers an event for each of the nodes. What's an efficient way to do selection or move programmatically?

**Comment by vakata** [comment]
To be honest - currently there is no quick and easy way to speed things up. 

This will be improved with v.4 which has a separate model and presentation layer, so making drastic changes can be done at once and then once ready - the presentation layer will update.

Until v.4 is out **you can try using the `move_node` `skip_redraw` argument** - move your nodes around (but pass `true` for that argument), and then call `redraw()` to refresh the UI - that should probably make things a bit faster.

Best regards,
