### ISSUE TITLE
select_node supress_event is fired although the flag is set

### ISSUE THREAD

**Issue by NashBridgesAT** [vakata/jstree#1716]
hi
i have some jstree instances and after creating the trees i set some preselected nodes by select_node. at this time i do not want the changed event to be fired and set the flag following the api. any further selection should fire the event. but it does not work, here is my code: (cat_arr) are the preselected node ids, working so far)

```
$(".categories").each(function(){		

	//create trees
       $(this).jstree({"plugins": ["checkbox"]}); 			
	
        //check selected nodes
	$(this).jstree(true).select_node(cat_arr, true);

        //define action on changed event	
	$(this).on("changed.jstree", function (e, data) {
	var i, j, r = [];
    for(i = 0, j = data.selected.length; i < j; i++) {
      r.push(data.instance.get_node(data.selected[i]).text);
    }
    console.log('Selected: ' + r.join(', '));	
	});
});
```

**Comment by vakata** [comment]
I can not reproduce this - please help me reproduce using this fiddle:
http://jsfiddle.net/DGAF4/2026/

Also - make sure you call select_node after the tree is ready.
