### ISSUE TITLE
Uncaught ReferenceError: _typeof is not defined

### ISSUE THREAD

**Issue by markuskoehler** [vakata/jstree#1717]
A year ago I successfully used jsTree for a project, but now that I try to do it again, I always run into an "Uncaught ReferenceError: _typeof is not defined" at the end. jsTree seems to generate a blob, so I cannot look into it what's happening, I just see this error where I would expect jsTree to load new data provided via ajax call... Any thoughts on this?

EDIT: Even tried different solutions to pull data in dynamically, like wrapping jstree in an axios promise, or an angular promise, or using the built-in jquery ajax call, but everytime when I expect valid data to come back all that i receive is this reference error...

**Comment by vakata** [comment]
It is a known issue with some transpilers ans possibly webpack. But as the code is completely valid there is nothing I can do except wait for the issue to be fixed from the transpiler / webpack side. In the mean time set `core.worker` to `false` in your jstree config and there will be no error.

**Comment by redterror** [comment]
I took inspiration from https://github.com/mapbox/mapbox-gl-js/issues/3422#issuecomment-366739198 and did the exclusion in the webpack config and that addressed the problem for me.
