### ISSUE TITLE
node.hidden does not work as expected

### ISSUE THREAD

**Issue by markusp72** [vakata/jstree#1719]
Hello Ivan,

thank you for this great plugin!!!

I would like to follow on ticket #1372. 
For me, the "hidden" state for nodes does not work as I would have expected.
E.g., after "refresh", all hidden nodes are shown again. This behavior is different from other node states, e.g. "selected". Both behaviors can be seen in the following fiddle (using jstree 3.3.3):

[jstree 3.3.3 fiddle](http://jsfiddle.net/cdtc2edq/1/)

In order to persist the flag, as a workaround, I am currently manipulating the dataobject, and reassign it to the jstree, instead of setting the state via "hide_node" or "hide_all":

$("#jstree").jstree(true).settings.core.data = manipulatedTreeData;
$("#jstree").jstree(true).refresh();

Best Regards,
Markus

**Comment by vakata** [comment]
I will try to improve on this in version 4, or at least include it in the docs. 
Opened and selected are processed separately - this is why they are reapplied after a refresh, the hidden state is not processed this way - it depends only on what is described in the data.
