### ISSUE TITLE
CRRM plugin

### ISSUE THREAD

**Issue by pbaker** [vakata/jstree#172]
I did not see the CRRM plugin.  Is this functionality available?  Am I missing something?

**Comment by suryatejamv** [comment]
The link mentioned above redirects to https://www.jstree.com/plugins/ page. But I can't find the CRRM plugin listed in the list. Can anyone confirm if the plugin is still active? thanks J

**Comment by vakata** [comment]
It is no longer a plugin - it is bundled in the core - this ticket is 4 years old.
move / copy / rename / delete are now included in the core - to enable those operations set `core.check_callback` to `true` as mentioned in the docs.

Best regards,
Ivan

**Comment by suryatejamv** [comment]
Hi,
Thanks a lot for the response. My bad that I dint see it properly.
Much obliged by your fast response

thanks,
Surya
