### ISSUE TITLE
Convert path structure to jsTree data structure

### ISSUE THREAD

**Issue by palsbo** [vakata/jstree#1720]
I have a path structure like this `["/26.787A59010000/B1-R1-A/gain",
"/26.787A59010000/B1-R1-A/offset",
"/26.787A59010000/B1-R1-A/pressure",
"/26.787A59010000/CA",
"/26.787A59010000/EE",
"/26.787A59010000/HIH3600/humidity",
"/26.787A59010000/HIH4000/humidity",
"/26.787A59010000/HTM1735/humidity",
"/26.787A59010000/IAD",
"/26.787A59010000/MultiSensor/type",
"/26.787A59010000/S3-R1-A/current",
"/26.787A59010000/S3-R1-A/gain",
"/26.787A59010000/S3-R1-/illuminance",
"/26.787A59010000/VAD",
"/26.787A59010000/VDD",
"/26.787A59010000/alias",
"/26.787A59010000/date",
"/26.787A59010000/disconnect/date",
"/26.787A59010000/disconnect/udate",
"/26.787A59010000/endcharge/date",
"/26.787A59010000/endcharge/udate",
"/26.787A59010000/humidity",
"/26.787A59010000/offset",
"/26.787A59010000/temperature",
"/26.787A59010000/type",
"/26.787A59010000/udate",
"/26.787A59010000/vis",
"/81.BFA735000000/alias",
"/81.BFA735000000/type"]`
And want to use jsTree to select folders and items.
Is there a way to convert /use this structure?
I have been seraching the net and trying for several days without luck. I have the feeling that ther are somthing I have overlooked.
Any help would be appreciated
I have no problem reading a file-structure. This list comes from a onewire structure.

**Comment by vakata** [comment]
You can set core.data to a function and convert this array to the required jstree format (either flat or nested).

**Comment by palsbo** [comment]
Thank you for answer, but not exactly what I was looking for. However I found a way to convert data. Here is my code:

`function childof(root, child) {
	for (idx in root) {
		if (root[idx].id == child.id) return idx;
	};
	return -1
}

function convert(lines) {
	startDir = "/";
	var result = [{ id: startDir, text: "Onwire devices", type: 'd', children: [] }];
	lines.forEach(function (line) {
		pIndex = 1;
		thisChild = result[0].children;
		var ar = line.split('/');
		var lastFld = ar.length - 1;
		for (var i = 1; i < ar.length; i++) {
			var id = "/";
			for (var j = 1; j <= i; j++) {
				id += ar[j]
				if (j < ar.length - 1) id += '/';
			}
			var text = ar[j - 1]
			info = {
				id: id,
				text: text,
				type: "d"
			};
			if (i == lastFld) {
				info.type = 'f';
				info.icon = "jstree-file";
			} else info.children = [];
			if (childof(thisChild, info) < 0) {
				thisChild.push(info)
			}
			var rootIndex = childof(thisChild, info);
			thisChild = thisChild[rootIndex].children
		}
	})
	return result;
}
`

**Comment by gromaxbro** [comment]
paslo your code is right but it it is make the child him dublicate 

so i fixed it 
function convert(lines) {
startDir = "/";
var result = [{ id: startDir, text: "Onwire devices", type: 'd', children: [] }];


lines.forEach(function (line) {
pIndex = 1;
thisChild = result[0].children;
var ar = line.split('/');
var lastFld = ar.length - 1;
var gh;
for (rrr in ar) {
    if ('' == ar[rrr]){
        gh = ar.length - 1;
    }
    else{
        gh = ar.length;
    }
    
}
for (var i = 1; i < gh; i++) {
    var id = "/";
for (var j = 1; j <= i; j++) {
    id += ar[j]
if (j < ar.length - 1) id += '/';
}


var text = ar[j - 1]
info = {
id: id,
text: text,
type: "d"
};

if (i == lastFld) {
info.type = 'f';
info.icon = "jstree-file";
} else info.children = [];
if (childof(thisChild, info) < 0) {
thisChild.push(info)
}
var rootIndex = childof(thisChild, info);
thisChild = thisChild[rootIndex].children
}
})

return (result);
}
