### ISSUE TITLE
Restoring state triggers 'changed' event multiple times

### ISSUE THREAD

**Issue by drbarto** [vakata/jstree#1722]
Hi,

I'm using jsTree 3.3.3 with the state plugin. 

When the tree state is restored by a page reload, the `changed.jstree` event is called for every selected tree node separately. (In my case, a costy operation is run when the selection changes; so if a tree with 20 selected nodes is restored, that operation is run 20 times!)

This looks like a bug to me: IMO restoring the state is an atomic operation and thus should only trigger the change event once. Anyway, even if this should be the expected behaviour: is there a way to get around this, e.g. to temporarily disable the selection change listener while the state gets restored? (I know there is an event _before_ the state plugin starts restoring, but there is none when restoring is finished).

Any help appreciated. Oh, and thanks for the great lib :)

Best,
Martin

**Comment by drbarto** [comment]
I figured out a workaround: I register for the `changed.jstree` event in the handler of the `ready.jstree` event. When this is fired the state plugin seems to have completed its restoring work.

If others have the same issue, here is my code:

    $tree.on('ready.jstree', function() {
      $tree.on('changed.jstree', onSelectionChanged);
    });

I'll leave this issue open for now because I'd be interested in whether the described behaviour is by design or by accident.

**Comment by vakata** [comment]
Sorry for the delay - I will search back in the repo history today, as the code for restoring state explicitly is set to trigger changed multiple times, but I have no memory why I did that. I will let you know later today.

**Comment by vakata** [comment]
Again - sorry for the huge delay - ```changed``` is explicitly triggered as some plugins need this event to react to changes (like wholerow). This will be improved in the next major version, but unfortunately it is not possible to fix this in v.3
