### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by primissus** [vakata/jstree#1724]
Hi, is posible to avoid the context menu on certain elements? Without the need of making all the functions again for the other elements.
@alanTorresManci
This works, but disables the menu for the other elements.
![screen shot 2017-03-14 at 18 35 30](https://cloud.githubusercontent.com/assets/19866079/23928398/1a0ab0b8-08e5-11e7-9c71-4197344d0d3e.png)
Thanks!

**Comment by primissus** [comment]
I´ve found the answer 
![screen shot 2017-03-14 at 18 42 10](https://cloud.githubusercontent.com/assets/19866079/23928563/0354e8ce-08e6-11e7-9280-b87b8c0d93dc.png)

**Comment by vakata** [comment]
Just so you know - there is a much better option - set `contextmenu.items` to a function - that way you have full control over the contextmenu for each node.
