### ISSUE TITLE
Unable to use AJAX request on WordPress

### ISSUE THREAD

**Issue by knowledgeplaces** [vakata/jstree#1725]
Thanks for this very nice plugin.
I have been through the doc and I have been able to make it run with the sample AJAX requests you provide on fiddle, using a code like this:

`jQuery(document).ready(function( $ ) {
// create pages to validate tree instance
jQuery('#jstree_pages_to_validate').jstree({
"core" : {
			"themes" : {
				"icons" : false
			},	
			"data" : {
				"url" : "//www.jstree.com/fiddle/"
			},
			"dataType" : "json" // needed only if you do not supply JSON headers
		},
		"plugins" : [ "checkbox" ]
	})	
});`

Now I need to populate JSTree from data I get from WordPress, and after many hours I don't have yet the solution.
I don't know if you are familiar with using AJAX with WordPress, but here is a sample AJAX call which works fine:
`	jQuery.ajax({
		type: 'POST',
		url: WP_AJAX_URL,
		data: {
			'action': 'kps_logout',
			'security': jQuery("#kpcms-ajax-nonce").val()
		},
		beforeSend: function(){
			jQuery('#kps-ajax-loader').css("visibility", "visible");
		},		
		success: function(){
			// redirect and deactivate default navigation
			window.location.href = kps_Host + kps_LoginPath;
		}
	});` 

What is specific:

1/ "WP_AJAX_URL" is the Ajax endpoint URL of WordPress. Using a server side localization feature of WordPress, this variable is replaced by the real endpoint URL.
2/ "action" is a parameter received by WordPress and you can trigger a server side specific function for each action. In what I want to do, the function triggered by action "kpcms_getChildPages", retrieves the tree of the child pages of the page I am currently in.
3/ "security" is an additional parameter required to secure AJAX calls to WordPress.

So I tried this, but it does not send the AJAX call:
`	jQuery('#jstree_pages_to_validate').jstree({
		"core" : {
			"themes" : {
				"icons" : false
			},	
			"data" : {
				"url" : WP_AJAX_URL,
				"action" : 'kpcms_getChildPages',
				"security" : jQuery("#kpcms-child-pages-nonce").val()
			},
			"dataType" : "json" // needed only if you do not supply JSON headers
		},
		"plugins" : [ "checkbox" ]
	})	
});`

Any advice appreciated on how to do this, thanks in advance.

**Comment by knowledgeplaces** [comment]
I found how to proceed.
I make the AJAX call to WordPress, and I build the JSTree in the response to this AJAX call.

**Comment by vakata** [comment]
You should have wrapped the action and security keys in a "data" master key.

Best regards,
