### ISSUE TITLE
Special characters as node names in filebrowser demo

### ISSUE THREAD

**Issue by geraldo** [vakata/jstree#1728]
I had issues with special characters in the file browser demo, they just didn't appear. I solved it substituting preg_match in line 41 of file demo/filebrowser/index.php with:

`$tmp = preg_match('/^[\p{L}]+$/ui', $item);`

I'm not sure if this has some negative side effects, right now it seems to work fine.

**Comment by vakata** [comment]
Thanks, but there is a separate repo for the demos now, so I will close this issue and update the demo code there.
