### ISSUE TITLE
Wrong tree structure

### ISSUE THREAD

**Issue by AndreaLombardo** [vakata/jstree#1731]
Hi, can anyone help me with this problem?
I'have a big number of items in my tree, but the folder don't respect the right tree structure.
This is my case:
https://jsfiddle.net/7vw0c2z9/

I'm using the alternative JSON structure.

Thanks a lot!

**Comment by vakata** [comment]
There are two problems that I can see:
1) You did not have a parent property on the root node, which caused jstree to NOT use the alternative format.
2) When the parent property is added there is an error - meaning you have a node whose parent does not exist, but I did not take the time to find which one.

Here is a trimmed down version of your fiddle:
https://jsfiddle.net/7vw0c2z9/1/

**Comment by AndreaLombardo** [comment]
Hi @vakata , thanks for your fast reply.
I deliberately omitted the parent property to display at least the tree. Speaking about how the father-son relationship, I'm sure there is not a son without a father. But, to be sure, there is a way to make the plugin catch the error and tell me what is the children orphans?

Thanks again!

**Comment by vakata** [comment]
Currently no, but I guess you could iterate through the object quickly and check for missing parents, or duplicated IDs (that could be the cause of the issue as well).
