### ISSUE TITLE
JStree search not working in file browser PHP

### ISSUE THREAD

**Issue by hrnmodi** [vakata/jstree#1732]
When I search for something like .jpg, .doc etc it opens all node but not searching when I search again it works. If I remove $('#tree').jstree('open_all');  from search then search not working. I've written following script...

`<script>
    
    $(function () {
        $('.tree-search').click(function (){
              $('#tree').jstree('open_all'); // if
              $('#tree').jstree(true).search($('#jstree-default_q').val());
        });
        $('#tree')
                .jstree({
                    'core': {
                        'data': {
                            'url': 'operations.php?operation=get_node',
                            'data': function (node) {
                                return {'id': node.id,'area-expanded':true};
                            }
                        },
                        'check_callback': function (o, n, p, i, m) {
                            if (m && m.dnd && m.pos !== 'i') {
                                return false;
                            }
                            if (o === "move_node" || o === "copy_node") {
                                if (this.get_node(n).parent === this.get_node(p).id) {
                                    return false;
                                }
                            }
                            return true;
                        },
                        'themes': {
                            'responsive': !1,
                            'variant': 'small'
                        }
                    },
                    'sort': function (a, b) {
                        return this.get_type(a) === this.get_type(b) ? (this.get_text(a) > this.get_text(b) ? 1 : -1) : (this.get_type(a) >= this.get_type(b) ? 1 : -1);
                    },
                    'contextmenu': {
                        'select_node': false,
                        'items': function (node) {
                            var tmp = $.jstree.defaults.contextmenu.items();
                            delete tmp.create.action;
                            tmp.create.label = "New";
                            tmp.create.submenu = {
                                "create_folder": {
                                    "separator_after": true,
                                    "label": "Folder",
                                    "action": function (data) {
                                        var inst = $.jstree.reference(data.reference),
                                                obj = inst.get_node(data.reference);
                                        inst.create_node(obj, {type: "default"}, "last", function (new_node) {
                                            setTimeout(function () {
                                                inst.edit(new_node);
                                            }, 0);
                                        });
                                    }
                                },
                                "create_file": {
                                    "label": "Upload Files",
                                    "action": function (data) {
                                        
                                            var inst = $.jstree.reference(data.reference),
                                            obj = inst.get_node(data.reference);
                                            $('.file_full_path').val(JSON.stringify(obj['id']));
                                            $('#uploads_files').modal();
                                    }
                                }
                            };
                            if (this.get_type(node) === "file"){
                                delete tmp.create;
                            }
                            delete tmp.remove;
                            delete tmp.ccp;
                            return tmp;
                        }
                    },
                    'types': {
                        'default': {'icon': 'fa fa-folder text-warning fa-lg'},
                        'file': {'valid_children': [], 'icon': 'fa fa-file text-inverse fa-lg'}
                    },
                    'plugins': ['dnd', 'sort', 'types', 'contextmenu','search']
                }).on('ready.jstree', function (e, data) {
                            // $("#tree").jstree('close_all');
                            //$("#tree").jstree("toggle_node",'/'); 
                            //$("#tree").jstree("open_all",'/'); // open all node except root
                            //$("#tree").toggle_node('/');;
                            data.instance.redraw(true);
 
                   }).on("select_node.jstree", function (e, data) {
                        console.clear();
                        console.log("Node id : "+ data.node.id + " : Node Type  "+ data.node.type + "Node Parent : "+ data.node.parent);
                        return data.instance.toggle_node(data.node);
                        
                }).on('create_node.jstree', function (e, data) {
                    $.get('operations.php?operation=create_node', {'type': data.node.type, 'id': data.node.parent, 'text': data.node.text})
                            .done(function (d) {
                                data.instance.set_id(data.node, d.id);
                            })
                            .fail(function () {
                                data.instance.refresh();
                    });
                }).on('rename_node.jstree', function (e, data) {
                    $.get('operations.php?operation=rename_node', {'id': data.node.id, 'text': data.text})
                            .done(function (d) {
                                data.instance.set_id(data.node, d.id);
                            })
                            .fail(function () {
                                data.instance.refresh();
                            });
                }).on('move_node.jstree', function (e, data) {
                    $.get('operations.php?operation=move_node', {'id': data.node.id, 'parent': data.parent})
                            .done(function (d) {
                                data.instance.load_node(data.parent);
                                //data.instance.refresh();
                            })
                            .fail(function () {
                                //data.instance.refresh();
                            });
                }).on('changed.jstree', function (e, data) {
                       
                    if (data && data.selected && data.selected.length) {
                        $.get('operations.php?operation=get_content&id=' + data.selected.join(':'), function (d) {
                            
                            if (d && typeof d.type !== 'undefined' && d.type !=='folder') {
                                    var file_path = $('.jstree-clicked').parent().attr('id');
                                    window.open("<?php echo SITE_URL .'/uploads/management/'.$_SESSION['adminid'].'/'.$_SESSION['organisation_name']?>/"+file_path);
                            }
                        });
                    } 
                });
    });
</script>`

**Comment by vakata** [comment]
There is a separate repo for the demos, and the demos are not full featured. If you'd like - open a ticket in the demo repo.
