### ISSUE TITLE
JSTree add download file button context menu for file only

### ISSUE THREAD

**Issue by hrnmodi** [vakata/jstree#1733]
I want to add download button after rename when I right click on file. I've tried following code but it show download button when I right click on folder not showing when I click on file... please check.

contextmenu: {
	'select_node': false,
	'items': function(node) {
		var tmp = $.jstree.defaults.contextmenu.items();
		delete tmp.create.action;
		tmp.create.label = "New";
		tmp.create.submenu = {
			"create_folder": {
				"separator_after": true,
				"label": "Folder",
				"action": function(data) {
					var inst = $.jstree.reference(data.reference),
						obj = inst.get_node(data.reference);
					inst.create_node(obj, {
						type: "default"
					}, "last", function(new_node) {
						setTimeout(function() {
							inst.edit(new_node);
						}, 0);
					});
				}
			},
			"create_file": {
				"label": "Upload Files",
				"action": function(data) {
					var inst = $.jstree.reference(data.reference),
						obj = inst.get_node(data.reference);
					$('.file_full_path').val(JSON.stringify(obj['id']));
					$('#uploads_files').modal();
				}
			},
			"download_file": {
				"label": "Download file",
				"action": function(data) {
					var inst = $.jstree.reference(data.reference),
						obj = inst.get_node(data.reference);
					$('.file_full_path').val(JSON.stringify(obj['id']));
					$('#uploads_files').modal();
				}
			}
		};
		if (this.get_type(node) === "file") {
			delete tmp.create;
		}
		delete tmp.remove;
		delete tmp.ccp;
		return tmp;
	}
}`
`

**Comment by hrnmodi** [comment]
Got the solution.  Now is there any way, when click on download open file in new tab?  

`
tmp.custom_action = {
                                    "label" : "Download File",
                                    "action" : function (data) {
                                        var inst = $.jstree.reference(data.reference),
                                        obj = inst.get_node(data.reference);
                                        console.log(JSON.stringify(obj['id']));      
                                    }
                                }
`

**Comment by vakata** [comment]
That is outside the scope of jstree - you could probably use `window.open`

**Comment by hrnmodi** [comment]
I've used window.open, unfortunately browser does't opening tab without allow popup....
