### ISSUE TITLE
URL to JQuery is broken

### ISSUE THREAD

**Issue by askrinnik** [vakata/jstree#1734]
I've just downloaded the last version of jsTree.
Then I opened basiс demo page but caught an error
Looks like URL to JQuery is broken in this line:
https://github.com/vakata/jstree/blob/master/demo/basic/index.html#L46

when I set 
`https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js`
it fixed the page

Could you, please, fix the URL?

Thank you in advance
Best wishes

**Comment by vakata** [comment]
The URL works: https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js (the one in the demo is protocol relative, but it works as well).
Maybe it was something network related at the time of your test?
