### ISSUE TITLE
Ajax call is not hitting in my static method

### ISSUE THREAD

**Issue by vbdhanesh** [vakata/jstree#1736]
<div id="container"></div>
<script>
$(function() {
  $('#container').jstree({
    'core' : {
      'data' : {
        "url" : "//www.jstree.com/fiddle/",
        "dataType" : "json" // needed only if you do not supply JSON headers
      }
    }
  });
});
</script>

**Comment by vakata** [comment]
That will not work because of cross-domain issues - look into CORS.

**Comment by vbdhanesh** [comment]
hi the above URL is a sample i have added my own static webservice URL
