### ISSUE TITLE
Check only results of the search

### ISSUE THREAD

**Issue by saulide** [vakata/jstree#1737]
Currently, if a search is made with config entry show_only_matches, matches are shown. If then the user wants to auto check showed elements, as a developer I don't find any appropriate api how to do so. If I trigger check_all, it checks all nodes, even not visible ones. Before doing some workarounds to implement a feature that just visible/searched items are checked, I wanted to ask if there is a better way using the api

**Comment by vakata** [comment]
This is already fixed by a contributor and the fix is in the repo, 3.3.4 will have that incorporated. If you do not want to wait - pull the source from the repo.

**Comment by sauliuni** [comment]
Is it possible to make a version bump (3.3.3.1?), so that at least bower gets the newest version with it? Or then the 3.3.4 update is planned?
