### ISSUE TITLE
re-select node after tree refresh

### ISSUE THREAD

**Issue by sjpeng** [vakata/jstree#1740]
If possible using JS to select node after tree refresh?

**before tree data:**
`var data = {
        'text': 'TEST',
        'icon': 'fa fa-users',
        'state': {'selected': true},
        'children': [{'text': 'a', 'icon': 'fa fa-user', 'state': {'selected': true}}, {'text': 'b', 'icon': 'fa fa-user', 'state': {'selected': false}}]
};`

**after, I want overwrite it:**
`var new_data = {
        'text': 'TEST',
        'icon': 'fa fa-users',
        'state': {'selected': true},
        'children': [{'text': 'a', 'icon': 'fa fa-user', 'state': {'selected': false}}, {'text': 'b', 'icon': 'fa fa-user', 'state': {'selected': true}}]
};
tree.jstree(true).settings.core.data = new_data;
tree.jstree('refresh', -1);`

but, children 'a' couldn't deselect :(

**Comment by vakata** [comment]
Hi, the `refresh` method is not the best way to change selection. Still if you really want to use it - use the second param - `forget_state`, which will make sure the selection is as you supply it in the data: https://www.jstree.com/api/#/?q=refresh&f=refresh()

If you mean a browser refresh - then take a look at the `state` plugin.
