### ISSUE TITLE
Drag File on desktop from jstree & Drop file in jstree from desktop

### ISSUE THREAD

**Issue by Abubakar63** [vakata/jstree#1741]
Hi @vakata 

I am using dnd plugin to order or move nodes internally, and that's working perfectly fine. But I also want to drag a file from jstree to my desktop so that I have that on my machine.

Similarly I want to drop a file from my local desktop to jstree so that it becomes a new node in jstree.

Please guide me in these 2 features.

Thanks alot.

**Comment by vakata** [comment]
Those do not have much to do with jstree - you should achieve them in the same way you would if not dealing with jstree. Just make sure you are using HTML5: https://www.jstree.com/api/#/?q=dnd.use&f=$.jstree.defaults.dnd.use_html5

**Comment by Abubakar63** [comment]
Thanks alot @vakata 👍
