### ISSUE TITLE
Refreshing the tree makes it flash as it is removed and created again

### ISSUE THREAD

**Issue by jcarlosgarciasegovia** [vakata/jstree#1744]
I want to refresh the tree to add any new nodes, remove any deleted nodes or update current nodes, but the tree flashes as it seems it is removed and created again when doing this.
Could this be fixed?
Will this fix require something like react.js to change the DOM without flashing?

**Comment by vakata** [comment]
This will not change - jstree regenerates whole parts of the DOM when nodes are added and deleted (not the whole tree, but most commonly - the parent node of the deleted or added node). This will not change in v.3, v.4 which will have a beta out some time in May will use some sort of virtual DOM, where this will not be an issue.

**Comment by jcarlosgarciasegovia** [comment]
You should not close issues until they are fixed.
It also prevents other people from opening the same issue again.
Are those changes available in some branch?

**Comment by vakata** [comment]
Closing the issue as "won't fix" is closing none the less - as I said - this will not change in v.3, so basically - I will not fix this, and I am closing the issue as "won't fix".
As for v.4 - again - as I said - it will be available some time in May. As a branch of course, and all branches are public.

**Comment by jcarlosgarciasegovia** [comment]
Yes, I am calling refresh every time I need to refresh the tree from the server, as other users may have changed it.
What is the proper way to refresh the whole tree from the server without calling refresh()?

**Comment by mikila85** [comment]
is there a way to replace the data without calling refresh? (loading from JSON)

**Comment by vakata** [comment]
To fetch a new copy of the data you must use refresh, but you can use the skip_loading flag which skips the loading indicator. Also by using the massload plugin you can provide the whole tree in one request, so that there is one request, one redraw and no loading indicator - this will minimize any flashing (if any).

**Comment by mikila85** [comment]
skip_loading flag did the work wonderfully!!! it now replaces it without even the slightest flicker! thank you very much @vakata !!
