### ISSUE TITLE
jstree.min.js:3 Uncaught TypeError: Cannot read property 'scrollLeft' of null     at a.jstree.plugins.types.get_state (jstree.min.js:3)     at a.jstree.plugins.types.save_state (jstree.min.js:5)     at a.jstree.plugins.types.<anonymous> (jstree.min.js:5)     at e (jquery.1.11.min.js:2)

### ISSUE THREAD

**Issue by simar7777** [vakata/jstree#1745]
Hi,

I am trying to do the select_node but it's giving me the above error ..

I have created node using create_node and get the created information throgh get_node it's giving me the correct information but when i try to select the same node through select_node it's giving me the follwoing error .
jstree.min.js:3 Uncaught TypeError: Cannot read property 'scrollLeft' of null
    at a.jstree.plugins.types.get_state (jstree.min.js:3)
    at a.jstree.plugins.types.save_state (jstree.min.js:5)
    at a.jstree.plugins.types.<anonymous> (jstree.min.js:5)
    at e (jquery.1.11.min.js:2)

**Comment by vakata** [comment]
That can only mean there is no tree parent available - maybe you discarded the DOM node somehow (perhaps removed it). If that is not the case - please provide a demo (jsFiddle would be great), so that I can help you, I am closing this until further information is provided.
