### ISSUE TITLE
get_children_dom() may return false

### ISSUE THREAD

**Issue by cmb69** [vakata/jstree#1746]
If no child node is rendered, `get_children_dom()` returns `false`, but the [documentation states](https://www.jstree.com/api/#/?f=get_children_dom(obj)) that it returns a jQuery object. I would appreciate if the documentation could be fixed in this regard, because one might easily expect that an empty jQuery object would be returned instead.

**Comment by vakata** [comment]
It also states that the node in question must be rendered. 

jsTree has never relied on throwing errors so changing this to an error or an empty object does not make much sense - all functions return `false` on error. I know this is a bad design decision, but it is the one I went with years ago. This will change in v.4 (which is a few months away), but I won't be changing this behavior in v.3 - sorry.

**Comment by cmb69** [comment]
Thanks for the quick doc fix, and also for the info about v.4! :)
