### ISSUE TITLE
Problem using css library with bundle .net framework

### ISSUE THREAD

**Issue by renandegrandi** [vakata/jstree#1748]
I use the bundle minifier and agroup .net framework and I'm using version 3.3.4 of jstree.

Added the file style.css or style.min.css the bundle returns me some errors:

![arquive01](https://cloud.githubusercontent.com/assets/10565320/25246041/ca4cd37a-25dc-11e7-82a6-c97dacb46938.png)

Checking in the file I found that the problems are referring to this line of code:

![arquive02](https://cloud.githubusercontent.com/assets/10565320/25246056/d6742040-25dc-11e7-805b-001fd4a387bd.png)

My bundle declaration is as follows:

![archive03](https://cloud.githubusercontent.com/assets/10565320/25246066/de8414a2-25dc-11e7-9b63-bca766a2380e.png)

Have any tips if the problem is in my implementation?

**Comment by vakata** [comment]
Sorry, I can not help you with this, but I can assure you that the CSS in jstree is valid, so if for some reason it does not compress well it will have to do with the tool that is used, or the configuration. Unfortunately, I am not too familiar with the tools you mentioned so I can not help.

**Comment by renandegrandi** [comment]
@vakata If svg is built outside of the style sheet file, and in the filter tag just referenced the id, this problem does not occur even using the microsoft bundle, thus leaving compatibility with one more technology, you think you could make that change to That I can keep my library compatible with the source?

![04](https://cloud.githubusercontent.com/assets/10565320/25338193/b74901b8-28d4-11e7-919d-262792685f7c.png)

![05](https://cloud.githubusercontent.com/assets/10565320/25338214/ca25435a-28d4-11e7-8a2f-3b21e3f9dad3.png)

**Comment by vakata** [comment]
I do not want to change working code, because a tool can not handle it, yet. This is an issue with the bundle code, not with jstree. The SVG belongs in the CSS, not in the markup, moving it to the markup will generate a lot of extra code and troubles (multiple instances, ID generation, etc).

**Comment by renandegrandi** [comment]
thanks.
