### ISSUE TITLE
External drag&drop to jstree

### ISSUE THREAD

**Issue by Audax23** [vakata/jstree#1749]
Hi,
i work on a cms, and use jstree to list my website page structure, 
so on right, i have a list of articles, and would like to drag a representation of an article to change their page or category parent, i don't want JsTree to create a new node but just catch external event to make my request and update the data. 
is there any example or advice to do it, please.
i see an example on an alternative of this plugin, but i don't want to change for other, JsTree work great ! 
http://www.easyjstree.com/Demos/External
thank you for your help

**Comment by vakata** [comment]
The accepted answer here: https://groups.google.com/forum/#!topic/jstree/BYppISuCFRE
