### ISSUE TITLE
Use both multiple: true and false

### ISSUE THREAD

**Issue by aditya1122** [vakata/jstree#1750]
Hi

I want to implement the multiple:true on some nodes and multiple:false to other nodes in the same tree, but i could not find a way to do this.

**Comment by vakata** [comment]
You could:
1) use `conditionalselect` and prevent selecting nodes which should not work with multiple if Ctrl is down
or
2) you could listen for the `select_node.jstree` event and deselect all other nodes, if a node that is not supposed to wirk with multiple is selected.

Personally I believe 1) is a better approach as the node never gets selected.
