### ISSUE TITLE
icon: "glyphicon glyphicon-flash" not working

### ISSUE THREAD

**Issue by etamponi** [vakata/jstree#1751]
I am defining the following `jstree`, but the "glyphicon" icons are not rendering at all. What I am missing? I see the tree, and the default icon, but not the custom ones defined with "glyphicon":

```javascript
  $('#file-tree').jstree({
    'core' : {
      'data' : [
         'Simple root node',
         {
           'text' : 'Root node 2',
           'state' : {
             'opened' : true,
             'selected' : true
           },
           'children' : [
             { 'text' : 'Child 2', "icon" : "glyphicon glyphicon-flash" },
             'Child 1'
           ]
        }
      ]
    }
  });
```

NB: I am self-hosting `jstree`, jquery and the stylesheet. I tried with the CDN version but the problem is the same.

**Comment by etamponi** [comment]
Solved: I need to include bootstrap. This dependency is not specified anywhere in the documentation as far as I can see. Can you please add it?

**Comment by vakata** [comment]
It is not a dependency - the flash icon is just a demo for font-based icons.

**Comment by SS-jin** [comment]
is it possible to set glypicons as icon for jqxtree, when we pass json data to the jqxtree from server end, and need to set different icons depending upon a certain value in each instance of the json data ?

**Comment by vakata** [comment]
@SS-jin - this is jstree, not jqxtree - I have the wrong repository.

**Comment by SS-jin** [comment]
haha, thanks, we can't use glyphicons apparently in jqxtree, i stored them as png images in a directory and mapped the icon attribute to them, then could see those icons.
