### ISSUE TITLE
Html escape issue when editing

### ISSUE THREAD

**Issue by ft-lie** [vakata/jstree#1752]
Editing text adding e.g.  "& <>", leaving the node, and then editing again, gives ".... &amp; &lt; &gt;"

probably Html escape issue

**Comment by vakata** [comment]
You probably need to set this to `true`: https://www.jstree.com/api/#/?q=for&f=$.jstree.defaults.core.force_text

**Comment by ft-lie** [comment]
Thanks for clarifications.
Improvement suggestion: update description of force_text from "Force node text to plain text (and escape HTML). Defaults to false"  to e.g.

By default jsTree presumes node text to be html, which allows for formatting, images etc. 
When allowing to edit the node text, you may either create a custom editor, or set force_text to true, which then expects the text to be plain text, and not html. 

When force_text is true, "<b>this is bold</b>" will be shown as 
"<b>this is bold</b>" , i.e. literary with less-than b greater-than etc.,  and not as 
**this is bold** (in bold)
