### ISSUE TITLE
contextmenu: Open popup after modifying an item

### ISSUE THREAD

**Issue by manuzi1** [vakata/jstree#1756]
I don't know which listener I have to use to get my solution.

First question: Is it possible to get the item name in the listener?

```
function customMenu(node) {
            console.log(node);
            var items = {
                createItem:{
                    label: "Create folder",
                    action: function (data) {
                        //...
                    }
                },
                renameItem: {
                    label: "Rename Folder",
                    action: function (data) {
                        //...
                    }
                },
                deleteItem:{
                    label: "Delete Folder",
                    action: function (data) {
                        //...
                    }
                },
                propItem: {
                    label: "Folder Properties",
                    action: function (data) {
                        // A small popup should appear where the user can fill in some folder properties in textfields and save it or cancel it)
                        // when I call a function, how to open the popup? I have no selector for the "Folder Properties
                        // or use a listener i have to call?
                    }
                }
            };
            return items;
        }
```
So I have the items above, first three working finde, propItem is my custom one and I dont know how to do it:

My aim is that I chose a folder from the tree, make a rightclick, choose "Folder Properties", a popup appears and there I can insert some data in textfields. Press the save button and call a controller method to store it in the DB.

Here are my listeners:

```
        $('#jsTreeHtml1').jstree({
            "core": {
                "check_callback": true
            },
            "plugins": ["contextmenu", "state"],
            "contextmenu": { items: customMenu }
        }).on('rename_node.jstree', function (e, data) {
            if (data.old == "New node") {
                console.log("create folder");
               //....
            }
            else {
                console.log("edit folder");
                //...
            }
        }).on('delete_node.jstree', function (obj, data) {
            //...
        });
```

So I have these listeners, but I am not happy with that. When a folder is created, or a file is renamed, I have to use the rename_node listener, because the user is inserting the folder name (from the created one or the edited one) and I don't know how to check, from which item the call is coming.

To my problem in the header question: It is the same issue. When I can find the item name (for example: propItem) in the data of the listener, I could make an if statement with

```
.on('click', function(data){
  if(data.item = 'propItem'){
    //open the popup
}
```
But, I don't know how to do that.

**Comment by vakata** [comment]
Sorry, I do not understand the issue.

1) Open the popup as you normally would (if jstree was not on the page) - just invoke the JS that will open the popup. If you need something from the actual node - the `node` variable is in scope and you can read stuff from it.

2) Sorry, I do not understand how a click handler will have anything to do with the contextmenu property.

Please clarify and I will reopen, from what I currently understand all you need is scoped variables which you already have. Maybe if you provide a demo it will help me understand what the problem is.
