### ISSUE TITLE
Differences in displaying tree - JSON vs HTML

### ISSUE THREAD

**Issue by sSwiergosz** [vakata/jstree#1760]
Hi,

I've got two trees. One of them is populating with JSON(2) and the second is configuring with HTML (1). There are differences in displaying them. The JSON one doesn't have this 'dotted line' between nodes. 

1 - ![image](https://cloud.githubusercontent.com/assets/18450225/25945566/a7bc8ae6-3647-11e7-8114-83a220d1495d.png)

2 - ![image](https://cloud.githubusercontent.com/assets/18450225/25945542/9097c948-3647-11e7-9b17-73a3e7e4cf7c.png)

What can I do about this? They are using the same stylesheet.

**Comment by vakata** [comment]
I can not help you without a demo - a jsFiddle perhaps? In the mean time - you can explicitly configure the theme settings using this option: https://www.jstree.com/api/#/?q=dots&f=$.jstree.defaults.core.themes.dots

Please provide a demo and I will reopen.
