### ISSUE TITLE
a_attr not working using ajax

### ISSUE THREAD

**Issue by mtsys** [vakata/jstree#1761]
I am using C# MVC and returning a Json and a_attr is not working.
How to send a_attr through json and format it inside C#?

My C# Controller

```
public ActionResult Nodes() 
{ 
    var nodes = new List<JsTreeModel>(); 

    nodes.Add(new JsTreeModel() { id = "101", parent = "#", text = "Simple root node" });
    nodes.Add(new JsTreeModel() { id = "102", parent = "#", text = "Root node 1", a_attr = "class : no_checkbox" }); 
    nodes.Add(new JsTreeModel() { id = "103", parent = "102", text = "Child 1" }); 
    nodes.Add(new JsTreeModel() { id = "104", parent = "102", text = "Child 2" }); 
            
    return Json(nodes, JsonRequestBehavior.AllowGet); 
} 
```
My HTML

```
$('#html1').jstree({
    'plugins': ["checkbox"],
    'core': {
        'data': {
            'url': '/Ajax/Nodes',
            'data': function (node) {
                return { 'id': node.id };
            }
        }
    }
});

<div id="html1"></div>
```

My Result
`
[{"id":"101","parent":"#","text":"Simple root node","icon":null,"state":null,"opened":false,"disabled":false,"selected":false,"li_attr":null,"a_attr":null},{"id":"102","parent":"#","text":"Root node 1","icon":null,"state":null,"opened":false,"disabled":false,"selected":false,"li_attr":null,"a_attr":"class : no_checkbox"},{"id":"103","parent":"102","text":"Child 1","icon":null,"state":null,"opened":false,"disabled":false,"selected":false,"li_attr":null,"a_attr":null},{"id":"104","parent":"102","text":"Child 2","icon":null,"state":null,"opened":false,"disabled":false,"selected":false,"li_attr":null,"a_attr":null}]`

**Comment by vakata** [comment]
Sorry, I can not help you with C# related questions. All I can tell you is that `a_attr` should be an object in the resulting JSON.
