### ISSUE TITLE
how to get partially selected parent id

### ISSUE THREAD

**Issue by parulgupta09** [vakata/jstree#1762]
I am using "jstree" for treeview(Parent-Child) structure with checkboxes and returning id of each selected item.But i am getting only children's id . I am not getting partially selected parent id . So i want partially selected parent id too.
click [ http://jsfiddle.net/2kwkh2uL/5807/ ] to find the code.

**Comment by vakata** [comment]
Here is how you get ONLY the partially selected parents (those in indeterminate state):
http://jsfiddle.net/2kwkh2uL/5809/
