### ISSUE TITLE
Contextmenu visible on long-press on iPad

### ISSUE THREAD

**Issue by WeeJeWel** [vakata/jstree#1764]
When longpressing on an iPad, the native contextmenu appears next to the jstree contextmenu.

Originally reported here: https://github.com/athombv/homey/issues/1000#issuecomment-301699364

![d2eb3f32-3a11-11e7-8c67-f070bc4f31b0](https://cloud.githubusercontent.com/assets/319873/26201359/e6b113e4-3bd2-11e7-857d-27d828ac5873.png)

**Comment by vakata** [comment]
Please check again using the code from the master branch. If the issue is still there let me know and I will reopen. Sorry I am asking for this, but I do not currently have an iPad to test on.
