### ISSUE TITLE
Custom icon for each file type

### ISSUE THREAD

**Issue by Abubakar63** [vakata/jstree#1767]
Hi, 

Currently I am using 

var _makeJSTreeConfig = function(_files){
    return {
      "plugins" : [ "contextmenu","search", "state", "unique","changed", "types", "wholerow", "dnd"],
      'core' : {
        "check_callback" : function(operation, node, node_parent, node_position, more) {
          if (operation === "move_node") {
            return node_parent.original.type === "directory";
          }
          return true;
        },
        'data' : _files
      },
      'dnd': {
        'check_while_dragging': true
      },
      'contextmenu': {
        'items': _sidebarContextMenu
      },
      "types" : {
        'directory' : {
          'icon' : 'fa fa-folder'
        },
        'file' : {
          'icon' : custom_icon_class(_files)
        }
      }
    };
  };

mentioned code to display folder icon for folder types and file-code icon for file types. 

Now what we need to do is: we want custom icons for each file type. e.g. JS, HTML, XML etc 
JS -> 'fa fa-code-o'
HTML -> 'html-icon-class'
XML -> 'xml-icon-class'
How can I modify upper config to integrate our required change. Please guide.

Kind Regards,
Abubakar

**Comment by vakata** [comment]
You have two options: 
1) pass the custom icon with the data (not the config), or 
2) create separate node types for each file type you want to support - the same way as you have `file` add `js`, `html`, etc.
