### ISSUE TITLE
Drag&Drop issue regarding html.style.marginTop

### ISSUE THREAD

**Issue by cmb69** [vakata/jstree#1769]
If a `margin-top` is set on the `<html>` element, drag and drop does not work as expected in IE 11 (and presumably former versions). For instance, it is not possible to move a node inside another. This can be reproduced in the [demo](https://www.jstree.com/demo/), after setting:
````
html {margin-top: 37px}
````
Afterwards it is not possible to move "Child 1" into "Child 2", if the latter node is closed.

The problem is that [`rel`](https://github.com/vakata/jstree/blob/1dd7de3b742c20452ef86ea245e779f5a3aa68eb/dist/jstree.js#L6718) is calculated to be less than 0 (IE only), apparently caused by a bug in `jQuery.fn.offset()` which is documented to ignore the `margin-top` of the `<html>` element (but apparently doesn't on contemporary browsers).

**Comment by vakata** [comment]
Thank you for the detailed description. 
If I understand correctly this appears to be a bug with jQuery and not jsTree? There is nothing I can do about it from jsTree's side - let me know if I misunderstood you?

**Comment by cmb69** [comment]
On further investigation, I'm pretty sure it is a bug in jQuery, so I've filed jquery/jquery#3676. Sorry for the noise!
