### ISSUE TITLE
checkbox_disabled conflict with wholenode selection

### ISSUE THREAD

**Issue by mallezie** [vakata/jstree#1771]
Hi there, 

I've noticed there is a conflict when disabling a checkbox with the label click.
When a checkbox is disabled you cannot select / unselect it, which is off course the desired behaviour. 
However when clicking on the label of the item you can still select / unselect the checkbox. 
See http://jsfiddle.net/950ma5rv/2/
First child is disabled. Clicking the checkbox works as desired. Clicking the label does select / unselect it.

**Comment by vakata** [comment]
It is up to you the developer to sort out this behavior - `checkbox_disabled` is meant to do just that - disable the checkbox. 
If you want you can change various checkbox plugin options (like detach checkboxes from node selection, which is the main reason `checkbox_disabled` exists).
