### ISSUE TITLE
"'tie_selection' : false" not working as expected

### ISSUE THREAD

**Issue by marcelodive** [vakata/jstree#1773]
Good night, friend.

I'm trying to make `tie_selection` works when it's `false`, but without success.
I have done a simple [fiddle](http://jsfiddle.net/DGAF4/2208/) to show what is happening and I don't know what I'm doing wrong.

In this same fiddle, if you choose another option, like `visible : false`, it works fine.

Thanks.

**Comment by vakata** [comment]
Hello,

You also need to change the `whole_node` setting:
https://www.jstree.com/api/#/?q=checkbox&f=$.jstree.defaults.checkbox.whole_node

Here is the updated fiddle:
http://jsfiddle.net/DGAF4/2212/

Best regards,
Ivan

**Comment by marcelodive** [comment]
Oh, thank you SO much, @vakata!

Can I buy you a coffee? I didn't find a donation button in the project. ^^'

**Comment by vakata** [comment]
No problem - glad I could help.

If you want to support jstree - the donate button is on the homepage: https://www.jstree.com/ - the fourth (blue) button - right next to "report bugs".

Have a nice day,

**Comment by marcelodive** [comment]
Yeah!
The coffee was buyed! :D 
Thank you again.

`Receipt: 7MJ39394A9792071N`
