### ISSUE TITLE
create_node.jstree event not triggered with lazy load

### ISSUE THREAD

**Issue by vnea** [vakata/jstree#1774]
Hello,

I need to catch the event [create_node.jstree]( https://www.jstree.com/api/#/?f=create_node.jstree) but I'm using lazy load:
```javascript
$myTree.jstree({
        core: {
            // ....
            data: function(node, cb) {
                var nodes = [];
                // Create nodes ...

                cb.call(this, nodes);
            }
            // ...
        }
    })
    .on("create_node.jstree", function (node, parent, position) {
        console.log("Node created");
        // Need to do stuff with the new created node
    });
```
The problem is that the **create_node.jstree** is never triggered.

Is there any solution ?

**Comment by vakata** [comment]
create_node only fires when a node is created by **user interaction**. You are probably looking for the ```load_node.jstree``` event or the more general ```model.jstree``` event.
