### ISSUE TITLE
Modifying node names while loading the tree

### ISSUE THREAD

**Issue by BentCoder** [vakata/jstree#1775]
Hi,

Is there a way of firing event straight after creating a node on tree load? I need to modify the name of each node.

Thanks

Example below gets fired once after loading whole tree which makes no use for me.
```
$('#container').bind('loaded.jstree', function(event, data){
    console.log(data.instance);
}).jstree(); 
```

**Comment by vakata** [comment]
Take a look at the ```model.jstree``` event:
https://www.jstree.com/api/#/?q=model&f=model.jstree

**Comment by BentCoder** [comment]
Thanks for the response. I tried for about 2 hours now and need your help. I just need suffix all node names with `-DONE`. Do you mind updating https://jsfiddle.net/f7b1wj00/ ?

Thanks

**Comment by vakata** [comment]
Keep in mind this is not an optimal solution - if you are dealing with a large tree with no lazy loading it might be better to set the name in the data.
Anyway: https://jsfiddle.net/f7b1wj00/1/

**Comment by BentCoder** [comment]
Lovely, thank you very much. I actually have a massive tree (15K nodes) so I'll keep your suggestions in mind.

**Comment by BentCoder** [comment]
@vakata This is the last question. I didn't want to open up a new ticket as this is not issue like the original question above so adding it here.

I have seen your answer for exact match in search functionality `search.search_callback` but couldn't manage to implement in my case. JSFiddle is here: https://jsfiddle.net/fxmdzekn/ So when I search for `501` in, it shouldn't give me `Mulburry 501`. 

Much appreciated with your help and I must say this is a great library!

**Comment by vakata** [comment]
Here is the improved fiddle:
https://jsfiddle.net/fxmdzekn/1/

Best regards,
Ivan

**Comment by BentCoder** [comment]
Thank you.
