### ISSUE TITLE
Why not fill the property via ajax

### ISSUE THREAD

**Issue by mtsys** [vakata/jstree#1778]
I can not understand the reason that my ajax comes right, arrows the elements correctly and then the event is called (line 3507 jstree.js)

`this._data.core.state`

And all records are deselected as selected. I tested debugging
If you use the same data in txt format, it works perfectly

I think it has something to do with `this._data.core.state`

**Comment by vakata** [comment]
I am not sure I understand your question. State comes into play in those scenarios: 
1) if explicitly using the ```state``` plugin - if you do not want persistent selection across reloads you should not use the state plugin.
2) when using ```refresh``` - by default client side state is preserved, but there is a boolean argument to disable that behavior

If this does not answer your question - please clarify or provide a demo and I will reopen.
