### ISSUE TITLE
[Question] Re: Populating a node using a callback function with alternative initial tree

### ISSUE THREAD

**Issue by colingoldberg** [vakata/jstree#1780]
I am providing the alternative json format to initialize the tree.
eg. (per https://www.jstree.com/docs/json/)
{
  id          : "string" // required
  parent      : "string" // required
  text        : "string" // node text
...
}

I have not found anything in the documentation that allows me to lazy load a node given this format (c/f https://github.com/vakata/jstree#populating-the-tree-using-a-callback-function).

Is there a way to do this? How do I express this?

Colin Goldberg

**Comment by colingoldberg** [comment]
After posting the above a minute ago, I might have misread the documentation - I was thinking that the 'data' function was provided in the json. I think (correct me if I am wrong) that I can use the demonstrated method of using a callback function, and simply provide the tree - or subtree - using the alternative json format anyway.

**Comment by vakata** [comment]
Lazy loading works regardless of the data format chosen. And yes - if you want to use a function it is set in the config - check the homepage of this repository - there is a demo provided.
