### ISSUE TITLE
The contextmenu jsTree fails after AJAX load

### ISSUE THREAD

**Issue by manuzi1** [vakata/jstree#1784]
I have the following javascript (C#, MVC app) which is creating my folder structure inculding the contextmenu.
The thing is very easy, On the left side my folderstructure and on the right side should be a datatable with several rows which will be loaded from the "LoadFiles" Ajax request.

```
$('#foldertree').jstree({
    "core": {
        'data': data,
        'check_callback': true
    },
    "state": {"key": "foldertree"},
    "plugins": ["state", "contextmenu"],
    "contextmenu": { items: customMenu }
}).on('select_node.jstree', function (e, data) {
    var _id = parseInt(data.node.original.primarykey);
    if (data.node.parent != "#") {
        jQuery.ajax({
            async: true,
            method: "POST",
            data: {
                "id": _id,
                "foldertext": data.node.text
            },
            url: '@Url.Action("LoadFiles")',
            success: function (data) {
                $("#files").html(data);
            },
            failure: function (errMsg) {
                alert(errMsg);
            },
        });
    }
});
```

So it only works, when a subfolder is selected. And then it is adding the rows on the right side of the page ($("#files").html(data);).
As soon as I am clicking on a subfolder and the files are loaded, the tree is still present, but I cannot call any functions from the contextmenu. As I said using the contextmenu after clicking on the subfolder, the #files is loaded and then I want for example delete a parent folder, I get:
`Uncaught TypeError: $(...).jstree is not a function`

The whole thing (create, edit, delete folder) is working on the parentfolder until i click on the sub and load the folder div on success to the right side.

So my instance is created on #foldertree. And I have tried this already:
```
        jQuery.ajax({
            async: true,
            method: "POST",
            data: {
              ....
            }).done(function(){
              $('#foldertree').jstree(true).destroy(true);
              $('#foldertree').jstree();
            });
        });
```
Is there any way to achieve my goal, that I can us my contextmenu after the $("#files").html(data); is loaded?

**Comment by vakata** [comment]
I do not think this is related to jstree - please remove your custom items function and try again. 
Does it work? If it does - then the custom contextmenu items function is the problem. If it does not - please let me know and I will reopen.

**Comment by manuzi1** [comment]
Tried it, but does not work. You are propably right, but maybe you can help me.

I think that my jstree instance is destroyed when the AJAX request for the subfolder succeeded. It is loading a partial view ($("#files").html(data);) into the page.

Because first I have the error `Uncaught error: jstree is not a function` when I want to open the contextmenu. Then I add the <script>jstree.js</script> to my partial view.
After that the contextmenu is working, but when i click on delete it is saying `Uncaught error: jstree(...).delete_node is not a function.

So is there a way to reload it or anything? Or do you have a comparable case? I just found this on SO: https://stackoverflow.com/questions/29406628/how-can-i-initialize-jstree-on-a-dynamically-loaded-asp-net-mvc-partial-view-tha (think the answer is from you).

I tried it, but when I execute your solution with .destroy and "reload" .jstree(); I just see the parent folders and can do nothing. Cannot expand them, no contextmenu, even the onclick log isnt fired.

**Comment by vakata** [comment]
As far as I understand - you are using .net's AJAX containers which are emptied and filled again when the AJAX call succeeds (or you are manually doing the same - removing the tree and adding new markup). jsTree will not work like that - the main DOM node should remain in the document DOM tree - once removed all bindings and events will fail (the effect you are seeing).
It this is not the case - please provide a minimal demo of the problem and I will have a look.

**Comment by cun3** [comment]
@manuzi1  I have the same issue. Were you able to find the solution for that? Is there a way to fix it?
