### ISSUE TITLE
Remove child nodes and redraw / bind jstree inside selected node not working

### ISSUE THREAD

**Issue by Mayur23491** [vakata/jstree#1785]
3
down vote
favorite
I have used jstree to bind the data inside it.

But whenever I open the node I mean expand the node it overwrite the existing with double time binding I have tried following FAQ but not getting the solution.

http://javascript.qahowto.com/How-to-remove-child-nodes-of-selected-node-in-jstree-javascript-jquery-jstree-11fce56

https://stackoverflow.com/questions/18861654/how-to-remove-child-nodes-of-selected-node-in-jstree

I have also tried the following code it removes in debugging but it binds again double time.

$("#" + $("#jstree").jstree("get_selected")).find('li').remove();

$("#jstree").jstree("remove", $('#jstree').find('.jstree-node'));

**Comment by vakata** [comment]
Sorry but I am not sure I understand the question.

Both links are using very old versions of jstree which have not been supported for years - if you are using v.1 - I can't help you. If you are using the latest v.3 then those guides will not work for you.

To remove children of the selected node you can use:
```js
var nodeID = $("#jstree").jstree(true).get_selected()[0];
var children = $("#jstree").jstree(true).get_node(nodeID).children;
$("#browser").jstree(true).delete_node(children);
```
Here is a demo (select ```node```):
http://jsfiddle.net/DGAF4/2255/

If I missed something please let me know and I will reopen.

**Comment by mayank5oct** [comment]
I want to delete children the create new children. is this possible ?

**Comment by mayank5oct** [comment]
I want to delete children then create new children. Is this possible ?
