### ISSUE TITLE
Question: wholerow and dnd together: dnd on the whole row not working

### ISSUE THREAD

**Issue by fr00x** [vakata/jstree#1786]
Dear Ivan,

Many thanks for your plugin. I love it and will happily donate once my project is done.

I am using both "wholerow" and "dnd" plugins identical to what the demo on https://www.jstree.com/demo/ display. The demo page serves as an example for this question.

How could I control jsTree to allow drag and drop on the whole row? Currently in my and the demo setup, only the label itself is dragable.

Version in sue: 3.3.4

Thank you.

**Comment by vakata** [comment]
Hi,

You are looking for the ```large_drag_target``` option:
https://www.jstree.com/api/#/?q=dnd.large&f=$.jstree.defaults.dnd.large_drag_target

Best regards,
Ivan
