### ISSUE TITLE
Can't select multiple nodes

### ISSUE THREAD

**Issue by sathio** [vakata/jstree#1787]
so, i'm trying to select programmatically some nodes on my tree 

    var ref = $('#scenes_tree').jstree(true);
    ref.close_all();
    ref.deselect_all(true);
    ref.select_node([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], true); 

but not all nodes are selected, in fact only nodes from 1 to 4 are selected.
it's not an issue with nodes id because if i close all the nodes I can happily select node number 10 

    ref.close_all();
    ref.deselect_all(true);
    ref.select_node([10],true);  //node 10 is now open

here's a video 
https://gfycat.com/PoisedDimpledIrishwolfhound

Here's the jsfiddle
https://jsfiddle.net/a4t87yaw/16/

is there something I'm doing wrong?

**Comment by sathio** [comment]
Seems like the css classes are correctly set but for some reason they're invisible.  

![screen shot 2017-07-05 at 16 14 34](https://user-images.githubusercontent.com/1990816/27868481-18038086-619d-11e7-8581-d62770638a50.jpg)

**Comment by vakata** [comment]
This is not a bug - you are suppressing the event - wholerow relies on those events. ```supress_event``` is an internal parameter to ```select_node``` you should use it with caution.

To resolve your issue - remove the second param to ```select_node```. Here is the fixed fiddle:
https://jsfiddle.net/a4t87yaw/17/

**Comment by sathio** [comment]
I see, the problem I have is that I need to suppress the event, otherwise a lot of other issue arise on my application.

thanks anyway

**Comment by vakata** [comment]
In that case you can select the first nine nodes with the second param as `true`, and remove it on the last invocation, that way you get a single ```changed``` event.
