### ISSUE TITLE
Angular 2 integration using typescript 

### ISSUE THREAD

**Issue by HackPoint** [vakata/jstree#1790]
https://stackoverflow.com/questions/44987260/how-to-add-jstree-to-angular-2-application-using-typescript-with-types-jstree?noredirect=1#comment76955233_44987260

**Comment by vakata** [comment]
I am not familiar with angular, but there are a few good jstree wrapper directives as far as I know - have a look at them.

**Comment by rakshitharathika** [comment]
hi,
   
   i have to need tree strcture to use the angular5
