### ISSUE TITLE
Get all siblings, when one child is selected

### ISSUE THREAD

**Issue by manuzi1** [vakata/jstree#1792]
The case, that I have the state plugin causes that my useres can reach child folders without clicking onto the parent folder.

The child folder has no attribute how many siblings it has. What is the easiest way to retrieve the amount of  the children folders.

In the parent node I have no problem to get the length of the children, but select_node on a child folder doesn't give me the count of the siblings, which I need. The object just gave me the parent, which is a useful information for this. But this assumes, that the user has to go back, because my object isnt the parent anymore.

Is there an easy way to achieve this?

**Comment by vakata** [comment]
I am not sure I understand correctly but you probably need this:
```js
$('#tree').jstree(true).get_node('the_parent_id_you_have').children.length
```

If I misunderstood - please clarify.
