### ISSUE TITLE
Node event change from original

### ISSUE THREAD

**Issue by MoraesGil** [vakata/jstree#1794]
Can I set listner to when node.state changed from node.original.state ??

I have
node.exemple = node.original.exeple.

and i would catch change when .
node.exemple != node.original.exeple

**Comment by vakata** [comment]
No, this is not possible - jstree does not monitor object change and does not fire such events, as jstree itself will never modify those custom properties. If they are modified, the modification is done outside of jstree - so you can monitor those changes yourself using standard JS practices.
