### ISSUE TITLE
Help with popover

### ISSUE THREAD

**Issue by aline-matos** [vakata/jstree#1795]
I'm trying to integrate jstree with popover of bootstrap on hover some of nodes, but I can't add in the specify node:

`$('#trucks').on('hover_node.jstree', function (node, obj) {
        if(obj.node.original.attr.type == 'truck'){
            console.log(obj);
            $(obj).popover({
                placement: 'right',
                container: 'body',
                html: true,
                trigger: 'click',
                content: function () {
                    return 'teste';
                }
            });
        }
    });`

Someone have already done this?

**Comment by vakata** [comment]
Are you sure this actually triggers a popup? My guess is it only binds it. You could also use pure DOM event delegation and not rely on ```hover_node```:
```
$('#tree').on('mouseenter', '.jstree-anchor', function () {
  var node = $('#tree').jstree(true).get_node(this);
  // rest of code
});
```

I am closing this as it is not an issue with jstree, and aside from the code above there is nothing more I can do to help.

**Comment by aline-matos** [comment]
Thank you @vakata :+1:
