### ISSUE TITLE
For ie8

### ISSUE THREAD

**Issue by guoxiongpeng** [vakata/jstree#1796]
For surpporting ie8,you don`t need change too more code.Just add some code like this at the head of jstree.js:

if (!Array.prototype.every) 
	{
	  Array.prototype.every = function(fun /*, thisp*/)
	  {
	    var len = this.length;
	    if (typeof fun != "function")
	      throw new TypeError();  
	     var thisp = arguments[1];
	    for (var i = 0; i < len; i++)
	    {
	      if (i in this &&
	          !fun.call(thisp, this[i], i, this))
	        return false;
	    } 
	     return true;
	  };
	}
	if (!Array.prototype.indexOf)
	{
	  Array.prototype.indexOf = function(elt /*, from*/)
	  {
	    var len = this.length >>> 0;
	    var from = Number(arguments[1]) || 0;
	    from = (from < 0)
	         ? Math.ceil(from)
	         : Math.floor(from);
	    if (from < 0)
	      from += len;

	    for (; from < len; from++)
	    {
	      if (from in this &&
	          this[from] === elt)
	        return from;
	    }
	    return -1;
	  };
	}

	if (!Array.prototype.filter)
	{
	  Array.prototype.filter = function(fun /*, thisp*/)
	  {
	    var len = this.length;
	    if (typeof fun != "function")
	      throw new TypeError(); 
	     var res = new Array();
	    var thisp = arguments[1];
	    for (var i = 0; i < len; i++)
	    {
	      if (i in this)
	      {
	        var val = this[i]; // in case fun mutates this
	        if (fun.call(thisp, val, i, this))
	          res.push(val);
	      }
	    } 
	     return res;
	  };
	}
	if (!Array.prototype.forEach)
	{
	  Array.prototype.forEach = function(fun /*, thisp*/)
	  {
	    var len = this.length;
	    if (typeof fun != "function")
	      throw new TypeError(); 
	     var thisp = arguments[1];
	    for (var i = 0; i < len; i++)
	    {
	      if (i in this)
	        fun.call(thisp, this[i], i, this);
	    }
	  };
	}
	if (!Array.prototype.map)
	{
	  Array.prototype.map = function(fun /*, thisp*/)
	  {
	    var len = this.length;
	    if (typeof fun != "function")
	      throw new TypeError(); 
	     var res = new Array(len);
	    var thisp = arguments[1];
	    for (var i = 0; i < len; i++)
	    {
	      if (i in this)
	        res[i] = fun.call(thisp, this[i], i, this);
	    } 
	     return res;
	  };
	}
	if (!Array.prototype.some)
	{
	  Array.prototype.some = function(fun /*, thisp*/)
	  {
	    var len = this.length;
	    if (typeof fun != "function")
	      throw new TypeError(); 
	     var thisp = arguments[1];
	    for (var i = 0; i < len; i++)
	    {
	      if (i in this &&
	          fun.call(thisp, this[i], i, this))
	        return true;
	    } 
	     return false;
	  };
	}
	if (!Array.prototype.lastIndexOf)
	{
	  Array.prototype.lastIndexOf = function(elt /*, from*/)
	  {
	    var len = this.length; 
	     var from = Number(arguments[1]);
	    if (isNaN(from))
	    {
	      from = len - 1;
	    }
	    else
	    {
	      from = (from < 0)
	           ? Math.ceil(from)
	           : Math.floor(from);
	      if (from < 0)
	        from += len;
	      else if (from >= len)
	        from = len - 1;
	    } 
	     for (; from > -1; from--)
	    {
	      if (from in this &&
	          this[from] === elt)
	        return from;
	    }
	    return -1;
	  };
	}

**Comment by vakata** [comment]
I want to keep native prototype modification to a minimum. Anyway - I believe currently (the version from the master branch) works fine in IE8, there was a big with 3.3.4, but it is now fixed and 3.3.5 should work normally with IE8 without prototype modification.

**Comment by guoxiongpeng** [comment]
Got it.

**Comment by 6epcepkep** [comment]
@vakata hello! Error in ie8 ('d' is null or not an Object) I tried to connect different versions of updated jstree and jquery (preferably version 1.12.4) but still a mistake. Anything you can recommend?
