### ISSUE TITLE
If I use checkbox and dnd plugin cannot drag checked elements

### ISSUE THREAD

**Issue by falinsin** [vakata/jstree#1797]
I can drag unchecked elements but cannot drag cheked ones.

So I have to uncheck a checked element, then I can start dragging and at the end check it again.

Is this a known issue or something I´m doing wrong?

**Comment by vakata** [comment]
I can not reproduce the issue:
http://jsfiddle.net/DGAF4/2275/

Please update this fiddle so that the issue can be reproduced and I will reopen.

**Comment by falinsin** [comment]
Here is my fiddle, hope you can see what im doing bad.
http://jsfiddle.net/DGAF4/2277/

Thanks in advance

**Comment by vakata** [comment]
I have absolutely no issue with dragging the selected elements. The drag is always initiated. Keep in mind by default jstree will drag the whole selection if a selected node is dragged - you may need to set this option to ```false``` (depending on your needs):
https://www.jstree.com/api/#/?q=drag&f=$.jstree.defaults.dnd.drag_selection

If this is not it - please describe the problem - what is happening and what do you expect to happen? Which browser are you using? Do you see any errors in the console?

**Comment by falinsin** [comment]
seting this:

{"drag_selection":false},

as you reccomend solve my problem in my especific tree

Thank you very much.
