### ISSUE TITLE
Cannot read property'state' of undefined

### ISSUE THREAD

**Issue by krunalc** [vakata/jstree#1798]
I'm using v3.2.1 of jstree.

I'm trying to update the child of the nodes being expanded as per following code.
`    $('#tree_3').on('open_node.jstree', function (e, data) {
        var result = find(jsonTreeData, data.node.id);
        var testRootNodeChild1 = {};
        testRootNodeChild1.id = "TestChild1_Id";
        testRootNodeChild1.text = "TestChild1";
        result.children.push(testRootNodeChild1);
        $("#tree_3").jstree(false).refresh_node(data.node.id);
    });

    function find(source, id) {
        for (key in source) {
            var item = source[key];
            if (item.id == id)
                return item;

            // Item not returned yet. Search its children by recursive call.
            if (item.children) {
                var subresult = find(item.children, id);

                // If the item was found in the subchildren, return it.
                if (subresult)
                    return subresult;
            }
        }
        // Nothing found yet? return null.
        return null;
    }
`

Is this correct way of adding/updating the children of node being expanded? Can I avoid refresh of full tree?

With above code, I'm able to add new node as a child but when refresh is executed I get the error as shown in screenshot below 
![image](https://user-images.githubusercontent.com/7286816/28334358-82a970e6-6c18-11e7-86f3-0e9db37881f5.png)

Can you provide appropriate code sample to update the children of the node being expanded?

Thanks,

**Comment by vakata** [comment]
This error means you have a duplicate ID in your tree - either make sure your IDs are unique, or let jstree autogenerate the IDs. As for updating and creating nodes - there are plenty of examples on the home page of this repo and on jstree.com

**Comment by krunalc** [comment]
Following is the html generated by my code :
`<ul class="jstree-container-ul jstree-children" role="group"><li role="treeitem" aria-selected="true" aria-level="2" aria-labelledby="ab5f416f-1edd-4ab0-846e-1621ccfff7d7_anchor" aria-expanded="true" id="ab5f416f-1edd-4ab0-846e-1621ccfff7d7" class="jstree-node  jstree-open jstree-last" aria-busy="false"><i class="jstree-icon jstree-ocl" role="presentation"></i><a class="jstree-anchor jstree-clicked" href="#" tabindex="-1" id="ab5f416f-1edd-4ab0-846e-1621ccfff7d7_anchor"><i class="jstree-icon jstree-themeicon fa fa-building icon-state-danger icon-lg jstree-themeicon-custom" role="presentation"></i>Organization1</a><ul role="group" class="jstree-children"><li role="treeitem" aria-selected="false" aria-level="3" aria-labelledby="j1_8_anchor" id="j1_8" class="jstree-node  jstree-leaf"><i class="jstree-icon jstree-ocl" role="presentation"></i><a class="jstree-anchor" href="#" tabindex="-1" id="j1_8_anchor"><i class="jstree-icon jstree-themeicon" role="presentation"></i>Child node 1</a></li><li role="treeitem" aria-selected="false" aria-level="3" aria-labelledby="j1_9_anchor" id="j1_9" class="jstree-node  jstree-leaf jstree-last"><i class="jstree-icon jstree-ocl" role="presentation"></i><a class="jstree-anchor" href="#" tabindex="-1" id="j1_9_anchor"><i class="jstree-icon jstree-themeicon" role="presentation"></i>TestChild1</a></li></ul></li><li role="treeitem" aria-selected="false" aria-level="1" aria-labelledby="a7c17d05-f3a6-4031-b858-f42430a204d2_anchor" aria-expanded="false" id="a7c17d05-f3a6-4031-b858-f42430a204d2" class="jstree-node  jstree-closed"><i class="jstree-icon jstree-ocl" role="presentation"></i><a class="jstree-anchor" href="#" tabindex="-1" id="a7c17d05-f3a6-4031-b858-f42430a204d2_anchor"><i class="jstree-icon jstree-themeicon fa fa-building icon-state-danger icon-lg jstree-themeicon-custom" role="presentation"></i>Organization2</a></li><li role="treeitem" aria-selected="false" aria-level="1" aria-labelledby="24b5f759-6045-495f-ad5b-1c392c3bf670_anchor" aria-expanded="false" id="24b5f759-6045-495f-ad5b-1c392c3bf670" class="jstree-node  jstree-closed jstree-last"><i class="jstree-icon jstree-ocl" role="presentation"></i><a class="jstree-anchor" href="#" tabindex="-1" id="24b5f759-6045-495f-ad5b-1c392c3bf670_anchor"><i class="jstree-icon jstree-themeicon fa fa-building icon-state-danger icon-lg jstree-themeicon-custom" role="presentation"></i>Organization3</a></li></ul>`

I'm not able to figure out the duplicate id in above html. Can you pls help to figure out the issue?

**Comment by vakata** [comment]
The issue is with your JS:
```
testRootNodeChild1.id = "TestChild1_Id";
testRootNodeChild1.text = "TestChild1";
result.children.push(testRootNodeChild1);
```

You are appending the same node (with the same ID) to all opened nodes.

You could also remove your ```find``` function and do this instead:
```
$('#tree_3').on('open_node.jstree', function (e, data) {
  data.instance.create_node(data.node, { text : 'some title' });
});
```

**Comment by krunalc** [comment]
Above just one line of code suggested by you did the trick and works the way I want it to be. 

Thanks for your help.
