### ISSUE TITLE
How can I get the list of selected nodes in real visual order 

### ISSUE THREAD

**Issue by falinsin** [vakata/jstree#1799]
Sorry, I've been all day trying to get the list of selected nodes but in the last order we see in the tree.

Here a very simple fiddle:

http://jsfiddle.net/DGAF4/2323/

You can Check/uncheck elements and drag & drop  but when I get the node list always list in the original order no matter if I reorder elements using drag & drop.

Is there a way of get selected and in the real visual order?

Thank you very much for your help

**Comment by vakata** [comment]
I do not think you can get them in the order you want - there is no such order. Let me explain - nodes can be on many different levels so you could do a breadth first or depth first search. This is up to you to implement. 

As for a solution you can try - use the ```get_json``` method to get the whole tree as a flat array and then filter all selected nodes (using ```.filter``` for example) - that way the you will have the selected nodes in depth first mode.
