### ISSUE TITLE
Separator is not visible in context menu

### ISSUE THREAD

**Issue by krunalc** [vakata/jstree#1800]
after adding context menu plugin, I have configured context menu as per following in my code :

`                            "AddSite": {
                                "icon": "fa fa-sitemap",
                                "separator_before": false,
                                "separator_after": true,
                                "label": "Add site",
                                "action": function (obj) {
                                    AddSite();
                                }
                            },
                            "AddOrg": {
                                "icon": "fa fa-building",
                                "separator_before": false,
                                "separator_after": false,
                                "label": "Add organization",
                                "action": function (obj) {
                                    AddOrganization();
                                }
                            },
                            "UpdateOrg": {
                                "icon": "fa fa-pencil",
                                "separator_before": true,
                                "separator_after": false,
                                "label": "Update organization",
                                "action": function (obj) {
                                }
                            },
                            "RemoveOrg": {
                                "icon": "fa fa-trash",
                                "separator_before": true,
                                "separator_after": true,
                                "label": "Remove organization",
                                "action": function (obj) {
                                }
                            },
                            "ViewAll": {
                                "icon": "fa fa-eye",
                                "separator_before": true,
                                "separator_after": false,
                                "label": "View all organizations",
                                "action": function (obj) {
                                    ViewAllOrganizations();
                                }
                            }
`

With above code in place, I was expecting to see a separator after "Add site" and "Remove Organization" menu items. But I don't see any separator irrespective of the value I set for "separator_after" or "separator_before" as you can see below in the image.

![image](https://user-images.githubusercontent.com/7286816/28405113-96216304-6d49-11e7-9f5a-eaa6311bf3df.png)

Can you suggest what is the problem with the code? What needs to be corrected in order to set the separators?

Regards,
Krunal

**Comment by vakata** [comment]
You obviously have modified the contextmenu CSS a lot. Please check your own rules - the separators should be in the markup, but something in your own CSS has them hidden.

Here is a demo: http://jsfiddle.net/2kwkh2uL/6177/
