### ISSUE TITLE
need events for unique plugin

### ISSUE THREAD

**Issue by jeansfish** [vakata/jstree#1801]
When unique plugin enabled and renaming a node with existing one, all functions work fine. But is there any event to raise to say the rename cancelled due to duplicated name, so that I can handle it, e.g. having a popup to tell user why.

**Comment by vakata** [comment]
The ```core.error``` callback will be triggered. Inside the callback you will receive the error parameter which has all the information you need - which plugin triggered the error, the error code, etc.
