### ISSUE TITLE
unable to search on specific property

### ISSUE THREAD

**Issue by tancndi** [vakata/jstree#1804]
I have a model that looks like this in the tree `{id: value1, text: description, parent: parent1}`. 
I'm wondering if there is a way to search an item based on the id ? Because actually the search plugin only process on the text property on my tree model.

**Comment by vakata** [comment]
Use the ```search_callback``` option - that way you have full control over matching:
https://www.jstree.com/api/#/?q=search_call&f=$.jstree.defaults.search.search_callback
