### ISSUE TITLE
Valid children issue

### ISSUE THREAD

**Issue by MehdiBela** [vakata/jstree#1805]
Hello,

I face sort of a bug with types plugins valid children. It's working fine except in one case. Below is a screenshot of my issue: if i drag and drop an invalid children element at the left of the element, it's prevented, but at the right of it it's not prevented. Red circles represent the position of my cursor when drag and dropping. I dont have this issue with parent or children elements. On the left of the screenshot is the bug, on the right the expected behavior. 
 
![image](https://user-images.githubusercontent.com/22913703/28712681-5940763e-738c-11e7-8511-a1b1d69b3da3.png)

**Comment by vakata** [comment]
Please provide a demo of the issue - a jsFiddle (for example) will be helpful.

**Comment by MehdiBela** [comment]
Here it is, sorry CSS lacking though.

**Comment by vakata** [comment]
Please provide a **working** fiddle of the issue. This one contains multiple missing files and tries to make AJAX requests - I can not help you with the limited information you are supplying. 

I did however notice that you are using ```wholerow``` - you might want to set this option to ```true``` (it might fix the issue you are having):
https://www.jstree.com/api/#/?q=large&f=$.jstree.defaults.dnd.large_drop_target

**Comment by MehdiBela** [comment]
I'm trying to make that jsfiddle work but it takes more time than in an actual IDE. I've tried enabling large_drop_target but it makes the whole row appears as a valid children, instead of the left side of the anchor.
