### ISSUE TITLE
Types plugin with glyphicons - sometimes wrong icon image

### ISSUE THREAD

**Issue by JHeskethUK** [vakata/jstree#1806]
I've been using jsTree on and off now for several months and it's a great product! Every problem I've had so far I've been able to resolve by searching the issues and questions.

However, I'm not sure how to get around this one, so I'd appreciate some help.

I've distilled the issue down to its simplest form:
3 types: default (icon = false), love (glyphicon-heart, black) and hate (glyphicon-remove, red).

I can toggle the type of a node between love and hate with no problem - the colour and icon changes as expected.

However, if I set the type to hate, then unset it (set type to default) and then set it to love, the colour and tooltip (set with a_attr title) change correctly but the icon remains as a cross instead of changing to a heart.

I've attached an example - click the 'Hate' button then 'Love' to see the intended styles, then click on 'Hate', then 'Unset' then 'Love' in that order to see the issue.
[testJsTree.zip](https://github.com/vakata/jstree/files/1182782/testJsTree.zip)

Looking in the browser developer tools, it looks like the glyphicon-remove class is not being removed when the type is changed to default, so when it is then changed to love it has both the glyphicon-remove and glyphicon-heart classes, and glyphicon-remove wins.

I'm using jsTree 3.3.4.

**Comment by JHeskethUK** [comment]
Hi, I see this has been closed. Would you mind telling me how to fix the issue? Am I setting the type icons incorrectly?

**Comment by vakata** [comment]
It is closed from a commit - it was a bug and I fixed it - thank you.

You can either pull the jstree source from github or wait for the next
release.
