### ISSUE TITLE
Add item to Context menu

### ISSUE THREAD

**Issue by g14nluk4** [vakata/jstree#1807]
hi , how can i add a new item to default context menu , i mean  i wanna the default context menu with 1 item customized by me?

**Comment by MehdiBela** [comment]
Here is a snippet of a custom context menu I wrote : 
` "contextmenu": {
            "items": function (node) {
                return custom_context_menu(node, yourTree);
            }
        }`
and an extract of function custom_context_menu(node, yourTree)

` items.liens = {
        'label': 'Lier',
        'separator_before': true,
        'icon': 'fa fa-link'
    }
    items.liens.submenu = {
        'label': {
            'label': 'label',
            'action': function () {
                return link_or_comp('link', 'HW');
            },
            'separator_before': true,
            'icon': 'fa fa-microchip'
        },
(...)
return items
`

**Comment by g14nluk4** [comment]
thank you , it was usefull !
