### ISSUE TITLE
How to differentiate an item from a subitem?

### ISSUE THREAD

**Issue by MarlonSi** [vakata/jstree#1808]
How to differentiate an item from a subitem?

I have as output using the code
console.log($('#data').jstree(true).get_selected()); 

This array: 
["27", "28", "33", "35", "36"]

Being that:

27 - category
   28 - subcategory
   33 - subcategory
35 - category
   36 - subcategory

How can I differentiate to save in the database?
Thank you.

**Comment by vakata** [comment]
You can use ```get_selected(true)``` and get the full node objects - then you can inspect their parents, children, etc. 

You can also depending on your needs use ```get_bottom_selected``` or ```get_top_selected``` - read up on those in the api docs.
