### ISSUE TITLE
create_node failed in Google Chrome

### ISSUE THREAD

**Issue by Kharmanoid** [vakata/jstree#1810]
According to documentation create_node function takes second parameter "node" which can be simple string with the name. This workflow leads to error in Chrome: "**Uncaught TypeError: Cannot create property 'text' on string 'bla-bla-bla' at a.jstree.plugins.contextmenu.create_node (jstree.min.js:6)**"

**Comment by vakata** [comment]
I created a demo working off your description:
http://jsfiddle.net/2kwkh2uL/6239/

I see no problem - please update the fiddle so that I can see the issue and I will reopen.

Best regards,
Ivan
