### ISSUE TITLE
Last level of nodes is not shown

### ISSUE THREAD

**Issue by AlirezaAhmadiRad** [vakata/jstree#1811]
Hello
This is the set of data that I'm feeding to HSTree:
window.LeftTreeData = [];
window.LeftTreeData.push(
{'text': 'System Manager-1.0.0' ,'id': 'ba83a87a-b783-495a-a9ed-134ff35af806', 'parent': '#', 'state' : { 'disabled' : false, 'selected' : false}, 'type': 'root'},
{'text': 'Application Manager' ,'id': 'ad9eb540-9c58-4a5b-b75e-3ceedd018193', 'parent': '09b88c42-6047-4409-af33-72fc0f6fcbac', 'state' : { 'disabled' : false, 'selected' : false}, 'type': 'd8eac5fd-14f7-4c4a-8cda-8437869c43c6'},
{'text': 'A994782C-53EF-463C-AC5C-286EC8020F18' ,'id': 'a80dde43-a3a8-4cee-8bc1-4b7a850a1ce2', 'parent': 'a09550f9-0ae0-4d72-98de-03a20be2f48c', 'state' : { 'disabled' : false, 'selected' : false}, 'type': 'folder'},
{'text': 'Packages and licensing' ,'id': 'd2959c22-3350-4e32-b937-719320960292', 'parent': '09b88c42-6047-4409-af33-72fc0f6fcbac', 'state' : { 'disabled' : false, 'selected' : true}, 'type': '8d7e53ea-ff92-4d04-bad4-73e62422df6a'},
{'text': 'Currently running' ,'id': '39c43b34-2ba1-438c-b5df-a451c1aa67bd', 'parent': 'ba83a87a-b783-495a-a9ed-134ff35af806', 'state' : { 'disabled' : false, 'selected' : false}, 'type': '8e06d7ab-de6e-450e-a29c-5d9bdb5b3ff6'},
{'text': 'Application Explorer' ,'id': 'a09550f9-0ae0-4d72-98de-03a20be2f48c', 'parent': 'ba83a87a-b783-495a-a9ed-134ff35af806', 'state' : { 'disabled' : false, 'selected' : false}, 'type': '88c1c08a-c3c1-49dc-93ba-feaf03440fb9'},
{'text': 'Group Membership' ,'id': 'a330a039-043a-4eae-b2d4-6501fd96398b', 'parent': 'ba83a87a-b783-495a-a9ed-134ff35af806', 'state' : { 'disabled' : false, 'selected' : false}, 'type': 'ac47e7e0-57f3-4ce5-82f0-30bea1d7ff66'},
{'text': 'Group Manager' ,'id': '210d9420-ce39-4cfd-ba56-7cd9a0754f5d', 'parent': '09b88c42-6047-4409-af33-72fc0f6fcbac', 'state' : { 'disabled' : false, 'selected' : false}, 'type': '1da53ac4-6608-4ba9-a2f3-d18c5ba012eb'},
{'text': 'User Settings' ,'id': '75dfbe54-1bb7-46c6-8503-6243d13c2b8b', 'parent': 'ba83a87a-b783-495a-a9ed-134ff35af806', 'state' : { 'disabled' : false, 'selected' : false}, 'type': '1a8f4dd0-141f-4db6-ae9d-f86a537cb672'},
{'text': 'Administration' ,'id': '09b88c42-6047-4409-af33-72fc0f6fcbac', 'parent': '39c43b34-2ba1-438c-b5df-a451c1aa67bd', 'state' : { 'disabled' : false, 'selected' : false}, 'type': 'f95b6c08-a9fc-45a0-a67c-0f286a3f3ecb'}
);

and this is how I start the plugin:

    var $mytree = $('#TreeMenuDiv').jstree
    (
        {
            plugins: ["types", "contextmenu"],
            core: {
                'check_callback': true,
                data: window.LeftTreeData
            },
            types: types,
            contextmenu: { 'items': JSTree_ContextMenu }
        }
    );
Plgin simply doesn't show the level of nodes that one of them is selected.
Please help

Thanks

**Comment by vakata** [comment]
Please provide a demo of the issue - modify this fiddle I created from your code:
http://jsfiddle.net/2kwkh2uL/6238/

I believe that it is working fine (I see no problem), so I will close this for now, once you give me more information about the issue I will reopen if needed.
Thank you.

**Comment by AlirezaAhmadiRad** [comment]
You are right.
Problem was somewhere else: a typing mistake in open_node event was preventing the normal behavior.
Thanks for the good job.
