### ISSUE TITLE
jQuery deprecates $.isArray in 3.2.0

### ISSUE THREAD

**Issue by brendon** [vakata/jstree#1812]
As per https://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/ and https://github.com/jquery/jquery/issues/2961

Apparently you can just use `Array.isArray` instead.

**Comment by vakata** [comment]
Unfortunately that is not an option - I will keep the deprecated method for now as jstree 3.x supports IE8 which does not have ```Array.isArray```. jsTree 4.x does not depend on jquery at all but is not yet published - I believe by the time ```jQuery.isArray``` is removed, jsTree v.4 will be stable.
I will however keep this in mind, and if there are any delays in v.4 I will address the issue.
Thank you.

**Comment by brendon** [comment]
Thanks @vakata. Just a thought for in the meantime, how about an intermediary method in jstree that checks for `Array.isArray` and just uses that instead of calling the jQuery method? That way there'd be no deprecation warnings for jQuery 3 users and IE8 would still be supported.
