### ISSUE TITLE
Dynamic contextmenu with AJAX

### ISSUE THREAD

**Issue by vnea** [vakata/jstree#1813]
Hello,

I want to construct a different contextmenu for each node.
The entries of the contextmenu are retrieved with an AJAX call.

I currently do this:
```javascript
$("#mytree").jstree({
    ...
    plugins: [
        "contextmenu"
    ],
    contextmenu: {
        items: function (node) {
            var entries= {};

            // Make the AJAX call to get the entries
            $.ajax({
                url: "....",
                async: false, // VERY BAD
                data: node.id,
                success: function () {
                    // Construct the entries
                    ...
                }
            });

            return entries;
        }
    }
});
```
However I have to make a non-async call to wait the **entries** variable to be filled but non-async calls are deprecated.

Is there a solution ?

**Comment by vakata** [comment]
As stated in the docs - the second param the ```items``` function accepts (besides ```node```) is a callback function to invoke once the contextmenu is ready:
https://www.jstree.com/api/#/?q=items&f=$.jstree.defaults.contextmenu.items

**Comment by vnea** [comment]
I didn't see it, thank you very much it works !

If someone else is interested, here the solution in details:
```javascript
items: function (node, buildContextMenu) {
    var entries= {};

    $.ajax({
        url: "....",
        data: node.id,
        success: function () {
            // Construct the entries
            ...

            buildContextMenu(entries); // <--- SOLUTION
         }
    });
}
```
