### ISSUE TITLE
cant append child node ID same root node

### ISSUE THREAD

**Issue by x-ercise** [vakata/jstree#1815]
the jsTree always return **Uncaught RangeError: Maximum call stack size exceeded**
,i have bind data with JSON format.

var nodes = [
       { "id" : "ajson1", "parent" : "#", "text" : "root node" },
       { "id" : "ajson2", "parent" : "ajson1", "text" : "Child 1" },
       { "id" : "ajson3", "parent" : "ajson1", "text" : "Child 2" },
       **{ "id" : "ajson1", "parent" : "ajson3", "text" : "root node" }**
];

$('#using_json_2').jstree({ 'core' : {
    'data' : nodes
} });

as last node is child of "id : ajson3".
purpose, i need a last node to be child of **ajson3** and also use **id** and **text** like that

**Comment by vakata** [comment]
IDs MUST be unique - jstree WILL not work with duplicate IDs - if you can not guarantee unique IDs - let jstree assign the IDs.
