### ISSUE TITLE
Traverse Nodes

### ISSUE THREAD

**Issue by benjaminBinghamCGI** [vakata/jstree#1816]
[Someone found a nice way to traverse nodes](https://stackoverflow.com/a/44369074).  I like it however I think it should have a break like most "each" functions do.  So here's my update to it:

```javascript
each_node: function(callback) {
    if (callback) {
        var id, nodes = this._model.data;
        for (id in nodes) {
            if (nodes.hasOwnProperty(id) /*&& id !== $.jstree.root*/) {
                if (callback.call(this, nodes[id]) === false) {
                    break;
                }
            }
        }
    }
},
```

Can this be added to the next release please?

**Comment by vakata** [comment]
Thank you for the suggestion, but I'd rather focus on jstree v.4, which has a nice way to traverse and filter all nodes. I will publish a beta soon. 

If there is some delay in the beta I will add this, but for now I am reluctant to do so, as this means maintaining more features while phasing out v.3 - I hope you understand.

**Comment by benjaminBinghamCGI** [comment]
Sounds good.  jsTree is awesome!  Thank you very much.
