### ISSUE TITLE
showing the checkboxes without reloading the tree

### ISSUE THREAD

**Issue by vagharsh** [vakata/jstree#1817]
i don't know if i should post this here .. but i have a question. . is there a way to show and use the checkbox plugin without reloading the tree .. i want to use the checkbox for manual custom exporting feature.
thanks

**Comment by vakata** [comment]
You can create the tree with the checkboxes and only hide them using CSS (like ```#tree .jstree-checkbox { display:none; }``` and then show them on demand by using another rule (like ```#tree.exporting .jstree-checkbox { display:inline-block; }```

Enabling plugins will not work without a refresh, but maybe the above approach will work for you.
