### ISSUE TITLE
[issue/question] Disable Automatic scroll to selected node or the most recent hovered node.

### ISSUE THREAD

**Issue by jarey** [vakata/jstree#1818]
Hello,

I'm facing some behaviour on my jstree with scroll that i would like to alter (and to know if this is expected behaviour).

I found that when i apply scroll browsing the tree, if i click on the div, without selecting any element (on a blank space, without interacting with any node), the tree scrolls automatically following two behaviours, depending on the scenario:

1. The tree will scroll to the selected node if no other node has been hovered by the mouse.

1. The tree will scroll to the most recent hovered node if there has been one hovered by the mouse, even if it has not been selected and other node is.

Is this expected behaviour? If it's the case,  is there any way to disable this behaviour? I would like no automatic scroll when clicking on blank space, and no hove interference.

The use,case can be reproduced on the following jsfiddle: https://jsfiddle.net/t067rm8d/1/

Thanks in advance.

**Comment by jarey** [comment]
Found that the reason of the behaviour commented is the following code on the event **focus.jstree** (if that code in the event handler is commented, the scroll doesn't happen, that's what i want) :

https://github.com/vakata/jstree/blob/d7f39a264eba613cf550bd6693922c851e63636d/src/jstree.js#L847

Would you mind to encapsulate that code in a function, in order to be able to overwrite or make a plugin to modify this behaviour without changing jstree core code by my own? (if there's another way of changing it, and you don't mind to guide me to achive it, it would be awesome).

Thank you very much in advance.

**Comment by vakata** [comment]
Sorry for the long delay in getting back to you. This is done because of screen readers. I will add an option to disable this later today.
