### ISSUE TITLE
Documents and Api are so bad

### ISSUE THREAD

**Issue by delin-teng** [vakata/jstree#1820]
Documents and Api are so bad

**Comment by jarey** [comment]
@delin-teng Don't you think you should elaborate your point, and give details on what are you referring to?

Many people is using the jstree component withoot problem.

**Comment by vakata** [comment]
@jarey - thank you. @delin-teng - please provide more details. jstree is an open source project - feel free to contribute. The API docs are generated from the comments in the source code - you are more than welcome to improve them and make pull requests. The readme is also in this repo - if it is lacking in any way - please do make a pull request.
