### ISSUE TITLE
After dropping child node onto a new parent node - unable to open parent node

### ISSUE THREAD

**Issue by gracedigital** [vakata/jstree#1821]
We have a button that allows users to create/add a new folder to the tree.  Works great.
However when a user drags an existing child node from an existing folder to the new folder we are unable to open the new folder.  If we reload the page the existing nodes we dropped onto the new folder show up correctly.

There are no errors so we are wondering if you had any guidance on what might cause this type of behavior.

**Comment by vakata** [comment]
You probably have AJAX loading, and my guess would be that you are not setting the new node ID once the create operation completes. If this is not it I will need a demo of the issue so that I can help.

Best regards,
