### ISSUE TITLE
Creation of nodes with the same name

### ISSUE THREAD

**Issue by carlosips** [vakata/jstree#1822]
Exist a little bug when creates two nodes with the same name and after try to remove one of this: 
remove the two nodes with the same name (expected, but not desirable) and, the most important, remove parent node too.

Javascript console shows this message: 

`TypeError: p[f.children[k]] is undefined`

**Comment by vakata** [comment]
If by "same name" you mean "same ID" - this is not possible - jstree does not support duplicate IDs, as the whole point of an ID is to be unique.
