### ISSUE TITLE
Make browser crash with checkbox plugin and Ajax data from server.

### ISSUE THREAD

**Issue by MinimalistYing** [vakata/jstree#1823]
Thanks for your nice work with this plugin first~

I use jstree(newest version) with checkbox plugin in my project.And my jstree will lazy load data from server.But when I open one parentNode and the data send from server is something like below : 
```
{
  id          : "1" ,
  text        : "parentNode" ,// this is the node which i open now
  children    : [{
      id : "10",
      text: "sonnode0",
      children: true // this meas the sonnode0 can open, it still have some other son node
  },{
      id : "11",
      text: "sonnode1",
      children: true
  }] 
}
```
Then the browser will crash down, and i have to shut down the browser.

I find that the data format from server is wrong, the correct data which server should return was : 
```
// yes, no need  to return the parentNode.
[{
      id : "10",
      text: "sonnode0",
      children: true // this means the sonnode0 can open, it still have some other son node
  },{
      id : "11",
      text: "sonnode1",
      children: true
}] 
```
Then it works fine.
But without use checkbox plugin,both of the format can work, the browser will not crash,and the node can open normally(Although it has some problem when use the first format and call  `get_checked` method and other methods).

I think this is the same problem with  issue#1612.

I know that if I use correct data format, there will not have any problem.But although i use wrong format, the jstree can work fine(has correct UI ), there is no error message.I think this will be misunderstand sometime.

Maybe you can throw some error when the data format send by server was wrong or emphasize this point in the doc?So the people use wrong format will know as soon as possible.

**Comment by MinimalistYing** [comment]
I see your doc here https://github.com/vakata/jstree#populating-the-tree-using-ajax-and-lazy-loading-nodes. I think it shuould be emphasized that the second response is not the same with the first one!

**Comment by vakata** [comment]
The two responses are not different. You always return an array of child nodes.

**Comment by MinimalistYing** [comment]
@vakata I mean that the initial server response is different from the response to get child nodes.See here [Populating the tree using AJAX and lazy loading nodes](https://github.com/vakata/jstree#populating-the-tree-using-ajax-and-lazy-loading-nodes)

In jstree README.md, there has : 

The initial server response is:
```json
[{
  "id":1,"text":"Root node","children":[
    {"id":2,"text":"Child node 1","children":true},
    {"id":3,"text":"Child node 2"}
  ]
}]
```

The server response is:
```json
["Child node 3","Child node 4"]
```

Maybe some people will be confused about this two response.See below example:
When open Child node 1,if  the server response is: 
```json
[{
  "id":1,"text":"Child node 1","children":[
    {"id":3,"text":"Child node 3"},
    {"id":4,"text":"Child node 4"}
  ]
}]
```

This format is wrong, but jstree still can work, and will not through any error message.
