### ISSUE TITLE
How to set text length

### ISSUE THREAD

**Issue by praveenpatil27** [vakata/jstree#1825]
Hi,

How to set default length for Parent and child text in tree.
Ex: parent in tree has text "findnameforfunctioninprojectabcd"
how to set length of this text to some default length and it should display in tree like
"findnameforfunction
inprojectabcd"

Thanks,
Praveen

**Comment by vakata** [comment]
jsTree does not work with multiline text. Every node's title is single line - you can try to tweak the CSS but that is not recommended.
