### ISSUE TITLE
how to create a root by contextmenu?

### ISSUE THREAD

**Issue by yueraiyu** [vakata/jstree#1827]

**Comment by yueraiyu** [comment]
I want to create a node,the parent is "#".

**Comment by vakata** [comment]
The short answer is - you can't - it is not built in. But since ```vakata.contextmenu``` is completely separate from jstree you can actually bind to contextmenu clicks on the container, and show your own custom menu with an option to create a root node. Take a look at ```jstree.contextmenu.js``` - there you can see how to attach a contextmenu.
