### ISSUE TITLE
Changing config of a loaded tree

### ISSUE THREAD

**Issue by vdaruben** [vakata/jstree#1829]
Is is possible to change config of a loaded tree?
I am trying to make drag and drop enabled or disabled by clicking a button.

I made this possible now by passing a variable to my view with the value "" or "dnd"  witch is passed to the jstree config. But this way the page needs to be reloaded when the button is clicked, I would like to prevent my page being reloaded.

**Comment by vakata** [comment]
No, it is not possible - while some options are actually read at runtime (which make sit possible to change them at runtime), complex plugins like dnd have initialization code which needs to be run, so it is not possible to enable the plugin at runtime.

BUT, what you are trying to do is easily achievable using the ```is_draggable``` dnd option:
https://www.jstree.com/api/#/?q=dnd.is_&f=$.jstree.defaults.dnd.is_draggable

1) Setup the tree like you would when you want dnd enabled
2) Make sure the button toggles a boolean variable
3) Return that variable from the ```is_draggable``` config

Best regards,
Ivan
