### ISSUE TITLE
Question/Issue: types plugin and position configuration options

### ISSUE THREAD

**Issue by papakai** [vakata/jstree#1832]
Stumbled over this one as we were looking for a non-css solution for using custom icons based on css sprites: https://old.jstree.com/documentation/types
In the current documentation I wasn't able to find `position` documented, just `icon`. Isn't that any longer supported, if yes why not? Does that mean we are forced in direction of a css solution then instead of using the types plugin (which I really liked!).

**Comment by vakata** [comment]
You can either specify a path, or a className in the icon property. 
- If you need an image - set the `icon` property to the image path.
- If you need something more complex (such as a sprite) - define a class with the background properties (position, size, etc) and position setup and set the `icon` property to the class name. 

I see no point in adding numerous config options that directly correspond to CSS properties. 

If for some reason you do not want to write any CSS code you can still generate the class definition using JS and add it to the stylesheet list.

**Comment by papakai** [comment]
what means
>  you can still generate the class definition using JS
in detail - can you please provide an example for better understanding?

**Comment by vakata** [comment]
This is not jsTree related - jstree depends on a classname. 

Aside from using pure CSS, you are free to inject the related CSS in the document however you want - either by injecting a style tag, or modifying the document.styleSheets collection, or any other option you think of.
