### ISSUE TITLE
Jstree.com  broken

### ISSUE THREAD

**Issue by Stormrage74** [vakata/jstree#1833]
Hello, 
I dont know if this is the good place for this, so sorry if it is not.
Your website https://www.jstree.com is broke and we cannot navigate on it ( i tried to view the event list for example but i got a empty page).
I tried also with old version of site but i don't figure out where to find event list.

best regards

**Comment by vakata** [comment]
Thank you for letting me know - there was an issue with the server config - the hosting provider made some changes without letting me know early this morning. 
It should be up and running now.

Best regards,
Ivan
