### ISSUE TITLE
DND plugin move or copy if different tree

### ISSUE THREAD

**Issue by Rey777** [vakata/jstree#1834]
Hi,
First of all, nice work.
In my scenario I have 2 tree, the source one and the target one.
I would like to copy the node from the source to target but move the node from source to source tree.
So if I drag and drop a node outside the parent tree it should be a copy, if move inside of the same tree it should just move the node.
I don't want that the user must use the CTRL key, so to achieve this I tried to change the dnd options "always_copy" on rutime checking where the node is drop , but I couldn't make it works.
Any solution?

Thanks.

**Comment by vakata** [comment]
By design multi tree moves are actually always copy operations - the node is first copied to the new tree and then deleted in the original tree. You can prevent the delete operation by using ```check_callback```.

Quick & dirty sample code:
```
var preventDelete = false;
$('#tree1').jstree({
  core : { check_callback : function (operation) { if (preventDelete && operation=="delete_node") { preventDelete = false; return false; } return true; } },
  ...
$('#tree2').jstree({
  core : { check_callback : function (operation) { if (preventDelete && operation=="delete_node") { preventDelete = false; return false; } return true; } },
  ...
$('#tree1, #tree2').on('copy_node.jstree', function (e, data) {
  if (data.is_multi) {
    preventDelete = true;
  }
});
```

**Comment by Rey777** [comment]
Works like a charm.
Didn't know about "is_multi" attribute.

Thanks a lot.

**Comment by dhara-pyrumas** [comment]
Hi @vakata ,

I'm trying to use the same code, but getting following error:

> Uncaught ReferenceError: preventDelete is not defined

What should I do?

Thanks
