### ISSUE TITLE
 The jstree folding event does not work.

### ISSUE THREAD

**Issue by seongjihyeon** [vakata/jstree#1835]
Hello.

The jstree folding event(close) does not work.
I think this is a conflict with jquery svg library(ver 1.5.0).

I have to use the jquery.svg-1.5.0 library, 
is there any solution?

**Comment by vakata** [comment]
I can not help you without a detailed description of the error, or preferably a demo. jsTree keeps global scope modifications to a minimum, so I doubt there is something wrong with jstree's code. Still - what is the error in the console (is there one?) if not - can you provide a demo?

I am closing this until more information is available.
