### ISSUE TITLE
How to adapt this function to works with the new JStree

### ISSUE THREAD

**Issue by allipierre** [vakata/jstree#1837]
That Function worked fine in old Version of Jstree.  How to adapt this function to works with the new JStree

function init_tree_custome(){
  var lTreeConfig = {
    "plugins" : ["json_data", "search", "ui", "themeroller"],
    "core" : {
      "load_open": true,
      "initially_open": []
    },
    "ui" : {
      "initially_select": []
    },
    "json_data" : {
        "ajax" : {
            "type"           : 'GET',
            "url"            : "wwv_flow.show",
            "data": function(node){
                      return {
                        "p_request"      : "APPLICATION_PROCESS=GET_NODE_DATAA",
                        "p_flow_id"      : $v('pFlowId'),
                        "p_flow_step_id" : $v('pFlowStepId'),
                        "p_instance"     : $v('pInstance'),
                        "x01"            : $(node).attr("id") || 0,
                        "x02"            : "LOADA"
                        };
            },
            "success": function (new_data) {
                return new_data;
            }
        }
    },
    "search":{
      "ajax" : {
            "type"           : 'POST',
            "url"            : "wwv_flow.show",
            "data": function(searchvalue){
                      return {
                        "p_request"      : "APPLICATION_PROCESS=GET_NODE_DATAA",
                        "p_flow_id"      : $v('pFlowId'),
                        "p_flow_step_id" : $v('pFlowStepId'),
                        "p_instance"     : $v('pInstance'),
                        "x01"            : searchvalue,
                        "x02"            : "SEARCH"
                        };
            },
            "success": function (nodelist) {
                return nodelist;
            }
      }
    }
  };
 
  lTreeConfig.core.initially_open = ["1","2","5","6","39","43"];
  lTreeConfig.ui.initially_select = ["43"];
 
 $("#treecontainer")
   .bind("select_node.jstree", function(event, data){console.log(data);})
   .jstree(lTreeConfig);
}

**Comment by allipierre** [comment]
i write it like so

$('#container').jstree({
    'core' : {
      'data' : {
        "url" :  "wwv_flow.show",
        "data" : function (node) {
          return {
                        "p_request"      : "APPLICATION_PROCESS=GET_NODE_DATAA",
                        "p_flow_id"      : $v('pFlowId'),
                        "p_flow_step_id" : $v('pFlowStepId'),
                        "p_instance"     : $v('pInstance'),
                        "x01"            : '' || 0,
                        "x02"            : "LOADA"
                        
              };
                        
        }
          ,
            "success": function (data ) {
               return { "id" : data.id };
            }
      }
    }
  });


get the Data in that format

[{"data":{"title":"Form Modules(10)","attr":{"href":"#"},"icon":"form"},"attr":{"id":"1121145"},"state":"closed"},{"data":{"title":"PL/SQL Libraries(16)","attr":{"href":"#"},"icon":"pll"},"attr":{"id":"1121146"},"state":"closed"},{"data":{"title":"Menu Modules(2)","attr":{"href":"#"},"icon":"menu"},"attr":{"id":"1121147"},"state":"closed"},{"data":{"title":"Object Libraries(5)","attr":{"href":"#"},"icon":"olb"},"attr":{"id":"1121148"},"state":"closed"},{"data":{"title":"Report Modules(12)","attr":{"href":"#"},"icon":"onrptprop"},"attr":{"id":"1121149"},"state":"closed"},{"data":{"title":"APEX Applications(5)","attr":{"href":"#"},"icon":"apex"},"attr":{"id":"1121150"},"state":"closed"},{"data":{"title":"Database Objects(1701)","attr":{"href":"#"},"icon":"database"},"attr":{"id":"1121151"},"state":"closed"},{"data":{"title":"ASCII FILES(11)","attr":{"href":"#"},"icon":"ascii"},"attr":{"id":"1121163"},"state":"closed"}]

-- My Div

<div id="container">





But the Container is empty

**Comment by vakata** [comment]
The major jump from v.1 to v.3 means that you have to familiarize yourself with the new data format and config options - there are plenty of examples on the homepage of this repo. I am afraid I can not write this for you - but by just glancing at the data I can tell you that the data format is wrong and is not what jstree expects. You can read about the format here:
https://github.com/vakata/jstree#the-required-json-format
