### ISSUE TITLE
jstree files won't be displayed when there is apostrophes in filename

### ISSUE THREAD

**Issue by alexisgstalter** [vakata/jstree#1840]
Hello, I create an instance of jsTree with HTML lists (ul and li) it work perfectly except that there is an error when filename contains apostrophe (which is usual in french):

`node.childNodes[1].setAttribute(j, obj.a_attr[j]);` line 2455, the error is : InvalidCharacterError: String contains an invalid character

Is there a possibility to change jstree encoding or language to fix it ?

**Comment by vakata** [comment]
Can you provide a demo (jsfiddle?) of the issue, so that I have something to work with?

**Comment by vakata** [comment]
Closing this as there is no sufficient information for me to fix.
