### ISSUE TITLE
Add element HTML into list <li>

### ISSUE THREAD

**Issue by henrytran9x** [vakata/jstree#1841]
Hello ! I used **jstree** , Could you guide me how to add HTML into list tag "li" , I tried but when load Browser which generate format remove my custom HTML into tag "li". How to fix it !

Thank you !

**Comment by vakata** [comment]
jsTree is very sensitive to its markup requirements аnd will not work with random markup. However, if you nave an anchor tag inside the LI node you can put pretty much everything inside the anchor - jstree will not touch it.
