### ISSUE TITLE
Lazy load of children overwrites parent data object

### ISSUE THREAD

**Issue by paylord** [vakata/jstree#1842]
I am using my own function to lazy-load each node as it is expanded then sending the data to the tree with:

cb(data.children);

This bit is working fine.  Part of my data that is coming back includes counter data about the new child items that I want to store against the node (parent of the children).

After calling the callback function with the child data I set my counter data within the data object of the node:

node.data.counter = data.counter;

If I check the value of my node.data immediately after this I can see it is set correctly.  However, as soon as the function completes then the node.data loses the counter value.

I initially thought this might be a context issue but if I add a breakpoint in my browser and get the data from the tree through the console then I can see the counter value correctly set.  Again, as soon as I release the breakpoint the counter value disappears.

At the moment, I am guessing this is something to do with the callback function applying the child items to the node but not really certain.

Is there a better way for me to do this?

Thanks

Dave

**Comment by vakata** [comment]
Can you provide a demo of the issue? Also - before working on a demo - have you tried setting ```core.worker``` to ```false```? Please try that first.

**Comment by irowbin** [comment]
@vakata I am also having an issue with lazy loading. When I click to the parent, it got replaced by child response from the server.
I have  `JSON` response like this format as you mentioned in docs.
```javascript
// grand parent
[{"id":1,"text":"app 1","children":true},]

//  grand parent > children
[{"id":2,"text":"app child 1","children":true},]

//  grand prent > children > grand children 
[{"id":34,"text":"active","children":false},]
```

Please take a look;

![untitled](https://user-images.githubusercontent.com/13050078/32665057-3092515e-c65b-11e7-82bb-daad55933f7e.gif)

**Comment by irowbin** [comment]
@vakata  what does mean `core.worker`? That was not referenced in docs.

**Comment by vakata** [comment]
Here is the description of ```core.worker``` on jstree.com:
https://www.jstree.com/api/#/?q=core.wo&f=$.jstree.defaults.core.worker

I am closing this as I can not reproduce it, I will reopen if more info is available.

**Comment by paylord** [comment]
@vakata - sorry about that.  I was working with a client with some sensitivity and had trouble providing you with an example.  I eventually worked around the issue pushing the data I needed to preserve into a separate array.  Essentially the lazy load seems to be overwriting the data object of the parent.
