### ISSUE TITLE
Manually control the display of tree nodes?

### ISSUE THREAD

**Issue by a854363956** [vakata/jstree#1844]
When I need to add data, I can tap to expand, but I didn't add his sub data after I added the data, so what should I do if there is no expansion button? I want to use code to control tree show and hide
var data =[{"2"},{"3"}]
$("#NodeMenu").jstree({
	        "core" : {
	            "themes" : {
	                "responsive": false
	            }, 
	            // so that create works
	            "check_callback" : true,
	            'data': data
	        },
	        "types" : {
	            "default" : {
	                "icon" : "fa fa-folder icon-state-warning icon-lg"
	            },
	            "file" : {
	                "icon" : "fa fa-file icon-state-warning icon-lg"
	            }
	        },
	        "state" : { "key" : "demo2" },
	        "plugins" : [ "contextmenu", "dnd", "state", "types" ]
	    }); 
I wish I could expand his node, but no show expand  button , What attributes should I add to achieve this effect?

**Comment by vakata** [comment]
You can use ```show_node``` and ```hide_node``` - make sure all nodes are loaded and hide or show them as needed. You can also create and remove nodes at runtime using ```create_node``` and ```delete_node```, but keep in mind this is slower and not recommended for a large volume of nodes.
