### ISSUE TITLE
Not easy to change icons

### ISSUE THREAD

**Issue by leprinco** [vakata/jstree#1845]
I ddidn't want to write a full theme but I have tried to simply override the tree icons using 
```
<link rel="stylesheet" href="dist/themes/default/style.min.css" />
<style>
.jstree-default .jstree-node, .jstree-default .jstree-icon {
    background-image: url(myicon32px.png);
}
</style>
```
By doing so, the background icon fills the full div because it overrides : 
```
.jstree-default .jstree-last {
  background: transparent;
}
```
I have patched the default theme as bellow, but would it be possible to integrate a solution in the default theme ?
```
.jstree-default .jstree-last {
  background: transparent !important;
}
```

Thanks in advance

**Comment by vakata** [comment]
I try to limit the number of important clauses I use. Since you want to avoid building a whole theme (which I tried to make as easy as possible by using .less mixins), you can use the types plugin and only use the ```icon``` rule for the different node types (as well as the built-in ```default``` type).

**Comment by leprinco** [comment]
Hi, 
Thanks for your answer but if I am not mistaken, the Types plugin allows to change node icons when I wanted to change the rendering of the tree ([+], [-], |, ....). 
The !important clause I used was the simplest way to patch but there may be other solutions (that I have not looked after yet :) )
thanks again

**Comment by vakata** [comment]
Oh, I see - I missed that. No - sorry I will not be making such changes. I believe guessing what people will want and trying to accommodate that is not a good idea. After all - just make sure you place the !important rule in your own CSS (where you make the changes to the rendering and everything will be fine).

That being said - v.4 will have a much simpler HTML structure (hence simpler CSS) but that won't be out for at least a month or two.
