### ISSUE TITLE
JsTree + Ajax Lazy Load doesn't work

### ISSUE THREAD

**Issue by aaronr0207** [vakata/jstree#1846]
I'm following this [guide][1] to setup JsTree with lazy load using Ajax in my Laravel 5.5 app .

This is my controller: https://gist.github.com/aaronr0207/7fa0a38f40bfd2f728a15d655254f82d

My View:
https://gist.github.com/aaronr0207/f87720263e3d6026b04b00c08bae5cb2

My JsTree class is exactly the same I didn't make any change.

Actually I'm getting the following error on chrome's console:

> d9973d3e-1476-4453-a013-9e9c8430bcba:1 Uncaught TypeError: Cannot read property 'children' of undefined

[![enter image description here][2]][2]

But when I dump the response to debug it (at the end of TreeViewController data method):

            dd(response()->json($tree->build()));
It works...

[![enter image description here][3]][3]

My response looks like this (when I die-dump it):

[![enter image description here][4]][4]

Any idea? Thank you

**EDIT1**: If I return a simple `json_encode($tree->build)` there are no errors but it shows an empty tree... and the response looks like this:

[![enter image description here][5]][5]

**EDIT2**: got it! But now there are a new issue... All I did to solve it was change the url string with a callback:

     $('#jstree').jstree({
        'core': {
            'data': {
                'url': function (node) {
                    return '{!! route('tree.data') !!}' ;
                },
                'data': function (node) {
                    console.log(node);
                    return {'id': node.id};
                }
            }
        }
    });

But now when I fetch next level directories, if they have another directorie inside it fails without error:

[![enter image description here][6]][6]

Test1 content is the following:

[![enter image description here][7]][7]

If I delete test1/test2 folder, it works showing:

[![enter image description here][8]][8]

What is happening now? 

  [1]: http://mackhankins.com/blog/lazy-loading-with-jstree-and-laravel
  [2]: https://i.stack.imgur.com/BNdLe.png
  [3]: https://i.stack.imgur.com/Qo8z4.png
  [4]: https://i.stack.imgur.com/6RLOY.png
  [5]: https://i.stack.imgur.com/iqUPd.png
  [6]: https://i.stack.imgur.com/EUwSV.png
  [7]: https://i.stack.imgur.com/CZzy7.png
  [8]: https://i.stack.imgur.com/rSG50.png

**Comment by vakata** [comment]
This error means you have a missing parent in the data you feed to jstree - I believe in the latest version the error even states that. Check your data.
