### ISSUE TITLE
can load_nodes load an array of id:text map or whatever to append new nodes to a tree?

### ISSUE THREAD

**Issue by vetik32** [vakata/jstree#1848]
```
$jqueryEl.jstree(true)  // get jstree instace
.load_nodes(['a','b','c'], function(){  // here I'm struggled with what obj format is
   console.log(arguments);
});
```
could anyone point me to a example that can explicitly show how to call jstree to append 
new nodes. I've tried to pass an array os strings, objects{id, text}.
Out of variants, only one left - create_node; 
what I looking for is to append another json structure, array - format that is used to create a tree.
Than you.

**Comment by vakata** [comment]
Please read the docs - it seems what you need is ```create_node``` not ```load_node```
