### ISSUE TITLE
after_open.jstree is not working if it has only one node.

### ISSUE THREAD

**Issue by Neetesh1** [vakata/jstree#1849]
Hi Team,

I have observed that if js tree has only one node then it is not calling after_open.jstree method. 
Here are the fiddle example
https://jsfiddle.net/neeteshdev/xt02bcLn/ (in this case only one node hance it is **not working**)
https://jsfiddle.net/neeteshdev/jbg0gfww/	 (in this case it has multiple node  hance it is **working**)

**Comment by vakata** [comment]
Please read the docs more carefully - after_open fires after opening any single node - in the event of a single root node - there is NO node to open, so the event does not fire. If you had three root nodes each with one child - it would have fired three times. You probably want to listen for the ```open_all``` event if that is what you need.
