### ISSUE TITLE
Context Menu is giving null reference for the first time using lazy loading

### ISSUE THREAD

**Issue by atuldmathur** [vakata/jstree#1852]
When i am opening my context menu for the first time, the node gets triggered and do the calling of its children. This is lazy loading scenario. But the context menu is giving "null" value to $j.jstree.reference(data.reference)

Error : "Uncaught TypeError: Cannot read property 'get_node' of null"

Please give some suggestion.

**Comment by vakata** [comment]
Sorry, this is not a known issue - I can not help you without a demo - please provide a jsfiddle for example. And if you are using angular - this is most likely an issue with the angular wrapper.

**Comment by atuldmathur** [comment]
yes i am using angular for it. what do you mean by angular wrapper?

**Comment by vakata** [comment]
jstree does not provide an angular directive - you are most likely using ngJsTree or something of the sort, which I do not maintain. If that is not the case and you are using jstree as is (without ngJsTree or some other directive) - please provide a demo of the issue.

**Comment by atuldmathur** [comment]
we are using jstree as is, here is my code : 

var inst = $j.jstree.reference(data.reference);
console.log(inst);
var obj = inst.get_node(data.reference);

Here inst variable is getting null value, but data.reference is not null when i am consolling that. And this is actually happening for the very first time when i am opening context menu without expanding the node. Seems like lazy loading is happening after the instance of context menu is created. Is there any way we can delay this operation.

**Comment by akprasad19** [comment]
Hi,
Even i am facing the similar problem like this.

**Comment by vakata** [comment]
This error simply means that there is no available instance (among the parents of data.reference). As I already said - there is no way for me to help with this issue without having context - where does data.reference come from, etc. 
This is why I asked for a demo. I am closing this until a demo (or at least more context) is available.

**Comment by 19z** [comment]
i have a similar problem like this.

`data.reference` is a correct jQuery object. but `$.jstree.reference(data.reference)` might be return `null`.  when it happen,  Chrome dev tool cannot recognize `data.reference` into a dom

DEMO: 

https://jsbin.com/debiwocavo/edit?output

now i use this:
```
console.log(data);
var inst = $.jstree.reference(data.reference) || $.jstree.reference(data.reference.content),
obj = inst.get_node(data.reference);
console.log(obj);
```
