### ISSUE TITLE
Search Plugins node selected while it's invisible

### ISSUE THREAD

**Issue by casperazy** [vakata/jstree#1853]
Hi Ivan,

I just looking into this issue. Please refer to the link below:

[https://jsfiddle.net/casperazy/ze68uzy6/1/](url)

First, you select the "Child2",
Second, you search "3" and you select "Child3".
Lastly, you click on the Retrieve Button.

Console showing the  ["child2", "child3"] is selected. 

I think it should only appear on ["child3"] .

**Comment by vakata** [comment]
This is the normal behavior, you are only searching not deselecting anything. The Child 2 node is still selected.
