### ISSUE TITLE
How to display node.icon dynamically according to node.data

### ISSUE THREAD

**Issue by 2736629976** [vakata/jstree#1854]
i want a node shows different icons according to node.data。（node.date is defined by myself.），if node.data is true, the node show "fa fa-file-o" icon, else show "fa fa-file" icon.

```json
"types" : {
  "#" : {
    'icon' : node.data ? "fa fa-file-o" : "fa fa-file",
    "valid_children" : [ "1" ]
  }
}
```

but i don't know how to get node.data from "types" correcty. And `'icon' : node.data ? "fa fa-file-o" : "fa fa-file"` is wrong, node.data is guess by myself.

@vakata @elia @StephanHoyer @irfanevrens @ehsan

**Comment by vakata** [comment]
You are not approaching this right. The types plugin can not have conditionals that are evaluated at runtime for each node. You can pass the icon along with your data, or pass a type along with the data - it is your choice - you can see a demo on jstree.com and the homepage of this repo.

**Comment by 2736629976** [comment]
thanks, i can understand your answer.
