### ISSUE TITLE
Setting jstree.defaults.checkbox.whole_node to false not working

### ISSUE THREAD

**Issue by asuraphel** [vakata/jstree#1857]
I tried setting the option `jstree.defaults.checkbox.whole_node` to `false` but it only disables click events on the whole node only when the node is already checked. 

Please view [this fiddle](http://jsfiddle.net/2kwkh2uL/4553/).

**Comment by vakata** [comment]
Keep in mine disabling whole node makes little sense while tie_selection is still on. It all depends on what you are trying to do. Give me some details and I will reopen and try to help.
