### ISSUE TITLE
open_all / close_all Event

### ISSUE THREAD

**Issue by alchala** [vakata/jstree#1858]
I've a large tree around 10,000 nodes, and also have a button call open_all and another call close_all 
$(TreeObject).jstree("open_all");
$(TreeObject).jstree("close_all");

the issue is, I need to display loading message for the user right after the user click expand all button because it takes almost 5 to 7 seconds to open all nodes, in other words I want to achieve the following:
1- User click expand.
2- Loading message appears.
... (jsTree opening all nodes process)
3- Hide loading message after all nodes displayed.

**before_open** and **after_open** events did not help, because **after_open** will fire immediately after the node open regardless there are still other nodes in opening process.

**loaded** and **ready** events did not help as well, as they fire after building the tree for the first time only.

I'm looking for something **before_open_all** and **after_open_all**

Thank you in advance for any hint to solve the issue

**Comment by vakata** [comment]
Display the message just before you call ```open_all```, I do not get the need for an event.

**Comment by DomiDenie** [comment]
Hi, I implemented the same sollution you mentioned above but it seems that the 'open_all' event is already called when all the children of a certain node are loaded and not just when all nodes are done loading ( which is actually what I need )
