### ISSUE TITLE
Replace tree images by font

### ISSUE THREAD

**Issue by bahmansh** [vakata/jstree#1859]
Hi
I dont wanna use images in tree style.
instead i need to display font icons. so dont need to use url in stylesheet.
![image](https://user-images.githubusercontent.com/19801131/31947035-f363d7ee-b8c2-11e7-8634-f99872acf8e8.png)

**Comment by vakata** [comment]
As seen on the jstree homepage the node icons are easy to replace and font icons are supported. As for the open/close icons - feel free to create your own theme - the provided themes work with the provided images.
