### ISSUE TITLE
Show context menu from a button inline with node

### ISSUE THREAD

**Issue by l0v3w4v3** [vakata/jstree#1861]
How can I display context menu by a click on a button at the end of each node?
For example:
![capture](https://user-images.githubusercontent.com/6983104/32042818-153aa59a-ba63-11e7-918a-36aad5a998f5.JPG)

**Comment by vakata** [comment]
You will have to create a plugin for this, so that you can append the menu and trigger events. I believe a similar plugin was already created on the groups page. Anyway - here is a small demo to get you going:
https://github.com/vakata/jstree/blob/master/src/misc.js#L148
