### ISSUE TITLE
Query for upgrading move_node.jstree from v1 to v3

### ISSUE THREAD

**Issue by parthbhagat** [vakata/jstree#1865]
First of all, thanks for such a nice plugin.

This is not actually an issue, but query for help on how to upgrade for particular task with jstree.

I am trying to upgrade jstree plugin for existing project. Earlier project was using 1.0-rc3, then I've upgraded jquery version to latest version from 1.11 to 3.x and so decided to upgrade jstree version to latest one, at this moment it is 3.3.4.

A functionality I am looking is that there are two root nodes in single jstree. One root node is a source node and another is target node. I am using "dnd" plugin to use drag and drop functionality. From source root node, drag a child node and drop it to target root node or to any of its children. The final result should be node from source root node should be there only and target root node will initiate an ajax request which will eventually persist node detail to database and then render the entire tree again with new node included under target root node. So basically it is Copy operation in the same jstree, but is performed using drag and drop move operation.

With 1.x, this functionality was performed with below code snippet:

```
$(<selector>).jstree({ ... <data and plugin related information> ... }
).bind("move_node.jstree", function (event, data) {
	//delete newly inserted node
        // Find children nodes of target node and iterate over it
	data.inst._get_children(data.rslt.np).each(function () {
                // If child node is of type "CONTENT" then delete that node from target root node
		if ("CONTENT" == $(this).attr("dataType")) {
			data.inst.delete_node(this);
		}
	});
        // Is jstree editable or not (boolean flag)
	if (treeEditable) {
        // Initiate ajax request to open form which captures detail for new node.
		dropContent(data.rslt.r.attr("dataID"), data.rslt.r.attr("dataType"), data.rslt.o.attr("dataID"));
	}
});
```

I couldn't find mapping of data maps from older version to new one.

Can anyone suggest how to upgrade this code snippet to latest version of jstree?

**Comment by vakata** [comment]
jsTree v.1 has not been supported for years. From what I gather you might find this option useful:
https://www.jstree.com/api/#/?q=dnd.always&f=$.jstree.defaults.dnd.always_copy

As for data attached to a node you can access it (inside the handler) using ```data.instance.get_node("node_id").data```, or if you want the moved/copied node - ```data.node.data```

Let me know if I can help any further.

**Comment by parthbhagat** [comment]
**dnd.always_copy** did works. It now triggers **copy_node.jstree** event instead of **move_node.jstree**.
https://www.jstree.com/api/#/?f=copy_node.jstree

One more thing I am expecting for  mogration. Can we get children for any node? I see there is a function for **get_children_dom()**, which returns DOM LI elements for the node. Instead is there any helper function available which returns jstree object for children elements? Earlier with 1.x it was supported using **_get_children()** function.

**Comment by parthbhagat** [comment]
Any input on this is greatly appreciated @vakata 

Thanks
