### ISSUE TITLE
restore checkboxes with collapsed nodes

### ISSUE THREAD

**Issue by maxwilms** [vakata/jstree#1867]
Hi,

I'm using the state and checkbox plugin with lazy loading. This works fine so far. The state is restored on page refresh. 
But if I check a lazy loaded node, close the parent folder and refresh the page the node is not checked anymore.

Fiddle: https://jsfiddle.net/emuwx5h4/

Obviously jsTree doesn't know the checked node on page restore and just drops it. I wonder if there is any callback available to tell jsTree how to resolve this node?

**Comment by vakata** [comment]
I am afraid this is not possible - jstree will first restore opened nodes, and then reselect nodes, but only if they are loaded. Unfortunately there is no way to select nodes that are not currently visible - that would men always loading the whole tree.

Btw - you can modify the state object before it is applied, so theoretically you could include the nodes that need to be loaded ... and the close them, but it might be a bit cumbersome. I will consider adding a loaded key to the state object and options, which would reload all loaded nodes - how does that sound?

**Comment by maxwilms** [comment]
Hello,

yes, I think a loaded key attribute should solve the problem. Simple and elegant solution. I like it.

Meanwhile I implemented a workaround. Just force the parent nodes to open by altering the state object (thank you for the advice): https://jsfiddle.net/ck4pts50/ (sadly it requires the full tree to be present, or extra API calls).

**Comment by vakata** [comment]
In order to use the new functionality you will need to enable the two new options in your config (I had to add the new options in order to keep backwards compatibility):
```js
...
		state : { preserve_loaded : true },
		core : {
			loaded_state : true,
...
```

**Comment by maxwilms** [comment]
This works like a charm. Thank You!
