### ISSUE TITLE
How to locate the search results？

### ISSUE THREAD

**Issue by maoyue0917** [vakata/jstree#1868]
A large data set, close to twenty thousand data items，and the height of the tree diagram is far larger than the browser window's visible range. In order to find the search results( used search plugins), we must to drag the scroll bar, so the user experience is very poor.Is there a function similar to "ctrl+F" which could make query and auto location? or  add anchor link to make page rolling? ps: "show_only_matches" can not meet our demand.

**Comment by a854363956** [comment]
You can consider the search function, and then reload the tree node, hide the node is not used, I think this is a good solution

**Comment by vakata** [comment]
There is a class that you can use - ```jstree-search``` I believe - using that class you can easily implement "jump to" functionality or add some visual indication in your CSS.

**Comment by maoyue0917** [comment]
Thanks for your guidance @vakata . Now that the problem is solved.
var searchResult = $("#container").jstree('search', $("#q").val());
$(searchResult).find('.jstree-search').focus();
