### ISSUE TITLE
Refresh node not working

### ISSUE THREAD

**Issue by diego22296** [vakata/jstree#1871]
Hi,

I'm trying to refresh a certain node of a tree that uses the sort plugin. I want to refresh the node when the data changes so that the tree remains ordered. 

I could use the `tree.jstree(true).refresh();` but it refreshes the whole tree and, as the trees I'm working with have over 2000 nodes and their information is changing constantly, it would be annoying for the user to see the tree reloading each time.

I tried using the `refresh_node` function, but the children nodes of the one that I am reloading freeze.

Please see the fiddle with the error here: http://jsbin.com/cokaxekome/1/edit?html,js,output

Thanks! Let me know if you need more information.

**Comment by vakata** [comment]
The data source you are using does not allow to refresh a specific node - use the callback or AJAX options for that. I am afraid the demo is flawed. Once you start using a callback or the AJAX option you will be able to refresh the children of a given node.
