### ISSUE TITLE
Allow move only selected leafs

### ISSUE THREAD

**Issue by otavio515** [vakata/jstree#1872]
Hello, here is my problem:

> When I select all leaves, the parent node get selected too, how can I disable this?

It was solved using:

`"checkbox": {
                    	"three_state" : false
                    },`

Is there any way to when I select the parent node, select all leaves except the parent?

Thanks.

**Comment by vakata** [comment]
There is a is_draggable callback in the dnd config - it does exactly what you need:
https://www.jstree.com/api/#/?q=dnd.is_&f=$.jstree.defaults.dnd.is_draggable

If you want to prevent moves not initiated using drag'n'drop use the check_callback:
https://www.jstree.com/api/#/?q=check_call&f=$.jstree.defaults.core.check_callback
