### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hibbault** [vakata/jstree#1876]
when i click on a parent node without opening it first i get the following error. after opening the parent node it works without any problems.

vendor.js:4472 Uncaught RangeError: Maximum call stack size exceeded
    at Object.trigger (vendor.js:4472)
    at jQuery.fn.init.triggerHandler (vendor.js:5029)
    at $.jstree.plugins.wholerow.trigger (jstree.js:884)
    at $.jstree.plugins.wholerow.deselect_all (jstree.js:3285)
    at HTMLDivElement.<anonymous> (common.js:1338)
    at HTMLDivElement.dispatch (vendor.js:4557)
    at HTMLDivElement.elemData.handle (vendor.js:4243)
    at Object.trigger (vendor.js:4472)
    at jQuery.fn.init.triggerHandler (vendor.js:5029)
    at $.jstree.plugins.wholerow.trigger (jstree.js:884)

My code is like below;
 ```javascript
function createLocationTree(targetDiv) {
        var isSingleSelect = targetDiv.data('single-select');
        targetDiv.jstree({
            "core": {
                "themes": {
                    "icons": false
                }
            },
            "search": {
                "case_insensitive": true,
                "show_only_matches": true
            },
            "plugins": ["checkbox", "search", "wholerow"]
        }).on("changed.jstree",
            function (e, d) {
                var bottom = targetDiv.jstree().get_bottom_selected(true);
                if (isSingleSelect && bottom.length > 1) {
                    targetDiv.jstree().deselect_all();  //i get the common.js error on that line
                    var children = targetDiv.jstree("get_children_dom", d.node);
                    if (children.length === 0) {
                        targetDiv.jstree().select_node(d.node);
                    } else {
                        var singleSelectErrorTitle = targetDiv.data('single-select-error-title');
                        var singleSelectErrorMessage = targetDiv.data('single-select-error-message');
                        var alertType = targetDiv.data('alert-type');
                        swal(singleSelectErrorTitle, singleSelectErrorMessage, alertType);
                    }
                    return;
                }
                var selectedIds= [];
                $(bottom).each(function(index, item) { selectedIds.push(item.data.locationId) });
                if (selectedIds.length)
                $('#' + targetDiv.data('selected-locations-elem')).val(selectedIds.join(','));
                var checkedArr = d.instance.get_checked(true);
                var labelArr = [];
                for (var i = 0; i < checkedArr.length; i++) {
                    labelArr.push(checkedArr[i].text);
                }
                $('#' + targetDiv.data('label-elem')).text(labelArr.join(','));
            });
        var to = false;
        $('#' + targetDiv.data('search-box-elem')).keyup(function () {
            if (to) {
                clearTimeout(to);
            }
            to = setTimeout(function () {
                var v = $('#' + targetDiv.data('search-box-elem')).val();
                targetDiv.jstree(true).search(v);
            },
                250);
        });
    }
```   

i am using html data with jstree version 3.3.4

**Comment by vakata** [comment]
That is normal - you are calling ```deselect_all```, which in turn triggers the ```changed.jstree``` event, which calls ```deselect_all``` and so on and so forth.

You have to refactor your code so that it does not cause a an endless loop - try invoking ```deselect_all``` with ```true``` as the first param - that should suppress the ```changed``` event:
https://www.jstree.com/api/#/?q=deselect_all&f=deselect_all([supress_event])

**Comment by hibbault** [comment]
ok i used the parameter but i still have the same problem. if i open the node and select the parent i get notification, otherwise i dont. you can see it here:
[https://jsfiddle.net/h4sq2vdr/](https://jsfiddle.net/h4sq2vdr/)

**Comment by hibbault** [comment]
hello ivan, i think i found the problem, thanks for your help.
