### ISSUE TITLE
checkbox initial state from html data

### ISSUE THREAD

**Issue by LaySoft** [vakata/jstree#1878]
I'm using checkbox plugin, and i need to set the initial states of checkboxes from html data. I tried add data-jstree='{"selected":true}' attributes to the li elements, and the checkboxes appears in the checked state, but they opened too, and this is not need for me. I tried data-jstree='{"opened":false,"selected":true}', but the node remains opened.

How can i make to checkboxes in checked state (from html data), but the nodes are not opened?

**Comment by vakata** [comment]
Use this option: https://www.jstree.com/api/#/?q=expand&f=$.jstree.defaults.core.expand_selected_onload
