### ISSUE TITLE
Node reopening doesn't call ajax.

### ISSUE THREAD

**Issue by otavio515** [vakata/jstree#1879]
Hello Vakata!

I'll explain my issue with those screenshots

I've added a video to explain better.

## 1 - **Initial state (Level 0)**

![first](https://user-images.githubusercontent.com/11263232/32666993-7a9f2802-c620-11e7-8163-b98defdeb1bf.png)

## 2 - **Opened Level 1**

![second](https://user-images.githubusercontent.com/11263232/32667013-873e939a-c620-11e7-84d7-ee37d65259be.png)

## 3 - **Opened Level 2**

![third](https://user-images.githubusercontent.com/11263232/32667017-87c55ae2-c620-11e7-8fe6-495b3fb96eac.png)

## 4 - **Opened Level 3**
  - All leaves are showing.

![fourth](https://user-images.githubusercontent.com/11263232/32667012-871e8ed8-c620-11e7-8b5a-df1eddea58d7.png)

## 5 - **Minimized all levels when I clicked on Root Level (Level 1)**
  - As you can see, it do not get all minimized, looks that a second click is triggered and it starts to reopen

![fifth](https://user-images.githubusercontent.com/11263232/32667010-86c409a4-c620-11e7-9f66-9e0f9798ad9f.png)

## 6 - **This is while it is reopening, just to situate you**

![fifthsecond](https://user-images.githubusercontent.com/11263232/32667011-8700f576-c620-11e7-85a8-b229e72c479a.png)

## 7 - **Fully reopened afeter the 'fake' second click triggered by itself**

![fourth](https://user-images.githubusercontent.com/11263232/32667012-871e8ed8-c620-11e7-8b5a-df1eddea58d7.png)

## 8 - **Finally it comes to the first state after I click again to minimize (everything closed)**

![sixth](https://user-images.githubusercontent.com/11263232/32667016-87a6a836-c620-11e7-9205-fcf372f01fbd.png)

## 9 - **When I click again to reopen the node, it reloads only the children that I've opened on step 4.**

![seventh](https://user-images.githubusercontent.com/11263232/32667015-87831682-c620-11e7-9466-1aa36bbcbf0f.png)

Between steps 5 and 6 it happens so fast, like in an eye blink.

If for a reason I minimize the root level and after I want to access another children inside Level 1 or 2, I can't because this issue is not allowing me to reload the children content when I click on the root level, what is supposed to do I think, once it is loading with ajax.

Not sure if it helps, but this is what I'm using.

`Code below`
https://pastebin.com/bZ4bzA9R

There is a vídeo to help a little bit more:

https://vimeo.com/242556615

`Checkboxes are hidden with:`
 `      .jstree li.jstree-open > a.jstree-anchor > i.jstree-checkbox,`
`	.jstree li.jstree-closed > a.jstree-anchor > i.jstree-checkbox,`
`	.jstree li.jstree-node > a.jstree-anchor > i.jstree-checkbox { display:none; }`

Since now, I appreciate your help.

Best regards.

**Comment by vakata** [comment]
Hi,

I am afraid I can not help you without a full demo. To be honest - I can not think of a scenario where jstree will do that. Are you using the latest version? Have you added any custom code? Check your data for duplicate IDs.

This is all I can think of, please provide a demo and I will reopen.
