### ISSUE TITLE
Cannot create property 'children' on boolean 'false'

### ISSUE THREAD

**Issue by dcbrewster** [vakata/jstree#1883]
Using jstree for the first time and getting the following exception. I have no idea how to get around the problem or what it is I'm doing wrong.

Uncaught TypeError: Cannot create property 'children' on boolean 'false'
    at $.jstree.plugins.wholerow._append_html_data (jstree.js:1470)
    at $.jstree.plugins.wholerow.<anonymous> (jstree.js:1401)
    at Object.proxy (jquery-1.10.2.js:841)
    at fire (jquery-1.10.2.js:3062)
    at Object.fireWith [as resolveWith] (jquery-1.10.2.js:3174)
    at done (jquery-1.10.2.js:8249)
    at XMLHttpRequest.callback (jquery-1.10.2.js:8792)

The problem line is dom.children = [] and a good chance the following line will also create an exception..
jstree Code:
	_append_html_data : function (dom, data, cb) {
			dom = this.get_node(dom);
			**dom.children = [];**
			dom.children_d = [];
			var dat = data.is('ul') ? data.children() : data,

Any suggestion?

Dave

**Comment by vakata** [comment]
Please share your config and initial data. From what I gather you are trying to create a jstree from an already existing markup, my guess would be that the markup you have in the jstree DIV is not what jstree expects. I will be able to help further when you share the markup (or at least part of the markup if it is huge) and the jstree config you are using.

**Comment by dcbrewster** [comment]
Below is a sample of the code I am using. The defined controller does return the json string outlined below.

Thanks. Dave
============================================
@{
    ViewBag.Title = "Tree";
}
<link href="~/Scripts/jstree/dist/themes/default/jstree_style.css" rel="stylesheet" />
<div class="container">
    <h2>Resource Library</h2>
    <p>Lorem ipsum dolor sit amet, hendrerit tellus, tortor a erat, bibendum nunc scelerisque adipiscing vivamus. Laoreet lectus duis vitae at wisi, vestibulum auctor ante, nunc leo, imperdiet velit sit ornare nec. Sapien libero in vehicula placerat molestie, phasellus aenean facere venenatis, molestie eu nunc mauris platea amet. Non lacus sagittis adipiscing consectetuer accumsan ultricies.</p>
    <div class="row" style="text-align:left;">
        <input id="treeSearch" class="input" style="margin:0em auto 1em auto; display:block; padding:4px; border-radius:4px; border:1px solid silver;" type="text">
    </div>
    <div id="tree" class="col-xs-5">
        Tree Goes Here
    </div>
    <div id="documents" class="col-xs-5">
        Documents Go Here
    </div>
    <div id="keywords" class="col-xs-2">
        Keywords Go Here
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jstree/dist/jstree.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#tree').jstree({
                core: {
                    animation: 200,     
                    multiple: false,                        // Cannot select multiple nodes
                    check_callback: true,
                    themes: {
                        stripes: true,
                        dots: true,
                        icons: true
                    },
                    strings: { 'Loading ...': 'Please wait ...' },
                    state: { 'key': 'resourceLibrary' },              // Save state for next time - need state plugin
                    data: {
                        url: '/Resource/GetFolder/',
                        data: function (node) {
                            if (node.id === "#") node.id = 1;
                            return { 'id': node.id };
                        }
                    },
                    error: function (data, e) {
                        alert('fuckup:' + data.status + ' - ' + e);
                    }
                },
                // Set how group types are displayed
                types: {
                    '#': {
                        max_children: 1,
                        max_depth: 4,
                        valid_children: ['root']
                    },
                    root: {
                        //icon: '/static/3.3.4/assets/images/tree_icon.png',
                        valid_children: ['default']
                    },
                    default: {
                        valid_children: ['default', 'file']
                    },
                    file: {
                        icon: "glyphicon glyphicon-file",
                        valid_children: []
                    }
                },
                plugins: ['contextmenu', 'dnd', 'search', 'state', 'types', 'wholerow']
            });

            // Search
            //var treeSearch = $('#treeSearch');
            var to = false;

            $('#treeSearch').keyup(function () {
                if (to) clearTimeout(to);

                to = setTimeout(function () {
                    var v = $('#treeSearch').val();
                    $('#tree').jstree(true).search(v);
                }, 250);
            });
            // End Search
        });
    </script>
}

**Comment by vakata** [comment]
I am pretty sure your JSON response does not have a Content-Type header indicating that the result is indeed JSON (that is why the error comes from a function responsible for working with HTML data, not JSON). If you can not set a header - use the ```core.data``` config option (which is standard jQuery AJAX config) to instruct jQuery to handle your data as JSON.

You also need to follow the required jstree data format - jstree will have no idea what to do with the "branches" key in your object. The format is well documented both in this repo and on www.jstree.com 
You can always do some custom manual mapping if you can't change the data format - if that is the case - check out the "Using a callback function" part of the data docs.

I also noticed you are setting ```node.id``` to 1 if it is ```"#"``` - do not that, especially since you actually have a node with an ID of 1 (as seen in the sample data).
