### ISSUE TITLE
Is it possible to use jstree in angular 4?

### ISSUE THREAD

**Issue by Bushira23** [vakata/jstree#1884]
Good day,

I am porting a project from angularjs to angular 4. I need to use jstree in angular 4. Is this possible? If yes, is there a guideline for me to follow?

Kind Regards,
Rachidi

**Comment by alanhg** [comment]
Yes,I will show you code.

1. index.html
You can use CDN
```html
    <script src="http://cdn.staticfile.org/jquery/1.12.4/jquery.min.js" type="text/javascript"></script>

    <script src="https://cdn.bootcss.com/jstree/3.3.4/jstree.min.js"></script>
    <link href="https://cdn.bootcss.com/jstree/3.3.4/themes/default/style.min.css" rel="stylesheet">
```

**Comment by Bushira23** [comment]
Hi @alanhg,

Thank you for your feedback. Since I am using webpack to bundle my javascript and typescript files, I have added jstree to webpack config. The project I am porting uses jsTree together with ngJsTree. I have added both. However, I seeing the following error during runtime:
_**Uncaught TypeError: Cannot read property 'defaults' of undefined
    at ngJsTree.js:3
    at Object.945 (ngJsTree.js:25)
    at __webpack_require__ (bootstrap b1526ed…:54)
    at webpackJsonpCallback (bootstrap b1526ed…:25)
    at angularJsTree.bundle.js:1**_

Any idea what I am missing here?
Thanking you in advanced.
Kind Regards,
Rachidi

**Comment by vakata** [comment]
I am closing this, but feel free to continue the discussion. I am closing the issue as there is no problem with jstree itself and I do not provide the angular wrapper and can't help with it.

**Comment by cassianomon** [comment]
@alanhg Your example is not working properly, could you provide a Plunkr please?

**Comment by Dhamu143** [comment]
any update that ? now i am also planning to use jstree with angular 5 . anyone has used then please help me.
