### ISSUE TITLE
node number, undefined

### ISSUE THREAD

**Issue by GlauberF** [vakata/jstree#1885]
**node number, undefined**

I need to render from a list where it can have multiple node, one inside the other.
I can not know the exact node number, because the client can create multiple nodes.
How to make this automatic, regardless of how many knots, my list process and show the automatic tree

**Comment by vakata** [comment]
I am not sure I get the question, but if you need auto-numbering of nodes add this plugin to your page (and enable it in your config):
https://github.com/vakata/jstree/blob/master/src/misc.js#L182

**Comment by GlauberF** [comment]
Ok, how would you put it together using this plugin?
And what should be the structure of my json?
