### ISSUE TITLE
a.toLowerCase is not a function

### ISSUE THREAD

**Issue by joaoinw** [vakata/jstree#1886]
My search doesn't work. Its shown this erro in console **a.toLowerCase is not a function**

Thie is the search code in the page

	$('#filtrar_tree').keyup(function () {
		
		if(to) { clearTimeout(to); }
		
		to = setTimeout(function () {

			var v = $('#filtrar_tree').val();
			tree.jstree(true).search(v);
		
		}, 250);
	});

An another page with the same code work perfectaly

**Comment by vakata** [comment]
Please provide a demo (jsfiddle for example) or at least - more information:
- which version are you using
- where is the error - which file, which line
- how do you create the tree - what is your data source, maybe provide a sample

I will reopen on more information.
