### ISSUE TITLE
Search on a table (related to 3rd party plugin, just want to mention here)

### ISSUE THREAD

**Issue by cassianomon** [vakata/jstree#1887]
I am in need of a crossover between search and table plugins,

Here is the issue I made on the table plugin repository:

https://github.com/adamjimenez/jstree-table/issues/23

**Comment by vakata** [comment]
Using the search_callback option this should be pretty easy to implement:
https://www.jstree.com/api/#/?q=search_call&f=$.jstree.defaults.search.search_callback

You get the whole node in the callback, so you have the full node data (including columns) as well as full control over what is considered a match.

**Comment by cassianomon** [comment]
Thank you @vakata, gonna try that tomorrow

**Comment by cassianomon** [comment]
Worked, thank you @vakata
