### ISSUE TITLE
HTML Checkbox instead of anchor

### ISSUE THREAD

**Issue by atomicpages** [vakata/jstree#1888]
Hi there,

Curious to see if it's possible to use a regular old HTML checkbox instead of the anchor element with the checkbox plugin. I did some searching and saw no question regarding this. I did some poking around the checkbox plugin source and I didn't see this as an option (hidden or otherwise).

**Comment by vakata** [comment]
Hi,

Here is a sample plugin that does just that, but keep in mind the change is visual only. You can not use the submitted values, as jstree does not keep all nodes in the DOM:
https://github.com/vakata/jstree/blob/master/src/misc.js#L66

**Comment by atomicpages** [comment]
For anyone passing by you need to include `checkbox` before `realcheckboxes`:

```js
$('#tree').jstree({
     plugins: [
          'checkbox',
          'realcheckboxes'
     ]
});
```
