### ISSUE TITLE
Whether or not there was an API that I can get all nodes by

### ISSUE THREAD

**Issue by yanyumiao** [vakata/jstree#1889]
Whether or not there is an API that I can get all nodes by

**Comment by vakata** [comment]
You can use get_json:
https://www.jstree.com/api/#/?q=get_json&f=get_json([obj,%20options])

The result is a serialized tree, but if you need the actual node object invoke ```get_json``` with the ```flat``` option, then loop over the collection and call ```get_node``` to get each node instance by ID.

**Comment by yanyumiao** [comment]
what the api return was a tree but not an array, array is better for me, thanks

**Comment by vakata** [comment]
Use the ```flat``` option - that will return an array of nodes.
