### ISSUE TITLE
JsTree 2nd level child not able to select on load

### ISSUE THREAD

**Issue by Raju-N** [vakata/jstree#1891]
Hi, I am taking selected nodes and storing in session storage. on page refresh I am selecting previously selected nodes using "select_node" and passing either selected objects or id, the node is not selected if the parent has more than one child node (i.e for level 2 child ) but getting selected if the parent has only one child node. I tried in timeout but not worked. when I execute $('tree').jstree("select_node", selectedNodes); after sometime in browser the node is getting selected. please help me to solve this issue. For your information I am loading 100 data for the tree.

**Comment by vakata** [comment]
Activate the ```state``` plugin in your instance - there is more info in the docs - it does exactly what you need. 
Adding ```"state"``` to your plugins array should be enough.

**Comment by Raju-N** [comment]
Thanks for that suggestion. for page refresh scenario it works but I have one more scenario. I have an option to search. On clicking search button I am calling jstree("refresh") and data are dynamically retrieved in $.jstree.defaults.core.data where I have mentioned url, type and returned data to $.jstree.defaults.core.data on success. In this scenario "state" plugin completely failed to retain state so  I felt storing selected data in session and making the node to select by using jstree("select_node") in 'refresh.jstree' callback function but it failed to select 2nd level node. Please help me to solve this issue.

**Comment by vakata** [comment]
Look at what the state plugin does so that you can implement this. My guess would be that you should call ```get_state``` and ```set_state``` instead of only storing the selected values. The idea is that you need to restore opened nodes before selecting any children (if you have a tree where nodes are loaded on demand). The *_state functions mentioned above should do the trick for you.

**Comment by Raju-N** [comment]
Thank again for the solution. Let me check whether it works in my scenarios.
