### ISSUE TITLE
Setting state in JSON object to "disabled" breaks the "is_disabled()"

### ISSUE THREAD

**Issue by TomReddish-MVC** [vakata/jstree#1894]
Running jstree 3.3.4 

I am setting the state for some of my nodes to disabled in the JSON data. I am listening to some events like "after_open" and when I ask if the node is disabled it is returning false every time. I have the checkbox plugin loaded and when I disable the nodes in JSON I am also disabling the checkbox in JSON.

On "after_open" it should check if this node is disabled and then go and disable it's children nodes if it is. For trees where I am not disabling checkbox or the node in JSON this works fine. Any ides?

```


.on("after_open.jstree", function(e, data)
{
    // this returns false everytime
    const disabled = $(e.currentTarget).jstree(true).is_disabled();
    ...
})
```

**Comment by vakata** [comment]
Please read the API more carefully - you need to pass an argument to the ```is_disabled``` call, which is the node you want to check - in your case that would be ```data.node```

**Comment by TomReddish-MVC** [comment]
Ahhh! I was including it in the other parts and knew I needed to use the node just a slip up sorry about that. 

Shouldn't that function throw an exception if no node is passed instead of returning an actual value?

Tom Reddish 
Software Engineer
MediaVue Systems
Skype: t.reddish
Tel: +1 781.926.0676
w <applewebdata://02CE60AA-39CE-40B1-AD7C-34A3AC1B8832/www.mediavuesystems.com>ww.mediavuesystems.com <applewebdata://02CE60AA-39CE-40B1-AD7C-34A3AC1B8832/www.mediavuesystems.com>
