### ISSUE TITLE
Parent checkboxes not being checked when children selected.

### ISSUE THREAD

**Issue by duracell80** [vakata/jstree#1897]
Affects : jsTree - v3.3.4

Found that when selecting child folders, the parent folders and the root is not being checked (not selected but visually checked to make a valid chain). The chain seems invalid when selecting from deep level children. 

Example of working as expected tree selection: http://demos.telerik.com/kendo-ui/treeview/checkboxes
![tree-structure-working-correctly](https://user-images.githubusercontent.com/18121278/33849048-0c57a8ca-de75-11e7-8f8e-56aaeb377926.gif)

**Comment by vakata** [comment]
I am afraid I have no idea what you mean - please read over the config options of the checkboxes plugin. If you still believe something is wrong - please provide a demo (jsfiddle perhaps) and a description - what action should I take to reproduce the issue, what you think the expected result should be, what the result actually is. I will reopen when more information is available.

**Comment by duracell80** [comment]
Sure thing the expected selection is noted in the animated gif (to have parent folders visibly selected when clicking child items). I can work on reproducing on codepen or js fiddle.

In the project this is set, is there a cascade: both?
       ```
  $('#jstreeDiv').jstree({
               'plugins':["wholerow","checkbox"],
                 'checkbox' : {
                     'three_state': true,
                     'cascade': 'down'
                 }
            })
```

**Comment by vakata** [comment]
This should be enough to achieve what you need:
```
$('#jstreeDiv').jstree({ 'plugins':["wholerow","checkbox"] });
```

Here is a demo, feel free to modify this in order to demonstrate the problem:
http://jsfiddle.net/2kwkh2uL/7296/

**Comment by duracell80** [comment]
I updated the fiddle to reproduce the issue.
