### ISSUE TITLE
dnd_top.vakata data does not correct.

### ISSUE THREAD

**Issue by freelyageha** [vakata/jstree#1898]
```javascript
$(document).on('dnd_stop.vakata', function (e, data) {
  const ref = $('.jstree').jstree(true);
  const node = ref.get_node(data.element);
  const { id, parent, original } = node;
  console.log("node : " + id + ", original parent: " + original.parent + " attached to: " + parent);
  console.log("node: " + node);
});
```
When I did execute this event, current parent value does not changed.
But parent value in node object(at chrome console) is changed.
How can I capture changing parent value when raise stop event?

**Comment by vakata** [comment]
This is an external DND event - please do not use this event unless you know exactly what you are doing. Use the ```.jstree``` events (like ```move_node```, ```copy_node```, etc) to work with jstree nodes.
