### ISSUE TITLE
Node expansion broken with latest Firefox (57.0.2)

### ISSUE THREAD

**Issue by kjolley** [vakata/jstree#1899]
I have just updated Firefox and it has broken expanding/contracting nodes. This can be seen in the demo on https://www.jstree.com/.

**Comment by vakata** [comment]
I am using FF58 and there are no issues on the homepage demos on jstree.com - which demo is broken?

**Comment by vakata** [comment]
There was an issue with the filebrowser demo, but that was not related to a browser version. Please provide more information so that I can fix any errors.

**Comment by kjolley** [comment]
This is on Firefox 57.0.2.(64-bit) on both Windows 7 and Windows 10. It has happening on all demos. Screenshots are from the first demo on the front page (https://www.jstree.com/).

![screenshot1](https://user-images.githubusercontent.com/7817395/33958510-7a005a5c-e03c-11e7-842f-62da2df6bc40.png)
![screenshot2](https://user-images.githubusercontent.com/7817395/33958511-7c26f7b4-e03c-11e7-96e1-0eef12bf8c01.png)
![screenshot3](https://user-images.githubusercontent.com/7817395/33958515-7e4ee056-e03c-11e7-8a3b-2003f7526b6f.png)
![screenshot4](https://user-images.githubusercontent.com/7817395/33958517-802d9d9a-e03c-11e7-9d59-b1b13c15fcb6.png)

In screenshots 1 and 3 I am clicking the node - it neither expands or contracts. This was working fine until the latest Firefox update.

**Comment by vakata** [comment]
I just tested on two different machines using FF 57.0.2 (Quantum) 64-bit - both were fine. Could you please verify that you have cleared your cache? Do you get any errors in the console?

**Comment by kjolley** [comment]
Cleared cached - same problem. No errors in the console. 

I've disabled each plugin in turn - it seems that the issue is caused by the MJsonViewer plugin. The problem has gone away now that I have disabled this. 
Thanks for your support.

**Comment by vakata** [comment]
Thank you for the info, I am closing this.
