### ISSUE TITLE
save_state not working after dnd

### ISSUE THREAD

**Issue by lekhrajgit** [vakata/jstree#1900]
If I do multiple dnd in same tree and i do save_state after each move and in some cases when i do jstree("refresh") it goes back to the very first state where as i need it to retrieve last saved state .

**Comment by vakata** [comment]
You'd be better off using ```get_state``` and then ```set_state``` and calling ```refresh``` with the forget state option to avoid any race conditions. 
Also keep in mind ```refresh``` does not use the state from the state plugin, it uses the state as it is in the moment you invoke the method.

**Comment by lekhrajgit** [comment]
Thank @vakata really appreciate your help.

Is this correct syntax ?
`var state = inst.get_state();
 inst.set_state(state);
 inst.refresh('forget_state');`
