### ISSUE TITLE
add a new key using json

### ISSUE THREAD

**Issue by aminebhd** [vakata/jstree#1901]
hey firstly i thank you so much for this perfect plugin, 

just i want to ask you about how can i add new key value into the checkbox 
this is my code 
NB * i use php/json i have already the array key on the php side just i want to know how can i get it and set the value in the checkbox.

`$('#tree-container').jstree({
                      "plugins" : ["contextmenu", "types", "wholerow","checkbox"],
                      'core' : {
                        'data' : <?php echo json_encode($tree); ?>
                      }
                          });`

thank you so much

**Comment by vakata** [comment]
I am afraid that even if you add a value to the checkbox plugin that will not do any good for you - the checkboxes are for display purposes only - they can not be submitted as a normal form, as not all nodes are kept in the DOM (children of closed nodes are removed).
Your best bet is to populate a hidden field each time the selection in the tree changes - listen for the change event and then call ```get_selected``` or ```get_checked``` and populate the hidden field.
