### ISSUE TITLE
how to get detail data of children

### ISSUE THREAD

**Issue by linjinghui** [vakata/jstree#1902]
tree data like: [
{
‘id’: '0',
'text': 'name1',
'children': [
{
‘id’: 'id1',
'text': 'name1-1',
'children': []
}
]
}
]

setp1、select item 
setp2、
‘select_node.jstree’ function return data, 
data['children'] only back array of id, like ['id1', 'id2', 'id3', ...]

ques: 
i want get detail data of children, like back: children = [{
‘id’: 'id1',
'text': 'name1-1',
'children': []
}],
what should i do?

**Comment by vakata** [comment]
Check out ```get_json``` and ```get_node``` in the docs.
