### ISSUE TITLE
[QUESTION] jsTree without jQuery dependency?

### ISSUE THREAD

**Issue by temuri416** [vakata/jstree#1904]
Hi Ivan,

Have you ever considered releasing a jsTree version without jQuery dependency?

Cheers!

**Comment by vakata** [comment]
Yes, I have, in fact my working copy of v4 does not have any dependencies. I hope to publish it soon - I keep missing the deadlines I set for myself. I will give my best to release an alpha version soon.

**Comment by temuri416** [comment]
Fantastic! Looking forward to it.

**Comment by vakata** [comment]
A bit more info on v.4:
 - no jQuery
 - separate model and renderer components - meaning that there is a single source of truth - the model - all operations are performed on the tree model
 - the only implemented renderer so far is an infinite scroller with DOM node reusage, but the separate renderer component means that there can be a "classic" renderer, a canvas renderer, etc. As for the infinite scroller - only viewport-visible nodes are kept in the DOM and the DOM nodes are reused.
 - I am working on paging support
 - the above changes mean dropping IE8 support

**Comment by temuri416** [comment]
... and the "conditional unselect" plugin too, right? :-)

**Comment by vakata** [comment]
Hahaha, yes - in one form of another - I am still figuring out the "plugin system" for the new version, but I will try not to lose any functionality that is available in v.3 and also implement new features (like the conditional unselect functionality) :)

**Comment by vakata** [comment]
I am closing this discussion for now.

**Comment by amirgalor-gong** [comment]
Hi,
Any news on the v4 timeline ?
do you require any assistance ?

**Comment by gabayarden** [comment]
Hi @vakata 
Are there any news for v.4 of JsTree?
We are using JsTree since 2014 and we really need the infinite scrolling due bad search performance

**Comment by vakata** [comment]
@amirgalor-gong @gabayarden @temuri416 

I just published some dev code to:
https://github.com/vakata/jstree/tree/v.4.0

Some basic functionality is still missing, and the code works only in browsers that support generators, but that will change over the next few weeks.

**Comment by amirgalor-gong** [comment]
@vakata thank you,
again if you need any help - we would be offering it gladly.

**Comment by jrochkind** [comment]
Has this not ended up happening?

**Comment by ppazos** [comment]
Hi @vakata is v4 going to be released? thanks

**Comment by ug-code** [comment]
Any news about v4?
Looking forward to it.

**Comment by temuri416** [comment]
How about we all instead of asking @vakata - just donate him $10? Who's in?

**Comment by vakata** [comment]
I am struggling with time for jstree - I did nudge the repo a bit in 2023, so I expect to be able to find more and more time for jstree, but it is not as much as I want it. v4 lacks all the plugins of v3 and is not yet thoroughly tested, but it looks promising - I hope to reenable plugins one by one in the upcoming weeks / months. 

Once again - thanks to all who support the project! @temuri416 - thank you for being a long term supporter!

**Comment by gumbarros** [comment]
Are there any updates regarding v4 👀?
