### ISSUE TITLE
$(...).jstree not working in functions.

### ISSUE THREAD

**Issue by aydinokutanoglu** [vakata/jstree#1905]
Hi,

When using jstree it works on root of scripts, however not work in the functions. Below is my usage:

<script type="text/javascript">
    // This works OK.
    $('#tree').jstree({
    	'plugins' : [ "wholerow", "checkbox" ],
    	'core' : {
        	'data' : {
        		'url' : "ManageLDAP?Action=GetOuList",
   		 method: "POST",
   		 dataType: "json"
        	}
        }                	 		    		
    });
    
    function submitMe() {
    	var checked_ids = [];
        // This line gives the error, TypeError $(...).jstree is not a function 
    	$('#tree').jstree('get_checked',null,true).each(function(){
    		checked_ids.push(this.id);
    	});
    	//setting to hidden field
    	document.getElementById('checkedElements').value = checked_ids.join(",");
    }
</script>

Thanks,

**Comment by vakata** [comment]
Sorry, this has nothing to do with jstree - it is the way you include your files - you probably overwrite the jQuery variable and lose all plugins in the process - that would be my guess. Still, there is no way to prevent a jQuery plugin from working from inside a function. And event if there is - jsTree is not doing it.
