### ISSUE TITLE
cannot access homepage of http://www.jstree.com

### ISSUE THREAD

**Issue by honganan** [vakata/jstree#1906]
I am not sure if it's my locate result in access timeout for the jstree website. It seems not stable always when access from china.

**Comment by vakata** [comment]
Thank you for notifying me. I can not see any outages listed on my provider's page, and the site seems to load quickly for me. It is probably your local connection, let me know if the problem persists and I will investigate further.

**Comment by honganan** [comment]
I guess it is because of our goverment's firewall. We can only access foreign countries network by VPN. I guess many other chinese facing on the same problem, and jstree is a very good-to-use widget. I wonder if you can put the API doc on github, that will be much helpful. Thanks 4 your reply!
