### ISSUE TITLE
How to style DnD marker and line?

### ISSUE THREAD

**Issue by Francescogatto** [vakata/jstree#1907]
Hi, i need tu customize position, color and dimension of Drag and drop arrow and line, but i didn't find nothing about this. Someone have any idea about that?

**Comment by Francescogatto** [comment]
I found the css of the marker #jstree-marker, but how to edit the line?

**Comment by vakata** [comment]
Add any rules in your own CSS and customize as needed, just make sure your CSS is either after the original jstree one, or that it has higher specificity.

**Comment by Francescogatto** [comment]
But i can't find the css for the line marker..

**Comment by vakata** [comment]
The last version to have a marker was v.1, which has not been supported for years. v.3 does not have a marker - all it has is the little triangle.

**Comment by Francescogatto** [comment]
Thx fot the answers, but i need to customize this line
![schermata 2017-12-20 alle 15 11 35](https://user-images.githubusercontent.com/4219260/34211040-2e1a2652-e598-11e7-843f-8b587aa7df99.png)

**Comment by vakata** [comment]
Exactly - this is v.1 - it has not been supported for years.

**Comment by Francescogatto** [comment]
ah.. thanks a lot again
