### ISSUE TITLE
With touch node drag helper not appears.

### ISSUE THREAD

**Issue by ChandradipJ** [vakata/jstree#1908]
Drag and drop does not work correctly on touch devices. 

On drag helper, not appears.

**Comment by vakata** [comment]
It does but is usually hidden by the finger. You can correct this using CSS in your page and align the helper as you wish.

**Comment by RJSekar** [comment]
The issue still persist.
On drag helper, does not appears.

@vakata As you suggested. I had applied custom CSS to align the helper still not visible in ipad while dragging the node.

**Comment by ChandradipJ** [comment]
For me this is worked by setting **touch-action: none** and also disable the scroll on touch if you have.
