### ISSUE TITLE
json-loaded data is in original

### ISSUE THREAD

**Issue by RussNelson** [vakata/jstree#1912]
The JSON doc (https://www.jstree.com/docs/json/) says "Keep in mind you will be able to access any additional properties you specify - jsTree won't touch them and you will be able to use them later on." That's true, but those properties are not available in the node data. You have to go into the "original" hash to get them. I can't find the word "original" anywhere in the docs. Like this, modified from a demo in the docs:
```    $('#jstree_demo_div').on("changed.jstree", function (e, data) {
        console.log(data.selected);
        var i, j, r = [];
        if (data.selected.length == 1) {
            r.push(data.instance.get_node(data.selected[0]).original.v1);
        }
        $('#tab').html('<table id="tab"><tr><td>' + r.join('</td></tr><tr><td>') + '</td></tr></table>');
    });
```

**Comment by vakata** [comment]
Thank you - I updated the docs.
