### ISSUE TITLE
Unable to uncheck all nodes and only keep the selected checked.

### ISSUE THREAD

**Issue by zonewar** [vakata/jstree#1913]
Does jsTree allow me to uncheck all the nodes (recursively, including children) and only check the one that I select?  It doesn't seem to work.  Any help would be appreciated.  Thanks!

JsFiddle
Here is the code:
Top in jsFiddle:
<link href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" type="text/css" rel="stylesheet" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
    <div id="Tree"></div>
Bottom portion of jsFiddle:

var data1 = [{
      "id": "W",
      "text": "World",
      "state": { "opened": true },
      "children": [{"text": "Asia"}, 
                   {"text": "Africa"}, 
                   {"text": "Europe",
                    "state": { "opened": false },
                    "children": [ "France","Germany","UK"]
      }, {"text": "China"}]
    }];

$('#Tree').jstree({ 
    core: {
      data: data1, 
      check_callback: false
    }, 
    checkbox: {       
      three_state : false, // to avoid that fact that checking a node also check others
      whole_node : false,  // to avoid checking the box just clicking the node 
      tie_selection : false // for checking without selecting and selecting without checking
    },
    plugins: ['checkbox']
})
.on("check_node.jstree uncheck_node.jstree", function(e, data) {
    var result = [];
    
    getAllChildrenTexts($('#Tree'), data.instance.get_parent(data.node), result)
    
    
  
            
	if(data.node.state.checked === false ){
      //alert('uncheck');
      $('#Tree').jstree("select_node",data.node);
  		//uncheck all chilren
      /*
      var lnLevel = data.node.parents.length;
            var lsSelectedID = data.node.id;
            var loParent = $("#" + lsSelectedID);
            

					for (var ln = 0; ln <= lnLevel -1 ; ln++) {
                var loParent = loParent.parent().parent();
            
                
                $('#Tree').jstree("deselect_node", loParent);
            }
      */      
      }
      
  else {
  	//uncheck all.  then check all parents
  	
    
    			var lnLevel = data.node.parents.length;
            var lsSelectedID = data.node.id;
            var loParent = $("#" + lsSelectedID);
            $('#Tree').jstree("deselect_all", data.node.children);
          
            
            for (var ln = 0; ln <= lnLevel -1 ; ln++) {
                var loParent = loParent.parent().parent();
                $('#Tree').jstree("select_node", loParent);
                
            }
            
            
  
  }
  

})

function getAllChildrenTexts(treeObj, nodeId, result) {
    var node = treeObj.jstree("get_node", nodeId);
    treeObj.jstree("uncheck_node", node);
    //result.push(node.text.toUpperCase());
    

if (node.children) {
      for (var i = 0; i < node.children.length; i++) {
        getAllChildrenTexts(treeObj, node.children[i], result);
      }
    }
    }

**Comment by vakata** [comment]
Use ```deselect_all``` and the ```select_node``` and pass an array of node IDs as the first argument.
