### ISSUE TITLE
Has anyone figured out how to send JSON to a template, e.g. Handlebars and paint that?

### ISSUE THREAD

**Issue by KnowledgeGarden** [vakata/jstree#1914]
That I see no example of that leaves me to suspect that the usual escaping that goes on means it cannot be done. Still, it seems worth asking a perhaps naive question.  Thanks in advance for thoughts.

**Comment by vakata** [comment]
Templating engines are way too slow and they too escape in pretty much the same way. Anyway - v.4 is coming and it has something like a virtual DOM, making it hard to use a templating engine anyway.
