### ISSUE TITLE
"whole_node : false" doesn't work as expected

### ISSUE THREAD

**Issue by sergiik** [vakata/jstree#1916]
With "whole_node : false" I still can set checkbox by clicking on node name.
I would expect that sate can be changed in such case only by clicking on chekbox itself. Clicking anywhere else should not change checkbox state.

Here is code example:
https://jsfiddle.net/_kiser_/2kwkh2uL/7504/

**Comment by vakata** [comment]
I am not sure exactly what you need, but you probably need to detach selection from checkbox state:
https://jsfiddle.net/2kwkh2uL/7507/
