### ISSUE TITLE
jstree is not updating dynamically  or not able to refresh

### ISSUE THREAD

**Issue by Ashwin501** [vakata/jstree#1918]
Hi,

I am new to angular and jstree. Using Jsfree as a plugin for my project but it is not working when data changes dynamically or it is not refresh.

Javascript code:

$('#container').jstree({
                    "types": {
                        "default": {
                            "icon": "glyphicon glyphicon-file"
                        },
                        "demo": {
                            "icon": "glyphicon glyphicon-folder-open"
                        },
                        "process": {
                            "process": "true"
                        }

                    },
                    "plugins": ["types"]
                });

HTML Code:
<div id="container">
                    <ul>
                        <li data-jstree='{"opened":true, "type":"fileview"}'>Version
                            <ul>
                                <li ng-repeat="content in codebase"><a  data-content="{{content.content}}" >
                                   {{content.file_path}}</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>

"content" is having data and it is changing dynamically. But i am using jquery plugin in  my angularJs is that a problem? Please assist soon.
Thanks in advance.

**Comment by vakata** [comment]
I am afraid I can not help you with angular - jstree does not natively support angular. You must be using one of the third-party directives - ask the directive vendor.
