### ISSUE TITLE
Context Menu Appears in Wrong Place when SVG Foreign Object Tags present.

### ISSUE THREAD

**Issue by mmacfadden** [vakata/jstree#1920]
SVG allows for a foreignObject tag that lets you embed HTML inside an SVG element. The specification can be seen here:

https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject

```HTML
<html>
<body>
  <div>Some text</div>
  <div js-tree="tree_config">My Tree</div>
  <svg width="400px" height="300px" viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg">
    <rect></rect>
    <foreignObject width="100" height="50" requiredExtensions="http://www.w3.org/1999/xhtml">
      <!-- XHTML content goes here -->
      <body xmlns="http://www.w3.org/1999/xhtml">
        <p>Here is a paragraph that requires word wrap</p>
      </body>
    </foreignObject>
  </svg>
</body>
</html>
```

The issue here is that you wind up with more than one "body" tag in the resulting HTML. One directly under the HTML tag and then one under the foreignObject tag. The issue here the following line in the context menu plugin:

https://github.com/vakata/jstree/blob/93eb5c77ef237f3e9ee82838fde106b1e8d2e780/src/jstree.contextmenu.js#L486

The `appendTo()` function seems to be appending the context menu `ul` to the "last" body element in the document which is the one in the `<foreignObject>` tag. The code then goes on to position the element using CSS as seen below:

```HTML
<ul class="vakata-context jstree-contextmenu jstree-default-contextmenu" 
    style="left: 95px; top: 414px; display: block;"> `<foreignObject>`
</ul>
```

This means that the UL is not positioned relative to the top and left of the body tag in the `<foreignObject>` and not the actual main page's body tag. Therefore when the context menu pop's up it is not in the right place at all.

It seems like the selector used in the appendTo needs to be refined some how. Perhaps using `$(document.body)` or something like it. Maybe getting the document the JSTree belongs to, then getting that document's body would be best.

**Comment by vakata** [comment]
I am afraid I cannot reproduce the issue - here are two trees - one below the SVG element, one above, in both instances the contextmenu works properly.
http://jsfiddle.net/2kwkh2uL/7538/

Would you please update the fiddle so that I can reproduce the problem and fix it. I do not mind changing all occurrences to ```document.body```, but I'd rather have a way of validating that the fix works.

**Comment by mmacfadden** [comment]
@vakata Certainly. I took a quick peek and I did notice the text from the foreign object isn't showing up so I don't think its being rendered yet. I will update the fiddle and see if I can reproduce it there for you. Thanks for the quick response, and great work on JSTree in general.

**Comment by mmacfadden** [comment]
@vakata I wasn't able to modify your fiddle directly, but I was able to create one from scratch. The issue seems to be that if you just put the foreignObject tag in the HTML the extra body tag is removed. However joint JS is adding it (perhaps with JQuery), the extra body tag is not removed.

https://jsfiddle.net/5mo6wexj/
