### ISSUE TITLE
Have counter for childs types

### ISSUE THREAD

**Issue by aemaeth2501** [vakata/jstree#1921]
Hi,

This is more a feature request (or a quick guidance request), considering the fact that I am way too much a noob to implement the thing myself :) 

In a project I would require to have different counters on each nodes indicating the number of childs objects with a certain type (represented by color).

For example, on a parent node having 3 type A childs, 4 type B childs and 6 type C child I would like to have, on the node:
```
> Parent node label | 3 4 6
```
With the number 3 4 and 6 having a different color.

Do you think it is feasible ?

Regards,

aemaeth2501

**Comment by vakata** [comment]
You'd have to build a plugin for that. You can see sample plugins here:
https://github.com/vakata/jstree/blob/master/src/misc.js#L222

This sample plugin adds an icon, youacn similarly add a text node (with color), or multiple text nodes. I am afraid it is not a trivial task, but it is doable - use the linked sample plugin as a guide (and don't forget to include it on your page once finished, and list your plugin's name in the ```plugins``` config option on your instance).

**Comment by aemaeth2501** [comment]
Thank you for the guidance :)
