### ISSUE TITLE
Custom ContextMenu based on multiple selection

### ISSUE THREAD

**Issue by minedun6** [vakata/jstree#1922]
Hey,
How can I go about conditionally adding/remove menu items based on multiple/single selection ?
I tried to attack this but problem is that this can be acheived through the variable data accessible in the _disabled property through a callback. But I want to remove the menu item completely if I have a multiple selection.

**Comment by vakata** [comment]
https://www.jstree.com/api/#/?q=contextmenu.items&f=$.jstree.defaults.contextmenu.items - set to a callback - if multipleselection is detected - return no items, otherwise - the items you want.
