### ISSUE TITLE
Chrome does not handle sorting well

### ISSUE THREAD

**Issue by vemanaanne** [vakata/jstree#1923]
I am trying to sort layers dynamically in the sort function and my sort function is as below.
'sort': function (a, b) {
return parseInt(this.get_node(a).original.displayorder) > parseInt(this.get_node(b).original.displayorder) ? 1 : -1;
}

The private property display order is the one which sorts it. It works very well in IE but in chrome the actual nodes of the parent sit in between a set of child parent nodes.

Structure is like this.

-Root Node
-- Parent Node1-Display Order 0
---ChildNode1-DisplayOrder 0
---ChildNode2-DisplayOrder 1
---ChildNode3-DisplayOrder 2
----Parent Node 1 Child1-Display Order 0
----Parent Node 1 Child2-Display Order 1
----Parent Node 1 Child3-Display Order 2

The above structure renders correctly in IE but when it is chrome it comes as below.
-Root Node
-- Parent Node1-Display Order 0
---ChildNode1-DisplayOrder 0
----Parent Node 1 Child1-Display Order 0
---ChildNode2-DisplayOrder 1
----Parent Node 1 Child2-Display Order 1
---ChildNode3-DisplayOrder 2
----Parent Node 1 Child3-Display Order 2

I dont know what wrong I am doing here. Please help me.

**Comment by vakata** [comment]
I can not help you without a demo of the issue. I seriously doubt this is a jstree or Chrome problem - I suspect something is wrong with your data. As I said - please provide a demo so that I am able to help you and I will reopen.

**Comment by vemanaanne** [comment]
No problem, can I provide a live public domain website that has the same problem? Please let me know.

**Comment by vemanaanne** [comment]
Well, I figured the code that works in Chrome but now it does not work in FireFox.

Below is my code which works for IE and Chrome

After the code I provided instructions for viewing the problem on the live site.

Please help.

 // Get the node A.
                    var nodeA = this.get_node(a);

                    // Get the node B.
                    var nodeB = this.get_node(b);

                    // Get the node A children length.
                    var lengthA = nodeA.children.length;

                    // Get the node B children length.
                    var lengthB = nodeB.children.length;

                    // Check if the length of A and Length of B is greater = 0 OR check if the length of B and Length of A is greater than 0.
                    if ((lengthA == 0 && lengthB == 0) || (lengthA > 0 && lengthB > 0))
                        // Return the diaplay order.
                        return parseInt(this.get_node(a).original.displayorder) > parseInt(this.get_node(b).original.displayorder) ? 1 : -1;
                    else
                        // Return the display order
                        return lengthA > lengthB ? -1 : 1;


1) Go to web site --.https://marinescotland.atkinsgeospatial.com/nmpi/default.aspx
2)  From screen click on the icon highlighted with a red pen.
<img width="346" alt="screen1" src="https://user-images.githubusercontent.com/35293139/34773825-f49dec7e-f604-11e7-98ed-2b2ce9fabedf.PNG">
3)  As per screen2- once the dialog opens go to the node Productive and then go the node Fishing. You will that nodes inside layers are jumbled.
