### ISSUE TITLE
jstree dnd on move arrow appearance

### ISSUE THREAD

**Issue by kvelaro** [vakata/jstree#1924]
When I move element to another, interface gives me three positions [Arrow appears there]. Top border element, middle, and bottom border position. The problem is that, if I drop on middle arrow selection it's ok, if I drop on top or bottom position visual representation fails, but data.events.target is ok.

My config as follows

var tree = $('#xxx').jstree({
        "core" : { check_callback : true },
        "plugins": ["contextmenu", "dnd"]       
    });

$(document).on('dnd_stop.vakata', function(event, data) {
        var draggedElement = tree.jstree().get_node(data.element).data;
        var parentElement = tree.jstree().get_node(data.event.target).data;
        var domObj = data.element;

        console.log(data.event.srcElement);
        console.log(data.event.target);
        console.log(data.event.toElement);
 });

On your site at demo page 
http://yii.local/#/demo
drop functionality works perfect, but from https://github.com/vakata/jstree-php-demos it's behaviour as I described.

Could you please answer, how to solve this problem professionally?
![eejjhpfdimlmlbom](https://user-images.githubusercontent.com/8030568/34818295-6f392504-f6cb-11e7-9d7a-3c2addcff1e2.png)

**Comment by vakata** [comment]
The code from php-demos uses v.3.3.3, and jstree.com uses the latest version - update your code to the latest version.

**Comment by kvelaro** [comment]
I use latest version of jstree.
Please look at https://www.jstree.com/plugins/ right to the dnd plugin. Error also exists there
