### ISSUE TITLE
Cannot load 10k plus child nodes in FireFox and IE browser but can load in Chrome.

### ISSUE THREAD

**Issue by razmy** [vakata/jstree#1925]
Cannot load 10k plus child nodes in Firefox and IE browser. However, I was loaded in Chrome browser.
I tested up to 40k in Chrome and it loaded without any issue.  Please help us to resolve this issue.

**Comment by vakata** [comment]
This is normal - it all depends on how nested the data is and other factors. I usually test with 35k nodes, and they work fine in all browsers - but as I said - there are many factors in play. A flat list of 10k will take a lot longer to render than a nested set. I am afraid there is nothing more I can do for v.3 (I hope you are using v.3, if using v.1 - please upgrade!). 

You could consider lazy loading, so that data is added to the tree as needed and not in one go, but that might require some refactoring on your part.

v.4 which I am working on will not have this problem, but I think a beta will be available in spring the earliest.

**Comment by razmy** [comment]
Can you share the lazy loading steps with me.

**Comment by vakata** [comment]
Use this:
https://github.com/vakata/jstree#populating-the-tree-using-ajax-and-lazy-loading-nodes
Or this:
https://github.com/vakata/jstree#populating-the-tree-using-a-callback-function

The first solution uses AJAX, the second - a callback function - use whichever suits your needs.

**Comment by razmy** [comment]
Thanks for share the links. However, I'm already following the lazy loading (https://github.com/vakata/jstree#populating-the-tree-using-ajax-and-lazy-loading-nodes). Basically I have one parent node when expand the child node of 10k plus only the browsers (Firefox and IE) give the issue.

**Comment by razmy** [comment]
Do you have any bulk load  api to load the data and create the nodes without disturbing existing nodes in the tree? Please help me on this question as I'm in a critical  situation. Thanks in advance for understanding.

**Comment by razmy** [comment]
Hi Vakata,
Basically, I'm loading the nodes using the lazy loading approach. Here, I'm only loading 50k since we cannot load more than 10k plus in the IE and FireFox. And the last node of the tree will be some thing like "load 5001 to 10000 of 25000". When user clicks on the this special node I'm using a ajax call to fetch the data. Here, I'm currently using the "create_node" api which is very slow and hanging the browser. If there are is any bulk loading api as I mention in the previous post that would be a great help.
Thanks
Razmy

**Comment by vakata** [comment]
No, there is no such method, ```create_node``` is not meant to load large amounts of nodes. 

Here is a piece of code you might want to have a look at and optionally merge on top of your copy of jstree:
https://github.com/vakata/jstree/pull/1742

**Comment by razmy** [comment]
Hi Ivan,

Thanks for you support, I am able to pagination type of approach based the
client requirement. However, I am unable to display the spinner when
creating the nodes. Please let me know how can I call the spinner
externally of the jstree.

Regards,
Razmy

**Comment by vakata** [comment]
Add the ```jstree-loading``` class to the node's LI element.

**Comment by razmy** [comment]
Thanks for reply.However, I already found this and implemented.
