### ISSUE TITLE
ARIA attributes

### ISSUE THREAD

**Issue by KennethSeiero** [vakata/jstree#1926]
Hey

I've got a blind user, with JAWS installed.  During our test of the jsTree we noticed that, he couldnt get the states of the lines, as he was using arrowkeys for navigation.

The ARIA attributes are located on the LI, but when JAWS is reading from the elements, its reading the A links.

As i couldn't find another working method, I ended up fixing this, by adding the aria attributes to the A element, and also setting the role to checkbox, otherwise i couldnt read him the checked state.

(my top root level is pre-defined with id "ALL", thats why im checking for that value, and the returned id is just #, and i cant select on ##).

Here's my working sample code:

On select handler (adding the aria-checked: true and also parent markers for checkbox (true, false, mixed))

		sms_jsTree.on('select_node.jstree', function (e, data) {
			var a = $("#"+data.node.a_attr.id);
			a.attr("aria-checked",true);
			
			var selected = sms_jsTree.jstree("get_selected",true);
			$.each(selected,function(index,value){
				var a = $("#"+value.a_attr.id);
				a.attr("aria-checked",true);
				
				if (value.parent != "#") {
					var parent = $("#"+value.parent);
				} else {
					var parent = $("#ALL_anchor");
				}
				
				if (sms_jsTree.jstree("is_undetermined", parent) == true) {
					//Multi state
					parent.find("a.jstree-anchor").first().attr("aria-checked","mixed");
				} else if (sms_jsTree.jstree("is_checked", parent) == true) {
					//Checked state
					parent.find("a.jstree-anchor").first().attr("aria-checked","true");
				} else {
					//Unchecked state	
					parent.find("a.jstree-anchor").first().attr("aria-checked","false");
				}
			});
		});

I've got a similar handler for deselection, and on open/close of parents adding (aria-checked=false, and aria-expand:false)

Sample HTML DOM:

Look for A attributes ->  aria-checked="false" role="checkbox"

```
<li role="treeitem" aria-selected="false" aria-level="3" aria-labelledby="ABHK-HX-CR1_anchor" id="ABHK-HX-CR1" class="jstree-node  jstree-leaf">
    <div unselectable="on" role="presentation" class="jstree-wholerow">&nbsp;</div><i class="jstree-icon jstree-ocl" role="presentation"></i>
	<a class="jstree-anchor" href="#" tabindex="-1" aria-level="3" aria-checked="false" role="checkbox" id="ABHK-HX-CR1_anchor">
	<i class="jstree-icon jstree-checkbox" role="presentation"></i>
	<i class="jstree-icon jstree-themeicon jstree-themeicon-custom" role="presentation" style="background-image: url(&quot;library/img/mfg-labs-iconset_2014-07-29_link_3_nodes_16_0_ff6600_none.png&quot;); background-position: center center; background-size: auto auto;"></i>
	ABHK-HX-CR1</a>
</li>
```

**Comment by vakata** [comment]
Accessibility and trees is a big mess at the moment. I would really love some PRs regarding this functionality as each time I make a change one thing improves but something else breaks, sometimes only in one browser / reader combo. I try to follow the spec as close as I can, but for anything else - please provide PRs.

**Comment by kutensky** [comment]
If anyone here with the same problem, here is my solution for making tree readable by Jaws and NVDA. You can call this function on "ready.jstree" event.
```
var fixJsTree = function(jsTree, $tree) {
	fixSubtree($tree);

	$tree.on('after_open.jstree after_close.jstree', function(e, data) {
		var $li = jsTree.get_node(data.node, true);
		duplicateAriaExpand($li);

		if (e.type === 'after_open') {
			fixSubtree($li);
		}
	}).on('select_node.jstree deselect_node.jstree', function(e, data) {
		var $li = jsTree.get_node(data.node, true);
		duplicateAriaSelected($li);
	}).on('enable_node.jstree disable_node.jstree', function(e, data) {
		var $li = jsTree.get_node(data.node, true);
		duplicateAriaDisabled($li);
	}).on('deselect_all.jstree', function(e, data) {
		for(var i = 0; i < data.node.length; i++)
		{
			var $li = jsTree.get_node(data.node[i], true);
			duplicateAriaSelected($li);
		}
	}).on('check_node.jstree uncheck_node.jstree', function(e, data) {
		var $li = jsTree.get_node(data.node, true);
		var $a = $li.children('a');
		duplicateAriaSelected($li, $a);

		if ($a.attr('isfolder') === "true") {
			setTimeout(function() {
				$li.find('li').each(function() {
					var $childLi = $(this);
					var $childA = $childLi.children('a');
					duplicateAriaSelected($childLi, $childA);
				})
			}, 100)
		}
	})
};

function fixSubtree($subTree) {
	$subTree.find('li').each(function() {
		var $li = $(this);
		var $a = $li.children('a');
		$li.attr('role', 'presentation');
		$a.attr('role', 'treeitem');
		$a.attr('aria-level', $li.attr('aria-level'));

		duplicateAriaExpand($li, $a);
		duplicateAriaSelected($li, $a);
		duplicateAriaDisabled($li, $a);
	});
}

function duplicateAriaExpand($li, $a) {
	getChildAnchor($li, $a).attr('aria-expanded', $li.attr('aria-expanded'));
}

function duplicateAriaSelected($li, $a) {
	getChildAnchor($li, $a).attr('aria-selected', $li.attr('aria-selected'));
}

function duplicateAriaDisabled($li, $a) {
	getChildAnchor($li, $a).attr('aria-disabled', $li.attr('aria-disabled'));
}

function getChildAnchor($li, $a) {
	return $a || $li.children('a');
}
```
