### ISSUE TITLE
Is it possible to modify the format of the JSON data for getting the Ajax load child node

### ISSUE THREAD

**Issue by loveincode** [vakata/jstree#1927]
``
![image](https://user-images.githubusercontent.com/29159573/35026777-f0b1ada2-fb87-11e7-80f3-74d6460297ec.png)

Can this modify the JSON format？

Thank you！

**Comment by vakata** [comment]
If you need to modify the JSON before passing it to jstree use ```core.data``` as a function - fetch the data with a normal ajax call, modify it so it matches the format required by jsTree, and then invoke the callback.

**Comment by loveincode** [comment]
thank you!
