### ISSUE TITLE
jsTree get JSON Data from .html link

### ISSUE THREAD

**Issue by Mxesli** [vakata/jstree#1929]
I want to get my JSON files from a .html site so that a javascript can check the URL Parameters from the link and return the right value / JSON. But jsTree does not shows the data. 

(jsTree open the link like this "https://xxx.yyy/xxx/getData.html?id=2")

my .html site:

```
    <head>
    <script src="scripts/getJSON.js"></script>
    </head>
```
    
    
my .js site (just for testing):

```
    var url_string = window.location.href;
    var url = new URL(url_string);
    var id = url.searchParams.get("id");
    //console.log(id);
    
    if (id === "2"){
        document.write('[{"id":"2.1.1","text":"Sub Folder 2.1.1","children":[{"id":"2.1.1.1","text":"Sub Folder 2.1.1.1"}]}]');
    }
```

is it possible to do what i want with jsTree? or do i need to use a .json link?

(with a .json link it works fine, but i cant check the URL Parameters)

**Comment by Mxesli** [comment]
Okay i read your documentation about lazy loading again and now i know i need to set "dataType" to "json" in order to get json from a .html link but i also noticed that jsTree / the ajax call does not run javascript code so my idea wont work.  

In the lazyloading doc. you said : 

> You can also set "url" to a function and it works exactly as with "data" - each time a request has to be made, jstree will invoke your function and the request will go off to whatever you return in this function. This is useful when dealing with URLs like: http://example.com/get_children/1

but you did not explain how to do it. could you help me out, so that when a Node with the ID "2" gets openend the links in not "https://xxx.xxx/xxx/json?id=2"  but insted "https://xxx.xxx/xxx/json/2.json"

**Comment by vakata** [comment]
I believe all the options are clearly explained both on jstree.com and on the homepage of this repo. I am afraid I can not help you further.
