### ISSUE TITLE
How to lazy load nodes when expanded in jsTree?

### ISSUE THREAD

**Issue by TheInvoker** [vakata/jstree#1934]
I have this js code to create a tree with the jsTree plugin.

		var n2 = {
			  id          : "B", // will be autogenerated if omitted
			  text        : "B", // node text
			  icon        : undefined, // string for custom
			  state       : {
				opened    : false,  // is the node open
				disabled  : false,  // is the node disabled
				selected  : false  // is the node selected
			  },
			  children    : [],  // array of strings or objects
			  li_attr     : {},  // attributes for the generated LI node
			  a_attr      : {},  // attributes for the generated A node 
			};
		var n1 = {
			  id          : "A", // will be autogenerated if omitted
			  text        : "A", // node text
			  icon        : undefined, // string for custom
			  state       : {
				opened    : false,  // is the node open
				disabled  : false,  // is the node disabled
				selected  : false  // is the node selected
			  },
			  children    : [n2],  // array of strings or objects
			  li_attr     : {},  // attributes for the generated LI node
			  a_attr      : {}  // attributes for the generated A node
			};
			
		
		$('#jstree_demo_div').jstree({ 
			'core' : {
				'data' : function (obj, cb) {
					console.log(obj);
					cb.call(this, [n1]);
				}
			}
		}); 

There is 2 nodes, A and B. B is a child of A. I want to set it so that B is a child of A, but B is only added to the DOM, when A is expanded the first time.

The above code doesn't work, it seems to always load B when A is loaded. Does anyone know how to do this?

Thanks

**Comment by TheInvoker** [comment]
I figured it out. You just set `children` to true, which means it has children but it doesn't know them yet. The actual children can be stored in the `data` property. When the node is expanded, you just get the children from the `data` and return that, to render into the DOM. The data callback gets called on the initial load, and the id will be `#`, which means you need to return the root elements array. If it's not that, then you expanded a node.

		var n2 = {
			  id          : "B", // will be autogenerated if omitted
			  text        : "B", // node text
			  icon        : undefined, // string for custom
			  state       : {
				opened    : false,  // is the node open
				disabled  : false,  // is the node disabled
				selected  : false  // is the node selected
			  },
			  children    : [],  // array of strings or objects
			  li_attr     : {},  // attributes for the generated LI node
			  a_attr      : {},  // attributes for the generated A node 
			};
		var n1 = {
			  id          : "A", // will be autogenerated if omitted
			  text        : "A", // node text
			  icon        : undefined, // string for custom
			  state       : {
				opened    : false,  // is the node open
				disabled  : false,  // is the node disabled
				selected  : false  // is the node selected
			  },
			  children    : true,  // array of strings or objects
			  data : [n2],
			  li_attr     : {},  // attributes for the generated LI node
			  a_attr      : {}  // attributes for the generated A node
			};
		var root = [n1];
		
		$('#jstree_demo_div').jstree({ 
			'core' : {
				'data' : function (obj, cb) {
					cb.call(this, obj.id == "#" ? root : obj.data);  
				}
			}
		});

**Comment by vakata** [comment]
Storing all this data in the node structure is not really recommended, besides - you could store it in the ```children``` property and skip lazy loading all together.

Anyway - a better approach would be to simply use the variables, WITHOUT storing anything on the parent node:
```js
cb.call(this, obj.id == "#" ? [n1] : [n2]); 
```
