### ISSUE TITLE
jstree dnd over/out node

### ISSUE THREAD

**Issue by mardif** [vakata/jstree#1936]
Hi Ivan,
  How can I give user evidence on tree where drop will be executed during dnd event?

For example: I have a normal tree composed by folders and leafs.
![jstree](https://user-images.githubusercontent.com/4513750/35471253-bb675278-0357-11e8-8586-af964a26e608.png)

When user drag leaf named "Vaiano Valle", I would like to highlight destination (n. 1), and if user move above/after leaf (not inside), I would highlight "Centro abitato" (2), because drop above/after leaf will cause that "Vaiano Valle" will be son of "Centro abitato".

Otherwise, is there a way to draw someting between leafs? I don't know.... a black div revealed only on dragover?

Can you help me?

Thx in advance

**Comment by vakata** [comment]
The idea behind the arrow is to point to where the node would go. So if you drop between nodes the arrow will point there, if dragging over the center portion of a node the arrow will try to indicate that.

If you want to override that behavior you have a couple of options - either listen for the dnd_move.vakata event and add your own custom code, you could also use the check_callback https://www.jstree.com/api/#/?q=check&f=$.jstree.defaults.core.check_callback but it is a bit more involved.

Either way - I am afraid I can not implement this for you - it is possible but I can't help you with implementing it.

**Comment by mardif** [comment]
So sad, but I understand you.

Thx a lot
