### ISSUE TITLE
How to listen and event if all nodes are expanded or not ?

### ISSUE THREAD

**Issue by jimmy17x** [vakata/jstree#1938]
I used the open_all on event listener , but this works  only if I am invoking this event . 

But how can I detect if the user is expanding each node one by one and all nodes are expanded ?

Both show_all and open_all is getting invoked on doing only on doing opne_all

**Comment by jimmy17x** [comment]
I have found this solution , please let me know if this is valid - 
```

	$('#container').on('after_open.jstree', function(e, data) {
            var closed_count = $(".jstree-closed").length;
            if(closed_count == 0)
            {
            	alert("all opened");
            }
            
				 }).jstree();
```

**Comment by vakata** [comment]
Your solution will work fine. But if you use the search functionality combined with ```show_only_matches``` check if the end result is what you need (then the alert will fire if all visible nodes are open, which does not necessarily mean ALL nodes in the tree).

**Comment by jimmy17x** [comment]
In my use case ALL nodes should be visible . Thanks for acknowledging
