### ISSUE TITLE
Uncaught TypeError with very simple tree (stop isn't a function)

### ISSUE THREAD

**Issue by stephane** [vakata/jstree#1939]
In this fiddle https://jsfiddle.net/6Latwa7k/, when I click on the node with two children an error is raised:

`jstree.min.js:3 Uncaught TypeError: h.children(...).css(...).end(...).removeClass(...).addClass(...).attr(...).children(...).stop is not a function`

The fiddle use jquery 3.3.1
Tested with Chrome and Firefox.

**Comment by vakata** [comment]
jstree requires jQuery, not jQuery slim (which has no animation functions - hence the error).

**Comment by stephane** [comment]
OK, thank you very much. Is it possible to add that information in the
documentation of jstree?

2018-01-30 13:04 GMT+01:00 Ivan Bozhanov <notifications@github.com>:
