### ISSUE TITLE
I am not able to refresh jstree in IE 11

### ISSUE THREAD

**Issue by krunal1089** [vakata/jstree#1944]
steps to reproduce
1) load Jstree from database with ID
2) delete any child node or add child node 
3) tree is getting refresh but newly added node is not getting displayed or deleted node is not removed from tree.
but same code is working in Chrome Browser but not on  Internet Explorer 11

**Comment by vakata** [comment]
This could be a lot of things but I doubt it is a jstree problem. Make sure any responses are not cached and that indeed - the changes are stored in the DB.
