### ISSUE TITLE
How much is the upper limit of the set of data that the jsTree can display?

### ISSUE THREAD

**Issue by maoyue0917** [vakata/jstree#1945]
How much is the upper limit of the set of data that the jsTree can display? **Thirty-million data items can be displayed ?** If the plug-in support for such a big data, then in actual use need to pay attention to what? In order to avoid the program stuck. @vakata

**Comment by vakata** [comment]
I assume you will be using lazy-loading, as without it most browsers will even struggle to hold the thirty million node objects in memory.
The limit will depend on the type of data you have - a flat list of 30 million nodes will crash, in fact - anything above 15000 nodes will probably crash (depending on browser). A heavily nested list will fare better, as only visible nodes are kept in the DOM, I have done tests with 100 000 nodes, but again - it all depends on your structure.
To be honest - I do not think 30 million nodes can be reliably visualized by any library. I am working on v.4 which might be a bit better (as it uses a sort of a virtual dom), but that won't be ready soon. If you really must have a tree - give jstree a try if you can use lazy loading and the data is not very flat, but still - 30 million nodes is a lot, so I am not sure it will work properly in all cases - the limitation will have to do mostly with RAM usage and browser DOM interactions.
