### ISSUE TITLE
Jstree stopped working from Chrome v63.0.3163.100 (Build oficial) and futher v64  also

### ISSUE THREAD

**Issue by suggaladinesh** [vakata/jstree#1946]
Hi!

I have implemented jstree in my Salesforce org . Few days back it was working properly and now, without any change in the code, it stopped working mainly the folder tree structure

I've cleared the cache and tried,it doesn't work. For other browsers its working properly. Only issue is coming in chrome browser

Do you know what could be going on?

Thanks!

**Comment by suggaladinesh** [comment]
[VFPage.txt](https://github.com/vakata/jstree/files/1719622/VFPage.txt)
Attaching "VFPage.txt" is my code which I have used. It is working in Chrome 62 version and below version & Other browsers also its working fine. What Can i do in the code level so i can fix my issue in chrome 64 version

**Comment by vakata** [comment]
I can assure you jstree works fine on all Chrome versions from 14 up. I can not help you further, as debugging someone else's code is not a service I provide.
