### ISSUE TITLE
jsTree - How to load children only using ajax call, while Parents are loaded with html UL LI tag

### ISSUE THREAD

**Issue by rajiv-menon** [vakata/jstree#1948]
jsTree - How to load children only using ajax call, while Parents are loaded with html UL LI tag.

So the view would be something like:

there are about 20 Parent nodes (loaded using UL LI), once those are rendered, when user clicks on any of those Parent nodes, an ajax call is fired which will populate the child node for that parent.

any example would really help. Thank you in advance!!

**Comment by vakata** [comment]
Use ```core.data``` as a callback - then you have to manually parse the HTML for the first load (when the ID you receive in the callback is "#", any other ID should be processed using an AJAX request.
Here are the docs on this use case:
https://github.com/vakata/jstree#populating-the-tree-using-a-callback-function
