### ISSUE TITLE
Add style showing drop target in between nodes

### ISSUE THREAD

**Issue by bbottema** [vakata/jstree#1950]
When dragging a node over other nodes, the hint of where a node will actually drop is inconclusive:

- If I drop it on the top edge of a node, it will drop above
- If I drop it on the bottom edge of a node, it will drop below
- If I drop it in the middle of a node, it will drop inside

Sounds pretty straightforward, but it's actually quite unpredictable with a lot of mis-drops. It would be great if we could see a divider-styled drop target for the drop-on-edge cases.

**Comment by vakata** [comment]
I will see what I can do for future versions, but for now you can use this solution:
http://jsfiddle.net/2kwkh2uL/9265/

You can tweak the style of the pseudo element in order to achieve different effects.

**Comment by bbottema** [comment]
Geez, I never even saw that `#jstree-marker`, due to my side menu being on top of it. After fixing it's z-depth I saw it. Still, the divider in your demo is very helpful. Thanks.
