### ISSUE TITLE
WAI-ARIA Mismatch

### ISSUE THREAD

**Issue by MarioBatusic** [vakata/jstree#1952]
Navigating the tree with the keyboard focusses ```<a>```-tags whereas all necessary ARIA staff is noted on the parent ```<li>``` tags. 
The screenreader NVDA for example speacks neither tree levels nor the expansion state by keyboard navigating but only "Link LinkName".

Solution: Put and control ARIA markup directly on the ```<a>``` tag and set every ```<li role=presentation>```. Thanks.

**Comment by vakata** [comment]
Duplicate of #1926
