### ISSUE TITLE
Tree is not available during ajax refresh

### ISSUE THREAD

**Issue by sebasmoyano** [vakata/jstree#1956]
During the resolution of the ajax call that loads nodes, tree events like `click` are not fired. 

Any workaround for this?

**Comment by sebasmoyano** [comment]
To update the tree I'm using:

`$('#mytree').jstree(true).refresh(true);`

**Comment by vakata** [comment]
Tree nodes can be clicked while the tree is refreshing - here is a demo:
http://jsfiddle.net/DGAF4/2996/

Open the root - you can still select it while it is loading, once loaded - click "refresh" - once again - you can click on the root node while it is refreshing.

**Comment by sebasmoyano** [comment]
Please check now:
http://jsfiddle.net/DGAF4/3022/

During refresh selection is not allowed.

**Comment by vakata** [comment]
Yes, of course, as there is nothing to click on. The loading message is not a valid node and is not meant to be selected.
