### ISSUE TITLE
contextmenu not triggered

### ISSUE THREAD

**Issue by wambacher** [vakata/jstree#1957]
Hi,

i'm migrating a web application from openlayers to leaflet.

the old - and still running - site is using ui-layout and jstree is running fine in the left area. 
see https://wambachers-osm.website/boundaries (*).

By using leaflet i want to make this page simpler and therefore easier to support.

I managed to get the base layout (without ui.layers) running and now i want to add jstree in a leaflet dialog box. see  https://wambachers-osm.website/boundaries5    (ending with 5 for Version 5)

The tree is fine but contextmenu does not work. nothing happens.
Added the tree to an ui-dialog box with the same problem.

any idea? especially if there are known problems or "to do's" when using leaflet.

regards
walter

*) you are welcome to use that site. > 430.000 boundaries of the world in different formats. of course for free. that's osm.

**Comment by vakata** [comment]
Probably z-index related - give the contextmenu DIV a higher z-index in your CSS. For example using:
```
.jstree-contextmenu { z-index: 99999; }
```

**Comment by wambacher** [comment]
no, did not help :(
i debugged a little bit and the plugin is called and is running - but does not display anything.

i'm not very experienced with plugins but:

jstree.js:46 	document = window.document; // local variable is always faster to access then a global

which value will/should get document? the main window or the dialog box window?

regards
walter

btw: please don't close unless the problem is solved :(

**Comment by vakata** [comment]
Since you so kindly provided my with information on how to close / open issues. Let me provide you with some insight on how to file them:
1) Provide version information - do not expect the maintainer of a project to debug your code
2) Provide a demo pf the issue - it is best to have an isolated demo - of the issue only.

In your case the provided link does not work (JS error), so I provided you with my best guess, which always solves issues with modals - the z-index tip. Once there is a demo of the issue that I can look at I will reopen this ticket.

**Comment by wambacher** [comment]
yes, i know - and i'm working on it.

**Comment by wambacher** [comment]
the long version is back again: https://wambachers-osm.website/boundaries5

now i'll strip it down.

**Comment by wambacher** [comment]
after stripping down to this version https://wambachers-osm.website/boundaries5/mini.jsp **it's working**.
last line i removed was <link rel='StyleSheet' href='css/map.css'> so the problem comes from this style file :(

i'll check this file and i hopefully find the - self made - problem.

**Comment by wambacher** [comment]
omg: found  

`ul.vakata-context{
        z-index: 99;  
}`

in my style. (this file is more than 4 years old. no idea why i added that stuff.)

sorry for that.

Regards
walter
