### ISSUE TITLE
issue on: Populating the tree using a callback function

### ISSUE THREAD

**Issue by Xixiao007** [vakata/jstree#1960]
Hi,

I try to use jstree in a Salesforce application.

I use callback function mentioned in the `README` file: https://github.com/vakata/jstree#populating-the-tree-using-a-callback-function.

The code snippet below is the simplest scenario, which works as - when a node is double-clicked:
1. A AJAX call is fired out to server endpoint, which immediately return a 'hello' string.
2. Once AJAX call is finished successfully, display its sub node. Note that the data returned from AJAX has nothing to do with the sub node data (testing purpose here).

**The issue**
The AJAX call returned from server is epic slow, 10 - 30sec or timeout...  In normal scenario, it should be within 1 sec as the server only returns a dummy "hello" string.

From the screenshot, we can see that the ajax call is fired (multiple times), but the response it not there.

**Troubleshoot**
If I put the AJAX call outside of $("#render123").jstree(), such as triggered by a button, the call returns instantly and well.

**Question**
I ran out of options to debug and diagnose, how can I continue?? I sense that it might be other js libraries used in the page are incompatible with jstree, but hard to tell....

```javascript
    $("#render123").jstree({
      core: {
        data: function(node, cb) {

          //Salesforce specific way to call server side ajax endpoint: getStructureInfo(), which immediately return a 'hello' string;
          var action = component.get("c.getStructureInfo");
          action.setParams({});
          action.setCallback(this, function(response) {
            console.log("callback is returned");
            var state = response.getState();
            console.log("state: " + state);

            if (state === "SUCCESS") {
              var result = response.getReturnValue();
              console.log("Data: \n" + result);
              cb([
                {
                  text: "Docs",
                  children: true,
                  data: {
                    uri: "123"
                  }
                }
              ]);
            }
          });
          $A.enqueueAction(action);
          console.log("ajax fire");
        }
      }
    });
```
![virtualbox_testbox_05_03_2018_10_29_32](https://user-images.githubusercontent.com/13655323/36969136-4adf29f8-206d-11e8-9f0e-4f0711da1443.png)

**Comment by vakata** [comment]
jsTree has absolutely no affect on the speed of the response. Once you call ```cb``` jstree will display what you passed - I would check somewhere else. Run a profiler and check where the time is spent, if it is on the server side (and not for example waiting on a client side queue) - debug the server side. You can also gather some information on the network tab. I assure you this has nothing to do with jstree.

**Comment by Xixiao007** [comment]
It is indeed a Salesforce trick, thread can be closed.
I have got the answer in this thread below:
https://salesforce.stackexchange.com/questions/210400/a-enqueueaction-not-returned-in-jquery-context
