### ISSUE TITLE
jstree id changes upon new request

### ISSUE THREAD

**Issue by rajiv-menon** [vakata/jstree#1962]
Hello,

I've a jstree that is created using UL LI, looks like this

<ul class="jstree-container-ul jstree-children" role="group">
	<li role="treeitem" aria-selected="true" aria-level="1" aria-labelledby="j1_1_anchor" aria-expanded="true" id="j1_1" class="jstree-node jstree-last jstree-open">
	<i class="jstree-icon jstree-ocl" role="presentation"></i>
	<a class="jstree-anchor jstree-clicked" href="#" tabindex="-1" id="j1_1_anchor">Super Group</a>

Once rendered, I use id="j1_1" to perform some tasks.

I found that everytime UL LI is recreated upon new page request, the id changes to j2_1 and then to j3_1 so on and so forth.

Since, I rely on id being "j1_1", is there a way to keep that id as "j1_1" and not have it change upon every new request? is that possible?

all child node id pattern also bases it's numbering based on parent node.

Thanks much!!

**Comment by vakata** [comment]
jsTree falls back to autogenerated IDs when no IDs are specified. The IDs are built using j<instance-counter>-<node-counter>. The fact that the IDs change means that there is no actual page refresh, just the tree is recreated (maybe a SPA).

Anyway, if you need to rely on IDs - make sure you specify your own IDs and do not depend on the autogenerated ones.
