### ISSUE TITLE
ContextMenu overlaps with other tree nodes

### ISSUE THREAD

**Issue by Xixiao007** [vakata/jstree#1963]
Hello,

I enabled the contextmenu in my jstree instance. However, issues appear:

1. the context menu overlaps with other nodes (screenshot below)
2. Hover over mouse to items in the context menu does not highlight them like how [the demo does ](http://jsfiddle.net/vakata/2kwkh2uL/4489/)

Troubleshooting:

I suspect that the styling is ruined by other parts of the page. But I am not sure where to look into.
Any tip is very much welcomed!

![screen shot 2018-03-09 at 14 27 36](https://user-images.githubusercontent.com/13655323/37207540-2696aa80-23a6-11e8-9f3f-c8e2e7288e53.png)

**Comment by vakata** [comment]
Inspect the contextmenu and increase its z-index in your CSS.
