### ISSUE TITLE
Do I have to use frames?

### ISSUE THREAD

**Issue by meatballcoder** [vakata/jstree#1966]
I wanted to use jsTree with links and populate the right pane on a click.  I didn't see how to do that, plus I was wanted to know if I had to have frames to make jsTree work.  Thanks.

**Comment by vakata** [comment]
https://github.com/vakata/jstree#working-with-events

As stated in the docs - jsTree will trigger the ```changed.jstree``` event every time the selection is changed. You can listen for that event and react accordingly (as seen in the demo - you get the current selection so you can update your right pane accordingly).
