### ISSUE TITLE
Disable context menu right click event for an specific node.

### ISSUE THREAD

**Issue by Freddie-Pike** [vakata/jstree#1967]
I am currently having issue disabling a context menu for a specific node. 

Issue #1862 describes disabling the context menu for all nodes using the following line of code:

$('#jstree_div_id').off("contextmenu.jstree", ".jstree-anchor");

However, I want to do this with a specific node. My thoughts on how to do this would be define an unique class for the node in the JSON like this:

var new_node = {
       ...
        "a_attr": {
          "class": "no-context-menu"
        },
      };

And then once new_node is added to the jstree, I can modify the JQuery code above and do this in order for the new node to not have a contextmenu:

$('#jstree_div_id').off("contextmenu.jstree", ".no-context-menu");

This however doesn't work. Do you have any suggestions on how to achieve this?

**Comment by vakata** [comment]
Use this:
https://www.jstree.com/api/#/?q=context&f=$.jstree.defaults.contextmenu.items

Make sure you set it to a callback function - it will receive the node - if you do not want a contextmenu - invoke the callback with a falsy value.

**Comment by haobr** [comment]
Tks @vakata . But, how to hidden right-click properties, please?
