### ISSUE TITLE
How to unload children nodes

### ISSUE THREAD

**Issue by Mari0oo** [vakata/jstree#1968]
Hello guys!

I have a problem... I using ajax to load children nodes, but in case when I click option in context menu I have to unload children from the one specific node and make it as jstree-leaf.

I'm refreshing the node with refresh_node function, but it's making load_node, which is downloading first level of children and I can't stop it. 
If I make inst.refresh() then all nodes would be refreshed so it works, but if other nodes were having children, then their children also would be unloaded, which I don't want to do.
```
unload: {
                label: "Unload",

action: function (data) {
                    var inst = $.jstree.reference(node.id);
                    
                    inst.refresh_node(node);

                },
```

Do you have any ideas how to do it? 

Best regards

**Comment by vakata** [comment]
Hi,

If I understood correctly, calling ```refresh_node``` on the ```node```'s parent should do the trick.

Best regards,

**Comment by Mari0oo** [comment]
Unfortunately it's not. In my case I have large tree with many nodes with lazy loading by ajax, and these nodes have option unload in menu. And what I want to do is when one of these nodes have children use this option to "unload" them from this node and make this node jstree-leaf again. Refresh_node() parent not works, exactly do nothing at all. Refresh() tree works, but I want to unload children of just one node, not of all nodes in the tree.

**Comment by Mari0oo** [comment]
Ok, I already found a solution for this. I'm refreshing this node and returning just one element from the server, then catching loaded.jstree event and after that deleting this useless child node. 

I was can't delete child nodes without this, because this is a large tree and deleting all of them was making page freezed.

**Comment by sharpTrick** [comment]
I have noticed with the suggested solution of refreshing the parent comes with the reloading of all siblings and their open children which is both undesirable in terms of efficiency as well as ugly in terms of animation.

I propose the following solution:

    $('#jsree').on("after_close.jstree", function(e, data) {
        for (const child_id of data.node.children.slice()){
            // dictionary to ignore operations that do not need to be forwarded to server
            // useful in logic that forwards tree operations (must remove child_id after ignoring)
            ignore_ajax_request_dict['delete_node'].add(child_id)
            $("#jsree").jstree('delete_node', child_id);
        }

        data.node.state.loaded=false;
        data.node.children = true;
        $("#jsree").jstree('redraw_node', data.node);
    });
