### ISSUE TITLE
jstree function not working in Ajax success, when using with Object stringify

### ISSUE THREAD

**Issue by DeepakDhaka** [vakata/jstree#1971]
Data is in format : 
[{"id":"animal","parent":"#","text":"Animals","icon":"","a_attr":null},{"id":"device","parent":"#","text":"Devices","icon":"","a_attr":null},{"id":"dog","parent":"animal","text":"Dogs","icon":"","a_attr":null},{"id":"lion","parent":"animal","text":"Lions","icon":"","a_attr":null},{"id":"mobile","parent":"device","text":"Mobile Phones","icon":"","a_attr":null},{"id":"lappy","parent":"device","text":"Laptops","icon":"","a_attr":{"href":"www.google.com"}},{"id":"Dalmation","parent":"dog","text":"Dalmatian","icon":"glyphicon glyphicon-file","a_attr":null}]

function myAccFunc()
{
$.ajax({
	        url: "/getFolderStruct",
	        type: 'GET',
	        success: function (res){

            $("#box").html("");
	        	var objectsList = JSON.parse(JSON.stringify(res));
                        var treeHiearchy =  JSON.stringify(res);
                 
            $('#jstree').jstree({
                        'core': {
                        'data': treeHiearchy // not working
                        }
 });

	        },
	        error:function(error){ console.log(JSON.stringify(error));},
	        cache: false,
	        contentType: false,
	        processData: false
	    });

}

**Comment by vakata** [comment]
Do not stringify.
