### ISSUE TITLE
href javascript dunc

### ISSUE THREAD

**Issue by DeepakDhaka** [vakata/jstree#1975]
![capture](https://user-images.githubusercontent.com/37296529/38182860-d8262634-3659-11e8-8695-63f709176391.PNG)

on clicking of href, i have, href="javascript:showDocs();",  is not working as on clicking the link, as it just change jstree-clicked.

Kindly Assist.

**Comment by vakata** [comment]
It is all in the docs - the section is called interacting with the tree. You have to use the ```changed.jstree``` event.

**Comment by DeepakDhaka** [comment]
Hi Vakata, 

Thanks for help, this function call worked, but getting issue in getting value of id of li, though methodcall showDocs(this).

Kindly Help

**Comment by vakata** [comment]
Again - read the docs on the ```changed.jstree``` event available on jstree.com
