### ISSUE TITLE
jstree-undetermined state for selecting

### ISSUE THREAD

**Issue by wagnerfillio** [vakata/jstree#1976]
The father is in the indeterminate state.
But I want, if there is at least one child selected.
The parent is also selected.

state: selected: true

How can I do it ?

**Comment by vakata** [comment]
Disable ```three_state``` and do it manually using the ```changed.jstree``` or ```select_node.jstree``` event. Basically - when node is selected you want to gather all its parents and set their state to selected. The API functions are all there - ```data.instance.select_node(data.node.parents)``` - what you do with deselect is up to you.

**Comment by wagnerfillio** [comment]
This is what I have.

`var jstree_funcao = [];
	if ($('#jstree_funcao').find('.jstree-checkbox').length > 0) {
        jstree_funcao = $('#jstree_funcao').jstree(true).get_json('#', { 'flat': true });
    }`

**Comment by wagnerfillio** [comment]
Working!!
Thank you for your help!!
