### ISSUE TITLE
Suppress firing the changed.jstree event upon initialization

### ISSUE THREAD

**Issue by therealfekioh** [vakata/jstree#1978]
Hi, 
I was wondering when the event _changed.jstree_ is fired? 

I have a situation where the code to be executed when someone actually selects/deselcts a node, causes an error if it is executed before a map in the same page has finished loading. But the event seems to fire upon init as well?! Below my config:

```
    $(jstreeID).jstree({
        "plugins" : [ "wholerow", "checkbox", "search" ],
        "core" : {
            "expand_selected_onload" : false,
            "themes" : {
                "icons": false
            }
        }
    });
```
I have avoided the problem by ignoring the first call of the event, but maybe there is a more elegant way? Below my workaround:

```
    var firstVisit = true;
    $(jstreeID).on("changed.jstree", function (e, data) {
        if (firstVisit) {
            // Do nothing
            firstVisit = false;
        } else {
            // The actual code
        }
    }).jstree();
```
Thanks

**Comment by vakata** [comment]
It is up to you to deal with sync issues - sorry. There is no other way - jstree will fire this event if there is any initial selection to the tree. You could ignore the first event, or ignore until the map is loaded, or ignore until some other event fires first - the choice is yours and depends on your situation.

Best regards,
Ivan
