### ISSUE TITLE
add input element to node

### ISSUE THREAD

**Issue by FromTula** [vakata/jstree#1979]
Hi, I want to add input for node element.

```
<ul>
       <li>Node 1 <input type="text"></li>
</ul>
```

After click on input I get focusout from this input.

How can i add input for node?

**Comment by jhonNumpaque** [comment]
possibility you can use...
 https://stackoverflow.com/questions/9821006/creating-a-new-node-in-jstree?rq=1

**Comment by FromTula** [comment]
No, this rename input. I need additional input.
Example:

`<ul>
       <li>Node 1 <div>ENTER NEW VALUE: <input type="text" value="5"><button>ADD</button></div></li>
</ul>`

**Comment by vakata** [comment]
You should probably create a plugin for this. I believe there was one such plugin on the google groups jstree forum. This is beyond the scope of supporting jstree, so I can not help you but here is a list of sample plugins to get you started:
https://github.com/vakata/jstree/blob/master/src/misc.js
