### ISSUE TITLE
Single Node Selection With Checkbox (Individual Selection With Checkbox)

### ISSUE THREAD

**Issue by manojkumarmeda** [vakata/jstree#1980]
Hi to all, jstree concepts are very nice,  I have a query...that is already we have checkboxes selection but I want to select only which node I selected it means don't want to check the parent nodes..Even if all the child nodes are selected ..

    Please Suggest possible solution

**Comment by vakata** [comment]
Set this option to ```false```: https://www.jstree.com/api/#/?q=three_state&f=$.jstree.defaults.checkbox.three_state
