### ISSUE TITLE
It's not possible to prevent the node selection when the parent is selected (or select_all called)

### ISSUE THREAD

**Issue by bb1** [vakata/jstree#1982]
I've tried to disable the node or use the conditionalselect plugin. It is impossible for the user to directly change the selection when clicking on the affected node but by selecting the parent or using an "select all" Button he can skip all my checks.

I prepared a live demo for you to play: https://plnkr.co/edit/tcpZwVVrFDayAjIsqMFG?p=preview

My workaround would be to check on every changed selection and remove the forbidding nodes manually.

**Comment by vakata** [comment]
Check out and enable this option:
https://www.jstree.com/api/#/?q=casca&f=$.jstree.defaults.checkbox.cascade_to_disabled

As for ```select_all``` - that is an API call - jstree will not pass API calls through the same checks as user interactions. Disabled nodes are only disabled for user interactions, you can check and uncheck them programmatically.

**Comment by bb1** [comment]
Oh.. thanks a lot!

**Comment by bb1** [comment]
Wait.. this still doesn't fix the select_all()-Button.
