### ISSUE TITLE
Opened folder no longer has children when filtered in Search

### ISSUE THREAD

**Issue by mhmacleod** [vakata/jstree#1984]
Before I've opened a folder in the tree, if I search for nodes in a way that the same folder will appear in, the folder shows that it contains children as normal, and I can open it to view its subfolders as normal.
If I've opened it before a search however, then perform the same search, that same folder now appears to have no children in the search results and I can no longer view its contents.

**Comment by vakata** [comment]
Enable this option:
https://www.jstree.com/api/#/?q=matches_children&f=$.jstree.defaults.search.show_only_matches_children
