### ISSUE TITLE
Refresh_node(obj) freezes the page on large tree

### ISSUE THREAD

**Issue by Mari0oo** [vakata/jstree#1987]
Hi,

I have a problem with refresh_node() function. The tree is very large, but it shouldn't be a problem of this case because it should only send new ajax request for newest data - and it doesn't. I don't know what that function is exactly doing before it goes to the ajax function in tree configuration? At the moment it freezing page and do some strange stuff before it goes to the ajax. Any ideas how to help me?

Best regards,
Mario

**Comment by vakata** [comment]
When you refresh a node all its children are redrawn (if visible), this is probably what hangs your browser but I can not help you further without a demo.
