### ISSUE TITLE
Icon of opening of the folder for the empty folder

### ISSUE THREAD

**Issue by IhorDavydiuk** [vakata/jstree#1988]
Hello. Tell please, at addition of the empty folder and updating of the page the icon of opening of knot is added. When pressing her she disappears. What can be made that the icon of opening wasn't added to empty folders? It misleads the user that the folder not empty.
After reboot for an empty folder, an icon for the opening appears
![image](https://user-images.githubusercontent.com/30239457/38799618-9be23374-416d-11e8-9b04-c8b2994107ac.png)
After opening the nodes(The 'li' tag with an empty folder adds the class 'jstree-leaf')
![image](https://user-images.githubusercontent.com/30239457/38799650-b9b929ca-416d-11e8-8e50-f149d06414d8.png)

**Comment by vakata** [comment]
There is something wrong with your data - as you can see on all the demos this is not something jstree does wrong. I can not help you further without a demo, but this definitely is a problem with the data you pass to jstree.
