### ISSUE TITLE
Positioning issue

### ISSUE THREAD

**Issue by m0n9oose** [vakata/jstree#1989]
I have an instance of jstree with enabled types plugin:

Example:

```
0. file
1. file
2. folder
```

Now if i'm trying to replace file at position 1 there's no way to insert new file: i can remove existing item but can't insert new one to the same position.

Same problem exists if I'm trying to delete old item, create new one at position 0 and then move new item to position 1 -> `false`

**Comment by vakata** [comment]
Please provide your jstree version, also a demo would help, as I cannot understand the issue, without a demonstration. I can indeed remove a node and add a new node in its place, so any problems you might encounter are either related to the way you configured jstree, or your data. 

Please provide a small demo where I can reproduce the issue and I will reopen.

**Comment by m0n9oose** [comment]
@vakata https://jsfiddle.net/tu0frrqq/38/

this snippet has one major difference - this code does not allow to insert new node to first position too. While my code does not allow to insert a new `file` before `folder` only.

PS version 3.3.5

**Comment by vakata** [comment]
You are passing in a string, which jstree interprets as a node title. Here is the fixed example: https://jsfiddle.net/tu0frrqq/40/

**Comment by m0n9oose** [comment]
Yeah, you're right. It seems i have a different problem in my code, but it's fine in jsfiddle. Is there any way to figure out what's going on and why jstree can't insert a new to node to certain position? Maybe there's some kind of validation errors?

**Comment by m0n9oose** [comment]
It seems i've found the problem. It's not obvious, but create node node has been affected by `check_callback` function. I have a function to manage drag'n'drop:

```
function(operation, node, parent, position, more) {
    var firstFolderId = parent.children.find(function(e) { return ... });
    var firstFolderIndex = parent.children.indexOf(firstFolderId);

    /*
    ** Check new position in list: folders cannot be higher than any file within same parent
    */
    if (node.type === 'file') {
      if (position > 0 && typeof firstFolderId === 'string' && position >= firstFolderIndex) return false;
    } else if (node.type === 'folder') { // allow to move category between folders or to root
      if (position < firstFolderIndex) return false;
    } else {
      return false;
    }
  ...
  }
```

the problem is check `position >= firstFolderIndex`: if i keep `>=` then my jstree renders the right move icons but actually it doesn't allow to put file to last position before first folder. If i remove `eql` and keep just `>` then moving and create new node works fine, but in interface i can see that i can put file after first folder, but i drop this file to position after first folder nothing happens.
