### ISSUE TITLE
The contents of the folder are not displayed when the folder is found via the plugin "search"

### ISSUE THREAD

**Issue by IhorDavydiuk** [vakata/jstree#1990]
Hello, can you answer please: can I make that after searching, found folders show their contents? At the moment, only the found folders are displayed without the possibility of viewing the content in them.

**Comment by vakata** [comment]
Set this to ```true```:
https://www.jstree.com/api/#/?q=show_only_matches_chi&f=$.jstree.defaults.search.show_only_matches_children

**Comment by IhorDavydiuk** [comment]
Thank you very much for your help! You helped me a lot and it's not the first time!
