### ISSUE TITLE
Text too long. Will there be a wrapping feature?

### ISSUE THREAD

**Issue by chitgoks** [vakata/jstree#1994]
If a text width is more than the container, is there an option to wrap the text?

**Comment by vakata** [comment]
https://www.jstree.com/api/#/?q=ell&f=$.jstree.defaults.core.themes.ellipsis

**Comment by chitgoks** [comment]
hi vakata

i edited the post because it is not what i wanted. i actually modified it to see if text wrapping is supported

or do i need to create a new issue instead of reopening this?

please advise

**Comment by chitgoks** [comment]
ok got it thank you
