### ISSUE TITLE
drag and drop icon showing specific target location not visible

### ISSUE THREAD

**Issue by tmderosa** [vakata/jstree#1995]
I have jstree working and it is great.  My only issue is when a user drags a node.  You see the node and the node text as well as the red X or green check, you also see a highlighted node as the target, but you don't see the arrow or marker that specifically shows where the target will land (on a node or between a node).  This is specifically an issue if the user wants to drag a node off the root and create another root.  They basically have to guess whether their target is another node or the base.   I am doing this in salesforce.com inside of a lightning controller.  I have changed the z-index on the div containing the jstree but no help.   Also I cannot see the contextmenu when I right-click but I am less concerned about that.

Here is my code for the tree

({
    init: function (cmp, event, helper) {
		helper.getCustomerName(cmp);
    },
	scriptLoaded  : function(component, event, helper) {
        component.set("v.isjQueryLoaded", true);
        var custName = component.get("v.custName");
       var logoMaster = $A.get('$Resource.relationshipPricingIcons') + '/fwcmad210update/master.png';
       var logoRelationship= $A.get('$Resource.relationshipPricingIcons') + '/fwcmad210update/relationship.png';

        $('#jstree_demo').jstree({
          "core" : {
            "animation" : 0,
            "check_callback" : true,
           
            'data' : [
                    
                                {
                                    'id' : 'node_2',
                                    'text' : '833591431',
                                    'icon' :logoMaster,
                                    'state' : { 'opened' : true, 'selected' : true },
                                    'children' : [ { 'text' : '71357','icon' :logoRelationship }, { 'text' : '1810000123','icon' :logoRelationship }]
                                },
                                    
                                {
                                    'id' : 'node_3',
                                    'text' : '6816656679',
                                    'icon' :'jstree-file',
                                    'state' : { 'opened' : true, 'selected' : true }
                                   
                                },
                                                {
                                    'id' : 'node_4',
                                    'text' : '654564652',
                                    'icon' :'jstree-file',
                                    'state' : { 'opened' : true, 'selected' : true }
                                   
                                }
                            
                    
                ]
          },
            "dnd" : {
                    "is_draggable" : function(node) {
                        
                        if (node[0].icon.includes('master')) {
                            
                            return false;
                        }
                        return true;
                    }
                },
            
            "types" : {
                "default" : {
                  
                  max_children : 3,
                    max_depth :1
                },
                "default" : {
                  
                  max_children : 3,
                    max_depth :1
                },
            },
            
           
          
          "plugins" : [
            "dnd", 
            "state", "types", "contextmenu"
          ]
        });
        
        $("#jstree_demo").jstree(true).set_icon('node_2',logoMaster );
        $('#jstree_demo').on("move_node.jstree", function (e, data) {
            
            //if this is being onto another node, make that node a parent icon
            if (data.parent != '#'){
               $('#jstree_demo').jstree(true).set_icon(data.parent,logoMaster);
               $('#jstree_demo').jstree(true).set_icon(data.node,logoRelationship);
            }
            //if there is no parent set the icon back to regular
            else{
                $('#jstree_demo').jstree(true).set_icon(data.node,'jstree-file');
            }
            //if this is the last child being removed from a parent set the parent back to a file icon
            var prevChildren = $('#jstree_demo').jstree(true).get_children_dom(data.old_parent);
            if(prevChildren.length ==0)
            {
                $('#jstree_demo').jstree(true).set_icon(data.old_parent,'jstree-file');
            }
			component.set("v.existingRelationsMsg","There are no existing retail relationships");
            var $tree = $(this);
            $($tree.jstree().get_json($tree, {
                flat: true
            }))
            .each(function(index, value) {
                var node = $("#jstree_demo").jstree().get_node(this.id);
                if(node.icon.includes('master')){
                    component.set("v.existingRelationsMsg","");
                }
            });
         });
        
        $('#jstree_demo').on("select_node.jstree", function (e, data) {
            component.set("v.accountID",data.node.text);
            if(data.node.icon.includes('master')){
                component.set("v.masterSelected",true);
                 component.set("v.relSelected",false);
            }
            else if(data.node.icon.includes('relationship')){
                component.set("v.masterSelected",false);
                 component.set("v.relSelected",true);
            }
            
            else {
                 component.set("v.relSelected",false);
                 component.set("v.masterSelected",false);
            }
     

         });
        
        $("#jstree_demo").bind('ready.jstree', function(event, data) {
            component.set("v.existingRelationsMsg","There are no existing retail relationships");
            var $tree = $(this);
            $($tree.jstree().get_json($tree, {
                flat: true
            }))
            .each(function(index, value) {
                var node = $("#jstree_demo").jstree().get_node(this.id);
                if(node.icon.includes('master')){
                    component.set("v.existingRelationsMsg","");
                }
            });
		});

        
	},

    
})

**Comment by vakata** [comment]
I can not help you fix z-index issues - sorry. Ordering elements is something very specific to your page - make sure ```.vakata-contextmenu``` and ```#jstree-marker``` have a high enough z-index.
