### ISSUE TITLE
Selected : true using ajax

### ISSUE THREAD

**Issue by mattcollins171** [vakata/jstree#1997]
I feel that I'm going round in circles here so would appreciate some assistance.

Firstly I initialise jsTree without any data:
`$('.accessTree').jstree({
        "core" : {
             "themes" : {
                  "variant" : "large"
             },
             'multiple': false,
        },
        "checkbox" : {
             "three_state": false,
             "whole_node": false,
        },
        "plugins" : [ "wholerow", "checkbox" ]
   });`

Then when a modal is opened the data is inserted into the tree via an AJAX call that as made. Below is the code that is added into the 'success' function of the AJAX
`var folders = []
                      for(x in returnedInfo.folders){
                           if(returnedInfo.folders[x].parent == null){
                                var parent = '#';
                           }else{
                                var parent = returnedInfo.folders[x].parent;
                           }
                           if(returnedInfo.folders[x].client_upload == 1){
                                var folder = {
                                     id          : returnedInfo.folders[x].file_id,
                                     parent      : parent,
                                     text        : returnedInfo.folders[x].file_name,
                                     state       : {
                                          selected  : true
                                     },
                                }
                           }else{
                                var folder = {
                                     id          : returnedInfo.folders[x].file_id,
                                     parent      : parent,
                                     text        : returnedInfo.folders[x].file_name,
                                }
                           }
                           folders.push(folder)
                      }
                      $('.accessTree').jstree(true).settings.core.data = folders;
                      $('.accessTree').jstree(true).refresh();`

The tree is built correctly. Although, it doesn't seem to set the checkbox to ticked.

I'm using the latest version of jsTree (3.3.5) and working in Chrome.

**Comment by vakata** [comment]
```refresh``` will normally reload all data and reapply the last state, meaning that any state you have set using the data will not be applied. You can try setting the second parameter to ```true```: 
https://www.jstree.com/api/#/?q=refresh&f=refresh()
