### ISSUE TITLE
How can I drag nodes onto a random DIV?

### ISSUE THREAD

**Issue by segachann** [vakata/jstree#1998]
Hello, vakata. First please let me compliment your jsTree. Great module!

And..., I have a question as the title.
I know that I can realize similar thing using move_node.jstree event.
But, this event is for a specific DIV, right?

The below code is working in a specific DIV id:
$('div').on('move_node.jstree', function (e,data) {
    console.log("moved.");
    console.log("this is moved node.",data.node);
    console.log("parent.",data.parent);
    console.log("old_parent.",data.old_parent);
  });
but, not working between some div id and other div id.

thanks for your help.

**Comment by vakata** [comment]
If you want to use DIV to DIV drag'n'drop you have to use the low-level vakata.dnd functions. The jstree ones only work in the context of a tree. Those are not documented, but I have used them numerous times for random dnd stuff: https://github.com/vakata/jstree/blob/master/src/jstree.dnd.js#L408
