### ISSUE TITLE
Not work select_node.jstree for two jsTree 

### ISSUE THREAD

**Issue by korcstar** [vakata/jstree#2002]
I have two jsTree in same page
Each jsTree have own select_node event
<pre>
$("#tree1").jstree({...})
     .on('select_node.jstree', function (e, data) {
            // get selected node id and draw second tree with node id
            $("#tree2").jstree({...})
                   .on('select_node.jstree', function (e, data) {
                          console.log('select second tree');
                  });
});
</pre>

when i select first tree then second tree is show on the page
also second tree works as well
but when i select first tree again, only second tree's on(''select_node.jstree') works
I cannot get work of first tree select event
How can i get separate two tree's selection event?

**Comment by vakata** [comment]
You need to explicitly destroy the second tree before creating it again.

**Comment by korcstar** [comment]
Yes I know I need to destroy or refresh second tree before creating it again
But i cannot get select_node event of first tree after create second tree
It is call always second tree select_node event

**Comment by korcstar** [comment]
It works as well when i update jsTree version
Sorry for my issue and Thank you
