### ISSUE TITLE
Multiple selection is not possible

### ISSUE THREAD

**Issue by teo89** [vakata/jstree#2003]
I cannot select multiple nodes except if I press the ctrl button. My tree is configured like this.
`$scope.treeConfig =
	core:
		check_callback: true
		worker: true
		multiple: true
		themes:
			name: 'proton',
			responsive: true
		types:
			default:
			       icon: 'icon-hidden'
		plugins: [
			"types"
			"sort"
		]`
It make sense that when I click in a node to select a node and after that to click to another one and both of the nodes to remain selected. Could you please tell if I make a mistake with my configurations of the tree?

**Comment by vakata** [comment]
Use this config:
http://jsfiddle.net/2kwkh2uL/12146/

**Comment by vakata** [comment]
Yes - take a look at the conditionalselect plugin, but keep in mind you need to figure out how to deselect nodes.
