### ISSUE TITLE
Three state

### ISSUE THREAD

**Issue by centerlinemapping** [vakata/jstree#2004]
I am using the checkbox plugin and I want to select all children but not allow the parent node to be selected.  How can I achieve this functionality?  The parent should never be selectable, just the children.  I've removed the checkbox from the parent node, although when selecting all children, the parent gets selected.
Thanks for you help1

**Comment by vakata** [comment]
You can find all available options here:
https://www.jstree.com/api/#/?q=checkbox

Take a look at the cascade option, you might also want to disable the parent and take a look at the cascade_to_disabled option.
