### ISSUE TITLE
Fixed label on edit

### ISSUE THREAD

**Issue by marcossapp** [vakata/jstree#2005]
I wouldn't consider this question as an issue, but I am trying to solve a problem on edit method.
The scenario is: 
There is a tree that can have it's labels edited. These labels are formed by an ordination sequence, for example:
[ 1 - Intro ]
-----[ 1.1 - SubIntro ]
------------[ 1.1.1 - SubSubIntro ]
[ 2 - Middle ]
-----[ ... ]

So, if I edit a label, the input text shows _1 - Intro_ but I don't want allow edit this ordination, but the "real" label only ( Intro ).

Is that possible to do? Maybe append something before the "real" label...

I was thinking about a workaround, that could be a popup input text opened on onEdit event, but it's annoying for users to do this all time when editing, once the normal behavior is more efficient.

Any tips?

**Comment by vakata** [comment]
You could try adding this sample plugin to your page (and your config): 
https://github.com/vakata/jstree/blob/master/src/misc.js#L182

I believe it does exactly what you need it to do. Here is a demo:
http://jsfiddle.net/2kwkh2uL/12154/
