### ISSUE TITLE
Uncaught TypeError: a.toLowerCase is not a function

### ISSUE THREAD

**Issue by lbsfei** [vakata/jstree#2007]
hi Support:
My init data as below:
```
'data' :[{"id":"root_13","text":"7m\u00b34#\u63d0\u53d6\u8bbe\u5907","type":"root","children":[{"id":"46_num_0_accid_0","text":"tr","type":"","children":[{"id":"47_num_0_accid_0","text":"tetet","type":"","children":[{"id":"55_num_1_accid_2","text":["2\u53f7\u87ba\u4e1d"],"type":"file","children":false,"icon":""},{"id":"56_num_3_accid_3","text":["\u7279\u79cd\u87ba\u4e1d"],"type":"file","children":false,"icon":""},{"id":"57_num_0_accid_0","text":"eter","type":"","children":true,"icon":""}],"icon":""}],"icon":""}],"icon":"http:\/\/localhost:8082\/uploads\/assets\/r2.png"}]
```

Use demo to run ,I got an Error "Uncaught TypeError: a.toLowerCase is not a function".

Debug it,I found
in jstree.min.js want to add a check  :
if( typeof(a) == 'object'){ a = a[0];}

It worked very good now!
Hope is useful to you!

br/feiger

**Comment by vakata** [comment]
The text property should not be an array (as you are using), it should be a string (as documented) - this is why you get the error.

**Comment by lbsfei** [comment]
yes,
you are right.
