### ISSUE TITLE
set_id.jstree does not fire

### ISSUE THREAD

**Issue by Syndace** [vakata/jstree#2008]
Hey!

First of all, thank you (and all contributors) for this awesome library, it is a joy to use it :)

Now the problem: it seems like the set_id.jstree event never fires when using the set_id method.

This can easily be reproduced with just a few lines of code:

```JavaScript
$("#tree").on("set_id.jstree", function() {
    console.log("The id was set!"); // Never runs
});

$("#tree").on("ready.jstree", function() {
    console.log("Setting the id...");

    var jstree = $("#tree").jstree(true);

    jstree.set_id(jstree.get_node("#test"), "foo");
});

$("#tree").jstree({
    core: {
        data: {
            "id": "test",
            "text": "test",
            "children": []
        }
    }
});
```

"Setting the id..." appears in the console, the dom shows the new id, but the event does not fire.

Am I missing something?

**Comment by vakata** [comment]
You might be using an old jstree version? I believe this event was added in 3.3.0.

Here is a working demo:
http://jsfiddle.net/2kwkh2uL/12163/

If you still have issues with the latest code - let me know and I will reopen.
