### ISSUE TITLE
How to Add node dynamically with custom id

### ISSUE THREAD

**Issue by IamAmeyR** [vakata/jstree#2009]
Hello All,
I am trying to use jstree inside my angular 2 project. Now I have node js api and it fetches data on every node click of tree. 
Can you please tell me how can I call post api and add node after receiving data inside existing tree structure ?

Thanks in Advance.

**Comment by vakata** [comment]
Here is how you create a node:
https://www.jstree.com/api/#/?q=create_node&f=create_node([par,%20node,%20pos,%20callback,%20is_loaded])

As for the angular part - I can not help you with that.

**Comment by IamAmeyR** [comment]
Thank you @vakata .
