### ISSUE TITLE
show contextmenu when hover a node and hide contextmenu when leave

### ISSUE THREAD

**Issue by myidcn** [vakata/jstree#2010]
hello,  I'm using the jstree I want show contextmenu when hover a node and hide contextmenu when leave.
but i doesn't work。
the code is：
$('#tree').on("mouseover.jstree", function (e, data) {
                 $(e.currentTarget).trigger('contextmenu');
            })；
Thank you very much。

**Comment by vakata** [comment]
Make sure you trigger the event on the anchor element, not current target. Keep in mind that will be a very bad user experience (from what I imagine) - if you really need this make sure you use the mouseenter, mouseleave events attached to the jstree-anchor elements.

**Comment by myidcn** [comment]
thanks ， I have test it。it is not so good to use mouse over。
