### ISSUE TITLE
tmp.plugin is not a function

### ISSUE THREAD

**Issue by Matraxgreen** [vakata/jstree#2011]
I am trying to use jquery treeview for multiple selection for my product but when my code come to **jstree** the code gives me an error 

$('#TreeViewPopup').click(function (f) {
            debugger;
            $('#TreeViewShow').modal('toggle');
            $('#tree').jstree({
                plugins: ['sort', 'types', 'checkbox'],
                'core': {
                    'data': {
                        "url": function () {
                            return '@Url.Content("~/TechnicalService/RegisterProduct/TreeViewFull")' + '?ProductID=' + $("#SelectProductMainID").val();
                        }, "dataType": "json",
                    }
                }
            });

I have problem jstree 
it gives me  tmp.plugin is not a function error . I search google but I couldnt solve it. Pls help me to get rid of this problem . Do you have any idea to solve this?

**Comment by vakata** [comment]
Please provide more information (which version of jstree are you using) and a demo of the issue, as I can not reproduce it. Here is a starting point for a demo:
http://jsfiddle.net/2kwkh2uL/12206/

I will reopen when a way to reproduce is available.

**Comment by Matraxgreen** [comment]
Firstly Thank you so much for your response Vakata really.

I have ;
<script src="~/Scripts/jquery-1.10.1.js"></script>
<script src="~/Content/jquery-ui-1.9.2/js/jquery-ui-1.9.2.custom.js"></script>
<script src="~/Content/js/jquery-tree/jstree.js"></scrip  
bootstrap 3,0,0 version 
jstree version 3.2.1

I dont know how can I solve my problem Vataka.
 
when my debug is come here ".jstree" I take this problem ;  tmp.plugin is not a function

**Comment by vakata** [comment]
Please use the jsfiddle above so that I can reproduce the issue. 

If that is asking too much - then at least:
1) make sure you are using the **latest** uncompressed version of jstree
2) let me know which line the error is on
