### ISSUE TITLE
search plugin

### ISSUE THREAD

**Issue by loveincode** [vakata/jstree#2013]
There's a lot of data. Is there a loading when search？
The search time is very long without loading

**Comment by vakata** [comment]
All searches happen on the main thread, but those should be pretty quick as the code goes through an array of nodes, but just in case there are a couple of things you can do:
1) disable fuzzy searching
2) implement server side search if this fits your project (there is more information on how to do that on the api page).

It could be that it is not the search that is slow, but that you have a huge flat tree and you have show_only_matches enabled - if so - disable that option.

If after implementing any of the above the search is still slow - please provide a demo (or at least your full config and your jstree version) and I will try to help further.

**Comment by loveincode** [comment]
thank you! Exactly have a huge flat tree with 10000+ nodes.
