### ISSUE TITLE
How to clear the jstree checkbox cache?

### ISSUE THREAD

**Issue by samchenws** [vakata/jstree#2014]
hello,How to clear the jstree checkbox cache?I want to clear cache but i  do not know,please tell me,thank you

**Comment by vakata** [comment]
I am afraid I do not know what you mean, maybe you have enabled the ```state``` plugin - if so - remove it from your config, that is the only cache-related setting. If this is not it - please clarify and I will reopen.

**Comment by samchenws** [comment]
@vakata thank you. when I remove  ['state'] ,it  is  no cache.I'm sorry, my English is bad.

**Comment by samchenws** [comment]
@vakata hello,i has a question?
![image](https://user-images.githubusercontent.com/37535153/40633607-51525b18-6323-11e8-98ec-dbd4d6a5c50f.png)
what can i do？

**Comment by vakata** [comment]
I do not understand the question.

**Comment by samchenws** [comment]
@vakata ...oh,no.i just want to create tool in jstree.
