### ISSUE TITLE
Get position/index

### ISSUE THREAD

**Issue by frerotg** [vakata/jstree#2015]
Hi everybody and thanks a lot for your work on this plugin.

I use the DND plugin but I can not get the position or index of the element that is changed. I saw a lot of post about the index but despite my research I did not find how to get it.

Can you help me ?

Best regards
Grégory.

**Comment by vakata** [comment]
Here is the position (both old and new) in the move event (works the same for copy): 
https://www.jstree.com/api/#/?q=move_node&f=move_node.jstree
If you need it some other time (besides the event) get the node and check its position among its siblings (by getting the parent and inspecting the parent's children array).
