### ISSUE TITLE
Very slow performance on clear_search function

### ISSUE THREAD

**Issue by Mari0oo** [vakata/jstree#2016]
Hi,

I have a big jsTree and after search a lot of nodes are opened and when I want to clear the search, then page is freezed or even sometimes it get runtime script error. I noticed when I set the option search.close_opened_onclear to true as default, then it's so much faster. But I need to have opened finded nodes on clear. Do you have any ideas, how to fix that issue?

Best regards,
Mariusz

**Comment by vakata** [comment]
Unfortunately there is no solution for this - depending on how your flat your data is it may take quite some time to redraw the whole tree. This usually affects trees with at least a few thousand nodes. There will be no fix for this in v.3, v.4 which has been in progress for quite some time fixes this by having only viewport visible nodes in the DOM, but it won't be ready any time soon - I hope I will publish a beta this summer.
