### ISSUE TITLE
Script: jquery-1.7.2.min.js

### ISSUE THREAD

**Issue by wrmarquezo** [vakata/jstree#2017]
After lot of attempts using the jstree I figured out that i had to use this script (jquery-1.7.2.min.js) to get it to work. I didn't see any mention about this script in the documentation so i had to figure it out by myself. i think is important to reference this in the documentation.
Thanks

**Comment by vakata** [comment]
This is not true, jstree v.3 works with any version of jQuery (above 1.9.1). I currently use it with v.3. Maybe you are using jstree v.1 which has not been supported for years?
