### ISSUE TITLE
Get node by attributes

### ISSUE THREAD

**Issue by Yanow0** [vakata/jstree#2023]
Hello,

I'm looking for a way to get any node of my tree by his li_attr

Is it possible ? And if it is, how can I do this ?

Thank you

**Comment by evilaugust** [comment]
I just get all nodes and loop over them.

`
var someNodes =[];

tree.jstree('get_json', null, { 'flat': true }).forEach(function (node) {
            if (node.li_attr['data-blah']) {
                someNodes.push(node);
            }
});
`

**Comment by Yanow0** [comment]
Thank you ! 

I'm going to try this

**Comment by Yanow0** [comment]
I'm having a hard time trying to understand how 'get_json' works, I'm still a beginner.

```
mixerTree.get_json(null, { 'flat': true }).forEach(function (node) {
		console.log('test');
	if (node.li_attr['mid']) {
		//future code
	}
	});
```

It does not even go through the loop.

Any ideas why ?

Thanks

**Comment by evilaugust** [comment]
Try like this:

```
mixerTree.jstree('get_json', null, { 'flat': true }).forEach(function (node) {
	console.log('test');
	if (node.li_attr['mid']) {
		//future code
	}
});
```
If that doesn't work try outputting to the console the results:

`console.log(mixerTree.jstree('get_json', null, { 'flat': true }));`

That way you know what you are trying to loop over.

**Comment by Yanow0** [comment]
I already tried like this but it still shows no result

Thank you for the advice, I will try to output the results when I get back home

**Comment by Yanow0** [comment]
Ok so now I know that I was looping over an empty array. 

Do I need to do something particular on my tree to use the 'get_json' function ?
