### ISSUE TITLE
Sort all children of a node after drop

### ISSUE THREAD

**Issue by Yanow0** [vakata/jstree#2024]
Hello,

I have a quick question. I'm using 2 trees, I'm able to drop elements from tree B to tree A.

Now I want to sort all the children nodes of a parent when a new node is dropped in the parent. 

I can sort both trees at the beginning, but I can't sort them after each drop.

Is there a way to do that ?

Thank you

**Comment by vakata** [comment]
The sort will work in exactly the same way regardless of the point in time when you sort. If it does not work this means there is something wrong with your sorting code. I can not help you further without a demo - I can have a look at your code, but from the description I do not see a problem with jstree itself.

**Comment by Yanow0** [comment]
Ok thank you, then it must an error from me. I will fix my sorting code.
