### ISSUE TITLE
unique id for all nodes 

### ISSUE THREAD

**Issue by Priya08Nirmal** [vakata/jstree#2025]
Hi Vakata,

I have one query. In my project requirement is to display tree however at two levels the name of the nodes are same. Based on my understanding, to use jsTree we need all the node id's to be unique. 
Is there any way we can handle this ? 
To clarify my question please see below example -

Root ----> child 1---->child 11 ----> child 121
                                                   ----> child 122
                            ----> child 12 ----> child 121
                                                   ----> child 122

         ----> child 2 ---->child 11---->child 121
                                                   ---->child 122
                             ----->child 12---->child 121
                                                   ---->child 122

and so on............... hope I am clear with the query. 
Thanks in advance,
Priya

**Comment by vakata** [comment]
On the client side jstree either needs unique IDs or no IDs - decide which one suits you better. The point of an ID is to be unique. You can simply omit the ID and let jstree handle IDs and use a custom data property for your ID, or on the server side make sure you add a prefix or something so that your IDs are unique.

**Comment by xingguo3** [comment]
Hi Vakata, 
Although I can add a process to make sure the uniqueness of IDs, 
i still wonder how to filter duplicated IDs using jsTree Build-in features or plug-in tools. 
Could you please advise?

**Comment by vakata** [comment]
The idea behind an identifier is to be unique in the collection. If you can not produce unique IDs - omit them. You can also set core.data to a function and remove the ID property before passing the data to jstree.

**Comment by xingguo3** [comment]
thanks for your quick reply. I totally got your points. However, currently I am designing a lazy-load mode in jsTree, which means that the jsTree will load sub-nodes (ajax call) only if parent-node is click to expand. 
Thus, i am not sure whether set core.data to a function will work. 
I found that there is a plug-in feature called "unique" in jsTree, but I don't know whether it can help to filter duplicated IDs in sub-nodes  automatically. Any idea?

**Comment by vakata** [comment]
No the unique plugin does something else. You can use core.data as a function with lazy loading.

**Comment by xingguo3** [comment]
Will Try. Thanks!
