### ISSUE TITLE
option to work with raw json object?

### ISSUE THREAD

**Issue by timotheecour** [vakata/jstree#2026]
http://jsonviewer.stack.hu/ allows to pass in raw json data (without children / text fields, etc), eg:
```
{"a":[1,2,{"b":3}]}
```

which shows up as:
![image](https://user-images.githubusercontent.com/2194784/41432743-b9b2af32-6fcb-11e8-9a56-0a4a20950524.png)

is there a similar built in way in jstree or do I have to write my own raw_json_to_jstree_json (which would add children, text nodes) ?

**Comment by vakata** [comment]
jsTree only understands the two documented formats - flat or nested. You need a converter.
