### ISSUE TITLE
inconsistency on double click on the node of (larger characters )in IE 11

### ISSUE THREAD

**Issue by kala15** [vakata/jstree#2027]
I have an inconsistency on double click in browser only in IE 11
when i double click on the tree no the width is shifted towards left for longer contents , expand(+) is  hidden and deletion of subgroup is not possible on double click of node (longer characters)   
![image](https://user-images.githubusercontent.com/40287061/41451211-6a4f11ec-7089-11e8-85e8-d98cf414daa3.png)
before double-click
![image](https://user-images.githubusercontent.com/40287061/41451233-7b9772be-7089-11e8-8048-53e44fa72374.png)
after double-click

**Comment by vakata** [comment]
This is because the node is focused, this is how focus works in IE. I will not change this as it is necessary for screen readers, accessibility, etc.

**Comment by Sarath-Raja** [comment]
Is there any workaround to counter-affect the focus behavior in IE?
