### ISSUE TITLE
populate jstree from json

### ISSUE THREAD

**Issue by sadhnaprajapati** [vakata/jstree#2029]
i want to populate jstree from flat json on the basis on level.

{id: "Delhi", text: "Delhi", level: 0, parents: Array(0)}
{id: "Eigen", text: "Eigen", level: 1, parents: Array(1)}
{id: "Sensenuts",text: "Sensenuts", level: 1, parents: Array(1) }
{id: "Janakpuri", text: "Janakpuri", level: 2, parents: Array(2)}
{id: "Vikaspuri",text: "Vikaspuri", level: 2, parents: Array(2)}

**Comment by vakata** [comment]
The supported formats are well documented. You will have to convert your data to one of the supported formats.
