### ISSUE TITLE
DND Problem with parenst

### ISSUE THREAD

**Issue by dpablos95** [vakata/jstree#2032]
Hello, I have a problem rigth now. I´m trying to use DND plugin and I´m capable of moving my folders into anothers folders and files can´t be inside other files. The thing is that my JSON shows the parent of the folder and when I drop it in another folder, I would like that the file could change the parent but it keeps the same parent as the one before. What can I do to understand that?

**Comment by vakata** [comment]
jstree will not change anything in your original data, and you need to update any custom logic you have yourself. If I misunderstood - please provide a demo with a detailed description and I will reopen.

**Comment by dpablos95** [comment]
[vakata.docx](https://github.com/vakata/jstree/files/2139618/vakata.docx)
Please, can you help with this.
