### ISSUE TITLE
Is there any way to tell jstree add children ul element to DOM even if parent nod is not expanded?

### ISSUE THREAD

**Issue by mohammad3n** [vakata/jstree#2033]

**Comment by vakata** [comment]
You can always use ```load_node```

**Comment by mohammad3n** [comment]
This is a function right? I want to know if there is a configuration to set to true when initializing the tree.

**Comment by vakata** [comment]
I see what you mean. No, this is not possible - jstree only keeps visible nodes in the DOM. You could give this untested plugin a try, but I do not guarantee it will work: https://github.com/vakata/jstree/blob/master/src/misc.js#L350

**Comment by mohammad3n** [comment]
Thanks a lot.
