### ISSUE TITLE
SyntaxError: '#' is not a valid selector

### ISSUE THREAD

**Issue by nodeticswww** [vakata/jstree#2034]
I'm using JSTree 3.3.5 in one of my WebExtensions. With unknown data input (user's data, don't know exactly what it contains) and calls:

$("div#tree").jstree(true).settings.core.data = treedata;
$("div#tree").jstree(true).refresh();

There's an Exception "SyntaxError: '#' is not a valid selector" with trace:

![jstree-problem](https://user-images.githubusercontent.com/33017518/42097687-6c36bd0a-7bc1-11e8-8d9a-3869503e7a56.JPG)

Any idea what could cause this and how to fix it?

**Comment by vakata** [comment]
Make sure the data you provide has valid IDs - by valid I mean - something you can use as an ID attribute on a HTML tag. jsTree does its best to clean up and support various input but "#" as an ID will not work.

**Comment by nodeticswww** [comment]
Yep. Nodes have valid IDs and none of the nodes has '#' as an ID. This has happened only with one user AFAIK - for everyone else the code is working fine. So it's some kind of weird corner case.

**Comment by nodeticswww** [comment]
Figured it out. One of the nodes had an empty string "" as an id. It would be useful if JSTree threw a descriptive Exception saying that empty ids are not valid and would give the node data as part of the Exception to help track it down.
