### ISSUE TITLE
Search and ajax 

### ISSUE THREAD

**Issue by AtHerGloaguen** [vakata/jstree#2035]
Hello,
 I can not get the ajax search plugin working.

I get a good data that contains the search, but it does not integrate.

here is the starting json:
{"id": "00000000000000000000", "text": "POISSY Ferrage", "children": [{"id": "BAT5", "text": "Building 5", "children"
: True, "state": { "ouvert": false, "disabled": false, "selected": false}}, { "id": "LIBRARY", "text": "library
 installation A08 \ u0026 A7 "," children ": true," state ": {" opened ": false," disabled ": false," selected ": false
}}, {"id": "LOC_MEDIAMETRY", "text": "Loc mediametrie Do not delete", "icon": "jstree-file", "state": {"opened"
: False, "disabled": false, "selected": false}}, { "id": "DV2MOTE5", "text": "DV2MOTE5", "children": true, "state"
: {"opened": false, "disabled": false, "selected": false}}, {"id": "BAT3", "text": "Building 3", "children": true
, "State": { "ouvert": false, "disabled": false, "selected": false}}, { "id": "LOC_STATISTIQUES", "text": "Location
 for statistical calculations "," icon ":" jstree-file "," state ": {" opened ": false," disabled ": false," selected "
: false}}, {"id": "MECA", "text": "MA machining", "children": true, "state": {"opened": false, "disabled": false, "selected"
: false}}, {"id": "COMAPISAIG", "text": "PLC-SAIG Com Monitor", "children": true, "state": {"opened": false
"Disabled": false, "selected": false}}, { "id": "MSMLUSIN", "text": "MSMLUSIN", "children": true, "state": { "ouvert"
: False, "disabled": false, "selected": false}}, { "id": "DV2CULA5", "text": "DV2CULA5", "children": true, "state"
: { "Ouvert": false, "disabled": false, "selected": false}}, { "id": "DDCETEST", "text": "DDCETEST", "children": true
, "State": { "ouvert": false, "disabled": false, "selected": false}}, { "id": "CONVEYORS", "text": "Convoyeurs_PY_Bt3_Bt5"
, "Children": true, "state": { "ouvert": false, "disabled": false, "selected": false}}, { "id": "TEST1", "text": "TEST1"
, "Children": true, "state": { "ouvert": false, "disabled": false, "selected": false}}], "state": { "ouvert": true
"Disabled": false, "selected": false}}

the result of the research:

{"id": "00000000000000000000", "text": "POISSY Ferrage", "children": [{"id": "MECA", "text": "MA machining", "children"
: [{"id": "DPTM", "text": "DPTM SECTOR", "children": [{"id": "MA", "text": "MA SUB AREA", "children": [{ "id"
: "USMA", "text": "WORKSHOP USMA", "children": [{"id": "GRP_11", "text": "GROUP 11", "children": [{"id": "BOITIER_COURONNE"
, "text": "Crown case", "children": [{"id": "LIG_BOITIER_EBAUCHE", "text": "Rough case line", "children"
: [{"id": "OP_005be", "text": "OP 5", "children": [{"id": "5007086% 100", "text": "MEDIUM 5007086", "icon": " jstree-file "
, "State": { "ouvert": true, "disabled": false, "selected": false}}], "state": { "ouvert": true, "disabled": false
, "Selected": true}}], "state": { "ouvert": true, "disabled": false, "selected": true}}], "state": { "ouvert": true
"Disabled": false, "selected": true}}], "state": { "ouvert": true, "disabled": false, "selected": true}}], "state"
: { "Ouvert": true, "disabled": false, "selected": true}}], "state": { "ouvert": true, "disabled": false, "selected"
: True}}], "state": { "ouvert": true, "disabled": false, "selected": true}}], "state": { "ouvert": true, "disabled"
: False, "selected": true}}], "state": { "ouvert": true, "disabled": false, "selected": true}}

javascript:
`search: {
             show_only_matches: true,
             show_only_matches_children: true,
             case_insensitive: false,
               ajax: {
                 url: "_url",
               
                success: function (new_data) {
                    console.log ('search tree:' + new_data);
                     return new_data;
                }
                
                }
         
             }

$ (".search-input"). keyup (function () {

        var searchString = $ (this) .val ();
        console.log (searchString);
        if (searchString.length> 2) {

        $ ('# tree'). jstree (true) .search (searchString);

        }
    });`
 

would you have a solution?

thank you

**Comment by vakata** [comment]
Read the docs on the search plugin - you are supposed to return an array of parent IDs that need to be loaded so that the matching nodes will be available to jstree.

**Comment by AtHerGloaguen** [comment]
thank you for your reply,
I got lost in the tests.
however, when I go back a single table, the concerned node opens and is selected.
but when there are two or more paintings, nothing happens.
ex:

```
> [[ "00000000000000000000", "MECA", "DPTM", "MA", "REMA", "GRP_7", "RECEPT_R3", "RECEP_R3_BLANC", "OP_030r3b", "2,948,500
> % 050 "], [" 00000000000000000000 "," MECA "," DPTM "," MA "," USMA "," GRP_11 "," BOITIER_COURONNE "," LIG_BOITIER_EBAUCHE "
> "OP_070be", "5005283% 100"], [ "00000000000000000000", "MECA", "DPTM", "MA", "USMA", "GRP_11", "BOITIER_COURONNE"
> "LIG_BOITIER_EBAUCHE", "OP_040be", "5,005,282 100%"]]
```

best regards

**Comment by vakata** [comment]
A single array, not an array of arrays. Just as I showed above.

**Comment by vakata** [comment]
I am afraid I have no idea what you mean - jstree can visualize one tree at a time. Follow the required format.
