### ISSUE TITLE
Can not Make Root Node !!!

### ISSUE THREAD

**Issue by danielk68** [vakata/jstree#2036]
hi 
i can not create root node. i use this code but not working for me 
`$('#jstree').jstree(true).create_node('#', {'id': 'blah', 'text': 'new node', 'type': 'folder'}, 'last', function() {
                                                console.log('done');
                                            });`
or use this code
`$('#jstree').jstree(true).create_node(null, [id = "R3", parent = "#", text = "R3"], 'last', "createRootNode", true)`

**Comment by vakata** [comment]
Make sure you have ```core.check_callback``` set to ```true```, so that changing the structure is allowed. If this is not it - please share your config or provide an example so that I can help.
