### ISSUE TITLE
create_node event cant be binded after unbind

### ISSUE THREAD

**Issue by scudr** [vakata/jstree#2037]
I want to add some nodes in my jstree without using the contextmenu, just using a normal button.  
I added this line to achieve this:  $("#myTree").jstree('create_node',  $("#myTree"), "last", nodeArray); This line creates only a 'New node' and triggers the binded event ('create_node.jstree'). In this event i removed the 'New node' and add all nodes contained in my array as following:
     for (i = 0; i < newNodes.length-1; i++) {
                newNode = nodeArray[i];
                data.inst.create_node($("#myTree"), "last",newNode);
            }
but in order to achieve this i had to add $("#mytree").unbind("create_node.jstree") before calling the above loop and at the end i tried to bind the event again  $("#myTree").bind("create_node.jstree"). This for the case i clicked again in this button. but after clicking the button again, it only creates a  'New node'. What i expected is to have the same list with all the nodes. But binding again the tree doesnt seem to work.  I would appreciate any help. Thanks in advance :)

**Comment by vakata** [comment]
Make sure you only unbind your own event handlers - not all handlers, as jstree has its own handlers too. Anyway it seems to me you are not working with events properly - .bind('create_node.jstree') will not do anything without a second argument.
If this is not it - please provide a demo (jsfiddle perhaps) and I will reopen.

**Comment by scudr** [comment]
I will try to explain it here (if it is not enough i will try to achieve it with jsfiddle):

This is the definition of my tree ( this tree is by the way in a Jquery dialog)
**$("#myTree").jstree({  ......
        }).bind("create_node.jstree", function (event, data) {**

           var nodesArray =  data.args[2];

           $("#myTree").unbind("create_node.jstree");

         for (i = 0; i < nodesArray .length; i++){
          // after calling the next line, the bind("create_node,jstree") will be called again and then i get into 
            an endless loop. That's why i added the above unbind
             data.inst.create_node($("#myTree"), "last", nodesArray [i]);
 
        }
        
Then i tried to bind this event again, but i click on the button, it will be created a 'New Node'
        $("#myTree").bind("create_node.jstree");

       **});**

Somewhere else in this Jquery dialog i have a button, which i click to add some nodes to the my jstree 
**$("#addPrivateGroup").live('click', function () {**

This is the variable which contains all my nodes
var nodesArray= [............................];

Here i try to add a node on the tree, after calling this line, the **.bind("create_node.jstree", function (event, data) {** from above will be called.
$("#myTree").jstree('create_node', $("#myTree"), "last", nodesArray);

**});**

I wanted to use the same instance of my tree to create the nodes, in order to improve the performance, because when adding more than 100, the performance was very poor, but it was my fault, because i was searching on the DOM my 'Jstree' for every node i added. What i wrote above improved the performance significantly. But my problem was to bind again. I aprecciate your help. Thank you very much
