### ISSUE TITLE
How to implement initialization, when the child nodes are not all selected, the parent node status is half selected?

### ISSUE THREAD

**Issue by tenglongwentian** [vakata/jstree#2040]
How to implement initialization, when the child nodes are not all selected, the parent node status is half selected?

**Comment by vakata** [comment]
If the child nodes are loaded - the parent status will be set automatically. If the children are loaded on demand you can force the parent in an indeterminate state by using: ```state : { undetermined : true }``` as documented: https://github.com/vakata/jstree#the-required-json-format
