### ISSUE TITLE
create_node problem

### ISSUE THREAD

**Issue by Yodaac** [vakata/jstree#2043]
Hello,
I have a weird problem when I try to create  a node on a tree, and I'm not sure why...
The demo file with the code doesn't contains such example, i.e. adding a node by clicking on a button.

The online demo (the one with gree trees https://www.jstree.com/demo/) doesn't work , when I click on create button, it return a flase value when creating, and nothing is created:

```
function demo_create() {
	var ref = $('#jstree_demo').jstree(true),
	sel = ref.get_selected();
	if(!sel.length) { return false; }
	sel = sel[0];
	sel = ref.create_node(sel, {"type":"file"}); // sel equals false here
	if(sel) {
		ref.edit(sel);
	}
};
```

What is weird is that it works with context menu just fine.
Problem only happens when trying to add a node with a button.

I'm using the 3.3.5 version of jstree.min.js with jquery 3.3.1.min.js.
I have the problem in both firefox and chrome, both up-to-date.
Any clue?

Thanks.
Y.

**Comment by Yodaac** [comment]
Hum, I decided to log last_error() right after I try to create a node.
There is an error:

User config for core.check_callback prevents function: create_node

Y.

**Comment by vakata** [comment]
I have no idea what you mean. Here is a demo using 3.3.5:
http://jsfiddle.net/2kwkh2uL/14148/

Please modify so that I can reproduce the issue and help you. Until then I am closing this.

**Comment by Yodaac** [comment]
Please, see this JsFiddle:
https://jsfiddle.net/yoda72/8c96hzm2/2/

Also, please, enable chrome CORS extention: https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi/related, otherwise you will get a no 'access-control-allow-origin' javascript error, since I get data from remote http://jstree.com server .

Y.

**Comment by vakata** [comment]
You have explicitly set that the root node can have only one child (types plugin) and you are trying to add a second one.

**Comment by Yodaac** [comment]
You are right, sorry I'm new with fidle, and it didn't saved my latest code.
Please, check this one:
https://jsfiddle.net/yoda72/8c96hzm2/

Thanks,
Y.

**Comment by vakata** [comment]
Once again - I believe any problems you may have are based on your types config. 

Please provide a less complicated demo:
 - no chrome plugins - remove the AJAX call by including node data directly in the core.data property
 - no specific selection - if a node needs to be selected - use the state.selected property to preselect it 

This is the only way that I can help you - provide a simple way to reproduce the issue.

**Comment by Yodaac** [comment]
Hello,
I removed types.
https://jsfiddle.net/yoda72/8c96hzm2/8/

It's working now.
Note that the code of the previous fidle, is the code extracted from jstree web site:
https://www.jstree.com/demo/

Thanks.
Y.
