### ISSUE TITLE
copy_node strange...

### ISSUE THREAD

**Issue by livefrugally** [vakata/jstree#2045]
When copy_node from other tree and  nodes to copy has complex structure, 
copy_node called twice times.

It creates(new copied) node in order the deepest depth first. 

---------------------------------------------------------------------------
Node 1 (selected to copy, level 1) 
　ㄴ-----Node 1-1 ( level 2...)
 　　　　　 ㄴ-------Node 1-1-1 (level 3...)
 　　　　　 ㄴ-------Node 1-1-2
 　　　　　 ㄴ-------Node 1-1-3
　ㄴ-----Node 1-2
　ㄴ-----Node 1-3
----------------------------------------------------------------------------
it copy level 3 before level 2 (I didn't use sort plugin)

I want to copy nodes like flat JSON order, the following order.

Node 1
Node 1-1
Node 1-1-1
Node 1-1-2
Node 1-1-3
Node 1-2
Node 1-3

what should I do?

**Comment by vakata** [comment]
Please provide an example (feel free to use this fiddle as a base: https://jsfiddle.net/8c96hzm2/10/)  so that I can help.
