### ISSUE TITLE
about 'select_node'

### ISSUE THREAD

**Issue by qianqian05723** [vakata/jstree#2046]
code : $(selectBoxId).find(".jstreeSingleTabDept").jstree('select_node', selectedIdArray);   when i use this to select large nodes ,the webpage stop response,maybe too many datas, do you have a better way to do it

**Comment by vakata** [comment]
This is the only way to properly select nodes, just make sure selectedIdArray contains only the IDs (without a ```#``` prefix). You could also speed things up by not firing the ```changed.event``` and preventing opening of the nodes:
https://www.jstree.com/api/#/?q=select_node&f=select_node(obj%20[,%20supress_event,%20prevent_open])
