### ISSUE TITLE
Change the JSON information after dragging and dropping

### ISSUE THREAD

**Issue by dpablos95** [vakata/jstree#2049]
Hello, here is my array called jsondata

var jsondata = [
           { "id" : "Color palette", "parent" : "#", "text" : "Here is the Color Palette"},
           { "id" : "Colors", "parent" : "Color palette", "text" : "Here are the colors" },
           { "id" : "Red", "parent" : "Colors", "text" : "Red","type":"file" },
           { "id" : "Yellow", "parent" : "Colors", "text" : "Yellow","type":"file" }

When I drag and drop a node, for instance, I move the Yellow Node and I dropped beside "Colors", the new Json should be

var jsondata = [
           { "id" : "Color palette", "parent" : "#", "text" : "Here is the Color Palette"},
           { "id" : "Colors", "parent" : "Color palette", "text" : "Here are the colors" },
           { "id" : "Red", "parent" : "Colors", "text" : "Red","type":"file" },
           { "id" : "Yellow", "parent" : "**_Color palette_**", "text" : "Yellow","type":"file" }

but the value continues, The parent does not change. 

How can I change and update the jsondata and change the value when I drag and drop in another parent.

THANK YOU SO MUCH

**Comment by XelaNimed** [comment]
Hello @dpablos95 
With such questions it is better to address to StackOverflow. You brought little information and it is very difficult to understand where you can have a problem. I advise you to create a new question on StakOverflow and publish a link to it here.

Have not you tried using it like that?
```js
$('jstree.selector').jstree(true).get_json("#", {flat: true});
```

**Comment by vakata** [comment]
@XelaNimed pointed you in the right direction - use ```get_json```

**Comment by dpablos95** [comment]
I have this code 

var data = "text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(jsondata));
var a = document.createElement('a');
a.href = 'data:' + data;
a.download = 'data.json';
a.innerHTML = 'download JSON';

var container = document.getElementById('container');
container.appendChild(a);

and with that I download the .json file. But, when I drag and drop in another place, the .json file does not change at all.

**Comment by vakata** [comment]
This is irrelevant - as @XelaNimed already said - instead of ```jsondata``` use ```$('#your-tree').jstree(true).get_json()```
