### ISSUE TITLE
Can't find way to set custom key name for children

### ISSUE THREAD

**Issue by sns2009** [vakata/jstree#2052]
jstree is created to visualize tree data, almost always from some API. How can I specify children key name to my custom?

**Comment by vakata** [comment]
Use ```core.data``` as a callback function, make your API call, convert the data to the required structure and pass it along to jstree. Check the homepage of this repo for docs on how to use ```core.data``` as a function.

v.4 will have an option to configure those fields, but it is still in development.

**Comment by sns2009** [comment]
ok, thanks
