### ISSUE TITLE
Toggle between all three visual states upon click for parent nodes .

### ISSUE THREAD

**Issue by WaheedAsghar32** [vakata/jstree#2053]
Hello,

Currently when I click on a parent node it toggles b/w checked and unchecked . but I want it to go from Unchecked to Undetermined to checked and then back to unchecked . 

is above possible ? if yes please guide me on this .

**Comment by vakata** [comment]
No, this is not possible - clicking the parent changes its state - which is either checked or not. The undetermined state depends on the state of the children - they need to be partially selected. So no - it is not logically possible to have the node in undetermined state after clicking on it.
