### ISSUE TITLE
create_node returns true(boolean) instead of created node id.

### ISSUE THREAD

**Issue by wonsuc** [vakata/jstree#2055]
If I call `create_node` with closed node, it successfully create new node.

However it returns `true` value not new `node id`.

It only happens if I call this method with closed node which is not loaded children data yet.

One more weird behavior is it returns `node id` since next calls. Only first call of `create_node` with closed node returns `true`.

Should I always open the node every time if I want to create new node under of it?

I tried to search similar issue, but I couldn't. Please let me know if it is duplicated.

**Comment by vakata** [comment]
This is normal and expected behavior - there is no way for jstree to return the node ID as the parent should first be loaded and opened - which I guess in your config is an async operation. In this case - listen for the create_node.jstree event, or use the callback parameter to obtain the new ID.
