### ISSUE TITLE
Adding an option to update the parent ID on DnD

### ISSUE THREAD

**Issue by XelaNimed** [vakata/jstree#2056]
Hello.
I know that the plugin does not change the data source. At the moment I'm doing this myself, but it's very difficult to do without knowing the plugin at a very good level. Currently, when you move a node from one element to another, the visual representation changes and it is displayed correctly when calling get_json, but the data itself does not change. It is possible that this has not been realized so far for some reason, but in my opinion this is a very necessary opportunity. Maybe it makes sense to implement this behavior and include it in the plugin's settings when using JSON static data?

**Comment by vakata** [comment]
No, this will not be included. For most use cases the data is an external source which can not be modified. In the rare cases when a JSON object is used jstree will not touch the object, as that could have many side effects.

It is best for a library to keep to itself and only preserve its own internal state.

You can very easily keep any object you may have in sync by listening for any events that modify the structure and call ```get_json```:
```
// add any other events you may need
$('#tree').on('create_node.jstree rename_node.jstree delete_node.jstree move_node.jstree copy_node.jstree', function (e, data) {
  YOUR_VAR = data.instance.get_json();
});
```
