### ISSUE TITLE
Lazy load and search with massload

### ISSUE THREAD

**Issue by Zarrdex** [vakata/jstree#2057]
Hi; 
Not sure if this is supposed to do this, but i thought i would ask. 

I am using lazy load, to load the nodes when the user requests, as the tree could become quite large.

Now, whilst searching through the list, this calls the mass upload function passing though the list of parent ids as the nodes might not exist in the DOM (not sure why i have to pass through the parent ids but it seems to want that instead of the id of the node searched node). 

Next in the Mass upload, i would have expected, that i could return all nodes (including the parents right up to the root) that have been defined in the search list. 

now here is the issue, if i return all the nodes that is requested, Jstree just bombs out and shows no data. 
but if I only return the root node, this will call my lazy load function, and will complete satisfactory, showing the correct nodes highlighted after search. 

this i feel is completely wrong, as I would expect that the json.data coming from the mass Upload should 
override the current tree, and it shouldn't have to call the lazy load function. 

my data structure using the alternative Json format, 

           List<TreeNode> treeNodes= new List<TreeNode>()
           {
                new TreeNode { Id="node1" , Text="World", Parent="#",   Children=true },
               new TreeNode { Id="node2" , Text="Site B", Parent="node1", Children=true },
               new TreeNode { Id="node3" , Text="Site A", Parent="node1",  Children=true },
               new TreeNode { Id="node4" , Text="Area C", Parent="node2", Children=false },
               new TreeNode { Id="node5" , Text="Area B", Parent="node2",  Children=true },
               new TreeNode { Id="node6" , Text="Area A", Parent="node2", Children=false },
               new TreeNode { Id="node7" , Text="Area A", Parent="node3",  Children=false },
               new TreeNode { Id="node8" , Text="Area B", Parent="node4",  Children=true },               
               new TreeNode { Id="node9" , Text="Department A", Parent="node5",  Children=false },
               new TreeNode { Id="node10" , Text="Department B", Parent="node5",  Children=false },
               new TreeNode { Id="node11" , Text="Department C", Parent="node5",  Children=false },
               new TreeNode { Id="node12" , Text="Department B", Parent="node8",  Children=false },
               new TreeNode { Id="node13" , Text="Department A", Parent="node8",  Children=false }
            };

My js tree initialiser
            var to = false;
            $('#demo_q').keyup(function () {
                if (to)
                {
                    clearTimeout(to);
                }
                to = setTimeout(function () {
                    var v = $('#demo_q').val();
                    $('#ultree').jstree(true).search(v);
                }, 250);
            });

            $('#ultree').jstree({
                "core": {
                    "animation": 0,
                    "check_callback": true,
                    'force_text': true,
                    "themes": { "stripes": true },
                     'data': {
                        'url': '@Url.Action("GetLazyLoadNodes", "Home")',
                        'data': function (node) {
                            return { 'id': node.id };
                        }
                    }
                },
                "search": {
                    // As this has been a common question - async search
                    // Same as above - the `ajax` config option is actually jQuery's AJAX object
                    "ajax": {
                        "url": '@Url.Action("GetSearchNodes", "Home")'
                    }
                },
                "massload": {
                    url: '@Url.Action("GetMassload", "Home")',
                    "data": function (ids) {
                        return { "ids": ids.join(',') };
                    }
                },
                "plugins": ["massload", "search", "wholerow"]           
            });

process:
> Load page with only root showing
> enter text in search box e.g. Area
> call GetSearchNodes which returns "node1","node2","node3"
> Call MassLoad 
if I return 
        List<TreeNode> treeNodes= new List<TreeNode>()
           {
                new TreeNode { Id="node1" , Text="World", Parent="#",   Children=true },
            };

Works ok but calls Lazy load on all nodes till we get to the correct node(s).

else if I return 

The full tree with the searched nodes included
        List<TreeNode> treeNodes= new List<TreeNode>()
           {
                             new TreeNode { Id="node1" , Text="World", Parent="#",   Children=true },
               new TreeNode { Id="node2" , Text="Site B", Parent="node1", Children=true },
               new TreeNode { Id="node3" , Text="Site A", Parent="node1",  Children=true },
               new TreeNode { Id="node4" , Text="Area C", Parent="node2", Children=false },
               new TreeNode { Id="node5" , Text="Area B", Parent="node2",  Children=true },
               new TreeNode { Id="node6" , Text="Area A", Parent="node2", Children=false },
               new TreeNode { Id="node7" , Text="Area A", Parent="node3",  Children=false },
               new TreeNode { Id="node8" , Text="Area B", Parent="node4",  Children=true }, 
            };
or 
The full tree with the searched nodes excluded
        List<TreeNode> treeNodes= new List<TreeNode>()
           {
               new TreeNode { Id="node1" , Text="World", Parent="#",   Children=true },
               new TreeNode { Id="node2" , Text="Site B", Parent="node1", Children=true },
               new TreeNode { Id="node3" , Text="Site A", Parent="node1",  Children=true },
            };
this either does not update the JSTree or only shows 1 node under the root node 

Any help would be appreciated, just in case i have not set-up it up correctly

**Comment by vakata** [comment]
The massload call expects a specific response - an object where there is a key for each requested ID and the value is the children of that node - basically - grouping the normal responses in a single object.

So for example if you get a request for IDs 1,3 and 50 you should return something like:
```
{
  "1" : [{"id":2,"text":"child of 1"}],
  "3" : [{"id":4,"text":"child of 3"},{"id":5,"text":"child of 3"}],
  "50" : [{"id":51, "text":"child of 50"}]
}
```

I hope this clears things up.

**Comment by vakata** [comment]
Sorry, please provide the actual JSON responses or a demo. The server side code is not of much use to me.

**Comment by Zarrdex** [comment]
List<TreeNodeSearch> xxx = new List<TreeNodeSearch>
        {
             new TreeNodeSearch
             {
                 Id = "1",
                 Text = "World",
                 Children = new List<TreeNodeSearch>
                 {
                     new TreeNodeSearch { Id="2", Text="Site B" }, new TreeNodeSearch { Id = "2", Text = "Site A" },
                 }
             },
            new TreeNodeSearch
             {
                Id = "2",
                Text = "Site B",
                Children = new List<TreeNodeSearch>
                {
                    new TreeNodeSearch { Id="4", Text="Area C" },
                    new TreeNodeSearch { Id = "5", Text = "Area B" },
                    new TreeNodeSearch { Id = "6", Text = "Area A" },
                }
             },
            new TreeNodeSearch
             {
                Id = "3",
                Text = "Site A",
                Children = new List<TreeNodeSearch>
                {
                    new TreeNodeSearch { Id="7", Text="Area A" },
                    new TreeNodeSearch { Id = "8", Text = "Area B" },
                }
             },

        };

Equates to 

{
  "1" : [{ Id="2", Text="Site B" }, { Id = "2", Text = "Site A" }],
  "2" : [{ Id="4", Text="Area C" },{ Id = "5", Text = "Area B" },{ Id = "6", Text = "Area A" }],
  "3" : [{ Id="7", Text="Area A" },{ Id = "8", Text = "Area B" }]
}

**Comment by vakata** [comment]
This is not valid JSON, I assume you are sure this is the actual response? 
What is this body in response to - what did jstree request. Sorry about all the questions but I can't help you without the full picture. There is nothing wrong with the functionality itself as I use it on a number of systems with hundreds of daily users, so I am pretty sure it works. 
My guess is there is something wrong with the data and/or the request.

**Comment by Zarrdex** [comment]
sorry, I forgot some formatting changes. My mistake
{
"1" : [{ "id":"2", "text":"Site B" }, { "id":"3", "text":"Site A" }],
"2" : [{ "id":"4", "text":"Area C" },{ "id":"5", "text":"Area B" },{ "id":6, "text":"Area A" }],
"3" : [{ "id":"7", "text":"Area A" },{ "id":"8", "text":"Area B" }]
}
but this is based on (i am guessing and its not clearly defined)
[
"ParentId" : [{ "id":"child id", "text":"child text", children :true/false??? can i add this  }],
"ParentId" : [{ "id":"child id", "text":"child text"  },{ "id":"child id", "text":"child text"  }],
]

**Comment by Zarrdex** [comment]
Hi Vakata;

I am using jsTree 3.3.5 in a MVC Core project

Using the following plugins  massload, search, and wholerow  

When the page first loads, it goes off to the lazy-load function and returns the root node, when I click on the expand this uses the lazy-load function to load the next level, which is working great. 

If i have expanded all the nodes, and search this just searches the dom elements and expands correctly.

But, if i have not expanded any nodes and search, for "Area" this calls the search function which returns a array of parent id's  ["1","2","3"] ["(root)","child of root","child of root"]

This list of id's get passed to the Massload function in which I return as per your specification
{
"1" : [{ "id":"2", "text":"Site B" }, { "id":"3", "text":"Site A" }],
"2" : [{ "id":"4", "text":"Area C" },{ "id":"5", "text":"Area B" },{ "id":6, "text":"Area A" }],
"3" : [{ "id":"7", "text":"Area A" },{ "id":"8", "text":"Area B" }]
}
now what is shown on the screen is


![treenodesearchexample](https://user-images.githubusercontent.com/20085018/43385652-301eca8a-93d9-11e8-92c6-676d8a2b3640.png)

As you can see from the image, we are missing the text from the first child node, as well as we are missing entirely the second child node. plus, Area B has child nodes, which is unknown in this image. 

Although if I only returned the following on MassLoad
{
"1" : [{ "id":"2", "text":"Site B" }, { "id":"3", "text":"Site A" }],
}
This, will call the lazy load function for each of the searched ids excluding the already opened node (root) ["2","3"] and produces what is expected. 

Can you help me? i.e. Am i missing a configuration setting

Also, why can't i return the values using your new json format {id,text,parent,children=true/false};
As, well as why i can't return all the nodes for the search, as that would mean i could return the full searched tree results, and all your code would need to do is present it, instead of have to run the lazy-load function
