### ISSUE TITLE
Need Help in JsTree

### ISSUE THREAD

**Issue by mayankbha** [vakata/jstree#2058]
I am using jstree. My requirement is I need to get all parents and children of selected node and make them selected. It should work vice versa. I am using checkbox plugin.

I am using below code

`$("#testing").jstree({
				'plugins': ['checkbox'],
				"checkbox": {
					"keep_selected_style" : false,
					"three_state" : false,
					"cascade" : "up",
				},
				"core" : {
					"multiple" : "on",
					"animation" : 250,
					//"data" : result,
					"data" : [{"text":"func_extensions_job","children":[{"state":{"opened":true,"selected":true},"text":"CodiacSDK.NewModule.dll;extensionCreatePre;","children":[{"state":{},"text":"CodiacSDK.NewModule.dll;extensionInquirePost;","children":[{"state":{},"text":"CodiacSDK.JavaScriptWrapper.dll;UnitValues::extensionCreatePre;","children":[]},{"state":{},"text":"CodiacSDK.JavaScriptWrapper.dll;UnitValues::extensionDeletePre;","children":[]}]},{"state":{"opened":true,"selected":true},"text":"CodiacSDK.NewModule.dll;extensionExecutePost;","children":[{"state":{"opened":true,"selected":true},"text":"CodiacSDK.PythonWrapper.dll;UnitValues::extensionInquirePre;","children":[]},{"state":{},"text":"CodiacSDK.PythonWrapper.dll;UnitValues::extensionExecutePre;","children":[]}]}]},{"state":{},"text":"CodiacSDK.NewModule.dll;extensionDeletePre;","children":[{"state":{},"text":"CodiacSDK.NewModule.dll;extensionInquirePost;","children":[{"state":{},"text":"CodiacSDK.JavaScriptWrapper.dll;UnitValues::extensionCreatePre;","children":[]},{"state":{},"text":"CodiacSDK.JavaScriptWrapper.dll;UnitValues::extensionDeletePre;","children":[]}]},{"state":{},"text":"CodiacSDK.NewModule.dll;extensionExecutePost;","children":[{"state":{},"text":"CodiacSDK.PythonWrapper.dll;UnitValues::extensionInquirePre;","children":[]},{"state":{},"text":"CodiacSDK.PythonWrapper.dll;UnitValues::extensionExecutePre;","children":[]}]}]}]}],
					"themes":{
						"icons":false
					}
				}
			})
			.on("select_node.jstree", function (node, selected) {
				var parentNode = $("#testing").jstree(true).get_parent(selected.node.id);

				console.log(parentNode);
			})
			.on("changed.jstree", function (e, data) {
				var jsTreeLib = $("#testing").jstree(true); // Js Tree object
				var jsonOptions = $("#testing").jstree(true).get_json('#', {flat:false}); // Getting 'dirty' json tree by JsTree API

				var result = getFilteredJsonTree(jsTreeLib, jsonOptions); //Main function for creating json tree for OSOC API

				var newObj = result.reduce((a, b) => Object.assign(a, b), {});

				console.log(JSON.stringify(newObj));
			});`

My problem is I need to show root/parent/children node selected at time of edit/update tree, now if I use three_state option true then it works fine but in this option if only one parent is selected then it shows all its child selected even I just checked one child of its parent. So I made false to this option and now I manually doing this functionality.

I need, when I check any last children who doesn't have any more child then selected child as well as all its parent up to root should get selected. Similarly when I select any parent then its all children and sub children should get selected.

As I am using nested level tree and it may get more deeper so it should work in all condition.

Any help is really appreciated.

Thanks

**Comment by vakata** [comment]
I am not sure I understand what you mean - if selecting a parent selects its children, and selecting a node selects all its parents you'd have all nodes selected all the time - for example selecting any node would result in the root node being selected and selecting the root node means all its descendants will be selected.

Anyway - you can find all children, ancestors and descendants as properties on each node object, so you are free to do whatever you want with those. The properties are ```parent```, ```parents```, ```children```, ```children_d```. 

If this does not solve your problem or point you in the right direction - please clarify or ask on stackoverflow, as this seems like a general usage question - not a feature request or bug report.
