### ISSUE TITLE
Lazy load and search with massload #2057 reply

### ISSUE THREAD

**Issue by Zarrdex** [vakata/jstree#2060]
Hi Vakata; 

Thank you for coming back to me,

I am now returning the following values 

            List<TreeNodeSearch> xxx = new List<TreeNodeSearch>
            {
                 new TreeNodeSearch
                 {
                     Id = "1",
                     Text = "World",
                     Children = new List<TreeNodeSearch>
                     {
                         new TreeNodeSearch { Id="2", Text="Site B" }, new TreeNodeSearch { Id = "2", Text = "Site A" },
                     }
                 },
                new TreeNodeSearch
                 {
                    Id = "2",
                    Text = "Site B",
                    Children = new List<TreeNodeSearch>
                    {
                        new TreeNodeSearch { Id="4", Text="Area C" },
                        new TreeNodeSearch { Id = "5", Text = "Area B" },
                        new TreeNodeSearch { Id = "6", Text = "Area A" },
                    }
                 },
                new TreeNodeSearch
                 {
                    Id = "3",
                    Text = "Site A",
                    Children = new List<TreeNodeSearch>
                    {
                        new TreeNodeSearch { Id="7", Text="Area A" },
                        new TreeNodeSearch { Id = "8", Text = "Area B" },
                    }
                 },

            };

when searching for the text Area. 

I needed to add the 'Text' into the first section (before the array of child nodes) , otherwise the node did not display the text on the tree. 

Also, with this i am expecting 2 nodes to be displayed under the root node, But all i am getting back is only 1 node with its child nodes
Example below shows what i am getting back with the details based on your criteria

![treenodesearchexample](https://user-images.githubusercontent.com/20085018/43385652-301eca8a-93d9-11e8-92c6-676d8a2b3640.png)

And below is what i am expecting to get back

![treenodesearchexpected](https://user-images.githubusercontent.com/20085018/43385830-b9306964-93d9-11e8-8b77-4c403cbf1a99.png)

also, once we have the searched nodes, I am unable to lazy load any other nodes, for example 
World-->Site B-->Area B has nodes underneath which i would like to expand, so i could work on them to do such as create/update/delete those nodes

Regards

**Comment by vakata** [comment]
Duplicate
