### ISSUE TITLE
Children loaded twice through ajax cause tree to stop working

### ISSUE THREAD

**Issue by ThorsteinnHelgi** [vakata/jstree#2061]
I have a tree with 5 parents that together hold 8 children. I load the tree using ajax from two json files. All loads fine and displays fine.

I can expand a parent node and collapse it multiple times. 

However if I expand another parent node I notice that the children of all the other parent notes are doubled in "this._model.data" (debugging in Chrome.) "this._model.data" was fine prior to this and the newly expanded node is also fine. When I then try to expand some of the other nodes (e.g. the first node that used to work fine) an exception is eventually thrown in "redraw_node" function (line 1433: "b.setAttribute("aria-level", f.parents.length),") and the tree stops working (not able to expand parent nodes any more).

Error shown:  "Uncaught TypeError: Cannot read property 'length' of undefined"

However the error seems to be triggered by the double loading of the children into "this._model.data" when I expanded the second parent node.

**Comment by vakata** [comment]
I can not help you without a demo, but my guess is that the children have IDs which would cause a crash, as an ID should be unique inside a tree. It could also be hard coded parent IDs, which would cause an issue if loading node A's children, but the response says that the parent is node B. I am almost certain there is something wrong with your data.

If the above does not help - please provide a demo and I will reopen.

**Comment by ThorsteinnHelgi** [comment]
Root json: data/a4s.json
[
    { "id" : "A", "parent" : "#", "text" : "A", "state" : { "opened" : false}, "children" : true, "a_attr" : { "path" : ""} },
    { "id" : "B", "parent" : "#", "text" : "B", "state" : { "opened" : false}, "children" : true, "a_attr" : { "path" : ""} }
]

Children json: data/a4s_ch.json
[
    { "id" : "L11", "parent" : "A", "text" : "L11", "children" : false, "a_attr" : { "path" : ""} },
    { "id" : "L12", "parent" : "A", "text" : "L12", "children" : false, "a_attr" : { "path" : ""} },
    { "id" : "L13", "parent" : "A", "text" : "L13", "children" : false, "a_attr" : { "path" : ""} },
    { "id" : "L31", "parent" : "B", "text" : "L31", "children" : false, "a_attr" : { "path" : ""} },
    { "id" : "L32", "parent" : "B", "text" : "L32", "children" : false, "a_attr" : { "path" : ""} },
    { "id" : "L33", "parent" : "B", "text" : "L33", "children" : false, "a_attr" : { "path" : ""} }
 ]

Loading data:
                'data' : {
                    'dataType': 'json',
                    'contentType':'application/json; charset=utf-8',
                    url : function (node) { 
                        var theUrl = node.id === '#' ?
                            'data/a4s.json' : 
                            'data/a4s_ch.json';                        
                        console.log("theUrl: " + theUrl);
                        return theUrl;
                    },
                    data : function (node) { 
                        let nodeObj = {"id":node.id, "text":"", "path":""};
                        if (node.id !== '#') {
                            nodeObj.text = node.text;
                            nodeObj.path = node.a_attr.path;
                        }
                        console.log("Node.id: " + node.id + ", text: " + nodeObj.text + ", path: " + nodeObj.path);
                        return nodeObj; 
                    }
                }

![image](https://user-images.githubusercontent.com/34395062/43603951-01197872-9684-11e8-98dc-4b6b8161946d.png)

Error: 
Expand A
Collaps A
Expand B (see picture)
Now I can not expand A

**Comment by vakata** [comment]
As I said in the first comment - you CANNOT load the same children twice. What you are doing is trying to place the same children, with the SAME IDs under two different parents. 
Once again - as I said in the first comment - the IDs should be unique in the tree. If all you are doing is a simple demo you could simply remove the IDs from your _ch json file.

**Comment by ThorsteinnHelgi** [comment]
Please take a look again as each child HAS a unique id and IS unique in the tree.

Removing the id's has the effect of putting all children under all parents. 

I'm not struggling with this just for a simple demo.

A better answer would have been that I have to split up my _ch.json into one per each parent. That actually solved this.

A change in the code would also help: not to put a child into the tree if the id already is there.

**Comment by vakata** [comment]
You are trying to load the same children under two different parents (the parent property has no effect in this case as with lazy loading you are supposed to only return relevant data).

Anyway - I am glad you figured it out.
