### ISSUE TITLE
State Plugin issue

### ISSUE THREAD

**Issue by SM0767** [vakata/jstree#2062]
The tree structure remains same as like in previous state after re-login my application. I'm forming the tree newly while login the application. Please help me to solve this issue. Thanks in advance.

**Comment by vakata** [comment]
The state plugin only preserves the opened / selected / checked state, it does not preserve structure modifications. 
If you need to save structure modification on the client side - use core.data as a function and localStorage.
If you mean that state is not restored - make sure your nodes have the same ID, also it might help setting the state.key option to something specific (in case you have multiple trees in your app).

If the above does not help - please provide a demo and a more detailed description of the issue.

**Comment by vakata** [comment]
This is exactly how the state plugin is meant to work - server state is discarded and client state is reapplied. To work around that - you could use a token that is unique to the current session as part of the ```state.key``` option - this way the state will be kept only for the current session. You could also have a look at the ```state.filter``` and modify the state that is being reapplied however you want.
