### ISSUE TITLE
Node path displays only last node name

### ISSUE THREAD

**Issue by Bel1haz0r** [vakata/jstree#2063]
I have an issue with jstree get_path function.
My tree displays something like a folder structure. Let's say I open folder with path Root\folder1\folder2.  On selecting a node, this event is called:

```
$('#tree').on("select_node.jstree", function (e, data) {
    var path = $('#tree').jstree(true).get_path(data.node,'\\');
    $("#path").text(path);
});
```

However instead of getting full path like Root\folder1\folder2, I only get \\\folder2. The number of backslashes increases as I go deeper into the structure, but only last node text is displayed. All the nodes in the tree appear correctly in the tree along with icon and some style attribute I add. If I select to display node ids instead of text, I get correct ids. So if I do this

```
$('#tree').on("select_node.jstree", function (e, data) {
    var path = $('#tree').jstree(true).get_path(data.node,'\\', true);
    $("#path").text(path);
});

```
I would get something like 0\1\4, which are correct ids of nodes in the path. For loading the data, I am using ajax, here is the code 

```
$('#tree').jstree({
	'core' : {
		'multiple': false,
		'data' : {
			"url" : '{{ URL::to("getFolders")}}',
			"data" : function (node) {
				return { "id" : node.id, "jobid" : '{{ $jobid }}' };
			},
			"dataType" : "json"
		}
	}
});
```

**Comment by vakata** [comment]
Sorry, but I can not reproduce the issue:
http://jsfiddle.net/2kwkh2uL/16084/

Please modify the fiddle so that I can see the problem.

**Comment by Bel1haz0r** [comment]
Looks like the issue only appears if I use lazy loading through ajax, meaning I do not load entire tree at the beginning, but load it step by step when user clicks on a node. Unfortunately this does not work for me, as sometimes I have a huge tree and this loading can take a while, so I need to use lazy loading.
