### ISSUE TITLE
Lazy load and search with massload #2057 unresolved

### ISSUE THREAD

**Issue by Zarrdex** [vakata/jstree#2064]
Hi Vakata;

See also Lazy load and search with massload #2057 

I am using jsTree 3.3.5 in a MVC Core project

Using the following plugins massload, search, and wholerow

When the page first loads, it goes off to the lazy-load function and returns the root node, when I click on the expand this uses the lazy-load function to load the next level, which is working great.

If i have expanded all the nodes, and search this just searches the dom elements and expands correctly.

But, if i have not expanded any nodes and search, for "Area" this calls the search function which returns a array of parent id's ["1","2","3"] ["(root)","child of root","child of root"]

This list of id's get passed to the Massload function in which I return as per your specification
{
"1" : [{ "id":"2", "text":"Site B" }, { "id":"3", "text":"Site A" }],
"2" : [{ "id":"4", "text":"Area C" },{ "id":"5", "text":"Area B" },{ "id":6, "text":"Area A" }],
"3" : [{ "id":"7", "text":"Area A" },{ "id":"8", "text":"Area B" }]
}
now what is shown on the screen is

![treenodesearchexample](https://user-images.githubusercontent.com/20085018/43385652-301eca8a-93d9-11e8-92c6-676d8a2b3640.png)

As you can see from the image, we are missing the text from the first child node, as well as we are missing entirely the second child node. plus, Area B has child nodes, which is unknown in this image.

Although if I only returned the following on MassLoad
{
"1" : [{ "id":"2", "text":"Site B" }, { "id":"3", "text":"Site A" }],
}
This, will call the lazy load function for each of the searched ids excluding the already opened node (root) ["2","3"] and produces what is expected. Although this will cause a lot of traffic if the tree was a lot bigger

Can you help me? i.e. Am i missing a configuration setting

Also, why can't i return the values using your new json format {id,text,parent,children=true/false};
As, well as why i can't return all the nodes for the search, as that would mean i could return the full searched tree results, and all your code would need to do is present it, instead of have to run the lazy-load function

**Comment by vakata** [comment]
Once again - as I said in the previous issue - I can not help you without a demo where I can see the whole config and the actual requests and responses.
It could be a million things - something missing in the config, a duplicated ID, something wrong with the responses, etc. I can't keep guessing - it is a waste of both our times.

**If you want me to help you - please provide a demo.** As I said before - I use this functionality daily and it works, I just checked again, so there is nothing wrong with the massload plugin itself.

As for the the why questions:
1) massload is a very simple plugin - it simply expects a lot of responses grouped into one - so you can return whatever you return when massload is not active, just make sure it is grouped in the required response format. You can use the ```parent``` property, but the massload format should be honored.
2) the AJAX search is meant to plug into the client-side only search process, this is why there is a server search, then a load and then a client side search. You are more than welcome to create a PR where the search response is used directly as long as it does not brake existing functionality.

**Comment by vakata** [comment]
I will reopen when a demo is available.
