### ISSUE TITLE
can't select default under ie8

### ISSUE THREAD

**Issue by mhfe123** [vakata/jstree#2065]
i fount it can't default select the item in ie8 even i had set open_node

**Comment by vakata** [comment]
Please provide a more detailed description or a demo. 
Here is a fiddle with a preselected node - it should work fine in IE8:
http://jsfiddle.net/vakata/2kwkh2uL/4479/

**Comment by vakata** [comment]
I can not help without a demo. What is in tdata? Is there an error in IE8? Does it work in other browsers?

**Comment by mhfe123** [comment]
tdata is the data, it can be worked in chrome,edge,but cant work in ie 10-8,maybe something error in my code, i would to check it, thanks a lot for care my question,thank you

**Comment by mhfe123** [comment]
i found the event loaded.jstree didnt work in ie10-8, is it the problem in jstree or in my code ?
