### ISSUE TITLE
checkbox.cascade_to_hidden is selecting nodes that are hidden by search.show_only_matches where they dont match

### ISSUE THREAD

**Issue by eddo888** [vakata/jstree#2068]
```
        'checkbox': {
            'cascade_to_hidden': false
        },
        "search": {
            "show_only_matches": true
        }
```

Hi, I am using the search.show_only_matches = true.
I search for items and for those that are not matched. they are hidden as expected,
however if I use checkbox.cascade_to_hidden=false and I check the parent,
it selects nodes that were hidden by the search.

Cheers Dave

**Comment by vakata** [comment]
I can not reproduce this. Using 3.3.5 I get no issues - here is a demo:
http://jsfiddle.net/2kwkh2uL/16622/

Please modify so that I can see the issue and I will reopen.
