### ISSUE TITLE
Uncheck parent node won't work if it has disabled node

### ISSUE THREAD

**Issue by wonsuc** [vakata/jstree#2070]
I have some children nodes which should not be checked, so I disabled the node and used 'cascade_to_disabled' setting and it works well.

However, when I check the parent node it cascades down children nodes, except disabled nodes, and if I uncheck the parent node nothing happens.

It shows a squared icon(which means some of children are checked) and if I click it, it unchecks itself and children doesn't work.

Here is the screenshot and my code, please let me know if I'm doing something wrong or if it is expected behavior and what the reason is.

Thanks!

![image](https://user-images.githubusercontent.com/9866158/43872867-d83ba386-9bbe-11e8-8967-648093926979.png)

    var tree = $.jstree.create($treeDOM, {
        'core': {
            'multiple': true,
            'data': {
                'url': function(node) {
                    return node.id === '#' ? '/tree/getRootNodes' : '/tree/getChildrenNodes';
                },
                'data': function(node) {
                    return node.id === '#' ? null : {'parentId': node.id};
                }
            }
        },
        'state': {'key': 'tree-master-relation'},
        'checkbox': {
            'keep_selected_style': false,
            'cascade_to_disabled': false
        },
        'plugins': ['wholerow', 'ui', 'search', 'types', 'state', 'checkbox']
    });
    window.tree = tree;

**Comment by vakata** [comment]
This is expected as there is no correct way to handle this. By default jstree will try to check undetermined nodes, but since this node can not be selected - there is nothing jstree can do to uncheck it. This had been discussed at length in another issue - I will find it later today and post a link here.

**Comment by wonsuc** [comment]
I already searched and read tons of discussions related to this issue from here, but I thought this issue is a new issue which has not been referred.

I think the behavior against common UX is that most people expect how it should work.

I'm referencing some other libraries.

[Ant-Design Tree component](https://ant.design/components/tree/)
[A Tree Plugin For Vue2](https://zdy1988.github.io/vue-jstree/) - this library is originated from jstree, but it works differently with the same situation.

I want to listen to your feedback. Thank you.
