### ISSUE TITLE
in IE8 cant use default as key

### ISSUE THREAD

**Issue by mhfe123** [vakata/jstree#2071]
i found it cant use dafault as key in object when i set the type,like this:
'core': {
                    'animation': 0,
                    'check_callback': true,
                    'data': tdata,
                    'themes': {
                        'responsive': false,
                        'stripes': false
                    }
                },
                'contextmenu': {
                    'items': customMenu
                },
                'types': {
                    'default': {
                        'max_depth': 5,
                        'max_children': 5,
                        'icon': 'tree_empty'
                    }
                },
                'plugins': [
                    'contextmenu',
                    'search' ,
                    'types',
                    'wholerow'
                ]
if types set default when this code run in IE8,browser will say SCRIPT1028: 缺少标识符、字符串或数字,but i didnt find a way to make this key compatible,

**Comment by vakata** [comment]
This is an IE8 limitation and an unfortunate name choice on my end. 
I believe it can be worked around using ```obj['default']```. You could also make sure you do not use the ```default``` type.
Changing this now is not possible as it will require a major version bump, and v.4 will probably not support IE8 anyway.
