### ISSUE TITLE
dnd plugin : would really like better visual indication of a 'before' or 'after' drop, or be able to prevent 'before' and 'after' drops.

### ISSUE THREAD

**Issue by seductiveapps** [vakata/jstree#2072]
i am using v3.3.5, and core : { check_callback : function (op,node,par,pos,more) { ... } } to monitor for 'move_node'===op (because i can't get the dnd_move event to even fire), but even after more than an hour of googling, i can not find any way to see if it's going to be a 'before'/'after' drop or an 'inside' drop.

my code is at https://gitlab.com/seductiveapps/seductiveapps/blob/master/seductiveapps/businessLogic/saTree/1.0.0/saTree-1.0.0.source.js

ideally, there would be some kind of visual feedback to indicate during the dragging part of dnd, as well as an option to prevent any of the following dnd variants : inside, before, after.

it would also be great if i could visually tweak the helper somehow..
right now it's a bit hard to see in my semi-transparent interface.
perhaps set the defaults of the helper to be white background, border-radius 5px and opacity about 0.7?

**Comment by seductiveapps** [comment]
by the way, many thanks for making jsTree MIT licensed.
it's saved me much time already.

**Comment by vakata** [comment]
Feel free to tweak the CSS according to your needs - just use stronger selectors and you can change the appearance of the helper.

As for check_callback - ```more.pos``` is what you are looking for, but if you are only interested in drag events - also check if ```more.dnd``` is ```true```.
