### ISSUE TITLE
Disable click and dblclick events on the arrow next to node

### ISSUE THREAD

**Issue by Tz133** [vakata/jstree#2076]
I have registered click and dblclick event to the jstree nodes. It is working alright. 
Issue -
The click and dblclick events gets fired even when I click on the arrow before a parent node. I want the arrow to only toggle the parent node and i want to disable the click and dblclick events on the arrow click as I am performing  custom actions in them.

Click and dblclick events : 

        $("#" + _containerId).on('select_node.jstree', function (ignore, data) {
            _selectedNodeId = data.node.id;
            _selectedFolderPath = data.node.id;
            if (_dblClick) {
                _dblClick = false;
            }
            else {
                _dblClick = true;
                setTimeout(function () {
                    if (_callback && _dblClick) {
                        _dblClick = false;
                        _callback();
                    }
                }, 250);
            }
        });

        $("#" + _containerId).on('dblclick.jstree', function (event) {
            var li = $(event.target).closest("li");
            var node = $("#" + _containerId).jstree(true).get_node(li[0].id);
            $("#" + _containerId).jstree(true).close_node(node);
        });

**Comment by vakata** [comment]
Why are you using the select_node event? If you want to bind click and doubleclick use the normal DOM events:
```js
$("#" + _containerId).on('dblclick', '.jstree-anchor', function (e) {});
$("#" + _containerId).on('click', '.jstree-anchor', function (e) {});
```

**Comment by Tz133** [comment]
Okay. But my doubt is click and double click events get fired on the arrow click also. The arrow before a parent node. I want to disable that. I don't want the custom actions to execute on arrow click.

**Comment by vakata** [comment]
Of course they get executed on the arrow - you attach your listener to ```.jstree-node``` instead of ```.jstree-anchor``` (as shown in the example code above).
