### ISSUE TITLE
Issue with 4 Level jstree select_node event

### ISSUE THREAD

**Issue by krunal1089** [vakata/jstree#2077]
I am using jstree with 4 level and at each level I am allowing to add child only at level 3 rd to add child but after adding that child not able to select that newly created child. I am also allowing to add child from out side of jstree using textbox which ever level is selected it will allow to add child at that node (Level 3rd) after adding Level 3rd child I am automatically creating child at level 4. and I am not able to select this child. I am using select_node event but it is firing 4 5 times and causing an issue for me. How to handle this.

any help will be appreciated.

**Comment by vakata** [comment]
Please provide a demo of the issue, as I do not think this is related to the actual jstree code ... you either have something misconfigured or duplicated IDs. I will reopen when a demo is available.
