### ISSUE TITLE
Jstree - load parent first then load children on demand

### ISSUE THREAD

**Issue by kaavithasatish** [vakata/jstree#2078]
I have a question related to jstree, I would like to load the parent root element initially then after the click of the arrow icon i would like to load the children under the parent node using create_node() function. I have used open_node event but when i click the arrow but its not triggered.. and in class i have set class="jstree-closed", which gives me closed arrow.

I have used the select_node event for selecting the elements and pass it to another page. So i cant use the select_node event. 

Any suggestions kindly post.

**Comment by vakata** [comment]
Lazy load is documented both on jstree.com and the homepage of this repo, my guess is you need the callback option: https://github.com/vakata/jstree#populating-the-tree-using-a-callback-function

**Comment by kaavithasatish** [comment]
Thanks for your reply.

Jstree was already implemented by constructing the <ul><li> nested <ul>.... for 1000 elements, the Main Problem is Performance and all data loading in One Modal.  

I have tried with sample jstree callback function. My requirement is to implement pagination too. My idea is to load the first 30 elements in Page1 with jstree() instance, and when user clicks the Page 2, I can fetch the next 30 elements but problem is, is there a way to append the next 30 elements in the same  jstree() instance and so on?   Is there any other approach to implement, I can very well take it up.

**Comment by kaavithasatish** [comment]
ok. But what kind of data is better for jstree.core.data json format  or constructing ul li nested list. I would like to do in scroll autoload though Possible?? .  Load first 30 elements then while scrolling down load another 30 records as json format and append with the previous json data and give it to jstree.core.data. Is this could be the good approach?

**Comment by kaavithasatish** [comment]
ok..Thank you.

**Comment by kaavithasatish** [comment]
ok...Thank you. But Is the above proposed one could be a good approach? 
First load I construct the jstree with 30 elements then while scrolling down loading another 30 elements. Is there a way to append the data to previous jstree (like redraw or something), because constructing the JSON for every 30 elements and concatenating JSON and give the complete JSON to jstree.core.data is again the performance drawback right? Kindly suggest me some.

**Comment by kaavithasatish** [comment]
ok...Thank you. But Is the above proposed one could be a good approach?
First load I construct the jstree with 30 elements then while scrolling down loading another 30 elements. Is there a way to append the data to previous jstree (like redraw or something), because constructing the JSON for every 30 elements and concatenating JSON and give the complete JSON to jstree.core.data is again the performance drawback right? 

Can i use create_node(Pass next 30 elements JSON Obj)??

Kindly suggest me some.
