### ISSUE TITLE
Is there a way to append set of elements in Jstree 

### ISSUE THREAD

**Issue by kaavithasatish** [vakata/jstree#2080]
Thanks for your reply.

Jstree was already implemented by constructing the nested ul li ... for 1000 elements, the Main Problem is Performance and all data loading in One Modal.
I have tried with sample jstree callback function. My requirement is to implement pagination too. My idea is to load the first 30 elements in Page1 with jstree() instance, and when user clicks the Page 2, I can fetch the next 30 elements but problem is, is there a way to append the next 30 elements in the same jstree() instance and so on? Is there any other approach to implement, I can very well take it up.

**Comment by vakata** [comment]
Duplicate #2078
