### ISSUE TITLE
Loading nodes one by one dynamically via ajax on every click

### ISSUE THREAD

**Issue by black007php** [vakata/jstree#2081]
Hello everyone,

I am trying to make a File manager plugin for my new website. I am using Jstree plugin to achieve this.
It is not working as expected. I have done all the steps as stated in the Jstree demos & examples.
The ajax call works fine. But the nodes are not rendered inside the HTML.

Here is the code for you to review

> <script>

    $(function () {
        // jstree3 - ajax data
        $('#jstree3').jstree({
            'core' : {
            'data' : {
            'url' : 'ftp_manager/get_nodes',
            'data' : function (node) {
              return { 'id' : node.id };
            }
           }
          }
        });
    });
    </script> 

> 

Server response screenshot
![image](https://user-images.githubusercontent.com/25099445/44448752-c97b0800-a609-11e8-8aa4-a383dd528841.png)

Any help would be much appreciated.

Cheers
Milan

**Comment by vakata** [comment]
I can assure you lazy loading works just fine. I can not tell you what is wrong without a demo of the issue.
