### ISSUE TITLE
State and scrolling issues

### ISSUE THREAD

**Issue by saulide** [vakata/jstree#2082]
Im want to use the state plugin, so that the user can get the same position in the tree after refresh.

I forked the state plugin demo into http://jsfiddle.net/cu48y5q2/1/  and added some additional children to the tree, so that scrolling works. If i look what the jstree is storing into the local storage during interaction in the tree, i always have following data there:

` ... scroll: {left: 0, top: 0} ....`

It seems that either a bug exists, or i need more detailed information how state plugin works.
Is there any configuration key that i missed in API description.

Tested with Chrome 68

**Comment by vakata** [comment]
jsTree will not store or modify the window scrollbar position - you will have to do that yourself. jsTree will only restore the scroll position of its own container (if it has scrollbars). Restoring window scroll position is not something jstree should do as that might interfere with other components on the page.
