### ISSUE TITLE
Issues with events when upgraded to latest

### ISSUE THREAD

**Issue by gs-smuthyam** [vakata/jstree#2083]
Hi There, 

We have been using 3.1.1 version till now. All the events used to work fine. Recently we tried to upgrade the library as in need of the performance improvements. Observed below issue, any suggestions to resolve these issues would be helpful.

Our code is highly dependent on loaded, select_node and changed events. It is observed that though the events being triggered from the library(debugging mode). However, the listener the event is not being  heard. 

The same happened for loaded, that worked when changed to ready.jstree. But now the same issue with the select_node. 

The listeners created when the tree created. In case of select node, we are calling the method explicitly to select node.
this._jsTree.jstree('select_node',this.options.selectedNode,true,true); 

But the listener is created on tree creation time.

**Comment by vakata** [comment]
I am afraid I can not help you without a simplified demo of the issue - I can assure you events work fine in 3.3.5 (it has been the stable version for 8 months now). It must have something to do with the way you attach the listeners.
Please provide a simplified demo and if there is an issue - I will reopen. Here is a sandbox to get you started:
http://jsfiddle.net/2kwkh2uL/17537/
