### ISSUE TITLE
jsTree.get_json() not returning undetermined state

### ISSUE THREAD

**Issue by Shatterator** [vakata/jstree#2084]
Hi, if I call the get_json Mehtod on jsTree the returned Json does always give me false on state - undetermined, even if the TreeNode clearly has the state as indicated by the checkbox.

**Comment by vakata** [comment]
```undetermined``` is a visual state only - it is not stored or returned - it is only calculated at runtime. 
If you need the undetermined list you can use this method: https://www.jstree.com/api/#/?q=und&f=get_undetermined([full])
