### ISSUE TITLE
Context menu won't show up if tree is empty

### ISSUE THREAD

**Issue by azev** [vakata/jstree#2085]
If the tree is empty the user cannot add a first new node by right clicking on it because the context menu won't show up

**Comment by vakata** [comment]
The contextmenu plugin only handles clicks on nodes. What you need can be achieved like so:
http://jsfiddle.net/2kwkh2uL/18144/

**Comment by azev** [comment]
Thanks Vakata.
Exactly what I needed.

I have already set up some custom menu items in `$.jstree.defaults.contextmenu.items`
In your fiddle:

```
if (inst) {
      e.preventDefault();
      $.vakata.context.show(e.target, { 'x' : e.pageX, 'y' : e.pageY },
     // get custom menu items from previously built menu in $.jstree.defaults.contextmenu.items
}
```

How do I get the custom menu items from previously built menu in `$.jstree.defaults.contextmenu.items`

**Comment by KoPIIIyH** [comment]
Corrected your fiddle a bit, you forgot one closing curly brace.
http://jsfiddle.net/nuk48p2v/
