### ISSUE TITLE
sort plugin: minor issue

### ISSUE THREAD

**Issue by azev** [vakata/jstree#2086]
There is a minor bug on sort plugin regarding letter cases. For example:
```
- atlanta
- NEW YORK
- Texas
```
will sort:
```
- NEW YORK
- Texas
- atlanta
```
because the sortion function will give priority to Upper case letters before lower case.
'a' comes first than 'N' and 'T' but it will be put last because it is lower case.

**Comment by simon1tan** [comment]
I've noticed this problem as well. What I did was presort the data prior to loading and not use the sort plugin at all. Perhaps the sort plugin should allow overwriting with custom algorithm.

**Comment by vakata** [comment]
Yes, as jstree uses the default sorting function which is case sensitive, you can always provide your own sorting function and make it case insensitive:
https://www.jstree.com/api/#/?q=sort&f=$.jstree.defaults.sort
