### ISSUE TITLE
After dblclick, expand selected node and hide himself

### ISSUE THREAD

**Issue by afmoleirinho96** [vakata/jstree#2089]
What i pretend to do is a search through directories.
Therefore, after i click one folder/file, i want that selected node to expand himself, showing the next depth and hiding himself. Similar to what we do, when we go from C/ProgramFiles/x/y...

As for now, through delegate, i can toggle the selected node and expand the next "depth", but my selected node doesn't disappear. Or when it does, with : $(this).parents().first().hide();, i  have to dblclick, twice and the selected node dissapears along with all the rest of the files/folders.

What can i do in this situation?

Here's a sum of my delegate method:

""
tree.delegate('a','dblclick', function(event){
			var selectedElement $(self.container).find('.jstreeEE').jstree(true).get_selected(event.target);
			var selectedElementId= selectedElement[0];

			if( selectedElement[0].id == $(this).parent().attr('id') ){
				self._addOperationToExpression(selectedElement[0], true);
				$(this).jstree(true).toggle_node(event.target);
			}
			$(this).parents().first().hide();
});

So let's suppose this hierarchy:

A 
  B:
  
  C   E  G 
       F
  D  

A is root and has A/C/D as child. C has E and F as child. E has G has child.

If i dbl click onto A, i can make him disappear but along with all childrens aswell.

If i dbl click on C, for instance, C/E/F/G disappear. I want so that E and F appear when i dblclick C. and not hide the whole selected node hierarchy.

Hope i was concise.

Thanks in Advance.

**Comment by vakata** [comment]
This is not something jstree supports. There is no way to hide a parent and keep its children visible. The only solution I can think of is reinitializing the whole tree with new data on each click, which should be fairly easy to do.

**Comment by afmoleirinho96** [comment]
Could you provide me a simple example?

Basically what i want to do is a search in directory per say. An example is when we go through our directories, we click one node, we expand and get the selected node child's directories and so on.

And thanks once again.

**Comment by afmoleirinho96** [comment]
@vakata

**Comment by vakata** [comment]
This is not tested - consider it pseudo code, that you will need to heavily modify to fit your needs, but it will be something like this:

```js
function createTree(children) {
  $('#tree_container')
    .jstree({ core : { data : children } })
    .on("changed.jstree", function (e, data) {
        var selected = data.selected[0]; // the currently selected node ID
        var children = fetchChildrenSomehow(selected);
        setTimeout(function () { createTree(children); }, 0)
    });
}
createTree(["Root"]);
```
