### ISSUE TITLE
Not working with `import` statement

### ISSUE THREAD

**Issue by mohitsati14** [vakata/jstree#2090]
I included both files `jstree.min.js` and `style.min.css` through `import`. All is working except the icons are not visible.
The reason for this is `url` in `style.min.css` are searching for the icons in my project's public folder. If I copy these icons (32px, 40px, grobber) in public folder, it is working fine.

**Comment by vakata** [comment]
jstree is configured so that it searches for the icons with a path relative to the css file - as long as you keep the jstree bundle intact - it will work.

**Comment by mohitsati14** [comment]
I have not touched the folder. I have installed it by npm. These are import statements:
```
import $ from 'jquery';
import 'jstree/dist/themes/default/style.min.css';
import 'jstree/dist/jstree.min.js';
```
But still icons are not showing.

**Comment by mohitsati14** [comment]
Transpilers support importing CSS like JS (https://guide.meteor.com/using-npm-packages.html#npm-styles). I am doing the same for other CSS files.

How do you think should I include CSS in my project? Manually copying CSS file and other assets defeats the whole purpose of installing via npm.

**Comment by vakata** [comment]
Sorry I am not familiar with importing CSS in meteor - you have to turn to their manuals regarding relative paths in css files and bundling the images. This is not something I am familiar with and I don't think there is something that I can do on the jstree side - the images themselves are in the npmFilemap array.

**Comment by vakata** [comment]
It seems to be a known issue anyway:
https://stackoverflow.com/questions/14669143/loading-background-images-from-css-file-in-meteor

**Comment by mohitsati14** [comment]
Seems like a meteor issue. Thanks for your time @vakata.
