### ISSUE TITLE
Jstree - data load on page scroll

### ISSUE THREAD

**Issue by kaavithasatish** [vakata/jstree#2092]
Is there a way to load the Json data on the page scroll. Jstree is working very well and fulfil all our needs except the page scroll option. 

Due to performance issue on the large volume of data ... I would like to do jstree data load on scroll.

Kindly suggest me

**Comment by vakata** [comment]
Search around the issues here - some people tried to create third party plugins for this. jstree itself does not support loading data as you scroll. 
I am currently working on v.4 which will have a virtual DOM which will resolve most of the issues related to large volumes of data, but v.3 will not get this, as I am currently applying only bug fixes or small features to that version.

**Comment by kaavithasatish** [comment]
ok, I can understand thanks. 

In my scenario I take 50 elements from database and construct the Json and bind in Jstree.core.data.. Then fetch 50 elements from database on the page scroll, construct Json and append with previous json , then supply to jstree.core.data.. 
By doing so, while loading data its loads the complete tree eveytime right, so scroll goes up and then i have re-position scroll. Is there a way to stop this?? 

Its again a performance drawback because constructing jstree everytime.   

Is there any work around for these two... Kindly suggest your valuable info on this.. Apart from this all other functionality is working fine.

**Comment by vakata** [comment]
Are you dealing with a flat list? 
 - if not - why not switch to jstree's lazy loading - it will not slow the UI down
 - if yes - how large of a flat list is this, usually a few thousand nodes will not cause any delay

If you want to recreate the instance every time (which I do not recommend, because you are effectively multiplying the wait time for the user) - take a look at the state plugin - it will reposition the scroll.

**Comment by vakata** [comment]
Send the attributes with the data (look into the JSON format - the ```li_attr``` and ```data``` keys), what you are doing is potentially slowing down rendering even more.

**Comment by kaavithasatish** [comment]
This is the sample data Which i constructed:
<ul><li data-l01='BBB' data-l02='BAA' data-l03='HGB' data-l04='BCC' data-elementname='A01' data-jstree='{"type":"leaf"}' title="HGB">HGB</li><li data-l01='Z01' data-l02='Z02' data-l03='IAS/S' data-l04='IAS/IFRS' data-elementname='A02' data-jstree='{"type":"leaf"}' title="IAS/IFRS">IAS/IFRS</li><li data-l01='US-02' data-l02='U01' data-l03='US-03' data-l04='US-GAAP' data-elementname='A03' data-jstree='{"type":"leaf"}' title="US-GAAP">US-GAAP</li>

**Comment by vakata** [comment]
The HTML data type is very very slow and not a good option for big trees, you definitely should switch to JSON. As I said - lazy loaded JSON will be ideal unless you have tens of thousands of nodes in a flat list.

**Comment by kaavithasatish** [comment]
For state plugin:

 "state": { "key": "myTree" },
 "plugins": ["wholerow", "types", "conditionalselect", "search", "state"]

Need to do any other change, in ul list??

**Comment by kaavithasatish** [comment]
The above code doesnt restore the scroll position ?? Could you help me out for the work around??
