### ISSUE TITLE
jstree- dataload on page scroll -- follow up

### ISSUE THREAD

**Issue by kaavithasatish** [vakata/jstree#2093]
ok, I can understand thanks

In my scenario I take 50 elements from database and construct the Json and bind in Jstree.core.data.. Then fetch 50 elements from database on the page scroll, construct Json and append with previous json , then supply to jstree.core.data..
By doing so, while loading data its loads the complete tree eveytime right, so scroll goes up and then i have re-position scroll. Is there a way to stop this??

Its again a performance drawback because constructing jstree everytime.

Is there any work around for these two... Kindly suggest your valuable info on this.. Apart from this all other functionality is working fine.

**Comment by vakata** [comment]
Please keep the discussion in a single issue.

Duplicate #2092

**Comment by kaavithasatish** [comment]
Sorry..I thought its closed .. I thought you wont see the closed discussion...
