### ISSUE TITLE
Document.registerElement() is deprecated.

### ISSUE THREAD

**Issue by Justin-Lessard** [vakata/jstree#2094]
`document.registerElement()` is deprecated in favor of customElements.define(). It is scheduled to be removed from chrome around March 2019.

It should be updated to `customElements.define()`

References: 
[Document.registerElement()](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement)
[CustomElementRegistry.define()](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define)

**Comment by vakata** [comment]
There are checks in place - if it is removed this will not crash jstree. I doubt I will implement the new method as it seems like a very rarely used feature. 
Do you use the <jstree> custom element?

**Comment by Justin-Lessard** [comment]
Nope I don't use JsTree as a custom elements personally.

Maybe keep this issue open for future references, until someone who need this submit a PR. It looks like a small fix and probably anyone could do it.

Thank you for your super fast response.

**Comment by bugybunny** [comment]
Shouldn’t the check if the method/protoptype exists (I have no JS background, so dunno what the correct term is)  also be updated? https://github.com/vakata/jstree/blob/5c6a68ba0502fedc0a0dced1b5c9605e56ff8dd6/src/vakata-jstree.js#L14

**Comment by brendon** [comment]
It probably should, though it doesn't seem to trigger the deprecation message, it means this fixed code will never be run once `registerElement` is removed.

**Comment by StefH** [comment]
Chrome and Edge Chromium display this Deprecation message:
`[Deprecation] document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.`
