### ISSUE TITLE
Question : Customize the rendering of elements

### ISSUE THREAD

**Issue by Head-Strong** [vakata/jstree#2095]
Hi,

Is it possible to display the number of child nodes in a tree ?
e.g. Parent (2)
          -> Child(3)
               -> C1(0)
               -> C2(0)
          -> Child(4)
and during rename the count should not display.

Thanks

**Comment by vakata** [comment]
Try customizing this plugin:
https://github.com/vakata/jstree/blob/master/src/misc.js#L181
