### ISSUE TITLE
how to open all second level node

### ISSUE THREAD

**Issue by jnlijie** [vakata/jstree#2097]
Hello vakata
I have such a need,
I have a drop down box when I select "Open second level node"
The tree needs to open all second-level nodes on the tree whose children are closed
Or open all third-level child nodes whose child nodes are closed
what should I do .
Thank you!

Like this.
Default Display
![image](https://user-images.githubusercontent.com/28328509/45194962-08ef5880-b288-11e8-99c6-ca6e92fcbd12.png)

select second-level node
![image](https://user-images.githubusercontent.com/28328509/45194990-27555400-b288-11e8-9f09-d69b34bea996.png)

select third-level node
![image](https://user-images.githubusercontent.com/28328509/45195055-7d29fc00-b288-11e8-9937-9b653cb53d17.png)

**Comment by vakata** [comment]
jstree only provides ```open_node``` and ```open_all```. ```open_node``` works with arrays - so you can pass all second level nodes to it. As for collecting them - you might want to iterate over the internal jstree object ```instance._model.data``` and collect all IDs where the ```parents``` property is an array with a length of 2 (or 3 for third level).

**Comment by jnlijie** [comment]
Hello vakata
I use open_node as you said,
But new problems have arisen, I type the following in the console,
``` javascript
  $container.jstree().open_node(["342423332","3424232","323"],function(e,data){console.log(,e,data)})
```
No nodes are open,
Am I wrong?
This is my code
http://jsfiddle.net/2kwkh2uL/18536/  
Thank you!

**Comment by vakata** [comment]
You are trying to open nodes with no children, you are also opening nodes whose parent is closed, I would also advise using strings as ids.

**Comment by jnlijie** [comment]
Thank you very much for your answer, Vakata.
I use numbers as ids, just because it's fast, and it's a test, the real data is a string, thank you for your reminder.
Now that I understand my problem, I am using Open Node Error,
And I found out that I understand the error, that is, when using open_node, it will not open its parent node until it reaches the node of his more node.
When using _open_to, the parent node will be opened. You are doing the operation of opening the parent node in the source code.
So now all I have to do is open my father's section.
Thank you very much!
