### ISSUE TITLE
changed.jstree event is not working

### ISSUE THREAD

**Issue by teo89** [vakata/jstree#2102]
I have a tree on which I want to get the selected node any time the user selects one. As a result, I am trying to use an event which can provide me this functionality.  I tried to catch the changed.jstree event with no success.
The following tree is in  jsTree 3.0.8v.

html code: 
`<div id="treeModal" js-tree="treeConfig" ng-model="treeData" should-apply="true"
						tree="treeInstance" tree-events="ready:readyCB;"></div>`

and in controller code: 
`$('#treeModal').on 'changed.jstree', (e, data) ->
			console.log 'The selected nodes are:'
			console.log data.selected
			return	`

tree configuration code:
`$scope.treeConfig =
			core:
				check_callback: true
				worker: true
				multiple: false
				themes:
					name: 'proton',
					responsive: true
			types:
				default:
					icon: 'icon-hidden'
			plugins: [
				"types"
				"sort"
				"changed"
			]`

Is this event working? If not, is there a way to get the selected node when the node is selected? The get_selected() function is not useful to me as I need to be capable to have the selected node on click and not after other action(for example to click a button after selection).

**Comment by vakata** [comment]
The ```changed.jstree``` event works just fine - I can assure you. If you have any trouble - please consult the vendor of your angular directive.

**Comment by teo89** [comment]
Thanks you, I found a workaround for my case, as so I don't need the events.
