### ISSUE TITLE
jsTree Populating children under wrong node when using callback function

### ISSUE THREAD

**Issue by hariharan06** [vakata/jstree#2103]
Hi, I've been trying to populate jstree using callback function.  When I click a node expand icon, it makes a ajax call to populate the node. Now when I expand multiple nodes, the data gets populated under wrong node and other nodes are not populated at all. This issue happens only when the nodes I expand all nodes at once and when it returns bulk data (eg. 2100 children in each node in my case). I checked the ajax call response and it returns correct children for the node I expanded. If I individually expand each node after one gets populated, I can get the correct tree structure. The issue happens only when I expand all nodes at once.  Please help me with a solution to fix this issue. Thanks in advance.
[jstreeFunction.txt](https://github.com/vakata/jstree/files/2370955/jstreeFunction.txt)
![jstreenodesexpanded](https://user-images.githubusercontent.com/13466297/45360382-0759c380-b5ed-11e8-8bd1-7c231982cb44.jpg)

**Comment by vakata** [comment]
You are using a ```cbb``` variable that is preventing you from properly loading the nodes (it gets reset every time a new node is loaded) - I would advise simplifying this code - take a look at the example on the homepage of this repo.

**Comment by hariharan06** [comment]
Thanks for your response. I now understand that _cbb_ variable is causing the problem. But for my requirement I have to store _cb_ in a separate variable because I cannot pass _cb_ into the ONSUCCESSFUNC:nodeBuildJSTree function since it does not support arguments. Is there any other workaround for using the _cb_.
