### ISSUE TITLE
How to display count of children at parent node

### ISSUE THREAD

**Issue by freddielaure** [vakata/jstree#2104]
Hi,
How to display count of children at parent node like here
https://www.telerik.com/forums/count-the-number-of-all-child-nodes-and-display-it-on-the-parent-node

**Comment by vakata** [comment]
You can use a custom plugin - like advised here: #2095

**Comment by freddielaure** [comment]
HI Vakata,

thanks for Feedback.  I am Populating the tree using AJAX and lazy loading nodes. I am afraid that solution will not works for me., because i get the childs nodes when i clich of the Parent node.

**Comment by vakata** [comment]
Then return the child count as part of the node data and use a custom plugin to display that number next to the node text (as advised above - it is all the same where the number comes from - the actual children array or a data property).

**Comment by freddielaure** [comment]
Thanks works ;)
