### ISSUE TITLE
32px.png - Windows 10 theme attached.

### ISSUE THREAD

**Issue by azev** [vakata/jstree#2105]
I updated the 32px.png icons to match Windows 10 theme.
Please include it in future versions.

![32px](https://user-images.githubusercontent.com/6639188/45373455-e6ca4300-b5c5-11e8-90d7-526c27789530.png)

**Comment by vakata** [comment]
Thank you for sharing this - it is great! I will not update the core theme, but it is wonderful to have this available to anyone who wants a custom theme.

**Comment by shjulberg** [comment]
> I updated the 32px.png icons to match Windows 10 theme.
> Please include it in future versions.
> 
> ![32px](https://user-images.githubusercontent.com/6639188/45373455-e6ca4300-b5c5-11e8-90d7-526c27789530.png)

this theme is great.  Is it possible to get a matching 40px. image?
