### ISSUE TITLE
State undetermined

### ISSUE THREAD

**Issue by wagnerfillio** [vakata/jstree#2106]
I know that a status key is sent as follows:

`state: {
      disabled: false
      loaded: true
      opened: false
      selected: true
}`

But is it possible to include in the state the undetermined item?
would be like this:

`state: {
      disabled: false
      loaded: true
      opened: false
      selected: true
      undetermined : true
}`

 I need to get the value if the parent is undetermined and save in database.
That's all I have.

` var jstree = [];`
`if ($('#jstree').find('.jstree-checkbox').length > 0) {`
    ` jstree = $('#jstree').jstree(true).get_json('#', { 'flat': true });`
` }`

**Comment by vakata** [comment]
Undetermined is a visual state only and is calculated at runtime - it is never stored. But it is fairly easy to apply the results of: https://www.jstree.com/api/#/?q=get_un&f=get_undetermined([full]) to the array you get from ```get_json```
