### ISSUE TITLE
.refresh() and key bindings

### ISSUE THREAD

**Issue by azev** [vakata/jstree#2107]
After doing a `.refresh()` on the tree to load the new `.settings.core.data` the tree is reload successfully but it seems to stuck/hold the whole DOM hotkeys binding.

**Comment by vakata** [comment]
Please provide a demo of the issue, as I can not reproduce it. Here is a fiddle where the key navigation works fine after calling ```refresh```: http://jsfiddle.net/2kwkh2uL/18869/
