### ISSUE TITLE
dnd_start: data.event.target not always accurate

### ISSUE THREAD

**Issue by azev** [vakata/jstree#2108]
`dnd_start.vakata` has some kind of bug because `data.event.target` is not always accurate.
It is ok most of the time. but not always. User may clickdown on a node to drag it and in the end the dragged node may not be the one the event started with, but it's **neighbour node**

![s20180912181655](https://user-images.githubusercontent.com/6639188/45453931-9a136480-b6b8-11e8-87bd-e301c151a4a4.png)

**Comment by vakata** [comment]
The dnd events are low level events emitted from the DND helper, which is not related to jstree in any way - its events do not have the concept of node ID, etc - they only work with what was clicked in the DOM. Usually you will not have to deal with those events when working with a tree only (move_node, copy_node and check_callback will suffice), but if you have to implement something that needs the low level events it is up to you to normalize the node (for example using get_node with the second param set to true).
