### ISSUE TITLE
jstree 4

### ISSUE THREAD

**Issue by FredGr** [vakata/jstree#2111]
Could Please you disclose some information on the architecture of the next version of jstree and what will change.

**Comment by azev** [comment]
What you mean by the "the archtechture"? It is just great the way it is.

**Comment by FredGr** [comment]
Hello,
Thanks for sharing this very interesting information. Since you will go towards some kind of virtual DOM and renderers, did you consider building jstree as a React or Vue or even a more genric Web component ?

**Comment by vakata** [comment]
The goal is to remove dependencies, not add them. Anyone is free to create their own renderers of course - for Angular / React / Vue / etc. The underlying model will provide enough hooks for that. As for webcomponents - jstree currently supports a custom element, but very few people use that. It will be pretty straight forward to add a custom element to v4, I am yet unsure if it will be part of the core package or not.

**Comment by martinRenou** [comment]
@vakata Thanks for the hard work! I can't wait to see `jstree` jquery-free. I made a Jupyter widget based on `jstree`: https://github.com/QuantStack/ipytree. It was just a try, not yet used by anyone but myself. Once it's jquery-free, the plan would be to nuke this repo and directly put our ipytree widget inside of the core of https://github.com/jupyter-widgets/ipywidgets.
I rely on some ugly hacks to replace your base icons by `fontawesome` icons, do you have any plans to make the icons easier to replace for `jstree4`?

Screenshot of `ipytree` inside of the Jupyter notebook:
![ipytree](https://user-images.githubusercontent.com/21197331/48358589-5a0e3500-e69b-11e8-83b7-eff42f3af8b4.png)

**Comment by funkindy** [comment]
@vakata Hello Ivan! Any updates on the 4th version? Thank you.

**Comment by vakata** [comment]
@funkindy 

I just published some dev code to:
https://github.com/vakata/jstree/tree/v.4.0

Some basic functionality is still missing, and the code works only in browsers that support generators, but that will change over the next few weeks.

**Comment by andvasp** [comment]
Hi @vakata !
Do you intend to release the version 4 (without jquery) of this amazing component?
Will be great to use in another frameworks like Angular, React, Vue!
