### ISSUE TITLE
refresh() not checking previously checked nodes

### ISSUE THREAD

**Issue by azev** [vakata/jstree#2112]
When I use `refresh()` the previously checked nodes are not being checked after the `reload()`.
I checked the source and the `checked` inside `state` is set
`state: { 'checked' : true }`
`reload()` is completely ignoring the checked state.
On the first load they are checked OK but after the `refresh()` nothing will be selected.

**_I cannot use cookies or browser storage in this scenario so I can't use 'state' plugin_**

**Comment by vakata** [comment]
Refresh will ignore server side state, as it restores the tree to its state before the refresh call. So if on first load you have checked a node using server data, then the user unchecks it and calls refresh - the node will not be checked again even though it comes as checked from the server. This is configurable - you can use the forget_state parameter of ```refresh```.
If this is not enough or if I misunderstood - please provide a demo of the issue (as it all depends on how you have configured your tree - data source, checkbox config, etc) and I will reopen the issue.

**Comment by azev** [comment]
the `forget_state` parameter address the `opened` state only. Unfortunately I had to implement this function to recheck the nodes according to the source data:

```
            $tree.refresh(true);
            recheckNodes();

function recheckNodes() {
        var groups = SOURCE_DATA;
        for (var i = 0; i < groups.length; i++) {
            for (var j = 0; j < groups[i].children.length; j++) {
                if (groups[i].children[j].state){
                    if (groups[i].children[j].state.checked){
                        $tree.check_node(groups[i].children[j].id);
                    }
                }
            }
        }
    }
```
It is not elegant but it was the only way I found to restore the check states afer a tree refresh

**Comment by azev** [comment]
Is it possible it could be done another way? I mean the `refresh` must check somewhere for the nodes **checked** `state`

**Comment by vakata** [comment]
Server state restoration works fine with:
```.refresh(false, true);```
But client state is not restored when using ```tie_selection : false``` and ```.refresh();```

Is that the bug you originally wanted to report? Sorry I misunderstood.

**Comment by azev** [comment]
Exactly Vakata! You got it right. Thanks for reopening it.
