### ISSUE TITLE
Jstree - recreate instance everytime but need to maintain the state

### ISSUE THREAD

**Issue by kaavithasatish** [vakata/jstree#2113]
Hello, 

Q1) I have a quick question. Initially when I load the data of 100 nodes and for the next 100 nodes i have recreated the jstree instance. But how to maintian the previous state because user might have collapsed some nodes and opened some. Which would be the best way to retain the previous state. 

I thought of using state plugin. But can you give me some direction on how to implement because i tried it doesnt work as  expected. 

Share me some example of how to do it if this would solve my problem. 

Q2)
I have tried with callback function, but its get triggered only if node click event occurs..Sample code snippet
 
$(function () {
    $('#container').jstree({
        'core': {
            'data': function (node: any, cb: any) {
                if (node.id === "#") {               
                cb([{ "text": "Root1", "children": true, "parent": "#" }, { "text": "Root2", "parent": "#" , "children": false }]);
                }
                else {
                    cb(["Child"]);
                }
            }
        }
    });
});

Is there a way to add list of parent node through trigger by other event like page on scroll, take the last tree node and add one set of JSON data after that. Is it possible?? 

Iam open for ideas also. Thanks a lot for your support.  Kindly update.

**Comment by vakata** [comment]
Hi,

1) Just include the "state" plugin in your "plugins" config array - this is all
2) Pagination of data is not supported by jstree - if you want to use pagination - you have to implement it yourself - it is not something I can help with.

Best regards,

**Comment by kaavithasatish** [comment]
I have used state plugin in plugin array, but whenever i recreate the jstree its not maintaining the state and I have mentioned as jstree.open_all after the jstree instance creation.
