### ISSUE TITLE
Issue in changing the Icone based on some condition

### ISSUE THREAD

**Issue by anshulkumar84** [vakata/jstree#2114]
I have attached the below code where I want to change the icome based on downIndicator, But it not happening. Please suggest. 
function createJSTree(jsondata) {
			$('#JSTreeView').jstree({
                'core': {
                	'themes': {
                        'name': 'proton',
                        'responsive': true
                    },
                	"check_callback" : true,
                	"opened":true,
                	'data': jsondata
                },
                "types" : {
                    "error_icon" : {
                        "icon" : { 
                                "image" : "img/tree-icon.png" 
                            },
                       }
                },
               //"state" : { "key" : "SimpleJSTree" },
             "plugins" : ["search","sort" , "changed","conditionalselect","types"]
            })
            .on('ready.jstree',
            	function(event,data,type) {
            	  jQuery.each(data.instance.settings.core.data,function(key, val,type) {
            		  
            		if(val.downIndicator == 1){
            			data.instance._model.data[val.id].type = "error_icon";
            		}
                    return data;
                  });

**Comment by vakata** [comment]
To change a type use the built-in set_type method, do not change the internal objects.
https://www.jstree.com/api/#/?q=set_typ
