### ISSUE TITLE
Not able to add a custom <a><i></i><a> element in the jstree

### ISSUE THREAD

**Issue by Mudit-Garg** [vakata/jstree#2115]
I was trying to add my own element inside jstree using a custom plugin .This is the code for the same:

```js
/*global jQuery */
// wrap in IIFE and pass jQuery as $
(function ($, undefined) {
	"use strict";

	 var _aEdit = document.createElement('A');
	 _aEdit.className = 'editFolder';
	//  _aEdit.attributes('href', "#");
	var _iEdit = document.createElement("I");
	_iEdit.className = 'jstree-icon jstree-themeicon';
	     _aEdit = _aEdit.appendChild(_iEdit);

	$.jstree.plugins.jstreeEditDeactivate = function (options, parent) {
		this.redraw_node = function(obj, deep, is_callback, force_render) {
			obj = parent.redraw_node.apply(this, arguments);
			if(obj) {
				var i, j, tmp = null, icon = null;
				for(i = 0, j = obj.childNodes.length; i < j; i++) {
					 if(obj.childNodes[i] && obj.childNodes[i].className && obj.childNodes[i].className.indexOf("jstree-anchor") !== -1) {
					 	tmp = obj.childNodes[i];
					 	break;
					 }
				}
				if(tmp) {
					tmp.className += ' jstree-themeicon'; 
					icon = _aEdit.cloneNode(false);
					tmp.insertBefore(icon, tmp.childNodes[12]);
					console.log($(icon).parent().html());

				}
			}
			
			return obj;
		};
		
	};

	// you can include the sample plugin in all instances by default
	//$.jstree.defaults.plugins.push("jstreeEditDeactivate");
})(jQuery);` 

```

It is only inserting just the ```<i>``` tag and not the parent ```<a>``` tag....

console.log line is showing this......

```<i class="jstree-icon jstree-themeicon" role="presentation"></i>Root node<i class="jstree-icon jstree-themeicon"></i>```

So my question is ..is it not possible to add an element other that i or img or nested element in particular.....or is it just a syntax mistake by me?

If it is possible to add element tags  like ```<a>``` please provide an example if possible....
Thank you

**Comment by vakata** [comment]
You are adding an ```<a>``` element inside another ```<a>``` element - most browsers do not allow this and will clean it up. Try using another element instead (for example a ```<span>```).

**Comment by Mudit-Garg** [comment]
Thanks for letting me know about my silly mistake...duh..
But I tried with div and span already with same code ..still no luck...is there any other thing i'm missing?

**Comment by Mudit-Garg** [comment]
if at all is it possible to modify the _create_prototype_node function but not inside the jstree.js file
but my plugin.js file and apply it to all nodes when i do this...
`	$.jstree.defaults.plugins.push("jstreeEditDeactivate");
`
