### ISSUE TITLE
Parent node checkbox state based on visible nodes

### ISSUE THREAD

**Issue by EmadMokhtar** [vakata/jstree#2116]
I have a parent in a tree with two hidden children and one visible child when I the user deselects the one visible child the parent checkbox will be partially selected.

**Before hidding the nodes**
![image 2018-09-20 at 4 19 21 pm](https://user-images.githubusercontent.com/311636/45825069-a53a4600-bcf1-11e8-809c-54df6cae2c44.png)

**After hidding the nodes**
![image 2018-09-20 at 4 19 50 pm](https://user-images.githubusercontent.com/311636/45825053-a0759200-bcf1-11e8-879a-a8e2c4d4520e.png)

Is there a way the parent gets the states based on the visible children?

**Comment by vakata** [comment]
No, jstree does not support that, sorry.

**Comment by EmadMokhtar** [comment]
@vakata Thanks for the feedback, and don't be sorry. Thank you for the package 👍
