### ISSUE TITLE
contextmenu: 2 minor issues

### ISSUE THREAD

**Issue by azev** [vakata/jstree#2117]
1. Missing documentation for contexmenu `_disabled`
https://stackoverflow.com/questions/4559543/

2. icon colors of disabled menus not desatured (css filter) when item disabled:
![s20180920130711](https://user-images.githubusercontent.com/6639188/45832092-5d0e2a00-bcd7-11e8-82ba-5bc7a654cce5.png)

**Comment by vakata** [comment]
You are welcome to create a pull request for this.

**Comment by vakata** [comment]
The docs are here:
https://www.jstree.com/api/#/?q=contextmenu.items&f=$.jstree.defaults.contextmenu.items

The grayed out icon is coming.
