### ISSUE TITLE
Oncomplete 

### ISSUE THREAD

**Issue by Mudit-Garg** [vakata/jstree#2118]
is there any way to tell when the $('#mytree').jstree({
core;{}
});

is done populating in the dive with id '#mytee' 

This is because i want to do some custom styling once is it populated but i'm not able to target li of jstree as they are not generated yet.....

**Comment by vakata** [comment]
It is not recommended to modify the DOM as it will be redrawn on change ... so you'd have to redo your modifications. I would recommend using CSS classes only, or a creating a plugin if DOM modification is really necessary.
Anyway, the events you might want to use are:
https://www.jstree.com/api/#/?q=loaded.js&f=loaded.jstree
https://www.jstree.com/api/#/?q=ready.js&f=ready.jstree
https://www.jstree.com/api/#/?q=ready.js&f=state_ready.jstree
