### ISSUE TITLE
Can't deselect node when selection untied to check

### ISSUE THREAD

**Issue by Spankyed** [vakata/jstree#2124]
The user clicks a button to add a node, and my code adds it to the selected node. If no node is selected, it is assumed the user wants to add a node to the root of the tree.

I am unable to deselect the last node in order to add to the root. One remains selected. I have selection untied to checking, because I need the two functionalities to handle things independent of the other. 

Issue Reproduced Here: http://jsfiddle.net/dpzy8xjb/236/ 
Select a single node then try to deselect it.

**Comment by vakata** [comment]
Sorry but there are no instructions - I do not understand the problem.

Using the UI you can deselect a selected node using a Ctrl+click.
Using the API - you can call ```deselect_all```

If this does not help - please clarify and I will reopen.

**Comment by Spankyed** [comment]
Ah, didn't know you had to press ctrl as well. Is there a way to make it so that when you just click the node it deselects, instead of having to press ctrl.

**Comment by vakata** [comment]
Try this:

```
$('#tree').on('click', '.jstree-clicked', function () {
  $('#tree').jstree(true).deselect_node(this);
});
```

I've updated your fiddle too:
http://jsfiddle.net/dpzy8xjb/237/
