### ISSUE TITLE
start the tree from specific node

### ISSUE THREAD

**Issue by meneva** [vakata/jstree#2126]
Hello, I am trying to populate a jstree from json file. the tree is working nicely but i am stuck at some point. I want to generate the tree from a specific node. Let say i have 50 nodes and each may have some childs. So i want to start the tree from 20th node and first 19 nodes will not be shown in the tree. 
![jstree_expected_tree](https://user-images.githubusercontent.com/24285458/46517755-9081b480-c892-11e8-9f93-6855ac908187.PNG)
thanks in advance

**Comment by vakata** [comment]
Modify your data or if not possible - use ```core.data``` as a callback - load your data from the external source, modify it as needed and pass it on to jstree.
