### ISSUE TITLE
restoring state in ajax loaded content

### ISSUE THREAD

**Issue by antman3351** [vakata/jstree#2127]
See update below.

When the page is loaded with page reload (F5) or a tab is restored the state is loaded correctly.

When the content is loaded via ajax (exactly the same page, just the nav bar and footer remain the same) the state isn't reloaded.

The structure is created in html

Tests:
* The state state_ready event is fired
* setting state.filter  = function (data){	console.log(data); }  the data is the same in both cases
* Tried setting a delay on initialising jstree to rule out page still loading.

Thanks,
Antonio

**Update 18/10/18**
instance_counter isn't reset when calling destory.
I added `instance_counter = 0;` in `$.jstree.destroy` (is there a more elegant way? ) so i can call `$.jstree.destroy();`  before initialising the tree.

Every time a tree is initialised this._model.data increments the prefix for the node (j1, j2, j3 ...) so the node names didn't correspond to the names saved in the local storage.

Antonio.

**Comment by vakata** [comment]
I am sorry I am just getting to this now. If you want to deal with any kind of state you should never rely on jstree's autogenerated IDs. Use your own IDs and restoring state should work just fine.
