### ISSUE TITLE
Can have multiple nodes selected with multiple: false

### ISSUE THREAD

**Issue by SrivastavaAnubhav** [vakata/jstree#2128]
Demo can be found [here](https://csclub.uwaterloo.ca/~a23sriva/jstreebug).

If you have a parent to 3 or more nodes selected and multiple set to false, the child nodes are also selected. I believe this is fine, but we can then deselect any of the children to leave more than one selected node.

I feel like the expected behavior is that when you click on a child, it should remain selected and all of its siblings should become unselected. I would be happy to open a PR, but I wanted to confirm that this isn't known/by design and that you agree with the expected behavior.

**Comment by vakata** [comment]
Thank you for the report - please open a PR and I will review. I just don't get the idea of having checkboxes active and multiple set to false ... they both contradict each other.

**Comment by SrivastavaAnubhav** [comment]
Hmm I see what you're saying. What I really want is an option to allow only one top-level node to be checked. I am trying to represent a directory of files, and only want the user to be able to select one directory or file, where if the directory is selected, all files in it are selected. Using checkbox makes it visually clear that this is happening. Would it be better to introduce a new `uniqueTopLevelCheckbox` in the checkbox plugin?

**Comment by vakata** [comment]
This is very specific to your use case - if I encounter more people needing this I will consider adding an option to the core. You could achieve this by listening for the changed event - take a look at this:
http://jsfiddle.net/2kwkh2uL/19566/
