### ISSUE TITLE
How to Manually set the show_only_matches property

### ISSUE THREAD

**Issue by PengEleven** [vakata/jstree#2129]
The default is to initialize the settings directly.
 $("#container").jstree({
           "search": {
                "show_only_matches": true,
            }
})

And I want to indicate whether the structure is reorganized through buttons or check boxes.
 
I thought it was like this.
$('#container').jstree(true).search("show_only_matches", true);

But it doesn't seem to work. How do I set it up?

**Comment by vakata** [comment]
The third argument of the search function:
https://www.jstree.com/api/#/?q=search(&f=search(str%20[,%20skip_async])
