### ISSUE TITLE
Suggestion:  for developers who must test remotely, can plugins be toggled through the UI so that alt-tabbing to code editors is not needed?

### ISSUE THREAD

**Issue by peternoges** [vakata/jstree#2130]
Hello Vakata,
Great work.  I have a small suggestion, and I don't know if it is valid but here it is:

Suppose someone is unable to locally test jstree, because they implement it on a cloud server that lacks local html testing tools.

In that scenario, testing requires not only a roundtrip 'save' to the server, but also an ALT + TAB to reach the code-editor to perform the jstree modifications (such as plugin array changes) to server, and wait, then test.  

The problem here is jstree developers feel forced to Alt+Tab from the browser test to code editor to make changes/modifications to jstree plugin inclusions/exclusions (the "plugins": array)  If jstree developers were provided a faster way to alter jstree plugins (such as from the UI, proposed below) then this would be a non-issue.  

My suggestion is to add a boolean "vakata_developer_mode" to jstree CORE such that when set to TRUE a collapsible / moveable / sizeable (and position/state cached/remembered)  UI pannel appears that allows a developer to enable and disable jstree plugins, **_WITHOUT_** having to ALT + TAB between their code-editor! 

Assuming this is a valid use-case, and assuming "vakata_developer_mode" , I suppose when jstree loads it would need to evaluate vakata_developer_mode and if TRUE would load plugin preferences from browser cache, not the server. For development purposes, those constrained to testing remotely would probably gain efficiency if they could perform plugin alterations (inclusions / exclusions) through a UI panel rather than having to ALT+TAB into their code editor to do the same.  If a vakata_developer_mode panel allowed for UI (ajax-driven) updates to plugin preferences (& subsequently would reload the tree) then it seems faster than having to alt-tab and modify the plugins array and save.

A use-case for disabling and enabling plugins frequently is that a jstree developer might frequently toggle  'contextmenu' plugin ON/OFF, therefore doing this as fast as possible is the goal.  For example this plugin is often included to mimic users to test the context menu... and the same plugin is often excluded by the developer so that the developer can regain the right-click ability in the jstree page to perform inspections (such as Google Chrome Inspect Element).

Thanks for the great work, this is just a suggestion and it might not be a good one :)

**Comment by vakata** [comment]
Thank you for the idea, but this is easily achievable using "user-land" code - just add whatever checkboxes and config settings you need (in a panel you tie to your own system's debug setting), add a button, onclick of that button - build a config and reinitialize jstree with those options - all using JS, without the need to use the editor. Then when you are happy with the result - get the resulting config (as JSON) and paste it in your code editor. Please clarify if I missed the point.
