### ISSUE TITLE
Keyboard keydown event problem

### ISSUE THREAD

**Issue by Mari0oo** [vakata/jstree#2131]
Hi,

I can not configure my own keydown event, because before it will trigger defaults of Jstree. 
I have disabled them, but it's not resolving my problem, because i want to keep arrows and other keys enabled as default. I just want to make ESC and ENTER keys to work as my logic - ESC when creating new node should delete it (like cancel adding operation), when node is being rename from old name to new one then ESC should put the old name. ENTER key when the new node is being create or the old is renaming, then the key should validate input data - if it's not empty make rename, otherwise display information dialog and make the node editable again.

Could you help me please, how to resolve it?

Best regards,
Mari0oo

**Comment by vakata** [comment]
The handlers you refer to are not attached in the same way as all other handlers. For the other handlers - just attach your BEFORE creating the jstree instance and then you can ```stopImmediatePropagation```.

As for the input created when using ```edit```:
There is a callback you can use:
https://www.jstree.com/api/#/?q=edit(&f=edit(obj%20[,%20default_text,%20callback])

If the user canceled the event (the third parameter) call ```delete_node```, as for validation - you can validate and if unsuccessful put the node back in edit mode, or the easier option - use ```check_callback``` to perform the validation (there is an ```edit``` option):
https://www.jstree.com/api/#/?q=check_callback&f=$.jstree.defaults.core.check_callback
