### ISSUE TITLE
how can I supply  datasource to json and different field names?

### ISSUE THREAD

**Issue by purusingh** [vakata/jstree#2132]
how can I supply  datasource to json and different field names?

I want to supply fields

id       ->  _id,
title    ->   name
children -> subgroups

**Comment by vakata** [comment]
Use ```core.data``` as a callback and map your data to the required format. A demo can be found on the homepage of this repo.

**Comment by purusingh** [comment]
<div id="container"></div>
<script>
$(function() {
  $('#container').jstree({
    'core' : {
      'data' : function (node, cb) {
        if(node.id === "#") {
          cb([{"text" : "Root", "id" : "1", "children" : true}]);
        }
        else {
          cb(["Child"]);
        }
      }
    }
  });
});
</script>

on this callback you are providing data from callback.


Lets say I have already Data

var data = [_id:'1', name: 'abc', subgroups: [{_id:'11', name:'ss'}],_id:'2', name:'bcd', subgroups:[]];

how can I use this from callback function?

Thank You

**Comment by vakata** [comment]
This is not related to jstree, but still I will provide an example.

Consider this pseudo code just to get you going.

```
  var data = [{_id:'1', name: 'abc', subgroups: [{_id:'11', name:'ss'}]},{_id:'2', name:'bcd', subgroups:[]}];
  function mapper(nodes) {
    var rslt = [];
    for (var i = 0, j = nodes.length; i < j; i++) {
      var node = {};
      node.id = nodes[i]._id;
      node.text = nodes[i].name;
      node.children = mapper(nodes[i].subgroups);
      rslt.push(node);
    }
    return rslt;
  }
  $('#container').jstree({
    'core' : {
      'data' : function (node, cb) {
        if (node.id === "#") {
          cb(mapper(data));
        }
      }
    }
  });
```

**Comment by purusingh** [comment]
Thanks for your help, it is working fine now.
But it is almost creating new set of data from existing data set and pass the new data set.
Wouldn't it be nice if we can pass the field names on settings?


Thank You
