### ISSUE TITLE
`select_node` invocation will evaluate the node as an expression

### ISSUE THREAD

**Issue by dvuckovic** [vakata/jstree#2133]
Hello,

calling `select_node()` on an already initialized jstree instance will sometimes evaluate the passed value. Used example from the basic demo:

```js
$('#evts_button').on("click", function () {
    var instance = $('#evts').jstree(true);
    instance.deselect_all();
    instance.select_node('<svg onload="alert(1);"/>');
});
```

Managed to reproduce it in Firefox (v63.0b14), Chrome seems not susceptible.

It looks like SVG code here is special: using anything else will either break the layout or simply not run. Please investigate, since there could be some security implications.

Thanks!

Regards,
Dusan

**Comment by vakata** [comment]
Thank you for reporting this. My guess is this is related to ```get_node``` trying to use whatever you passed as a selector (by passing it to ```$()```, which in turn will evaluate the code if it detects new HTML). I will fix ASAP.
