### ISSUE TITLE
When move node, i want destination node id/ref to update its position into database

### ISSUE THREAD

**Issue by ravi-ku** [vakata/jstree#2136]
Hi,

When moving node, i want source & destination nodes info to update info into database. Although, i found source node info. But i also need destination node info to update in the database. Please help.

**Below is my code:**

.on('move_node.jstree', function (e, data) {
                    //debugger;
                    $.get('@Url.Action("MoveNode", "ProjectSettings")',
                        {
                            'operation'     : 'move_node',
                            'projectId'     : @ViewBag.ProjectID,
                            'id' 		    : data.node.id,
                            'parent' 		: data.parent,
                            'oldparent'     : data.old_parent,
                            'position' 	    : data.position,
                            'oldPosition'   : data.old_position

                        })
                        .fail(function () {
                            data.instance.refresh();
                        });
                    console.log('===== Moving '+ data.node.text + '========' );
                    console.log('id          =', data.node.id );
                    console.log('parent      =', data.parent);
                    console.log('position    =', data.position );
                    console.log('old_position=', data.old_position );
                    console.log('old_parent  =', data.old_parent );

                });

**Comment by vakata** [comment]
Everything you need is provided in the event data:
https://www.jstree.com/api/#/?q=move_node.jstree&f=move_node.jstree

If you need extended info based on the ID, simply use ```data.instance.get_node```:
https://www.jstree.com/api/#/?q=get_node&f=get_node(obj%20[,%20as_dom])

**Comment by ravi-ku** [comment]
Appreciated for the prompt response.

My question is about, when we move (drag n drop) node, then there is 2 nodes, 1 is which is moved, 2nd is which is replaced by moved node. in other words, we swapped the 2 nodes. 

now i want both of nodes info (ids, positions) to update in the database.

**I am using below code to trigger below function when node is moved**

('move_node.jstree', function (e, data) 

====
Now i want both of nodes (ids, positions). Please suggest.

Thanks in advance!

**Comment by vakata** [comment]
I already gave you the link to ```get_node``` - please use the knowledge you already have to get the information you need. I am sorry, but I am not here to write your code for you.

1) You have ```node.parent```
2) You can use ```get_node```
3) You can inspect what you get from the above call
4) You should notice the ```children``` array
5) The position you need so desperately is available via:  
```data.instance.get_node(node.parent).children.indexOf(node.id)```

**Comment by vakata** [comment]
```move_node``` moves a node to a new position, by design it does not replace a node (read below on why I clarify this). 

For example:
```
Root1
Root2
  Child1
  Child2
```
If you grab Root1 and drop it between Child1 and Child2, that wound mean that inside the ```move_node``` event you will get data.node which is Root1, position which is 1 and parent - which is Root2. 
Given the functions you already know - if you need to get the node currently occupying that place (if any) you can use:
```
currentID = data.instance.get_node(data.parent).children[data.position]; 
```
If you need the whole node:
```
data.instance.get_node(currentID);
```
**Keep in mind if I drop Root1 AFTER Child2, it will occupy position number 2, which is currently empty (it won't replace anything).**

**Comment by ravi-ku** [comment]
That is what I was looking for!

Thanks!!!

**Comment by harveydobson** [comment]
@ravi-ku  @vakata 

I had the same requirement, so thanks for thrashing this out! 

I am upgrading from an older version of JSTree where the logic that is in place is as @ravi-ku says, to keep the server logic the same, we need to know the new node and the node it is "replacing".  

This (above) I believe is the solution so thanks so much, it was driving me crazy!
