### ISSUE TITLE
How to get both nodes when node is moved (swapped)

### ISSUE THREAD

**Issue by ravi-ku** [vakata/jstree#2139]
My question is about, when we move (drag n drop) node, then there is 2 nodes, 1 is which is moved, 2nd is which is replaced by moved node. in other words, we swapped the 2 nodes. 

now i want both of nodes info (ids, positions) to update in the database.

**I am using below code to trigger below function when node is moved**

('move_node.jstree', function (e, data) 

====
Now i want both of nodes (ids, positions). Please suggest.

**Image 1**
![move-node](https://user-images.githubusercontent.com/11146609/47065584-20afea00-d201-11e8-8ec3-740fb6167e73.png)

**Image 2**

![move-node-1](https://user-images.githubusercontent.com/11146609/47065664-6a003980-d201-11e8-8a72-079d559990c6.png)

Thanks in advance!

_Originally posted by @ravi-ku in https://github.com/vakata/jstree/issues/2136#issuecomment-430489266_

**Comment by vakata** [comment]
I already answered in the previous ticket - stop opening new tickets please. If you think my answer was not enough - keep the discussion in the original ticket.
