### ISSUE TITLE
activate_node can not use with checkbox

### ISSUE THREAD

**Issue by GRAMMAC1** [vakata/jstree#2140]
when use activate_node to active a node
`Uncaught TypeError: Cannot read property 'target' of undefined`

**Comment by GRAMMAC1** [comment]
NO
I am very sure that I will use `activate_node`. I want the same effect as the user clicks.
`select_node` can not solve my problem. I have tried it.

**Comment by vakata** [comment]
I can not help you unless you tell me what you need. All ```activate_node``` does is call ```deselect_all``` and then ```select_node``` (in most cases). If you tell me your use case - I might be able to help.

**Comment by GRAMMAC1** [comment]
Sry I didn't describe my problem clearly.
The function I am implementing is to automatically select the current node after adding a new node.
`select_node` can select current node. but it can not trigger the `activate_node.jstree` event. 
I try not to use `checkbox` plugin, then `activate_node` works and the problem is solved.
but I must use `checkbox` plugin and `activate_node` doesn't work.
 
`Uncaught TypeError: Cannot read property 'target' of undefined`

I need a way to trigger the `activate_node.jstree` event after adding a new node. That's my problem.

Thank you very much for your reply. 
I am not a good English speaker at present, so if I say something improper or impolite, please forgive me.
