### ISSUE TITLE
How to get node at position?

### ISSUE THREAD

**Issue by Mari0oo** [vakata/jstree#2143]
Hi,

I want to get node, which about I know is on specific position and level in tree, but I don't know his new ID, after refresh.  How I can get this node?

Best regards,
Mari0oo

**Comment by vakata** [comment]
You should probably make sure you have consistent IDs ... aside from that - depends on what you know about the node (I do not know what you mean by level), for example:
```instance.get_node(KNOWN_PARENT).children[KNOWN_POSITION]```

If you only know a set of positions, you can start at the root and work your way down:
```
var id1 = instance.get_node("#").children[KNOWN_POSITION_1];
var id2 = instance.get_node(id1).children[KNOWN_POSITION_2];
// etc (you'd probably have to use a loop but you get the point)
```
