### ISSUE TITLE
document.registerElement deprecation

### ISSUE THREAD

**Issue by mkavici** [vakata/jstree#2144]
Hi,
With Chrome 70 release; 
"[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details." warning is started to apper on console.
Regards

**Comment by vakata** [comment]
This is already fixed in the core, but currently ```document.registerElement``` is still present for older browsers. I will remove it entirely in the next version.
