### ISSUE TITLE
Deprecation warning by Chrome

### ISSUE THREAD

**Issue by claudix** [vakata/jstree#2145]
Chrome started to warn about deprecating a feature used by jstree:

    document.registerElement is deprecated and will be removed in M73, around March 2019.
    Please use window.customElements.define instead. 
    See https://www.chromestatus.com/features/4642138092470272 for more details.

Here it's the details' direct link:
https://www.chromestatus.com/features/4642138092470272

According to the [MDN webdocs](https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement ) , this function should be replaced by [`customElements.define` API](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define). 

I haven't checked the viability of moving to the new API yet. Has anybody already started any work on this issue?

**Comment by vakata** [comment]
Fixed in https://github.com/vakata/jstree/commit/537a32301d1f786dd2a523abf5c24e5bb0f193bc
I will probably remove the whole ```registerElement``` block in the next release.

**Comment by bc-lee** [comment]
I am using chrome 70.
It seems like `document.registerElement` is called whenever `window.customElements.define` is failed or not. If `document.registerElement` call is moved into catch area, this warning disappers.

```patch
 		// proto.attributeChangedCallback = function (name, previous, value) { };
 		try {
 			window.customElements.define("vakata-jstree", function() {}, { prototype: proto });
-		} catch (ignore) { }
-		try {
-			document.registerElement("vakata-jstree", { prototype: proto });
-		} catch (ignore) { }
+		} catch (ignore) { 
+			try {
+				document.registerElement("vakata-jstree", { prototype: proto });
+			} catch (ignore) {}
+		}
 	}
```

I also wonder that last release tag ( https://github.com/vakata/jstree/releases/tag/3.3.6 , released on 17 Sep ) does not contain  `window.customElements.define`, but but latest NPM release (published on 9 days ago) contains that code.

**Comment by VipinTi** [comment]
I have not updated my jstree library yet. I am using jstree 3.3.4.  As i can not update the jstree library right now due to some reason.
I am using chrome version 75 and getting warning message "document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details" 
But my all functionalities are working fine. Will this deprecation will cause any problem in future?

**Comment by VipinTi** [comment]
Also i would like to know in latest jstree library 3.3.7 , what other changes has been added apart from document.registerElement. 
What could be the impact of latest jstree 3.3.7?

**Comment by vakata** [comment]
The deprecation will not cause any issues. As for the changes - github provides all the information you need:
https://github.com/vakata/jstree/compare/3.3.4...3.3.7
