### ISSUE TITLE
Trouble using edit function on nodes

### ISSUE THREAD

**Issue by ambischof** [vakata/jstree#2146]
In the newest version I can't have the node name be editable. When enter is clicked, the callback doesn't get the right data, but just empty string.

Works in 3.3.5
https://jsfiddle.net/anneb574/t9kembqx/

doesn't work in 3.3.6
https://jsfiddle.net/anneb574/xbkevc64/

If something has changed, please let me know

**Comment by gabojkz** [comment]
Hi, I got the same issue, for the time being, I will downgrade cause I need to use the editing future but for me everytime edit a node it just returns the current name instead of the new one and the callback returns false.

**Comment by ambischof** [comment]
Thanks for the fix!
