### ISSUE TITLE
How can I deserialize data send with get_json method ?

### ISSUE THREAD

**Issue by lagommette** [vakata/jstree#2147]
Hi,

We have chosen jstree for our project because it seemed the best around. However, we encounter some difficulties to read data send form treeview to controller using get_json method. Indeed, we do not know which structure of class to define in order to deserialize the data. We get an error on server side.

Can you help us on this please ?

On Client side:
        var nodes = TV_Etablissements.jstree(true).get_json('#', { flat: false})

        $.ajax({
            url: '@Url.Action("AssociationEntiteClientPM", "ProfilMetier", new { area = "Administration" })?lazy',
            data: { 'id': $('#SelectedProfilMetierID').val(), 'id2': $('#ddlClient').val(), 'id3': JSON.stringify(nodes) },
            type: 'POST',
            dataType: "text",
            success: function (data) {
                r = JSON.parse(data);
                if (r.success) {
                    alert('cool !');
                }
                else
                    alert(r.message);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(textStatus + " : " + errorThrown);
            }
        });

On Server side:
        public ActionResult AssociationEntiteClientPM(string id, string id2, string id3)
        {
            // This does not work
            JavaScriptSerializer j = new JavaScriptSerializer();
            object a = j.Deserialize(id3, typeof(DownloadedNodes));

            // This does not work eather
            dynamic EntitesClient = JsonConvert.DeserializeObject<DownloadedNodes>(id3);

            JsonResult Resultat = new JsonResult();
            using (var MaDal = new Dal())
            {
                bool ToutEstOk = true;

                if (ToutEstOk)
                    Resultat = Json(new { success = true, message = "OK" }, JsonRequestBehavior.AllowGet);
                else
                    Resultat = Json(new { success = false, message = App_LocalResources.ProfilMetier.ProfilMetier_Index.ErreurAssociation }, JsonRequestBehavior.AllowGet);
            }
            return Resultat;
        }

--------------------------------------------------------
--------------------------------------------------------

    public class DownloadedNode
    {
        public string id { get; set; }
        public string text { get; set; }
        public bool icon { get; set; }
        public string type { get; set; }
        public LiAttr li_attr { get; set; }
        public AAttr a_attr { get; set; }
        public State2 state { get; set; }
        public bool data { get; set; }
        public List<object> children { get; set; }
    }

public class State2
    {
        public bool loaded;
        public bool opened;
        public bool selected;
        public bool disabled;
        public bool failed;
        public bool loading;
        public bool undetermined;
        
    }
    public class LiAttr
    {
        public string id;
    }
    public class AAttr
    {
        public string href;
        public string id;
    }

Thanks in advance for your help.

Regards
Nicolas

**Comment by lagommette** [comment]
Hi,

I have found how to make it work ! :)

First the property children of my Class DownloadedNode has to be 
**public List<DownloadedNode> children { get; set; }**

Then on server side, I have to deserialize this way:
 
public ActionResult AssociationEntiteClientPM(string id, string id2, string id3)
{
###     List<DownloadedNode> Nodes = JsonConvert.DeserializeObject<List<DownloadedNode>>(id3);
[...]
}

**Comment by vakata** [comment]
I am glad you figured it out.
