### ISSUE TITLE
Using } Alternative JSON format - Impossible to have some nodes checked

### ISSUE THREAD

**Issue by lagommette** [vakata/jstree#2148]
Hello,

I am loading a full treeview using the alternate JSON format (with parent id).

There is one node that has the `state.selected = true` the others are set to false. When the treeview is displayed this node is not checked.

I can get all nodes checked by setting all the state.selected to true but it is not what I am looking for.

How can I get it to work ?

Thank you in advance.

Regards,
Nicolas

**Comment by vakata** [comment]
It works fine. Maybe you have activated the state plugin and that restores some other state on top of your tree. Anyway - here is a demo (if I misunderstood - please modify the fiddle so that I can see the issue):
http://jsfiddle.net/2kwkh2uL/19904/

**Comment by lagommette** [comment]
Hi, 


I've updated the fiddle. 


As you can see, the node "ACHATS 52060" is selected in the treeview but in the data it is specified as selected: false. 


So there is something that is not working properly or I am not using the correct options. 


Thanks in advance for your help. 


Regards, 
Nicolas 

----- Mail original -----

De: "Ivan Bozhanov" <notifications@github.com> 
À: "vakata/jstree" <jstree@noreply.github.com> 
Cc: "lagommette" <nicolas.rossignol@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Jeudi 25 Octobre 2018 21:59:47 
Objet: Re: [vakata/jstree] Using } Alternative JSON format - Impossible to have some nodes checked (#2148) 


It works fine. Maybe you have activated the state plugin and that restores some other state on top of your tree. Anyway - here is a demo (if I misunderstood - please modify the fiddle so that I can see the issue): 
http://jsfiddle.net/2kwkh2uL/19904/

**Comment by lagommette** [comment]
I think I have found something. The behaviour is not the same between fiddle and my app.

In the fiddle, the correct nodes are checked. But in my app no node at all are checked. Maybe I do not use the same version.

The version of jsTree I use in my app is 3.1.1.2 from NuGet.

The version of jQuery I use in my app is 3.3.1 from NuGet.

**Comment by vakata** [comment]
I have no idea what 3.1.1.2 is ... jstree uses semantic versioning in the format major.minor.patch (no fourth number). Unfortunately I do not maintain the nuget package, but you should update anyway - the current version is 3.3.6 (it seems like you are on 3.1.1 which was released in *2015*)

**Comment by lagommette** [comment]
Thanks for you reply. 


Do you know who maintains the nuget packages ? 

----- Mail original -----

De: "Ivan Bozhanov" <notifications@github.com> 
À: "vakata/jstree" <jstree@noreply.github.com> 
Cc: "lagommette" <nicolas.rossignol@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 26 Octobre 2018 10:05:12 
Objet: Re: [vakata/jstree] Using } Alternative JSON format - Impossible to have some nodes checked (#2148) 


I have no idea what 3.1.1.2 is ... jstree uses semantic versioning in the format major.minor.patch (no fourth number). Unfortunately I do not maintain the nuget package, but you should update anyway - the current version is 3.3.6 (it seems like you are on 3.1.1 which was released in 2015 )

**Comment by vakata** [comment]
Here is a list of all packages - you can see their maintainers too:
https://www.nuget.org/packages?q=jstree

**Comment by lagommette** [comment]
Thanks a lot :)

**Comment by vakata** [comment]
If you update the fiddle you need to include the URL.
