### ISSUE TITLE
get_selected not working in ASP.Net project

### ISSUE THREAD

**Issue by fobos3-1** [vakata/jstree#2149]
Hi

I am using jstree in an ASP.Net project and I am having a very wird behavior when trying to determine the selected node.

It is rare because previously I developed a prototype in "pure" html which works perfectly.

But when executing it from visual studio 2017 I get the following error in the browser's console:

"Error of type not captured: $ (...). Jstree (...). Attr is not a function"

Error comes with the next line:

var id = $ ('#Results'). jstree ('get_selected'). attr ('id');

I also tried with the following asigment:

var id = $ ('#Results'). jstree (). get_selected (true) [0]

This time the variable "id" keeps the value "undefined".

In both cases, the view (built using a static JSON array) is rendered correctly and respons to user events.

Same html code, same libraries (jstree 3.3.3 and jQuery 3.3.1), same browser, same computer. The "pure" html works, the ASP.Net does not.

I would really appreciate any help you could give me in this

Best regard.

**Comment by vakata** [comment]
Sorry, I am not a .net developer, so I cannot help. Since it works in pure HTML / JS, I assume this is not a jstree issue, so I am closing this.
