### ISSUE TITLE
Mass Load after search

### ISSUE THREAD

**Issue by ankita199** [vakata/jstree#2150]
Hi,
I am Loading only parent nodes for the first time and if user clicks on node it will load its children.This is how it is working. Now i am trying to implement search. So when ever user type in search textbox, after type complete it make ajax request and get all maching ancestor nodes. But how i can load those data in tree view. what should be the response?
```
<form data-id="treemenu-search">
  <input class="form-control-sm" type="search" data-id="query" />
</form>
<div data-id="treemenu" data-content="taxonomies"></div>
<script>
$(function() {
  var content = $('[data-id="treemenu"]').data("content");
  var timeout = null;
  $('[data-id="treemenu"]').jstree({
    "expand_selected_onload": false,
    "plugins" : ["search","state","massload"],
    'core' : {
      "themes" : {
        "dots" : false // no connecting dots between dots
      },
      'data' : {
        "url" : function (node) {
          url = "hierarchy/index?content="+content;
          if (node.id != "#"){
            url += "&id="+node.id;
          }
          return url;
        },       
        'data' : function (node) {
          console.log(node);
        }
      }
    },
    'search': {
      'ajax': {
        'url': 'hierarchy/search?content='+content,
        'success' : function(data) {
          $('[data-id="treemenu"]').jstree(true).settings.core.data = data;
          $('[data-id="treemenu"]').jstree(true).refresh();
        },        
      }
    }
  }).bind("select_node.jstree", function(evt, data){
      var node_id = data.node.id;
      Rails.ajax({
        type: 'get',
        accept: 'js',
        format: "js",
        url: "/taxonomies/"+node_id
      });
  });

  $('[data-id="query"]').keyup(function(event) {
    clearTimeout(timeout);    
    timeout = setTimeout(function () {
      $('[data-id="treemenu"]').jstree(true).search(event.target.value);
    }, 500);
  });
});
</script>
```
In Previous version jstree 1.0-rc3 ( which is used in my project and i am upgrading to new 3.3.1),  After search it make request for each child to get its data automatically.but dont finf tutorial how it should work inlatest version. Anyone can help me with this?

**Comment by vakata** [comment]
Massload uses the same format as the normal loading, but wrapped in an object, so for example, if when loading the children of a node with the ID "node1", you would return ```[{"id", "node2", "text":"Node 2", "children":true}]``` and when loading the children of "node2" you would return ```[{"id", "node3", "text":"Node 3"}]```, then when massloading"node1" and "node2" together you need to return this:

```
{
  "node1" : [{"id", "node2", "text":"Node 2", "children":true}],
  "node2" : [{"id", "node3", "text":"Node 3"}]
}
```
