### ISSUE TITLE
Renaming node via context menu no longer working after commit 2a08acf

### ISSUE THREAD

**Issue by robinfhu** [vakata/jstree#2154]
After doing a `yarn add jstree`, we somehow ended up with the `master` version of jstree (slightly ahead of version 3.3.6).

I noticed that if you try to rename a node using the context menu, the node no longer updates.  I did some investigating, and found that this commit may be the problem: https://github.com/vakata/jstree/commit/2a08acf1f95e1a156ebb7a5408f1b9470940fe3a

In particular, you changed the line to use `this.element.find(obj)` instead of `$(obj, this.element)`.  This appears to have broken the `get_node()` routine.

I'm bringing this to your attention and hope this can help other people who may encounter the same issue.

For now, reverting to jstree version 3.3.5 fixes it for me.

**Comment by vakata** [comment]
Thank you for investigating - I will fix ASAP. Duplicate #2146
