### ISSUE TITLE
Limit the max number of open nodes?

### ISSUE THREAD

**Issue by stephenlawrence** [vakata/jstree#2155]
Is there a way to limit the max number of open nodes? I am using the state plugin, and some users open all nodes and every time they return I get a lot of queries which slows things down. I would like to only allow the most recent 5 state changes from restoring. Is that possible?

**Comment by MehdiBela** [comment]
Hello. I'm not the plugin author or a contributor but I've a suggestion. You could try to bind the open_node.jstree event, check the number of already opened nodes and allow the opening or not. Something like below:
```
yourTree.on('open_node.jstree', function (ev) {
   let opened = yourTree.find(".jstree-open");
   // here you should probably add a filter concerning the state plugin
   if(opened.length > your_limit){
       ev.preventDefault();
       alert('too many nodes opened !')
   }
});
```

**Comment by vakata** [comment]
For your use case - I would use the ```state.filter``` callback and clear stuff from the state:
https://www.jstree.com/api/#/?q=state.filter&f=$.jstree.defaults.state.filter

You could also check out the massload plugin.
