### ISSUE TITLE
How to get all the nodes with Checked, unchecked and undetermined state

### ISSUE THREAD

**Issue by lagommette** [vakata/jstree#2156]
Hello,

I need to send back to server the treeview data with all states for the nodes knowing that I use the checkbox pluging.

Indeeed, when I use the get_json method, I only know if the nodes are checked/not checked:

`var nodes = TV_Etablissements.jstree(true).get_json('#', { no_data: true, flat: false })`

Is there a way to get the undetermined status as well ?

Thanks in advance for your help.

Regards
Nicolas

**Comment by vakata** [comment]
It is not stored on the object itself as it is for representation purposes only, but you can get all the undetermined nodes this way:
https://www.jstree.com/api/#/?q=get_und&f=get_undetermined([full])

And then apply to your ```nodes``` object.
