### ISSUE TITLE
Select node without firing click event with keyboard

### ISSUE THREAD

**Issue by zexxar** [vakata/jstree#2157]
Hi,

I wanted to ask if there is a way to select a node with the keyboard without firing the click event. Because I have a tree with links where on click you will change to that location. There is also a contextmenu for the tree which work perfectly with the mouse. 
But when the keyboard is used to navigate I can change the location by using enter, but this fires the on click event.
 What I need would be also a way to select a node with the keyboard without firing the on click event, because I need to be able to open the contextmenu on a node with the keyboard and a special keycombination. 
I could easily do this if I could select a node without firing the click event. I tried doing it with thw hoverevent which also fires if a node is just focused but there I only get a DOM Object without the node id.

So is there a way to do this?

Thanks in advance
Kevin

**Comment by vakata** [comment]
jstree itself does not fire a click event - this is not related to the jstree code. 

Anyway - to the questions:
To get a node from a DOM object you can use ```get_node```. 
A better solution is to react to jstree events - for example ```changed.jstree``` and ```select_node.jstree``` - in both events you get the original event which triggered the action and you can differentiate between click and keypress and you can choose to react differently based on the information you get in the events.

**Comment by vakata** [comment]
https://www.jstree.com/api/#/?q=keyboard&f=$.jstree.defaults.core.keyboard

**Comment by daljit3** [comment]
@vakata 
> for example changed.jstree and select_node.jstree - in both events you get the original event which triggered the action and you can differentiate between click and keypress and you can choose to react differently based on the information you get in the events.

could you please show me how to check what triggered select_node? i.e. whether it was fired when user actually clicked on the node or a node was selected on ready. 

I want to take certain actions on select_node event only when user clicked on a checkbox to select or deselect. However, if a node was selected on ready I want to ignore some steps.
