### ISSUE TITLE
load_node event is not working on ie(8-11)

### ISSUE THREAD

**Issue by xualen** [vakata/jstree#2160]
jstree load_node event is not working on ie(8-11).

For example

$('#data').jstree({
		'core' : {
			'data' : [
				{ "text" : "Root node", "children" : [
						{ "text" : "Child node 1" },
						{ "text" : "Child node 2" }
				]}
			]
		}
	});

	$('#data').on("load_node.jstree",function(){
		alert();
	})

**Comment by vakata** [comment]
Bind the event handler BEFORE creating the instance and it will fire - in your example when you bind the handler the event has already fired.
