### ISSUE TITLE
Expand / collapse only children

### ISSUE THREAD

**Issue by algorys** [vakata/jstree#2161]
I'm starting to use this plugin and I'm trying to make sure that when the user presses "shift" and clicks it, it expands or shrinks the tree from the selected (or clicked) node.

I've found this kind of code:

```javascript
$("#my_tree").bind("close_node.jstree", function (e, data) {
    data.inst.close_all(data.rslt.obj);
    return false;
})
```

But this kind of properties no longer seems to exist. Here is my current code:

```javascript
$('#tree')
    .on('select_node.jstree', function (e, data) {
        let node = $(this).jstree().get_selected(true)[0];
        $('#nodeName').html(node.text);
        $('#invURI').html(node.li_attr['data-uri']);
        $('#permID').html(node.li_attr['data-id']);
        $('#accessMask').html(node.li_attr['data-access']);
    })
    .on("click.jstree", function(e) {
        if(e.shiftKey && !expanded){
            $(this).jstree('open_all');
            expanded = true;
        } else if(e.shiftKey && expanded) {
            $(this).jstree('close_all');
            expanded = false;
        }
    })
    .jstree(
        {
            "core": {
                "data": [gcsInventoryTree[0]],
                "check_callback" : true
            },
            "plugins": ["dnd", "search"]
        }
    )
    .bind("close_node.jstree", function (e, data) {
        console.log('data ', data);
        data.instance.close_all(data.rslt.obj);
        return false;
    })
```

How I can achieve this ? Thanks.

**Comment by vakata** [comment]
In you click handler add this:
```$(this).jstree('open_all', e.target);```

The code you are trying to use is from v.1 (which has not been supported for many years). The docs on v.3 can be found on https://www.jstree.com and the homepage of this repo.

**Comment by algorys** [comment]
Thanks @vakata, it works perfectly. 

Yes, I have read the documentation, but we lack a few examples for the events. For example, the event `click.jstree` is not listed...

I also noticed that in the `select_node.jstree` event, the `event.shiftKey` property is always **undefined** ... is it normal behavior ?

**Comment by vakata** [comment]
If you want the original event - check for ```data.event``` as documented:
```.on("select_node.jstree", function (e, data) { data.event ... })
