### ISSUE TITLE
JSTree firefox

### ISSUE THREAD

**Issue by rodrigodebem1** [vakata/jstree#2163]
Hello there, how's it going? I'm using the JSTree feature on a service in the company I work in. On that regard, we're having issues with all our tree views in Mozilla Firefox 63. They keep loading indefinitely. On Chrome it works just fine. Do you know if there's already any issue regarding this? If not, how can you help me solve it? If you need any extra info, please let me know.

If you want to check it out, once you create an account on https://panel.slicingdice.com/login/ you have access to a tool called "Workbench" located on the left-side menu.

**Comment by vakata** [comment]
Please provide a minimal demo of the issue so that I can have a look - a jsfiddle / codepen / etc. Until then I can not help because I can not reproduce an issue in firefox.
