### ISSUE TITLE
Cascade undetermined can't uncheck whole tree (all children)

### ISSUE THREAD

**Issue by Emptycz** [vakata/jstree#2164]
My issue is that I'd like to select just a few children from parent but in the same time I can't uncheck all these children from his parent by clicking (changing status) on parent which is kinda sad because I have to go and manually uncheck all these children if I changed my mind (and it can be like 15 children)... Is it possible to set the checkbox plugin into `undetermined` status with possibility of massive unchecking all children when user changes his mind?

**Comment by vakata** [comment]
How about clicking twice? First it will select all children, then deselect them - the same way you see in all trees in various software (both mobile and desktop) - installers for example. If you want to do something custom you can always extend jstree with your own plugin, but I will not modify the core unless more people need this functionality.

**Comment by Emptycz** [comment]
Clicking twice does nothing... it only changes type of visual indicator inside checkbox (from cube [#] to ✓ and back again) it's missing the third status (not selected status) :/

**Comment by Emptycz** [comment]
I have this configuration btw:
`$('.js-categories-checkboxtree').jstree({
		"core" : {
			"animation" : 0,
			"check_callback" : true,
			"themes" : { "stripes" : true },
			"state" : { "opened" : true },
			"children" : [{
				"state" : { "checked" : true },
			}],
		},
		"types" : {
			"#" : {
				"max_children" : 1,
				"max_depth" : 4,
				"valid_children" : ["root"]
			},
			"root" : {
				"icon" : "/static/3.3.5/assets/images/tree_icon.png",
				"valid_children" : ["default"]
			},
			"default" : {
				"valid_children" : ["default","file"]
			},
			"file" : {
				"icon" : "glyphicon glyphicon-file",
				"valid_children" : []
			},
		},
		"plugins" : ["changed", "checkbox", "types"],
		"checkbox" : {
			"keep_selected_style" : true,
			"three_state" : false,
			"cascade" : "undetermined",
			"tie_selection" : false,
			"cascade_to_disabled": false,
			"cascade_to_hidden" : false,
			"whole_node" : true,
			
		},	
		"expand_selected_onload" : true,

	});`

**Comment by Emptycz** [comment]
Oh it's fine I have written my own script in the end. Wonna me post it here for other or later implements / fixes?

**Comment by ciarancourtney** [comment]
@Emptycz yes please...
