### ISSUE TITLE
Warning in Chrome "document.registerElement is deprecated"

### ISSUE THREAD

**Issue by ihsmarkit-syntagma** [vakata/jstree#2165]
Adding <script src=".../jstree.min.js"></script> into your webpage leads to the following console warning in Google Chrome browser:
﻿
jstree.min.js:6 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.

**Comment by vakata** [comment]
This is fixed in this commit: https://github.com/vakata/jstree/commit/d17f2d2c5584f5c97eb45d04e02150f77aca7e9d
3.3.7 should work fine.

**Comment by anilgupta83** [comment]
Wouldn't this break compatibility with Edge though?
window.customElements is not supported in IE/Edge
https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define#Browser_compatibility

**Comment by timri** [comment]
No, since IE/Edge didn't support document.registerElement (aka CustomElements V0) either:
https://developer.mozilla.org/en-US/docs/Web/API/Document/registerElement#Browser_compatibility
