### ISSUE TITLE
href redirection after browser back button

### ISSUE THREAD

**Issue by mkiening** [vakata/jstree#2167]
Hi,
I'm using jstree with lazy loading from a database, that returns json objects. Leaf nodes contain a link and redirect the user on click. The problem is, when the user hits the back button after getting redirected to the new page, the tree is first loaded in the previous state, and then the user is immediately redirected again. I'm using plugin state to save the states of all nodes. Is it possible to prevent this redirection after hitting the back button? Perhaps by only saving the state of opened nodes, but not of selected? Here is the code I used for the tree:

```
$('#ajax').jstree({
                 'core' : {
                        'data' : {
                                 "url" :  function(node) {
                                         return node.id === '#' ? "./tree.php" : "./tree.php?id="+node.id;
                                },
                                type: 'GET'
                        }
                },
                'plugins' : ['state'],
         }).on("select_node.jstree", function (e, data) {document.location = data.instance.get_node(data.node, true).children('a').attr('href')});
```
Thanks a lot for your help in advance.

**Comment by vakata** [comment]
You can filter the state object using:
https://www.jstree.com/api/#/?q=state.filter&f=$.jstree.defaults.state.filter

Remove the ```core.selected``` property and selection will not be restored.

Alternatively - attach your handler only after ```state_ready.jstree``` has fired:
https://www.jstree.com/api/#/?q=state_ready&f=state_ready.jstree
