### ISSUE TITLE
Opened is false Still sending massload ajax

### ISSUE THREAD

**Issue by ankita199** [vakata/jstree#2168]
Hi,

I am using jstree v3.3.6. Here is my  Code
  ```
loadData(configs){
  	var _self = this;
    var timeout = null;
    var jstree = this.$selector.jstree({
      "expand_selected_onload": false,
      "plugins" : ["massload","state","checkbox"],
      'core' : {
        "themes" : {
          "dots" : false
        },
        'data' : {
          "url" : function (node) {
            var url = configs.dataUrl;
            if (node.id != "#"){
              url += "?node_id="+node.id;
            }
            return url;
          },
          "dataType" : "json"
        }
      },
      "checkbox" : {
      },
      "massload": {
        url: 'hierarchy/massload?model_name=Classification',
        "data": function (ids) {
          return { "ids": ids.join(',') };
        }
      }
    }).bind("loaded.jstree", function (event, data) {
    	var insertHTML = '<input type="checkbox" name="checkAll" id="checkAll" /><label for="checkAll" id="checkAllLabel">SELECT ALL</label>';
        $(this).prepend(insertHTML);
        _self.setSelectAllCheckboxforFlexAttribute();
       
     // this.jstree(true).check_node(nodeids);

  	}).bind("open_node.jstree", function(event, data){
    	//_self.setSelectAllCheckboxforFlexAttribute();
   	});
  }
```
What i am trying to achieve is, in my tree view if user clicks on parent node then all parent and its data must be selected and save to db then after when user open bootstrap modal same state of tree view should be loaded. I have try this to be working with tie_selection: false and manage checkbox state my own. But still it is sending xhr request if state is "checked: false" OR "selected: false" (according to tie_selection". Am i doing something wrong?

**Comment by vakata** [comment]
Sorry, but I do not understand the issue. If massload is configured it will be used. As for the custom logic you are trying to implement - I can not help you with that, all I can say is that the config seems fine.

Please clarify if I misunderstood and there is an issue with jstree itself and I will reopen the issue.
