### ISSUE TITLE
Opened is false still massload request is sending

### ISSUE THREAD

**Issue by ankita199** [vakata/jstree#2169]
In this issue [https://github.com/vakata/jstree/issues/2168#issue-38354631] I am trying to load jstree with given data

`[{"id":1,"text":"Non Retail","children":true,"state":{"opened":false,"selected": false}},{"id":16,"text":"Jewelry","children":true,"state":{"undetermined":true,"opened":true}}]`

but using massload all root node child is loaded. What i want is only those child node should be loaded which has a state "undetermined" OR selected true

**Comment by vakata** [comment]
Keep the discussion in a single issue. Duplicate #2168 
Also - read the docs on what massload does - it has nothing to do with opened or undetermined.
