### ISSUE TITLE
Send parameter to a plugin while rendering of the tree

### ISSUE THREAD

**Issue by Mudit-Garg** [vakata/jstree#2171]
So I made a custom plugin for jsTree....That plugin is used to show extra nodes(edit and delete font awesome icon)...

Before calling the function for creating/rendering the tree I am checking for few condition......

So what I wanted to do was that I wanted the edit icon for all nodes in tree when some condition meets and also wants to show delete when some other condition meets....

So here is my question ...is it at all  possible that I can pass some parameter while defining (or maybe while using it)  my custom plugin So that i can change the node according to my need/requirements..

I hope this issue was descriptive enough..
Thank you

**Comment by vakata** [comment]
Each plugin can have settings. You can add a setting to your plugin in the form of two callbacks - ```edit``` and ```delete```, both callables which receive the current node. This way you will be able to do this in your config:
```
yourpluginname: { edit : function(node) { return true; }, delete : function (node) { return node.id == "1"; } }
```
And in your code (probably in the ```redraw_node``` function that you override) you should handle this using:
```
if (this.settings.yourpluginname.edit.call(node)) { ... show edit icon }
if (this.settings.yourpluginname.delete.call(node)) { ... show deleteicon }
```

This should be enough to get you going.
