### ISSUE TITLE
more ways to interact with text

### ISSUE THREAD

**Issue by Hanmac** [vakata/jstree#2174]
Hi i currently have the problem that the node text value is not what i want to display.
the html of the node i need does have multiple values combined

like this:
```
[parent]
 - [icon] [label]        [pos value] [boolean flag] [boolean flag]
```
But when i edit it, i don't want to edit the html but only the label, and when the label is changed, the rest of the html is restored.

the things i would need, or would nice to have a this two or more things:

* Inside the Edit function, something that takes a node and returns the text to be insert into input field
* Something that takes the inserted value and convert it before it is inserted into the node
* OR Another way would be for set_text or rename to interact before the value is set
* OR a way to interact with the renderer how the node is displayed (how the html of the node is generated)

like some kind of before_edit or before_set_text would be good

**Comment by vakata** [comment]
You can achieve this using a custom plugin that overrides the ```redraw_node``` method and adds the desired flags. Check ```src\misc.js``` in this repo for plugin examples.
