### ISSUE TITLE
Length of the ID variable

### ISSUE THREAD

**Issue by buffaloforge** [vakata/jstree#2175]
I have a question on the length of the id field.  I have a below test case where the length of the id will cause the tree to duplicate, even though the id is unique.  In the below example if the "Sequences","id":45035996395987339, will cause duplication, however if the "Sequences","id":7339 it works as it should. jsTree 3.3.6

**--this causes duplication--**
{"text":"conn1","id":0,
"children":[{"parent":"0","text":"user1","id":45035996395987326,
	"children":[
	{"parent":"45035996395987326","text":"Tablespaces","id":45035996395987338},
	{"parent":"45035996395987326","text":"Sequences","id":**45035996395987339**,
		"children":[{"parent":"45035996395987326","text":"TEST_SEQ","id":45035996460563808}]},
	{"parent":"45035996395987326","text":"Tables","id":7340,
		"children":[{"parent":"45035996395987326","text":"ct","id":7334}]}
		]}]}]

**--this works as expected --**
{"text":"conn1","id":0,
"children":[{"parent":"0","text":"user1","id":45035996395987326,
	"children":[
	{"parent":"45035996395987326","text":"Tablespaces","id":45035996395987338},
	{"parent":"45035996395987326","text":"Sequences","id":**7339**,
		"children":[{"parent":"45035996395987326","text":"TEST_SEQ","id":45035996460563808}]},
	{"parent":"45035996395987326","text":"Tables","id":7340,
		"children":[{"parent":"45035996395987326","text":"ct","id":7334}]}
		]}]}]

![image](https://user-images.githubusercontent.com/37871691/49157837-bfdefb80-f2ee-11e8-8dc2-abe0f776d44d.png)

![image](https://user-images.githubusercontent.com/37871691/49157905-f1f05d80-f2ee-11e8-893a-ff5952ec9766.png)

**Comment by vakata** [comment]
This is not jstree related. Do not use integers (you are overflowing the integer) - pass it as string:
```
[
          {"text":"conn1","id":"0",
"children":[{"parent":"0","text":"user1","id":"45035996395987326",
"children":[
{"parent":"45035996395987326","text":"Tablespaces","id":"45035996395987338"},
{"parent":"45035996395987326","text":"Sequences","id":"45035996395987339",
"children":[{"parent":"45035996395987326","text":"TEST_SEQ","id":"45035996460563808"}]},
{"parent":"45035996395987326","text":"Tables","id":"7340",
"children":[{"parent":"45035996395987326","text":"ct","id":"7334"}]}
]}]}]
```
