### ISSUE TITLE
Disabled style not working on IE11 and works weird on Edge

### ISSUE THREAD

**Issue by meddyrainzo** [vakata/jstree#2176]
### Description
When using IE 11, the disabled style doesn't work at all. It looks exactly the same as when it is not disabled. 

When using Edge browser, the disabled style works. But if you have child nodes, the node icons are not visible. 

![with_edge](https://user-images.githubusercontent.com/9278878/49221186-ad40f100-f3d8-11e8-8df3-78f0c355babe.PNG)

(They get visible if you open the developer console -> inspect element -> hover on the blank space where the icon should be)

### Additional info
version: 3.3.7

### Possible error location: 

```
.jstree-default .jstree-disabled > .jstree-icon {
    opacity: 0.8;
    filter: url(data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'><filter id='jstree-grayscale'><feColorMatrix type='matrix' values='0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0.3333 0.3333 0.3333 0 0 0 0 0 1 0'/></filter></svg>#jstree-grayscale);
    filter: gray;
    -webkit-filter: grayscale(100%);
}

```

IE 11 doesn't support -webkit-filter so this might be the cause of the issue

**Comment by vakata** [comment]
Here is a demo:
http://jsfiddle.net/vakata/2kwkh2uL/20342/

It seems to work fine in Edge, and the icon is not gray in IE as it does not support ```filter```, the icon will be gray only where there is support:
https://caniuse.com/#search=filter

If I misunderstood - please clarify and I will reopen.

**Comment by meddyrainzo** [comment]
Hi @vakata ,

Thank you for your response. 

Your demo works when trying it out on Chrome with jQuery(edge) extension.

Here are some screenshots I took from the result of your demo using an actual edge browser (still using the jQuery(edge) extension)

First result 

![edge2](https://user-images.githubusercontent.com/9278878/49278996-9b1d8c00-f486-11e8-9a85-b7c1c66854ba.PNG)

Second result 

![edge3](https://user-images.githubusercontent.com/9278878/49278997-9bb62280-f486-11e8-83a9-132d371a8798.PNG)

Third result

![edge1](https://user-images.githubusercontent.com/9278878/49278998-9bb62280-f486-11e8-8742-62c95ab1f316.PNG)

Fourth result

![edge4](https://user-images.githubusercontent.com/9278878/49279802-b8535a00-f488-11e8-8d6b-d3debb167c56.PNG)


Sometimes the disabled folder gets displayed as expected but then multiple toggles on the RootNode will lead to the second, third or fourth result again.

**Comment by vakata** [comment]
I could not reproduce the problem using:
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

Check if your version is the same. Anyway - this is in no way a jstree bug, so there is nothing I can do - this is something that should be brought to the attention of MS devs, as there seems to be (or was) a problem with using ```filter``` on Edge. 

You can disable the filter in your code using ```#your-tree-id .jstree-disabled > .jstree-icon { filter: none; }``` - that will probably resolve the issue.
