### ISSUE TITLE
Wholerow hover issue when calling hover_node event

### ISSUE THREAD

**Issue by delta1186** [vakata/jstree#2177]
I have a tree where I am using the wholerow plugin.  I needed to use the hover_node event to add a custom height to the jstree-wholerow div because I am wrapping my node text to new lines.  What I discovered is if you add the event binding the jstree-wholerow-hovered class stops getting applied to the jstree-wholerow div.  If I remove the event binding the jstree-wholerow-hovered class start working again.  I will note that the jstree-hovered class gets applied to the anchor tag with and without the hover_node event binding.  I am using latest version of jstree. 

`.jstree({
        "plugins": ["search", "contextmenu", "types", "sort", "wholerow", "checkbox"],
           'checkbox': {
                    'whole_node': false,
                    'tie_selection': false
              },....
)
.off('hover_node.jstree').on('hover_node.jstree', function () {
                //.jstree-default-mjhcs .jstree-wholerow
                ......custom height code here.....
            });`

**Comment by vakata** [comment]
This is expected - you are unbinding all event handlers:
```.off('hover_node.jstree')```
You should only unbind your own handlers. Either by passing in the same function or by using your own namespace (```hover_node.jstree.delta1186``` for example) - there should be more info on that in the jQuery docs.
