### ISSUE TITLE
Save context menu selection on json file.

### ISSUE THREAD

**Issue by Alberto75** [vakata/jstree#2184]
My menu was built by reading a json file; If I make a change using the contextmenu plugin, can I save it in the same json file? Ex: If I add a node in a treeview I wont to save it on json file.
Thanks
Albe

**Comment by vakata** [comment]
Yes, but this is not something jstree can do for you - that is server-side logic. You have many options - for example listening for the events you are interested in, in the handlers calling get_json() and sending the result to the server and saving it. Or have a dedicated save button, etc, but this is all out of the jstree-code scope. All the events and methods you need are documented on the API page on jstree.com
