### ISSUE TITLE
DND

### ISSUE THREAD

**Issue by wraith1821** [vakata/jstree#2188]
When I drag a Root Folder to a different position in the tree and drop, it puts the dragged node wherever it wants.  Usually not where I Dropped.

Ex.

Try to Change This:

Folder 1
Folder 3
Folder 2
Folder 4
Folder 5

To This:

Folder 1
Folder 2
Folder 3
Folder 4
Folder 5

Results in:

Folder 1
Folder 3
Folder 4
Folder 5
Folder 2

Not necessarily at the end of the list but never where I drop.

Sorting doesnt work at all for me.  

Version 3.3.5

**Comment by vakata** [comment]
I cannot reproduce this (using the latest version, but also using 3.3.5). Please provide more details so that I can help. 
Here is the fiddle I used to test:
http://jsfiddle.net/vakata/2kwkh2uL/20663/

I will reopen this as soon as more information is available.
