### ISSUE TITLE
jQuery is undefined

### ISSUE THREAD

**Issue by teslor** [vakata/jstree#2195]
Hi!
In the latest release there is a bug in the code `obj instanceof jQuery`, because jQuery is undefined when jquery was imported using `require`. It causes a crash.
Btw, thanks for your library! I'm using it in my project https://github.com/teslor/ray. Didn't find anything better.

**Comment by vakata** [comment]
Try the latest code from the repo (no version yet). I believe this was fixed in this commit: https://github.com/vakata/jstree/commit/a1a28cfe05178d0263cdd2bc3b79d879bc3b9eab
