### ISSUE TITLE
How can I stop jstree from increasing it's internal counter

### ISSUE THREAD

**Issue by martintan** [vakata/jstree#2196]
I'm using jstree in a react app. When I switch to a new component (switching to another page) I try to destroy the jstree like this
```
destroy() {
    this.$tree.jstree(true).destroy(false)
    this.$tree.jstree('destroy').empty()
    this.$tree.remove()
}
```
So I set the flag `keep_html` to false. However, when I go back to the component where I'm using jstree (I repopulate my jstree with JSON data), all the nodes have their ids increased to `j2_1`, `j2_2`, and so on. Even when I set my own ids for every node (e.g. `1`, `2`), jstree adds a 4 for some reason to all node ids (e.g. `41`, `42`). It only resets the counter if I reload the app (back to `j1_1`, `j1_2`)

**Comment by vakata** [comment]
jstree generates IDs only when you do not specify your own - it will never append something to your own ID. For any app where you need to preserve state it is recommended to use your own IDs - basically - if you rely on those IDs - make sure you use your own. As for appending "4" - this is not something jstree does.

**Comment by martintan** [comment]
Thank you for the advice. I just had to use my own IDs and then everything starts to work correctly. I found that the 4 being appended to the id was a mistake on my part (I forgot to reset my counter whenever I finish walking through a directory, so the id continues incrementing after the first 40 iterations), nothing to do with jstree..
