### ISSUE TITLE
Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by hexarcate** [vakata/jstree#2198]
A line that was added in [this commit](https://github.com/vakata/jstree/commit/cbc9d724f90ca4ab9c74578364be28d087532b64), which was part of release 3.3.7, is producing a fatal exception: 

> jQuery.Deferred exception: Right-hand side of 'instanceof' is not an object TypeError: Right-hand side of 'instanceof' is not an object at a.jstree.plugins.state.get_node (https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.7/jstree.min.js:2:12949)

I have multiple instances of jQuery on the page, so perhaps that might be an issue. Previous releases worked fine. I am using jQuery 3.2.1:
`var jQuery_3_2_1 = $.noConflict(true);`

**Comment by vakata** [comment]
Already fixed in this commit:
https://github.com/vakata/jstree/commit/a1a28cfe05178d0263cdd2bc3b79d879bc3b9eab

**Comment by hexarcate** [comment]
@vakata I get the same exception when I replace jQuery with $
