### ISSUE TITLE
Auto scroll doesn't work when you drag item on EDGE browser version 42.xxx above

### ISSUE THREAD

**Issue by AkshayShaha** [vakata/jstree#2199]
Considering there is large number of items and vertical scrollbar appears on screen.
Try to drag first item from screen to the last position.
Hence there are large number of items screen should auto-scroll, which doesn't work on EDGE browser version 42.xxx above.

P.S. This works fine on Chrome, FF, IE and earlier versions of EDGE.

**Comment by vakata** [comment]
Then this is most probably a problem with EDGE itself. I will have a look and let you know.

**Comment by AkshayShaha** [comment]
Hi vakata,
Any update on this?
Thanks.

**Comment by vakata** [comment]
This is probably fixed by MS - I just tested on Edge 44 (using https://www.jstree.com) and scrolling works fine.
