### ISSUE TITLE
Message or notification when search returns no results

### ISSUE THREAD

**Issue by jacksontan** [vakata/jstree#220]
When the search does not return a value, the tree just shows a blank <ul>. Is there an attribute in jstree or a plugin so when the user searches a string and it does not exist in the tree, it will show a text like "No records found". This should also be available for the ajax loading or initial load when the query does not return anything. BTW, I'm using xml_data plugin.

**Comment by AboObe** [comment]
How to open all children of a certain node ??
How to get the node IDs that resulted from the search ??

**Comment by vakata** [comment]
@AboObe 
https://www.jstree.com/api/#/?q=open_node&f=open_node(obj%20[,%20callback,%20animation]) - use ```node.children``` as the first parameter
https://www.jstree.com/api/#/?q=search.js&f=search.jstree
