### ISSUE TITLE
Different url for init and load on demand

### ISSUE THREAD

**Issue by plamtod** [vakata/jstree#2200]
I is there option initially to load json data from one url and use other url to load node(and its childs) on demand  when it is selected. My backend doesn't make difference and load root in both cases which break functionality When node is selected I call tree.load_node to load leaf on demand.

**Comment by vakata** [comment]
You can set ```core.data.url``` to a function, so that each node can be loaded from a different URL. You can also set ```core.data``` to a function for full manual control.
