### ISSUE TITLE
jstree checkbox data is not working

### ISSUE THREAD

**Issue by ruchikam** [vakata/jstree#2201]
jstree checkbox is not working for defining setting for each node level in multi level tree. Also I am not able to access all the  node data attribute which are checked using the following statement

$("#objectSchemaTree").jstree("get_checked",null,true);

I am not able to disable checkbox and later enable it based on some condition.

**Comment by vakata** [comment]
To get the whole node info use ```get_checked(true)``` as stated here (I do not know why you used ```null```):
https://www.jstree.com/api/#/?q=get_checked%20&f=get_checked([full])

You can use ```enable_checkbox``` and ```disable_checkbox```.
