### ISSUE TITLE
External ajax request for adding nodes

### ISSUE THREAD

**Issue by opxwebdev** [vakata/jstree#2202]
Hi.
I have a working project with the old jstree version. Now I want to update jstree to the current version. But I ran into a problem. In the project I have a JS API, which is used to access the server. In the old version of jstree, I could easily make my ajax request and add new nodes to any parent node. But in the new version I can't do it. When adding a parent node without child nodes, I have to add the parameter 

`children: true`

But in this case, the internal state for this node is set to 

`state.loaded = false`

and when I try to add a new node to this node is executed the **load_node** method, and not the **create_node** method.

I tried to change the state of the parent node before adding new nodes 

```
node.state.disabled = false;
node.state.failed = false;
node.state.loaded = true;
node.state.loading = false;
node.state.opened = true;
node.state.selected = false;
```

and it's worked as I wanted. But understand. that this is not the best way to solve this problem.

Is it possible to correctly implement adding nodes via an external ajax request?

**Comment by vakata** [comment]
I am sorry, but I am not sure I understand the issue. You can add a node using ```create_node```, there is no such thing as a parent node without children - a node either has children or does not have children. If it does - jstree will try to load them when you create a child inside. If I understood correctly - you have two options:
1) add the node using ```create_node``` and do not set ```children``` to ```true``` - it will be rendered as a normal leaf node, but as soon as you add a child inside - it will be rendered as having children.
2) same as above, but set ```children``` to ```true``` - then jstree will try to load the node when you access it, that will fail (make sure the server response is an empty array, or if you do not want to hit the server - intercept using ```core.data``` as a function), as soon as that fails - the node will be rendered as a leaf node, and same as above - if you add a child it will be rendered as having children.

Let me know if I misunderstood.
