### ISSUE TITLE
jstree open nodes

### ISSUE THREAD

**Issue by AboObe** [vakata/jstree#2204]
How to open all children of a certain node ??

**Comment by vakata** [comment]
No need to ask in two separate tickets:
[https://www.jstree.com/api/#/?q=open_node&f=open_node(obj%20[,%20callback,%20animation])](https://www.jstree.com/api/#/?q=open_node&f=open_node(obj%20%5B,%20callback,%20animation%5D)) - use `node.children` as the first parameter
