### ISSUE TITLE
Element.createShadowRoot is deprecated

### ISSUE THREAD

**Issue by vivek-kandhvar** [vakata/jstree#2212]
Thanks for fixing the document.registerElement issue. But after upgrading to the latest version, i.e., 3.7.0, I see this warning. Any plans to fix this as well?

>[Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
(anonymous) @ content.min.js:2

**Comment by vakata** [comment]
The latest version is 3.3.7 and there are no ```createShadowRoot``` calls- can you provide a file:line? I suspect this is not a jstree issue. I will reopen if I am wrong.

**Comment by vivek-kandhvar** [comment]
Damn, you are right. Nothing to do with jstree. Sorry about that.
