### ISSUE TITLE
Search plugin performance

### ISSUE THREAD

**Issue by dmathew** [vakata/jstree#2213]
I have a lazily loaded tree with this configuration:

```
$('#navtree').jstree({
    'core': {
        'data': {
            'url': '/NavTree/GetNode',
            'data': function (node) {
                return { 'id': node.id, 'context': $('#context').val() };
            }
        },
        'check_callback': true,  // for context menu
        'multiple': false
    },
    'plugins': ['state', 'contextmenu', 'search'],
    'contextmenu': {
        'items': CustomMenu,
        'show_at_node': false
    },
    'search': {
        'ajax': {
            'url': '/NavTree/Search',
            'datatype': 'json',
            'data': { 'selected': 'yes' }
        },
        'search_callback': function (str, node) {  // search whole name of an item even when only a summary is displayed
            if (node.a_attr.title !== null && node.a_attr.title.toUpperCase().indexOf(str.toUpperCase()) > -1)
                return true;
            else
                return false;
        },
        'show_only_matches': false,
        'fuzzy': false
    }
});

$('#navtree').on("search.jstree", function (e, data) {
    $('#q').removeClass('loading');
});
```
On searching a subtree with ~300 nodes, it takes 100 seconds to find and highlight about 75 nodes. Following your suggestions on other threads, I disabled `fuzzy_search` and `show_only_matches`; I haven't tried the massload plugin yet, as there seems to be no clear improvement reported for search performance. The actual search is done using a SQL Server stored procedure (which takes < 1s). I am using the latest version (3.3.7). What can I be doing differently to improve search speeds? Let me know if I can provide more details about my implementation.

Thank you for developing and supporting this feature-rich JQuery plugin!

**Comment by vakata** [comment]
You should take a look at how many requests there are after the initial search AJAX request - if there are many requests which take a lot of time - using massload will improve this dramatically.

Otherwise - I see no reason for a search on 300 nodes to take more than a few milliseconds. Applying the callback you have specified to 300 nodes should be very quick.

If the above does not help - please provide an isolated demo of the issue and I will reopen and help further.

**Comment by tdolgyras** [comment]
I was having the same issue on search with 1000 nodes in v3.3.7 browser hangs. After downgrading back to v3.0.9 search works fine now.

**Comment by vakata** [comment]
@tdolgyras thank you for sharing. Can you provide a demo of the issue? Do you have any idea if it is AJAX related? Because if not - it should be easy for me to reproduce and fix.

**Comment by vakata** [comment]
@dmathew @tdolgyras Here is a demo using the latest jstree version and around 300 nodes, some with children, and a search call is made as soon as the tree is ready:
http://jsfiddle.net/vakata/2kwkh2uL/20700/

Could you please demonstrate the issue by modifying the demo?

**Comment by dmathew** [comment]
@vakata Thank you for your responses. The process of making a demo for you helped me realize that the performance issue is probably in my back-end code rather than in the JS library.
![image](https://user-images.githubusercontent.com/2026236/53445172-94df7300-39d5-11e9-8d77-daaed0c90d3a.png)

If you're interested, you can see a demo here:
https://dotnetfiddle.net/SMQePq
The search string is close to the bottom of the view definition.

The performance of the demo could possibly be improved using the massload plugin. But that doesn't seem to be the case in my production system.
