### ISSUE TITLE
JsTree sprite images doesn't show up in high contrast

### ISSUE THREAD

**Issue by AnupNaruto** [vakata/jstree#2214]
I am using JsTree to show a hierarchy of elements in my application.
As part of our org review process, I tested my application with **high contrast theme** and the sprite icons from 32px files don't show up at all.
In fact i even tested a lot of jstree examples in JsFiddle in **high contrast theme** 

Also if I inspect that element, I can see that the icon has occupied some space (like how it occupies in **normal theme**)

Custom plugin code by vakata: http://jsfiddle.net/DGAF4/586/
Some other examples: http://jsfiddle.net/1m97d73f/2/
                                     https://jsfiddle.net/andrealombardo84/xspju6n7/

Also i'm attaching an image that compares the jstree mentioned in above links in **normal theme** against **high contrast theme**

![jstree_defect](https://user-images.githubusercontent.com/30925883/53234791-5769a580-36b6-11e9-9827-a03f47d5beff.png)

Any idea why i am seeing this?

**Comment by vakata** [comment]
I guess it depends on the browser - some browsers will not show background images in high-contrast mode:
http://adrianroselli.com/2012/08/css-background-images-high-contrast-mode.html

Let me know it there is something I can do on the jstree side.

**Comment by AnupNaruto** [comment]
Thanks for your quick reply, My application has few icons, sprite images and font-icons, they show up as expected with out any issue. I am using multiple libraries and i haven't encountered such issue till now. So i highly doubt it's a browser issue.

**Comment by vakata** [comment]
I just checked - using the developer tools it is clear that the high contrast mode sets all ```background-image``` properties to ```none```, which in turn broke not only jstree but the whole site I was using as a test (all background images disappeared). I will look into this topic further - there is a fix in the article I provided in my first comment, but I am not sure I should force the icons on, as it seems they are explicitly turned off which does not affect the functionality of the tree. You could of course apply the mentioned fix to your site to solve any issue you may be having, but I have to educate myself further before I decide whether I should enable the icons forcefully.
