### ISSUE TITLE
Create Functionality in Context Menu of jsTree not working

### ISSUE THREAD

**Issue by aajane** [vakata/jstree#2216]
New nodes won't be created when 'types' plugin is defined.

Please look at this fiddle. I'm unable to create new Nodes in the tree.
 http://jsfiddle.net/z8L5r9w3/1/

or look into stackoverflow:
https://stackoverflow.com/questions/55023377/create-functionality-in-context-menu-of-jstree-not-working

**Comment by vakata** [comment]
This is because you are using custom types, and by default the contextmenu create action will create a node of type "default" which is not allowed by your config. Make sure you override the contextmenu callbacks with your own types.

**Comment by aajane** [comment]
okay. Can you provide a sample fiddle for this?

**Comment by aajane** [comment]
or atleast try to edit the jdFiddle I refered?

**Comment by vakata** [comment]
Here is a demo:
http://jsfiddle.net/0jqeb65L/

**Comment by aajane** [comment]
Thanks Ivan. It works perfectly
