### ISSUE TITLE
Node change event

### ISSUE THREAD

**Issue by orangethakkali** [vakata/jstree#2217]
I have a tree with 2 nodes - Root, Child. By default Root is selected and "changed" event is fired when I click on "Child" node. Is it possible to get the node that was previously selected during the "changed" event.

**Comment by vakata** [comment]
Enable the ```changed``` plugin, then in the ```changed``` event you will also have a ```changed.selected``` and ```changed.deselected``` properties.

**Comment by orangethakkali** [comment]
Thanks, but I cannot see data.deselected in the output.
[https://pastebin.com/0t2eGRrk]

**Comment by vakata** [comment]
Here is an example:
http://jsfiddle.net/rowbheq2/1/

**Comment by orangethakkali** [comment]
Thanks again, I had Plugins property at the wrong place. It works now.
