### ISSUE TITLE
Get checked node not working when I draw tree with checked element 

### ISSUE THREAD

**Issue by FatenElhariry** [vakata/jstree#2218]
Hi ,
I use jstree for edit in this case I draw the tree with checked element the element appear checked but when call function for get_checked not got it and the parent of the element appear as no child checked 
When I check by mouse after loading it will be checked 
I try this case by two ways draw tree with html and with json data I got the same result 
What is the reason

**Comment by vakata** [comment]
Please provide a demo of the issue, as I can not reproduce this. Also make sure you are using all properties correctly - checked and selected could be the same, but they could also be different:
https://www.jstree.com/api/#/?q=tie&f=$.jstree.defaults.checkbox.tie_selection - it all depends on how you configure the tree.

I will reopen when a demo is available and I can reproduce. Here is a stepping stone - it works fine for me:
http://jsfiddle.net/8ax6cwoy/
