### ISSUE TITLE
load_node issue on IE 11- does not trigger ajax requests to get the data from server

### ISSUE THREAD

**Issue by Aravindhan1992** [vakata/jstree#2219]
--for example

$(treeid).jstree(true).load_node(myArray, function callback(){
setInterval(function(){
//code
},5)
});

the above code is not loading the nodes from myArray. And no trace of xhr under network tab.
tried setting 'cache':false in the config but no avail. '
nodes are loaded when I run it in private window(clearing cache didnt help though).

**Comment by Aravindhan1992** [comment]
-- no traces of ajax request on network tab...

**Comment by vakata** [comment]
I need a more complete example in order to help. This is not a known issue and I can not reproduce it.

**Comment by vakata** [comment]
I will reopen when more info is provided and I can reproduce.
