### ISSUE TITLE
Contextual Menu plugin - Does not open when right clicking name

### ISSUE THREAD

**Issue by Dubz** [vakata/jstree#2220]
Contextual Menu only works when right clicking on the icon and not the name.
When right clicking on the name, it breaks the contextual menu for that file/node and users can no longer access it (even the checkbox, if enabled) until after refreshing.

Tested on the demo site to verify.

**Comment by vakata** [comment]
I can not reproduce - which browser, which OS? Right-clicking anywhere on a node works fine:
https://www.jstree.com/plugins/

Please provide more information and steps to reproduce the issue and I will reopen.

**Comment by Dubz** [comment]
My apologies. I tested this on FIrefox and in an incognito window on Chrome, both worked properly.

Isolated the issue to an extension (Flip this) that allows me to right click and rotate elements (ex. pictures) on demand, without having to fiddle with dev tools to rotate it manually.

The plugin is working properly.
