### ISSUE TITLE
Abort previous ajax calls in jsTree

### ISSUE THREAD

**Issue by ravilog** [vakata/jstree#2222]
How to cancel previous ajax call while loading child nodes.. am using below format to load nodes using ajax. And trying to abort previous ajax call in the beforesend function which unfortunately called multiple times and causes throbe icon to display multiple times(switching between previous and current nodes).
.jstree({
                'core': {
                    'data': {
                        'async': true,
                        'data': function (node) {....},
'url':function(node){....},
'beforesend':function(jqXhr){
if(prevRequest!=undefined && prevRequest!=''){
prevRequest.abort();
}
prevRequest=jqXhr;
},
'success';function(data){.....}
.......});

**Comment by vakata** [comment]
Switch to using core.data as a function - that way you have full control over the AJAX requests (since you will be making the manually).

**Comment by ravilog** [comment]
Thanks a lot, can you provide any sample which uses core.data as a function ?

**Comment by vakata** [comment]
Try using instance.get_node(prevNode).state.loaded = false;

**Comment by ravilog** [comment]
'$tree.jstree(true).get_node(prevNode).state.loaded = false;' 
it did help but also brought back the issue i was facing previously. it just triggers multiple ajax request which makes the flickering(switching between current and previous nodes).
