### ISSUE TITLE
drag a node from source tree to target tree

### ISSUE THREAD

**Issue by NickCong** [vakata/jstree#2225]
Hi,
   Thanks for your great job. The jstree is awesome.
    I have two trees, one is source and the other is target.The source nodes have some custom properties. When I drag the source node to the target tree, then I get the json data from target tree. But the new added node dosen't contain the custom properties.
   I have found the "always_copy" configration, but I dosen't know how to use it.
  Can you share me a code sample ?

**Comment by vakata** [comment]
The data property is not copied between trees, you need to do that manually. Here is a demo:
http://jsfiddle.net/uhcfdgxo/
