### ISSUE TITLE
Problem with father checkbox, when their children is not selec

### ISSUE THREAD

**Issue by ribeirofilipe** [vakata/jstree#2229]
When deny all the children permissions from some father checkbox, the father keeps selected,

<a href="http://picasion.com/"><img src="http://i.picasion.com/pic89/6ceb3f1dcc72621a3b2ccffa4cc1fe1e.gif" width="300" height="115" border="0" alt="http://picasion.com/" /></a><br /><a href="http://picasion.com/">http://picasion.com/</a>

Example code bellow:

`(function() {
    "use strict";
    angular
        .module('gestorCatalogo')
        .directive('treeviewgeneric', treeviewgeneric);

    treeviewgeneric.$inject = [];

    function treeviewgeneric() {
        return {
            restrict: 'E',
            template: '<div ng-hide="hide" class="tree-view-generic" style="height: 300px;"></div><div ng-hide="!hide" style="text-align: center"><span  class="m-datatable--error">Nenhum resultado encontrado</span></div>',
            scope: {
                editData: '=',
                search: '=',
                selected: '='
            },
            link: function($scope, element, attr) {

                $scope.nodes = {};
                $scope.hide = false;

                var $tree = $(element).find('.tree-view-generic');
                var treeInitializedBefore = false;

                $scope.$watch('selected', function() {

                }, true);

                $scope.$watch('editData', function() {

                    if (!$scope.editData) {
                        return;
                    }

                    initializeTree();
                });

                $('.tree-view-generic').on('click', function(e) {
                    let isClickedClass = e.target.className.includes("jstree-clicked");
                    let isThemeIconClass = e.target.className.includes("jstree-themeicon");
                    if (!isClickedClass && !isThemeIconClass) {
                        $tree.jstree(true).deselect_all();
                        $scope.$apply(function() {
                            $scope.selected = undefined;
                        });
                    }
                });

                $scope.$watch('search', function() {
                    $tree.jstree('search', $scope.search);

                    if ($scope.search) {
                        if ($scope.nodes.length <= 0) {
                            $scope.hide = true;
                        } else {
                            $scope.hide = false;
                        }
                    }
                }, true);

                function initializeTree() {
                    if (treeInitializedBefore) {
                        $tree.jstree('destroy');
                    }
                    var treeData = _.map($scope.editData, function(item) {
                        return {
                            _id: item.id,
                            id: item.id,
                            parent: item.parentId ? item.parentId : '#',
                            text: item.name,
                            state: {
                                opened: true,
                            },
                            li_attr: item,
                        };

                    });

                    $tree.jstree({
                        'core': {
                            data: treeData
                                //expand_selected_onload: false
                        },
                        "types": {
                            "default": {
                                "icon": "fa fa-folder tree-item-icon-color icon-lg"
                            },
                            "file": {
                                "icon": "fa fa-file tree-item-icon-color icon-lg"
                            }
                        },
                        "search": {

                            "case_insensitive": true,
                            "show_only_matches": true
                        },
                        plugins: ['search']
                    });

                    treeInitializedBefore = true;

                    $tree.on("changed.jstree", function(e, data) {
                        var i, j, r = [];
                        for (i = 0, j = data.selected.length; i < j; i++) {
                            $scope.$apply(function() {
                                $scope.selected = data.instance.get_node(data.selected[i]);
                            });
                        }
                    });

                    $tree.on("search.jstree", function(e, data) {
                        $scope.nodes = data.nodes;
                    });

                }

            }
        };
    }
})();`

**Comment by vakata** [comment]
This example does not use the jstree checkboxes plugin - this is custom logic implemented on top of angular - I am afraid I can not help you with that. 
If I misunderstood and there is an issue with jstree itself - let me know and I will reopen.
