### ISSUE TITLE
linked to issue #2222-(stop loading nodes in lazy loading)

### ISSUE THREAD

**Issue by ravilog** [vakata/jstree#2230]
Hi, 
this is related to a closed issue #2222 which i created sometime ago. kindly provide directions on how to stop already initiated open_node functions. since I have many nodes and levels in my jstree i need to stop loading the node(for which open_node is called and being executed) except the last node that was clicked to open.

**Comment by vakata** [comment]
Here is a demo of cancelling node loading. Once cancelled (after 1 second), the node can be opened again:
http://jsfiddle.net/nuy5r78b/
