### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread

### ISSUE THREAD

**Issue by bbalet** [vakata/jstree#2232]
When I use JsTree with the tree loaded by Ajax (by relying on your lib), I get a Deprecation notice on Google Chrome. My code looks like:

        $('#organization').jstree({
            rules : {
                deletable  : false,
                creatable  : false,
                draggable  : false,
                dragrules  : false,
                renameable : false
              },
            core : {
              multiple : false,
              data : {
                url : function (node) {
                  return node.id === '#' ? 
                    '/organization/root' : 
                    '/organization/children';
                },
                'data' : function (node) {
                  return { 'id' : node.id };
                }
              },
              'check_callback' : true
            },
            plugins: [ "search", "state", "sort" ]
        });

After reading again the doc, I assume that the _core_ attribute is JQuery's ajax object. So I've tried to pass the option `async: true` (under core) but without success.

**Comment by vakata** [comment]
This is not related to jstree - make sure you are not modifying the jQuery AJAX defaults somewhere else in your code. jsTree will not make sync requests unless explicitly configured to do so.
