### ISSUE TITLE
ContextMenu plugin memory leak

### ISSUE THREAD

**Issue by yzhang921** [vakata/jstree#2234]
Hi Vakata, as title described that maybe context menu plugin has a memory leak issue. 
First, I doubt that there is some problem with my code. After I checked again and again and found out if I remove the **contextMenu** plugin then the memory leak issue disappeared. 
Even if I didn't set any context items and turn on contextMenu plugin setting, memory leak also exists.
```javascript
         //treeOption.contextmenu.items

           destroyed() {
            $(document).unbind('context_show.vakata');
            $(this.$el).find("#tree-body").empty();
            this.treeRef.destroy();
            $(this.$el).remove();
            $('context_show.vakata').remove();
            this.treeRef = null;
            this.tree = null;
```

**Comment by vakata** [comment]
Sorry but I can't fix this - please provide a PR if you know where the leak is.

**Comment by RamPonds** [comment]
Facing the memory leak in the similar fashion. $.jstree.plugins.contextmenu.prototype._data.core.original_container_html.prevObject.prevObject

**Comment by alex-Hudson** [comment]
I also am facing this problem. In my application I also removed all context menu items and found the memory leak. When I removed the plugin from the jsTree plugins the memory leak was no longer observed

**Comment by alex-Hudson** [comment]
@vakata I have caught the memory leak. I will submit a PR.
For any interested the leak is a missing call to $(document).off('.jstree'); in the unbind method (in jstree.js line 947)

**Comment by alex-Hudson** [comment]
This issue is fixed by PR https://github.com/vakata/jstree/pull/2557 @vakata
