### ISSUE TITLE
jstree的refresh()方法有问题

### ISSUE THREAD

**Issue by long5635152** [vakata/jstree#2235]
如果我用ajax方式加载树,之后调用refresh方法会报错,报错后再调用一次refresh方法,就会一直显示"loading"
![微信截图_20190419161221](https://user-images.githubusercontent.com/26703718/56414678-ee6d6b00-62bd-11e9-8eda-5d28a2eec10c.png)
![微信截图_20190419161329](https://user-images.githubusercontent.com/26703718/56414723-1957bf00-62be-11e9-81d8-f7fe17c8c32c.png)

**Comment by vakata** [comment]
Sorry, I can not understand the issue. As for the error - it is most likely due to an error in your data (duplicate ID, missing parent, etc).
