### ISSUE TITLE
Driving context menus from Javascript

### ISSUE THREAD

**Issue by pbrown12303** [vakata/jstree#2236]
I am using Agouti to test an app that includes jstree. Agouti lets me drive the user interface, selecting DOM elements via ID and directing mouse actions to DOM elements. It can also execute javascript. With this as background, I am trying to pick menu entries from a jstree context menu. I have figured out how to select the tree item and I can direct a right mouse event to the tree item, but I can't figure out how to navigate the resulting context menu. I suspect that the context menu items do not have IDs, so I can't select them that way. Is there a way to navigate the context menu and select a menu entry using javascript? Suggestions for alternative approaches are welcome!

**Comment by vakata** [comment]
A few simple selectors should do the trick ... either use numeric indexes (the contextmenu is a list inside the body), or match using the rel attribute on the anchors, or you could even use the item text to find a particular item (if you need to be absolutely sure you can always ask the devs to include a specific class name for each item):
![image](https://user-images.githubusercontent.com/146052/56617501-b43afb00-6628-11e9-835c-5c0e8bb6a5fe.png)
