### ISSUE TITLE
move_node('child','parent',0) call fails with "Moving parent inside child" for first child

### ISSUE THREAD

**Issue by cxw42** [vakata/jstree#2237]
[CodePen](https://codepen.io/anon/pen/KYxBjB) (open it and wait about 4 seconds).  I have a tree with only one parent node (ID `jparent`) and one child node (`jchild`).  I call:

    tree.move_node('jchild', 'jparent', 0);

and expect nothing to happen, since the child is already at position `0`.  Instead, I get a `check` error with the following fields:

    data: "{"chk":"move_node","pos":0,"obj":"jchild","par":"jparent"}",
    error: "check"
    id: "core_01"
    plugin: "core"
    reason: "Moving parent inside child"

That `check` call is [here](https://github.com/vakata/jstree/blob/3.3.7/src/jstree.js#L4025), and I think the `inArray()===0` test might not be right.  However, I am not sure.

I would like this call to be a no-op rather than an error.  Any ideas on what I'm doing wrong?  Is it actually a bug?  Thank you!

Tested with jstree 3.3.7 and jquery 1.10.2 (as used on the JSTree Demo page) on Chrome 73.0.3683.103 (Official Build) (64-bit) and Firefox 66.0.3 x86.

**Comment by vakata** [comment]
The error message is wrong - it should be that there is nothing to do. I will give this some thought, because not doing anything can be misleading and might break existing code, as other devs might expect either a success or a failure, and not doing anything might not be the best option. I lean towards a separate error for this, which you can ignore.

**Comment by cxw42** [comment]
@vakata Thanks for the response - I will adjust my own code to ignore the error in that case.  If you do decide to update jstree to make the nothing-to-do case an ignorable error, could it be distinguished by `id`, a new `ignorable` field, or something else other than `reason`?  Testing against a natural-language string seems risky to me from a maintenance perspective.  Much appreciated!

**Comment by vakata** [comment]
Of course, all errors have IDs (for example - the one you referred to is ```core_01```).
