### ISSUE TITLE
Deprecation notice for document.registerElement

### ISSUE THREAD

**Issue by twhetzel** [vakata/jstree#2240]
I'm seeing this notice in the console for jstree:
[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details. 

For Line 4697 `i.registerElement("vakata-jstree", {`

Will this be updated in a future version of jstree?

**Comment by vakata** [comment]
This is already fixed in 3.3.8 - you should not see such a warning on https://www.jstree.com/
