### ISSUE TITLE
Select only items that are filtered by search

### ISSUE THREAD

**Issue by Rikijs** [vakata/jstree#2242]
Hello!

I would like to be able to check all nodes that are visible when search filter is applied.
At the moment `select_all` and `deselect_all` really select all nodes even those hidden by search.
How can one accomplish that?

I think i found [discusson of this feature](https://github.com/vakata/jstree/pull/1696), yet i do not know how to implement it.

Thank you!

**Comment by vakata** [comment]
The pr you linked to is merged but the options apply to cascading. You can call ```check_node``` on you roots and the cascade options will take care of the rest: https://www.jstree.com/api/#/?q=checkbox.cascade

Let me know if I can help further.

**Comment by Rikijs** [comment]
Hello!

I have only one level of elements (files in given folder) with checkboxes.
So - no root is present in the tree.

**Comment by Rikijs** [comment]
Perhaps a resolution:
-- add `Root node` ,
-- hide it with CSS,
-- call JS to check root;

Is there a better option?

**Comment by vakata** [comment]
If you have a single level only then why go through all this trouble and not use a jQuery selector? Like ```$('#tree li:visible')```? You can pass the result set to the ```select_node``` function.

**Comment by Rikijs** [comment]
Your idea is clearly better then mine.
Though, my code checks only first element instead of all visible items.
Any idea what is wrong?
Do i need to prepare data from jquery object?

    $project_tree = $('#my_tree');

    $check_uncheck.on('click', function (event)
    {
        let $select_status = $(this).attr('data-select-status');
        $select_all_status = parseInt($select_all_status, 10);

        let $visible_node_ids = $project_tree.find('li:visible');
        console.log($visible_node_ids);

        if ($select_all_status === 1)
        {
            $project_tree.jstree('select_node', $visible_node_ids);
            $(this).attr('data-select-all-status', '0');
        }
        else if ($select_all_status === 0)
        {
            $project_tree.jstree('select_node', $visible_node_ids);
            $(this).attr('data-select-all-status', '1');
        }
    });

**Comment by Rikijs** [comment]
Used `jQuery each` to go trough every visible li element. Now it  works.
