### ISSUE TITLE
Sort tree elements by value of data attribute

### ISSUE THREAD

**Issue by Rikijs** [vakata/jstree#2243]
Hello!

I am using `jsTree` to display `folder and file tree` structure that consists of folders and files on disk. Of course files have extensions and alphabetical order does not sort *right*. Sort option: `by type` is closest to what i want to achieve.

As i see `sort` plugin sorts alphabetically by name of each node.
I would like to sort tree elements by value of custom data attribute - that would consist of `extension + fileName + uuid`.

Code example would be terrific.

Thank you!

**Comment by vakata** [comment]
The sort plugin has a single option - a callback - a regular js sorting function, that enables you to create compl;ex sorting (the same way as sorting an array in pure JS): https://www.jstree.com/api/#/?q=sort&f=$.jstree.defaults.sort

**Comment by Rikijs** [comment]
Hello!

Here is sorting function that should sort by type and name.
Yet, i keep getting `attr is not a function`...

    "sort" : function(a, b)
    {
        let a1 = this.get_node(a);
        let b1 = this.get_node(b);
        console.log(a1);
        console.log(b1);
        if (a1.attr('data-item-sort-value') === b1.attr('data-item-sort-value'))
        {
            return (a1.attr('data-item-sort-value') > b1.attr('data-item-sort-value')) ? 1 : -1;
        }
        else
        {
            return (a1.icon > b1.icon) ? 1 : -1;
        }
    }

I also tried:
 1. a1.getAttribute('data-item-sort-value')... got `TypeError: a1.getAttribute is not a function`
 2. a1.data('item-sort-value')... got `TypeError: a1.data is not a function`

How can one get data attribute of node in sort function?

Help would be appreciated.
Thank you!

**Comment by Rikijs** [comment]
https://imgur.com/ezyQBop
Data attribute `data-item-sort-value` is displayed in console.
Yet i can not seem to access it!

**Comment by Rikijs** [comment]
Created[ question on StackOverflow](https://stackoverflow.com/questions/55983706/how-to-access-node-data-attribute-inside-jstree-sort-function)

**Comment by Rikijs** [comment]
Here is working sort function that uses data attribute values.

    'sort' : function(a, b)
    {
        let a1 = this.get_node(a);
        let b1 = this.get_node(b);
        let isv_a1 = a1.a_attr['data-item-sort-value'];
        let isv_b1 = b1.a_attr['data-item-sort-value'];

        return (isv_a1 > isv_b1) ? 1 : -1;
    }
