### ISSUE TITLE
Create node not working when children:true

### ISSUE THREAD

**Issue by symon01107** [vakata/jstree#2245]
Hello, looks like I am stuck here. I am using latest version of JStree
I have following JSON

```
{
 "id": "ajson_" + index, "parent": "ajson_" + category,  "text": item.SubCategory, "children": true
}
```

I am creating node with following code
`$('#jstree_div').jstree('create_node', currentNodeID, node, 'last');`

This create node is not working when     "children": true in the JSON. But otherwise it works. 
I am showing empty node primarily but later creating children on click event

**Comment by vakata** [comment]
Setting children to true means that the children will be loaded at a later time. When you try to create a node inside the node jstree must first load the children (as the node is marked as having children) before creating the new node inside. When loading fails (which I presume is what is happening to you) the node will not be created.
