### ISSUE TITLE
Bad parent in node

### ISSUE THREAD

**Issue by rromus** [vakata/jstree#2246]
Hello!
Version jstree 3.3.8.   data.url = json
Problem: When make a   instance.refresh_node (node_id).  From node.parent  = node.id

In function _append_json_data (): 
args = {
	'df'	: this._model.default_state,
	'dat'	: data,
	'par'	: dom.id,
	'm'		: this._model.data,
	't_id'	: this._id,
	't_cnt'	: this._cnt,
	'sel'	: this._data.core.selected
},
The value is incorrectly assigned  'par'	: dom.id
Must be - 
			var par = dom.parent;
			if(dom.id == '#') par = '#';

			var w = null,
				args = {
					'df'	: this._model.default_state,
					'dat'	: data,
					'par'	: par,
					'm'		: this._model.data,
					't_id'	: this._id,
					't_cnt'	: this._cnt,
					'sel'	: this._data.core.selected
				},

**Comment by vakata** [comment]
When refreshing a node you should return the children of the node, not the actual node. Please provide a demo of the issue, because I do not understand the problem.

**Comment by vakata** [comment]
Will reopen when a demo is available.
