### ISSUE TITLE
All jstree nodes need to collapse on load 

### ISSUE THREAD

**Issue by Akash1858** [vakata/jstree#2247]
Hi,
I try to load a tree with all nodes closed.

i tried all posiible way to do it. but it's not working.
i also try above solution but still no luck :(
can anybody help me on this.
here is my code.

$j("#jstree").jstree({
"plugins": ["changed","checkbox","types","wholerow","themes", "contextmenu","dnd","search"],
"checkbox" : { "three_state" : false},
"types" : { "file" : { "icon" : "jstree-file" } },
"core" : {
themes: {"stripes": true},
state : { "opened" : false },
check_callback : true,
animation : 0,
"check_callback" : function (op, node, par, pos, more) {
var profilename = '{!$Profile.Name}';
if(op === "move_node"){

                      if(decodeHTML(node.text) =="Email Comms" || decodeHTML(node.text) =="Electricity Drawing" || decodeHTML(node.text) =="Safe Dig" || decodeHTML(node.text) =="Line Search" || decodeHTML(node.text) =="Expired"  || decodeHTML(node.text) =="Job Pack"  || decodeHTML(node.text) =="JobDocs" || decodeHTML(node.text) =="Completed supplier JobDocs (PAPERREC)"  || decodeHTML(node.text) =="General Job Docs" || decodeHTML(node.text) =="Surv/DNO/Inv/M&C" || decodeHTML(node.text) =="DNO Invoices" || decodeHTML(node.text) =="Meter & Certs" || decodeHTML(node.text) =="Survey"   ){ console.log('11111'); return false; }
                      if(btBoxITMovePublicGrp=='true' && IsbtSteriaGroupMove=='false'){
                           console.log('btBoxITMovePublicGrp 11 = ' + btBoxITMovePublicGrp);
                          if( ( (String(node.parents).includes(SafeDigNodeID) && SafeDigNodeID!='') || ( String(node.parents).includes(LineSearchNodeID) && LineSearchNodeID!='' ) || ( String(node.parents).includes(ExpiredID) && ExpiredID!='' ) || ( String(node.parents).includes(zoiID) && zoiID!='' ) ) && ((par.text=="Line Search" && btBoxITMovePublicGrp =='true') || (par.text=="Safe Dig" && btBoxITMovePublicGrp =='true') || (par.text=="Electricity Drawing" && btBoxITMovePublicGrp =='true') || (par.text=="Expired" && btBoxITMovePublicGrp =='true') || (par.text=="ZOI" && btBoxITMovePublicGrp =='true'))){
                              console.log('btBoxITMovePublicGrp 33 = ' + btBoxITMovePublicGrp); 
                              return true;
                           }
                          else { return false; }
                        }
                        else if(IsbtSteriaGroupMove=='true' && btBoxITMovePublicGrp=='false'){
                           console.log('IsbtSteriaGroupMove 11 = ' + IsbtSteriaGroupMove);
                          if( (String(node.parents).includes(generalJobDocs) && generalJobDocs!='') && ((par.text=="Line Search" && IsbtSteriaGroupMove =='true') || (par.text=="Safe Dig" && IsbtSteriaGroupMove =='true') || (par.text=="Electricity Drawing" && IsbtSteriaGroupMove =='true'))){
                              return true;
                           }
                          else { return false; }
                        }
                        else if(btBoxITMovePublicGrp=='true' && IsbtSteriaGroupMove=='true'){
                           console.log('btBoxITMovePublicGrp 11 = ' + btBoxITMovePublicGrp);
                          if( ( (String(node.parents).includes(generalJobDocs) && generalJobDocs!='') || (String(node.parents).includes(SafeDigNodeID) && SafeDigNodeID!='') || ( String(node.parents).includes(LineSearchNodeID) && LineSearchNodeID!='' ) || ( String(node.parents).includes(ExpiredID) && ExpiredID!='' ) || ( String(node.parents).includes(zoiID) && zoiID!='' ) ) && ((par.text=="Line Search" && btBoxITMovePublicGrp =='true') || (par.text=="Safe Dig" && btBoxITMovePublicGrp =='true') || (par.text=="Electricity Drawing" && btBoxITMovePublicGrp =='true') || (par.text=="Expired" && btBoxITMovePublicGrp =='true') || (par.text=="ZOI" && btBoxITMovePublicGrp =='true'))){
                              return true;
                           }
                          else { return false; }
                        }
                        else { return false;}
                    }
              },
                multiple: true,
                data : function (node, cb) {
                    loadNodes(this, node, cb);
                },
                 expand_selected_onload : false
            },
            contextmenu : { "items" : customMenu  , "select_node": true} 
        });

**Comment by vakata** [comment]
jstree does not open all nodes by default - if the nodes are opened you either have manually set the ```opened``` state property of each node, or you call ```open_all`` in your code.
