### ISSUE TITLE
How i can get node opened depend on params in url?

### ISSUE THREAD

**Issue by WissemWEB** [vakata/jstree#2250]
For example i have URL like http://jstree/?pathofroottobeopened=rootnode1/subnode11/subnode111. So i can get parameters from URL by using `const urlParams = new URLSearchParams(window.location.search);
      const myParam = urlParams.get('pathofroottobeopened');` Where rootnode1 etc are names of nodes to be opened. In other words "how i can send user link to node, and when he goes to this link he get node opened" it should be like link to folder. I can use get_node, but it works only with #id, not by name, or path. Is it possible?

**Comment by vakata** [comment]
You could use a jQuery selector, or even better - traverse all nodes and find the IDs of the ones you need opened:
http://jsfiddle.net/hend973s/1/

**Comment by WissemWEB** [comment]
> You could use a jQuery selector, or even better - traverse all nodes and find the IDs of the ones you need opened:
> http://jsfiddle.net/hend973s/1/
Another one and i hope last question) How i can iterate in the same way if i don't use json. My htmltree generated on the server side like ul>li>ul>li and so on) and then the jstree called `$('#downloads_tree').jstree({
      'core'    : { 'dblclick_toggle': false },
      'state'   : { 'key' : 'statekey' },
      'plugins' : [ 'state' ]
    });`

**Comment by vakata** [comment]
You can still iterate in the same way. This code is iterating over jstree's internal node structure - it is always in that form no matter the tree source.
