### ISSUE TITLE
Can not update the property three_state to true after having loaded the data to the tree using ajax, because when I load it I set it to false

### ISSUE THREAD

**Issue by NeiserDeveloper** [vakata/jstree#2251]
Although when I load the data I set the property three_state = false and when it finishes loading I want to update the property three_state = true I'm interested in this but it does not work help please.

$(function () {
                $.ajax({
                    async: true,
                    type: "POST",
                    url: "/Perfiles/GetTreeData",
                    dataType: "json",
                    success: function (data) {
                        createJSTrees(data);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status);
                        alert(thrownError);
                    },
                    complete: function () {
                        $('#onflycheckboxes').jstree({
                            checkbox: {
                                three_state: true
                            },
                            plugins: ["checkbox"]
                        })
                        $('#onflycheckboxes').jstree(true).refresh();
                    }
                });
          });

function createJSTrees(jsondata) {
                $('#onflycheckboxes').jstree({
                    'core': {
                        'data': jsondata,
                        "check_callback": true
                    },
                    "types": {
                        "default": {
                            "icon": "fa fa-folder"
                        },
                    },
                    checkbox: {
                        keep_selected_style: true,
                        three_state: false
                    },
                    "children": [{
                        "state": { "selected": true },
                        "icon": "fa fa-file",
                    }],
                    plugins: ["themes", "types", "json_data", "ui", "checkbox", "children"]
                });
            }

**Comment by vakata** [comment]
This property can not be toggled after the tree is initialized.
