### ISSUE TITLE
multiple selection only one event

### ISSUE THREAD

**Issue by ua4192** [vakata/jstree#2252]
Hi 

I have a jtree with thousands of nodes.

I have implemented my own search module using alsql library, the searc h goes very fast but when I want to select the results of the search I have the bottleneck because for each node selected I get a triggered event.
Would it be possible to  select multiples nodes by only firing one event?

Best regards

**Comment by vakata** [comment]
Either use the ```supress_event``` boolean:
https://www.jstree.com/api/#/?q=select_node&f=select_node(obj%20[,%20supress_event,%20prevent_open])

Or traverse the internal structure (```instance._model.data```) and set the selected state and also update the internal selected array. 

I would first try the former, then the latter - as a last resort - it is fairly easy to overwrite the trigger function and only trigger events as needed.
