### ISSUE TITLE
Using the alternative JSON format on large tree does not work

### ISSUE THREAD

**Issue by leiftrulsson** [vakata/jstree#2254]
I'm trying to load a very large tree (see attached file), more than 10000 nodes/leafs, using the alternative JSON format, but it doesn't load. I don't get any error messages (only the Loading animation is shown).

Smaller tree loads just fine and I'm using the same code to generate all trees, so I know the tree and its nodes are ok.

Regards
Leif

[alternative-tree.txt](https://github.com/vakata/jstree/files/3294002/alternative-tree.txt)

**Comment by vakata** [comment]
Seems to work fine (even on jsFiddle):
http://jsfiddle.net/foqgv5tz/

**Comment by leiftrulsson** [comment]
So my tree is generated by a PHP-pgm like this:

$('#treeviewArchiveServerArchive').jstree({
		'plugins': ["wholerow"],					
		'core' : {
			'data' : {
				"url" : "tree_data_serverarchive.php?t=",
				"dataType" : "json" 
			}
		}
	})

Where the the PHP-pgm generates the JSON-data that I included before.

Obviously there's nothing wrong with the data, but could it be that the call to the PHP-pgm takes to long time?
