### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded error - again

### ISSUE THREAD

**Issue by duzun** [vakata/jstree#2258]
I have a big tree: 30000 items in 5000 folders with a maximum depth of 19 parents. 
No duplicate IDs are possible, as I store each item by a string ID in the DB and fetch the list as an object with IDs at keys.

I use `massload` and `search` plugins, no worker (it is too slow).

When I do a search which returns more than a few thousand items and has to open more than a thousand folders, I get this error: **Maximum call stack size exceeded error** at [dist/jstree.js#L1990](https://github.com/vakata/jstree/blob/master/dist/jstree.js#L1990).

I've done some investigation and came to the conclusion that:

- jsTree makes extensive use of callbacks internally, even when not absolutely necessary (no async scenario, nor user's callback involved),
- `$.proxy()` that could be easily avoided by adding `var that = this;` in parent scope function. This could be handy in many cases and makes the code smaller after minification.
- \* anonymous function with the role of `$.proxy()`, when not even `$.proxy()` is required: eg. `this._append_json_data(obj, data, function (status) { callback.call(this, status); })` should be `this._append_json_data(obj, data, callback)`.

\* I've run a quick search and replace for `function (status) { callback.call(this, status); }` and got ride of **Maximum call stack size exceeded error**, which drives the conclusion that I've just extended the capacity of jsTree+massload, but did not fix the issue completely.

By modifying the code according to all cases described above, the capacity of jsTree could be extended even further.

To solve the issue completely, the chain of callbacks `massload._load_nodes() -> jstree._append_json_data() -> rslt() -> jstree._load_nodes() ...` should be broken with at least one async call ([setImmediate](https://github.com/YuzuJS/setImmediate), Promise or setTimeout?).

To me, the appropriate place to break the chain would be at [dist/jstree.js#L1990](https://github.com/vakata/jstree/blob/master/dist/jstree.js#L1990):

```js
setImmediate(rslt.bind(this), func(args), false);
```

or even better at [dist/jstree.js#L1938](https://github.com/vakata/jstree/blob/master/dist/jstree.js#L1938):

```js
setImmediate(cb.bind(this), true);
```
I'm curious to know your thoughts on this @vakata.

P.S. Great library!

**Comment by vakata** [comment]
Should be fixed by the merged PR

**Comment by duzun** [comment]
Cool, thanks!

I've done some work/experimenting with the other proposed solutions on [unproxy](
https://github.com/duzun/jstree/tree/unproxy) branch. This doesn't directly solve any issue after the merged PR, but I think improves the code by removing some intermediate functions.
