### ISSUE TITLE
Why does the loading indicator only appear once during the first search?

### ISSUE THREAD

**Issue by allipierre** [vakata/jstree#2264]
Hi,

Why does the loading indicator only appear once during the first search?

It doest not display for the second, third ,.... search.

It only display for the first search.

Thanks

**Comment by vakata** [comment]
The loading indicator only displays when nodes are about to be opened, but they are not yet loaded. On consequent searches your nodes are probably already loaded. Also - search typically loads the nodes first and then opens them, so the indicator is not shown.
