### ISSUE TITLE
Separate the click action on the check box of the item name click

### ISSUE THREAD

**Issue by VConsulting** [vakata/jstree#2265]
Hello,

I am looking to do a product category management via jsTree, I would like to separate the click from the checkbox of the select_node.

In fact two actions:
Check box: Saves the product that belongs to this category
Item Text: When clicked, I want to display a detail in another div to configure options in the category.

I can not separate the two actions, can you give a small example?

**Comment by vakata** [comment]
https://www.jstree.com/api/#/?q=tie_s&f=$.jstree.defaults.checkbox.tie_selection
