### ISSUE TITLE
Text outside a tag?

### ISSUE THREAD

**Issue by yondaimeorg** [vakata/jstree#2266]
Right now the current tree structure looks like:

    <div>
        <ul>
            <li>
                <a></a>
                    <ul>
                        <li>
                           <a></a>
                        </li>
                    </ul>
            </li>
        </ul>
    </div>

The text for the node appears between the `<a></a>` tags.

Is there anyway to create a node such that:

    <li><a>Text here</a> button here</li>

Thanks!

**Comment by vakata** [comment]
Yes - but you need to create a plugin that extends the method that draws a node. Search the issues for examples, or take a look at src/misc.js in this repo - it contains many plugin examples.
