### ISSUE TITLE
Some Help on sorting nodes

### ISSUE THREAD

**Issue by dorel14** [vakata/jstree#2267]
Hello , I'm new user of jstree and having some troubles in ordering my nodes:

My json looks like this
`

0 |  
-- | --
id | 19
parent | "#"
text | "Sujet flottant"
type | "themes"
position | "0"
rang | "1"
state | null
1 |  
id | 1
parent | "#"
text | "Il me faut un nouveau ....."
type | "themes"
position | "1"
rang | "2"
state | null
2 |  
id | 5
parent | "#"
text | "Ça part pas , ça arrive pas"
type | "themes"
position | "1"
rang | "3"
state | null
`
My jstree init is like this 
`$('#treeViewDiv').jstree({
      'core':{
        'themes':{
          "icons":true,
          "url":true
        },
        'check_callback' : true,
        'multiple' : true,
        "data":{
          "url":"/treviewjson",
        }
              },
      'checkbox': {
        "three_state": true,
        "cascade":'up',
      },
       'types' : {
                  "#" : { "max_children" : 1, "max_depth" : 4, "valid_children" : ["root"] },
                  "root" : { "icon" : "glyphicon glyphicon-th", "valid_children" : ["default"] },
                  "themes" : { "icon" : "/static/js/jstree/icons/baseline_receipt_black_18dp.png","valid_children" : ["default","question"] },
                  "question" : { "icon" : "/static/js/jstree/icons/baseline_chat_black_18dp.png", "valid_children" : [] }
                  },

      'plugins': ["themes", "checkbox",  "sort", "ui",  "changed", "search", "contextmenu", "types"]
    }
      );`

And my nodes are not sorted by position like i would like , what do i miss ?

Thx

**Comment by vakata** [comment]
You need to provide a sorting function in the initialization of the tree, that will be invoked when nodes need to be sorted:
https://www.jstree.com/api/#/?q=sort&f=$.jstree.defaults.sort
