### ISSUE TITLE
.delete_node is too slow when a lot of siblings

### ISSUE THREAD

**Issue by duzun** [vakata/jstree#2268]
I have a folder with 10000 nodes, and when I delete 100, it is very slow.
It redraws the whole parent node 100 time!

I've modified the sources to test an alternative:

```js
//...
var node = this.get_node(obj, true);

//...

if(node) node.remove();

// Instead of:
// this.redraw_node(par, true);
```

So far it works, and is much, much faster!
But I'm not sure I'm not breaking anything else.

**Comment by vakata** [comment]
It could break plugins that rely on the redraw_node event, or extend draw_node. I will give this some thought - thank you for reporting.

**Comment by vakata** [comment]
This is fixed in v.4 (which is early alpha) - I will not be improving this on v.3.
