### ISSUE TITLE
Help me somebody please!!!

### ISSUE THREAD

**Issue by neromont** [vakata/jstree#2269]
How I can open not loaded nodes?

I have this code: 

`<div id="jstree_ajax_demo"></div>
$(function() {   
   // AJAX loading JSON Example:
   $('#jstree_ajax_demo').jstree({
    'core': {
      'data': {
        "url" : "/ajax_children2.js",
        "dataType" : "json" 
      }
    },    
    "types" : {
      "default" : {
        "icon" : "glyphicon glyphicon-record"
      }
    },
     "plugins" : [ "types", "unique" ]
  });  
  $('#jstree_ajax_demo').on("changed.jstree", function (e, data) {
    console.log('ds: ' + data.changed.deselected);    
  });  
$("#jstree_ajax_demo").on
('loaded.jstree', function() {
 $("#jstree_ajax_demo").jstree("load_node","4"); // This worked
 $("#jstree_ajax_demo").jstree("load_node","5"); // Not worked
 });  
});
`
And this js:

`[{
  "id":1, "icon":"/cicon5.png", "text":"Root node","children":[
    {"id":2,"text":"Child node 1"},
    {"id":3,"text":"Child node 2"}
  ]
},
{
  "id":4,"text":"Root node 2","children":[
    {"id":5,"text":"Child node 1"},
    {"id":"myid","text":"Child node 2"}
  ]
}]`

Ask me please, how I can open not loaded node by id?

**Comment by neromont** [comment]
Sorry, not "load_node", I use "open_node".

**Comment by vakata** [comment]
I am afraid I do not understand the use case here - there is no way to open a node that does not exist. If you want to manipulate a node that is not yet loaded you need to first load all of its parents and then you can manipulate it.
