### ISSUE TITLE
IE11, EDGE visual glitches

### ISSUE THREAD

**Issue by egklt** [vakata/jstree#2270]
Jstree + types plugin. 

Grid lines disappears, background changes color while moving mouse.

edge.
https://gfycat.com/dimmarvelousgnatcatcher

ie11
https://gfycat.com/regularboweddeviltasmanian

**Comment by egklt** [comment]
Removing css effect solved my issue.

.jstree-default .jstree-anchor, .jstree-default .jstree-animated, .jstree-default .jstree-wholerow {
    transition:none !important;
}

**Comment by vakata** [comment]
That seems like a browser issue to me, so there is not much I can do on my end. Great that you have found a solution - this way if anyone has the same issue they will find your solution - thank you.
