### ISSUE TITLE
Loading plugins (checkbox)

### ISSUE THREAD

**Issue by davidvandertuijn** [vakata/jstree#2273]
I have some issues loading plugins, they do not seem to work. I installed jstree using `npm install --save jquery jstree`, and added `require("jstree");` to my app.js (Laravel). The tree itself is working perfectly, only the plugins are not working. i expect the .jstree-checkbox class in the html content, but this is currently missing.

This is my JavaScript code:

`<script>window.onload = function() {
    var role_id = $('input[name=role_id]').val();
    $("#tree").jstree({
        core: {
            plugins: [
                "wholerow",
                "checkbox"
            ],
            data: {
                url: "/settings/authorization/roles/rights/json/" + role_id
            },
            themes: {
                name: "proton",
                stripes: true,
                dots: false
            },
            checkbox: {
                three_state: false,
                whole_node: true,
                tie_selection: false
            }
        }
    }).on("check_node.jstree uncheck_node.jstree", function (e, data) {
        // not relevant
    });
}</script>`

And this is the JSON response:

[{"id":1,"parent":"#","text":"Settings","icon":"fa fa-cog","state":{"opened":false,"checked":false}}]

Screenshot:
https://imgshare.io/image/jstree-checkboxes.aXA89

Any suggestions?

**Comment by vakata** [comment]
When requiring jstree you are only including the core, each plugin you need has to be required separately.
