### ISSUE TITLE
Question: can I use element.QuerySelectorAll alternative in Search code for older browsers 

### ISSUE THREAD

**Issue by NilG99** [vakata/jstree#2275]
Hi,
Please do not treat this as bug or issue but rather I needed a suggestion from your end.
I know there is no support in jstree for older browsers , but I have a dire situation in my project where I have to support the jstree functionality in quirks mode.  I have made it work in all the cases apart from the search. The search uses document.querySelector and element[0].querySelectorAll. 
I have used polyfills to add the document.querySelector and document.querySelectorAll methods but I am not able to make the element[0].querySelectorAll method. Is there a way I can use an alternate code(jquery function or an external code) for the below part of the code even if there is a performance hit. Any help will be greatly appreciated, Thanks 

this._data.search.dom = $(this.element[0].querySelectorAll('#' + $.map(r, function (v) { return "0123456789".indexOf(v[0]) !== -1 ? '\\3' + v[0] + ' ' + v.substr(1).replace($.jstree.idregex,'\\$&') : v.replace($.jstree.idregex,'\\$&'); }).join(', #')));

**Comment by vakata** [comment]
jsTree supports very old browsers (IE8) but it does not support quirks mode - sorry about that. You could simply fork the repo and use your own version (with your fixes) and periodically update from the master repo in order to get the latest fixes.
