### ISSUE TITLE
jstree CreateNode Method

### ISSUE THREAD

**Issue by kaavithasatish** [vakata/jstree#2276]
Hello,

As per the design, create_node() method insert only one Node, but my requirement is to add up 50 nodes at a time. I have read in one forum that this change may be incorporated in future release. Is that done? 

Thanks.

**Comment by Oleg26Dev** [comment]
You can implement it using your own function, for example: parse and create nodes in loop etc

**Comment by vakata** [comment]
create_node is not intended for such operations. v.4 uses a separate model / visualization which supports what you need out of the box, but it is still in early alpha stage.
