### ISSUE TITLE
Jstree not loading with MeteorJS and browser-policy package

### ISSUE THREAD

**Issue by LaChips** [vakata/jstree#2277]
Hi,

I'm currently using MeteorJS and JsTree. I installed the browser-policy package that allows to set Content Security Policy and since, my trees won't load anymore.
It just displays "loading" but never load anything, I don't have any errors in browser console or server console.

Do you have an idea about what's causing this ?

Thanks.

EDIT : False problem, sorry for that, I just needed to allow blob in my browser-policy : BrowserPolicy.content.allowOriginForAll('blob:');

EDIT #2 : It's working in localhost, but not on the online version.

**Comment by vakata** [comment]
jstree uses blobs and data if core.worker is enabled. Set your CSP reporting URL and it will display exactly what the violations are, this is something you need to configure on your side.
