### ISSUE TITLE
jsTree not working after jQuery upgrade

### ISSUE THREAD

**Issue by udayathays** [vakata/jstree#2281]
Hi

I have upgraded my application from jQuery 1.8.2 to jQuery 3.3.1, but after this change my jsTree functionality is not working. it is giving me error like :Uncaught TypeError: $(...).jstree(...).get_node is not a function.

What do i need to make it work. Is jsTree not compitable with jQuery 3.3.1.

I am using jsTree 3.3.3

**Comment by Oleg26Dev** [comment]
I have returned back to 
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
and now jstree works.

**Comment by vakata** [comment]
jsTree 3 is fully compatible with jQuery 3, but keep in mind the version you are using is almost 3 years old - I'd upgrade jQuery and jsTree.
