### ISSUE TITLE
How to pass icon via ajax function?

### ISSUE THREAD

**Issue by Oleg26Dev** [vakata/jstree#2284]
ASP.NET
I'd like to create tree using data from database.
I read the data in the controller method. The . But how can I provide icon from the controller?

**Comment by vakata** [comment]
The same way you provide the node title - it is just a property named ```icon``` - you can either use a class, or a path to a file.

**Comment by Oleg26Dev** [comment]
Ok, thanx, I mean not the file path to icon located in wwwroot/.../file, but image blob from database.
For example, I read in Controller 
"select name, icon from nodes where ...."
and pass node information to jstree in view 
Now I read hierarchy to build the tree except icons
