### ISSUE TITLE
How to build and use my own context menu?

### ISSUE THREAD

**Issue by Oleg26Dev** [vakata/jstree#2285]
For example, how to add to the context menu:
...
Search
Refresh
..

Search - it should be the same search plugin which used by button as in your examples but Search in sub-tree, "search from here"

Refresh - it should be  possibility to refresh sub-tree starting from selected node where menu was clicked or entire tree if it is root.
My app works with database and somebody works with db too and I need to refresh etc.

**Comment by vakata** [comment]
This is the config option you need:
https://www.jstree.com/api/#/?q=contextmenu.item&f=$.jstree.defaults.contextmenu.items

You can use the default actions as an example:
https://github.com/vakata/jstree/blob/master/src/jstree.contextmenu.js#L60

**Comment by win32nipuh** [comment]
Thanx!
