### ISSUE TITLE
How to use forecolor in node text?

### ISSUE THREAD

**Issue by win32nipuh** [vakata/jstree#2287]
I'd like to display some nodes using different colors.
How can I change foreground color for node?

**Comment by vakata** [comment]
You have full control over what classes are applied to each node. You can then use those classes in your css to style the elements:
https://github.com/vakata/jstree#the-required-json-format (li_attr and a_attr)

**Comment by win32nipuh** [comment]
Ok, thnx. 
How can I pass the color attribute from controller via ajax method?

**Comment by win32nipuh** [comment]
Ok, thnx. I did not find any examples with attributes. 
Could you please show an example how to pass to json style="color:#ff0000" for nodes text?
