### ISSUE TITLE
How to pass search parameters dynamically?

### ISSUE THREAD

**Issue by win32nipuh** [vakata/jstree#2289]
I have a search dialog where user enters search string and can set some parameters like

```
case_sensitive
fuzzy
show_only_matches
```
etc

How can I pass these parameters to jstree search every time when user does search?

```
$(document).ready(function () {
            $(".search-input").keyup(function () {
                var searchString = $(this).val();
                $('#SimpleJSTree').jstree('search', searchString);
            });
        });

```

**Comment by vakata** [comment]
Some of those are already available as parameters:
```this.search = function (str, skip_async, show_only_matches, inside, append, show_only_matches_children)```
You can also change the ```.settings.search``` object before invoking ```search()``` - the new values will be picked up.
