### ISSUE TITLE
get_selected method does not sort

### ISSUE THREAD

**Issue by kvelaro** [vakata/jstree#2290]
I need to select only one node at a specified time. 
Didn't find anything useful on inet, and did it my way.
Logic is pretty simple. Find all selected nodes and find user selected node.
In loop check if user selected node is equals to selected node[i]. If it's not then deselect, otherwise select.
```
$("#<?=$jstreeId;?>").on("select_node.jstree", function (event, data) {
            let selectedItem = data.node.id;
            var isLeaf = $("#<?=$jstreeId;?>").jstree(true).is_leaf(selectedItem);
            if(isLeaf == false) {
                return false;
            }
            let selected = $("#<?=$jstreeId;?>").jstree(true).get_selected();
            selected.forEach((item) => {
                if(item != selectedItem) {
                    var node = $("#<?=$jstreeId;?>").jstree(true).get_node(item);
                    console.log('desel:' + item)
                    $("#<?=$jstreeId;?>").jstree(true).deselect_node(
                        node
                    );
                }
                else {
                    console.log(item)
                }
            });
});
```
It works, but not with all nodes. Somehow get_selected method returns child node first and then parent node. Not as I guess it should be. 

To be precise, I select child node, and step after I see parent id, which is not equal to user selected id, and deselect parent (so child is deselected).

Question is: Why get_selected method returns in arbitrary order, is this correct behaviour?

**Comment by vakata** [comment]
One node at a time is achieved with ```settings.core.multiple``` set to ```false```
