### ISSUE TITLE
JSON from the database as an object, not just a simple array (e.g. generated with JSON_FORCE_OBJECT for json_encode)

### ISSUE THREAD

**Issue by spam1** [vakata/jstree#2291]
I'm creating (for jstree) the flat JSON format like that:
http://myjson.com/ndo9j

But as I'm using that data in a few different places, it will be great to use an "object" format with keys like:
http://myjson.com/axppz
So I can have quick access (by key/id) to the selected element.

Is it possible in some simple way?

**Comment by vakata** [comment]
You can always use ```core.data``` as a function, get the data from an AJAX call, transform the object to an array and then pass it to jstree, while at the same time using the original object as you please.
