### ISSUE TITLE
load_node breaks tree structure

### ISSUE THREAD

**Issue by gh0stwizard** [vakata/jstree#2293]
Hi,
I have using jstree with ajax. On first load I build full tree. Later on an user may do actions on nodes. When an action is completed I refresh the node and its children via `load_node`. But jstree breaks structure after this call. See the illustration below:
![jstree_load_node_dots_bug](https://user-images.githubusercontent.com/4180049/63255027-7cae2980-c27d-11e9-9e52-92ae724c077a.png)

Am I doing this wrong or it is a bug?
Thank you.

**Comment by gh0stwizard** [comment]
Workaround:
```js
function reloadNode(treeid, nodeid) {
    var isLast = $($(treeid).jstree(true).get_node(nodeid, true)).hasClass('jstree-last');
    $(treeid).jstree(true).load_node(nodeid, function (node, status) {
        if (!status || isLast) return;
        $($(treeid).jstree(true).get_node(nodeid, true)).removeClass('jstree-last');
    });
}
```
As I see, there is something wrong with re-calculating internal values of node.parent, node.parents.

**Comment by gh0stwizard** [comment]
I am not sure, if the patch below is correct. The core issue is that `node.parents` and `parent_node.children_d` properties are contain the duplicate value of `node.id` when `load_node(node.id)` is called.
At the moment I can not check the case when a new node must be added via ajax call, a volunteer needed.
```diff
--- old/jstree.js
+++ new/jstree.js
@@ -1623,7 +1623,7 @@
 						parse_flat = function (d, p, ps) {
 							if(!ps) { ps = []; }
 							else { ps = ps.concat(); }
-							if(p) { ps.unshift(p); }
+							if(p && ps.indexOf(p) == -1) { ps.unshift(p); }
 							var tid = d.id.toString(),
 								i, j, c, e,
 								tmp = {
@@ -1710,7 +1710,7 @@
 						parse_nest = function (d, p, ps) {
 							if(!ps) { ps = []; }
 							else { ps = ps.concat(); }
-							if(p) { ps.unshift(p); }
+							if(p && ps.indexOf(p) == -1) { ps.unshift(p); }
 							var tid = false, i, j, c, e, tmp;
 							do {
 								tid = 'j' + t_id + '_' + (++t_cnt);
@@ -1837,13 +1837,15 @@
 						}
 						// 3) normalize && populate parents and children_d with recursion
 						for(i = 0, j = p.children.length; i < j; i++) {
-							tmp = parse_flat(m[p.children[i]], par, p.parents.concat());
+							tmp = parse_flat(m[p.children[i]], p.parent ? p.parent : par, p.parents.concat());
 							dpc.push(tmp);
 							if(m[tmp].children_d.length) {
 								dpc = dpc.concat(m[tmp].children_d);
 							}
 						}
 						for(i = 0, j = p.parents.length; i < j; i++) {
+							if (m[p.parents[i]].children_d.indexOf(par) >= 0)
+								m[p.parents[i]].children_d.splice(m[p.parents[i]].children_d.indexOf(par), 1);
 							m[p.parents[i]].children_d = m[p.parents[i]].children_d.concat(dpc);
 						}
 						// ?) three_state selection - p.state.selected && t - (if three_state foreach(dat => ch) -> foreach(parents) if(parent.selected) child.selected = true;
@@ -1858,7 +1860,7 @@
 					}
 					else {
 						for(i = 0, j = dat.length; i < j; i++) {
-							tmp = parse_nest(dat[i], par, p.parents.concat());
+							tmp = parse_nest(dat[i], p.parent ? p.parent : par, p.parents.concat());
 							if(tmp) {
 								chd.push(tmp);
 								dpc.push(tmp);
@@ -1870,6 +1872,8 @@
 						p.children = chd;
 						p.children_d = dpc;
 						for(i = 0, j = p.parents.length; i < j; i++) {
+							if (m[p.parents[i]].children_d.indexOf(par) >= 0)
+								m[p.parents[i]].children_d.splice(m[p.parents[i]].children_d.indexOf(par), 1);
 							m[p.parents[i]].children_d = m[p.parents[i]].children_d.concat(dpc);
 						}
 						rslt = {

```

**Comment by vakata** [comment]
You most probably have duplicated IDs.

**Comment by gh0stwizard** [comment]
The case is that I am just reloading the data of a node. Of course, it has the same ID! An this is a bug then jstree does not understand that.

**Comment by vakata** [comment]
Please provide a demo of the issue and I will help. By duplicated IDs I mean different nodes with the same ID.

**Comment by gh0stwizard** [comment]
I just tried the call `refresh_node`, the result is the same as with `load_node`. I may produce a demo, but it will take some time. The case in details:
```js
[
// Huge tree is loaded upon jstree initialization.
{
  id: 1,
  children: [
   {
     id: 2,
     children: [
       {
          id: 200,
       }
     ]
   },
   {
     id: 3
   }
  ]
},
...
{
   id: 1000
},
]
```
Later on, as I said, is called `load_node` for existing nodes to reload internal data of nodes.
Important moment is that the result on server side for `load_node` is just a node data without any footprint about parents, for instance, `load_node(2)` will return:
```js
{
   id: 2,
   children: [
     {
        id: 200,
     }
   ]
}
```
As you see there is no more information about which parent is (id = 1).

**Comment by gh0stwizard** [comment]
I have made the demo: https://jsfiddle.net/b156sLrq/
Reload node 1 to see the issue.

**Comment by vakata** [comment]
The server response for load_node(2) should only include the children of that node, not the node itself. So in your example - that would be:
```
[
     {
        id: 200,
     }
   ]
```
