### ISSUE TITLE
DND not working properly when initialized from Promise

### ISSUE THREAD

**Issue by xeinebiu** [vakata/jstree#2295]
When initializing the JSTREE from a Promise, the DND does not work properly.

`  setTimeout(() => {
      this.treeView.setData([{
        id: '1',
        name: 'Hello',
        parentId: '#',
        tag: 'I am tag one'
      }, {
        id: '2',
        name: 'Folder 2',
        parentId: '1',
        tag: 'I am tag two',
        hasChildren: true
      }, {
        id: '3',
        name: 'Folder 3',
        parentId: '1',
        tag: 'I am tag three',
        hasChildren: true
      }], options);
    }, 1000);`

setData():void is an TypeScript method which does follow the wiki how to init and set the data on JSTREE.

[Watch the gif Preview](https://media.giphy.com/media/Vbnzz0fdbdQBP7xAln/giphy.gif)

**Comment by vakata** [comment]
Please provide a jsFiddle (or some other demo of the issue), are there any error messages in the console? DND is not affected by timeouts in any way. Please provide a demo and I will reopen.

**Comment by xeinebiu** [comment]
> Please provide a jsFiddle (or some other demo of the issue), are there any error messages in the console? DND is not affected by timeouts in any way. Please provide a demo and I will reopen.

Please find the demo project on the link below
[https://stackblitz.com/edit/angular-kehuis](https://stackblitz.com/edit/angular-kehuis)

**Comment by vakata** [comment]
I believe any errors you may encounter should be reported to the creator of the angular directive. This is not something I maintain.
