### ISSUE TITLE
 How to use move_node.jstree cancel the node move?

### ISSUE THREAD

**Issue by qiushicai** [vakata/jstree#2296]
version3.3.8. How to implement this behavior?
```js
$(jstree).on('move_node.jstree', function (e, data) {
    if (condition fails) {
    return false; //cancel move.
    }
    if(update db fails){
    return false; //cancel move .
    }
    //go on...
    return true; //do move.
})
```
If you use the check_callback.move_node operation, this function will be called many times and is not suitable for updating the database. You cannot get old_parent and new_parent at the same time.
```js
var count = 0;
"check_callback": function (operation, node, node_parent, node_position, more) {
        if (operation == 'move_node') {
            //called many times . it is not suitable for updating the database
            console.log(++count);
            if (condition fails or update db fails)) {
                return false; //cancel
            } 
            //move node  
            return true;
        }
    }
```

**Comment by vakata** [comment]
```check_callback``` is the way to go if you want to prevent something (it will be called many times if using drag'n'drop but you can always filter by who initiated the check (found in the ```more``` object)).  You can get all needed parents.
The ```move_node.jstree``` event signals that something has already happened - it should be used for DB sync. It is too late to cancel in the event handler, but you could sync to DB on some condition and on other - refresh the tree.
