### ISSUE TITLE
Disable Checkbox not working

### ISSUE THREAD

**Issue by Herz3h** [vakata/jstree#2298]
When I do disable_checkbox on a node, it doesn't work. Doing disable_node with same node disables the node but then it becomes grayed out which I do not want.

Here is how I initialized jstree:

```
                treeCheckbox.jstree({
                    'checkbox': {
                        'three_state':false,
                        'tie_selection': false
                    },
                    "plugins": ["checkbox", "themes"],
                });
``` 

jstree version: 3.3.8

**Comment by vakata** [comment]
Please provide an example so that I can see which  part is not working. If the only problem is the graying out - you can override it in your own CSS.
