### ISSUE TITLE
Using overflow:wrap with break-any

### ISSUE THREAD

**Issue by desaija-lilly** [vakata/jstree#2300]
I'm trying to account for leaf nodes with large names, and using the following works adequately:

jstree-anchor:hover{
    overflow: visible;
    white-space: normal;
    height:auto;
    width:260px; 
    overflow-wrap: break-word;
}"

however most of the leaf names are one long underscore separated word, and I'd like to break anywhere.  I tried using "break-any" as an option but that's not available.  So using the above, it starts the wrap on a new line. A little clunky.   If you notice, break-word does work fine when the word has a hyphen.

![image](https://user-images.githubusercontent.com/23194002/64050917-7c4c4300-cb47-11e9-8bec-39711367c51d.png)

![image](https://user-images.githubusercontent.com/23194002/64050960-94bc5d80-cb47-11e9-896c-9b584f3c7e77.png)

**Comment by vakata** [comment]
This is not something I can solve in jstree itself. Most of the time I either use a scrollbar or ellipsis. Officially - multiline nodes are not supported - they might work, but are not tested.
