### ISSUE TITLE
drag and drop

### ISSUE THREAD

**Issue by yriiarutiunian** [vakata/jstree#2304]
Hello!
How do I prevent copying a node after drag and drop?
can't find this out in documentation :(

**Comment by vakata** [comment]
```core.check_callback``` is what you need.

**Comment by yriiarutiunian** [comment]
Thank you for your response. but i also need the copyNodeCB function to be called anyway, cuz this is the way i check if the node can be inserted into the tree. technically, i need every node to be allowed being draged and droped into another tree, but after i drop the node, i need this node not to be inserted, but copyNodeCB to be called, cuz there's checking on the server side, and if its okay, i manage the response from server how i should insert this node.

**Comment by yriiarutiunian** [comment]
dnd_stop.vakata doesn't work either

**Comment by yriiarutiunian** [comment]
make story short i wanna prevent copying node after it's been dropped.

**Comment by vakata** [comment]
If you have already allowed for the copy to happen (copyNodeCB has already been called), the only way to "revert" it is to refresh your tree from the server (where the changes would not be applied). What this means is - call data.instance.refresh() if you want to "revert" the drop.

**Comment by yriiarutiunian** [comment]
Unfortunatly, thats not the case for me either, cuz everything what happens
is happen to trees over some protocol, which tell how the trees should be
updated, it might be the next operations: insert, update or delete. so
technically i don't have to change anything with tree on the client side,
cuz at some point the server will tell me what to do, after i drop a node
from one tree to another server has to tell me if its possible or not, so i
can kinda delete the node after the drop and wait for the response or i can
leave the node hanging out in the air kinda after the drop waiting for the
another response from the server which is kinda like ok bro you're allowed
to drop this node into that node.

сб, 12 окт. 2019 г. в 20:21, Ivan Bozhanov <notifications@github.com>:
