### ISSUE TITLE
State Plugin Bug? - Custom Markup duplicates

### ISSUE THREAD

**Issue by johnnytolengo** [vakata/jstree#2305]
I need to add a custom markup (div,span,text,etc..) to the node I am using "node_customize" plugin, the thing is that it duplicates or run twice when the "state" plugin is on. Seems to be a but inside the  "state" plugin.
Eg: I want to add a letter "G" after the node text. results->
```
----Main G
    |---- Hello G
              |---- One G
              |---- Two G
    |---- House G
              |---- Red G G         <<-- here duplicates on opened sub-nodes
              |---- White G G       <<-- here duplicates on opened sub-nodes

```
I use the plugin in this way:

```
node_customize: {
				default: function(el, node) {
					$(el).find('a').append(" G")
				}
			}
```

node_customize plugin:
```
(function ($, jstree, undefined) {
	"use strict";
	
	if($.jstree.plugins.node_customize) { return; }

	$.jstree.defaults.node_customize = {
		
		"default": null
	};

	$.jstree.plugins.node_customize = function (options, parent) {
		
		this.redraw_node = function (obj, deep, callback, force_draw) {
			var node_id = obj;
			var el = parent.redraw_node.apply(this, arguments);
			console.log(el)
			
			
			if (el) {
				var node = this._model.data[node_id];
				var cfg = this.settings.node_customize;
				
				if(cfg.default)
					cfg.default(el, node);
			}
			return el;
		};
	}
})(jQuery);
```

Any idea how to fix it?

**Comment by johnnytolengo** [comment]
I is not a bug in the "state" plugin, confirmed. 
The issue also occour when use:  ` $("#jstree").jstree("show_all");`
It duplicates, triplicates the added "G" letter or whatever thing.
I am still looking for a solution, for sure is a bug somewhere.

**Comment by vakata** [comment]
```$(el).find('a').append(" G")``` will find all descendants of the current node. Try ```children``` instead.

**Comment by johnnytolengo** [comment]
`children`  fix this issue. 
It helped me so much.

Thank you
