### ISSUE TITLE
Error at error reporting

### ISSUE THREAD

**Issue by ivangrozni** [vakata/jstree#2306]
Hello,

I've been using jstree minified files that are attached to entity_reference_tree drupal module (https://www.drupal.org/project/entity_reference_tree) (I think it is 3.3.7 version). I had an error at parent referencing in json object that was given to this library and instead of getting to print out error I was getting 
  `this._data is undefined`
in console. 
I think I should be getting this error out: https://github.com/vakata/jstree/blob/70b13cc8de8275308f92619f2e08a455a8126faa/src/jstree.js#L1837

I am not sure whether this issue was taken care of at newer the newer version but I am reporting it, because it took me some time to figure out was going on.

**Comment by vakata** [comment]
Thank you for reporting. Yes, this was fixed exactly a year ago today:
https://github.com/vakata/jstree/commit/e719ced1f061fbfbe7c93648237114d2fa7fc9b2

**Comment by ivangrozni** [comment]
Ok, sry for reporting then, I'll paste this to drupal.org.
