### ISSUE TITLE
Collapse all when DIV loses focus?

### ISSUE THREAD

**Issue by Erik-2019** [vakata/jstree#2308]
I've been looking for the last 2 days for a solution and have been unable to find one.
Is there a way to trigger close_all when the tree DIV loses focus?

I've tried the following but the event fires every time you click on a new item in the tree.
`
$('#'+returnDiv)
.on('focusout.jstree'   , function () { console.log('focus out jsTree');   })
.on('focusout'          , function () { console.log('focus out');          })
.on('unset_focus.jstree', function () { console.log('unset focus jsTree'); })
.on('unset_focus'       , function () { console.log('unset focus');        })
.on('blur.jstree'       , function () { console.log('blur jsTree');        })
.on('blur'              , function () { console.log('blur focus');         });`

Thanks

**Comment by vakata** [comment]
Sorry, I can not think of a solution except monitoring the selected element (I believe there is a document level event for that) and then checking if its parent is a tree, and if not - collapse the tree - that should do the trick, but it will be a document level event handler.
