### ISSUE TITLE
How to use Material icons in custom type theme.

### ISSUE THREAD

**Issue by aloksoni11** [vakata/jstree#2310]
HI,
I want to use a jstree in the materializecss theme. I try to create a custom type plugin with material icons but not success. Can you please help me to get material icons with custom type plugin in jstree.
Thanks in advance.

**Comment by vakata** [comment]
Sorry, I do not use those - how are they applied? jsTree expects a class name. You could also inspect the element and check if the material icon is overridden by jstree's icon because of selector strength. If this does not help - please provide an example and I will reopen.
