### ISSUE TITLE
Jstree lazy loading search with massload

### ISSUE THREAD

**Issue by xchange95** [vakata/jstree#2311]
Hello!

We are trying to implement Jstree with lazy loading and massload on search. So far so good for loading independent nodes on ajax calls but I cannot figure out how to config the massload to load nodes on search. 

This is an example of a search via GET:

`.../api/app-nodes/nodes/search?str=User%20stars`
Response: `["7d334061-9805-41c3-90b7-c39938a204bc"]`

Now, when massload requests on /api/app-nodes/nodes via POST, we send the following ids in the body: 
`ids: 7d334061-9805-41c3-90b7-c39938a204bc`

The response I am returning from the serverside looks like this:
`{ 
   "7d334061-9805-41c3-90b7-c39938a204bc":[ 
      { 
         "id":"root",
         "text":"root",
         "children":true,
         "type":"root"
      },
      { 
         "id":"96dad54a-e3a7-48d9-bf69-306778889931",
         "text":"root-leaf1",
         "children":true,
         "type":"area"
      },
      { 
         "id":"84877ebc-bcfd-4565-b28e-2fddc5e4f8a6",
         "text":"root-leaf2",
         "children":true,
         "type":"entity"
      }
   ]
}`

The nodes are a representation of:  'destination' : [{ # (tree's top parent), root-parent, sub-parent1, sub-parent2  }]

Still, the jstree won't load the nodes when the search finished. What is wrong?

**Comment by vakata** [comment]
The search ajax response should include which IDs need to be expanded in order to reveal the search results.

Then massload will fetch those in a single pass. All those IDs (of nodes which need to be expanded) will be sent to the server.

The response should be in the format:
```node-id : [children-of-that-node]```

**Comment by xchange95** [comment]
So the search of a random node should include all it’s recursive parents untill the root node of the tree? 

It is a bit unclear for me how the responses should look like. Maybe you can provide a simple example of searching a let’s say 3rd level of depth node, providing the responses of how the massload response needs to be returned to the browser.
