### ISSUE TITLE
RTL Support with whole row plugin

### ISSUE THREAD

**Issue by mubbo** [vakata/jstree#2312]
The Whole Row plugin does not work correctly with RTL support.. the mouse over as well as the selected div shows in the wrong position

see fiddle for example of problem

http://jsfiddle.net/0vxtme6o/1/

**Comment by vakata** [comment]
Can you provide screenshots as it looks fine in my browser.

![image](https://user-images.githubusercontent.com/146052/67592571-bb260000-f768-11e9-88af-da313dd274d3.png)

**Comment by mubbo** [comment]
google Chrome
Version 78.0.3904.70 (Offizieller Build) (64-Bit)

msie edge and ff are ok.

![image](https://user-images.githubusercontent.com/6881530/67665044-29d1ac00-f969-11e9-838e-94c017dad16a.png)

**Comment by derrick13** [comment]
I tested the fiddle with Browserling and Chrome 75 - and it worked.
https://www.browserling.com/
Soo it seems that Chrome 76 or 77 introduced this issue.

**Comment by derrick13** [comment]
I added a chrome issue here:
https://bugs.chromium.org/p/chromium/issues/detail?id=1018684

**Comment by derrick13** [comment]
Latest news from the Google devs: Seems like it will be fixed in Chrome 79

**Comment by vakata** [comment]
Great, I am closing this then.
