### ISSUE TITLE
jstree checkbox plugin

### ISSUE THREAD

**Issue by mingminghao** [vakata/jstree#2313]
1.how to use jquery to change the checkbox's states (checked,unchecked,undetermined)
2.when I changed the states to checked,I don't want to  trigger the check_node event
thanks!

**Comment by vakata** [comment]
There are method - check_node, uncheck_node - but they will always trigger an event. You can however check the event property of the event data object to identify if you triggered those calls manually.

**Comment by mingminghao** [comment]
tank you very much!
