### ISSUE TITLE
Right click pop-up menu is not coming properly

### ISSUE THREAD

**Issue by GauravKatariya** [vakata/jstree#2317]
Hi ,
I have enabled the right click on node. But, the pop up menu appears on the start of the node always. However, I want the pop up menu to appear from the place where I have right clicked. How can I achieve this ?

![image](https://user-images.githubusercontent.com/30768305/68274290-c2191080-008e-11ea-8852-e1b350a31cf3.png)

**Comment by vakata** [comment]
https://www.jstree.com/api/#/?q=contextmenu&f=$.jstree.defaults.contextmenu.show_at_node
