### ISSUE TITLE
uncaught TypeError in console log

### ISSUE THREAD

**Issue by judyEngelsman** [vakata/jstree#2318]
just downloaded V3.3.8 and loaded it for the first time and get the following error:
Uncaught TypeError: a.expr.createPseudo is not a function at jstree.min.js:2
[update] ran the unminified version: so its line 257
<code>$.expr.pseudos.jstree = $.expr.createPseudo(function(search) {<code>

i didn't see anything yet in the docs about this, aside from just including the js and css files, is there something else missing?

thanks!

**Comment by vakata** [comment]
All examples on jstree.com run on 3.3.8 - this error probably means you are running on an incompatible version of jQuery.
