### ISSUE TITLE
jsTree refresh triggers changed.jstree event twice

### ISSUE THREAD

**Issue by yusufozturk** [vakata/jstree#2323]
Hi @vakata,

Thank you for this great library! We are going to use this in our production environment with the next release.

During the tests, we see that refresh(true) method triggers the changed.jstree event twice, one for the "deselect_all" and one for the "select_node". I think this is for refreshing selections as well.

The issue is, everytime when changed.jstree called, we update the filtering so page can be refreshed by based on the selection.

For now, we did some improvements, by setting some global variable, so it helps us to realize refresh(), so we do not update filters again and again during the refresh().

But during the refresh() process, if user selects a node, we are not processing it because we simply think that it's happened during the auto-refresh.

Is there a way to supress triggering "changed.jstree" during the refresh()? Or how can we understand that changed.jstree actually happened by user click, not because of the refresh process.

Thanks!

**Comment by yusufozturk** [comment]
I see that, refresh() does not send any event. So checking the event might be a workaround for this?
```
if (typeof data.event === 'undefined') {
                    // jsTree Auto Refresh happened, there wasn't any user click
                    return;
                }
```

Thanks!

**Comment by vakata** [comment]
This is an option. You can also listen for the refresh.jstree event - it triggers when the refresh is complete - if that helps. But you figured it out - the event will only be set if the user initiated the selection change.
