### ISSUE TITLE
core.check_callback & dnd_stop.vakata

### ISSUE THREAD

**Issue by yriiarutiunian** [vakata/jstree#2327]
Hello!
Is there a way to get the core.check_callback result in a dnd_stop.vakata event?

**Comment by yriiarutiunian** [comment]
I do drag n drop with multiple nodes, but the copy_node callback fires only ones.
What am i doing wrong?

**Comment by vakata** [comment]
Seems to fire once for each copied node for me:
http://jsfiddle.net/nrfoqjwt/1/
