### ISSUE TITLE
Currently no way to detect when a foreign node is dropped on tree

### ISSUE THREAD

**Issue by radiantone** [vakata/jstree#2329]
Hi,
 I have a simple and obvious use case. I drag an element from my page and drop it onto jstree. JSTree creates a new node. This works. But the parent node is still collpased and I want to expand it when the drop occurs. However, there does not seem to be any dnd events to handle this case.

It looks as though there were 'dnd':'drop_finish' events in the past. But where are they now?

thanks.

**Comment by vakata** [comment]
```copy_node.jstree``` should fire.
