### ISSUE TITLE
Set_id doesnt update handlers and attributes

### ISSUE THREAD

**Issue by kpetrow** [vakata/jstree#2330]
All the handlers, and attributes are not set by set_id.  So if i create one node as generic "new" then set_id (properIDFromserver).  Next node "new" shares the handlers previously created and properly set node.  

id is "test" but the anchor and everything else is old 0_

`<li role="treeitem" aria-selected="true" aria-level="1" aria-labelledby="0_anchor" aria-expanded="false" id="test" class="jstree-node  jstree-closed jstree-last"><i class="jstree-icon jstree-ocl" role="presentation"></i><a class="jstree-anchor jstree-clicked" href="#" tabindex="-1" id="0_anchor"><i class="jstree-icon jstree-themeicon" role="presentation"></i>Root node</a></li>`

Fiddle:
https://jsfiddle.net/th7n4wqj/3/

In my lib which might be older build it is changing on set_id but then reverting back on drag and drop.

**Comment by kpetrow** [comment]
looks like setting 

```
new_node.a_attr.id = 'test_anchor';
inst.refresh_node(new_node);
```

seems like this should be part of set_id???

**Comment by kpetrow** [comment]
Any update on this runnign into this again and getting errors

**Comment by vakata** [comment]
I believe the problem here is that jstree does not enforce unique IDs when invoking set_id. You run into issues because you set the same ID to two different nodes (from what I understand). As for the other elements - changing their attributes is not needed and even results in errors:
https://github.com/vakata/jstree/issues/1380

You should rely on jstree's automatic IDs form new nodes and when setting new IDs for those nodes - make sure they are unique and everything should work fine.

**Comment by kpetrow** [comment]
@vakata That is not the case at all.  All id's are unique.  The issues is that set_id does not change the attributes of the sibling and parent tasks.  

Steps to recreate:

1. Change a nodes id.
The sibling and child attributes are not changed

NOTICE: aria-labelledby="0_anchor" AND  id="test" AND  id="0_anchor"

```
<li role="treeitem" aria-selected="true" aria-level="1" aria-labelledby="0_anchor" aria-expanded="false" id=**"test"** class="jstree-node jstree-closed jstree-last">

   <i class="jstree-icon jstree-ocl" role="presentation"></i>

   <a class="jstree-anchor jstree-clicked" href="#" tabindex="-1" id="0_anchor">
      <i class="jstree-icon jstree-themeicon" role="presentation"></i>
      Root node
    </a>

</li>
```

Are you saying even after set_id is used you can not re-use the previous id?  What happens if you need to shuffle around id's created new nodes and identify them later, etc..

**Comment by vakata** [comment]
Yes, exactly - you can not reuse IDs - I recognize this is a bug, but it is not something I will fix on v.3, and v.4 will not have this problem anyway. 

A quick fix is to redraw the tree after setting the new ID (or as mentioned above - do not use the same ID for all newly created nodes and let jstree handle the uniqueness).
