### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by vicn1222** [vakata/jstree#2332]
tree.delete_node has memory leak when it has children...

When I delete a tree node, I get delete event by connecting to delete_node.jstree.

However, when this node has children, the children doesn't got deleted even though those children disappear from the tree (because the parent got deleted).

I need those delete events, because I have plot associated with each node, when a node is deleted, I delete the plot. At this moment, only the parent emit the delete event.

I add following code to work around the problem, but the code should be in jstree.

Great work! Thank you!

<pre>
function deleteNodeList( tree, nodeList )
{
  while( nodeList && nodeList.length > 0 ) {
    deleteNodeTree( tree, nodeList.shift() );
  }

}

function deleteNodeTree( tree, nodeId )
{
  var node = tree.get_node( nodeId );

  // traverse to delete the children all the way to leaf
  deleteNodeList( tree, node.children );

  tree.delete_node( node );
}

</pre>

**Comment by vakata** [comment]
I do not agree about the event - the event simply means that a node was deleted - if you need to do some processing on the node's children - that should be in your own code. I do not believe there should be a separate event for each child. If you do need that - you can easily create a plugin that will trigger such events, but I will not add this to the core.
