### ISSUE TITLE
[Accessibility Issue] Screen reader is not passing the information for the state and position of the Controls in jsTree - v3.3.7

### ISSUE THREAD

**Issue by Raunak0786** [vakata/jstree#2335]
**Problem** IScreen reader is not passing the information for the state and position of the Controls in jsTree - v3.3.7 
**Repro Steps**:

Open any Jstree - v3.3.7

Navigate towards Expand /Collapsed node

Verify below scenario
a)Screen reader not inform state of the control
b)Screen reader not inform the position of the node in jstree

**Expected Result**:
a)Screen reader should inform the state of the node as expanded or collapsed
b)Screen reader should  inform the position of the node as example : node 1 out of 50

**Comment by vakata** [comment]
This all depends on the combination of browser / reader. Most readers do not implement the tree standard. I believe there is an open issue about this with links to specs etc. Long story short - the jstree markup uses the latest version of the spec, which most browser/reader combinations do not yet support.

**Comment by Raunak0786** [comment]
Hi @vakata ,

Can you please share the details of browser and reader combination in which everything work fine and share the specification for which you are taking about that help us to implement JS tree ?

**Comment by vakata** [comment]
I tested a long time ago - different browsers with different readers - it was hit and miss - no one reader / browser combo did everything right. Since you seem way more experienced in accessibility features - please do open PRs where you see fit.
