### ISSUE TITLE
Uncaught TypeError: Cannot create property 'children' on boolean 'false'

### ISSUE THREAD

**Issue by justlikeef** [vakata/jstree#2338]
Chrome shows that the response headers include: Content-Type: application/json

Error:
jstree.min.js:formatted:898 Uncaught TypeError: Cannot create property 'children' on boolean 'false'
    at a.jstree.plugins.unique._append_json_data (jstree.min.js:formatted:898)
    at a.jstree.plugins.unique.<anonymous> (jstree.min.js:formatted:804)
    at Object.i (jquery-3.4.1.min.js:2)
    at c (jquery-3.4.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.min.js:2)
    at l (jquery-3.4.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.4.1.min.js:2)

Context:
            _append_json_data: function(b, c, d, e) {
                if (null !== this.element) {
                    b = this.get_node(b),
--->                b.children = [],
                    b.children_d = [],
                    c.d && (c = c.d,
                    "string" == typeof c && (c = JSON.parse(c))),
                    a.isArray(c) || (c = [c]);

HTML:
<div id="ConfigItemTree_249146426" name="ConfigItemTree_249146426"></div>
<script>
startnode = 0; 
$(function() {
    $('#ConfigItemTree_249146426').jstree({
        'core' : {
            'data' : {
                'url': function (node) {
                    if (node.id === '#') { node.id = startnode; }
                    return '/jstree/shownode/depo/ConfigItemTree/ConfigItem/' + node.id;
                },
                'datatype' : 'json'
            }
        },
        'state' : { 'key' : 'ConfigItemTree' },
        'plugins' : ['massload', 'state', 'unique'],
    });
});
</script>

Response:
[{"id": 7, "text": "Incorrect", "icon": "/static/images/folder.png"}, {"id": 1, "text": "Primerica", "icon": "/static/images/folder.png", "children": true}]

**Comment by vakata** [comment]
Check your data for inconsistencies - you probably have some issues there. If that does not fix it - please create a demo and I will reopen.
