### ISSUE TITLE
No way to determine the post-cascade selection size after a deselect

### ISSUE THREAD

**Issue by joelamos** [vakata/jstree#2339]
My company has extended jstree to include a `requireSelection` property. When this property is true and we've deselected the last node, we want to recheck the node. The issue is that the `deselect_node.jstree` event is transmitted after the clicked node has been deselected but before cascading has occurred, making it difficult to determine when we've actually deselected the last node.

The checkbox plugin has `uncheck_node.jstree`, but I don't believe this is trasmitted at the appropriate time, either. Additionally, it requires that `tie_selection==false`.

**Comment by vakata** [comment]
The ```changed``` event is much better for this - when it fires check if the current selection is an empty array - if it is - restore the last selection. You can even enable the changed plugin - it will give you a list of all the deselected nodes in the last operation:
https://www.jstree.com/plugins/
