### ISSUE TITLE
Deselect enabled child nodes with disabled siblings doesn't work

### ISSUE THREAD

**Issue by andreika63** [vakata/jstree#2340]
How about clicking twice? First it will select all children, then deselect them - the same way you see in all trees in various software (both mobile and desktop) - installers for example. If you want to do something custom you can always extend jstree with your own plugin, but I will not modify the core unless more people need this functionality.

_Originally posted by @vakata in https://github.com/vakata/jstree/issues/2164#issuecomment-440561198_

Hi, first click selects all, second - deselect. All seems to be fine.
But if You have disabled child nodes- You can't apply deselect to enabled ones

**Comment by andreika63** [comment]
The problem is here:
https://github.com/vakata/jstree/blob/70b13cc8de8275308f92619f2e08a455a8126faa/src/jstree.js#L3170-L3175
In case when no disabled child nodes - first click calls select_node and node becomes selected.
In case when disabled child nodes - node never becomes selected due is_selected method always returns false, because node is in the undetermined state.

code should be something like this:

if(!this.is_undetermined(obj) && !this.is_selected(obj)) {
						this.select_node(obj, false, false, e);
					}
					else  {
						this.deselect_node(obj, false, e);
					}

and method deselect_node should be changed here
https://github.com/vakata/jstree/blob/70b13cc8de8275308f92619f2e08a455a8126faa/src/jstree.js#L3308

there is no undetermined field state in state object ))
loaded: true
opened: true
selected: false
disabled: false
failed: false
loading: false
hidden: false

**Comment by vakata** [comment]
Try this option:
https://www.jstree.com/api/#/?q=cascade&f=$.jstree.defaults.checkbox.cascade_to_disabled

**Comment by AllanAjour** [comment]
I have same issue ! ;o(

I don't want the disabled nodes to get "checked/selected" ("cascade_to_disabled"), so now i cannot uncheck the tree...
