### ISSUE TITLE
Uncaught ReferenceError: window is not defined at self.onmessage

### ISSUE THREAD

**Issue by namikarif** [vakata/jstree#2345]
"jstree": "^3.3.8",
"@angular/cli": "^8.0.3"

**Uncaught ReferenceError: window is not defined
    at self.onmessage (a32a4aca-50a2-470b-8dba-cd7e62c68ad8:1).**

`self.onmessage = function(e, t) {
    e.data && (e = e.data);
    var r, i, n, o, a = e.dat,
        l = e.par,
        u = [],
        c = [],
        h = [],
        p = e.df,
        d = e.t_id,
        m = e.t_cnt,
        A = e.m,
        f = A[l],
        g = e.sel,
        y = function(e, r, i) {
            i = i ? i.concat() : [], r && i.unshift(r);
            var n, o, a, s, l = e.id.toString(),
                u = {
                    id: l,
                    text: e.text || "",
                    icon: e.icon === t || e.icon,
                    parent: r,
                    parents: i,
                    children: e.children || [],
                    children_d: e.children_d || [],
                    data: e.data,
                    state: {},
                    li_attr: {
                        id: !1
                    },
                    a_attr: {
                        href: "#"
                    },
                    original: !1
                };
            for (n in p) p.hasOwnProperty(n) && (u.state[n] = p[n]);
            if (e && e.data && e.data.jstree && e.data.jstree.icon && (u.icon = e.data.jstree.icon), (u.icon === t || null === u.icon || "" === u.icon) && (u.icon = !0), e && e.data && (u.data = e.data, e.data.jstree))
                for (n in e.data.jstree) e.data.jstree.hasOwnProperty(n) && (u.state[n] = e.data.jstree[n]);
            if (e && "object" == typeof e.state)
                for (n in e.state) e.state.hasOwnProperty(n) && (u.state[n] = e.state[n]);
            if (e && "object" == typeof e.li_attr)
                for (n in e.li_attr) e.li_attr.hasOwnProperty(n) && (u.li_attr[n] = e.li_attr[n]);
            if (u.li_attr.id || (u.li_attr.id = l), e && "object" == typeof e.a_attr)
                for (n in e.a_attr) e.a_attr.hasOwnProperty(n) && (u.a_attr[n] = e.a_attr[n]);
            for (e && e.children && !0 === e.children && (u.state.loaded = !1, u.children = [], u.children_d = []), A[u.id] = u, n = 0, o = u.children.length; o > n; n++) a = y(A[u.children[n]], u.id, i), s = A[a], u.children_d.push(a), s.children_d.length && (u.children_d = u.children_d.concat(s.children_d));
            return delete e.data, delete e.children, A[u.id].original = e, u.state.selected && h.push(u.id), u.id
        },
        S = function(e, r, i) {
            i = i ? i.concat() : [], r && i.unshift(r);
            var n, o, a, s, l, u = !1;
            do {
                u = "j" + d + "_" + ++m
            } while (A[u]);
            for (n in l = {
                    id: !1,
                    text: "string" == typeof e ? e : "",
                    icon: "object" != typeof e || e.icon === t || e.icon,
                    parent: r,
                    parents: i,
                    children: [],
                    children_d: [],
                    data: null,
                    state: {},
                    li_attr: {
                        id: !1
                    },
                    a_attr: {
                        href: "#"
                    },
                    original: !1
                }, p) p.hasOwnProperty(n) && (l.state[n] = p[n]);
            if (e && e.id && (l.id = e.id.toString()), e && e.text && (l.text = e.text), e && e.data && e.data.jstree && e.data.jstree.icon && (l.icon = e.data.jstree.icon), (l.icon === t || null === l.icon || "" === l.icon) && (l.icon = !0), e && e.data && (l.data = e.data, e.data.jstree))
                for (n in e.data.jstree) e.data.jstree.hasOwnProperty(n) && (l.state[n] = e.data.jstree[n]);
            if (e && "object" == typeof e.state)
                for (n in e.state) e.state.hasOwnProperty(n) && (l.state[n] = e.state[n]);
            if (e && "object" == typeof e.li_attr)
                for (n in e.li_attr) e.li_attr.hasOwnProperty(n) && (l.li_attr[n] = e.li_attr[n]);
            if (l.li_attr.id && !l.id && (l.id = l.li_attr.id.toString()), l.id || (l.id = u), l.li_attr.id || (l.li_attr.id = l.id), e && "object" == typeof e.a_attr)
                for (n in e.a_attr) e.a_attr.hasOwnProperty(n) && (l.a_attr[n] = e.a_attr[n]);
            if (e && e.children && e.children.length) {
                for (n = 0, o = e.children.length; o > n; n++) a = S(e.children[n], l.id, i), s = A[a], l.children.push(a), s.children_d.length && (l.children_d = l.children_d.concat(s.children_d));
                l.children_d = l.children_d.concat(l.children)
            }
            return e && e.children && !0 === e.children && (l.state.loaded = !1, l.children = [], l.children_d = []), delete e.data, delete e.children, l.original = e, A[l.id] = l, l.state.selected && h.push(l.id), l.id
        };
    if (a.length && a[0].id !== t && a[0].parent !== t) {
        for (i = 0, n = a.length; n > i; i++) a[i].children || (a[i].children = []), a[i].state || (a[i].state = {}), A[a[i].id.toString()] = a[i];
        for (i = 0, n = a.length; n > i; i++) A[a[i].parent.toString()] ? (A[a[i].parent.toString()].children.push(a[i].id.toString()), f.children_d.push(a[i].id.toString())) : void 0 !== s && (s._data.core.last_error = {
            error: "parse",
            plugin: "core",
            id: "core_07",
            reason: "Node with invalid parent",
            data: JSON.stringify({
                id: a[i].id.toString(),
                parent: a[i].parent.toString()
            })
        }, s.settings.core.error.call(s, s._data.core.last_error));
        for (i = 0, n = f.children.length; n > i; i++) r = y(A[f.children[i]], l, f.parents.concat()), c.push(r), A[r].children_d.length && (c = c.concat(A[r].children_d));
        for (i = 0, n = f.parents.length; n > i; i++) A[f.parents[i]].children_d = A[f.parents[i]].children_d.concat(c);
        o = {
            cnt: m,
            mod: A,
            sel: g,
            par: l,
            dpc: c,
            add: h
        }
    } else {
        for (i = 0, n = a.length; n > i; i++)(r = S(a[i], l, f.parents.concat())) && (u.push(r), c.push(r), A[r].children_d.length && (c = c.concat(A[r].children_d)));
        for (f.children = u, f.children_d = c, i = 0, n = f.parents.length; n > i; i++) A[f.parents[i]].children_d = A[f.parents[i]].children_d.concat(c);
        o = {
            cnt: m,
            mod: A,
            sel: g,
            par: l,
            dpc: c,
            add: h
        }
    }
    return void 0 !== window && void 0 !== window.document ? o : void postMessage(o)
}`
**This error occurs in prod mode.**

**Comment by namikarif** [comment]
How do we fix this error?

**Comment by vakata** [comment]
This code is not from the repo - maybe check with your angular directive vendor? The code in the repo has explicit typeof checks.

**Comment by namikarif** [comment]
We received this error when we upgraded the angular version from 5 to 8.

**Comment by soniar4i** [comment]
I'm getting the same error when updating to angular 9. it showing a weird error when filtering my tree and all I get is 

`Uncaught ReferenceError: a is not defined at self.onmessage `

When I check the reference the line that contains the error says:

`
m.children_d.push(r[n].id.toString())) : void 0 !== a && (a._data.core.last_error = {
error: "parse",
                plugin: "core",
                id: "core_07",
                reason: "Node with invalid parent",
                data: JSON.stringify({
                    id: r[n].id.toString(),
                    parent: r[n].parent.toString()
                })
... `

I can see the data coming from the backend and it paints the tree at the beginning but not when filtering, @namikarif did you manage to find a solution?
