### ISSUE TITLE
create_node function is updating previously added data from nodes

### ISSUE THREAD

**Issue by AnujKoundal** [vakata/jstree#2349]
I am creating JsTree, with following functionality: (JsFiddle link is in the end)

 - Add dynamic new nodes (Working perfectly).
 - Place multiple controls inside node data (labels,hidden fields to use
   later) [Working fine]
 - Some controls on the page to set values into labels and hidden fields
   which are placed inside nodes [Working fine]

My Issue is : When I add text to labels from other controls placed on the page (Currently I have used checkbox but there will be multiple controls in later stage) it is working fine, but after that I add new node all data which is set is refreshed. 

Here is my Code: 

        <div id="html1">
          <ul>
            <li>
            <label class="lblProduct">New</label>
            </li>
          </ul>
        </div>
     <label class="labelRadio">No Fever:</label> <div class="inputRadio"><input id="chkBx_No_Fever" type="checkbox" style="outline:none;"></div>
     <button id="btnTest">Add Filter</button>

Jquery: 

     $('#html1').jstree(
                    {
                        "types": {
                            "filter": {
                                "icon": "glyphicon glyphicon-flash"
                            },
                            "treatment": {
                                "icon": "glyphicon glyphicon-ok"
                            }
                        },
                        "core": {
                            "check_callback": true,
                            "themes": {
                                "default": "large",
                                "dots": true
                            }
                        },
                        "plugins": ["wholerow", "changed", "types"]
                    });

     var _selected_Node_Container;
            var _newlyCreatedNodeId;
            var _selectedNodeId;
            var _parentId_Of_Selected_Node;
            $("#btnTest").click(function () {
                debugger;
                _selectedNodeId = $('#html1').jstree('get_selected').toString();
    
                if (_selectedNodeId.length <= 0) { abp.notify.error('Please select record to configure.'); }
                else {
                    create_Filter_Node();
    
                    //--- Move selected node under newly created Node
    
                    $('#html1').jstree("move_node", _selectedNodeId, _newlyCreatedNodeId, 0, null, true, false);
                    //---- Add Another node for pass/fail condition
                    $("#html1").jstree('create_node', _newlyCreatedNodeId, "sub child row", 'last', function (newNode) { _newlyCreatedNodeId = newNode.id });
                }
            });
    
            $('#html1').on('activate_node.jstree', function (e, data) {
                _parentId_Of_Selected_Node = data.instance.get_node(data.node.parent).id;
                _selectedNodeId = data.node.id;
                _selected_Node_Container = $('li[id=' + _selectedNodeId + ']');
                _selected_Node_Container = _selected_Node_Container.find($('a[id=' + _selectedNodeId + '_anchor]'))
    
            });
            function create_Filter_Node() {
                var data="";
                data += "<label name=\"lbl_No_Fever\" class=\"lbl_No_Fever\">Click This Row and then click Checkbox</label>";
                data += "<label name=\"lbl_Days_On_Feed_Mode\" class=\"lbl_Days_On_Feed_Mode\"></label>";
                data += "<label name=\"lbl_Days_On_Feed_Value\" class=\"lbl_Days_On_Feed_Value\"></label>";
                data += "<label name=\"lbl_Temperature_Mode\" class=\"lbl_Temperature_Mode\"></label>";
                data += "<label name=\"lbl_Temperature_Value\" class=\"lbl_Temperature_Value\"></label>";
                data += "<label name=\"lbl_Weight_Mode\" class=\"lbl_Weight_Mode\"></label>";
                data += "<label name=\"lbl_Weight_Value\" class=\"lbl_Weight_Value\"></label>";
                data += "<label name=\"lbl_Animal_Type\" class=\"lbl_Animal_Type\"></label>";
                data += "<label name=\"lbl_Processing_Group\" class=\"lbl_Processing_Group\"></label>";
               // data += "<label name=\"lbl_Relapse\" class=\"lbl_Relapse\"></label>";
                data += "<input type=\"hidden\" name=\"lbl_Relapse\" class=\"lbl_Relapse\"/>";
                $("#html1").jstree('create_node', _parentId_Of_Selected_Node, data, 'first', function (newNode) { _newlyCreatedNodeId = newNode.id });
            }
    
            //------ No Filter checkbox
            $("#chkBx_No_Fever").click(function () {
                if ($(this).is(":checked")) {
                    _selected_Node_Container.find('.lbl_Relapse').val("Value From Checkbox");
                    _selected_Node_Container.find('.lbl_No_Fever').text("Value From Checkbox");
    
                } else {
                    _selected_Node_Container.find('.lbl_Relapse').text(false);
                }
            });

[jsFiddle][1]

How to test: 

 - Select "New" folder icon
 - Press "Add Filter" button this will create new node "Click this row and then
   click checkbox" with some child nodes.
 - Select node with text "Click this row and then click checkbox" and
   then check checkbox. This will change selected nodes text to "Value
   from checkbox" [Only nodes with text "Click this row and then click
   checkbox" will change text on checkbox click.
 - select any node and then press "Add filter". Now a new node is
   created but all text is replaced to "Click this row and then click
   checkbox"

  [1]: https://jsfiddle.net/pvw70s5k/1/

**Comment by vakata** [comment]
This seems to be exactly what your code is doing - I don't see anything wrong on the jstree side. Please check your logic.
