### ISSUE TITLE
Mobile failure

### ISSUE THREAD

**Issue by ikbenignace** [vakata/jstree#2350]
Hello

When I try to test jsTree on a mobile device on Google Chrome,
I don't see the tree well. It does not work.

**Comment by vakata** [comment]
Please try to be more descriptive. Does the issue happen on jstree.com (as I have no problem). I will reopen when more details are available.

**Comment by ikbenignace** [comment]
I hope this is enough.

Op 20 jan. 2020 22:03 schreef Ivan Bozhanov <notifications@github.com>:

Closed #2350<https://github.com/vakata/jstree/issues/2350>.

**Comment by ikbenignace** [comment]
The selectboxes etc doesn't work on my phone.

![Screenshot_20200120-223041](https://user-images.githubusercontent.com/5038850/72780391-0abc8080-3c1f-11ea-9801-8def9f156d57.jpg)
![Screenshot_20200120-222958](https://user-images.githubusercontent.com/5038850/72780392-0abc8080-3c1f-11ea-84e7-42a3eac0bbbb.jpg)

**Comment by EnsPzr** [comment]
This problem is urgent for me.

**Comment by ikbenignace** [comment]
It is also urgent for me.
