### ISSUE TITLE
Tree forming is taking excessive time

### ISSUE THREAD

**Issue by JulieValanteena** [vakata/jstree#2353]
More than 3000 nodes are forming on one expand and it takes more than 10 minutes to complete the loading. It is loaded using lazy loading method only. Is there any other method to make it complete faster.

**Comment by vakata** [comment]
I will need to see a demo of this - my local tests have way more nodes and are rendered in less than a second regarding of browser. Please provide a demo and a browser version.

Here is a simple demo with 3000 dynamic nodes:
https://jsfiddle.net/r705zbm8/
