### ISSUE TITLE
JsTree not destroyed in jQuery Load, creating multiple nodes

### ISSUE THREAD

**Issue by leandrorepos** [vakata/jstree#2355]
Hello,

I use jQuery .load() and when reloading content with JsTree, the create_node() event create multiple children. This is increased each time I reload the tree.

How can I solve?
Thanks.

**Comment by vakata** [comment]
Please provide a demo and I will have a look, it seems however that you are not unbinding all events, also keep in mind ```create_node``` is not the proper way to populate the tree.

**Comment by leandrorepos** [comment]
Yes, I'm sorry. It's a button that I created to add a new node. The problem happens in this event:

`$(document).on('click', '#create-node', function(event) {
	$("#tree").jstree(true).create_node('#', {}, 'last', null, true);
});`

The problem is really not unbinding all events. How can I solve this?

Excellent work on the project!

**Comment by leandrorepos** [comment]
A redundancy error: The problem is really "not unbinding all events".

**Comment by leandrorepos** [comment]
I  solved using:
`$("#create-node").off().click(function() {`
`	$('#tree').jstree(true).create_node('#',{},'last',null,true);`
`});`

Thank you!
