### ISSUE TITLE
Undetermined checkbox uncheck

### ISSUE THREAD

**Issue by ognif** [vakata/jstree#2357]
I try to uncheck a node in my tree structure but it do not work if the node has the state undetermined. In my eyes this is wrong behavior because children of this node are selected. 

`$('#html1').on('check_node.jstree', function(e, data){
     $('#html1').jstree(true).uncheck_node( 'j1_1' );
 });`

The config is:
`                "plugins" : [ "checkbox", "contextmenu"],
                "checkbox": {
                    three_state : true,
                    whole_node : false,
                    tie_selection : false
                },`

If the node is full selected the whole node and its Childs get unselected.

**Comment by vakata** [comment]
Undetermined is a visual state only - it depends on the state of the children. Uncheck all children and the state will disappear.
