### ISSUE TITLE
stack icons with type plugins?

### ISSUE THREAD

**Issue by Scnck** [vakata/jstree#2358]
Hi,

what is the proper configuration to use "plugins" : ["stackedicon", "types"]... I can't seem to get it to work correctly?

**Comment by vakata** [comment]
Duplicate #2356 
I already answered there - remove `jstree-icon` from the class list of the inner elements - this class is what breaks your CSS.

**Comment by Scnck** [comment]
This is not the same question, as [#2356](https://github.com/vakata/jstree/issues/2356) I referring to the configuartion with the "types" plugin

**Comment by Scnck** [comment]
This is not the same question, as #2356 I'm referring to the configuration with the "types" plugin

     On Wednesday, February 12, 2020, 10:31:05 AM EST, Ivan Bozhanov <notifications@github.com> wrote:  
 
 
Closed #2358.
