### ISSUE TITLE
This is not the same question, as [#2356](https://github.com/vakata/jstree/issues/2356) I'm referring to the configuartion with the "types" plugin

### ISSUE THREAD

**Issue by Scnck** [vakata/jstree#2360]
This is not the same question, as [#2356](https://github.com/vakata/jstree/issues/2356) I'm referring to the configuartion with the "types" plugin

_Originally posted by @Scnck in https://github.com/vakata/jstree/issues/2358#issuecomment-585264262_

**Comment by vakata** [comment]
Sorry, I missed that.

The two plugins are not compatible - the types plugin is a core plugin, and stacked icons is provided by someone else just as a demo. You need to modify the stacked icons plugin to read the values from the types plugin, but I can't help you with that.
