### ISSUE TITLE
Selected state gets lost if parent node is closed and tree is loaded async

### ISSUE THREAD

**Issue by Baedda** [vakata/jstree#2361]
Hi @vakata ,
I am using jstree with AJAX enabled and run into the problem that the selected state cant be restored if a parent was closed before I reload the page. I think the behaviour in AJAX mode differs from the behaviour in _regular mode_. 

When I select a node inside a folder and then close the folder, the node stays selected in local storage. But when I reload the page and call `get_selected()` on the tree instance within a callback for the `state_ready.jstree` event, I receive an empty array.

You can reproduce my issue in the Basic AJAX demo as well. https://www.jstree.com/demo/

1. open Root 1
2. open Child 2
3. select One more

If I reload the page now, the tree opens all the nodes again and selects **One more**. This is expected behaviour.
But if I do the exact same steps and close **Child 2** before reload, then **Child 2** stays closed after reload and **One more** isn't selected anymore even though I never _disselected_ it.

I discovered the option `expand_selected_onload` that seems to be used for the behaviour I want, but no parent nodes get opened. Is this an issue or the expected behaviour by using AJAX?

**Comment by vakata** [comment]
This is the expected behavior - once the state is applied the node in question is not present (it has not been loaded), so jstree disregards it when reselecting. You can store the loaded (not only opened) nodes in the state and then it will work, try this setting (set it to true in your config):
https://www.jstree.com/api/#/?q=loaded_state&f=$.jstree.defaults.core.loaded_state

**Comment by Baedda** [comment]
Thank you very much! This option helps a lot. The nodes get loaded but the parent nodes of the selected node do not get opened automatically. Do I have to open them by myself?

**Comment by vakata** [comment]
If they are closed - they will not be opened. You can set this option:
https://www.jstree.com/api/#/?q=expand_selected_onload&f=$.jstree.defaults.core.expand_selected_onload
