### ISSUE TITLE
Problem on changing icon while moving (drop is a non jstree element)

### ISSUE THREAD

**Issue by TensaiKato** [vakata/jstree#2362]
Hello there!

First of all thank you very much for the plugin, it helped me a lot in a recent project, but I'm having an issue with icon changing.
I'm doing a drag and drop to a `<div>`, but when I get into "dnd_move.vakata" function, I'm tring to change the icon by using:

`data.helper.find('.jstree-node').removeClass('jstree-er').addClass('jstree-ok');`

It does change (if I put a beakpoint into it) but after it happens something goes wrong on JQuery and it changes the class back to "jstree-er".

I could fix the issue by commenting the line 6955 of jstree.js:

`data.helper.find('.jstree-icon').removeClass('jstree-ok').addClass('jstree-er');`

I would like to guide if I'm missing something, it seems to be fire only in non jstree elements.

Full code:

`$(document)
  .on('dnd_move.vakata', function (e, data) {
    var t = $(data.event.target);
    if (!t.closest('.jstree').length) {
      if (t.closest('.drop').length) {
        data.helper.find('.jstree-node').removeClass('jstree-er').addClass('jstree-ok');
      }
      else {
        data.helper.find('.jstree-icon').removeClass('jstree-ok').addClass('jstree-er');
      }
    }
  })`

**Versions:**
jsTree: 3.3.9
jQuery: 3.4.1

Your help is much appreciated, 

Thank you!

**Comment by vakata** [comment]
Make sure to bind you handlers after creating the tree (I cannot tell if you have because you have not provided that part of the code). If this is not it - please provide your full config and handlers and I will reopen.
