### ISSUE TITLE
JStree 3.3.8 doesnt load in IE Edge, only shows the Loading icon

### ISSUE THREAD

**Issue by ashokramkumar910** [vakata/jstree#2363]
I very recently used JSTree into my site and the JSTree will  not load on my remote vagrant machine. I use 3.3.8 and the JStree just shows the loading button. I get this error :
CSP14312: Resource violated directive 'default-src 'self'' in Content-Security-Policy: blob:https://localhost:2201/75f8dab3-6d27-4613-ba94-6b5085fb6142. Resource will be blocked.

**Comment by vakata** [comment]
Either modify your Content Security Policy, or set core.worker to false

**Comment by ashokramkumar910** [comment]
Setting Worker to false did the trick. thanks.
