### ISSUE TITLE
Refused to create a worker from..

### ISSUE THREAD

**Issue by bharathbkt** [vakata/jstree#2364]
Refused to create a worker from 'blob:<applicationURL>' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by vakata** [comment]
That is normal - either modify your CSP to include blob (or data), or disable the core.worker config option.
