### ISSUE TITLE
How to gets the new value of rename?

### ISSUE THREAD

**Issue by hugoren** [vakata/jstree#2365]
jstree version js 3.3.9

rename config is :
      'rename':{
                'label':'rename',
                'action':function(obj){
                    var inst = jQuery.jstree.reference(obj.reference);
                    var clickedNode = inst.get_node(obj.reference);
                    inst.edit(obj.reference, clickedNode.val);
                }
            }
Ths

**Comment by vakata** [comment]
It will be in the rename event that fires later. You can also check the edit method signature - there is also a callback you can use.
