### ISSUE TITLE
jstree can not to be bind  to a div element which is created dynamically

### ISSUE THREAD

**Issue by cqdlhjpdml** [vakata/jstree#2366]
```  tree(){
        $(`#${this.fileListBarID}`).jstree({
            'core' : {
                'data' : {
                    "url" : "http://127.0.0.1:3000/?lazy",
                    "data" : function (node) {
                        return { "id" : node.id };
                    }
                }
            }
        });  
    
    }
```
here ,this.fileListBarID is the id of the div element created dyanamically, the function tree called,but the data function not fired and no any request  to server

**Comment by vakata** [comment]
The div has to be available on the page. Make sure you check if the variable is actually set, and the DIV is actually in the markup when invoking ```jstree```.
