### ISSUE TITLE
jstree state plugin deselect nodes after refresh

### ISSUE THREAD

**Issue by M1ReuterLucas** [vakata/jstree#2367]
Hello, 

I just started to look into the state plugin for my jstree. Once I add it I'm able to see what is stored in localStorage but after I refresh the page, it deselect every nodes and it involves my site not working anymore. 

LocalStorage return this : `{"state":{"core":{"open":["shaft_line"],"scroll":{"left":0,"top":0},"selected":["generator"]}}},"ttl":false,"sec":1583316309256}`

"shaft_line" correspond to my root node and "generator" to the node I selected before I refresh the page. I would like it to still be selected after refresh but for the moment it gets deselected. 

I don't know if I have something else to do to make it work or if I did something wrong somewhere in my code. I can provide some code pieces if needed but won't be able to share the whole.

Thank you for your work and your help,

Lucas.

**Comment by vakata** [comment]
Sorry, I will need to see a demo of that - maybe create something isolated? 
I just tested and the state plugin works fine - you can check on jstree.com or create a simple HTML file yourself and you will see the state plugin doing its job.
I will reopen when more info is available.

**Comment by M1ReuterLucas** [comment]
I just tried with the same tree in an isolated file and indeed it works perfectly fine. 
You can find attached the before/after reload with the information I get from localStorage. Nothing seems to be odd.. 
![before_refresh](https://user-images.githubusercontent.com/34105938/75872928-54e47480-5e0f-11ea-8bd1-2215199ffa23.png)
![after_refresh](https://user-images.githubusercontent.com/34105938/75872939-5ada5580-5e0f-11ea-8460-7bd091fa047c.png)
