### ISSUE TITLE
jsTree performance issue on creating nodes and searching funtionality

### ISSUE THREAD

**Issue by ravishp** [vakata/jstree#2369]
Hi @vakata,

we are facing a huge performance issue on jstree where we have 25k+ nodes are there. I read your couple of posts about performance enhancement so I tried to make a correction as per your suggestion but not able to achieve success on it.  Please find below jstree implementation:

```
jsTree.jstree({
            "core": {
                "animation":0,
                "themes": { "icons": true, "dots": false, "theme": "default" },
                'check_callback': true,
                "data": function (node, cb) {
                    var source = transformTreeDataSource(dataSources, key, treeStyles);
                    //console.log('source', source);
                    cb(source);
                },
                "loaded_state": false,
                "worker": true
            },
            "types": {
                "default": {
                    "icon": "fa fa-folder icon-lg"
                }
            },
            "plugins": ["search", "types", "wholerow", "unique", "state"], 
            "search": {
                "case_sensitive": false,
                "show_only_matches": true,
                "show_only_matches_children": true,
                "search_callback": function (searchValue, node) {
                    return node.text.toLowerCase().search(searchValue.toLowerCase()) >= 0;
                }
            }
        });

        $.jstree.defaults.search.ajax = true;
        jsTree.off("select_node.jstree");
        jsTree
            .on(
            "select_node.jstree", function (evt, data) {
                cellNewValue = data.node.text;
                }
            )
            .on('search.jstree', function (nodes, str, res) {
                if (str.nodes.length === 0) {
                    jsTree.jstree(true).hide_all();
                }
            });
```
For Searching text on jstree, I used below code:
` jsTree.jstree(true).search($("#frmSearchTree").val(), false, true, '#');`

Would you please check my code and let me know if any way to improve performance on creating nodes and searching functionality.

**Comment by vakata** [comment]
How often do you create nodes? It should not be a problem unless you create a lot of nodes (essentially using create instead of load). As for searching - custom search will always be slow on huge datasets - no going around it - maybe try server side searches?

**Comment by ravishp** [comment]
Thanks for the reply, We have implemented an excel type format using spread js (grapecity) plugins and few of column cell clicks, we triggered a jquery dialog box and within dialog box, we are showing nodes. 

![image](https://user-images.githubusercontent.com/9713347/76762361-2e332000-67b7-11ea-8446-c3495ca0c19a.png)

Initially, we fetch all nodes records from ajax so can we switch to massload or simple way should be fine?

**Comment by vakata** [comment]
If initial load is slow, because you restore the client state using hundreds of requests - by all means - switch to massload. Also - make sure you switch to server side searches. Both those solutions should improve the situation quite a bit. Is there something else I can help with?

**Comment by ravishp** [comment]
Thanks, Any changes of a set "check_callback" and "worker" property value to false and improve performance?

**Comment by vakata** [comment]
As described - check_callback should be false, if you are not modifying the structure at runtime (so no creates / deletes / moves / etc by the user). As for worker - the tree will be faster if it is set to false, but it will block the main thread (so frozen UI) - try disabling the worker AFTER enabling massload and see how it works for your tree (remember to check on a configuration / browser similar to your average user, as dev machines tend to be faster).

**Comment by ravishp** [comment]
That advice should be beneficial for us, I have just created one "massload" demo on jsfiddle but seems like the latest version is not supporting him? http://jsfiddle.net/1aLub07f/
**Throwing error : a.isFunction is not a function**

![image](https://user-images.githubusercontent.com/9713347/76766946-d4ceef00-67be-11ea-9c8b-2fbcf3ed89ea.png)

**Comment by vakata** [comment]
It is a jsfiddle bug - use a stable jQuery version (not edge).

**Comment by ravishp** [comment]
Thanks @vakata
