### ISSUE TITLE
z-index in various parts - problem when using inside jQuery UI Dialog

### ISSUE THREAD

**Issue by ShyLionTjmn** [vakata/jstree#2370]
Context menu not showing up. fixed that with .vakata-context {  z-index:999 !important; }
But there is also same problem with dnd plugin - drop position markers not showing up too.
Which class do they use?

**Comment by ShyLionTjmn** [comment]
`#jstree-marker {
     z-index:999 !important;
}
`

**Comment by ShyLionTjmn** [comment]
It might be worth finding highest z-index on jstree initialization and use +1 for context menu and marker

**Comment by vakata** [comment]
I have commented on this many times before - all the classes are available in the code - it is up to the developer of the final product to order the z-index. Trying to get the highest index without context is not a good idea.
