### ISSUE TITLE
rename_node without event

### ISSUE THREAD

**Issue by ShyLionTjmn** [vakata/jstree#2371]
Need option to rename node without triggering event. In case of DB name reject, need to revert it's name back.

**Comment by ShyLionTjmn** [comment]
`lion@tmn-net-mon-02:/var/www/html/lib$ diff jstree-modified/jstree.js vakata-jstree-a7f2242/dist/jstree.js
3926c3926
< 		rename_node : function (obj, val, no_trigger) {
---
> 		rename_node : function (obj, val) {
3951,3953c3951
< 			if(!no_trigger) {
< 				this.trigger('rename_node', { "node" : obj, "text" : val, "old" : old });
< 			};
---
> 			this.trigger('rename_node', { "node" : obj, "text" : val, "old" : old });
`

**Comment by ShyLionTjmn** [comment]
Actually need option to skip trigger and checks on some functions too. To revert some changes, denied by backend.

**Comment by vakata** [comment]
This has been discussed many times - manage this state in your code and simply do not react to the event depending on a condition you manage. As for reverting changes - this is a bad idea - just refresh the tree.
