### ISSUE TITLE
How to prevent selection/deselection by user?

### ISSUE THREAD

**Issue by ShyLionTjmn** [vakata/jstree#2373]
I need to disallow user selection/deselection. Have it pre-selected by code only.
Was that discussed before?
Just in case you interested, i made simple option check in activate_node function:
```
activate_node : function (obj, e) {
+                        if(this.settings.core.readonly) {
+                                return false;
+                        }

```

**Comment by vakata** [comment]
You can always use the built-in conditionalselect plugin.
