### ISSUE TITLE
Reset cookie selection

### ISSUE THREAD

**Issue by shaendle** [vakata/jstree#2375]
Hello,

i use jstree with the following code:

`            
$(\'#dirtree\').jstree("destroy");

$(\'#dirtree\')

    .on('select_node.jstree', function (e, data) {

        loadMediaFolder('y', data.selected);

    })

    .jstree({

        plugins : ["json_data", "state", "types", "unique"],

        'core' : {

             'data' : {

                 'url' : "module/media/ajax/tree.php",

                'dataType' : "json"

             }

        },

    })

    var instance = $('#dirtree').jstree(true);

    instance.deselect_all();

    instance.select_node(\'1\');

`
The function shows the tree perfect. But allways i reload the site or i load the site new, the tree selected the last selected node. How can i disabled cookies or delete them if the page loaded new? Because, after i deleted the browser cache and then i reload the site, the tree will start without selected nodes.

Thank you for you help.

Regards Sascha

**Comment by vakata** [comment]
Remove the state plugin, or if you want to remove the selection only use:
https://www.jstree.com/api/#/?q=state.filter&f=$.jstree.defaults.state.filter

**Comment by vakata** [comment]
Or if you want to you can also delete the state on demand by removing the localStorage key:
https://www.jstree.com/api/#/?q=state.key&f=$.jstree.defaults.state.key

**Comment by shaendle** [comment]
Thank you very much.

It works now. But the function instance.select_node('1') does not work. How can i select a node after i load the tree? Must i use a ID or the name of the node for example 'media/video/' ?

I hope you can help me again.

**Comment by vakata** [comment]
This all depends on your data - maybe '1' is inside a node which is not yet loaded? If that is the case - remove the selected property from the state object - that way all previously loaded nodes will be loaded again, but not selected. Sorry, I can't help further, but your question is related to your data.

**Comment by shaendle** [comment]
Excuse me. I have expressed myself indistinctly. I would like to select a node in the tree using a Javascript function. The question is whether I can do this with the select_node function. And the question arises, which parameter should I then pass to this function.

Stay healthy and thank you

**Comment by vakata** [comment]
Sorry for the misunderstanding.

Yes, this is exactly what the function is meant to do. You should pass in the node ID (you can also use a DOM node, selector, etc, but the node ID is the best option). 

In my post above I tried to explain the most common reason why select_node fails to select a node - select_node can not select nodes which are not yet loaded (keep that in mind).

**Comment by shaendle** [comment]
Sorry I've tried a few things now, but I can't find a solution.

Isn't it that the tree is loaded with JSON?

My plan is to display the subdirectories on my hard drive in the tree. The files that are available in the selected directory are then displayed in another DIV. The user can then click on a file to change properties and then return to the tree view.

Since the page is reloading, I would like to open the directory saved in a SESSION with a Javascript function after loading. E.g. media / videos.

This are my JSON-Data:

`{"JSON":{
    "id":"media",
    "text":"media",
    "state":"{selected : true, disabled : false, opened : true}",
    "icon":"fas fa-folder",
    "children":[{
        "id":"media/clipboard",
        "text":"clipboard",
        "state":"{selected : false, disabled : true, opened : false}",
        "icon":"fas fa-folder",
        "children":[]
    },{
        "id":"media/contactmanager",
        "text":"contactmanager",
        "state":"{selected : false, disabled : true, opened : false}",
        "icon":"fas fa-folder",
        "children":[]
    },{
        "id":"media/contacts",
        "text":"contacts",
        "state":"{selected : false, disabled : true, opened : false}",
        "icon":"fas fa-folder",
        "children":[{
            "id":"media/contacts/uXLxXzJMShbrkLNkEVLpWC7uJMZe00lt",
            "text":"uXLxXzJMShbrkLNkEVLpWC7uJMZe00lt",
            "state":"{selected : false, disabled : true, opened : false}",
            "icon":"fas fa-folder",
            "children":[{
                "id":"media/contacts/uXLxXzJMShbrkLNkEVLpWC7uJMZe00lt/temp",
                "text":"temp",
                "state":"{selected : false, disabled : true, opened : false}",
                "icon":"fas fa-folder",
                "children":[]
            }]
        },{
            "id":"media/video",
            "text":"video",
            "state":"{selected : false, disabled : true, opened : false}",
            "icon":"fas fa-folder",
            "children":[]
        }]
    }",
    "mode":"application/json"
    }
}}`

I hope I could describe it somewhat understandably.

**Comment by vakata** [comment]
Have you tried selecting the node AFTER jstree is already loaded? Make sure you do not have the state plugin active and then call select_node INSIDE a "ready.jstree" handler (sorry I missed that in the first reply).
Like so:
```
$('#tree').jstree(...).on('ready.jstree', function (e, data) { data.instance.select_node('1'); }); // provided "1" is a valid ID - in your example "media" is a valid ID
```

**Comment by shaendle** [comment]
Thank you for the last tip. I was now able to solve my problem. Stay healthy!
