### ISSUE TITLE
Checkbox click 

### ISSUE THREAD

**Issue by zebratratata** [vakata/jstree#2376]
Hello
I have trouble when clicked to checkbox sometimes node is toggled (open, hide)
How i can disabled it? Need to disable toggle only by checkbox click

Thanks

**Comment by vakata** [comment]
Read the API docs on the various checkbox plugin settings:
https://www.jstree.com/api/#/?q=checkbox

**Comment by zebratratata** [comment]
I trying to change settings
Now it is like
"checkbox" : {
                "three_state" : false,
                'cascade': 'down',
                tie_selection: false,
                whole_node: false
            },

but it is not helped
