### ISSUE TITLE
tree broken after loading data.

### ISSUE THREAD

**Issue by dolfijn3000** [vakata/jstree#2377]
Hello everyone,
i made a working treeview in my node js website. the suer is able to drag and drop inside the treeview. i use this to save the json to my database that part works.
```
                   $('#tree').on("changed.jstree", async function (e, data) {
                        var v = $('#tree').jstree(true).get_json();

                        $.post("/worlds/<%= world.id %>/updateTree", {
                            treeData: v,
                        });                      
                    });
```
but after i load the json back into the treeview afte rit was saved it looks like this:
https://imgur.com/a/zOgm8zd

i think im extracting the data fro the treeview wrong. Does someone know how to fix this?

**Comment by vakata** [comment]
You should be using get_json to extract your data - read up on all the options:
https://www.jstree.com/api/#/?q=get_json&f=get_json([obj,%20options])
