### ISSUE TITLE
Set color to node icon

### ISSUE THREAD

**Issue by Rikijs** [vakata/jstree#2378]
Hello, Ivan!

I would like to assign colors to tree node icons.

In my application, user can select node color from palette with color picker,
Yet, in order to display said colors one have to create `CSS` classes that represent the colors.
It is problematic to create class for each color because of shear number of them,
I guess one solution might be to restrict colors in color picker...

In the mean time `style="color:#00F"` is not taken into account
This `html attribute` is ignored and removed from constructed tree.
If i rename `style` to `style123` it is kept in the tree.

```
<a class="jstree-anchor" href="https://127.0.0.1:8000/lv/admin/project/dir/59/65" tabindex="-1" data-parent-id="65" data-tree-node-color="#FF00FF" style123="#FF00FF" id="j1_6_anchor">
    <i class="jstree-icon jstree-themeicon lnr lnr-file-empty jstree-themeicon-custom" role="presentation"></i>
    my_file.zip
</a>
```

Maybe one could set color in link data element and get it on tree construction?
`<a href="#" class="tree-node" data-tree-node-color="#FF00FF">My tree node</>`

Is there a better/different solution available?!

Thank you.

**Comment by vakata** [comment]
Sorry, I am afraid there is no better solution, aside from creating a jstree plugin which reads the property you have defined. There are example plugins available in src/misc.js
