### ISSUE TITLE
refresh_node example

### ISSUE THREAD

**Issue by just-website** [vakata/jstree#2379]
Hello Vakata!
I really studied your repository's issues, I saw that this question was asked several times, but still could not find the answer. How can I update the data of a particular node using the refresh_node method? Whatever I try, it does not give a result. I sincerely do not understand the logic of his work. Can you tell me what needs to be fixed in my example so that the data is updated reactively?
https://repl.it/@polosatyj/ShockedUprightDirectories

**Comment by just-website** [comment]
I want to add.  Еhat when I try to call refresh_node(id) with "Alternative JSON format" - unhandled error is thrown `Uncaught TypeError: Cannot read property 'id' of undefined `. It seems this method do something wrong

**Comment by vakata** [comment]
You should refresh the parent, the node itself can not be refreshed (unless you do it manually).
As for the error - you probably have a missing or duplicated ID.

**Comment by just-website** [comment]
Regarding the error - I left an example. Look at it, when I get the chance there is an array of 4 test items in the alternative format. I am sure that there are no typos or missing id

**Comment by just-website** [comment]
> Вы должны обновить родительский узел, сам узел не может быть обновлен (если вы не сделаете это вручную).
> Что касается ошибки - у вас, вероятно, отсутствует или дублируется идентификатор.

Regarding the error - I left an example. Look at it, when I get the chance there is an array of 4 test items in the alternative format. I am sure that there are no typos or missing id

**Comment by just-website** [comment]
I have simplified the code example, and still face the same problem when trying to `refresh_node` with json alternative, i have `Cannot read property 'id' of undefined at a.jstree.core.redraw_node`  error. If you use the standard format, the problem disappears. Attach the sample code here if you can not see the [link](https://repl.it/@polosatyj/ShockedUprightDirectories). you can reopen the issue?  
  
code  
```
let local_data_alternative =
[
  { id : '1', text : 'Node 1', parent: '#' }
]

const set_data = () => 
{
  local_data_alternative[0].text = 'test';
}

$('#jstree').jstree({
  'core': {
    data: (obj, cb) => {
        cb(local_data_alternative)
      }
    },
});

setTimeout( () => {
  set_data();
  $('#jstree').jstree(true).refresh_node('1');
}, 2000)
```

**Comment by vakata** [comment]
You are refreshing a node, which has no children. Your code then returns the original structure AS IF it is the child of the refreshed node - jstree tries to append that to the node, which in turn fails - because you are trying to append node ID 1 within node ID 1 - I hope this make sit clear.
