### ISSUE TITLE
TypeError: can't assign to property "children" on false

### ISSUE THREAD

**Issue by Thaoden** [vakata/jstree#2380]
I use the AJAX-like format to lazily populate my tree. I then want to call `load_node` or `refresh_node` on a given node that was set with `children = true`, however the error
> TypeError: can't assign to property "children" on false: not an object

is thrown. When I inspect the `node.original` object, I don't see the `children` property at all.

On first tree load, my API returns:
 ```
[
    {
        "text":"530",
        "children":true
    },
    {
        "text":"516",
        "children":false
    }
]
```
When then calling `load_node`, `open_node` or `refresh_node` on the node `530`, the above error is thrown. Logging the `data.node.original` value only gives `text: "530"` completely omitting the `children` property. JSTree itself shows the node as having children (indicated by the small triangle) and is able to load them when clicking on the node. 

Browsing through the other issues, I see I can circumvent this behaviour by sending an array of child nodes instead of just the plain boolean, but that would cause some overhead on the API I would like to avoid if possible.

Thanks for any help, let me know if you need more info!

**Comment by vakata** [comment]
This usually happens when you have duplicated or missing IDs.

If this is not it - please provide a demo and I will reopen.

**Comment by Thaoden** [comment]
What ID might that be? The one that gets assigned to `data.node.id`? I don't control these.

**Comment by vakata** [comment]
@Thaoden there is no way to use lazy loading without specifying the IDs yourself.
