### ISSUE TITLE
Color Node

### ISSUE THREAD

**Issue by As1w** [vakata/jstree#2382]
Hi. How set color node in json structure, example:

```
var json_test = [{
                            "text": "New", 
                            "data": {"param1": 1, "param2": 2},
                            "color":red
                          }]
```
I want to use themes plugin, but do not undestand correct structure. My jstree not work.

**Comment by vakata** [comment]
There is no such option, you can however use li_attr, or a_attr to set a className and give that className any styles you like in your page's CSS. The above options are documented on the homepage of this repo.
