### ISSUE TITLE
Draggable node 

### ISSUE THREAD

**Issue by As1w** [vakata/jstree#2383]
Hi,
I use two trees. I want close opportunity draggable node from tree_1 to tree_2, but use draggable inside tree_1. 
I use next option in my project:
```
'core': {
                "check_callback": true
},
"plugins": ["dnd"],
"dnd" : {
              is_draggable : function () 
                {
                   return false; 
                }
} 
```
it work, but I can not draggable inside tree_1. Help me please.

**Comment by vakata** [comment]
Allow all nodes to be draggable, and inside check_callback - return false, when the tree containers are different (dragged node & drop target).

**Comment by As1w** [comment]
mmm... if i set 

check_callback - return false I can not create root and children in my tree + I can not drag node tree_2 in tree_1

**Comment by As1w** [comment]
I want draggable inside tree_1, create root/children and draggable node tree_2 in tree_1. 

Draggable tree_1 in tree_2 cancel !

**Comment by vakata** [comment]
I mean - return false only if the check is triggered by the operations you want to handle - the information is all there.
