### ISSUE TITLE
Save attribute data

### ISSUE THREAD

**Issue by As1w** [vakata/jstree#2384]
Hi, vakata

Thanks that answered my questions.

I use active dnd in your plagin. 
I have two tree, tree 1 and tree_ 2: 

```
json for tree_1:
[{
	"text": "test_1", 
	"data": { "option_1": 1 , "option_2": 2},  
	"children":  
	       [ {"text": "child_test_1", 
	       	  "data": {"option_3": 3, "option_4": 4}
                 }]
  }]
```

json for tree_2:
```
[{
	"text": "test_2", 
	"data": { "option_5": 5 , "option_6": 7},  
	"children":  
	       [ {"text": "child_test_2", 
	       	  "data": {"option_8": 8, "option_9": 9}
                 }]
  }]
```

When i use dnd data.node.data in my parent and children not save. In console write "TypeError: data.node.data is null". What setting i can use to fix this error?

**Comment by vakata** [comment]
https://www.jstree.com/api/#/?q=json&f=get_json([obj,%20options])
