### ISSUE TITLE
How can i allow move_node only between the same types?

### ISSUE THREAD

**Issue by iceman-fx** [vakata/jstree#2385]
Hello,
I have a list of nodes that consist of categories and articles.

![Unbenannt-1](https://user-images.githubusercontent.com/4291047/78881979-d2775200-7a57-11ea-9248-1b294ee9aa9f.jpg)

How can I prevent the article nodes from being moved between the categorie nodes and prevent the category nodes from being moved between the article nodes?
The nodes may only be moved between the same type of type.

My code:

```
mytree.jstree({
					"core": { 
						"check_callback": function (e,node,node_parent,node_pos,more) {
							nid = node.id; npid = node_parent.id;							
							
							if ( e == "move_node" ) {
							 node_parent.id ) { return false; }								//move only at the same level
								
							}
							if ( e == "copy_node") { return false; }												//disallow copy mode


							console.log("     ");
							console.log("-----------------------------------");
							console.log("     ");
							
							console.log(node);
		

							return true;
						},
...
```

**Comment by vakata** [comment]
check_callback is the more complicated way to go - you could dump out the `more` parameter and return true or false accordingly to your rules.

But since you are using types - set valid_children in the type definition:
https://www.jstree.com/api/#/?f=$.jstree.defaults.types
