### ISSUE TITLE
data-jstree='{"opened":false,"selected":true} ignores opened value

### ISSUE THREAD

**Issue by rieserCh** [vakata/jstree#2386]
Hallo,

i got an html tree where i want to set initial state selected = true, but opened = false using the data-attribute: data-jstree='{"opened":false,"selected":true} ignores opened value

It seems, that the opened value is ignored in this configuration. The other way around works.

**Comment by vakata** [comment]
http://jsfiddle.net/o9j87ns4/

**Comment by rieserCh** [comment]
i got the following plugins active:  [ "wholerow", "checkbox" ]

**Comment by rieserCh** [comment]
http://jsfiddle.net/0reo2jL5/

**Comment by vakata** [comment]
Use this:
https://www.jstree.com/api/#/?q=expan&f=$.jstree.defaults.core.expand_selected_onload

Here is your demo:
http://jsfiddle.net/7a0gjzym/

**Comment by rieserCh** [comment]
Ah, perfekt. Thanks!
