### ISSUE TITLE
How to Get sibling node Order number after drag stop

### ISSUE THREAD

**Issue by nemosmart** [vakata/jstree#2388]
Dear Ivan Bozhanov,

I'm trying to get node order number after drag is stoped, my goal is to swap node order number between node and update it to database. Please see my tree below: 

:: before
[-] root
   node-1
   **node-2**
   node-3

:: after 
[-] root
   node-1
   **node-3**
   node-2

Best regards, Anton

**Comment by vakata** [comment]
You can either use the DOM, or the internal data - in both cases - check the position of the node inside its parent's children:
tree.get_parent(node).children.indexOf(node);
