### ISSUE TITLE
jQuery 3.5.0 breaks jstree

### ISSUE THREAD

**Issue by jtraulle** [vakata/jstree#2389]
Hello :)

When upgrading to jQuery 3.5.0, it breaks jstree reporting that jstree function is undefined.

**Comment by jtraulle** [comment]
Maybe related to https://github.com/jquery/jquery/issues/4665

**Comment by StudioMaX** [comment]
I had the same error, deleting `node_modules` and reinstalling them via `yarn install` helped me.
Also I've added some changes in #2391 according to [jQuery Core 3.5 Upgrade Guide](https://jquery.com/upgrade-guide/3.5/)
