### ISSUE TITLE
Move/Copy nodes unable to access the node(s) details whilst a trigger in the background is moving the node

### ISSUE THREAD

**Issue by Zarrdex** [vakata/jstree#2392]
Hi:

I am getting the following error when trying to move/copy nodes

Uncaught TypeError: Cannot create property 'children' on boolean 'false'
    at a.jstree.plugins.search._append_json_data (jstree.min.js:2)
    at a.jstree.plugins.search.<anonymous> (jstree.min.js:2)
    at Object.i (jquery.min.js:2)
    at c (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at l (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)

this is down to the fact that i am not using your move/copy node function as i am moving/copying multiple nodes at the same time as well as giving the user to change the name of the node.

the error is shown when trying to get the node details whilst a trigger of yours (i am guessing) is moving/copying the item in the background

**Comment by vakata** [comment]
I will need to see your custom code which copies / moves nodes to know what is going wrong. Keep in mind it is wiser to use the built-in functions, as copying / moving manually in the internal model object will likely break the internal state (unless you took a lot of time to get familiar with it). My guess is this is what is going wrong. Also keep in mind the error is related to the search plugin - maybe something is misconfigured?

**Comment by Zarrdex** [comment]
Hi Vakata;

Please note that the custom code does NOT modify the copy/move functions, they still work in the background. 

Due to the fact that the move_node/copy_node events work on a one to one basis, i.e. if i copy 3 nodes the copy_node event activates 3 times. This is not helpful for the product i am working on as a business rule we do not allow the same node name in the same parent node. Thus, i need to ensure the user can change those names in a singular instance and not show the modal 3 times

Thus, i am using the dnd_stop.vakata event and try and work out the position and then showing a modal for the user to change the names of the nodes.
Example code (please note this is not all the code)
$(document).on("dnd_stop.vakata", function (e, data) {
    e.preventDefault();
    var targetId = data.event.target;
    var targetNode;

//Ensure we get the target node parent details
    if ($(data.event.target).is("svg") || $(data.event.target).is("i")) {
        targetId = data.event.target.parentElement.parentElement.id;
        targetNode = $('#treedata').jstree(true).get_node(targetId);
    }
    else if ($(data.event.target).is("path") || $(data.event.target).is("a")) {
        targetId = data.event.target.parentElement.id;
        targetNode = $('#treedata').jstree(true).get_node(targetId);
    }
    else if ($(data.event.target).is("div") && $(data.event.target).hasClass("jstree-wholerow-hovered")) {
        targetId = data.event.target.parentElement.id;
        targetNode = $('#treedata').jstree(true).get_node(targetId);
    }
    else {
        targetNode = $('#treedata').jstree(true).get_node($(targetId));
    }
    if (targetNode.id !== null || targetNode.id !== undefined) {

//wait till jstree internal triggers are run before running this else we will not be able to find any nodes that are being moved
        setTimeout(function () { LocationArea.ValidateDrop(targetNode, data.data.nodes, ''); }, 300);
    }
});

ValidateDrop: function (targetNode, nodes, mode) {
            debugger;
            var parentNode;
            var positionText = 'after';
            var targetNodeId = 0;
            let validNodes = [];
            let parentNodes = [];           

            //lets work out if the target node is the same type as the selected nodes type if it is then get the targets parent else it is the parent
            var firstChildnode = $('#treedata').jstree(true).get_node(nodes[0]);
            if (targetNode.type == firstChildnode.type) {
                parentNode = $('#treedata').jstree(true).get_node(targetNode.parent);
                targetNodeId = targetNode.id;
                if ((trackingMarker.top) < $('#' + targetNode.id).offset().top) {
                    positionText = 'before'
                }
            }
            else
            {
                parentNode = targetNode;
                positionText = 'last'
            }

            parentNodes.push(parentNode.id);

            nodes.forEach(function (e, index) {

                var node = $('#treedata').jstree(true).get_node(e);
                if (node !== false) {
//Not really needed as the jstree callback should handle this, 
                    if (LocationArea.ValidateDropPaste(parentNode.type, node.type))
                    {
                        validNodes.push(node.id)
                        if (!parentNodes.includes(node.parent)) {
                            parentNodes.push(node.parent);
                        }
                    }
                }

            });

                var data = {
                    parentNodeId: parentNode.id,
                    targetNodeId: targetNodeId,
                    moveNodes: validNodes,
                    positionText: positionText,
                    parentNodes: parentNodes,
                    defaultMode: mode
                };
//Display modal as to allow user's to change the node(s) name, and to enforce non duplicate name under parent node
                LocationArea.CopyNodesDialog(data);
                
        },


I had to put in a timeout
        setTimeout(function () { LocationArea.ValidateDrop(targetNode, data.data.nodes, ''); }, 300);
else the first call in the ValidateDrop function
        $('#treedata').jstree(true).get_node(nodes[0])
was sometimes throwing the highlighted error, as the internal trigger's was moving the object in the background.

I mean it would be really helpful, that move_node/copy_node events could deal with all the selected nodes at once (not on a one to one basis) , or a new move_bulk_node/copy_bulk_node event(s) that could

**Comment by vakata** [comment]
I will think about adding a bulk plugin, or will merge if someone provides a decent PR.
