### ISSUE TITLE
$('#Div').bind("ready.jstree", function() is not being called 

### ISSUE THREAD

**Issue by venu-nimmagadda** [vakata/jstree#2393]
Hello,
Tree is not loading some times and  hence .bind("ready.jstree) function is not invoked.

in our application,we are generating the JSON dynamically and this issue happens only when the JSON object is huge in size.are there any limitation of the JSON size that JSTREE supports?.
The issue i mentioned happens some times and  few occurances tree is loading fine. and .bind("ready.jstree) invoked 

when we expeience this issue,we see we are getting below script error.Note that this issue we are facing only in IE ,but not in chrome.
SCRIPT0: Script Error
Line: 0

Please can you help this resolved.

We are using version v 3.3.9

**Comment by vakata** [comment]
There is nothing I can do to fix this error - the error is not jstree related - you are probably hitting a browser limit.
