### ISSUE TITLE
[Help] : in lazy loading i am not able to expand till child node dynamically as parent nodes are not present

### ISSUE THREAD

**Issue by vaibhavkavi** [vakata/jstree#2395]
Hi Vakata,

In my application, i am expanding the tree to the selected node. it works fine if i don;t use to lazy loading but when i use lazy loading i am not able to expand my tree till selected node.

would you please give me sample json or code by which i can able to expand till child node dynamically. i am using same code in your example. it works fine when i expand the tree manually. but through code i am not able to expand it.
`
								'core' : {
									'data' : {
									    'url' : function (node) {
									      return node.id === '#' ? '/application url to fetch root node : 'url to fetch child nodes';
									    },
									    'data' : function (node) {
									      return { 'id' : node.id };
									    }
									}
								}`

please help with sample code

**Comment by vaibhavkavi** [comment]
i am using simple json   { "id" : "ajson1", "parent" : "#", "text" : "Simple root node" } as input to the jstree

**Comment by vakata** [comment]
Please read the docs and check the demos.

**Comment by vaibhavkavi** [comment]
i didn't find any document which tell load child node if loading is lazy load.

select_node automatically expands the parents but in lazy load, parent node is not present. would you please tell me which document i should refer. it will really help. i have recently started doing development. so don't have much experience.
