### ISSUE TITLE
Script going to unresponsive state when using jstree to show tree view json data

### ISSUE THREAD

**Issue by aayushikanoria** [vakata/jstree#2396]
I have been using jstree to show json data in tree view
When i am working with small set of data, i didnt find any performance issue.
In case of large data set, the page goes to unresponsive state.

While loading jstree i am using wholerow along with grid and making sure that once loaded grid event is fired the styling height of a row is similar and fits in one row to give a proper view 

All the columns of jstree and grid should align in same height to make it one row.

Pasting the code below 

function createPSBJSTree(viewName,jsonData) {   
	$(viewName).bind("loaded_grid.jstree",function(){
		$("span#status").text("loaded");
		alignCssPsbJstreeGroupOff();
	}).on("select_cell.jstree-grid",function (e,data) {
		$("span#clicked").html("clicked "+data.column+" of value "+data.value);
	}).on('update_cell.jstree-grid',function (e,data) {
		$("span#changed").html("changed "+data.col+" from "+data.old+" to "+data.value);
	}).on("select_node.jstree", function (e, data) { 
		$(viewName).jstree("toggle_node", data.node);
	}).on('after_open.jstree', function (e, data) { //when clicking on folder to expand
		for(var i=0;i<data.node.children.length;i++)
		{
			var element = $('#' + data.node.children[i]);
			element.children('.jstree-wholerow').css('height', element.children('a').height() + 'px');
			var element1 = $("div").find('[data-jstreegrid='+data.node.children[i]+']')
			element1.css('height', element.children('a').height() + 'px');
		}
	}).on("changed.jstree", function (e, data) {
		if(data.selected.length) {
			showProgressBar();
			setTimeout(function () {
			       someProcess.......
		}, 1000);
		}
	});

	$(viewName).jstree({
		plugins: ["json","grid","search","sort","wholerow","types"],
		core: {
			data: jsonData,
		},
		grid: {
			columns: [
				{width: 305, header: "&nbsp;",title:""},
				{width: 85, cellClass: "col1", value: "status", header: "<b>Status</b>", title:"Status"},
				{width: 85, cellClass: "col2", value: "priority", header: "<b>Priority</b>", title:"Priority"}
				],
				resizable:true,
		},
		"search": {
			"case_insensitive": false,
			"show_only_matches" : true
		},
		types : {
			"file": {
				"icon": "jstree-icon jstree-file"
			}
		},
	});
}

function alignCssPsbJstreeGroupOff()
{
//Called to fix styling issue for wholerow once jstree is Loaded 
//Jstree columns row heights should be similar to give the look of one row and select the wholerow
	if(mainLevelPsbGroupOn==0 || showAllPsbGroupOn==0){
		$('#psbView > ul>li').each(function() {
			var element = $('#' + this.id);
			element.children('.jstree-wholerow').css('height', element.children('a').height() + 'px');
			var element1 = $("div").find('[data-jstreegrid='+this.id+']')
			element1.css('height', element.children('a').height() + 'px');
		});
	}
}

**Comment by vakata** [comment]
This is related to the grid plugin, which is not supported by me. Also - make sure you make the height syncing a lot more efficient, especially if invoked every time a node is opened.
