### ISSUE TITLE
dnd only current node tree

### ISSUE THREAD

**Issue by As1w** [vakata/jstree#2398]
Hi,
I have two trees. When I copied current node  in my tree I copied her children, but I want copied  current node and node + children (variation menu, default copied node). How i can this do it? 

UPDATE: 

Can use checkbox plugin. If checkbox ON for every node this copy. how use checkbox for copy select nodes? have ideas ?  

Now, i copy node 

```
.on("copy_node.jstree", function(e, data) {
data.node.data = $.extend(true, {}, data.original.data);
    
    if (data.node.children_d.length > 0) {
        var array_children_d_sort = data.node.children_d;
        var array_children_d_original_sort = data.original.children_d;
            for (var i = 0; i < array_children_d_original_sort.length; i++) {
            var originalChild = $('#tree2').jstree(true).get_node(array_children_d_original_sort[i]);
            var copiedChild = $('#tree1').jstree(true).get_node(array_children_d_sort[array_children_d_original_sort.length-1-i]);
            copiedChild.data = $.extend(true, {}, originalChild.data);
      }
```

**Comment by vakata** [comment]
There is no such option, but you can use the event to delete all the children of the copied node (or even - all unchecked children).
