### ISSUE TITLE
Memory leak when repeatedly refreshing the tree.

### ISSUE THREAD

**Issue by rwtr** [vakata/jstree#240]
If the tree is repeatedly refreshed with new JSON node data, the browser will leak memory.

Specifically, my site polls a server every second, using a separate ajax call (not jstree ajax). This returns customised JSON, representing a hierarchy of nodes. This JSON is translated into the JSON data used by the jsTree json_data plugin and then assigned to the tree (get_settings().json_data.data). The following two lines are used to update the tree. Commenting out these lines will eliminate the memory leak, but will result in no tree being drawn:

jQuery.jstree._reference('#tree')._get_settings().json_data.data = jsonData;
jQuery.jstree._reference('#tree').refresh(-1);

**Comment by molikh** [comment]
?
