### ISSUE TITLE
$.jstree.defaults.state : restore the state of the last parent node clicked only?

### ISSUE THREAD

**Issue by githubcom13** [vakata/jstree#2400]
Hi,
How to restore the state of the last parent node clicked only? Currently the `changed.jstree` and `open_node.jstree` parameters restore all clicked (parent/childs) nodes as the default behavior of `$.jstree.defaults.state`.

Thanks

Here is my configuration:

```
<form id="s">
    <input type="search" id="q" />
    <button type="submit">Search</button>
</form>

<div id="jstree"></div>

<script>
$('#jstree').jstree({
    'core' : {
        "themes": {
            "icons": true,
            "dots": false,
            "responsive": false,
            "stripes": false
        }, 
        'data' : {
            "url" : "tree2.json",
            "dataType" : "json"
        } 
    },
    "state" : { "key" : "save", "events" : "changed.jstree" },
    "types" : {"default" : {"icon" : "fa fa-folder"}},
    "search" : {"show_only_matches" : true},
    "plugins" : [ "state", "types", "search" ]
});
$("#s").submit(function(e) {
    e.preventDefault();
    $("#jstree").jstree(true).search($("#q").val());
});
</script>
```

**Comment by vakata** [comment]
You can filter the state object manually, so you have full control over what is restored:
https://www.jstree.com/api/#/?q=state.filter&f=$.jstree.defaults.state.filter

**Comment by githubcom13** [comment]
Your documentation is not very explicit, no example concerning the state. And since you closed the discussion immediately after writing your answer, I take it that you don't want to explain your code. Too bad!

**Comment by vakata** [comment]
I close each issue when the problem itself is resolved. If you have further questions - I am happy to discuss them.
