### ISSUE TITLE
Get Checked Nodes Ordered

### ISSUE THREAD

**Issue by mehmetalidumlu** [vakata/jstree#2401]
Hi,
I have a tree which has 5 elements. 
I checked first, third and fifth nodes and get checked nodes. List seems normal.
After, i move li elements for order selected nodes and get checked nodes.
This time there is no change in the list.

I want get new ordered list when move fifth element on top.

Simple List (c is checked)
1c , 2 , 3c , 4 , 5c           ---> get_checked --->  1,3,5  in this order

Ordered List

5c , 4 , 2 , 3c , 1c           ---> get_checked --->  1,3,5  in this order

What i want?

5c , 4 , 2 , 3c , 1c           ---> get_checked --->  5,3,1

How can i do that?

Thanks...

**Comment by vakata** [comment]
Off the top of my head - use get_json, with the flat option, and then filter the result array depending on state.checked. This could give you an ordered list:
https://jsfiddle.net/9qznb65g/

**Comment by mehmetalidumlu** [comment]
Hi, this work for non child element list. But i use it with group. I mustnt move A1 element to B group. This is dangerous for app. If we can  move each element in its own group then it will work for me. There is a table for example. "-" is child element.

`
</table>
<table style="height: 211px; width: 442px;">
<tbody>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">Origin</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">Fail</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">Fail</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">Works</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">Works</td>
</tr>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">A</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">A</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">A</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">B</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">A</td>
</tr>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">-A1</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">-A1</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">-A1</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">-B1</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">-A3</td>
</tr>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">-A2</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">-A2</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">-B</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">-B3</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">-A2</td>
</tr>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">-A3</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">-B1</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">--B2</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">-B2</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">-1</td>
</tr>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">B</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">-A3</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">--B3</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">A</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">B</td>
</tr>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">-B1</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">B</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">-A2</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">-A2</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">-B2</td>
</tr>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">-B2</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">-B2</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">-B1</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">-A3</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">-B1</td>
</tr>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">-B3</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">-B3</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">-A3</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">-A1</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">-B3</td>
</tr>
<tr style="height: 23px;">
<td style="width: 88px; height: 23px;">Origin</td>
<td style="width: 74px; height: 23px;">&nbsp;</td>
<td style="width: 111px; height: 23px;">Fail</td>
<td style="width: 82px; height: 23px;">&nbsp;</td>
<td style="width: 81px; height: 23px;">Fail</td>
<td style="width: 65px; height: 23px;">&nbsp;</td>
<td style="width: 110px; height: 23px;">Works</td>
<td style="width: 110px; height: 23px;">&nbsp;</td>
<td style="width: 254px; height: 23px;">Works</td>
</tr>
</tbody>
</table>
`

**Comment by vakata** [comment]
Sorry it did not work in some cases. In that case - no - there is no way to get the items ordered, and I am afraid there is no way to achieve that from jstree itself.
