### ISSUE TITLE
Images not display in Search Plugin

### ISSUE THREAD

**Issue by apache289** [vakata/jstree#2402]
Certain Android phone models having issue to display images from the jsTree search plugin. 

![WhatsApp Image 2020-06-09 at 2 05 27 PM](https://user-images.githubusercontent.com/66663298/84112953-4041f900-aa5c-11ea-8d26-96f6af2cb157.jpeg)

![WhatsApp Image 2020-06-09 at 12 50 05 PM](https://user-images.githubusercontent.com/66663298/84113088-88f9b200-aa5c-11ea-9865-3f81787dc4f4.jpeg)

**Comment by vakata** [comment]
I am afraid I can't help with that - those are standard background images from a sprite. Do you have this issue all over the page, or just a single demo?
