### ISSUE TITLE
New version because of jQuery Upgrade

### ISSUE THREAD

**Issue by kozi** [vakata/jstree#2403]
Would it be possible to release a version containing the fix for jQuery 3.5 soon? Since the upgrade of jQuery closes a security hole we would like to update the library.

Thanks for this great plugin!

**Comment by vakata** [comment]
There should be no problem using the latest jstree version with jquery 3.5.0. Do you have an issue with the code?

**Comment by vakata** [comment]
@kozi Sorry, I forgot about the merged PR that addresses a change in jQuery. jsTree 3.3.10 is now published.
