### ISSUE TITLE
Webpack optimization

### ISSUE THREAD

**Issue by Herz3h** [vakata/jstree#2407]
I'm trying to import only plugins I need so I have: 

```javascript
import 'jstree/src/themes/default/style.css'
import 'jstree/src/jstree.js'
import 'jstree/src/jstree.types.js'
import 'jstree/src/jstree.dnd.js'
import 'jstree/src/jstree.checkbox.js'
````
But webpack keeps including jstree/dist/jstree.js even tho I never include that file nor do I do `import  'jstree'``.

So this seems to not be possible to import files individually, right ? If not how do I reduce bundle size and only include stuff I use ? 

<img width="561" alt="Capture d’écran 2020-06-30 à 22 12 43" src="https://user-images.githubusercontent.com/1900696/86172662-0cb83300-bb1f-11ea-900f-77f197c2ef85.png">

**Comment by vakata** [comment]
You can only include the modules you need - jstree will work just fine - they are all independent (unless stated otherwise). However, I am not familiar how webpack optimizes scripts and builds bundles.

As a simple test - create a sample HTML file and include only src/jstree.js and src/jstree.dnd.js - you can now create a tree with drag'n'drop enabled.

**Comment by Herz3h** [comment]
I have tried your suggestion, by only including first:

```js
import 'jstree/src/jstree.js'
```

This works fine, it only includes this file.

then :

```js
import 'jstree/src/jstree.js'
import 'jstree/src/jstree.dnd.js'
```

And as soon as I add any other jstree plugin to the main file, it starts including jstree/dist like in the attached screenshot. This only happens with jstree, I have many other dependencies, none of them acts like this.

<img width="674" alt="Capture d’écran 2020-07-01 à 10 36 58" src="https://user-images.githubusercontent.com/1900696/86222699-e201c500-bb86-11ea-8016-aa9b85186af7.png">

**Comment by Herz3h** [comment]
Unfortunately this https://github.com/vakata/jstree/blob/master/src/jstree.dnd.js#L13 makes it impossible to import one file at a time :/

**Comment by vakata** [comment]
I am not sure how this works, but why would that line include the file from the dist folder, instead of the file form the src folder?

**Comment by Herz3h** [comment]
I think because in webpack (not sure if its specific to it), when you require a package by name, it open the package.json of that module and reads the value in the "main" key. In this case "main" has a value of "dist/jstree"
