### ISSUE TITLE
Multiple selection not working for me

### ISSUE THREAD

**Issue by gwheeloc** [vakata/jstree#2408]
I've followed the example here (https://github.com/vakata/jstree/issues/2003).  I'm using the current version.  I've been trying to config the tree like this:
let config= {
                        "core": {
                            "multiple": selection.type === 'PICKTREE' ? false : true, // no multiselection
                            "themes": {
                                "variant": "large",
                                "dots": false // no connecting dots between dots
                            }
                        }
                    };

Are there certain combination of settings that prevent other settings from working as defined in the documentation?
Should the settings and data all be supplied in the same object at the same time when instantiating the tree?

**Comment by vakata** [comment]
When creating the tree it accepts a config object. You create the tree once, so all needed configuration options need to be set.
