### ISSUE TITLE
real_checkboxes boolean prop

### ISSUE THREAD

**Issue by armin-gitter** [vakata/jstree#2409]
Hi, how can i enable real_checkboxes feature in jsTree 3.3.10, I want to submit checkboxes on a form.

Thanks

**Comment by vakata** [comment]
They are not supported (as only visible parts of the tree are kept in the DOM). You'd be better off using the changed.jstree event and populate a hidden input (for example a multiple select) with all the values you need. Still, there is an experimental plugin - include it in your page and activate it on your instance:
https://github.com/vakata/jstree/blob/master/src/misc.js#L65

**Comment by armin-gitter** [comment]
thanks, where should i put that code ?
after js file of TreeView ?

**Comment by armin-gitter** [comment]
Hello, Thanks for your help. it's ok now, and i achieved real checkboxes in v 3.3.10
and I set a name attr for all genereated checkboxes but i want to bind  attr value, please help me to bind values into checkbox inputs
