### ISSUE TITLE
tree config setting combinations don't seem to work together

### ISSUE THREAD

**Issue by gwheeloc** [vakata/jstree#2410]
I have a need to change the multiple selection config setting from true to false, or the reverse depending on what the user is doing.  
I made a couple of fiddles to illustrate the problems I'm having in hopes you can correct me.
Why does this **not allow** multiple selections: http://jsfiddle.net/4eLzvwmh/
Why does this **allow** multiple selections, but the theme does not get applied: http://jsfiddle.net/ebc9g6fz/

I want both conditions to work, but can't seem to get them working together.

Additional question: If I change the tree settings and then call refresh(), does the tree get updated with the new settings? or do I need to use destroy(),  and recreate the tree?

Thank you.

**Comment by vakata** [comment]
Both examples allow for multiple selections (using ctrl).

Anyway - jsTree does not support changing the config at runtime - you need to destroy the instance and recreate it.

Also keep in mind - any config options when creating the tree are applied on top of the defaults.
