### ISSUE TITLE
open_node animation

### ISSUE THREAD

**Issue by ArturRusak** [vakata/jstree#2411]
hi,I have this code for open/close node by click. I want to do it with animation, but it isn't working with animation.

//open close by click on item
$('#jstree2').on('select_node.jstree', function (e, data) {
  const { node } = data;
  const isClickByLink = $(data.event.currentTarget).hasClass('jstree-anchor');

  if (!node.state.opened && node.children.length && isClickByLink) {
    data.instance.open_node(node, () => {}, 500);
    return;
  } else if (isClickByLink) {
    data.instance.close_node(node, true);
  }
});

**Comment by vakata** [comment]
Your code seems to work fine:
https://jsfiddle.net/mLa4nsxq/

Maybe you have disabled animations in your config?
