### ISSUE TITLE
Why doesn't the internal instance_counter get reset

### ISSUE THREAD

**Issue by gwheeloc** [vakata/jstree#2412]
For my website needs I save the id of the nodes (ex: j1_1) for those nodes which have been selected so I can re-select them at a future time.  When the tree is destroyed via the .destroy() method and I create a new tree for the same data as the previous time it was rendered,  I see that the root node id an the other nodes ids begin with a new higher number like j2_1 or j3_1 ... etc..  I tracked it down to the internal instance_counter variable of your plugin. I see it doesn't get reset.  Am I not destroying the tree correctly?  $.jstree.reference('#treeContainer').destroy();

**Comment by vakata** [comment]
This is by design - there is no way for jstree to know if you are recreating a tree, or creating a new one. For anything serious where you need consistent IDs you should set the IDs yourself and not rely on jstree's autogenerated ones.
