### ISSUE TITLE
resfresh_node freeze targeted node

### ISSUE THREAD

**Issue by Robinouchat** [vakata/jstree#2413]
Hi and thanks about this amazing plugin ^^
I have a little problem, i try to call the refresh_node function to reload a specifc node after i updated the core data.
But after the refresh_node function, the targeted node is freeze and i can't open it. Do you have any idea about what i'm doing wrong ?

`			
//Get the node

			var node = $('#jstree_demo_div').jstree(true).get_node(numNoeud)
			console.log("node"+node.id);
			//Set the data

			$('#jstree_demo_div').jstree(true).settings.core.data = dataTemp;
			//Refresh the node

			$('#jstree_demo_div').jstree(true).refresh_node(node);`

Thanks a lot,
Robin Hood

**Comment by kpetrow** [comment]
Instead of reloading the entire tree it is better to target specific nodes that need altering.   Refresh needs to parse the data and load in handlers etc.. where as set_text, set_type,set_id etc... can load edit single nodes

**Comment by vakata** [comment]
Refresh the whole tree - you can not refresh a single node, when your data is a simple object (and not a callback function or AJAX config).
