### ISSUE TITLE
How to tell if check_callback returns false on dnd_stop

### ISSUE THREAD

**Issue by kpetrow** [vakata/jstree#2414]
Link to SO issue:
https://stackoverflow.com/questions/62842037/jstree-tell-if-check-callback-is-true-during-dnd-stop-event

I am dragging from one tree to another and only allowing items from tree 1 to be dropped on certain items on tree2.  How can i tell on dnd_stop if the drag was succesful or was not allowed byt the check_callback function:
check callback
```
"check_callback": function(operation, node, node_parent, node_position, more) {
                if (!more || !more.dnd) return true;
                var allow;
                switch (node_parent.text) {
                    case "programs":
                        allow = ['exe'].indexOf(node.id.split('.').pop())
                        break;   
                    default:
                        allow = -1;
                }
                return allow > -1;
}
        }
```

dnd_stop:
```
$(document).on('dnd_stop.vakata', function(e, data) {
        console.log(e, data);
        // was this an dropped event or prevented by check_callback?????
       //find drop target
       ref = $j('#tree2').jstree(true);
       parent = ref.get_node(data.event.target);
 });
```

Thanks

**Comment by vakata** [comment]
You can not - dnd_stop happens BEFORE the final check_callback. When dealing with tree-to-tree moves - do NOT use the low-level dnd* events - all you need are the jstree events.

**Comment by kpetrow** [comment]
Which street event should I look at?  Create_node doesnt seem to be fired.

**Comment by kpetrow** [comment]
@vakata I went through every event in jstree events and couldnt find any that triggers on drag stop.  I figured i had two options:
1. rerun the call back manually and see if i am in true/false state
2. check the icon. 

I went with option 2:
 ```
$j(document).on('dnd_stop.vakata', function(e, data) {
            if ($j('.jstree-icon.jstree-ok').length > 0) {
                console.log(e, data);
                ref = $j('#project_list_container').jstree(true);
                parent = ref.get_node(data.event.target);
            } else
                console.log('canceled')
        });
```
