### ISSUE TITLE
Make it work with Material icons

### ISSUE THREAD

**Issue by KSD-France** [vakata/jstree#2415]
First: thanks for the hard work on this very useful piece of JS!

The only thing that prevents us from fully using it is the lack of support for [Material icons](https://material.io/resources/icons/) (already briefly reported in #2310).

Material icons differ from other font-icon libraries in that it does not fully rely on the use of custom classes but also on the content of the `<i>` element. For instance: `<i class="material-icons">settings</i>`.

We threw a very simple fork [there](https://github.com/KSD-France/jstree) but would be interested in hearing your thoughts about this and the possibility of integrating this in your `master`.

**Comment by vakata** [comment]
This can be packaged as 3rd party plugin similar to those here:
https://github.com/vakata/jstree/blob/master/src/misc.js#L221

**Comment by KSD-France** [comment]
Thanks for the pointer! Just rewrote it as a plugin.

We totally understand your strategy. We were just confused because we could not find documentation on the `misc.js` plugins file (neither on how to use it nor on how to create these plugins), did we miss something?
