### ISSUE TITLE
Highlighting problem with wholerow plugin enabled

### ISSUE THREAD

**Issue by pbrown12303** [vakata/jstree#2417]
With wholerow enabled, a selected node does not highlight with a single click: you have to click a second time (not a double click but a click, pause, click) before the node will highlight. If you remove the wholerow plugin it works as expected. This is with version 3.3.10.

**Comment by vakata** [comment]
Please provide an example (or modify this fiddle) - seems to work fine for me:
https://jsfiddle.net/jst4eyvp/
