### ISSUE TITLE
jstree node arrow nt showing in mobile chrome working fine at other browsers

### ISSUE THREAD

**Issue by ting5875** [vakata/jstree#2420]
> is not showing at mobile chrome

**Comment by ferdimorais** [comment]
Same here, print from jstree website.

![image](https://user-images.githubusercontent.com/63595324/89542682-5ce97b80-d7d6-11ea-8dc7-24aa39f20c2e.png)

**Comment by ferdimorais** [comment]
Also, when I inspect the mobile browser on chrome: if I uncheck the css source for the background image and check it again, then it shows on the browser.

**Comment by vakata** [comment]
Seems like a browser problem to me. I am afraid there is nothing I can do.
