### ISSUE TITLE
JQuery Edge changes break jsfiddle examples in this repo

### ISSUE THREAD

**Issue by j60tt0** [vakata/jstree#2423]
The simplest [example](http://jsfiddle.net/vakata/2kwkh2uL/) referenced in the documentation is broken due to the [removal](https://github.com/jquery/jquery/commit/58f0c00bed695f934bb205c6115e5fe99dd5c27b#diff-3f1223a688c3cbe3a76f223768a09427) of previously deprecated features of JQuery.

This should be fixed by https://github.com/vakata/jstree/pull/2422

**Comment by vakata** [comment]
Thank you for reporting - this is because jQuery edge will not support IE8, but jstree still does.
