### ISSUE TITLE
[Accessibility Issue] Incorrect tree items number announced in jsTree - v3.3.10

### ISSUE THREAD

**Issue by Karkhutvy** [vakata/jstree#2424]
It seems that screen readers treating single jstree item as two items and shows the number and ordinal number of elements doubled. 
The problem can be reproduced on jstree basic example from https://www.jstree.com/ using 
JAWS 2020.2006. 12 ILM or NVDA 2020.2  and Google Chrome 84.0.4147.105

Steps to reproduce:
1. Go to https://www.jstree.com/
2. Navigate to treeitem "Root node 1" from the example tree.
Expected result: Announcement  with " Root node 1 opened - one of two"
Actual result: Announcement  with " Root node 1 opened - two of four"

Problem is repoduced for every node from mentined tree - for example "custom icon URL" node announced as "4 of 8" instead of "2 of 4". As we can see tree with 4 items was announced as tree with 8. And items numbers starts from 2 instead of 1 and increasing with step 2.

**Comment by vakata** [comment]
This is most likely due to this commit:
https://github.com/vakata/jstree/commit/dd8f74ed706fedfe7814f3104dc337543415426d

I believe those were tips given in an issue:
https://github.com/vakata/jstree/issues/1926

I am happy to revert this commit, but I will do so when I get the time to install and test for myself as I am getting conflicting feedback. This is no one's fault of course - it is just that the spec and implementations of trees seem to be very different.

**Comment by Karkhutvy** [comment]
Thanks for the answer. I had problems with wrong annoncement described in #1926  when used jsTree version 3.3.9. In version 3.3.10 many accesibility issues were fixed and for my opinion screen readers works better with version 3.3.10. It seems that described in the ticket behavior is also browser dependent. I tested this case with different browsers and for Mozilla Firefox nodes number was always announced as "1 of 1" instead of doubled values. For Microsoft Edge and Internet Explorer all works fine.
Also when I used JAWS - selection state for the selected node was not announced. But, when used NVDA  - selection state for unselected nodes was anoounced(for the selected - not announced too). It is hard to find the same behavior for different screen reader/browser combination.

**Comment by Karkhutvy** [comment]
I found that screen readers read incorrect elements number in jsTree because each listitem in jsTree  v3.3.10 contains duplicated aria attributes for both elements `li `and` a`. That is why Chrome detects one list item as two list items.
Wai-aria practices recommend using the role “treeitem” to `li` or `a` element. 

> “The role is set on either the li or on an a element contained in the li.
> The role is set on the element that is interactive and focusable:
> If the node is a parent node that does not contain a link, the li element has the treeitem role.
> If the node is an end node that contains a link, the a element has the treeitem role.”
https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html

In our case `a` element is interactive and focusable and has “treeitem” role. Hence, `a `element should contain aria-attributes needed for “treeitem” role. And for correct behavior - duplicated aria-attributes should be removed from `li` elements.

Also, the role “presentation” can be removed from `li` elements. Wai-aria practices describe the ability to assign role=”none” for `li` elements: 

> “A listitem is required to be contained by a list, but the containing element is no longer a list; it is a tree or a group.
> Removing the listitem semantic from the browser's accessibility tree eliminates the potential for confusing rendering by assistive technologies.” 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html

I created the custom version of jsTree v3.3.10 where aria attributes were removed from `li `elements and leave them for a` `elements only. I tested this version in Chrome, Firefox, Edge, IE 11 with Jaws and NVDA. And problems described in https://github.com/vakata/jstree/issues/2424 and https://github.com/vakata/jstree/issues/2431 were fixed. 
What do you think about fixing jsTree  v3.3.10 this way?
I can create a pull request with my changes if needed.

**Comment by vakata** [comment]
@Karkhutvy thank you! A pull request would be great!
