### ISSUE TITLE
How to disable toggling checkbox?

### ISSUE THREAD

**Issue by sharathdaniel** [vakata/jstree#2428]
This is how i have initialized the plugin. I have some items already pre selected, user should be not be able to uncheck it or check other checkboxes.
`$('.access-tree').jstree({
		"plugins" : [ "checkbox" ]
	});`

TBH, the API documentation is not at all beginner friendly. Can't figure out how to enable/disable an option, no example to use a method.

**Comment by vakata** [comment]
Take a look at the conditionalselect plugin on this page: https://www.jstree.com/plugins/
It does what you need.
