### ISSUE TITLE
scrollspy plugin feature request

### ISSUE THREAD

**Issue by erez-o** [vakata/jstree#2430]
Hi, 

I think that a native scrollspy plugin would be a great addition to this package. 

Would you consider adding it or it's beyond the scope?

Thanks.

**Comment by vakata** [comment]
This would most likely be a plugin. I am not eager to add this to the core, but I maintain a collection of 3rd party plugins in https://github.com/vakata/jstree/blob/master/src/misc.js so feel free to open a PR.
