### ISSUE TITLE
get_children_dom returns false after upgrade 3.3.5 -> 3.3.6

### ISSUE THREAD

**Issue by mateuszf** [vakata/jstree#2435]
`$tree.jstree(true).get_children_dom($tree)` always returns `false` after upgrade to 3.3.6 and onwards (tested up to 3.3.10).

This code is executed in `loaded.jstree` event handler. It's not about node not being rendered bacause even if it's put in the setTimeout(..., 1000) handler it still returns `false`

**Comment by vakata** [comment]
Seems to work fine for me:
https://jsfiddle.net/wvp24ury/

Please provide a demo.
