### ISSUE TITLE
Background image with dotted stripes is not displayed in mobile Chrome browser

### ISSUE THREAD

**Issue by Stechentsev** [vakata/jstree#2436]
![photo_2020-09-15_12-57-47](https://user-images.githubusercontent.com/71321289/93196453-20089100-f753-11ea-8c44-17fa3a7d40d4.jpg)
![photo_2020-09-15_12-57-40](https://user-images.githubusercontent.com/71321289/93196470-2565db80-f753-11ea-912d-acf0ad0cca9b.jpg)

Picture 1 - mobile firefox;
Picture 2 -  Chrome 83.0.4103.106.

**Comment by vakata** [comment]
I believe there was another ticket about this and it turned out to be a browser bug. I will find it and link to it here.

**Comment by stla** [comment]
I had a similar issue and it was due to `themes.responsive = true`.

**Comment by vakata** [comment]
Nothing on jstree's side, thanks @stla - this is most probably it.
