### ISSUE TITLE
open_all method

### ISSUE THREAD

**Issue by sagittaracc** [vakata/jstree#2446]
The documentation says:
opens all nodes within a node (or the tree), revealing their children. If the node is not loaded it will be loaded and opened once ready.

But I don't need to load nodes which are not loaded yet. How can I do that?

**Comment by vakata** [comment]
I am not sure why you would need this, but anyway - you can traverse all nodes from jstree's internal structure and check their loaded and children properties - gather nodes which are loaded and have children in an array and then call open_node with that array.
