### ISSUE TITLE
Accessibility solution (screen reader) for old jstree version 1.0-rc3

### ISSUE THREAD

**Issue by dishjag** [vakata/jstree#2447]
I have to implement accessibility support on a old software which uses old jstree(v1.0-rc3). I have to make sure it has proper keyboard navigation and screen reader support. I was able to  make sure key board navigation works using hotkeys and js. But even after adding aria information i am not getting NVDA announcements , it uses lazy loading and all json is sent by server to build tree so i guess NVDA never gets whole information as children are loaded after the click on expand. 

I know that you have a new and better version that support accessibility but i cant replace old dependency and have to make workarounds so could you guide me for what could be done to get screen reader support for the old jstree. I would appreciate it.

Thanks 
jagdish

**Comment by vakata** [comment]
Sorry, I can not - v.1 was deprecated many many years ago. I do not support it.
