### ISSUE TITLE
How to deal with items that are long and that contain <br>

### ISSUE THREAD

**Issue by MagTun** [vakata/jstree#2451]
Hi, 

I am having some troubles to implement your plugin with the structure of my lists. Some of my items contain long text and `<br>, <i>,<b>` tags. Here is an example:

```
<ul>
<li>Tree<ul>
        <li>Title 1<br>Text under Title 1 <br>Lorem ipsum <b>dolor</b> sit amet <b><i>consectetur</i></b>
            adipisicing elit. Ad, quidem culpa quisquam aliquid dignissimos a error laudantium tenetur natus
            perspiciatis consectetur officiis obcaecati! Facere fugiat sequi totam aliquid. Similique,
            nesciunt?<ul>
                <li>Title 1.1<br>Text under title 1.1 <br><br>Lorem ipsum dolor sit amet consectetur
                    adipisicing elit. Ad, quidem culpa quisquam aliquid dignissimos a error laudantium
                    tenetur natus perspiciatis consectetur officiis obcaecati! Facere fugiat sequi totam
                    aliquid. Similique, nesciunt?<ul>
                        <li><b>Title</b> <i>1.1.1</i><br>Text under title 1.1.1</li>
                    </ul>
                </li>
                <li>Title 1.2</li>
            </ul>
        </li>
```
So jstree doesn't render the list properly. You can see what I mean [here](https://jsfiddle.net/o6naxqvz/)
I have try these two solutions ([here ](https://github.com/vakata/jstree/issues/270#issuecomment-44617871)and [here](https://stackoverflow.com/a/24746827)) but without any success.
How can I best implement jstree with such a list structure? Thanks  for you help!

Also, thanks a lot for this very nice plugin!

**Comment by vakata** [comment]
Sorry for the trouble you are having. Did you try this, I know it is not perfect (the solution you found), but I doubt there is a way for this too look any nicer in any tree:
https://jsfiddle.net/k4fp5edh/

**Comment by MagTun** [comment]
Thanks for your answer. As I wasn't able to make it work, I improved on this simple script that generates a [nested list](https://www.gnostice.com/nl_article.asp?id=208&t=Making_An_Interactive_TreeView_Control_From_An_HTML_Nested_List)
