### ISSUE TITLE
How do you change the folder icon color

### ISSUE THREAD

**Issue by pkasson** [vakata/jstree#2454]
Can you change the folder icon, or the dots colors ?

When a node is expanded, it shows the folder expanded icon, but it is hard to see on a dark background.

Also, when the initial list appears, which are 'parent' nodes, the expanded folder icons don't appear until you click them, is there any way to show the fact that these are parent folders so the user knows they can be expanded ?

**Comment by vakata** [comment]
There is a dark theme available, you can also create your own themes. The default folder is just that - the default - read the docs - you can change the icon to whatever you need.
