### ISSUE TITLE
Событие завершения прогрузки узла дерева

### ISSUE THREAD

**Issue by sagittaracc** [vakata/jstree#2462]
Есть ли какое-нибудь событие которое возникает когда узел полностью прогружен. Я имею ввиду когда закончится формирование DOM узла.

**Comment by vakata** [comment]
Sorry, please use English, I do not speak Russian.

**Comment by sagittaracc** [comment]
Sorry, i'm just wondering if there is a way to capture when the tree DOM is done loading in case i load loads of nodes at once.
When i do that the tree is kinda frozen until the dom is completely drawn

**Comment by vakata** [comment]
There is the `ready.jstree` event and the `state_ready.jstree` event (in case you are using the state plugin and want to know when the state is done being applied).
