### ISSUE TITLE
Turn ON/OFF cascade selection after init

### ISSUE THREAD

**Issue by shahimclt** [vakata/jstree#2463]
I have been looking for a way to turn on or off the cascade feature based on an external switch. 
Is there a way to change the `cascade` config at runtime or a callback to determine cascade behaviour? I could not find anything in the docs.

My only option currently is to traverse the tree and cascade manually

**Comment by vakata** [comment]
Officialy switching at runtime is not supported, but it shoudl work - target the instance's internal settings object:
```$('.jstree').eq(0).jstree(true).settings.checkbox.cascade = ...```
