### ISSUE TITLE
Deselect Node Event isn't fired

### ISSUE THREAD

**Issue by mmeah** [vakata/jstree#247]
This was an issue filed on stackoverflow.com, but the solution seems a bit convoluted.
http://stackoverflow.com/questions/11576444/how-to-listen-to-jstree-deselect-event/

Is there a better solution? Or is this a UI bug?

Site Question: According to the documentation, 'deselect_node' triggers an event, but nothing seems to happen. I am able to listen to select event though. How to listen to jsTree deselect event?

**Comment by dotsad** [comment]
This is still not working in latest build. I think we need to get `unselect_node.jstree` event and fire before `select_node.jstree` event. To have an ability to prohibit/undo selecting a new node is crucial. `deselect_node.jstree` only fires on when holding CTRL. I do not need multipe selection. Reason i need unselect event, is to check if user should save changes they made on that node before elaving to another node. Currently there is no way to have a previously selected event after user clicks on new node. 

![un_select](https://cloud.githubusercontent.com/assets/1864317/7326560/106bb794-ea7b-11e4-94bc-7ca0120e5175.gif)

**Comment by vakata** [comment]
Listen for both `deselect_node.jstree` and `deselect_all.jstree` - when a node is activated all other nodes are deselected as whole and not individually.

Also keep in mind it is best to listen for `changed.jstree` and not for `select_node.jstree`, `deselect_node.jstree` and `deselect_all.jstree`. When there is a change in selection - `changed.jstree` will fire and is the go-to event, all others should be used when you specifically need them to achieve something more advanced.
