### ISSUE TITLE
dnd feature

### ISSUE THREAD

**Issue by uc-pya** [vakata/jstree#2474]
how to use dnd plugin with jstree v4
i tried this option
 "dnd": {
                "open_timeout": 1,
                "is_draggable": function () {
                    return false; //data.li_attr.tid.length > 2
                },
                "drag_check": function() {
                    alert("drag start");
                },
                "drop_finish" : function () {
                    alert("DROP");
                },
                "drag_finish": function() {
                    alert("drag finish");
                },

            },
but dnd is not working
can anyone suggest how to enable it because it was working with jquery based jsTree

**Comment by vakata** [comment]
v.4 is not released yet, most plugins are not finished. v4 is in development - there is not even an alpha version available yet.
