### ISSUE TITLE
Can't send authorization headers in ajax request 

### ISSUE THREAD

**Issue by chetan776** [vakata/jstree#2477]
I want to send headers in my ajax request but in the library, there is no option to send headers.

**Comment by vakata** [comment]
```core.data``` accepts a jQuery AJAX settings object - so you should be able to send and do whatever you need (https://api.jquery.com/jquery.ajax/ - search for "headers" and you will find the ```beforeSend``` option which is how jQuery does it). You can also set ```core.data``` to callback function and inside it you can use whatever you please to fire off AJAX events so you have FULL control over headers, data, etc.
