### ISSUE TITLE
jstree without jquery?

### ISSUE THREAD

**Issue by tacman** [vakata/jstree#2493]
So bootstrap 5 is in beta 2, next release might be stable.  The big new change is that jquery is no longer required.  

So I've been playing around with removing jQuery, and was wondering if there were any plans to release jstree without needing jquery.  

Plain javascript supports custom events, and fetch() is now standard across browsers, so jquery's ajax isn't necessary.

It'd be nice to get away from jQuery, I think it'd be cleaner then to use Vue or React.

Not urgent, but it'd be nice.

Also in the "nice to have" list -- a demo using bootstrap 5.

**Comment by vakata** [comment]
Check out the v.4 branch - it is still in alpha stages, but is built only using vanillaJS with a custom virtual DOM.
