### ISSUE TITLE
 move_node bug

### ISSUE THREAD

**Issue by wenreshui** [vakata/jstree#2503]
When the mode_node method is used, the child_d field of the parent node repeats

**Comment by vakata** [comment]
Please provide a demo of the issue, as I can not reproduce this with the current code.

**Comment by wenreshui** [comment]
jstree version:3.3.11  jquery version:3.0.0-alpha1
`var tree = $("#accessGateWayTree");

	if (tree.jstree(true)) {
		tree.jstree(true).destroy();
	}
	tree.jstree({
		'core': {
			'themes': {
				"dots": false,
				"ellipsis": true
			},
			'check_callback': true,
			'data': treeData,
			'multiple': false
		},
		"plugins": ["wholerow"]
	});

`

**Comment by wenreshui** [comment]
So sorry!This is my problem!!
