### ISSUE TITLE
How to use Large iconset?

### ISSUE THREAD

**Issue by lexterror** [vakata/jstree#2508]
Hi, I'm trying to use the large icon theme. I used  "variant" : "large" ,but it doesn't change icon size. I want to be able to change default icon size!

**Comment by vakata** [comment]
The included icons are all the same size, but the large variant gives you more space to add custom CSS and larger icons. The current version uses raster icons, so no variants are included - this would make the package too big.

Here is the difference in size:
![image](https://user-images.githubusercontent.com/146052/111641512-e69a0680-8805-11eb-9086-bc2ffddd330e.png)
