### ISSUE TITLE
font-awesome icon problem on jstree leaf action

### ISSUE THREAD

**Issue by mardif** [vakata/jstree#2512]
Hi @vakata ,

thanks a lot for this amazing project, it's very helpful!!!
I'm using jstree+actions (both from npm repo) with my symfony 5 project + fontawesome (ver 5.12) + webpack encore.
Adding the action to the tree with:

```
jstree.add_action('all', {
    id: 'show-action',
    event: 'click',
    selector: 'i.jstree-icon',
    title: 'Modify',
    after: true,
    text: "",
    'class': 'show-action fa fa-caret-right',
    callback: function (node_id, node, action_id, action_el, event) {
        func(node);
    }
});
```

webpack `yarn run dev` works without problem, but loading the page, I see it:

![image](https://user-images.githubusercontent.com/4513750/112514194-59225d80-8d95-11eb-925a-b95f46790881.png)

on the right side are present a list of svg.

If I change the class value removing the **fa** class (so finally it will be  _'class': 'show-action fa-caret-right',_), reloading the page I see:

![image](https://user-images.githubusercontent.com/4513750/112514909-14e38d00-8d96-11eb-9c14-5dcb9f304c2e.png)

If I inspect it with Chrome DevTool, and I add the fas class, I see the correct icon:

![image](https://user-images.githubusercontent.com/4513750/112515620-b5d24800-8d96-11eb-8931-0919f240253e.png)

What will be the problem??

Thanks in advance

**Comment by vakata** [comment]
Sorry, this is related to actions which is not a plugin that I created - open an issue with the creator. Is there a repo for it?
