### ISSUE TITLE
Any possibility of a different tree like structure?

### ISSUE THREAD

**Issue by lexterror** [vakata/jstree#2513]
Hi, I was looking around and I wanted to know if would support different tree structures?

Example:

![image](https://user-images.githubusercontent.com/16135535/112522699-52cfb980-8d74-11eb-831a-a553e33e3946.png)

**Comment by vakata** [comment]
Sorry, this is currently not supprted. v.4 will have different renderers - so technically this will be easier to achieve in v.4, but it is still not on my TODO list for the initial versions.
