### ISSUE TITLE
Is it possible to hide one specific node in jstree

### ISSUE THREAD

**Issue by bencin-benny** [vakata/jstree#2516]
Hi 
I am tried to hide one node in the jstree but can't hide the node.
                 { text:  `${data}`,
                state : {  'opened' : false, 'selected' : false },
                children: [{ text: `${json_data_object[data]}`,icon:"fa fa-adjust" }],
                icon:"fa fa-adjust" }
                
                this is the sample of a node
in this, I tried with " 'hidden':true " in the status 
also, hide with id $('#jstree').jstree().hide_node(id);

these are not working

**Comment by vakata** [comment]
Hide node seems to work fine: 
https://jsfiddle.net/bd7aL4c0/1/

**Comment by bencin-benny** [comment]
I tried this one didn't work

**Comment by bencin-benny** [comment]
Hi

I tried this method but not possible to hide the nodes

Regards,
Bencin
