### ISSUE TITLE
 hide one specific node in jstree

### ISSUE THREAD

**Issue by bencin-benny** [vakata/jstree#2517]
Hi Ivan

I tried all the possible way get in Google to hide a specific node in the jstree but can't hide the node

Also I tried #2516 suggest method that also not working 

Is there any other possible methods for hide a specific node in jstree

Regards 

Bencin Benny

**Comment by vakata** [comment]
Please do not open duplicates. I already provided an example - there is no other way to hide a node, just invoke hide_node. Here is the demo again - this time simplified - watch node 1 disappear:
https://jsfiddle.net/jty6L5cd/
