### ISSUE TITLE
Checkbox plugin's property 'whole_node' does not work as documented

### ISSUE THREAD

**Issue by jmechevarria** [vakata/jstree#2518]
Hello

I was looking for a way to select a node and NOT have its checkbox state changed. For which, i put: 

`$.jstree.defaults.checkbox.whole_node = false;`

before the tree element initialization. It did not work as expected.

Current behavior with `whole_node: true`:
-
- Click on a node (not its checkbox): checkbox is toggled.

Current behavior with `whole_node: false`:
-
- Click on a node (not its checkbox): checkbox _is_ checked AND all other siblings are unchecked.

Desired behavior with `whole_node: false` (or some other way):
-
- Click on a node (not its checkbox): no checkbox changes.

---------------------------------------------------------------------------------------
**Checkbox** plugin's property `whole_node` does not work [as documented](https://www.jstree.com/api/#/?f=$.jstree.defaults.checkbox.whole_node):

> a boolean indicating if clicking anywhere on the node should act as clicking on the checkbox. Defaults to true.

At least for me, it was misleading.

Thank you

**Comment by vakata** [comment]
The node checkbox is tied to its selected state - when clicking anywhere on the node - the checkbox will be set, but if ```whole_node``` is ```false```, all other selected nodes will be deselected. If this is not the behavior you need you might also want to set ```tie_selection``` to ```false```: https://www.jstree.com/api/#/?q=tie_selection

**Comment by jmechevarria** [comment]
Hello, and thanks for the rapid reply.

To be completely honest, I still think `whole_node`'s description in the docs is misleading, might be just me though.

The combination of `whole_node: false` and `tie_selection: false` did indeed achieve what I wanted visually, I'll keep testing it to see if 

> checkbox are bound to [...] an internal array maintained by the checkbox plugin

does not have unwanted effects in my case.

Thanks a lot

**Comment by ismirsehregal** [comment]
I'm having a similar issue [here](https://github.com/stla/jsTreeR/issues/18#issuecomment-1772393595)

Is `checkbox.keep_selected_style` set to `false` when using `whole_node: false` and `tie_selection: false`?
