### ISSUE TITLE
Drop IE for version 4

### ISSUE THREAD

**Issue by tacman** [vakata/jstree#2519]
"NO IE FOR NOW, BUT WILL BE TRANSPILED LATER"

IE is dead, I think it'd be better if version 4 dropped support altogether.  To spend any time at all on it would be a distractrion.

Looking forward to version 4!

**Comment by vakata** [comment]
Given the recent news that IE11 support will end August 2021 - I will do exactly that. I do not plan on changing the code - it will be shipped as is - if someone wants to - they can transpile.
