### ISSUE TITLE
DND - Moves overly restricted, not allowing intermediate level nodes

### ISSUE THREAD

**Issue by MrBenGriffin** [vakata/jstree#2524]
The screen capture below shows an attempt to move node 'R27' to be the last child of - nodes R8, R9, R13, R4, R16, R11, R21, and R24 respectively.  

Current interaction is limited to current tier (R8) and deepest tier (R3).  Since each tier level is has a contextual depth, there is no reason why dragging the node into each depth zone should not allow placing the node as the last sibling of that tier.  

All of the aforementioned nodes should be available. 

While I am aware that the workaround (using defaults.dnd.inside_pos=last    – I also believe that 'last' should be the default), it is not UX intuitive to think of dropping a node onto the parent in order to place it correctly.

https://user-images.githubusercontent.com/1785064/116526359-6de09c80-a8d1-11eb-8455-5feeb412398f.mov

**Comment by vakata** [comment]
While dragging hover over R8, R9, R13, R4, R16, R11, R21 or R24 and release when the indicator is below the respective node.

**Comment by MrBenGriffin** [comment]
Thanks for your response - but I don't see it.   I can drag a node into (make child of) R8, etc.. but I don't see what you suggest.  See below - attempting to move R7 into being the last child of R12. I can easily move it to be the first, or second child of R12, but to make it the last child, I have to either close R22 or I have to drag it onto R12 (with the default option set), neither of which are intuitive to a normal user.

https://user-images.githubusercontent.com/1785064/116536391-bfdaef80-a8dc-11eb-9110-79ef9aac7b1a.mov

**Comment by MrBenGriffin** [comment]
Okay I found it.  It's a very small space, just in the corner of the new previous sibling.
I have to say that it's pretty hard to find the specific corner.  I will test on another browser.  It would be good to see a debugging visualisation of each of the drop areas.

https://user-images.githubusercontent.com/1785064/116540209-c1f37d00-a8e1-11eb-9299-3c416984e19f.mov
