### ISSUE TITLE
 Uncaught InternalError: too much recursion - selecting all nodes using checkbox

### ISSUE THREAD

**Issue by KennethSeiero** [vakata/jstree#2525]
When trying to check 703 checkboxes, i receive an error. I'm using multi state checkboxes.

I've got all 703 node-items in an "All" parent group. When clicking this "All"-checkbox, i get below error.

Uncaught InternalError: too much recursion
    _cascade_new_checked_state https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.11/jstree.min.js:4

However, if i call the jstree API using the following: 

ReportsDialog.Tree.element.jstree(true).select_all()

It works without any issues, and everything gets checked..

**Comment by vakata** [comment]
This is odd - can you provide a demo - usually an error with so little nodes means a problem with the data - a parent nested in a descendant for example.
