### ISSUE TITLE
Contextmenu plugin HTML element

### ISSUE THREAD

**Issue by Cristiian** [vakata/jstree#2527]
Hi, Is there a way to change the element in wich the contextmenu appends to?, currently is being attatched to body tag. I'm working with an Angular application, and the contextmenu appears outside the component scope and not being shown.

thank you for your help

![Captura de pantalla 2021-05-03 163658](https://user-images.githubusercontent.com/5752018/116937344-b5975900-ac2e-11eb-9ef0-0f1d6cf745d9.png)

**Comment by vakata** [comment]
There is not such option currently. You can temporarily fork the project and change this line and check if it solves the issue:
https://github.com/vakata/jstree/blob/master/src/jstree.contextmenu.js#L486
