### ISSUE TITLE
Reversing a nested drop

### ISSUE THREAD

**Issue by tacman** [vakata/jstree#2529]
I'm having trouble figuring out how to move something that's was a root into inside an item back out again.

My storage locations start out as all roots.  I can nest them pretty easily:

![image](https://user-images.githubusercontent.com/619585/118290637-a624d500-b4a4-11eb-8f49-18efa95a1610.png)

For example, how do I move "box" to be a root again?  I know I could create a fake root, then drag it out to be a child of that fake root, but that complicates my API call that updates the database.  I guess I can do that, just wanted to ask here if there's a way to do that.  Seems like an operation should be reversable.

Thx.

**Comment by vakata** [comment]
You can drag it above or below an existing root node - while dragging hover the node but place your mouse near the top or bottom of the node. When you drop the node will be positioned above or below the hovered node.

**Comment by tacman** [comment]
I have not been able to do that using Chrome or Firefox.
