### ISSUE TITLE
Dots are not shown when using plugin wholerow

### ISSUE THREAD

**Issue by VcNagZ** [vakata/jstree#2539]
Hi everyone!

On 3.3.11 version, when you use the plugin "wholerow", you can't show dots anymore. Even if you use core.themes.dots = true, the class "jstree-no-dots" is still here on the ul element, and so the dots are not visible.

Is it a bug or is it normal with that plugin ?

Can be reproduced here: https://codepen.io/mathang/pen/bZPOJO.

Thanks :)

**Comment by vakata** [comment]
The two plugins are not compatible - the way wholerow works is with a div nested in each node, unfortunately this hides the vertical dots (as they come from nodes that are before the current node in the DOM). 
v.4 (when out) will not have this problem, but it is currently under development.
