### ISSUE TITLE
Show context menu exception

### ISSUE THREAD

**Issue by wumingwuan** [vakata/jstree#2542]
https://www.jstree.com/plugins/
In context menu example, when right click the menu , js exception happened.
![image](https://user-images.githubusercontent.com/11922624/122362544-c86daf00-cf8a-11eb-9b92-ec0fcbc15263.png)

**Comment by vakata** [comment]
My guess is there is something wrong with a plugin you use. The contextmenu works fine on all browsers I could get my hands on and test. What version of chrome are you using?

**Comment by wumingwuan** [comment]
ok , thank you .
after i unistall this chrome plugin in. Everythiing work fine. Sorry for my carelessness.
https://chrome.google.com/webstore/detail/flip-this/donljlliiecjcagcenoeohjmabfegkph
