### ISSUE TITLE
Get all recursuive siblings on clicking parent

### ISSUE THREAD

**Issue by merlingeorge555** [vakata/jstree#2547]
For example:
a
 - b
 - c
    -  d
    -  e
        -  f
        -  g
        -  h

if node 'c' is clicked, all the siblings data  should be returned in hierarchical JSON.
output: {"text":"c", "children": [{ "text": "d", children:[]}, {"text": "e", children:[{"text": "f"}, {"text": "g"}, {"text": "h"}]}]}

**Comment by vakata** [comment]
Use this function:
https://www.jstree.com/api/#/?q=get_json
