### ISSUE TITLE
Round, radiobutton-style buttons for "multiple: false"

### ISSUE THREAD

**Issue by yaronkoren** [vakata/jstree#2549]
When users can only select one value in a tree, i.e. when "multiple: false" is specified, it may be confusing for some users to see checkboxes for each value, since those usually imply that any number of values can be selected. It would be more logical, I think, to have a radiobutton-style display, meaning having circles instead of squares.

**Comment by vakata** [comment]
I do not think you should enable the checkbox plugin if multiple is false. Still, if you want to do that it should be easy to change the icon using CSS in your own page.
