### ISSUE TITLE
attach dnd_stop to selector

### ISSUE THREAD

**Issue by kpetrow** [vakata/jstree#2555]
I have multiple trees, one is a file browser that is available in multiple places/pages(gloabally available) and others are for a page specific feature. The dnd_stop.vakata stop handlers are different for these trees. Is there anyway to attach the handlers to the parent div's? or to add a selector on the "on" handler?
none of these work:

```
$j(document).on('dnd_stop.vakata','#project_manager_body',function(){ })
$j('#project_manager_body').on('dnd_stop.vakata',function(){ })
```

**Comment by vakata** [comment]
The handlers should be different. The solution you came up with is the right one when doing something more complex (otherwise you would not need to use the dnd_* events).
