### ISSUE TITLE
Provide option to suppress deep copy

### ISSUE THREAD

**Issue by timmayo-ds** [vakata/jstree#2558]
Currently jsTree performs a deep copy on each node during tree creation. This causes shared substructure to be duplicated (see pic).   If the shared sub-structure is deep this can lead to major memory and performance problems.  [We recently found a build tree in our application was consuming 200MB]

![image](https://user-images.githubusercontent.com/55847798/132089734-91158daf-8d65-4750-865d-b8e13c764143.png)

It would be great if jsTree provided a way to disable the deep copy.  Naively it looks like replacing 'true' in the $.extend() call below by an optional value would do the job: 

	$.jstree.create = function (el, options) {
		var tmp = new $.jstree.core(++instance_counter),
			opt = options;
		options = $.extend(true, {}, $.jstree.defaults, options);

However, we are not clear whether that would create problems elsewhere

**Comment by vakata** [comment]
It needs to be a deep copy in order to create a full options object. If you are using core.data to build a large tree - try setting core.data to a function which in turn invokes the passed callback:
```
data: [ {...node...},{...node...} ] ->data: function (node, cb) { cb([ {...node...},{...node...} ]); }
```

**Comment by timmayo-ds** [comment]
Thanks. Will give that a go.
