### ISSUE TITLE
CSS background property tweak

### ISSUE THREAD

**Issue by PinkDuck** [vakata/jstree#2560]
```
.jstree-default-large .jstree-last {
	background: transparent;
}
```

better as

```
.jstree-default-large .jstree-last {
	background-image: transparent;
}
```

as otherwise it resets to default all the other background- properties.

**Comment by vakata** [comment]
It probably should reset all background properties. What issue do you run into? Can you provide a screenshot or a demo of what you modified in your custom setup, and how it is affected by this line?

**Comment by PinkDuck** [comment]
This overrode my own custom styles for other background properties, resulting in graphic corruption because of the custom icon grid offsets I'm using. Because your style previously only sets the background-image key but unsets with background:all-in-one this resets everything else with greater impact than necessary. i.e. why set background-image but clear background-*?
