### ISSUE TITLE
dnd issue

### ISSUE THREAD

**Issue by sagittaracc** [vakata/jstree#2564]
Hello!
I am using the dnd plugin.
Here's the problem I am having...
The `check_callback` function triggers all the time even if I am draging over the same node.
Is it possible to detect if the node, I drag over, has changed?

**Comment by sagittaracc** [comment]
Also I know that `check_callback` should return `true` or `false`. But now I need to decide it on the server side, so I have to send an ajax request inside `check_callback` and return what the server responses. How do I do that?

**Comment by vakata** [comment]
check_callback can not be used with ajax - it needs a sync response. Complex rules can be evaluated when the server receives the move_node request, if the complex rules fail - return an error and refresh the tree.

As for multiple triggers - you can process that in your callback - remember the last node and if it is the same node - return the previous return value.
