### ISSUE TITLE
jstree("deselect_all", false);

### ISSUE THREAD

**Issue by kofifus** [vakata/jstree#2572]
I have:

```
$('#tree').on('deselect_node.jstree ', (e, edata) => {
  debugger;
});
```

I then select a node and do:
```
$('#tree').jstree("deselect_all", false);
```

the node gets deselected but the event is not triggered

what am I doing wrong ?

**Comment by vakata** [comment]
Those are separate events - deselect_node and deselect_all. You can listen for both.
