### ISSUE TITLE
Selecting child item is not triggering the auto selectinon of its parent item

### ISSUE THREAD

**Issue by janarthananms** [vakata/jstree#2575]
Selecting child item is not triggering the auto selectinon of its parent item
Its reproducible in JStree's latest version as well. 

[] Parent:
     [] Child 1
     [] Child 2 
- 
Now select child 2 but the parent will not get selected.
But select child 1 the parent will get selected.

**Comment by vakata** [comment]
Look at the demo for the checkbox plugin:
https://www.jstree.com/plugins/

All appears to work properly. Keep in mind that cascading selection is highly configurable and depends on what you have actually configured (it also need the checkbox plugin to be activated for the instance).
