### ISSUE TITLE
Crear tree  desde datos  de mariadb con javascript

### ISSUE THREAD

**Issue by Yeoresley** [vakata/jstree#2576]
Buenas noches porfa alguien me podría ayudar como poblar los datos del árbol de jstree , desde una tabla en mariadb por ejemplo la tabla tienes estas columnas  id | nombre | parental

**Comment by vakata** [comment]
Sorry, I do not speak this language. This however seems like a discussion - my guess is that you want a demo for mariaDB - there is one for mysql, which is the same basically.

**Comment by Yeoresley** [comment]
OK gracias me gustaría que me facilitará la de mysql por favor

**Comment by vakata** [comment]
This is a bit old but it is still a good starting point: https://github.com/vakata/jstree-php-demos
