### ISSUE TITLE
Search Improvement possiblity 

### ISSUE THREAD

**Issue by lambda-science** [vakata/jstree#2577]
Hey,
Hello !

I use JSTree for a project of ontology. I use the search plugin to allow people to quickly find the nodes in my ontology and select them.
However some nodes are associated to synonyms names that I store in the "data" field of node under the "synonyms" field.
I wondered if you had any idea how I could improve the search plugin to not only look for match in the "text" field of nodes (the name of the nodes) but also look for match in a specific location of the "data" field.
Example:
```json
    {
        "id": "6",
        "text": "Type 1 Fiber",
        "icon": true,
        "data": {
            "description": "",
            "synonymes": "my_synonyms1",
        },
        "parent": "5"
    },
```
In this case, by inputing "my_synonyms1" in the search box, this node would also show up !

Any idea ?

Thanks a lot !

**Comment by vakata** [comment]
You can override the default search with your own function and implement whatever logic you need:
https://www.jstree.com/api/#/?q=search_call&f=$.jstree.defaults.search.search_callback
