### ISSUE TITLE
disable item paste on contextmenu by escape

### ISSUE THREAD

**Issue by mmtaheri** [vakata/jstree#2579]
hi
item select cut on contextmenu after change of opinion by press eacape disable item paste in contexmenu.
Thankful

**Comment by vakata** [comment]
I am afraid this can not go into the jstree core, as it is more of an application thing - I guess you'd want the escape key to work even if the tree is not focused. Anyway - it should be pretty easy to implement - listen for the Esc key, and if there is something in the jstree buffer you can clear it. There are dedicated functions for this:
https://www.jstree.com/api/#/?q=buffer
