### ISSUE TITLE
Partially selected parents

### ISSUE THREAD

**Issue by amr-el-sayed** [vakata/jstree#2584]
### Discussed in https://github.com/vakata/jstree/discussions/2583

<div type='discussions-op-text'>

<sup>Originally posted by **amr-el-sayed** November 20, 2021</sup>
Hello!
When I use get the selection using:
the  $('#tree').jstree("get_selected", true);
the resulting array does not include the parents that have partially selected children.

Is there a way to override the prototype or events so it includes the parents node as well?
Thank you!</div>

It will be better to add an option for this in a future version.

**Comment by vakata** [comment]
Hi, loop over ```top_selected``` and for each node invoke ```get_parents``` - merge in one and unique if needed - those are the nodes you are looking for.
