### ISSUE TITLE
How to listen for an event without jQuery

### ISSUE THREAD

**Issue by tacman** [vakata/jstree#2590]
Can I write the following without using jQuery?

```javascript
        $(element)
            .on('changed.jstree', this.onChanged)
        ;

       // this never fires.
        element.addEventListener('changed.jstree',  (event) => {
            console.log(event, 'no jquery!!');
        });

```

I know jQuery events are different than regular dom events, but not sure this is even possible.  In v4 this will be standard, of course, but I'm wondering if there's a way to start coding in preparation for that.

**Comment by vakata** [comment]
Unfortunately not - jQuery will not fire standard events (as far as I know), but it seems that creating a plugin which overwrites the trigger function might work:
```js
(function ($, undefined) {
	"use strict";
	$.jstree.plugins.domevents = function (options, parent) {
		this.trigger = function (ev, data) {
    		parent.trigger.call(this, ev, data);
            if(!data) { data = {}; }
			data.instance = this;
            this.get_container()[0].dispatchEvent(new CustomEvent(ev, { detail : data }));
		};
	};
})(jQuery);
```
Include this in your page and then in the ```plugins``` config array add ```"domevents"```. 
I have not tested this - it is off the top of my head. You can experiment and modify this as you please.

Keep in mind v.4 will be a major new version. Unfortunately I doubt it will be compatible with old event handlers, configurations, etc.
