### ISSUE TITLE
Drag & Drop not working

### ISSUE THREAD

**Issue by redfellow** [vakata/jstree#2591]
Here's my init code:

```js
	jq("#tree", component).jstree({
		"core" : {
			"check_callback" : true,
			"data" : component.loadData,
		},
		"plugins" : ["dnd"]
	});
```

Doesn't look like the plugin & check_callback setting are working because the tree functions virtually the same with/without those parameters.

I'm loading data via a custom function that uses the callback provided by jstree.

**Comment by vakata** [comment]
Seems fine to me: https://jsfiddle.net/sg87vyLz/

Maybe you are not using dist/jstree.js but src/jstree.js which is only the core module?

**Comment by redfellow** [comment]
That was my issue, thanks.
