### ISSUE TITLE
Duplicate parents after load_node, crashes chromium

### ISSUE THREAD

**Issue by chrisadamsonmcri** [vakata/jstree#2592]
I have a JSTree instance, using AJAX to load data.

I perform a data upload via another AJAX call, which completes, then I want to reload the node that I put the data in to refresh it. So then I perform a load_node on the parent node that the new nodes are to be created in, to refresh it, it creates invalid data in the _data structure. 

I call $('#studyDataDiv').jstree("load_node", "/root");

There are duplicate parents, self parents, see screenshot

![image](https://user-images.githubusercontent.com/9276757/147036623-a74423c5-fb03-4af9-b1a8-d0775380e872.png)

/root is its own parent
![image](https://user-images.githubusercontent.com/9276757/147036648-b5bd6a2a-485c-4061-8cf0-17f56a076fb1.png)

all children have duplicate /root in their parent list
![image](https://user-images.githubusercontent.com/9276757/147036842-bf0234ef-013e-4163-809a-94a6b59a60d1.png)

Thank you for an amazing tool.

**Comment by vakata** [comment]
This means something is wrong with your data - there should be no duplicates. Keep in mind the ajax response should only include THE CHILDREN of the specified node, not the node itself.

**Comment by chrisadamsonmcri** [comment]
Yeah I found the problem in my code. My bad. Thanks.
