### ISSUE TITLE
Disable all leaf in shortend way

### ISSUE THREAD

**Issue by unusualious** [vakata/jstree#2593]
Hello Guys, I wanna set access for users in limited situations. Users but can only check leaf in JSTREE and in this way I tried multi ways but never get the correct results. I think this(Bellow Codes) way can solve this problem but I can't get good results yet. 

   ```
          if (!data.instance.is_leaf(data.node)) {
               console.log("for leafs :::: "+data);
                $("#jstree").jstree().disable_node(data.node);   
                }
```

**Comment by vakata** [comment]
The only shorthand way I can think of right now is to iterate through the internal node storage (_data.model) and check for nodes which are loaded, but their children array has a zero length. You can then set the disabled property directly in the node object and once done - redraw the tree. But this makes sense only in huge trees.
