### ISSUE TITLE
aria-selected is not updated when using parent checkbox to check/uncheck child elements

### ISSUE THREAD

**Issue by oibanez** [vakata/jstree#2596]
The **custom icon URL** option is unchecked by default.  

![image](https://user-images.githubusercontent.com/26256100/149386416-78093e49-c1df-4256-8fa6-e567781de228.png)

It's aria-selected is set to false as expected.

![image](https://user-images.githubusercontent.com/26256100/149386548-bb6b00c9-271a-4a9c-a32a-e3e120442eca.png)

When using the parent check box to set all child checkboxes as selected ....

![image](https://user-images.githubusercontent.com/26256100/149386654-332f29fb-190b-450b-9f86-22aee7cbf53b.png)

The aria-selected for **custom icon URL** does not update to true as expected.

![image](https://user-images.githubusercontent.com/26256100/149386811-57f1ab6a-93cf-4068-8020-bd35ef609e30.png)

Unchecking also does not update the value for selected checkboxes.

**Comment by mandie-malott** [comment]
Hello Ivan, just checking in to see if you've been able to take a look at the issue above. We use this component in one of our products at the company I work at and we aim to meet WCAG 2.0 AA so we're hoping this issue can be resolved. Thanks!

**Comment by vakata** [comment]
This seems fixed now - 3.3.13 will be out later today.
