### ISSUE TITLE
Confusing get_next_dom() and get_prev_dom()

### ISSUE THREAD

**Issue by shadoWalker89** [vakata/jstree#2597]
Hi,

If we have three nodes

A
B
C

What the documentation says and what it is more logical to me is that if we are On node "B" then the get_next_dom() should return node "C" and the get_prev_dom() should return the node "A"

From the docs

![image](https://user-images.githubusercontent.com/1449151/149512631-80113cd4-d0ca-474f-af0a-435083770250.png)

![image](https://user-images.githubusercontent.com/1449151/149512703-347555fa-6eb8-4817-89d0-773556c1bea1.png)

If I'm not mistaken, I think that these two methods are doing the inverse of what they should be doing.

If so I think that this should be fixed in the next major version because it's obviously a breaking change.

Thanks for the amazing project, this is truly amazing and is the best tree plugin I have ever used.

**Comment by vakata** [comment]
get_prev_dom uses previousSibling and get_next_dom uses nextSibling (with some fixes around closed nodes, first node in collection, etc)
