### ISSUE TITLE
Possibility to add a hidden option on contextmenu items

### ISSUE THREAD

**Issue by minedun6** [vakata/jstree#2600]
Hi,
is it possible to add a ```hidden``` option to the menu items of a context menu, based on boolean/closure ?
Eg: 

```js
{
  label: "Label 1",
  disabled: false,
  hidden: true,
  hidden: function (data) {
       return false;
  },
  separator_before: true,
  separator_after: false,
  action: function (data) {
      // do something
  }
```

**Comment by vakata** [comment]
No, this is not possible but the whole contextmenu option can be set to a function - in that case you can control which items are shown depending on which node was selected - that should be more than enough for what you need.
