### ISSUE TITLE
problem on cdjns url not found

### ISSUE THREAD

**Issue by dorel14** [vakata/jstree#2601]
Hello
i'am using jstree from cdjns and i see today i have an error message loading some css

https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.11/themes/default/style.css => 404 not found .

can you please make something to restore this file ? 

i don't call it from my ressource page , i think something in js is calling thsi url 

~~~
d=this.settings.core.themes.dir;d||(d=a.jstree.path+"/themes"),c=d+"/"+b+"/style.css"}c&&-1===a.inArray(c,g)&&(a("head").append('<link rel="stylesheet" href="'+c+'" type="text/css" 
~~~

**Comment by vakata** [comment]
Only minified files are included in CDNJS - try using style.min.js
