### ISSUE TITLE
changed.jstree not firing after deselect_all

### ISSUE THREAD

**Issue by samcov** [vakata/jstree#2613]
I have a node of the tree that gets selected, and everything if fine.

Then there is an operation where I want to reset the tree to none selected, and I perform a **deselect_all**, which works.

However, I can't select that specific node again unless I click on another node.

How can I make that node respond to the changed event again without having to select somewhere else?

**Comment by vakata** [comment]
The only reason for changed.jstree not firing would be if you invoke deselect_all(true) which explicitly skips the changed.event

**Comment by samcov** [comment]
And that's why they pay you the big bucks :)

At first I didn't think I did that, but you're exactly correct, that's what I did!

Thanks!!!
