### ISSUE TITLE
Context menu icons

### ISSUE THREAD

**Issue by sdusa-o** [vakata/jstree#2621]
When I use the default context menu, there are no icons for Cut, Copy, Delete and so on. There is space on the left side, but no icons. How do I add/enable those icons? Thanks.

![image](https://user-images.githubusercontent.com/91920407/165564664-9461049f-194a-48a2-8abd-49936d2fa94d.png)

**Comment by stla** [comment]
I don't know for the default context menu. If you use a custom context menu, you have to set the `icon` option, e.g.

```js
contextMenu = {
  items: function customMenu(node) {
    var tree = $("#mytree").jstree(true);
    var items = {
      rename: {
        label: "Rename",
        action: function (obj) {
          tree.edit(node);
        },
        icon: "glyphicon glyphicon-edit"
      },
      delete: {
        label: "Delete",
        action: function (obj) {
          tree.delete_node(node);
        },
        icon: "glyphicon glyphicon-trash"
      },
      create: {
        label: "Create",
        action: function (obj) {
          tree.create_node(node);
        },
        icon: "glyphicon glyphicon-plus"
      }
    };
    return items;
  }
};
```

**Comment by vakata** [comment]
Thank you @stla

**Comment by smahn9123** [comment]
How can I remove the empty space? 

It seems $.vakata.context.icons should be false. How can I do that from outside?

```
		$.vakata.context = {
			settings : {
				hide_onmouseleave	: 0,
				icons				: true
			},
```
