### ISSUE TITLE
Best approach for search 90,000 nodes, because  searches very slowly

### ISSUE THREAD

**Issue by mmtaheri** [vakata/jstree#2628]
Hi.
I have a tree with about 90,000 nodes. When I search for a value, for example, it finds more than 200 nodes. It takes about 5 seconds. If it finds 900 nodes, it takes 10 seconds.
Please advise how to reduce this time
best regard

**Comment by vakata** [comment]
90 thousand nodes is not a trivial amount. There will be a performance penalty with client side searches no matter what you do. You can however check your settings - make sure you are not using a custom search function, or if you are - that it is optimized, also make sure to turn off fuzzy searching, etc. I can not help more without seeing your config.
