### ISSUE TITLE
jsTree conflict with postgreSQL

### ISSUE THREAD

**Issue by enCoreV1** [vakata/jstree#2630]
Hello, i tried to make tree from database and php scripts. 
This is my code whitch works well on MySQL database without any errors
```
case 'create_node':
   $node = isset($_GET['id']) && $_GET['id'] !== '#' ? (int)$_GET['id'] : 0;
   $nodeText = isset($_GET['text']) && $_GET['text'] !== '' ? $_GET['text'] : '';
   $statement = $pdo->prepare("INSERT INTO categories(category, parent_id) VALUES(?,?)");
   $statement->execute(array($nodeText, $node));
   $result = array('id' => $pdo->lastInsertId());
   break;
...
echo json_encode($result);
```
And it's ok. Add new node and rename it. But if change database to PostgreSQL i'll take error
Code for PostgreSQL
```
case 'create_node':
   $node = isset($_GET['id']) && $_GET['id'] !== '#' ? (int)$_GET['id'] : 0;
   $nodeText = isset($_GET['text']) && $_GET['text'] !== '' ? $_GET['text'] : '';
   $sql = "INSERT INTO categories (id, category, parent_id) VALUES (DEFAULT, :name, :parent_id) RETURNING id";  //returning id <->lastinsertid from MySQL 
   $stmt = $pdo->prepare($sql);
   $stmt->bindParam(':name', $nodeText, PDO::PARAM_STR);
   $stmt->bindParam(':parent_id', $node, PDO::PARAM_INT);
   $stmt->execute();
   $id = $stmt->fetchColumn(); //PostgreSQL serial (auto_increment) fix
   $result = array('id' => $id);
break;
...
echo json_encode($result);
```
$result will be the same: {id: "51"} (51 for example)

but JS give me error. jsTree last version.
```
jstree.js:3683 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at $.jstree.plugins.types.set_id (jstree.js:3683:12)
    at Object.<anonymous> (vvst.js:41:31)
    at fire (jquery-3.5.1.min.js:3500:31)
    at Object.fireWith [as resolveWith] (jquery-3.5.1.min.js:3630:7)
    at done (jquery-3.5.1.min.js:9796:14)
    at XMLHttpRequest.<anonymous> (jquery-3.5.1.min.js:10057:9)
```
So new node added but i need to refresh my page for rename it.
Thx for helping

**Comment by aadrian** [comment]
@enCoreV1 post here the two JSONs (from MySQL and from Postgres) since they're not the same.

**Comment by enCoreV1** [comment]
![1](https://user-images.githubusercontent.com/5033431/171470677-dbff883e-9381-4929-8c6b-4965042fca3c.png)
![3](https://user-images.githubusercontent.com/5033431/171474421-2d156cd9-cd93-4b85-905e-8b0c4219a052.png)

Only one idea - MySQL id in JSON as string with quotation marks and PostgreSQL  JSON as integer. So, how return right JSON format from PGSQL? Or i make another mistake? Thx in advance

**Comment by enCoreV1** [comment]
> @enCoreV1 post here the two JSONs (from MySQL and from Postgres) since they're not the same.
![1](https://user-images.githubusercontent.com/5033431/171490439-5cd87314-ac73-41d3-8152-3867ca338e69.png)

![3](https://user-images.githubusercontent.com/5033431/171490453-a838d617-553c-4b25-b059-9776b05ff282.png)

Only one idea - MySQL id in JSON as string with quotation marks and PostgreSQL JSON as integer. So, how return right JSON format from PGSQL? Or i make another mistake? Thx in advance

**Comment by vakata** [comment]
I am not sure there is something I can do - please provide the data in the format that is expected, jstree does not talk to a database directly. From looking at the error it seems like the node is never created - the ID is still the autogenerated j1_1. Usually the biggest difference when migrating to postgresql is types and the way the underlying library interprets them - have a look at that as well. I can assure you I have tens of projects using jstree and postgreSQL.
