### ISSUE TITLE
The cross in the default theme has two colors

### ISSUE THREAD

**Issue by stla** [vakata/jstree#2631]
Hello,

Is it normal that the cross in the [default theme](https://github.com/vakata/jstree/blob/master/dist/themes/default/32px.png) has two colors like this:

![jstree_default_32x](https://user-images.githubusercontent.com/4466543/170949469-c3471512-3daa-4b97-ac02-e24b3370e036.png)

I find its rendering is strange with these two colors.

**Comment by vakata** [comment]
This is the theme I have chosen, you are free to create your own themes, and/or modify the graphics used by using CSS overrides. Design is highly subjective.
