### ISSUE TITLE
Default context menu in Mozilla firefox on right click when the Shift key is pressed down

### ISSUE THREAD

**Issue by sagittaracc** [vakata/jstree#2632]
Hello!
Thanks for the great lib, I've been using it for a long time.
Now I have a problem with showing context menu in Firefox (v101.0).
It shows the default menu when shift pressed down
You can easily reproduce it here - https://www.jstree.com/plugins/

**Comment by vakata** [comment]
I believe this is a browser limitation - if you know of a fix - please let me know or create a PR.
