### ISSUE TITLE
Safari themes {stripes:true,... bug

### ISSUE THREAD

**Issue by jplevene** [vakata/jstree#2635]
![Mac issue](https://user-images.githubusercontent.com/1764110/175986573-97aad5f0-f3b4-4671-a6a4-3b56e978e290.png)

On Safari when stripes are set as true, trees with many nodes, the stripes go out of alignment to the nodes (see attached image).  Fine on Chrome on a Mac.

**Comment by vakata** [comment]
Hi Justin,

This must be something on your end (I see you have a lot of custom elements). I can't seem to reproduce the issue:
https://jsfiddle.net/yuvx6orw/

Let me know if you can reproduce without the custom elements?
