### ISSUE TITLE
Is it possible to make jstree component desing look modern?

### ISSUE THREAD

**Issue by sagittaracc** [vakata/jstree#2637]
Hello!
Here's design I want to apply to my jstree component - https://ibb.co/cNvP30m
Is it possible to make a remove button right float of the node to remove this node?

**Comment by vakata** [comment]
You can create your own theme, or simply override the CSS rules. As for the button - this should give you a starting point: https://github.com/vakata/jstree/blob/master/src/misc.js#L148
