### ISSUE TITLE
Got an error while pre-loading selected items (set selected: true)

### ISSUE THREAD

**Issue by xxytuni** [vakata/jstree#2639]
![jstreeError](https://user-images.githubusercontent.com/109549088/179583334-c1d2e53b-d811-4fd1-bea0-06b0ddef38d0.PNG)

attached is the error form the console log.
Everything looks fine, but the tree cannot be refreshed (tree showing Loading... )
 
If set the selected: false, the error is gone.

**Comment by vakata** [comment]
This is most likely due to an error with your data - duplicated IDs, or missing IDs - etc. Also check your own code on line 93 ;)
