### ISSUE TITLE
Changing the height of nodes (css) causes the context menu and the toggle function to behave incorrectly

### ISSUE THREAD

**Issue by sbirkh** [vakata/jstree#2641]
I wrote a Wordpress Plugin to organize Menus and Pages using jsTree and it works very fine. But adjusting the hight of the nodes (which is no problem and works fine as well), the ContextMenu appears on a wrong place and the toggle-function doesn't work (symbol changes, but nodes don't open).

Anyone have any ideas?

Thanks

**Comment by vakata** [comment]
Can you provide a demo of the issue?

**Comment by vakata** [comment]
Will reopen on more information.
