### ISSUE TITLE
Ctrl+Shift+Click support

### ISSUE THREAD

**Issue by kirensiva** [vakata/jstree#2645]
Hi,

Is it possible to make a selection using **Ctrl+Shift+Click**? Usecase is given below.

Have a look at the attached screenshot. I created this selection by clicking on the folder `1`, then `Shift+Click` on `4`. Then `Ctrl+Click` on `6` and `Ctrl+Shift+Click` on `9`. This is the behavior in `Windows OS`.
If it is not supported yet could you please guide which plugin should I customize?
![q1](https://user-images.githubusercontent.com/4952561/185379522-d8fb92f5-0fe7-4aa5-b14f-d0ade6c35405.png)

**Comment by vakata** [comment]
This is not yet supported, to add this one would have to do it in the core.
