### ISSUE TITLE
Firing a vanilla Javascript event from a jQuery listener 

### ISSUE THREAD

**Issue by tacman** [vakata/jstree#2649]
I'm trying to have my non-jQuery class respond to a apitree:select event, by sending the data via a vanilla javascript CustomEvent.

The code works when I fire the event from outside the jQuery listener, but not from within.  What am I doing wrong?

```javascript
import jQuery from 'jquery';
import 'jstree';

export default class  {

    setup() {
        $element = $('#tree').jstree(); 
        this._dispatchEvent('apitree:connect', { msg: "This works fine" });
        this.addListeners($element);
    }

    addListeners($element) {

        this._dispatchEvent('apitree:connect', {msg: 'Adding jquery listeners'}); //  listener gets this
        $element
            .on('changed.jstree', (e, data) => { // triggered when selection changes, can be multiple, data is tree data, not node data
                this._dispatchEvent('apitree:changed', {msg: "changed", e, data}); // calls method, but listener doesn't get it.
            })
     }

    _dispatchEvent(name, payload) {
      
        let ev = new CustomEvent(name, { detail: payload });
       console.log('Dispatching event ' + name + " " + payload.msg);
        window.dispatchEvent(ev);
        // hacks
        // this.element.dispatchEvent(ev);
        // document.dispatchEvent(ev);
    }
}
```

And my listener:
```javascript
   connect() {
        window.addEventListener('apitree:connect', this._onSelect);
        window.addEventListener('apitree:select', this._onSelect);
   }

    _onSelect(event) {
        console.error('received! ' + event.type, event.detail.msg);
    }
```

I've been hacking away at this, I know it's more jQuery than jstree.  But it's a good time to ask about the status of 0.4, too.

**Comment by tacman** [comment]
I'm going to close this until I have a better example.

**Comment by tacman** [comment]
For reasons that completely befuddle me, dispatching an event with a colon inside jQuery listener doesn't work.  

So my example above is accurate.  I've changed my code to dispatch apitree_changed, and my listener now receives it.

I love jstree, and I used to love jQuery, but now I can't wait until 0.4 is out without the jQuery dependency.  

@vakata , any idea why dispatching an event with a colon would be different inside of a jQuery listener?  And is there any way you can dispatch a javascript event instead of or in addition to the jQuery event in the current version?  I recognize that dropping jQuery in 0.4 is a big task, but perhaps there are ways to tweak the current code so that jQuery is completely internal to the library, and not required when using it.

**Comment by vakata** [comment]
jQuery is dropped in 4.0, but it still has no plugins - I am working on reenabling them. As for v.3 - sorry, I am afraid I will not be adding vanilla JS events - I will focus my limited time on v.4
