### ISSUE TITLE
Break line if node text exceeds container width

### ISSUE THREAD

**Issue by aleksvujic** [vakata/jstree#2650]
We have a very simple page layout. Left column (`col-4`) displays jsTree and right column (`col-8`) displays relevant data about the selected node. We noticed that jsTree doesn't break node name if it exceeds the column width. This is the code that we have ([online demo](https://codepen.io/aleksvujic/pen/JjvGEOw?editors=1010)):

```html
<div class="container">
  <div class="row">
    <div class="col-4 border border-success">
      <div id="jstree_demo_div"></div>
    </div>
    <div class="col-8 border border-danger">
      <p>Hello world</p>
    </div>
  </div>
</div>
```

```js
$(document).ready(function() {
  $('#jstree_demo_div').jstree({
    'core': {
      'data': [
        'Simple root node with a very long name which will overflow to the right container'
      ]
    }
  });
});
```

This is how it looks like:
![image](https://user-images.githubusercontent.com/17112542/189051554-2d2cbc90-c917-44a6-a1f1-47116ac35a68.png)

How can we break node text in multiple lines if it exceeds the column width?

**Comment by vakata** [comment]
Multi-line nodes have never been supported - sorry. You can place a <br> manually and it will probably work, but drag'n'drop and possibly other plugins will suffer.
