### ISSUE TITLE
Shift+click on intermediate level with checkbox behaviour

### ISSUE THREAD

**Issue by ulfblundberg** [vakata/jstree#2656]
I'm using a checkbox-tree  with > 2 levels. When I try to select a sequence of intermediate levels using 'Click' (1. below) followed by 'Shift+Click' (2. below), the first selection is cancelled and I have to make another 'Shift-Click' (3. below) on the initial node to get the nodes in-between to be selected. Is this really how it should work ?
How can avoid the third 'Click' ?
1.
![Screenshot 2022-09-27 at 14 09 59](https://user-images.githubusercontent.com/114489196/192523050-edcec62f-12cd-4b97-a831-bf713af0ac41.png)

2.
![Screenshot 2022-09-27 at 14 10 13](https://user-images.githubusercontent.com/114489196/192523078-32d07092-26f0-47c4-b6aa-2e71b7bf0e7b.png)

3.
![Screenshot 2022-09-27 at 14 10 23](https://user-images.githubusercontent.com/114489196/192523100-b0ad0bdb-ccdb-4b3b-a090-f8e4cc589edd.png)

**Comment by vakata** [comment]
Seems to work properly now (don't know which change fixed it). Try 3.3.13 which will be out later today.
