### ISSUE TITLE
Retina icon images

### ISSUE THREAD

**Issue by brendon** [vakata/jstree#2657]
Hi @vakata, I know it's probably a long shot but I wondered if the original design file for the default icons in `jstree` was more than @1x? If so, would it be possible to get a @2x or greater export of this to use? Now that I think of it, it'll probably require some rework of the coordinates in the CSS. Happy to work on a PR if I can get a higher resolution sprite map :)

**Comment by vakata** [comment]
The project is quite old, so it was created with 1x only. The v.4 branch uses SVG which should be fine on retina. You are more than welcome to submit a PR for v.3. I will not have the resource to do this, as I will focus most of my time on v.4 now.

**Comment by brendon** [comment]
No worries @vakata, if the original's weren't vector then that's all good. :) Thank you for your great work as always! :)
