### ISSUE TITLE
Syntax error/typo in delete_node-Method in V3.3.12

### ISSUE THREAD

**Issue by SKPFCW** [vakata/jstree#2665]
HI!

within the delete_node-Method there is a typo in **triger** -> **trigger**:

Instead of
``
this.get_node(this._model.data[$.jstree.root].children[0], true).children('.jstree-anchor').triger('focus');
``

it should be
``
this.get_node(this._model.data[$.jstree.root].children[0], true).children('.jstree-anchor').trigger('focus');
``

Beside this, eslint marks quite a few errors in your code.

![image](https://user-images.githubusercontent.com/63354164/198280791-a7e571ec-648d-4983-a1b3-0a2624fc447c.png)

**Comment by vakata** [comment]
This will be fixed in 3.3.13 later today (it is already fixed, but there has not been a version released)
