### ISSUE TITLE
jstree.js: typo on line 4033

### ISSUE THREAD

**Issue by ShyLionTjmn** [vakata/jstree#2678]
there is call to `triger` function instead of `trigger`

**Comment by vakata** [comment]
Can you provide a link to the file please - I can not seem to find this? I will reopen on more info.

**Comment by ShyLionTjmn** [comment]
huh... it is fixed now... might have been fixed just rights after i downloaded this lib

**Comment by ShyLionTjmn** [comment]
Now i get it.
At my project server, i've downloaded Release file https://github.com/vakata/jstree/zipball/3.3.12
Which dates to Sep 2021
There is above mentioned typo.
This link is on the jstree.com homepage.
