### ISSUE TITLE
jstree inside jquery-ui dialog - no drop position markers is shown

### ISSUE THREAD

**Issue by ShyLionTjmn** [vakata/jstree#2680]
When using jstree inside dialog, with dnd plugin - no drop position triangles appear.
Might be z-index issue?

**Comment by ShyLionTjmn** [comment]
Fixed with:
```
#jstree-marker {
  z-index: 10000000;
```

**Comment by vakata** [comment]
Sorry, this is something you need to fix manually as per your needs.
