### ISSUE TITLE
Confirm moving a node

### ISSUE THREAD

**Issue by Herz3h** [vakata/jstree#2690]
I'm trying to use 

```javascript
"check_callback": async function (operation, node, node_parent, node_position, more)
{
    if(operation !== 'move_node')
    {
        return false;
    }

   
    if(more && more.core && !confirm('Are you sure ?'))
    {
        return false;
    }

    return true;
},
```

But even if I decline the confirmation dialog, the node still gets moved, what is the proper way to do this ?

**Comment by vakata** [comment]
The function can not be async. Let me know if this fixes the issue.

**Comment by Herz3h** [comment]
Without async it indeed works properly. However I'd like to use sweetalert2 which returns a promise (hence the async), is there a workaround for it to work with async ?
