### ISSUE TITLE
select_node / activate_node no loger trigged when clicking on a selected node

### ISSUE THREAD

**Issue by Paradoxnode** [vakata/jstree#2691]
Starting from version 3.3.13 if a selected node gets selected neither `select_node` or `activate_node` event gets triggered.

I suspect that this issue is caused by commit [e6e6d9ad998e15e8291697e44238e3a389a12c8b](https://github.com/vakata/jstree/commit/e6e6d9ad998e15e8291697e44238e3a389a12c8b)

**Comment by Paradoxnode** [comment]
I do agree that `selected_node` shouldn't trigger if an user selects an already selected node. However `activate_node` event should trigger. As it says in the docs "[triggered when an node is clicked or intercated with by the user](https://www.jstree.com/api/#/?q=activate_node&f=activate_node.jstree)".

I have have a scenario where i need to track if a user clicks on a node (selected or not) and up to version 3.3.12 it was working fine.

**Comment by vakata** [comment]
activate_node is still triggered: https://jsfiddle.net/pf2L9anu/
