### ISSUE TITLE
Screen reader accessibility

### ISSUE THREAD

**Issue by Sereza7** [vakata/jstree#2696]
Hello!
When using a screen reader, navigation through a tree is not possible. When going up or down a node, the screen reader will only eventually read something.
I think this might be caused by the absence of tabindex changes in the trees. 

This issue can be tested on the demo https://www.jstree.com/demo/ .
Tested with screen readers such as Orca (Linux) , Jaws and NVDA (Windows).

Some great sources for screen-reader accessibility in hierarchy trees: 
http://accessibleculture.org/articles/2013/02/not-so-simple-aria-tree-views-and-screen-readers/
https://www.w3.org/WAI/ARIA/apg/patterns/treeview/

**Comment by vakata** [comment]
Thank you for the report - it is however a duplicate #2498 - I will focus on v.4 now, so accessibility in v3 will remain as is, as all bug reports and feature requests were a mix of contradicting opinions and PRs.

**Comment by Sereza7** [comment]
Behaviour with NVDA going through the tree:
*   Create  button  
✏   Rename  button  
 Delete  button  
Search  edit  has auto complete  blank
tree view
Root 2  not selected  2 of 2  level 1
level 3  One more  not selected  1 of 1
tree view
level 2  Child 2  not selected  collapsed  2 of 2
tree view
Child 1  not selected  1 of 2  level 2
tree view
level 1  Root 1  not selected  collapsed  1 of 2
tree view

____
When navigating with arrows, the first text, with the content, never has time to be narrated, and in the end, the user can only hear "tree view" when navigating.

**Comment by Sereza7** [comment]
Video example with NDVA on windows 10 (with the focusHighlight NVDA extension)

https://user-images.githubusercontent.com/28761965/218076021-b28709cf-d469-4d65-bf52-0108841ea2a7.mp4
