### ISSUE TITLE
Jstree 3.3.14 requires jquery 3.6 and higher

### ISSUE THREAD

**Issue by arunragha89** [vakata/jstree#2702]
Is there a reason why jquery 3.6  is required for this version of 3.3.14. We are on jquery version 3.5.1 due to some issues with 3.6 and we are not able to upgrade to 3.3.14

**Comment by vakata** [comment]
The requirement was added in Jul 22 when updating dependencies. There is no reason to use 3.6 and up specifically - 3.5 should be fine too - I just picked an old enough version to replace the obsolete 1.9. I will drop it to 3.5.
