### ISSUE TITLE
Control where the edit input is added on the dom

### ISSUE THREAD

**Issue by minedun6** [vakata/jstree#2704]
Is it possible to add some sort of hook/callback, just like the node_customize plugin to control where the edit input gets added on the DOM ?

I have customized the base node html and now the input breaks the html that I made.

Anything I can change, any event I can hook into ?

Thank you !

**Comment by vakata** [comment]
Sorry, I can not work on this - it is too big of a change - v.3 is small features and fixes only. You can try to add your own plugin - maybe override the .edit() method. There are examples on how to override methods in src/misc.js
