### ISSUE TITLE
css style from style.min.css without full path not working

### ISSUE THREAD

**Issue by NathanApb** [vakata/jstree#2716]
i just upgraded the jstree from 3.1.0 to 3.3.15 because some inconsistencies that sometime the tree did not load properly and now i have a now problem, now the arrow form the folders did not load, with a litle bit of investigation i discover that is due the change in the style.min.css path to the images:

from:
background-image: url("/Scripts/jstree/themes/default/32px.png")

working:
![image](https://user-images.githubusercontent.com/129546641/229203144-d20fcc91-802c-4929-9848-5db1fa99bff9.png)

to:
background-image: url("32px.png")

not working:
![image](https://user-images.githubusercontent.com/129546641/229203738-6149b1e3-139f-4f68-8715-c0ac3f43fca1.png)

reverting just this lines bring back the icons with no problem

**Comment by vakata** [comment]
This was likely something you or your team fixed manually (probably moved a file or two). The paths in the CSS were always relative to the file itself.
