### ISSUE TITLE
vakata-dnd and contextmenu elements not accounting for body scroll

### ISSUE THREAD

**Issue by josplice** [vakata/jstree#2737]
Firstly, great software. Really enjoy using it.
My issue is small and I am sure easy to fix, but I create this question due to lack of understanding from me.

<img width="1320" alt="Screenshot 2023-08-08 at 08 08 38" src="https://github.com/vakata/jstree/assets/61649720/0162bf33-04fd-48ba-b33c-a8d6961cd6f0">

<br />

<img width="1329" alt="Screenshot 2023-08-08 at 08 26 49" src="https://github.com/vakata/jstree/assets/61649720/423da5df-7679-4a15-a85b-850ee5c13d91">

When I scroll on the main body, the contextmenu and vakata-dnd elements are out of place by the exact scroll amount. Like I said, I am sure I just missed something in the documentation, but it would be great if you could send me in the right direction for a fix.

The doc viewer is in an iframe, but the records tree is injected into a div.

How do I get jstree to use the scroll amount to set the offsetTop of the elements.

Appreciate it.

**Comment by josplice** [comment]
Just remove position: relative on the body.

**Comment by vakata** [comment]
Sorry I could not help sooner - I gather you found your fix? Let me know if I should reopen.
