### ISSUE TITLE
 Wrap text of <a> (jstree-anchor) into <span> #1930 

### ISSUE THREAD

**Issue by rajnikantdas84** [vakata/jstree#2741]
Hi @vakata and team,

I know this is an old and closed issue, but I am not able to get the solution for this. So looking for the help.

<a class="jstree-anchor" href="#"> <i class="jstree-icon jstree-themeicon" role="presentation"></i> Another node </a>

It would be helpful im many ways (styling, text truncation with ellipsis etc.) to place this text inside a span/i/whatever. For example adding a span with the class jstree-label around "Another node":

<a class="jstree-anchor"> <i class="jstree-icon jstree-themeicon" role="presentation"></i> <span class="jstree-label">Another node</span> </a>

old issue ref: https://github.com/vakata/jstree/issues/1930

**Comment by vakata** [comment]
The anchor has a specific semantic meaning. Still - all of jstree's internal operations DO NOT rely on the anchor tag, so you could theoretically swap it for a SPAN. You can achieve that by overriding _create_prototype_node in a plugin - copy and paste the function in a plugin and load that plugin (there are plenty of examples in src/misc.js).
