### ISSUE TITLE
Nombre d'entités limitées à 10

### ISSUE THREAD

**Issue by cotegeo** [vakata/jstree#2745]
Bonjour,

Je rencontre ce problème. Il semble que lorsqu'on on essaye d'insérer plus de 10 noeuds à la suite, les suivants (11e et +) ne sont pas proposés au déroulement.

![Capture d’écran du 2023-09-17 19-30-54](https://github.com/vakata/jstree/assets/143707295/bf9cda74-71b6-4972-b1f2-757e3a5284fb)

Y a t il un moyen de modifier ce nombre ? Y a t il un nombre limite de lignes pour le fichier JSON ?

Merci pour vos retours

**Comment by cotegeo** [comment]
Cela vient de ma requête de production du fichier JSON. Cela ne vient pas du module.

**Comment by vakata** [comment]
I do not speak French - please use English.

There is no limitation on the number of nodes you can have, provided of course that their IDs are unique.
