### ISSUE TITLE
Inline Style Conflict with CSP

### ISSUE THREAD

**Issue by RealWorldDevelopers** [vakata/jstree#2750]
When using a Content Security Policy without the keyword unsafe-inline in the style-src, some styles are being blocked.

To reproduce:
1. Create a Tree with nested nodes.
2. Rename a child node.
3. Collapse the highest parent.

Using the browser's Dev Tools window under the console tab, you will see the CSP blocks an inline style attempt.

This was last reproducible with version 3.3.14

**Comment by vakata** [comment]
As far as I remember - the only thing that conflicts with CSP inline is the animation, which you can toggle off in your config: core : { 'animation' : 0, ...

**Comment by RealWorldDevelopers** [comment]
Actually anytime you attribute a tag with style like  `<div style="display:none">Foo</div>` it is considered inline style and will be blocked by the browser engine.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src

https://content-security-policy.com/examples/allow-inline-style/

Looking through the source code, it seems most formatting is done via CSS, but there are a few places where style is used to hide or display items.  This is a common practice, yet it does not play well when using strict CSP rules.

Creating a class like `jstree-hide` and `jstree-show` then adding / removing class instead of setting style easily fixes the issue.

**Comment by shjulberg** [comment]
I'm running into this as well.  Is there any intention of fixing this?   Example of what my console looks like with a tree I have, as well as the effect in the app:

![image](https://github.com/vakata/jstree/assets/17277228/a17ecd15-71cf-47cf-8eb2-b3d2117c705e)

![image](https://github.com/vakata/jstree/assets/17277228/6b4087c6-a54f-4194-98ec-3ea4fafe4b59)
