### ISSUE TITLE
move node fails if children are all typed to same?

### ISSUE THREAD

**Issue by kpetrow** [vakata/jstree#2762]
Weird instance and don't have time to really make a full ticket sorry.
But line 9220 errors in some odd cases, add check if child exists and seems to resolve

 inst.move_node([nodeBeingMOvedWithChildren], 'newParentID');

fails here

![image](https://github.com/vakata/jstree/assets/18248938/d9562516-5ec5-4a8b-af75-d982976a7303)

promise to come back and make demo, but busy now

**Comment by vakata** [comment]
Let me know if you find a way for me to reproduce the issue.
