### ISSUE TITLE
possible security issues, feedback needed

### ISSUE THREAD

**Issue by DanielRuf** [vakata/jstree#2763]
Our customer uses checkmarx SAST checks and we get the following results.

Can you check these and provide feedback?

![image](https://github.com/vakata/jstree/assets/827205/1e3fe4c7-2d37-47a7-8f5c-d285f3ef331c)

**Comment by rajniszp** [comment]
Some more information, details, example of XSS?

**Comment by DanielRuf** [comment]
Unfortunately I can not check that in detail anymore. So I'll close this issue.
