### ISSUE TITLE
How to Display File icon for Files

### ISSUE THREAD

**Issue by vasuvandla** [vakata/jstree#2781]
Dear jsTree Team,

I'm trying to display file icon for file under folders in jsTree. I'm unable to get sample code . Kindly help at the earliest .

Thanks in advance,
Sreenivasulu

**Comment by peternoges** [comment]
Hello @vasuvandla Sreenivasulu, 
I am a jstree user too.  Have you tried the “types” plugin? Jstree 3 documentation should have example using types to influence icon. Thanks for the info.

**Comment by vakata** [comment]
There are multiple demos of the types plugin as suggested by @peternoges  (thank you) and you can also use the icon property and set individual icons using your datasource.
