### ISSUE TITLE
bug in jstree 3.3.13 and above when reclicking on node to show info box

### ISSUE THREAD

**Issue by abdurrhmansaeed** [vakata/jstree#2786]
I found this solution for node info box 
https://codepen.io/Vsevporyadin/pen/XwrOjK
you can click on any node and the box will show and you can close it

it works ok to jstree v 3.3.12

in v 3.3.13 and above if you click on a node then close the box then click again the box will not show
I debugged the code until I found the issues it was in jstree v.3.3.13 and above

Here is the code modified working on 3.3.12
https://jsfiddle.net/d305gsmo/
![3-3-12](https://github.com/vakata/jstree/assets/90107817/21cc404a-55c8-4960-bbe3-d2a89a5b3502)

Here is the code modified Not working on 3.3.16
https://jsfiddle.net/d305gsmo/1/
![3-3-16](https://github.com/vakata/jstree/assets/90107817/ddde6407-06fe-4bd1-b3ca-7aff1e058fb0)

**Comment by vakata** [comment]
Thank you @gkralik
