### ISSUE TITLE
Status of JsTree

### ISSUE THREAD

**Issue by sdraper69** [vakata/jstree#2787]
Hi, just wondering what the status of this project is?

The biggest gripe I have is performance ([see here](https://github.com/vakata/jstree/issues/2505) and as well as selectNode performance issues), other than that, its pretty good. But its getting to a stage where I think I will need to replace it.

Obviously, with it being open source, I am always grateful for the effort and work put in. So this is not a criticism, but if its not really being actively worked on, it would be useful to know so I can evaluate my options.

Thanks!

**Comment by vakata** [comment]
Thank you for the kind words - I fully understand where you are coming from. To be honest - I am only replying to this now as I finally found the time to start working on jstree again. But I have no ETA for v.4 - it is somewhat usable now and the main concepts will not change, but it lacks a lot of the default plugins.
