### ISSUE TITLE
DND between trees check_callback more.is_multi is wrong

### ISSUE THREAD

**Issue by kpetrow** [vakata/jstree#2795]
When dragging between trees the is_multi key is wrongly set to true even if single item is being dragged across

Fiddle:

https://jsfiddle.net/w7qor1j9/3/

**Comment by vakata** [comment]
I believe there is some confusion regarding the meaning of this switch. ```is_multi``` is set to ```true``` when the items are not from the same tree, and to ```false``` if the dragged items are from the same tree. It is supposed to mean "is the drag multitree?"

**Comment by kpetrow** [comment]
Is there any way to tell in the callback if more than one item is being dragged? @vakata
