### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by crmatthews** [vakata/jstree#286]
I am using the latest (v1.0.0 2012-10-01) version of jstree, and I have entered the following code:

$("#pcr")
  // call `.jstree` with the options object
  .jstree({
    "types" : {
      "max_depth" : -2,
      "max_children" : -2,
      "valid_children" : [ "root" ],
      "types": {
        "root" : {
          "icon" : {
            "image" : "js/jstree/themes/default/_drive.png"
          },
          "valid_children" : [ "position", "position-abolished", "position-filled", "position-vacant" ]
        },
        "position" : {
          "icon" : {
            "image" : "js/jstree/themes/default/_drive.png"
          },
          "valid_children" : [ "person-in-position", "person-left-position" ]
        },
        "position-abolished" : {
          "icon" : {
            "image" : "js/jstree/themes/default/_drive.png"
          },
          "valid_children" : [ "person-in-position", "person-left-position" ]
        },
        "position-filled" : {
          "icon" : {
            "image" : "js/jstree/themes/default/_drive.png"
          },
          "valid_children" : [ "person-in-position", "person-left-position" ]
        },
        "position-vacant" : {
          "icon" : {
            "image" : "js/jstree/themes/default/_drive.png"
          },
          "valid_children" : [ "person-in-position", "person-left-position" ]
        },
        "person-in-position" : {
          "icon" : {
            "image" : "js/jstree/themes/default/_drive.png" }
          },
        "person-left-position" : {
          "icon" : {
            "image" : "js/jstree/themes/default/_drive.png"
          }
        }
      }
    },
    // the `plugins` array allows you to configure the active plugins on this instance
    "plugins" : ["themes","html_data","ui","crrm","hotkeys","types","contextmenu"],
    // each plugin you have included can have its own config object
    "core" : { "initially_open" : [ "root" ] },
    // it makes sense to configure a plugin only if overriding the defaults
    "ui" : {
      "initially_select" : [ "node1" ]
    },
    "core" : {
      "initially_open" : [ "root" ]
    }
  })

Everything works correctly (and thank you very much for a wonderful control) except for the icon changing. All the icons are the "default" icon in the d.png file (the one that looks like a yellow file folder).

What am I not doing correctly?

**Comment by deskstar127** [comment]
Hello Vakata
I am going to add some custom html out of anchor in node.  Custom html could be input box and an icon. but I need to add these html to only leaf.
and then I am going to bind some event handler to these element. 

Could you help me regarding this problem? 

Thanks. 
DeskStar
