### ISSUE TITLE
Types plugin doesn't suport open/closed icon 

### ISSUE THREAD

**Issue by HelbertFernandes** [vakata/jstree#386]
If you do this changes it will be fixed:
file jquery.jstree.js line 3820:
////////////////////////////////////////////////
if( tp.icon.image || tp.icon.position) {
    if(i == "default")  { icons_css += '.jstree-' + _this.get_index() + ' a > .jstree-icon { '; }
    else                { icons_css += '.jstree-' + _this.get_index() + ' li[' + attr + '="' + i + '"] > a > .jstree-icon { '; }
    if(tp.icon.image)   { icons_css += ' background-image:url(' + tp.icon.image + '); '; }
    icons_css += 'background-position:0 0; } \n';

```
if(tp.icon.position){
    if(i == "default")  { icons_css += '.jstree-' + _this.get_index() + ' > .jstree-open > a > .jstree-icon { '; }
    else                { icons_css += '.jstree-' + _this.get_index() + ' li.jstree-open[' + attr + '="' + i + '"] > a > .jstree-icon { '; }
    icons_css += ' background-position:' + tp.icon.position + '; } \n';
}
```

}
////////////////////////////////////////////////

Now to config it is simple:
"types" : {
    "drive" : {
        "icon" : {
            "image" : "./folder.png",
            "position" : "0 -18px" /_position of the image open_/
            /_the position of the image closed is every "0 0"_/
        },

**Comment by rajeshmythry** [comment]
asdaas

**Comment by kushal555** [comment]
Hey can someone please provide me solution, 
How to set the open and close icon for the directory?
