### ISSUE TITLE
jsTree 3.0.0 ajax success data manipulation

### ISSUE THREAD

**Issue by jupe** [vakata/jstree#424]
I'm trying to use this new jsTree 3.0.0 little like before, but ajax functionality is little different than earlier.

"core" : {
    'data' : {
      'url' : function (node) {
        return '/myurl.json';
      },
      'data' : function (node) {
        return { 'id' : node.id };
      },
      //this not working anymore ->
      'success': function(data, status, res, parent) {
            //I need to convert data a little more in front-end before jstree... ->
            return convertServerData(data, parent);
      }  
   }
}

**Comment by Zander-moody30** [comment]
Here’s a quick solution https://jquerys.space/questions/managing-various-responses-within-an-ajax-success-callback
