### ISSUE TITLE
[3.0.0-beta] Renaming doesn't work

### ISSUE THREAD

**Issue by dirkluijk** [vakata/jstree#429]
Hi,

I try to rename a node, but it keeps returning `false`. I think this is probably a bug in the new 3.0.0 beta-version.

I am using the latest built. My (simplified) code:

```
$('#tree')
                .jstree({
                    'core' : {
                        'data' : {
                            'url': 'some/url/to.json',
                            'data' : function (node) {
                                return { 'id' : node.id };
                            },
                            'type': 'post'
                        }
                    }
                })
                .on("select_node.jstree", function (e, data) {
                    $('#tree')
                            .jstree("rename_node", data.node, 'Foo');
                });
```

On selecting a node, nothing happens. The `select_node.jstree` event is being triggered though (tested with alert). I also tested whether the `rename_node.jstree`event is fired, but it is not. 

Thanks.

**Comment by jozef** [comment]
Thanks @vakata !
I was also fasing the same problem. Would be helpfull to write a short note to API documentation of rename_node() - http://www.jstree.com/api/#/?q=rename_&f=rename_node%28obj,%20val%29 about it if possible.
