### ISSUE TITLE
Changing ID of New Node Breaks Editing?

### ISSUE THREAD

**Issue by naufers** [vakata/jstree#459]
Hi, I am having an issue as follows, using ASP.NET MVC 4 with jsTree:
1) create new node in existing tree using create_tree
2) in the triggered event, use an AJAX call to get an appropriate ID for the database
3) in the AJAX "success" callback, set the new node with the new ID
4) call tree.edit on the node

This appears to break, manifesting in, depending on when I set the ID, either not going into the rename_node event, or being able to rename, but the node being renamed to an empty string (and thus disappearing from the UI).

This appears to be a side effect of resetting the object's ID, as if I don't set it to the new value, everything works appropriately.

**Comment by Seebiscuit** [comment]
Ahh, marvelous post.
