### ISSUE TITLE
dnd plugin - onDragComplete?

### ISSUE THREAD

**Issue by joshuataylor** [vakata/jstree#462]
Hi,

I love this plugin!

Is it possible with the dnd plugin to have it so when it has finished it I can see the data? Similar to change.jstree, open_node.jstree, close_node.jstree?

$('#jstree').on('changed.jstree open_node.jstree close_node.jstree', function (e, data) {
console.log(data);
});

**Comment by sanjeevpande** [comment]
Is there a way to get the changed data after drop. Data here I am referring is the json object which was initially passed to render the tree. Do I have to construct this data or is it available ?

**Comment by ShyLionTjmn** [comment]
Please, consider implementing such event on jstree node.
Using "move_node.jstree" isn't right one, when you need to update database - this event fires too often, while node being dragged around, no one would update DB during that.
