### ISSUE TITLE
Set "type" node by json data

### ISSUE THREAD

**Issue by ZioTano** [vakata/jstree#473]
Hi, I set up my Jstree to get data from a db via ajax.

$('#jstree').jstree({
    "plugins" : [
    "contextmenu", "dnd", "search",
    "state", "types", "wholerow"
     ],
   "core" : {
    "animation" : 0,

```
'data' : {

  'url' : function (node) {
    return node.id === '#' ?
      'get_tree1.php' : 'get_tree2.php';
  },
  'data' : function (node) {

    return { 'id' : node.id };
  }
}
```

  },

```
"types" : {"types" : {
  "default" : {
    "icon" : "glyphicon glyphicon-flash"
  },
  "g" : {
    "icon" : "http://jstree.com/tree.png"
  }
}
}
```

});

I get back this json and all work correctly:

[{"id":"g-3","parent":"#","text":"Gruppo Immobiliare 3"},{"id":"g-1","parent":"#","text":"Scuola Media Statale Dante Alighieri","children":true},{"id":"g-2","parent":"#","text":"Universita Di Catania"}]

Now i tryed to " supply a 'type' property with the node's data." like manual tell.

[{"id":"g-3","parent":"#","text":"Gruppo Immobiliare 3","type":"g"},{"id":"g-1","parent":"#","text":"Scuola Media Statale Dante Alighieri","type":"g","children":true},{"id":"g-2","parent":"#","text":"Universita Di Catania","type":"g"}]

No changes.

so i tryied inside li_attr:

[{"id":"g-3","parent":"#","text":"Gruppo Immobiliare 3","li_attr":{"type":"g"}},{"id":"g-1","parent":"#","text":"Scuola Media Statale Dante Alighieri","li_attr":{"type":"g"},"children":true},{"id":"g-2","parent":"#","text":"Universita Di Catania","li_attr":{"type":"g"}}]

Still default folder icon.

I tryied in many ways but ALWAYS see default icon.
where i have to insert type in json object?
can you help me to understand where I wrong?

Thank you a lot

**Comment by sokolukasz** [comment]
I also have this problem, in functin is_draggable - my code:

JSON:
`[{"id":"m101","text":"Blog","icon":"menu","type":"menu","children":true,"li_attr":{"id":"m101","title"
:"Blog"}},{"id":"m13","text":"Menu - test","icon":"menu","type":"menu","children":true,"li_attr":{"id"
:"m13","title":"Menu - test"}},{"id":"m5","text":"Menu g\u0142\u00f3wne","icon":"menu","type":"menu"
,"children":true,"li_attr":{"id":"m5","title":"Menu g\u0142\u00f3wne"}},{"id":"public","text":"Katalogi
 ukryte - publiczne","icon":"public","type":"public","children":true,"li_attr":{"id":"public","title"
:"Katalogi ukryte - publiczne"}},{"id":"not_public","text":"Katalogi nie opublikowane","icon":"not_public"
,"type":"not_public","children":false,"li_attr":{"id":"not_public","title":"Katalogi nie opublikowane"
}}]`

JS:
`.jstree({
					plugins: ['dnd', 'types', 'state'],
					core : {
						animation:0,
						strings:{
							loading:ILANG.loading_tree_struct
						},
						themes:{
							url:defaults.css,
							responsive : true
						},
						html_titles:true,
						data:{
							type:'post',
							url : defaults.ajax.getData,
							data: function (node) {
								return {
									id : node.id
								};
							}
						},
						check_callback : true,
					},
					dnd : {
						is_draggable : function(node) {
							
							dump(node[0].type);
							
							if ($.inArray(node[0].type, ['dir', 'todir', 'home', 'url']) != '-1') 
								return true;
							return false;
						}
					},
//					crrm:{ 
//						move:{
//							check_move:function(m){
//								if(!$.Imperial.options.hasAdminFullCatalogPrivileges || m.o.attr('rel') == 'menu' || m.o.attr('rel') == 'public' || m.o.attr('rel') == 'not_public')
//								{
//									return false;
//								}
//								return true;
//							}
//						}
//					},
					types:{
						valid_children: ['menu', 'public', 'not_public'],
						types:{
							menu:{
								max_depth :5
							},
							one_level_dir:{
								max_depth :1
							},
							public:{
								max_depth :5
							},
							not_public:{
								max_depth :5
							},
							dir_disabled:{
								max_depth :5
							},
							dir:{
								max_depth :5
							},
							todir:{
								max_depth :0,
								valid_children:[]
							},
							home:{
								max_depth :0,
								valid_children:[]
							},
							url:{
								max_depth :0,
								valid_children:[]
							}
						}
					}
				});`

In dump(node[0].type); i always have "default" type.

**Comment by sokolukasz** [comment]
![bez nazwy-2](https://cloud.githubusercontent.com/assets/3176131/18175806/228fc5bc-7073-11e6-8d92-070a6bcac070.png)

Watch this image, in orginal i send type menu and in function of file jstree.types.js model.jstree is still "default".

`.on('model.jstree', $.proxy(function (e, data) {
						var m = this._model.data,
							dpc = data.nodes,
							t = this.settings.types,
							i, j, c = 'default', k;
						dump(m);`

**Comment by sokolukasz** [comment]
Dear Mr Vakata, could you check this issue, please :)

**Comment by dmcclellan** [comment]
I've been using jstree for many years with the types plugin, I switched to a lazy load and struggled as well.  What I found to work  for me was to put the config data for "core.data" after the config for types.
