### ISSUE TITLE
create_node() problem with the new api

### ISSUE THREAD

**Issue by 7amou3** [vakata/jstree#499]
hello 
I have post a question on stackoverflow (http://stackoverflow.com/questions/21367140/create-dynamic-node-with-jstree-methode), but it seems no body know the solution.
I want to create a new node dynamically and append it to the tree but the create_node() method doesn't seem to be working
here is my code

//after ajax call ...
success : function(resp){
var parentid = resp.parentid;
$('#folderTree').jstree().create_node(parentid , 'new node' );
}

but nothing happened, when i log the results to the console i get 'false'

ps : the docummentation is missing some pieces (there is no 'par' parameter in the method create_node() ) 
see here : http://www.jstree.com/api/#/?q=(&f=create_node([obj, node, pos, callback, is_loaded])

Please help

**Comment by kaysersoze** [comment]
@lee-da - Although I'm necromancing this issue thread, I just wanted to thank you for saving me literally hours of pointless debugging. Thanks!

Perhaps this should throw an error in this case, or at least this particular combination should be noted in the documentation.

**Comment by vakata** [comment]
It is in the docs - the large yellow block: https://www.jstree.com/docs/interaction/

Anyway, the reason I decided to chime in is that the error idea will be implemented in the next major version.

Best regards,
Ivan

**Comment by sabirovruslan** [comment]
Hi!
Please tell me if the problem is solved?
I also can not add a node dynamically after ajax

**Comment by vakata** [comment]
There was no problem in the first place - just a config option you need to use.

**Comment by vakata** [comment]
You can get the children IDs using ```node.children``` - if you need the full nodes use ```get_node(child_id)```

**Comment by sabirovruslan** [comment]
Ok! Thank you! Already done )
