### ISSUE TITLE
Scroll jstree to show selected node

### ISSUE THREAD

**Issue by fernandojsg** [vakata/jstree#519]
I have a big jstree with vertical scrollbar. I select each node by code while clicking on some buttons on my interface, and I would like to know if there's a way to scroll to the selected node automatically. 
I mean, if the selected node using `select_node` is not visible due to the overflow, just scroll down or up to put it visible

**Comment by farooq7124** [comment]
Hi, I am trying to add scroll functionality to my jstree as it is very larg but not scrolling. Please see by below search function. Help me

$('#plugins4_q').keyup(function () {
    if(to) { clearTimeout(to); }
    to = setTimeout(function () {
      var v = $('#plugins4_q').val();
      $('#jstree-proton-3').jstree(true).search(v);
      var jstree = document.getElementById('jstree-proton-3');
		jstree.scrollTop = findPos( document.getElementById( uid ) ) - jstree.offsetHeight/2;
    }, 250);
    
  });

**Comment by vakata** [comment]
My guess is that it is not working because `uid` is not set.

**Comment by farooq7124** [comment]
How to achive this please help me on this.

**Comment by vakata** [comment]
Sorry, but I can't help you - it is not a programming problem - I have no idea which node you are trying to scroll to. If it is the first search result, you should listen for the `search.jstree` event and in that event - focus the first `.jstree-search` node:

```js
$('#plugins4_q').keyup(function () {
    if(to) { clearTimeout(to); }
    to = setTimeout(function () {
        var v = $('#plugins4_q').val();
        $('#jstree-proton-3').jstree(true).search(v);
    }, 250);
});
$('#jstree-proton-3').on('search.jstree', function (e, data) {
    if(data.nodes.length) {
        var jstree = document.getElementById('jstree-proton-3');
        jstree.scrollTop = findPos( data.nodes[0] ) - jstree.offsetHeight/2;
    }
})
```

Best regards,
Ivan
