### ISSUE TITLE
Initially_open and initially_select

### ISSUE THREAD

**Issue by KilroggD** [vakata/jstree#531]
Hello. I'm currently using jstree v3.0.0 with ajax loading of the html data. It works perfectrly, but I need some nodes to be pre-opened and pre-selected. Is there any way to do this with ajax loading? adding initially_open:["id1","id2","id3"] didn't help at all. Nodes are not opened and not selected. 

Thank you in advance

**Comment by xingguo3** [comment]
> data.instance.set_state

What if I want to unselected note in this way, Can I do that? 
e.g.
data.instance.set_state({ core : { opened : [full array of nodes here to open and load from the server], 'unselected' : [array of nodes to select] } })

Plz kindly advise
