### ISSUE TITLE
Ajax search plugin

### ISSUE THREAD

**Issue by KilroggD** [vakata/jstree#537]
Hello. Sorry for so many questions. Are there any examples for using "search" plugin with ajax tree? I need to search all over the tree, loading and expanding nodes, that match search request and whole branches, related to those nodes. Something like this http://zakupki.gov.ru/pgz/public/action/products/list/search?action=Reset&excludeFirst=true&callback=selectProductCallback&ignoreLevel=true&targetService=&searchQuery=
Can I do it with search plugin or I should better write my own function to find all id's to be opened and iteract with tree by set_state?

**Comment by rasoulabbasi20n** [comment]
Hi, I'm using jstree and I want to know (in search ajax) why in some cases (search term cases) it wont bold and expand the nodes after searching. And I checked the HTTP respond and it was filled with proper data. My node's texts are in Persian, is there any problem with text encoding?
All these aside, what a great plugin! Well done :+1:
