### ISSUE TITLE
Chrome scaling problem jstree 3.0.0

### ISSUE THREAD

**Issue by Skuratovsky** [vakata/jstree#552]
Hi, vakata! Thank you for your awesome plugin.

It seems there is a problem with scaling jstree (version 3.0.0-beta8 from official site) in Google Chrome (Version 32.0.1700.107) (current last version)

Scaling 100% - ok.

Scaling 110%:
![screenshot 2014-02-19 12 58 12](https://f.cloud.github.com/assets/2150496/2204819/05f90cf4-9945-11e3-8133-9da28ff4ea13.png)

Some problem with backgrounds offsets (wholerow plugin).
In Firefox there is no such problem.

Could you fix it?

**Comment by russplaysguitar** [comment]
FYI I also encountered this issue, but I think it is caused by a different Chrome bug which I've since reported: https://bugs.chromium.org/p/chromium/issues/detail?id=826420
