### ISSUE TITLE
Create & Rename triggered for creation

### ISSUE THREAD

**Issue by Glideh** [vakata/jstree#570]
With the `contextmenu` plugin, if I start the creation of a node, the `create_node` event is triggered before I give it a name, then `rename_node` gets triggered when I validate.

Wouldn't it be more logical to trigger only `create_node` once I give it a name ?

**Comment by EdgeHeman** [comment]
I was facing the same issue as you have described. I have prevent the rename_code by checking the id of the node as below. Hope this is helpful to you.
`.on('rename_node.jstree', function (e, obj) {
                    if (obj.node.id > 0) 
                   { 
                        renameNode(obj.node) //function to make ajax call to db to rename the node
                    }
                });`
