### ISSUE TITLE
Jstree.destroy() is not completly destroying the tree?

### ISSUE THREAD

**Issue by praveenlobo7** [vakata/jstree#572]

**Comment by Zlatov** [comment]
Let me talk with the code:
```
var panel = $('panel')
var struct = panel.children('#one_tree')
struct.jstree({core:{data: ... }, ...})
```
Now the user does not want a tree:
```
struct.jstree(true).destroy()
panel.empty()
panel.append(another_html)
```
Then user want tree (append struct...)...

**Jstree.destroy() is not completly destroying the tree** =(

Browser appetizingly eats RAM. How destroy jstree instance correctly?

**Comment by MGenidy** [comment]
i have two tab its logic working on jstree first tab logic must work on jstree without plugins:[checkbox]
and second tab logic must work on jstree with plugins:[checkbox]
i destroyed the tree and rebuild it again with success of what plugins needed but all event not work else first time
