### ISSUE TITLE
huge problem populating the jstree from json

### ISSUE THREAD

**Issue by ionutale** [vakata/jstree#574]
the documentation is poor, and cand understand how to do it.

can you provide an easy way to do it ?
like one function with 2 parameters ( file name, the tree to populate )

thanks allot

**Comment by woldsnewmedia** [comment]
I agree, the documentation is very very bad, and I have spent a day and got no where!

**Comment by s0rin** [comment]
I disagree, the jstree documentation isn't poor or bad.
As well everyone who opens issues will get a prompt and helpful answer.
