### ISSUE TITLE
Context menu not on top

### ISSUE THREAD

**Issue by erussell3** [vakata/jstree#593]
Hi,
I'm implementing the latest beta in an Asp.net MVC3 application. The problem I'm having is the popup context menu is hidden behind the tree. Not sure what is going on here. Is there a particular order of things to ensure that the popup appears in front (on top)?
Thanks in advance,
erussell3

![image](https://f.cloud.github.com/assets/6893156/2365971/4d9b1618-a6e9-11e3-935f-7f6883261ad9.png)

**Comment by frumbert** [comment]
Is it possible to introduce a setting into `$.jstree.defaults.contextmenu` or similar for a known z-index value, rather than having to hack it in styles? That way it could be computed before jstree initialises.

**Comment by vakata** [comment]
Personally, I'd refer to setting a z-index value from a script as "hacking" - setting a CSS property from a stylesheet seems normal to me. As I said so many times before - I will not participate in a z-index war - it is your responsibility as a developer to take care of the stacking of your own page. 

If you need to use javascript for that - fine - just use `$('.vakata-context').css('z-index', calculate_something());`

Sorry, I will not introduce numerous config options for simple one-liners (that should not be needed in the first place).

Best regards,
Ivan
