### ISSUE TITLE
Unable to set id's to json nodes

### ISSUE THREAD

**Issue by srini933** [vakata/jstree#606]
Hi,

I have been setting node id's from json. But when I retrieve the selected node IDs I am getting the jstree default values.

How can I get my own id's ??
Any help is appreciated.

//getting selected ids o button click
$("#getbutton").click(function() {
        var checked_ids = []; 
    checked_ids = $('#jstree').jstree('get_selected'); //for only node ids
    //checked_ids = $('#jstree').jstree('get_selected',true); //for complete node obj
    console.log(checked_ids);
});

//ouput is like, j1_2, j1_1 (not the ids I have given)

//My json
{
    "text": "root",
    "id": 123,
    "children": [
        {
            "text": "folder1",
            "id": 127,
            "children": [
                {
                    "text": "file",
                    "id": 456
                }
            ]
        }
    ]
}

//create JSTREE code
$('#jstree').jstree({'core':{'data': jsonData },
  "checkbox" : {
      "keep_selected_style" : false
    },
"plugins" : [ "checkbox", "json_data", "types", "themes", "ui" ]
 });
});

//Srini

**Comment by jonomynard** [comment]
Hi, I am getting this exact problem, but I am using the latest version from github (release 3.2.1 and also tried master).  I also tried converting the id to a string creating the node, but I still get j1_1 when later retrieving the node id.

Thanks,
Jonathan
