### ISSUE TITLE
Multiple selection doesn't turn off

### ISSUE THREAD

**Issue by hafezd** [vakata/jstree#622]
Hi, I have the following configuration:

<pre>
ftree = $('#file-tree');
ftree.jstree({
    "core": {
        "data": {
            "url": 'driveaccess.php?action=tree',
            "data": function (node) {
                return { 'id': node.id};
            },
            "dataType": 'json'
        },
        "themes": {"dots": false},
        "multiple": false,
        "check_callback": true
    }
});
</pre>

Even though I have <code>multiple</code> set to false, when I call <code>ftree.jstree('select_node', id);</code> for each node they all select instead of toggling the selected one off when another is selected. I tried <code>ftree.jstree('deselect_all ', true);</code> but it doesn't deselect anything!

I have the same problem with create_node which it doesn't work even though I have <code>check_callback</code> set to true!

<pre>
ftree.jstree('create_node', '#', {id:"newId", text:"new node"}, "last", false, false);
</pre>

**Comment by c-f** [comment]
You say, the `select_node` is low-level and recommend using `activate_node` instead. But in the API description `activate_node` is marked as private and internal, while `select_node` is public. This seems to be an inconsistency. 

So which is a recommended API method for changing selection programmatically?
