### ISSUE TITLE
a_attr not working

### ISSUE THREAD

**Issue by HadiBasiri** [vakata/jstree#625]
Hi.
why a_attr or li_attr not working .my json is like this:
{
"id":"acc_387fa8e7-49d5-4323-b960-8ac6e401b1ee",
"text":sample",
"type":"file",
"li_attr":null,
"a_attr":"'href ': 'http://www.google.com'",
"children":false
}

jstree v3

**Comment by vladimir-shmidt** [comment]
Hi,
Can you write this on site http://www.jstree.com/docs/json/  please
