### ISSUE TITLE
Search Crashes Chrome Tab on Large Trees

### ISSUE THREAD

**Issue by tebriel** [vakata/jstree#656]
I've got a tree of about 4,750 nodes and about 3,500 of them contain the string 'pdb'. If I search for a string that is less common (say 20-50 nodes) everything is fine, but searching for 'pdb' which has such a huge result set crashes chrome.

While digging through this part of the search function appears to take longer and longer each time:

``` javascript
for(i = 0, j = r.length; i < j; i++) {
    f = this.get_node(r[i], true);
    if(f) {
        this._data.search.dom = this._data.search.dom.add(f);
    }
}
```

Is this because you're holding both DOM trees in memory (or even in the DOM)?
Maybe for large trees building the dom could be a one-sweep operation, or you could add a hidden class to `<li>` so there aren't multiple trees existing at once?

I'm trying to grab some test data, will update this issue with a gist when I have it in a few.

**Comment by Abhi-joshi** [comment]
I'm trying with your changes in jstree.js file for fast search but no luck in that.. i think it is not compulsory to include jstree.search.js file right??

**Comment by vakata** [comment]
Read the docs about using jstree. You have to include the JS file found in the `dist` directory (`jstree.min.js`). The separate files in the `src` directory are for development only.

Best regards,
Ivan

**Comment by Abhi-joshi** [comment]
Still no luck... I am taking timeout to 2000 in search plugin as per the doc.

**Comment by vakata** [comment]
Let me clarify a bit - what do you mean by "trying the changes" - those were made an year ago and are part of the official build. There is no universal solution for fast search - if a result set is large - it will take time to be processed, especially if `show_only_matches` is set to true. 
You have not specified your problem, nor shown your config, so I can not help you in any way, I even have no idea what the 2000 timeout is. Please use the discussion group if you have any how-to questions, but if you do - provide a demo of the problem, or at least your config / sample data and related event handlers:
https://groups.google.com/forum/#!forum/jstree

Best regards,
Ivan

**Comment by Abhi-joshi** [comment]
Okay i posted my sample data on the forum..Let me know if there is any work around

**Comment by vakata** [comment]
Unfortunately, all you did was post a dump of raw data that is of absolutely no use to anyone trying to help. Please, let us continue the discussion in the discussion group: 
https://groups.google.com/forum/#!topic/jstree/_bt-rHGFwp8
