### ISSUE TITLE
Is it possible to disable a plugin when the tree is loaded?

### ISSUE THREAD

**Issue by rexdf** [vakata/jstree#666]
Two modes, one without checkbox, one with checkbox.  Is it possible to just load all node without reloading and rebuilding the tree? I want to do it just by click a button.

**Comment by xaionaro** [comment]
I want to disable "sort" plugin after load. Is that possible?

**Comment by NeiserDeveloper** [comment]
@xaionaro did you manage to disable the sort property? I also want to do the same thing with the plugin checkbox the property three_state when I set it to false and when it ends I want to change to true or maybe clicking on a button, I'm like crazy looking but I still can not do it, help please.
