### ISSUE TITLE
Search Plugin: Allow to open found subnodes

### ISSUE THREAD

**Issue by murphy83** [vakata/jstree#668]
It would be nice to have a configuration item of the search plugin to allow the user to select a subset of nodes (using show_only_matches: true) - but if these elements are not leafs, to display the children of them.
I currently have a tree with about 4k of entries, so users really enjoy having a search function, but in many cases they only now a "rough location" which may contain more detailed entries.
I don't want to go into technical details, but you may think of it as a tree of continents, countries, regions, cities, borouhgs and streets.  Now the user searches for a certain cityname and gets multiple results, but needs to select a street as the goal of the use case ... but the subtrees remain closed - only upon resetting the search they become visible.

I am going to work on the issue a bit for myself but I would love to see it included in JSTree soon.

**Comment by gl3n** [comment]
Hi Ivan,

I encounter the same problem : the "search" action "frozens" the tree. Expanding visibles (i.e. matching) nodes displays nothing, even if children match the search query.

I tried your 2 pieces of code but it display every nodes.

The only way I found for the moment is to call "search" action on every "load_node" events. It works great but it's a bad hack in my opinion because it browses every nodes each time. It would be cleaner/faster to search only on new nodes in this case.

Thanks for you help

**Comment by vakata** [comment]
Hi,

If children match the query they must be shown - can you provide a demo where the children match the search string but are not shown?

I will debug the above sample plugin further and let you know if I broke something in the latest releases.

Best regards,
Ivan

**Comment by gl3n** [comment]
Nodes are loaded with AJAX in my case. When I expand a visible node, children are properly inserted below this node, but they have a ``display:none`` style property on them, even if they match the search query. By the way, the search action (and my specific callback) is not called.

**Comment by vakata** [comment]
Please share your code - there must be something wrong with your config. Also keep in mind for lazy loaded trees you should use the search.ajax option to enable server side searches.

Best regards,
Ivan

**Comment by gl3n** [comment]
AJAX isn't appropriate in my case, I use the search plugin to apply a filter on tree nodes.

Here is my usage of the jstree : I added a ``type`` property (string) on each node object. The ``type`` is used for filtering and it also defines which URL to call for AJAX expanding and which URL to redirect to when selecting a node.

A simple example of my usage could be a tree with **user groups** on first level and **users** on the second level. Each user node has 2 fixed nodes : *"Professional contacts"* and *"Personal contacts"*. Expanding *"Professional contacts"* loads some contacts of the user, expanding *"Personal contacts"* loads other contacts of the user. On the top of the tree, two buttons allows to filter the tree : "Show only personal contacts" and "Show only professional contacts". It works great when all nodes are opened/loaded, but if I call ``search`` action and then expand a node (loads new nodes), all children nodes are hidden, even if they are matching.

```
.
├── Developers
│   ├── Steve
│   ├── John
│   │   ├── Professional contacts
│   │   │   ├── Hector Forest
│   │   │   └── Marlowe Dalton
│   │   └── Personal contacts
│   │       └── Wallis Jaxon
├── Managers
```

Here is my configuration code :

```js
options.search = {
    show_only_matches: true,
    search_callback: function(node) {
        return treeFilterer.isNodeMatching(node);
    }
}
```

And in the **treeFilterer** service :

```js
isNodeMatching: function(node) {
    for (var key in filters) {
        if (node.original.type === filters[key]) {
            return false;
        }
    }

    return true;
},
```

**Comment by vakata** [comment]
Sorry, but that is not what I meant. I simply mean that if your function marks the node as a match, then the node will be visible, no matter how deep it is in the structure. Here is a demo:
http://jsfiddle.net/DGAF4/268/

Also keep in mind your demo is a bit strange - the search callback accepts two arguments, and the first one is the search string, not the node.
Anyway have a look at the demo - even the closed unrendered node is shown automatically.

**Comment by vakata** [comment]
And here is one more demo, which has nested matches (the one you describe) as well as nested non-matching nodes, and the `show_only_matches` option is set to `true` (as in your code): 
http://jsfiddle.net/DGAF4/269/

You can clearly see the nested matches are revealed too.

**Comment by gl3n** [comment]
You're right about my *strange* demo : I removed some arguments to avoid mistakes !

I completely agree with your examples, it works.

The difference with my problem is that in your examples **all nodes are loaded** when you call "search" action. The search plugin works great on loaded nodes, but if you use AJAX loading, new nodes are loaded and added to the tree. The problem is : these new nodes are systematically hidden.

**Comment by vakata** [comment]
That is why the search plugin provides a way (using AJAX - the `search.ajax` option) to query the server about which nodes need to be loaded to reveal all possible search results. I do not see how you can use AJAX loading but you are somehow unable to use the search AJAX feature to load all needed nodes.
There is no way for jstree to know that some nodes will be a match if those nodes are not loaded. 
Once again - I am sorry if I misunderstood something, but to me it is simple - jstree can only search in loaded nodes (the opposite is like wanting your OS to search for a file on a flash drive that you have not yet plugged in). 
There is no way for jstree to match a node it does not even know exists. It is up to you to load all needed nodes before jstree can perform the search (hence the `search.ajax` config option). 
Did you try it? Do you need some demos? Please, share if you have any other ideas.

**Comment by vakata** [comment]
I can only think of allowing `search.ajax` to allow for a function accepting a search string and a callback, so that you have full manual control over how you fetch the list of nodes to be loaded. Would that work for you? Aside from that I am out of ideas, so please bare with me and explain in detail what you need, if `search.ajax` will not work and a callback will not work.

**Comment by gl3n** [comment]
I understand what you say. Indeed, I thought that search could act as a live search (such as jQuery live events) while the search is performed only when requested.

The ideal for me would be to have a live search that is executed on each node expanding, a search that would be active on existing and upcoming nodes.

Do you know what I mean ?

**Comment by vakata** [comment]
Thank you, and sorry it took me so long to grasp the concept. Yes, currently the search plugin is different, but I believe what you need can be added quickly with a few lines. 
I will get back to you and let you know.
Best regards,
Ivan

**Comment by gl3n** [comment]
Thank you Ivan !

**Comment by vakata** [comment]
Hi again,
I have a plugin almost ready, the reason it is not commited is that it might break current search functionality, as it has one extra parameter. I will work some more on making it backwards compatible.
```js
/**
 * ### Search plugin
 *
 * Adds search functionality to jsTree.
 */
/*globals jQuery, define, exports, require, document */
(function (factory) {
	"use strict";
	if (typeof define === 'function' && define.amd) {
		define('jstree.search', ['jquery','jstree'], factory);
	}
	else if(typeof exports === 'object') {
		factory(require('jquery'), require('jstree'));
	}
	else {
		factory(jQuery, jQuery.jstree);
	}
}(function ($, jstree, undefined) {
	"use strict";

	if($.jstree.plugins.search) { return; }

	/**
	 * stores all defaults for the search plugin
	 * @name $.jstree.defaults.search
	 * @plugin search
	 */
	$.jstree.defaults.search = {
		/**
		 * a jQuery-like AJAX config, which jstree uses if a server should be queried for results. 
		 * 
		 * A `str` (which is the search string) parameter will be added with the request. The expected result is a JSON array with nodes that need to be opened so that matching nodes will be revealed.
		 * Leave this setting as `false` to not query the server. You can also set this to a function, which will be invoked in the instance's scope and receive 2 parameters - an object (containing the search string - `str` and the optional node ID to limit the search to - `inside`) and the callback to call with the array of nodes to load.
		 * @name $.jstree.defaults.search.ajax
		 * @plugin search
		 */
		ajax : false,
		/**
		 * Indicates if the search should be fuzzy or not (should `chnd3` match `child node 3`). Default is `false`.
		 * @name $.jstree.defaults.search.fuzzy
		 * @plugin search
		 */
		fuzzy : false,
		/**
		 * Indicates if the search should be case sensitive. Default is `false`.
		 * @name $.jstree.defaults.search.case_sensitive
		 * @plugin search
		 */
		case_sensitive : false,
		/**
		 * Indicates if the tree should be filtered (by default) to show only matching nodes (keep in mind this can be a heavy on large trees in old browsers). 
		 * This setting can be changed at runtime when calling the search method. Default is `false`.
		 * @name $.jstree.defaults.search.show_only_matches
		 * @plugin search
		 */
		show_only_matches : false,
		/**
		 * Indicates if all nodes opened to reveal the search result, should be closed when the search is cleared or a new search is performed. Default is `true`.
		 * @name $.jstree.defaults.search.close_opened_onclear
		 * @plugin search
		 */
		close_opened_onclear : true,
		/**
		 * Indicates if only leaf nodes should be included in search results. Default is `false`.
		 * @name $.jstree.defaults.search.search_leaves_only
		 * @plugin search
		 */
		search_leaves_only : false,
		/**
		 * If set to a function it wil be called in the instance's scope with two arguments - search string and node (where node will be every node in the structure, so use with caution).
		 * If the function returns a truthy value the node will be considered a match (it might not be displayed if search_only_leaves is set to true and the node is not a leaf). Default is `false`.
		 * @name $.jstree.defaults.search.search_callback
		 * @plugin search
		 */
		search_callback : false
	};

	$.jstree.plugins.search = function (options, parent) {
		this.bind = function () {
			parent.bind.call(this);

			this._data.search.str = "";
			this._data.search.dom = $();
			this._data.search.res = [];
			this._data.search.opn = [];
			this._data.search.som = false;

			this.element
				.on('before_open.jstree', $.proxy(function (e, data) {
						var i, j, f, r = this._data.search.res, s = [], o = $();
						if(r && r.length) {
							this._data.search.dom = $(this.element[0].querySelectorAll('#' + $.map(r, function (v) { return "0123456789".indexOf(v[0]) !== -1 ? '\\3' + v[0] + ' ' + v.substr(1).replace($.jstree.idregex,'\\$&') : v.replace($.jstree.idregex,'\\$&'); }).join(', #')));
							this._data.search.dom.children(".jstree-anchor").addClass('jstree-search');
							if(this._data.search.som && this._data.search.res.length) {
								for(i = 0, j = r.length; i < j; i++) {
									s = s.concat(this.get_node(r[i]).parents);
								}
								s = $.vakata.array_remove_item($.vakata.array_unique(s),'#');
								o = s.length ? $(this.element[0].querySelectorAll('#' + $.map(s, function (v) { return "0123456789".indexOf(v[0]) !== -1 ? '\\3' + v[0] + ' ' + v.substr(1).replace($.jstree.idregex,'\\$&') : v.replace($.jstree.idregex,'\\$&'); }).join(', #'))) : $();

								this.element.find(".jstree-node").hide().filter('.jstree-last').filter(function() { return this.nextSibling; }).removeClass('jstree-last');
								o = o.add(this._data.search.dom);
								o.parentsUntil(".jstree").addBack().show()
									.filter(".jstree-children").each(function () { $(this).children(".jstree-node:visible").eq(-1).addClass("jstree-last"); });
							}
						}
					}, this))
				.on("search.jstree", $.proxy(function (e, data) {
						if(this._data.search.som) {
							if(data.nodes.length) {
								this.element.find(".jstree-node").hide().filter('.jstree-last').filter(function() { return this.nextSibling; }).removeClass('jstree-last');
								data.nodes.parentsUntil(".jstree").addBack().show()
									.filter(".jstree-children").each(function () { $(this).children(".jstree-node:visible").eq(-1).addClass("jstree-last"); });
							}
						}
					}, this))
				.on("clear_search.jstree", $.proxy(function (e, data) {
						if(this._data.search.som && data.nodes.length) {
							this.element.find(".jstree-node").css("display","").filter('.jstree-last').filter(function() { return this.nextSibling; }).removeClass('jstree-last');
						}
					}, this));
		};
		/**
		 * used to search the tree nodes for a given string
		 * @name search(str [, skip_async])
		 * @param {String} str the search string
		 * @param {Boolean} skip_async if set to true server will not be queried even if configured
		 * @param {Boolean} show_only_matches if set to true only matching nodes will be shown (keep in mind this can be very slow on large trees or old browsers)
		 * @param {mixed} inside an optional node to whose children to limit the search
		 * @param {Boolean} append if set to true the results of this search are appended to the previous search
		 * @plugin search
		 * @trigger search.jstree
		 */
		this.search = function (str, skip_async, show_only_matches, inside, append) {
			if(str === false || $.trim(str.toString()) === "") {
				return this.clear_search();
			}
			inside = this.get_node(inside);
			inside = inside && inside.id ? inside.id : null;
			str = str.toString();
			var s = this.settings.search,
				a = s.ajax ? s.ajax : false,
				m = this._model.data,
				f = null,
				r = [],
				p = [], i, j;
			if(this._data.search.res.length && !append) {
				this.clear_search();
			}
			if(show_only_matches === undefined) {
				show_only_matches = s.show_only_matches;
			}
			if(!skip_async && a !== false) {
				if($.isFunction(a)) {
					return a.call(this, { 'str' : str, 'inside' : inside }, $.proxy(function (d) {
							if(d && d.d) { d = d.d; }
							this._load_nodes(!$.isArray(d) ? [] : $.vakata.array_unique(d), function () {
								this.search(str, true, show_only_matches, inside, append);
							}, true);
						}, this));
				}
				else {
					a = $.extend({}, a);
					if(!a.data) { a.data = {}; }
					a.data.str = str;
					if(inside) {
						a.data.inside = inside;
					}
					return $.ajax(a)
						.fail($.proxy(function () {
							this._data.core.last_error = { 'error' : 'ajax', 'plugin' : 'search', 'id' : 'search_01', 'reason' : 'Could not load search parents', 'data' : JSON.stringify(a) };
							this.settings.core.error.call(this, this._data.core.last_error);
						}, this))
						.done($.proxy(function (d) {
							if(d && d.d) { d = d.d; }
							this._load_nodes(!$.isArray(d) ? [] : $.vakata.array_unique(d), function () {
								this.search(str, true, show_only_matches, inside, append);
							}, true);
						}, this));
				}
			}
			if(!append) {
				this._data.search.str = str;
				this._data.search.dom = $();
				this._data.search.res = [];
				this._data.search.opn = [];
				this._data.search.som = show_only_matches;
			}

			f = new $.vakata.search(str, true, { caseSensitive : s.case_sensitive, fuzzy : s.fuzzy });
			$.each(m[inside ? inside : '#'].children_d, function (ii, i) {
				var v = m[i];
				if(v.text && ( (s.search_callback && s.search_callback.call(this, str, v)) || (!s.search_callback && f.search(v.text).isMatch) ) && (!s.search_leaves_only || (v.state.loaded && v.children.length === 0)) ) {
					r.push(i);
					p = p.concat(v.parents);
				}
			});
			if(r.length) {
				p = $.vakata.array_unique(p);
				this._search_open(p);
				if(!append) {
					this._data.search.dom = $(this.element[0].querySelectorAll('#' + $.map(r, function (v) { return "0123456789".indexOf(v[0]) !== -1 ? '\\3' + v[0] + ' ' + v.substr(1).replace($.jstree.idregex,'\\$&') : v.replace($.jstree.idregex,'\\$&'); }).join(', #')));
					this._data.search.res = r;
				}
				else {
					this._data.search.dom = this._data.search.dom.add($(this.element[0].querySelectorAll('#' + $.map(r, function (v) { return "0123456789".indexOf(v[0]) !== -1 ? '\\3' + v[0] + ' ' + v.substr(1).replace($.jstree.idregex,'\\$&') : v.replace($.jstree.idregex,'\\$&'); }).join(', #'))));
					this._data.search.res = $.vakata.array_unique(this._data.search.res.concat(r));
				}
				this._data.search.dom.children(".jstree-anchor").addClass('jstree-search');
			}
			/**
			 * triggered after search is complete
			 * @event
			 * @name search.jstree
			 * @param {jQuery} nodes a jQuery collection of matching nodes
			 * @param {String} str the search string
			 * @param {Array} res a collection of objects represeing the matching nodes
			 * @plugin search
			 */
			this.trigger('search', { nodes : this._data.search.dom, str : str, res : this._data.search.res, show_only_matches : show_only_matches });
		};
		/**
		 * used to clear the last search (removes classes and shows all nodes if filtering is on)
		 * @name clear_search()
		 * @plugin search
		 * @trigger clear_search.jstree
		 */
		this.clear_search = function () {
			this._data.search.dom.children(".jstree-anchor").removeClass("jstree-search");
			if(this.settings.search.close_opened_onclear) {
				this.close_node(this._data.search.opn, 0);
			}
			/**
			 * triggered after search is complete
			 * @event
			 * @name clear_search.jstree
			 * @param {jQuery} nodes a jQuery collection of matching nodes (the result from the last search)
			 * @param {String} str the search string (the last search string)
			 * @param {Array} res a collection of objects represeing the matching nodes (the result from the last search)
			 * @plugin search
			 */
			this.trigger('clear_search', { 'nodes' : this._data.search.dom, str : this._data.search.str, res : this._data.search.res });
			this._data.search.str = "";
			this._data.search.res = [];
			this._data.search.opn = [];
			this._data.search.dom = $();
		};
		/**
		 * opens nodes that need to be opened to reveal the search results. Used only internally.
		 * @private
		 * @name _search_open(d)
		 * @param {Array} d an array of node IDs
		 * @plugin search
		 */
		this._search_open = function (d) {
			var t = this;
			$.each(d.concat([]), function (i, v) {
				if(v === "#") { return true; }
				try { v = $('#' + v.replace($.jstree.idregex,'\\$&'), t.element); } catch(ignore) { }
				if(v && v.length) {
					if(t.is_closed(v)) {
						t._data.search.opn.push(v[0].id);
						t.open_node(v, function () { t._search_open(d); }, 0);
					}
				}
			});
		};
	};

	// helpers
	(function ($) {
		// from http://kiro.me/projects/fuse.html
		$.vakata.search = function(pattern, txt, options) {
			options = options || {};
			if(options.fuzzy !== false) {
				options.fuzzy = true;
			}
			pattern = options.caseSensitive ? pattern : pattern.toLowerCase();
			var MATCH_LOCATION	= options.location || 0,
				MATCH_DISTANCE	= options.distance || 100,
				MATCH_THRESHOLD	= options.threshold || 0.6,
				patternLen = pattern.length,
				matchmask, pattern_alphabet, match_bitapScore, search;
			if(patternLen > 32) {
				options.fuzzy = false;
			}
			if(options.fuzzy) {
				matchmask = 1 << (patternLen - 1);
				pattern_alphabet = (function () {
					var mask = {},
						i = 0;
					for (i = 0; i < patternLen; i++) {
						mask[pattern.charAt(i)] = 0;
					}
					for (i = 0; i < patternLen; i++) {
						mask[pattern.charAt(i)] |= 1 << (patternLen - i - 1);
					}
					return mask;
				}());
				match_bitapScore = function (e, x) {
					var accuracy = e / patternLen,
						proximity = Math.abs(MATCH_LOCATION - x);
					if(!MATCH_DISTANCE) {
						return proximity ? 1.0 : accuracy;
					}
					return accuracy + (proximity / MATCH_DISTANCE);
				};
			}
			search = function (text) {
				text = options.caseSensitive ? text : text.toLowerCase();
				if(pattern === text || text.indexOf(pattern) !== -1) {
					return {
						isMatch: true,
						score: 0
					};
				}
				if(!options.fuzzy) {
					return {
						isMatch: false,
						score: 1
					};
				}
				var i, j,
					textLen = text.length,
					scoreThreshold = MATCH_THRESHOLD,
					bestLoc = text.indexOf(pattern, MATCH_LOCATION),
					binMin, binMid,
					binMax = patternLen + textLen,
					lastRd, start, finish, rd, charMatch,
					score = 1,
					locations = [];
				if (bestLoc !== -1) {
					scoreThreshold = Math.min(match_bitapScore(0, bestLoc), scoreThreshold);
					bestLoc = text.lastIndexOf(pattern, MATCH_LOCATION + patternLen);
					if (bestLoc !== -1) {
						scoreThreshold = Math.min(match_bitapScore(0, bestLoc), scoreThreshold);
					}
				}
				bestLoc = -1;
				for (i = 0; i < patternLen; i++) {
					binMin = 0;
					binMid = binMax;
					while (binMin < binMid) {
						if (match_bitapScore(i, MATCH_LOCATION + binMid) <= scoreThreshold) {
							binMin = binMid;
						} else {
							binMax = binMid;
						}
						binMid = Math.floor((binMax - binMin) / 2 + binMin);
					}
					binMax = binMid;
					start = Math.max(1, MATCH_LOCATION - binMid + 1);
					finish = Math.min(MATCH_LOCATION + binMid, textLen) + patternLen;
					rd = new Array(finish + 2);
					rd[finish + 1] = (1 << i) - 1;
					for (j = finish; j >= start; j--) {
						charMatch = pattern_alphabet[text.charAt(j - 1)];
						if (i === 0) {
							rd[j] = ((rd[j + 1] << 1) | 1) & charMatch;
						} else {
							rd[j] = ((rd[j + 1] << 1) | 1) & charMatch | (((lastRd[j + 1] | lastRd[j]) << 1) | 1) | lastRd[j + 1];
						}
						if (rd[j] & matchmask) {
							score = match_bitapScore(i, j - 1);
							if (score <= scoreThreshold) {
								scoreThreshold = score;
								bestLoc = j - 1;
								locations.push(bestLoc);
								if (bestLoc > MATCH_LOCATION) {
									start = Math.max(1, 2 * MATCH_LOCATION - bestLoc);
								} else {
									break;
								}
							}
						}
					}
					if (match_bitapScore(i + 1, MATCH_LOCATION) > scoreThreshold) {
						break;
					}
					lastRd = rd;
				}
				return {
					isMatch: bestLoc >= 0,
					score: score
				};
			};
			return txt === true ? { 'search' : search } : search(txt);
		};
	}($));

	// include the search plugin by default
	// $.jstree.defaults.plugins.push("search");
}));
```

**Comment by gl3n** [comment]
This is good news. Tell me if you want a beta tester for this new plugin.

**Comment by Wivison** [comment]
Hi,

Ivan you are implementing a new plugin or will merge in search plugin?
And if possible, could make an example of using? Because I'm the same difficulty of gl3n.

Sorry an error in writing. My English is basic.

Thanks.

**Comment by vakata** [comment]
I hope to be able to merge, but I am not sure yet. I don't want to break the API. Anyway - I will be back to this plugin in a few days when I hope to release 3.1.0. In the mean time - feel free to test the above code and tell me if you spot any issues.

**Comment by Wivison** [comment]
Okay, I will use the above code and anything I notice. Thanks for the quick response and you are doing a great job with the jstree, consider the best jquery plugin to work with tree. Congratulations!

**Comment by vaniaravinda** [comment]
Hi,

Can u please suggest me how to use the jstree search only for the selected parent node?? Existing jstree is giving the entire tree search result but I want search results of child at parent level(Selected Parent node) only.

Your suggestions are more helpful.

Thanks

**Comment by vakata** [comment]
You probably need the fourth parameter to search - `inside`, which limits search results to a particular parent and below: http://www.jstree.com/api/#/?q=search&f=search%28str%20[,%20skip_async]%29

Best regards,
Ivan

**Comment by vaniaravinda** [comment]
Hi,
TanQ :+1: so much for your quick reply. If u don't mind can u please give sample syntax for that??
As of now my code is as below
  $('#jstree_demo_div').jstree({
            "plugins": ["search"],
             "search": { "show_only_matches": true}
        });

Thanks

**Comment by vakata** [comment]
Somewhere in your code you invoke the `search()` function - make sure you pass in the fourth parameter. As for the other params - they are described in the link I gave you.

**Comment by vaniaravinda** [comment]
Hi,
 TanQ :+1: so much for your quick reply. I'll try and let u know if not I'll get back to u.

Thanks

**Comment by ninjavungve** [comment]
Hi vakata!
Plese guide me to add a plugin to jstree core?

**Comment by altvirus** [comment]
Hello, @vakata . 
I have some trouble with a search in the tree. In my object of tree was used key "text" with value, which contains html code. If I'm typing text with html in search field, plugin finds all leafs, because they contains this html-tag. 
How I can to resolve this trouble and to search only text between the html-tags?
Thanks.

**Comment by vakata** [comment]
Use the flexible `search_callback` option - you will have full manual control over what is considered a match and can customize the search as needed.

**Comment by altvirus** [comment]
@vakata , can you give an example of work a search_callback for my trouble?
Thanks.

**Comment by ahmedfire** [comment]
hello, @vakata .
i'm new in jstree and try do build jstree dual 2 trees
and want to select the node and when click the button node hide from the first tree and show in the 2nd tree with parent
please help me
thanks
