### ISSUE TITLE
setting the node_id inside the rename_node.jstree event

### ISSUE THREAD

**Issue by tejeshsmith** [vakata/jstree#687]
i'd like to rename my id, inside the "rename" node event,

this is my code,
 $('#jstree').on('rename_node.jstree', function (node,obj) {
// var node_id = "123" //calculated
.....
i've tried the 3 below,

 $('#jstree').jstree(true).set_id(obj,node_id); //not working

```
 obj.instance.set_id(this,node_id)// not working either
 obj.instance.set_id(obj,node_id)//nope..
```

how do i set the id?

**Comment by emillanm** [comment]
works for me too!! thanks
