### ISSUE TITLE
Search and CheckBox Plugins check hidden nodes

### ISSUE THREAD

**Issue by coreyperkins** [vakata/jstree#717]
I have noticed that if I do a search (with the "show_only_matches" bool set to true) the filtering works as expected. However, if I check a node that has hidden child nodes it will still check those children. I would expect it to only check the visible ones. I've gone though the code and I don't see an option available to make this happen. Is there one? I'd be happy to try and contribute one if not.

I'm working with 3.0.1.

Thanks

**Comment by MarkLeith** [comment]
+1 on this, selecting values that are filtered from view is a bad user interaction (and totally non-intuitive from a developer perspective too).

**Comment by danilo-helabs** [comment]
+1

**Comment by istrau3** [comment]
+1 my users are complaining about this.

**Comment by istrau3** [comment]
@vakata Any thoughts on fixing this. My users keep complaining about this (as it is very not intuitive for them). When checking a parent node (or unchecking), they only expect to affect the visible nodes.

**Comment by vakata** [comment]
A pull request would be welcome - I do not know where to begin. What if some children are hidden and the parent is checked - what should the parent icon be - checked or undetermined (as it has unchecked children), what if the hidden nodes are shown at some point later in time - how should that affect the parent status? How would you solve this - what is logical for your app?

**Comment by istrau3** [comment]
@vakata If there are some hidden unchecked children, the icon should (in my opinion) be undetermined (users understand that there are hidden unchecked items filtered out by the search). If the hidden nodes are shown again, that will have no affect on the parent status.

Basically, no change in the function of undetermined nodes, just avoid checking hidden nodes (the calculation for the parent state remains the same, it takes into account the hidden children).

**Comment by istrau3** [comment]
I will do my best to submit a PR (not very familiar with the code though).

**Comment by cassianomon** [comment]
@vakata related to this issue, is there a option where I have a similar behavior of  `check_all()` but for only filtered list?
