### ISSUE TITLE
Allow user to select and copy node text

### ISSUE THREAD

**Issue by ryanlchandler** [vakata/jstree#719]
It looks like events are being captured so that normal text selection is not possible.  Is it possible to allow the user to select and copy the text for each node?

**Comment by victarmas** [comment]
Is there a fix for this? I don't have a need for the drag-and-drop feature. Thanks!

**Comment by victarmas** [comment]
Here's a solution I came up with, which I hope helps others. I just floated a duplicate div with the content over each node on hover.
`
$(document).ready(function() {
    jQuery('.jstree').on('hover_node.jstree', function(e, data) {
        var this_node = $("#" + data.node.id + " .content");
        var node_top = this_node.position().top;
        var node_left = this_node.position().left;

        $("#" + data.node.id + " .content:first span").css("visibility", "hidden");
        $("#" + data.node.id + "_copy").css({top: node_top, left: node_left, display: "inline-block"});
    })
});
`
