### ISSUE TITLE
Node text does not escape html

### ISSUE THREAD

**Issue by TheJosh** [vakata/jstree#756]
When using inline HTML to populate the tree, if the nodes contain HTML entities, the node text will contain those entities even though they aren't rendered. I need to include HTML entities to be outputting valid HTML.

Test case:

``` html
<div id="jstree">
    <ul><li id="test">Test &amp; node</li></ul>
</div>
<script>
$(function () {
    $('#jstree').jstree();

    // this returns 'Test &amp; node' instead of 'Test & node'
    alert($.jstree.reference('#jstree').get_node('test').text);
});
</script>
```

In my testing I also switched to JSON loading, not to test the html encoding issue (because that doesn't apply to JSON) but to see if it breaks there when an embedded SCRIPT tag. These are still rendered as-is. This is a potential XSS issue for AJAX users:

``` javascript
$('#jstree').jstree({
    core: { data: [
        // this will cause an alert when the node is rendered
        'Test <script>alert("XSS");</script> node'
    ] }
});
```

I'd imagine you would need to decode entities while loading HTML (the JSON and AJAX loading can remain as-is), with another step being the encoding of entities at node render time.

**Comment by abeverley** [comment]
I had this same problem (I wanted users to be able to input/edit nodes with HTML entities). This fix works great. Many thanks.

**Comment by cweiske** [comment]
Summary: To let jsTree escape node "text" data automatically, set the configuration option `$.jstree.defaults.core.html` to `false`.
