### ISSUE TITLE
How to give initial root nodes undetermined state when children aren't loaded yet?

### ISSUE THREAD

**Issue by carlobernardini** [vakata/jstree#757]
Hi,

I'm building a tree with three-state checkboxes for each node. Initially only the topmost root nodes are loaded (in JSON format), then their children are loaded on demand when the user expands a node having children.
As I said initially only the topmost nodes are loaded in this format:

[{
    "id":"100",
    "parent":"#", // Indicates this is a topmost root node
    "text": "Test node which has children",
    "children":true, // Wether or not the node has children
    "state":{
        "selected": true, // Node is selected
    }
}]

The 'state' parameter only seems to accept the 'selected', 'opened' and 'disabled' states. Since the children aren't loaded yet I would want to specify (as this is being checked by the backend) if a node is undetermined (not selected and not deselected, square in checkbox). However, I've not yet found out how to do this. An 'undetermined'-state doesn't seem to do anything. Can I achieve what I want in a simple way or would I have to think of some kind of hack / create a function which reads out some custom parameter which indicates a node has to be undetermined after the JSON has been loaded?

Thanks in advance!

**Comment by GussSoares** [comment]
@kghosh Please, how to define lazy load in jstree???
