### ISSUE TITLE
Jstree 3.0.2 select node not working

### ISSUE THREAD

**Issue by Tochemey** [vakata/jstree#772]
I am using the latest Jstree. After loading the tree on the DOM, I want to select a particular node within another but i seems not working. However when the node is a parent node it is selected as expected. 

Please can you assist me to fix this issue.

**Comment by realtaken** [comment]
@vakata would you be able to give me some guidance please. I have many fields which I map with different nodes from the jstree and this is all working but when I edit a field to map, the jstree loads the last selected node, I want the only selected node to be this particular field I have mapped previously.

I have the id of the mappedField, I now just need to pass this into the select_node method but what ever I try is not working, this is my code.

function toggleSelector(ctrl) {
            var row = $(ctrl).closest('tr');
            var mappedFieldId = $(row).find('[id$="MappingPath"]').val();
            $('#jstree').bind('reselect.jstree', function () {
                $('#jstree').jstree().select_node(mappedFieldId);
            });
        }

I have also tried without the binding (not sure if I need it or not) and also with $('#jstree').jstree('select_node', mappedFieldId) syntax.

Thank you
