### ISSUE TITLE
Passing ajax data parameters directly when calling search function on the tree

### ISSUE THREAD

**Issue by leniel** [vakata/jstree#773]
Is it possible to pass additional parameters directly when calling the search function on the tree?

`
$("#tree").jstree().search(str, false, { parameterName: someValueHere });
`

I ask this because in my case right now I need the data to be dynamic instead of hardcoded in the search plugin config like this:

```
 "search": {
                "case_insensitive": true,
                "skip_async": false,
                "ajax": {
                    "url": "tree/GetParentNodes",
                    "data": { parameterName : $("#someInput").val() }
                }
```

The config above is assembled only once when the page loads and jsTree won't reevaluate the value of `$("#someInput").val()` dynamically, that is, it always sends the same value to the server! Hope you get my drift.

By the way: I'm using `jsTree 3.0.2`.

**Comment by Astriel** [comment]
This solution is not working for me. Each time I'm trying to do a function AJAX request, it's not opening the nodes after the search.

**Comment by vakata** [comment]
What you return in the response is a list of all parent nodes that should be loaded to reveal the matches. Keep in mind if jstree does not find matches it will not open the nodes (even though they are loaded). You have full manual control over what is considered a match using search_callback.
