### ISSUE TITLE
Cascade down overrides node selected state when loading data

### ISSUE THREAD

**Issue by poffof** [vakata/jstree#774]
I was very happy to notice the cascade: down option for checkbox tree in the latest version, since it was exactly what I needed. However, the issue I'm having with it is that the cascading applies also when generating the tree from JSON data, and not just when clicking the checkboxes in the generated tree. This means that the selected state I have set for each node in the data may be overridden by the cascading.

This results in a situation where I can save the tree state like this, where I have deselected "Two" and so "Three" has also been deselected:
![3](https://cloud.githubusercontent.com/assets/8288104/3719082/e681600c-163e-11e4-97d2-0f58ed7caae5.png)

But when I load it from JSON data where the state for both "Two" and "Three" is "selected": false, the selected state of "One" will cascade down, resulting in a situation like this (I have the nodes that should be deselected also colored gray):
![5](https://cloud.githubusercontent.com/assets/8288104/3719161/a9ae83e8-163f-11e4-8e0e-5e330ef44eb6.png)

Is there any way around this, so that I could keep the state when loading data the same way I have saved it?

**Comment by saranya-1992** [comment]
$("#your-tree").on("select_node.jstree", function (e, data) {
  if(data.event) { data.instance.select_node(data.node.children_d); }
});

This one so useful..
But in 1000 nodes, it's getting slow performance.

**Comment by TomLorenzi** [comment]
Here's my solution, if you instancied cascade like this, this should use the native cascade function after init and won't make any performance problems.

```
$tree.on('init.jstree', function(e, data) {
    data.instance.settings.checkbox.cascade = '';
}).jstree({
    core: {
        multiple: true,
        check_callback: true,
        data: {'Your own data'},
    },
    checkbox: {
        three_state: false,
        cascade: 'down'
    },
    plugins: listPlugins
}).on('loaded.jstree', function() {
    $tree.jstree(true).settings.checkbox.cascade = 'down';
})
```
