### ISSUE TITLE
refresh the tree repeatedly will trigger the tree crash

### ISSUE THREAD

**Issue by a0p00d** [vakata/jstree#791]
I add a button click to trigger jstree call the refresh method, if I click on it repeatedly (wait the last tree loaing done), I find sometimes it will crash the page totally, with no error log in the chrome console.

I write the jstree part like file browser demo, all I added is to load a list of node in the after_open callback

I debug from the server, and find the response for the query node is returned, but the browser doesn't trigger any before_open event, it is very strange...

**Comment by tolar** [comment]
Just note, that I also faced this problem.
