### ISSUE TITLE
Cascade Selection Up+Down, Cascade Deselection Down

### ISSUE THREAD

**Issue by savage25** [vakata/jstree#795]
I can't figure out how to do this... I'm hoping you have an easy solution.
For List:
a
 a.1
  a.1.A
  a.1.B
 a.2
  a.2.A
  a.2.B

If nothing is selected, and "a.2" is selected, I want "a" and all children of "a.2" to be selected (a.2.A & a.2.B).
And, if everything is selected, and "a.2" is deselected, I want "a" to remain selected, but all children below "a.2" to be deselected.

I have figured out the override of "Deselection Down" and the "Selection Up".  
http://jsfiddle.net/DGAF4/41/

But, I cannot figure out how to do the "Selection Down" -- when I try to cascade the downward selection, the "select" event fires when the parent node is "selected" during the cascade up, which then causes the recursive downward selection event to cause everything in the tree to become selected..
http://jsfiddle.net/DGAF4/42/

It would be great if the cascade functionality had this built in.  I tried to implement with temporary global variables to prevent the cascade down when in the middle of doing an up, but I couldn't get it to work.

Thanks for any assistance!

**Comment by lucasumberto** [comment]
"Conditional cascade" has a very common use for dependency cases where the tree can't have the last node checked if any of the parents aren't checked.
Thanks savage, this should really be in the core.

**Comment by krunal1089** [comment]
I have seen this example  (http://jsfiddle.net/DGAF4/41/) and it ia working as expected but is it possible to select first child node automatically if I select parent node and if already any child node selected then not more than 1 child node can be select?

**Comment by vakata** [comment]
@krunal1089 you probably need conditionalselect ... and a lot of custom logic, but it should be doable.

**Comment by krunal1089** [comment]
Hi vakata, Thanks for reply but I am not able to write custom logic as expected can you please help me with this? and child node should select automatically only fir level 4.
I have also created this example http://jsfiddle.net/56dwbe83/24/ can some one try and provide update on this.

**Comment by vakata** [comment]
Sorry, I can not help you with the custom logic - this is not something I provide as a part of supporting and maintaining jstree. You might have better luck on stackoverflow.
