### ISSUE TITLE
Nested nodes overlaying items lower down the tree.

### ISSUE THREAD

**Issue by MattMcCarthy** [vakata/jstree#837]
Bug and a possible fix.
The jquery animate function you are using for opening the jstree-children UL, is writing the UL's style tag after the complete event is fired. Leaving, height and padding styles in place. The height setting causes the opening of sub nodes to overlay lower content.

Suggested work around.
Replace the code from line 2159

d
    children(".jstree-children").css("display","none").end()
    .removeClass("jstree-closed").addClass("jstree-open").attr("aria-expanded", true)
    .children(".jstree-children").stop(true, true)
    .slideDown(animation, function () {
        this.style.display = "";
        t.trigger("after_open", { "node" : obj });
    });

with

d
    .children(".jstree-children").css("display","none").end()
    .removeClass("jstree-closed").addClass("jstree-open").attr("aria-expanded", true)
    .children(".jstree-children").stop(true, true)
    .slideDown(animation);
d
    .promise().done(function () {
        d.removeAttr("style");
        t.trigger("after_open", { "node" : obj });
    });

The promise / done combo allows the animate to fully complete before further events happen.
d.demoveAttr is a little brutal, but works for my situation.

HTH

**Comment by ment173** [comment]
Hello Matt,

Where you ever able to find a solution for this. I'm having the exact same problem at my current place of work. I know this was 7 years ago, but do you by chance remember what the fix was for this if there was one?

Thanks in Advance!
