### ISSUE TITLE
How to cancel the node move, depending on conditions?

### ISSUE THREAD

**Issue by acelot** [vakata/jstree#843]
``` js
.on("move_node.jstree", function (e, data) {
  // moving node via ajax request...
  // if not success cancel moving
  // else move
})
```

How to implement this behavior?

**Comment by redtopia** [comment]
@acelot - did you ever figure out how to undo a drag and drop action? From what I can see in your example (and I assume from what you already figured out by now), your ajax call to move the node on the server would happen in the `move_node` event listener as follows (shorthand code):
```
$('#tree').jstree(options).on('move_node.jstree', function(e, data) {
    // the check_callback returned true and the user moved the node
    ... make ajax call to move the node in the back end ...
move?)
});
```
I'm trying to figure out how I can cancel the move action (or undo the move action) if the ajax call failed for some reason, like if the server rejected the move?

**Comment by acelot** [comment]
@redtopia I've been waiting for you 4 years! :D (joke)
As far as I remember, it was a long time ago (in far far galaxy), I decided to do so, as recommended by @vakata.

**Comment by ekr3peeK** [comment]
@redtopia  @acelot  this is an old thread, but assuming that you have all the information in the `move_node` event listener, you can revert the action manually, in case the ajax request failed somehow.

I would advise putting the tree in a loading state, while the ajax request runs, and if the ajax request fails, using the same `data` variable to perform the inverse move action.
