### ISSUE TITLE
Problem with finding collapsed nodes.

### ISSUE THREAD

**Issue by sebah1989** [vakata/jstree#846]
Hi.

I have tree in which I'm looking for node by its id. Everything is ok, when node which I'm looking for is visible(his parent has state opened), but when its parent is closed jstree can't find that node.  For example:
$(document).ready(function(){
  $('#jstree_demo_div').jstree({ 'core' : {
    'data' : [
      { "id" : "ajson1", "parent" : "#", "text" : "Simple root node" },
      { "id" : "ajson2", "parent" : "#", "text" : "Root node 2" },
      { "id" : "ajson3", "parent" : "ajson2", "text" : "Child 1" },
      { "id" : "ajson4", "parent" : "ajson2", "text" : "Child 2" },
    ]
  }});

  $("#jstree_demo_div").on("select_node.jstree", function(){
    console.debug($(this).jstree(true).get_node("#ajson4"));
  });  
});

When 'Root node 2' node is opened there is an object returned to console, but when I close 'Root node 2' there is no node founded and false returned...

**Comment by ruwen-m** [comment]
Thanks vakata!
This also solves my problem when i update nodes of collapsed parents!
