### ISSUE TITLE
Suggestion: load_all

### ISSUE THREAD

**Issue by bzums** [vakata/jstree#875]
Hi,
ich would like a load_all method which works like open_all, just without opening the node. I tried to implement it myself more or less along the lines of open_all but realized thats its not that easy...
What do you think?

(To make it more clear: thats of course only necessary for a tree which is loaded async...)

Greets

**Comment by Rajesh-Pradhan** [comment]
Hi,
I want to open a specific node having selected but not able to do as I observe there the child level nodes only get forming when we expand the node. So is there any way to so that I can make one specific node (Leaf or Parent) get expanded at page load 

Thanks
