### ISSUE TITLE
get_checked node list return tree's id

### ISSUE THREAD

**Issue by ghost** [vakata/jstree#905]
Hi
i can't get checked nodes from tree, all solution was tested but does not resolved
i am using jstree with checkbox and always return value is tree's id
best regard

**Comment by wingyiu** [comment]
updated the document please?

**Comment by vakata** [comment]
No need, if you do not use `tie_selection: false` the `*checked` functions behave the same way as `*selected`.
Best regards,
Ivan

**Comment by ramibaccour** [comment]
var nodeChecked= $('#idTree').jstree(true).get_checked($('#idTree').jstree(true)._model.data,true);
