### ISSUE TITLE
End-to-End example 1) load the tree from JSON  2) user changes the tree  3) save the tree back to JSON

### ISSUE THREAD

**Issue by YO-Tech** [vakata/jstree#915]
OUF !!! after a month of jquery, javascript, AJAX, googling, reading and testing ... jstree.js development code reviews, ...

I do not understand why a simple example to perform following does not exist anywhere (Reading the API is painfull !!!) 

1) to load a tree from a any source (JSON, SQL database ... keep it simple, let's say JSON) ... I am able to do so !
2) give the user the possibility to change the tree nodes (DND, add, modify, delete are enough) ... I am able to do so !
3) and mainly ... save the changes back to the same source (JSON, SQL database, ...) for future usage Why allowing changes if we cannot save them ? ( I have tried lots of things from the API doc).  

You seem to be the GURU of this tool.

Easiest solution for me would be an updated nodes array from which I would be able to extract the node ID and PARENT and re-create my source for future usage after the user click on a SAVE button.

Ideally, I would let the user perform all updates he want and a SAVE button would scan the updated array and update back the source.

Many thanks in advance.  I am building a site which will use the outcome of tree updates.

Bye.

**Comment by orionseye** [comment]
> Hi,
> 
> 1. Take a look at the bundled PHP example (also available on jstree.com) - it is called sitebrowser and does exactly that

Wow.. sooo beautiful :) Thanks!
