### ISSUE TITLE
Optimizing dnd for touch devices

### ISSUE THREAD

**Issue by Glideh** [vakata/jstree#929]
Having the dnd working on touch devices is great.
But if the user wanted to scroll, he would have to touch an area without a node.
If he mistakenly **scrolls** on a node, it gets **dragged**.

Wouldn't there be a way to add a **delay** before triggering the drag ?
(As with mobile applications to move the shortcuts for example)

**Comment by vakata** [comment]
I am reading up on the idea. From what I have read so far it seems that holding to drag may be counterintuitive to most users and would be harder to explain, even if we put aside the fact that on most mobile browsers if you hold for too long the contextmenu event will be triggered.
How do you feel about only being able to drag the selected item on mobile? Tap to select and then drag - seems like a reasonable compromise, I will make it a setting of course which can be enabled or disabled. How do you feel about this suggestion?

**Comment by Glideh** [comment]
You are right, I didn't though about the standard behavior when holding the tap (context menu or text selection)
> How do you feel about only being able to drag the selected item on mobile?

You mean **not** in mobile, right ?
I think it would be a good idea to be able disable the dnd for mobile.

That said, I'm not still sure about the dnd intuitivity in mobile devices as it is still a non expected standard behavior (a slide is expected to scroll)

**Comment by vakata** [comment]
You can even now disable the dnd plugin for mobile (by not including it), but what I am suggesting takes this a step further:
Option 1 would be to keep it as is (the default) - if you tap and move on a node title - it will be dragged (so mobile is the same as desktop).
Option 2 would be to only be able to drag selected node - so taping and moving on a not selected node would scroll (that would be valid for mobile only - desktop will not be affected).
Option 3 would be to disable dnd on mobile (but not by conditionally omitting the dnd plugin in your config but by a setting in the dnd plugin options).

**Comment by Glideh** [comment]
The option 3 was actually what I was suggesting as a first step.
Having both 3 behaviors available would be great.
So dnd would have an option `reponsiveness` or `behavior` with 3 possible values:
* `standard` (default)
* `no_mobile`
* `partial` (select before drag on mobile)

**Comment by Glideh** [comment]
Seems perfect, I'll try that. Thanks !

**Comment by vakata** [comment]
The values for the `touch` option are boolean `true`, boolean `false`, and string `"selected"`. Let me know if there are any issues.
