### ISSUE TITLE
JSTREE function on the last clicked node

### ISSUE THREAD

**Issue by YO-Tech** [vakata/jstree#939]
Hi,

I have a page that shows, on the left side, tree nodes and on the right, details of the clicked node.

One of the fields on the right can be modified by the user from a drop-down list.

it is working fine when I click on one node and I use the drop-down list to update the node ... BUT, when I clicked more than 1 node prior to update the LAST ONE, it updates all previously clicked nodes !!

It seems working like a "checkbox" .;.. I would like to use it like a SELECT.

I have tried to use the $('#tree').jstree(true).deselect_all(), the MULTIPLE:false and the checkbox three_state false options as found in multiple google searches.

What I am looking at is to process one click node at a time or find way to address the last clicked node for the user to apply field update throughout the drop-down list.

I can provide codes and print screen on request.

Many thanks again.

Ciao.

**Comment by YO-Tech** [comment]
Ivan,
 
… as previously mentioned, I cannot access the discussion group so far.
 
I am re-visiting my coding to now use checkboxes.  After converting the code, the issue is still the same.
 
The JSTree code is working fine when I select (click) a street address (see my other email print screen) one after the other … only 1 address is process (I traced it)  BUT when I SELECT FROM A DROPDOWN LIST the RESPONSIBLE of the street grouping I just clicked, it re-processes all previously selected nodes (?).
 
Here is the code surrounding the SELECT on change:
 
                $( "#AddrT" ).on("select_node.jstree", function(e, data) (I have traced this process and this is o.k. … I clicked it 3 times and the 1 node was displayed at a time)
                {
                               $( "#WayRespL" ).css({'-webkit-appearance': 'menulist'});
                               $('.WayRespD2').css({'background-color': 'white'});
                               $("#WayRespL").prop("disabled",false);
                               $( '#WayRespL' ).val(data.node.data.WayResp);
                });
                $("#WayRespL").change(function() (when I changed the responsible from the dropdown list, it processes all previously checked nodes even if I done the selection on the last node checked … the other ones, were not checked)
                {              
                               $( "#AddrT" ).on("select_node.jstree", function(evt, data)
                               {
                                               $( '#WayRespL' ).val(this.value);
                                               $( '#WayResp' ).html(this.value);
                                               console.log(data.node.text);
                               });
                })
 
De : Ivan Bozhanov [mailto:notifications@github.com] 
Envoyé : Monday, December 29, 2014 2:04 AM
À : vakata/jstree
Cc : YO-Tech
Objet : Re: [jstree] JSTREE function on the last clicked node (#939)
 
Please provide your code so that I can help you, but it seems to me the error is in your code. Are you using the checkbox plugin or not? Anyway - how you handle selection is up to you, I can assure you jstree handles selection the way it should. Of course I will help you further if you provide some code, but please do so in the groups page: https://groups.google.com/forum/#!forum/jstree
Best regards,
Ivan
—
Reply to this email directly or  <https://github.com/vakata/jstree/issues/939#issuecomment-68236447> view it on GitHub.  <https://github.com/notifications/beacon/AJbZixc4tc-01wwRKdsjJOVgDu0XQY2Xks5ncPRUgaJpZM4DMv8j.gif> 
No virus found in this message.
Checked by AVG - www.avg.com
Version: 2015.0.5577 / Virus Database: 4257/8826 - Release Date: 12/28/14

**Comment by vakata** [comment]
Have a look at the API docs - especially the functions and events dealing with selection. I can assure you all you need to work with selections is there and it works properly.
