### ISSUE TITLE
Prevent DND (move) outside its root node

### ISSUE THREAD

**Issue by YO-Tech** [vakata/jstree#943]
Hi,

Can the CRRM (or other) plugin handle DND (move) of a node outside its root ?

Thanks.

Bye.

**Comment by vakata** [comment]
I am not exactly sure what your logic is, but if you want fine control over what is considered a valid new position for a node - use core.check_callback, it is a function that will be constantly executed while the user is dragging and returning true or false means that it is a valid move (and will be allowed) or is not valid (and will not be allowed even if the user drops).
