### ISSUE TITLE
add a button before node and checkbox

### ISSUE THREAD

**Issue by linkstack** [vakata/jstree#946]
Hi,
Can I add a button before the checkbox? (the "checkbox" plugin is enabled)

I tried to add button html directly to node text, but the button will appear after the checkbox. please check http://jsfiddle.net/c43mdyd7/.
The reason to do it is because that when user click this button, all children (and children of children, etc.) of this node need be expanded.

Thanks

**Comment by vakata** [comment]
This has been discussed in the groups page, but I can't find the exact topic. 
https://groups.google.com/forum/#!forum/jstree
To add UI elements you need to build a plugin. It is fairly easy - take a look at `src/misc.js` to get a feel, there are a couple of plugins that add a new UI clickable UI element to all nodes - for example `questionmark`.
Best regards,
Ivan

**Comment by linkstack** [comment]
Thanks I will check it soon
