### ISSUE TITLE
Tree appears disabled in IE 10, but fine in Firefox 34

### ISSUE THREAD

**Issue by geoffreywk** [vakata/jstree#947]
For some reason when I view the tree in IE 10 it appears disabled.  However, if I view same page in Firefox 34 tree appears normal. In addition, in IE 10 the nodes all appear with expansion indicators even if there are no sub-nodes, but doesn't happen in Firefox.  I am using 3.0.8 of the jsTree.  

Please see attached screen shots.  Tried to attached ASPX with code, but wouldn't let me upload them.

![firefox](https://cloud.githubusercontent.com/assets/10407339/5628850/89dfd444-957a-11e4-8c5f-87dfdc32238c.PNG)
![internetexplorer](https://cloud.githubusercontent.com/assets/10407339/5628851/89e2c488-957a-11e4-8755-26c1a03c4517.PNG)

**Comment by vakata** [comment]
You must be in compatibility mode - if you enabled it manually - disable it in the browser. If set using a meta tag - make sure you emulate at least IE8. Also keep in mind compatibility mode will be automatically triggered for intranet sites unless explicitly told otherwise (using a meta tag).

**Comment by geoffreywk** [comment]
Thanks that was the issue.  Once added meta tag for compatibility worked fine.
