### ISSUE TITLE
jstree .on(changed.jstree) and .refresh

### ISSUE THREAD

**Issue by YO-Tech** [vakata/jstree#950]
Goal:  change metadata of checked node(s) and refresh the tree to show the updates.  

Here for testing purposes, I change the .text field (instead of metadata) of checked nodes.

Once processed, I do not see the updates on the text field BUT if I expand the node (clicking on the arrow of the node) then the tree get refreshed and the parent node and its children text are shown with the text changed.

I would like the text being changed when I clicked, i.e. after processing the following function.

Here is my code

	$('#AddrT').on('changed.jstree', function (e, data)
	{	
		for(i = 0; i < data.selected.length; i++)
		{
			data.instance.get_node(data.selected[i]).text = "new text"; 
                        // changed 8 times for the parent node and its 7 children
		}
	});
	$('#AddrT').jstree(true).refresh(); 

BEFORE checking the nodes:

![image](https://cloud.githubusercontent.com/assets/9886091/5668578/afaa5d96-973e-11e4-8315-dcbb9edfe864.png)

AFTER checking the nodes (no change):

![image](https://cloud.githubusercontent.com/assets/9886091/5668636/1f4c0938-973f-11e4-836b-ce69195cb462.png)

AFTER closing and expanding the parent node (this is what I am expecting from my code but without closing and opening the node)

![image](https://cloud.githubusercontent.com/assets/9886091/5668604/dd8b4ae0-973e-11e4-8157-f236acce0e5b.png)

**Comment by vakata** [comment]
That line: `$('#AddrT').jstree(true).refresh();` should be inside the event handler and it will work as you expect it to.
