### ISSUE TITLE
jstree .on(changed.jstree) and .refresh #950

### ISSUE THREAD

**Issue by YO-Tech** [vakata/jstree#952]
It did not work.  Here is the complete tree code:

$( "#AddrT" ).jstree
	({	"plugins"			:	[	"checkbox"
								,	"contextmenu"
								,	"crrm"
								,	"dnd"
								,	"grid"
	//							,	"search"
								,	"sort"
								,	"state"
								,	"types"
								,	"unique"
								,	"wholerow"
								]
	,	"checkbox"			:	{	"three_state"			:	true		// if check boxes should cascade down and have an undetermined state. Defaults to true.
								,	"whole_node"			:	false		// if clicking anywhere on the node should act as clicking on the checkbox. Defaults to true.
								,	"keep_selected_style"	:	false		// if the selected style of a node should be kept, or removed. Defaults to true
								}
								
	,	"contextmenu"		:	{	"show_at_node"			:	true		// if the menu should be shown aligned with the node. Defaults to true, otherwise the mouse coordinates are used.
								,	"select_node"			:	false		// if the node should be selected when the context menu is invoked on it. Defaults to true.
								,	"items"					:	function(n)	{	var	tmp					=	$.jstree.defaults.contextmenu.items();
																					tmp.create.label	=	'AJOUTER';
																					tmp.rename.label	=	'RENOMMER';
																					tmp.remove.label	=	'SUPPRIMER';
																				return tmp;
																			}
								}
	,	"core"				:	{	"check_callback"		:	true		//	determines what happens when a user tries to modify the structure of the tree
								/*	"check_callback"		:	function (operation, node, parent, position, more)
																{
																	if(operation === "copy_node" || operation === "move_node")
																	{
																		if(parent.id === "#")
																		{
																			return false; // prevent moving a child above or below the root
																		}
																	}
																	return true; // allow everything else
																}*/
								,	"animation"				:	200			//	the open / close animation duration in milliseconds - set this to false to disable the animation (default is 200)
								,	"themes"				:	{	"stripes"			:	false
																,	"icons"				:	true
																,	"dots"				:	true
																,	"variant"			:	false //"large"
																}
								,	"strings"				:	{	"New node"			:	"NOUVEAU GROUPE"
																}
	//							,	"multiple"				:	true		//	if multiple nodes can be selected - commented option provide the use of CTRL key
								,	"data"					:	{	"url"				:	"Addr.json"
																}
								,	"dataType"				:	"json"
								}
	,	"grid"				:	{	"columns"				:	[	{	"header"	:	"Adresses"
																	,	"width"		:	50
																	,	"title"		:	"_DATA_"
																	}
																,	{	"header"	:	"Responsabilités"
																	,	"cellClass"	:	"col1"
																	,	"width"		:	30
																	,	"value"		:	"WayResp"
																	,	"title"		:	"WayResp"
																	}
																,	{	"header"	:	"Résidents"
																	,	"cellClass"	:	"col2"
																	,	"width"		:	30
																	,	"value"		:	"AddrRes"
																	,	"title"		:	"AddrRes"
																	}
																]
								,	"contextmenu"			:	false	//	if there is a need to have a context menu for field edit
								}
	,	"types"				:	{	"max_children"			:	-1
								,	"max_depth"				:	2
								,	"valid_children"		:	[	"W"		]
								,	"types"					:	{	"W"					:	{	"max_children"		:	-1
																							,	"max_depth"			:	2
																							,	"valid_children"	:	[ "C", "default" ]
																							}
																,	"C"					:	{	"max_children"		:	-2
																							,	"max_depth"			:	-2
																							,	"valid_children"	:	"none"
																							}
																,	"default"			:	{	"max_children"		:	0
																							,	"max_depth"			:	1
																							,	"valid_children"	:	[ "C" ]
																							}
																}
								}
	});
	$('#AddrT').on('changed.jstree', function (e, data)
	{	
		for(i = 0; i < data.selected.length; i++)
		{
			data.instance.get_node(data.selected[i]).text = "new text";
		}
		$('#AddrT').jstree(true).refresh();
	});

**Comment by YO-Tech** [comment]
... forgot to mention:  this time, I cannot even click into the checkboxes, it refreshes the tree all the time but the CHANGED function results are not applied.  Be careful I put some commented lines AND I was not able to format the first portion of tree definition (paste it and it format only starting the context menu instruciton).

**Comment by vakata** [comment]
You are using `core.data` as an AJAX request - refresh will just refetch the data from the server. I was under the impression you were `using core.data` as a function.
In your case - do not modify the internal data model (it is not recommended any way) and use the built in `rename_node` function.
Next time please reuse the ticket - no need to post a new one - if the information provided calls for it - I will reopen the ticket.
Best regards,
Ivan

**Comment by YO-Tech** [comment]
Hi,
 
… I did add additional comment (issue) on the ticket but the ticket is still marked as CLOSED.
 
Are you getting notified with the additional comments ?
 
Ciao.
 
De : Ivan Bozhanov [mailto:notifications@github.com] 
Envoyé : Friday, January 09, 2015 7:48 AM
À : vakata/jstree
Cc : YO-Tech
Objet : Re: [jstree] jstree .on(changed.jstree) and .refresh #950 (#952)
 
Closed #952 <https://github.com/vakata/jstree/issues/952> .
—
Reply to this email directly or  <https://github.com/vakata/jstree/issues/952#event-216483948> view it on GitHub.  <https://github.com/notifications/beacon/AJbZi6DFlMHmpXAwSdGyCRFH4zxINx-1ks5nf8VzgaJpZM4DQVNZ.gif> 
No virus found in this message.
Checked by AVG - www.avg.com
Version: 2015.0.5577 / Virus Database: 4257/8896 - Release Date: 01/09/15

**Comment by vakata** [comment]
I see absolutely no comment in the original issue (after me closing it): https://github.com/vakata/jstree/issues/950
Anyway - please use the `rename_node` function and you will be fine.

**Comment by YO-Tech** [comment]
… now do you see it ?
 
You should see this:
 
Hi,
 
... thanks.  But the example provided shows that I wanted to rename the node (text node).  It was for testing purposes.  What I really want to change is the METADATA , i.e. the MANAGER NAME.  I have read the RENAME_NODE but it seems to only rename the node name.  So, is there a way to change the meta data ?
 
... business purposes:  the manager will assign the technician responsibilities according to customer addresses or group of addresses (ex. a complete street addresses can be assigned to one technician as start up assignment but 1 address within the list can be assigned to specific technician).
 
 
 
De : Ivan Bozhanov [mailto:notifications@github.com] 
Envoyé : Friday, January 09, 2015 8:55 AM
À : vakata/jstree
Cc : YO-Tech
Objet : Re: [jstree] jstree .on(changed.jstree) and .refresh #950 (#952)
 
I see absolutely no comment in the original issue (after me closing it): #950 <https://github.com/vakata/jstree/issues/950> 
Anyway - please use the rename_node function and you will be fine.
—
Reply to this email directly or  <https://github.com/vakata/jstree/issues/952#issuecomment-69336604> view it on GitHub.  <https://github.com/notifications/beacon/AJbZiw5PdWVEfrnSusRSPjaIVSWEc9m_ks5nf9U-gaJpZM4DQVNZ.gif> 
No virus found in this message.
Checked by AVG - www.avg.com
Version: 2015.0.5577 / Virus Database: 4257/8896 - Release Date: 01/09/15

**Comment by vakata** [comment]
Are you having troubles with the grid plugin? If so - please try submitting the problem there. I do not maintain the grid plugin - it is a third party plugin. If you mean that the grid plugin does not change the values "live" - I guess that is probably so, but there is nothing I can do about it - it is up to the grid plugin.

**Comment by YO-Tech** [comment]
… I am not saying that at all (problem with grid plugin) but yes, at the end, the data I want to refresh after updating it will be part of the metadata.
 
… prior to the refresh, my function is updating the data model CONTENT.  I have tried with the node text field to see if a refresh from the data model CONTENT can be done.  As you told me, the $('#AddrT').jstree(true).refresh() is refreshing from the JSON file and not for the internal data.
 
… but when I click the icon to expand the node after updating the data model CONTENT, it does refresh the tree.
 
So, there must be something that is performed when I click the arrow icon that refreshes the tree, both the node text field and its metadata.
 
The usage of the GRID plugin is to DISPLAY the metadata fields aside the node text field, which to basic jstree is not able to do.
 
Let me know if there is something existing (like I said, there must be something) to refresh the tree from the internal data.  Otherwise, I will have to save the changes to the JSON file and REFRESH the tree, which will impact the response time.
 
Thanks.
 
Bye.
 
De : Ivan Bozhanov [mailto:notifications@github.com] 
Envoyé : Friday, January 09, 2015 9:36 AM
À : vakata/jstree
Cc : YO-Tech
Objet : Re: [jstree] jstree .on(changed.jstree) and .refresh #950 (#952)
 
Are you having troubles with the grid plugin? If so - please try submitting the problem there. I do not maintain the grid plugin - it is a third party plugin. If you mean that the grid plugin does not change the values "live" - I guess that is probably so, but there is nothing I can do about it - it is up to the grid plugin.
—
Reply to this email directly or  <https://github.com/vakata/jstree/issues/952#issuecomment-69341358> view it on GitHub.  <https://github.com/notifications/beacon/AJbZiym0UakvohqdLIlcYO02uc8GD_0Fks5nf97TgaJpZM4DQVNZ.gif> 
No virus found in this message.
Checked by AVG - www.avg.com
Version: 2015.0.5577 / Virus Database: 4257/8896 - Release Date: 01/09/15

**Comment by vakata** [comment]
Let me clarify again:
1) You need to use `rename_node` if you want to change the node text
2) Using `data.instance.get_node(..).data.field = "value";` WILL update the metadata

The reason you are not seeing the updated metadata field displayed next to the node text is because *the grid plugin is responsible for visualizing that data*. I am not aware if there is a way to notify the plugin that the data has changed, because *I am not the author of the grid plugin*.

You can try calling `data.instance.redraw_node(node, true)`, but keep in mind that is an internal method, and I am not sure if the grid plugin will pick up on that call, but you can try. 
Either way - there is nothing that can be done on jstree's side, and *the issue is not with jstree itself*.

Best regards,
Ivan
