### ISSUE TITLE
jstree overrides default iOS Safari behaviour of :hover

### ISSUE THREAD

**Issue by brendon** [vakata/jstree#954]
Hi there, I've been having a problem where the jstree code is interfering with the way that iOS Safari executes the CSS :hover behaviour. I have a drop down menu that's adapted for touch screens. If a user taps on a `<li><a>` in the menu that contains children, then normally the browser would toggle the :hover view. If the user touches again on the same `<li><a>`, the browser will go to that link.

For some reason when I add the jstree library, this is overridden and the browser goes straight to the link after it executes :hover. This happens on pages where the jstree library is loaded but where it isn't used at all on the page.

I've had a look through the code but can't see any obvious places that this behaviour is being enabled.

**Comment by brendon** [comment]
I've done some testing and found this code to be the culprit:

```
$(function () {
		$(document)
			.on('touchmove.vakata.jstree', function (e) {
				if(cto && e.originalEvent && e.originalEvent.changedTouches && e.originalEvent.changedTouches[0] && (Math.abs(ex - e.pageX) > 50 || Math.abs(ey - e.pageY) > 50)) {
					clearTimeout(cto);
				}
			})
			.on('touchend.vakata.jstree', function (e) {
				if(cto) {
					clearTimeout(cto);
				}
			});
	});
```

**Comment by vakata** [comment]
No, they should be on the document, but those two are `touchmove` and `touchend`, which should not interfere with :hover, that is very odd. Besides - I am not doing anything to the event - not preventing or stopping propagation.
I will read up on this but from the looks of it I am not sure what I will be able to do - I hope there is some info on this (Apple is not very open unfortunately).

**Comment by vakata** [comment]
The most accurate description I could find was in apple's docs and in this opinion: http://stackoverflow.com/questions/2741816/is-it-possible-to-force-ignore-the-hover-pseudoclass-for-iphone-ipad-users/18912168#18912168
Unfortunately the above code does not change the content in any way - it only clears a timeout. However this may be affected by other plugins - may I see your full config, or is simply adding `jstree.js` to the page enough? Sorry for asking those questions but currently I do not have an iOS device at hand.
From what I see - those events are from the contextmenu plugin, which means you are right - they can be scoped to the container. I will try this and commit a change, if that does not work we'll debug further.

**Comment by vakata** [comment]
Let me know if this does not solve the issue and I will reopen.

**Comment by brendon** [comment]
Hi Ivan, thanks for following this up for me. Your changed fixed the problem! :)

Basically iOS simulates a hover if the click results in a change in the visual aspects of the element. So in my case, clicking the A changes its colour, among other things. iOS then cancels the click event. Clicking one more time will trigger the click instead.

I'm not sure why working with timeouts would prevent this from working, but Apple hey?

Thanks again for fixing this so quickly. There's one other library I use that also triggers this behaviour, so onwards and upwards!
