### ISSUE TITLE
using select and text boxes with jstree - grid

### ISSUE THREAD

**Issue by tharasp** [vakata/jstree#956]
Hi,

I am using jstree-grid for collecting prices for a set of items in database. I used alternate json for for rendering jstree:
jsonData = [{"id":1,"text":"Materials and varieties", "parent":"#","to_unit_name":"Kg","to_data_needed":"N","to_unit_id":"","to_active":"Y",},
{"id":2,"text":"Bricks","parent":"1","to_unit_name":"ml","to_data_needed":"N","to_unit_id":"","to_active":"Y"}, {"id":3,"text":"Class(Country burnt)(high quality)","parent":"1", "to_unit_name":"1000 Nos", "to_data_needed":"Y","to_unit_id":9,"to_active":"Y"}];

My grid rendering part goes like this:

"grid": {
"columns": [{width: 50, header: "Items", title:"_DATA_"},
 {width: 30, header: "Unit", value:function(node){return(node.to_unit_name);}, title: "Default Unit"},
{width: 30, header: "Shop1 Price", title: "Price from Shop1", value:0}, 
{width: 30, header: "Shop2 Price", title: "Price from Shop2", value:0}],
 "width": 25,
"contextmenu":true,
"resizable":true
}

But only jstree item list displayed in grid and values for columns 2, 3 and 4 not showing. 

Also, I want to know whether i can place select and text boxes in jstree-grid.

Thanks.
![untitled](https://cloud.githubusercontent.com/assets/10546159/5756974/08b1de26-9cdc-11e4-8809-ed1422e593f9.png)

**Comment by vakata** [comment]
Please talk to the grid plugin author - it is a third party plugin, I am not the author and can not support it.
Here is the jsTree grid plugin repo: https://github.com/deitch/jstree-grid/
