### ISSUE TITLE
jstree preselect node and open all parents needed

### ISSUE THREAD

**Issue by blpraveen** [vakata/jstree#957]
I am trying to fix the problem on sliverstripe cms. This issue does not occur on small number pages. it occurs when there is lot of pages and all the pages and subpages does not load initially.
Consider a page having  5 depths and I am trying to open a page directly on depth 5. 
All the parent pages are not loaded, initially, it checks depth 5 node exits if not exists it calls ajax to get the node. 
On success it checks the ParentNode exits if not it calls load_node. The problem is here it is not getting all the parents nodes 

      if(nodeData.ParentID && !self.find('li[data-id='+nodeData.ParentID+']').length) {
        self.jstree('load_node', -1, function() {
		newNode = self.find('li[data-id='+nodeId+']');
		correctStateFn(newNode);
	});
	} else {
		self.createNode(nodeData.html, nodeData, function(newNode) {
			correctStateFn(newNode);
		});
	}

What does the  'load_node' does and what  values need to pass in the arguments to get all the parent nodes?

Please help
Thanks
B L Praveen

**Comment by vakata** [comment]
Here is what `load_node` does: http://www.jstree.com/api/#/?q=load_node&f=load_node%28obj%20[,%20callback]%29

As for your question I believe the most efficient way to select a node that is not yet loaded is to dispatch an AJAX request manually to get an array of all the node's parents' IDs and the pass that array to `load_node` along with a callback, once loading is done - the callback will be executed.
```js
$.get('/path/to/get/parents', { 'id' : NODE_ID_TO_SELECT }, function () {
  // data is an array like this one: [ '1', '5', '34' ] - all the IDs of the parents of NODE_ID_TO_SELECT
  $('#tree').jstree(true).load_node(data, function () {
    this.select_node(NODE_ID_TO_SELECT);
  });
});
```
That is all.

**Comment by blpraveen** [comment]
load_node does not loads the parents

self.jstree('load_node', nodeData.ParentIDs, function() {
	newNode = self.find('li[data-id='+nodeId+']');
	correctStateFn(newNode);
});

**Comment by vakata** [comment]
It loads the parents - that is the whole purpose of the function. I did not say the parents will be in the DOM however. You are obviously expecting they are in the DOM?

Please do not use the DOM to work with the tree - jstree provides all necessary functions, and it only keeps visible nodes in the DOM.

As I said in the previous post - use `select_node` with the node ID to reveal and select it. If you want to just reveal it - use `open_node` or `_open_to`.

Best regards,
Ivan
