### ISSUE TITLE
How to open last edited node?

### ISSUE THREAD

**Issue by Gandalf0007** [vakata/jstree#960]
I have a jsTree working like I want it. The problem is how to return to the last modified node? For example, when I upload files to the node I would like to have that same node opened and selected after reload of a tree. I have tried all possible ways ,but non made a progress. Can you please help me with an example?

**Comment by vakata** [comment]
I am not sure what you mean.
1) If you are using refresh, provided the nodes have the same ID both opened nodes and selection will be restored.
2) If you mean after a full page refresh - just include the `state` plugin.

Best regards,
Ivan

**Comment by Gandalf0007** [comment]
I have a tree that is constructed from backend(c#) and all nodes are in
state 'closed' using c# code. This is required for lazy loading to work
correctly and the whole tree would be too big to display. This function is
called every time the tree is redrawn. Then, I have an event 'select_node'
that marks the node every time it is clicked so that I know the last
clicked node ( I put a custom attribute on it, selector on id that is disk
path doesn' t work) After that redraw is called which constructs tree using
the same function specifed  at the beginning of this passage
Thank you
Ivan
