### ISSUE TITLE
Adding nodes by button and IE doesn't display node text

### ISSUE THREAD

**Issue by lkurylo** [vakata/jstree#962]
I have a tree to which I add, rename and remove nodes by buttons.
On Firefox and Chrome there is no problem, but on IE there are two problems when the buttons are clicked fast one by one.

When the Add group button is clicked, then nodes are visible in the tree, but not for all nodes their text is displayed.
With the Rename node button is clicked on node few times one by one, then node loses the selected to edit text.

Simple code to reproduction:
http://jsfiddle.net/q0rfrbcx/2/

That'a how it looks like on my IE11:
![jstree-ie11](https://cloud.githubusercontent.com/assets/744244/5801049/d74c345e-9fe6-11e4-833b-941b75cb43d2.png)

**Comment by vakata** [comment]
Thanks for the demo and sorry for taking so long to reply. I will fix this ASAP.

**Comment by lkurylo** [comment]
"When the Rename node button is clicked on node few times one by one, then node loses the selected to edit text."

This is really fixed. Thanks.
But the second problem with adding new nodes still occur.
