### ISSUE TITLE
Cannot read property 'dots' of undefined

### ISSUE THREAD

**Issue by Silverlay** [vakata/jstree#966]
Having strange issue in Chrome v.39.0.2171.95 m

include jQuery
include jsTree
include style

<div class="col-md-12" id="unitTreeEx">
</div>

initializing as ...

        $("#unitTreeEx").jstree({
            "core": ["Child 1", { "id" : "demo_child_1", "text" : "Child 2", "children" : [ { "id" : "demo_child_2", "text" : "One more" }] }],                
            "checkbox": {
                "keep_selected_style": false
            },
            "plugins": ["checkbox", "wholerow"]
        });

On init of jsTree catching error "Cannot read property 'dots' of undefined"
at init.jstree
At line 798: 						this._data.core.themes.dots			= s.dots;

**Comment by vakata** [comment]
Your config is wrong, data should be supplied in the `core.data` property. In your case:
```js
        $("#unitTreeEx").jstree({
            "core": {
                 "data" : ["Child 1", { "id" : "demo_child_1", "text" : "Child 2", "children" : [ { "id" :  "demo_child_2", "text" : "One more" }] }]
            }, 
            "checkbox": {
                "keep_selected_style": false
            },
            "plugins": ["checkbox", "wholerow"]
        });
