### ISSUE TITLE
Copy and Paste of a tree node causes children nodes to appear under both original node and target node

### ISSUE THREAD

**Issue by mohankumaranna** [vakata/jstree#968]
Hi, 
Thanks for sharing this great plugin.  

I am experiencing a problem and do not find a solution in the issues list, so writing this issue...I have a tree structure with checkbox enabled as shown below
![screenshot from 2015-01-24 16 54 05](https://cloud.githubusercontent.com/assets/8091312/5887249/e3e66ec0-a3ea-11e4-97b6-79a6192ea908.png)

on copy and paste of selected nodes, I see children of the selected node appears under both original node and target node as shown below
![screenshot from 2015-01-24 16 56 23](https://cloud.githubusercontent.com/assets/8091312/5887254/17667ace-a3eb-11e4-9b2b-30374d8de747.png)

Am I missing any settings?.  

Slightly different problem is noticed in Cut and Paste operations too.

Thanks. -Mohan

**Comment by vakata** [comment]
Thank you for reporting - it should be fixed now (both with `contextmenu` and `dnd` plugins). If you are calling `copy_node` or `move_node` manually, make sure you call them with `get_top_selected` instead of `get_selected` as parameter.

Best regards,
Ivan

**Comment by mohankumaranna** [comment]
Thanks Ivan.
