### ISSUE TITLE
Error in copying certain functions

### ISSUE THREAD

**Issue by mark1917** [vakata/jstree#970]
Hello.

There is an error in copying the nodes of the tree when you change the settings in the file class.tree.php.

I have a field in a table is called nodes_id instead of id (by default), if I pass in options:

'structure'	=> array( 
'id'	=> 'nodes_id',
'left'	=> 'lft',
'right'	=> 'rgt',
'level'	=> 'lvl',
'parent_id'	=> 'pid',
'position'	=> 'pos'

Tree is not working and not working up: 'data2structure'	=> 'data_nodes_id',

**Comment by vakata** [comment]
Sorry, the php scripts serve demo purposes only and are not supported, I really can't spend time looking into them. I will have a look when I can and let you know, but this is not related to jstree (which is the client-side lib only) so I will close this ticket.

Btw, using the error log you will probably track this error easily - it could be a hard coded `id` field somewhere.

Best regards,
Ivan
