### ISSUE TITLE
jstree async data load

### ISSUE THREAD

**Issue by Gandalf0007** [vakata/jstree#971]
Can you please provide me with a full asynchronous loading example? This would include backend (if possible in C# ASP.NET MVC) and frontend with jsTree function that uses core 'data' with  'url' and 'data'. I have looked for this kind of an example for the past two days, but your home page also does not have a fully working example as you load data through predefined JSON files - see this taken from your site:

'url' : function (node) {
        return node.id === '#' ?
          'ajax_demo_roots.json' : 'ajax_demo_children.json';
      },
      'data' : function (node) {
        return { 'id' : node.id };
      }

So, if you fetch ajax_demo_roots.json for example you get:
[
{ "id" : "demo_root_1", "text" : "Root 1", "children" : true, "type" : "root" },
{ "id" : "demo_root_2", "text" : "Root 2", "type" : "root" }
]

How does mapping from backend to jsTree node work? How are 'url' and 'data' used in that context?
Thank you

Ivan

**Comment by vakata** [comment]
The principle is the same (static files or not). 

Still, did you have a look at the demos section - it has a full DB example (no predefined files, but a live lazy-loaded tree which you can edit): 
http://www.jstree.com/demo/ (last example).

The code for this example is in this very repo: 
https://github.com/vakata/jstree/blob/master/demo/sitebrowser/index.php#L108

You can read an explanation here: 
https://github.com/vakata/jstree#populating-the-tree-using-ajax-and-lazy-loading-nodes
And here: 
http://www.jstree.com/docs/json/ ("Using AJAX" section)

It is also explained in the groups page a few times, for example in this unrelated question: https://groups.google.com/d/msg/jstree/BbBe5Zwb7Yo/8ibwkV33y00J

If you are having a hard time with C# and .net - google your problem - there are a few sites that offer jstree tutorials with .net

Best regards,
Ivan
