### ISSUE TITLE
doubled default text on new created node in edit mode

### ISSUE THREAD

**Issue by lkurylo** [vakata/jstree#972]
After fixing this bug https://github.com/vakata/jstree/issues/962 now there is another one.

When you try to add a new node as a child, then the node name is doubled in edit mode:
![jstree](https://cloud.githubusercontent.com/assets/744244/5936410/a46af34a-a6e4-11e4-8e7a-dfe8e9bdea7a.png)

Reproduction: http://jsfiddle.net/q0rfrbcx/5/

**Comment by vakata** [comment]
Thanks for reporting.

Best regards,
Ivan
