### ISSUE TITLE
how to use the file icon from default theme?

### ISSUE THREAD

**Issue by SamsonWorld** [vakata/jstree#974]
In the default, the icon is the folder icon in the default theme.
![32px](https://cloud.githubusercontent.com/assets/7642685/5956408/9602a60e-a7e8-11e4-8d5e-c4921ea3c501.png)

but i want to use the last file icon, how to define it?

**Comment by Muchiachio** [comment]
Hi @SamsonWorld 
You just need to override background image position for js tree node. It would look like this:
```
.jstree-default .jstree-themeicon {
    background-position: -101px -70px;
}
```

**Comment by vakata** [comment]
You can use the special jstree-file class, just set the icon property in your JSON to:
```json
...
"icon" : "jstree-file",
...
```

You can also use it in the types plugin too.

Best regards,
Ivan
