### ISSUE TITLE
demo (file browser)  doesn't work DnD on IE8

### ISSUE THREAD

**Issue by ntani** [vakata/jstree#975]
Hello.
It's nice library and great demo(file browser) on Chrome.
but , I noticed  demo(file browser) doesn't work DnD well  on IE8 .
I try to move a file to another folder , but the file doesn't move.

My Environment is IE8 on Win7(VirtualBox)
VirtualBox Image is provided by MS
(https://www.modern.ie/en-us/virtualization-tools)

demo url is below
http://www.jstree.com/demo/

**Comment by vakata** [comment]
It depends on what you are trying to move and where - there are some restrictions in the demo (as well as a few bugs with the virtual filesystem, which are external to jstree). I can assure you it works - I just tested in IE8 (there are a few glitches with the striped background though, which I will have a look at when I get the time).

Best regards,
Ivan

**Comment by ntani** [comment]
Hi.
Thank you for message and test in IE8 .
I tried  to make stripes option false , but , Dnd still  doesn't still work well in IE8 .
Do you have any other hint ?

**Comment by vakata** [comment]
Hi again, DND has nothing to do with the stripes option - Ijust mentioned it.
Please define what "does not work well" means? For example - do you get JS errors, does the drag start, do you see all UI elements (dragged node, marker, check or red cross)? Tell me what is different from Chrome, as I can not reproduce any problem.

**Comment by ntani** [comment]
Hello.
Thank you for message.
I apologize I 'm not good at English and  I didn't explain well.
 "DnD does not work well" means moved file don't appear .- I try to move a file to another folder , but the file looks doesn't move.
on Chrome , it works great.

**Comment by vakata** [comment]
I will see if I can reproduce, but keep in mind it can be related to the actual backend code, not jstree itself.
