### ISSUE TITLE
Copy/Move of multiple nodes doesn't work?

### ISSUE THREAD

**Issue by zeitiger** [vakata/jstree#977]
Hi,

I'm not sure if this more a feature request or a bug.

core.multiple is per default true

So if I enable dnd on a tree and select multiple nodes and drag them to another node only the node drops where my mouse cursor starts, the rest keep place and be selected.

Is that as designed or is that a bug?

Best regards and great work
David

**Comment by vakata** [comment]
This is a bug that is already fixed in the latest code in this repo. Thanks for reporting.

In the fixed version you can also control the behavior: http://www.jstree.com/api/#/?q=dnd&f=$.jstree.defaults.dnd.drag_selection

Best regards,
Ivan

**Comment by zeitiger** [comment]
Is this fixed in 3.0.9 or above?

**Comment by vakata** [comment]
Above 3.0.9 (the code here in the repo). If you want to wait for a release it will be fixed in 3.0.10.
