### ISSUE TITLE
open_node class

### ISSUE THREAD

**Issue by premhameed** [vakata/jstree#978]
$(function() {
			$("#container").jstree({
			  "types" : {
			    "default" : {
			      "icon" : "siteicon"
			    }
			  },
			  "plugins" : ["types"]
			});
$('#container').jstree('open_node', ".expand-menu");
});
I am trying to expand .expand-menu class. but it only expanding the first node only. any idea?

**Comment by vakata** [comment]
The `open_node` function deals with IDs or DOM objects or jQuery collections, not selectors.
You can try:
`$('#container').jstree('open_node', $('.expand-menu'));

Best regards,
Ivan

**Comment by premhameed** [comment]
Thanks Ivan
