### ISSUE TITLE
Hello sir....

### ISSUE THREAD

**Issue by moorthimnk** [vakata/jstree#979]
i need following data json can you tell how to add my local drive directories into tree using json..
![image](https://cloud.githubusercontent.com/assets/10783084/6001146/6273dc78-ab0c-11e4-91c4-b167d2ac99f0.png)

**Comment by vakata** [comment]
Please have a look at the demo - the full source is here on github, there is nothing more I can provide.

**Comment by moorthimnk** [comment]
which data loaded into tree jstree.json or somethings else sir can you tell me...

**Comment by vakata** [comment]
It is all in the source code - data is lazy loaded, not a static file, and is served by a PHP script, which reads the file system.
