### ISSUE TITLE
deselect_node event send a faulty selected nodes list ...

### ISSUE THREAD

**Issue by mohierf** [vakata/jstree#980]
I created a three levels tree : 
```
 Level 1
   Level 2
     Level 3 - 1
     Level 3 - 2
     Level 3 - 3
```

I binded to 'select_node' and 'deselect_node' events : 
```
      .bind('select_node.jstree', function(event, selectedNodes) {
      })
      
      .bind('deselect_node.jstree', function(node, selectedNodes) {
      })
```

When I select a 'Level 2' node the selectedNodes parameter gives me a list including all 'Level 3' nodes; but when I deselect this same node, I get the same list ... but nodes are not any more selected in the tree.

**Comment by vakata** [comment]
You are obviously using the checkbox plugin? Please share your config next time you submit a bug. If you are this behavior is normal - when using the checkbox plugin with the three_state option enabled, selecting and deselecting nodes cascades up and down. Also keep in mind is better to used the `changed.jstree` event. If I misunderstood - please clarify and I will reopen the ticket.

Best regards,
Ivan

**Comment by mohierf** [comment]
Hello,
I am using checkbox plugin, indeed ...

What is strange is that my leaf nodes are no more selected but are still in the selected nodes array.

I copy my configuration and a console log screen capture after I selected each one of the leaf nodes and then unselected their parent node. As you will see in the screen capture the tree is whole unselected but I still have a selected nodes array ... where as none are selected in the tree.

```
    var jsTreeData = new Array();
    jsTreeData.push( { "id" : 'entity_95', li_attr: { "entities_id" : 95 }, "parent" : "#", "text" : "Level 1" } );
    jsTreeData.push( { "id" : 'entity_96', li_attr: { "entities_id" : 96 }, "parent" : "entity_95", "text" : "Level 2" } );
    
    $('#hostsTreeTest')
      .jstree({ 
        "core" : {
          "check_callback" : true,
          "data" : jsTreeData
        }
        , "plugins" : [ 
          "checkbox",
          "sort"
        ]
        , "checkbox": {
            "three_state" : true
          , "whole_node": true
        }
      })
      
      .bind('ready.jstree', function(e, data) {
        var nodeID = $('#hostsTreeTest').jstree().create_node('entity_96', { "id": 'kiosk_1', "type": "host", "text": 'Level 3-1' }, "last", function (node) {
          $(node).attr("host_name", 'Level 3-1');
        });
        var nodeID = $('#hostsTreeTest').jstree().create_node('entity_96', { "id": 'kiosk_2', "type": "host", "text": 'Level 3-2' }, "last", function (node) {
          $(node).attr("host_name", 'Level 3-1');
        });
        var nodeID = $('#hostsTreeTest').jstree().create_node('entity_96', { "id": 'kiosk_3', "type": "host", "text": 'Level 3-3' }, "last", function (node) {
          $(node).attr("host_name", 'Level 3-1');
        });
        
        $('#hostsTreeTest').jstree().open_node('kiosk_1');
      })
      
      .bind('select_node.jstree', function(event, selectedNodes) {
        if (debugJs) console.debug('Selection :', selectedNodes.selected);
      })
      
      .bind('deselect_node.jstree', function(node, selectedNodes) {
        if (debugJs) console.debug('Deselection :', selectedNodes.selected);
      })
```
![image](https://cloud.githubusercontent.com/assets/2932687/6014550/73668788-ab66-11e4-97dd-03fc11019e55.png)

**Comment by vakata** [comment]
Hi, I see what you mean - this is why I suggested using the `changed.jstree` event. 
Deselect is triggered whenever a single node is deselected, the checkbox plugin picks up that event and reacts on it to apply cascading, so when you process that same event the checkbox plugin has not yet made its changes (those changes however are available in the `changed.jstree` event).

Sorry for the inconvenience, I will try to make this clear in the docs.

Best regards,
Ivan

**Comment by mohierf** [comment]
Thanks. When using ```changed.jstree```everything is ok !
