### ISSUE TITLE
Checkbox enable,disable, select, deselect in jstree 

### ISSUE THREAD

**Issue by tharasp** [vakata/jstree#982]
Thanks for the wonderful plugin. I am using it in my project along with jstreegrid. 

I could use a json generated from database for rendering jstree and jstreegrid. Now, based on values of some keys in json, I want to enable/disable and select/deselect checkboxes in jstree. Please have a look at http://jsfiddle.net/tharas/gw9ch970/61/.

A typical node in my json looks like
`{
        "id": 3,
        "text": "Class(Country burnt)(8\" 4\" 4\")(high quality)",
        "parent": "2",
        "data": {
            "item_id": 3,
            "mal_item_name": null,
            "data_needed": "Y",
            "def_unit_id": 9,
            "col_unit_id": null,
            "shop1_price": 100,
            "shop2_price": null,
            "remarks": null
    }`

For each node, i have the following requirements:
if data_needed == 'Y', enable checkbox (entire row), other wise disable checkbox(entire row)
if shop1_price != null, select checkbox, other wise deselect checkbox

With so many questions and answers found through google search, I could not decide which ones are applicable for latest version 3.0.9. So please provide solution or point to relevant links.

Thanks.

**Comment by vakata** [comment]
jstree uses the `state` key for this. Please read here:
https://github.com/vakata/jstree#the-required-json-format (you need `selected` and `disabled`)

If you have any questions specific to the jstreegrid plugin - please ask the plugin author (it is a 3rd party plugin - kudos to the author).

Best regards,
Ivan
