### ISSUE TITLE
AJAX, jstree, and check_callback doesn't work

### ISSUE THREAD

**Issue by wrustel** [vakata/jstree#984]
$('#treeDiv')
.jstree({
"core" : {
"animation" : 0,
"check_callback" : true,

"themes" : { "stripes" : true },
},
"checkbox": {
"keep_selected_style": true
},
"plugins" : [ "contextmenu","wholerow","types","dnd","state" ]

}).jstree("open_all");

this is how I have defined the jstree div.

I debugged the function check:

check : function (chk, obj, par, pos, more) {
obj = obj && obj.id ? obj : this.get_node(obj);
par = par && par.id ? par : this.get_node(par);
var tmp = chk.match(/^move_node|copy_node|create_node$/i) ? par : obj,
chc = this.settings.core.check_callback;
if(chk === "move_node" || chk === "copy_node") {
if((!more || !more.is_multi) && (obj.id === par.id || $.inArray(obj.id, par.children) === pos || $.inArray(par.id, obj.children_d) !== -1)) {
this._data.core.last_error = { 'error' : 'check', 'plugin' : 'core', 'id' : 'core_01', 'reason' : 'Moving parent inside child', 'data' : JSON.stringify({ 'chk' : chk, 'pos' : pos, 'obj' : obj && obj.id ? obj.id : false, 'par' : par && par.id ? par.id : false }) };
return false;
}
}

the variable chc allways have the value false, dont matter what I do, allways have the value false. Even swaping the value manually with the debugger still not working. Dont draw nothing, dont refresh nothing, just doesnt work.

Im trying to upload the tree with info from a database each time I click in one node, but doesnt work. never works. I just did copy paste from your examples, I debugged, also I checked all examples in internet but still not working. Can I have a good example about how to redraw the nodes from a data base message with AJAX? because I posted it in my last post and you closed it

**Comment by vakata** [comment]
Please keep the discussion in the original thread - if there is a reason - I will reopen the issue. There are thousands of users which use this component - trust me - there is nothing wrong with such a basic functionality like node creation. 
If you post a demo I will help you debug, but this is not a valid ticket. Once again - keep the discussion in the original thread.
