### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by elpix69** [vakata/jstree#985]
Uncaught TypeError: undefined is not a functionjstree.js:260 (anonymous function)jstree.js:11 instance_counterjstree.js:13 (anonymous function)
jstree.js:112 Uncaught TypeError: undefined is not a function

**Comment by vakata** [comment]
Sorry, I will need more steps to reproduce this - obviously all demos on the site are working, so please share your config and steps to reproduce (if needed).

**Comment by vakata** [comment]
I am closing this since I cannot reproduce, there is no function on line 260 and due to no further information. If you provide more info I will reopen the ticket.
