### ISSUE TITLE
Bug in state plugin when checkbox tie_selection is false

### ISSUE THREAD

**Issue by eDitore** [vakata/jstree#988]
in reference to issue #987
sorry I mean tie_selection is false. I have modified your example http://jsfiddle.net/DGAF4/276/ and and I have the same problem state plugin stores only first tree state and do nothing more.

**Comment by vakata** [comment]
Thanks for the clarification, here is an updated fiddle where I was able to reproduce the problem: http://jsfiddle.net/DGAF4/326/ (maybe you did not click on Update before pasting the link here - it was still my original example).
I am on it, thanks. I will have this fixed in a few hours.
