### ISSUE TITLE
jsTree 1.0 state example?

### ISSUE THREAD

**Issue by IvanDjapic** [vakata/jstree#989]
Can I get a working example for 1.0 jsTree that successfully solves state problem? I am using cookies plugin but my jsTree 1.0 is not showing the node that was last modified/created after redraw()? Just don't tell me to use 3.0 version as the whole project is built using 1.0 version.

**Comment by vakata** [comment]
Sorry, v.1 is a few years old and is no longer supported. Feel free to browse around the old code - here is the cookies plugin example: http://old.jstree.com/documentation/cookies
