### ISSUE TITLE
How to refresh only selected node, not the whole tree?

### ISSUE THREAD

**Issue by IvanDjapic** [vakata/jstree#990]
I have written a small "GIT - like" application for source control using jsTree 1.0.
All is solved and working except returning  to the last modified/deleted/created node.  I plan to do this by using refresh() function on the node where the change took place as currently I call refresh() on the whole tree. Can you give me an example of "partial" refresh()? Thank you

**Comment by vakata** [comment]
Sorry, I can not give you an example, v.1 is no longer supported, and I have not looked at those sources in over a year, sorry, I really can't be of any help.

Best regards,
Ivan
