### ISSUE TITLE
TypeError: Cannot read property 'state' of undefined at Object.$.jstree.core.load_node

### ISSUE THREAD

**Issue by npearson72** [vakata/jstree#991]
I'm getting `TypeError: Cannot read property 'state' of undefined at Object.$.jstree.core.load_node` when calling `refresh_node()`

What's strange is that it always works the first 2 times, but the 3rd time it's called I get the error.

After that, it works on every other call, but errors out on each call between.

Any ideas?

**Comment by vakata** [comment]
How can I reproduce this error - what methods are you calling. Keep in mind that if you are using the flat JSON format, and if your structure is broken (a "parent" reference to a non-existing node) you might get a similar error.
So please let me know what methods (and with what data) you are calling so that I can reproduce and fix this.

Best regards,
Ivan

**Comment by npearson72** [comment]
I'm calling the following method on my instance:

`<my jstree element>.jstree().refresh_node(<my node or node.id>)`

Here is a sample of the data I'm working with:

`{"id":6,"title":"Computers \u0026 Sport","description":"Eligendi quae eum distinctio. Animi similique et nam ut. Excepturi facere aut quo. Aut sed et illo beatae occaecati dolorum excepturi. Velit recusandae libero totam. Sint sit autem ducimus et saepe. In quis repellat nulla incidunt ut officia et. Temporibus maxime quae amet. Est dolor unde et. Quos aliquam labore quae.","position":1,"tenant_id":1,"created_at":"2015-02-07T05:36:38.921Z","updated_at":"2015-02-08T02:17:12.757Z","parent_id":null}`

Does this help or can I provide more info?

**Comment by vakata** [comment]
This looks like `v.1` data - sorry, but that is not supported, if you are using `v.3` then this data is not in the right format (for one - it lacks a `text` property).
If I misunderstood and you are using v.3 - please provide your full config, and some valid sample data and I will reopen the ticket (a demo of the problem will be the best possible scenario of course).

Best regards,
Ivan
