### ISSUE TITLE
Unable to cancel the opening of a node

### ISSUE THREAD

**Issue by AndrewWhitaker** [vakata/jstree#993]
It does not appear possible to cancel the `before_open` event that jstree raises. It would be useful to prevent the user from opening nodes under certain circumstances.

**Comment by vakata** [comment]
Sorry, none of the events jstree raises are meant to be canceled. If some setting is meant to be highly customizable and user controllable it can be set to a function.

Events are just informative and the API provides a lot of ways for you to react. `before_open` simply means that the node is already loaded, it probably is in the DOM and is about to be shown. So you can easily attach to the `open_node` event and close the node (the animation probably wouldn't have started anyway).

Best regards,
Ivan
