### ISSUE TITLE
Open Node while using lazy loading

### ISSUE THREAD

**Issue by dehlen** [vakata/jstree#994]
Hello,

I am using lazy loading to display my jstree since the tree can be really huge. Now i wanted to implement the ability to select the recent 10 nodes the user expanded. I am saving the nodes in an array and can select them, so everything looks fine. 

Unfortunately since I am using lazy loading i only can open nodes which are already displayed. 

Is there anyway If the user chooses one of the last 10 nodes from the select box, to navigate the tree to this node and load all parent nodes on the fly ?

Kind Regards,
David

**Comment by vakata** [comment]
No, jstree has no idea that a node exists if its parent is not loaded. That is like asking your OS to search a flash drive that you have not yet connected. 

Maybe the state plugin will work for you? 

Also - the `_load_nodes` function accepts an array of IDs to load (and the IDs may not be currently present), so if you know the parent IDs of the node you want to select you can easily call:
```js
$('#tree').jstree(true)._load_node(['parentID1', 'parentID2', 'parentID3'], function () {
  this.select_node("CHILD_ID_OF_PARENTID3");
});
```

Best regards,
Ivan

**Comment by dehlen** [comment]
I tried that but it is not working for me. Here is my setup:

For example i have a node with id "/branches" and one which is a child with id "/branches/Bug".
So I am trying your code like:
```javascript 
$('#tree').jstree(true)._load_node(['/branches'], function () { //Also tried with # too
  this.select_node("/branches/Bug");
}); 
```

I receive an error like this: ```https://localhost:8443/ETLTool/serverInterface.jsp?childsForId=undefined 500 (Internal Server Error) ```

This is how i initialize my jstree : 
```javascript
	$("#treeview").jstree({
		"plugins": ["types", "wholerow","state"],		
		"types": {
			"folder": {
				"icon": "./images/folder.png"
			},
			"file": {
				"icon": "./images/file.png"
			}
		},


		"core": {
			"data": {
				"url": function(node) { 

					if($("#treeDatasourceSelect").val() == "SVN") {
						if (node.id === "#") {
							return showOnlyScripts ?  "serverInterface.jsp?getRootScripts=YES" 
									: "serverInterface.jsp?getRoot=YES";

						} else {
							console.log(node);
							return showOnlyScripts ? "serverInterface.jsp?scriptsForId=" + node.id
									:"serverInterface.jsp?childsForId=" + node.id;
							
						}
					}
					else {
						if (node.id === "#") {
							return"serverInterface.jsp?explorerRoot=YES";

						} else {
							return "serverInterface.jsp?explorerChildsForId=" + node.id;
							
						}
					}
				},
				"data": function(node) {
				
						return {
							"id": node.id
						}
					
					
				}
			}
		}
	});
	
```
