### ISSUE TITLE
Open Node while using lazy loading(jsTree 1.0-rc3 version)

### ISSUE THREAD

**Issue by AjayBarot-BTC** [vakata/jstree#995]
I am using jstree 1.0-rc3 version (jquery 1.8.3) to display the tree by lazy loading .
I tried this way:

$('#container').jstree({
    'core' : {
        'data' : {
            "url" : "//www.jstree.com/fiddle/?lazy",
            "data" : function (node) {
                return { "id" : node.id };
            }
        }
    }
});

But some how I can get the Tree.
Reference : https://github.com/vakata/jstree#populating-the-tree-using-ajax-and-lazy-loading-nodes

**Comment by vakata** [comment]
The docs are for v.3, v.1 is no longer supported, sorry.

**Comment by AjayBarot-BTC** [comment]
Hey I am using jstree with backbone-js with marionette-js so we can handle view by composite-view.
I pass the json data from collection (router). Here I want to handle 500 nodes (3 parent node and other child node). I get kill page error in showing 500 nodes. 
jquery - 1.8.3
jstree - 3.0.9
Here is my code:

class @Demos.DemoTreeView extends Support.CompositeView
  initialize: ->
    _.bindAll this, "renderDemos"

  render: ->
    $(@el).
      bind("move_node.jstree", @nodeMoved).
      bind("loaded.jstree", @renderDemos).
      jstree(plugins: [ "themes", "html_data", "sort", "dnd" ]).
      data("model", @collection.build(id: null))

  renderDemos: ->
    listView = new Demos.DemoListView(
      el: @el
      tree: @el
      collection: @options.collection.roots()
    )
    @renderChild listView

So Please tell me how can I improve the performance of 500 nodes.
Thanks
Ajay

**Comment by vakata** [comment]
Your setup looks like v.1 code, are you sure are using v.3? What is a kill page error?

I test each release with a flat and nested list, both consisting of 30.000 nodes so I am absolutely sure jstree can handle 500 nodes, there must be something wrong with your script. 

Unfortunately I am not familiar neither with backbone, nor the way you are creating the tree and binding the data. Still, I can assure you jstree works fine with thousands of nodes, so any hickup with 500 nodes must be related to something you are doing or the way you are creating the instance and feeding the data.

**Comment by AjayBarot-BTC** [comment]
Thanks for a reply @vakata ,
kill page == Page Unresponsive error

Hey Is this proper code for creating node. Version 3.0 ,
@el = $(@options.tree).jstree("create_node", $(@options.container), "last", node).data("model", @model).data("parent", @model.activity)

@el = selector 

Regards,
Ajay Barot

**Comment by vakata** [comment]
No, this is not a proper way to populate the tree - please read the docs either on jstree.com or in the root of this repo. Create node should be used when a user is creating a node, populating the tree with data should not be done with `create_node` that would be way too slow.

My guess is you will need to set core.data to a function, but still - read up on all the options, take a look at the demos and decide.

Best regards,
Ivan

**Comment by AjayBarot-BTC** [comment]
Hi Ivan , 
  Can we use real_checkboxes in jsTree 3.0.9?.

buildCheckboxOptions: (options) ->
    opts =
      real_checkboxes:       true
      real_checkboxes_names: (n) =>
         console.log "In real checkboxes_names function"
        [options.checkboxNames, @demoID(n)]

    _.extend(@checkbox, opts)

See my console in real_checkboxes_names function. It does not allowed to enter real_checkboxes_names function .

Please guide me.

Thanks & Regards,
Ajay

**Comment by vakata** [comment]
No, there is no `real_checkboxes` option in v.3 - the way the tree is rendered (only opened nodes are in the DOM) make the real checkboxes impossible. 
You can use the `changed.jstree` event and `get_selected` / `get_top_selected` / `get_bottom_selected` functions to populate a hidden field (or fields) in your form.

**Comment by AjayBarot-BTC** [comment]
Thanks again @vakata  !

**Comment by AjayBarot-BTC** [comment]
Hey @vakata ,
        I have problem change_state.jstree. Here is my code: 
@$el.bind("change_state.jstree", groupsChanged())

Can you please tell me which event now i should use for version 3 ? 

I see this issue regarding change_state.jstree event
https://github.com/vakata/jstree/issues/456

Thanks & Regards,
Ajay

**Comment by vakata** [comment]
Sorry, no idea what `change_state` used to do. Take a look at all events and decide which one you need:
http://www.jstree.com/api/#/?q=event

**Comment by vakata** [comment]
Btw, there is a plugin to replace the icons with real checkboxes: https://github.com/vakata/jstree/blob/master/src/misc.js#L45
You can add the source for this plugin. Just keep in mind the change is visual only, if used inside a form it will probably not produce the results you want.

Cheers,
Ivan
