### ISSUE TITLE
#994 Issue trying to open parent and children nodes while using lazy loading

### ISSUE THREAD

**Issue by dehlen** [vakata/jstree#996]
Hello this issue is referring to the issue i made before (#994). The answer there wasn't the solution for me which is why I am creating this issue.

I tried the solution in the referred issue but it is not working for me. Here is my setup:

For example i have a node with id "/branches" and one which is a child with id "/branches/Bug".
So I am trying your code like:
```javascript 
$('#treeview').jstree(true)._load_node(['/branches'], function () { //Also tried with # too
  this.select_node("/branches/Bug");
}); 
```

I receive an error like this: ```https://localhost:8443/ETLTool/serverInterface.jsp?childsForId=undefined 500 (Internal Server Error) ```

This is how i initialize my jstree : 
```javascript
	$("#treeview").jstree({
		"plugins": ["types", "wholerow","state"],		
		"types": {
			"folder": {
				"icon": "./images/folder.png"
			},
			"file": {
				"icon": "./images/file.png"
			}
		},


		"core": {
			"data": {
				"url": function(node) { 

					if($("#treeDatasourceSelect").val() == "SVN") {
						if (node.id === "#") {
							return showOnlyScripts ?  "serverInterface.jsp?getRootScripts=YES" 
									: "serverInterface.jsp?getRoot=YES";

						} else {
							console.log(node);
							return showOnlyScripts ? "serverInterface.jsp?scriptsForId=" + node.id
									:"serverInterface.jsp?childsForId=" + node.id;
							
						}
					}
					else {
						if (node.id === "#") {
							return"serverInterface.jsp?explorerRoot=YES";

						} else {
							return "serverInterface.jsp?explorerChildsForId=" + node.id;
							
						}
					}
				},
				"data": function(node) {
				
						return {
							"id": node.id
						}
					
					
				}
			}
		}
	});
	
```

What could also be interesting in order to find the mistake here is, that when i add and if statement to the url configuration like so:

``` if (node.id != undefined) {...}``` the error of course goes away but I am confronted with this error here:
```  Uncaught TypeError: Cannot assign to read only property 'children' of false ```

**Comment by vakata** [comment]
Try `_load_nodes` - it was a typo in the original answer, please keep the discussion in a single thread - I will reopen it if needed.
As for your data - there is something wrong with it - obviously there is no node with that ID. 

Best regards,
Ivan

**Comment by dehlen** [comment]
Just reporting that this solved the issue for me. It just was the missing s in the method name.. Damn javascript... :+1:
