### ISSUE TITLE
Error handling empty AJAX result

### ISSUE THREAD

**Issue by lhpderckx** [vakata/jstree#997]
In case of lazy-loading HTML data by using AJAX and the result is empty, jstree fails (jstree.js, _load_node line 1337. Error on "type.indexOf('json')" in the ajax.done handler: cannot read property 'indexOf' of null.

In my opinion, jstree should remove the "expand" icon and stop the loading animation, since the result actually means there's nothing within the chosen node.

Empty results can occur when:
- it is too 'expansive' server-side to check whether a node contains subnodes
- an error is made while checking for sub-nodes and the rootnode was falsely set as expandable.
- changes in the database have caused subnodes to not exist any more.
- ...

**Comment by vakata** [comment]
By default jstree will remove the closed icon and loading animation if you return an empty array (the correct way of specifying that the node has no children), it will also remove the loading animation and leave the node as closed if there is an error with the AJAX response (if it fails for some reason). 

Could you provide your empty server response along with the headers as I cannot reproduce this. Anyway - I think I resolved the issue with the above commit - my guess is your server returns a `200 OK` status, but no `Content-Type` header.

Best regards,
Ivan

**Comment by lhpderckx** [comment]
I checked the response header's content type. It is indeed not specified. Content-Length=0 and status is 200, OK.

So, I thought about how to set it... The url that is called to get the inner <ul> data returns a string. I tried setting Response.ConcentType and charset from my MVC project's controller, but it was not returned (still no content type in response header).

Actually, my situation is kind of similar to this, although I'm returning HTML and not Json:
http://stackoverflow.com/questions/15671679/jquery-ajax-response-type

This is how I initialize jstree:
    $('#treeview').jstree({
        'core': {
            'data': {
                'url': CatalogGeneratorTreeUrl,
                'data': function (node) {
                    var range = $('input[name=range]:checked', '#generatorForm').val();
                    return { 'chapterId': node.id, 'range': range };
                }
            },
            'themes': {
                'icons': false
            }
        },
        'plugins': ['checkbox']
    });

So, I'm not specifying the ajax functions myself; it is done by jstree. When I add 'dataType': 'html' to the jstree initialization, exactly how ajax expects it (http://api.jquery.com/jquery.ajax/). I can see it's in the 's' variable in jstree.js, line 1327, but it is still not picked up by ajax. Is there a way to set the content type in the jstree initialization, without specifying explicit ajax functions?

This is the latest jstree init that I have tested with (core data):
            'data': {
                'url': CatalogGeneratorTreeUrl,
                'data': function (node) {
                    var range = $('input[name=range]:checked', '#generatorForm').val();
                    return { 'chapterId': node.id, 'range': range };
                },
                'dataType': 'html'
            }

**Comment by lhpderckx** [comment]
By the way, the extra check on 'type' works; I'm just trying to do it neatly by setting a content type.
