### ISSUE TITLE
Please auto lefttrim HTML data results

### ISSUE THREAD

**Issue by lhpderckx** [vakata/jstree#998]
I'm composing HTML data results within an MVC application. The HTML data is composed by a view that starts with Razor statements.

It is followed by some checks and enumerations. It looks readable in the view with nice indentation and all; it is common to program that way.

The jstree can't handle that and it actually took me hours to find out why: the result doesn't start with &lt;ul&gt; directly, but with an enter and spaces. jstree.js fails in _load_node on line 1342 on $(d), where d is the response data. This must be a common 'mistake' and I would therefore please jstree to automatically ltrim indentation characters before &lt;ul&gt;, like carriage return, line feed, space and tab.

Please don't do it for me, do it for others as I will surely never make this 'mistake' again :smile:

**Comment by vakata** [comment]
There must be something other than white space in your code, jQuery will handle whitespace in the HTML string just fine (it is not a jsTree issue). I just tested with a lot of new lines, spaces and tabs. 

I am closing this for now, but maybe you can provide a sample of the code that triggered the error? If it is indeed only white space I will reopen and see what I can do.

Best regards,
Ivan

**Comment by lhpderckx** [comment]
Thank you for your immediate response :)

I have done the test again and I now explicitly added a space character before the first <ul>. These are the headers:
![image](https://cloud.githubusercontent.com/assets/10994752/6210029/b9d9f47e-b5cb-11e4-9c61-934490419a15.png)

This is the response data:
![image](https://cloud.githubusercontent.com/assets/10994752/6210044/e1c0e1b4-b5cb-11e4-90ea-0a1c6d785c2e.png)

This is the error:
![image](https://cloud.githubusercontent.com/assets/10994752/6210070/407e7860-b5cc-11e4-97b8-527f5ab2fd33.png)

As you can see from the last screeny, I'm running jquery 1.9.1. Please take my word on it that when I remove the leading space, it works fine.

I just tried using the latest jquery 1.11.2 and that works, so this is something that has been fixed in jquery already. Still, left-trimming all whitespace from within jstree won't hurt or you may recommend a jquery version later than 1.9.1 (i'm not sure in which version this was fixed) if that's not already the case.

**Comment by vakata** [comment]
Thanks for the testing - I did not try versions of jQuery older than 1.11.

I understand your concern, but I do not consider it a good practice to work around bugs from other libraries, especially when the bug has been fixed (I looked up into it - the bug was fixed a year ago in 1.10). It adds bloat, makes jstree itself bigger and harder to maintain.

BUT, when reading up on the bug, I understood it is safer to use `$.parseHTML()` than `$()`, which also takes care of the whitespace. I believe the `parseHTML` never had the whitespace issue, so 1.9.1 should be fine too.

Once again - thanks,
Ivan

**Comment by lhpderckx** [comment]
Hmmm.... parseHTML returns an array where all whitespace before the actual &lt;ul&gt; is seen as a 'text' element. I'm actually getting three elements now with whitespace before and whitespace after (an enter). The first element in the data array that is passed to _append_html_data is "text", the second "ul" and the third is "text" again. This causes an error (undefined is not a function) in _append_html_data on line 1414:
<pre>
var dat = data.is('ul') ? data.children() : data,
    par = dom.id,
    chd = [],
    dpc = [],
    m = this._model.data,
    p = m[par],
    s = this._data.core.selected.length,
    tmp, i, j;
</pre>

Here's a screenshot of the 'data' param:
![image](https://cloud.githubusercontent.com/assets/10994752/6211499/e2666c06-b5da-11e4-9c95-e4865105b406.png)

So, I have a few options:
- Use your original $(d) code and a jquery version > 1.10,
- Use any version of jstree and jquery, but see to it that I manually trim off all whitespace before and after.

Note that with this new code using parseHTML, users using jquery >= 1.10 and now also have whitespace before or after, they will start receiving errors.

I believe parseHTML is the safer option, but _append_html_data may then need to 'search' for the UL element in the array.

**Comment by lhpderckx** [comment]
For now, I'm getting around now by downgrading jstree to the one using just $(d) and upgrading jquery, but when jstree remains unchanged, it will cause problems for everyone that has whitespace before or after the ul, whether or not they're using jquery >= 1.10

**Comment by vakata** [comment]
Sorry about that, on it.

**Comment by vakata** [comment]
Fixed with the last commit (forgot to reference)
