### ISSUE TITLE
Prevent parent node being checked when children are checked but check children when parent is checked

### ISSUE THREAD

**Issue by hwdavies** [vakata/jstree#999]
Hi, I have included the checkbox plugin and have set three_state to false in order to prevent the parent node being checked when all child nodes have been checked.

However... I would still like the all child nodes to be selected when the parent node is selected...

Is there a way to achieve this? Any help would be greatly appreciated! Thanks!

"checkbox" : {
  "three_state" : false,
},

"plugins": ["checkboxes"]

**Comment by vakata** [comment]
Please read the docs on the `checkbox.cascade` option and use it in your config (while keeping `three_state` to false):
http://www.jstree.com/api/#/?q=cas&f=$.jstree.defaults.checkbox.cascade

My guess is you need to set `cascade` to `"down"`.

Best regards,
Ivan

**Comment by hwdavies** [comment]
Perfect, thank you!
